### ISSUE TITLE
Linebreaking issues with `flex: 0 1 auto;` [was: disable automatic 'linebreaks' with MathJax for specific formulas]

### ISSUE THREAD

**Issue by scaljeri** [mathjax/MathJax#1017]
I noticed that when automatic linebreaks is turned on 

    'HTML-CSS': {linebreaks: {automatic: true}}    

formulas rendered inside inline elements will get unwanted line breaks ( [DEMO](http://jsfiddle.net/Cfrrf/19/))

In my case I render formules as follows:

    element.html(html); // insert the html
    $timeout(function () { // timeout to make sure it is in the DOM
         MathJax.Hub.Queue(['Typeset', MathJax.Hub, element.get(0)], cb);
    });

Is it possible to disable linebreaks for specific formulas or for formulas rendered in inline elements? If not, this would be a nice feature to have!

**Comment by pkra** [comment]
It would be good to have more detaild information -- see https://github.com/mathjax/MathJax/blob/master/CONTRIBUTING.md#bug-reports (which btw shows up when you write a new issue).

Anyway, the issue seems to be less about inline elements but about flexbox. On FF35 MathJax interacts with flexbox by not line-breaking. On Chrome 39, MathJax seems to have trouble identifying the available space -- not sure if that's a browser bug or a MathJax one. We'll look into it.

Generally speaking, flexbox certainly adds an interesting challenge to line-breaking when `flex-grow: 0`. A positive `flex-grow` value can be a workaround.

This is mostly unrelated to the issue, but two more comments. First, MathJax only performs linebreaking on display-style equations -- and those will always render as block elements, not inline. So from an HTML perspective, it seems like bad practice to wrap a display-style equation in inline elements as this might lead to unexpected rendering. You could use inline-style equations instead (and if need be set `\displaystyle`) as a workaround here, too. Second, from an authoring perspective, instead of marking elements as "do not break", a better approach might be to author content so that it line-breaks well (granted, that's not always easy and might requires some creativity and this issue is mostly unaffected unless you forcefully prevent linebreaks). 

Anyway, adding some way to skip linebreaking (e.g., via `no-linebreak` class or data attribute) is an interesting feature request but should probably be filed separately.

**Comment by scaljeri** [comment]
Thanks a lot for the detailed explanation. display -and inline style equations are new for me. You say that MathJax only performs linebreaking on displaystyle equations, but if I add \displaystyle to the equation

    \displaystyle f(x) = 

no linebreak is applied anymore! [jsfiddle](http://jsfiddle.net/Cfrrf/20/)

So why did MathJax break `f(x) =` and not the equation above ? or isn't `f(x) =` an inline-style equation ? I'm confused

**Comment by dpvc** [comment]
In order to do line breaking, MathJax must know the width of the container element for the mathematics.  When that element "shrink wraps" to fit its contents, then MathJax may not able to determine the line breaking width properly.  Usually, it will get the width of the content before the math is rendered (i.e., the other text in the element, and the "preview" test, which is the original LaTeX).

Since the span in your example has no other text than the math itself, the line breaking width is based on the size of the TeX code itself.  Because "f(x)=" turns out to be shorter in the original font than in the math fonts, MathJax gets a shorter line breaking width than what it needs, and so must break the equation. When you insert the `\displaystyle` that makes the original text longer that the final typeset math, and so MathJax gets a line break width that indicates it doesn't need to break the line.

You might be able to resolve the problem by adding a minimum width to the elements containing math, so that the line breaking width won't be too small.

**Comment by dpvc** [comment]
For the record, neither jsfiddle demo had line breaking for me (both displayed as `f(x) = ` on one line.  But my default browser font is not the standard one, so may have produced a wider (untypeset) preview, giving it enough room not to break.  It may also be browser dependent, as the implementation of flex-box may vary.  I have not investigated that.

**Comment by scaljeri** [comment]
Thanks a lot for pointing this out! Now I understand, except for one last thing! which is when I display an equation inline, I still get a linebreak  ([JSFIDDLE](http://jsfiddle.net/Cfrrf/26/)) As mentioned above, Mathjax only performs linebreaking to displaystyled elements. What is it that I do wrong here ?

**Comment by pkra** [comment]
>  I still get a linebreak 

> What is it that I do wrong here ?

You're not doing anything wrong. MathJax does not perform the line-breaking, the browser does. This can lead to unexpected results because while MathJax implements most of the MathML linebreaking algorithm (i.e., has an understanding how to do line-breaking in mathematics), a browser will

**Comment by pkra** [comment]
Meh, accidental posting. I edited my previous comment.

**Comment by pkra** [comment]
@dpvc seems like Chrome is ingoring the `nobr` tag nowadays; time to switch to `white-space: nowrap`?

**Comment by scaljeri** [comment]
I'm using chrome but I do see the same behaviour in Safari en FireFox: Checkout the cross-browser  [DEMO](http://jsfiddle.net/Cfrrf/33/) including the `white-space: nowrap`

Are there any plans yet to replace the `nobr` tag because it is deprecated ?

**Comment by dpvc** [comment]
> As mentioned above, Mathjax only performs linebreaking to displaystyled elements.

That is not actually correct.  MathJax will break an inline element if it is wider than the line breaking width, so line breaking *can* occur in an inline element.  The is the same problem as above:  Because the spain containing the mathematics has width zero without the mathematics, MathJax thinks the line breaking width is 0, and so even in-line equations are being broken.

> seems like Chrome is ingoring the nobr tag nowadays; time to switch to `white-space: nowrap`?

MathJax already applies the explicit CSS

    .MathJax nobr {white-space: nowrap ! important}

so `white-space:nowrap` is already in place (as you can verify with the DOM inspector).  But the breaking is being done by MathJax, not the browser, so this setting is not the problem.  The problem is that MathJax doesn't know the correct line breaking size.

One solution would be to set an explicit line breaking width, e.g., use

    linebreaks: {
      automatic: true,
      width: "15em"
    }

in your configuration rather than a container-relative width (which is the default).  If course, you will want to specify an appropriate size for your layout.

**Comment by pkra** [comment]
Doh! Thanks for correcting me, @dpvc.

**Comment by scaljeri** [comment]
thanks a lot for explaining. Adding `with` to the linebreaks objects solves the issue for me!
