### ISSUE TITLE
Mathjax render a 33554432 height Div

### ISSUE THREAD

**Issue by devon** [mathjax/MathJax#1019]
It's 32M px height, and the width has a wrong size on this element, it's 0.047 x 33554432 on chrome(Mac):

```html
<span class="math" id="MathJax-Span-4" style="width: 0.001em; display: inline-block;">
    <span style="display: inline-block; position: relative; width: 0.001em; height: 0px; font-size: 126%;">
        <span style="position: absolute; clip: rect(10000003.955em 1000.001em -9999995.964em 9999999.88em); top: -3.994em; left: 0.001em;">
            <span class="mrow" id="MathJax-Span-5">
                <span class="mi" id="MathJax-Span-6" style="font-family: STIXGeneral-Italic;">
                    x
                    <span style="display: inline-block; overflow: hidden; height: 1px; width: 0.001em;">
                    </span>
                </span>
            </span>
            <span style="display: inline-block; width: 0px; height: 3.996em;">
            </span>
        </span>
    </span>
    <span style="border-left-width: 0.001em; border-left-style: solid; display: inline-block; overflow: hidden; width: 0px; height: 0.001em; vertical-align: -12599999.982em;">
    </span>
</span>
```

**Comment by pkra** [comment]
Could you provide a minimal example that exhibits the problem? 

MathJax uses several methods to detect the surrounding CSS context. The most common problem arises when MathJax encounters content with `display:none` when MathJax is forced to move the equation elsewhere before laying it out; if the heuristics choose an element with a very different CSS context, then this kind of thing will happen  -- see http://boolesrings.org/krautzberger/2014/07/12/mathjax-best-practices-avoid-displaynone/.  

But we need some context to determine where the issue lies.

**Comment by devon** [comment]
The first error I got when I trying to debug this error is in html-css/jax.js, toHTML function

```
var q = this.data[0].HTMLspanElement().bbox;
if (q.skew) {
   o.bbox.skew = q.skew
}
```

The q is null. HTMLspanElement exist, but bbox is undefined. 

Maybe it's not about this error, I will keep looking at the code.

**Comment by dpvc** [comment]
As Peter points out, you have not given enough information for us to assist you.  For example, you con't give your MathJAx configuration, or the original form of the mathematics that you are using, or any way for us to reproduce what you are doing, so it is impossible for us to investigate the problem.  We need that in order to help.

I'm wondering if you are rendering the math "off screen" in an element with "display:none" and then transferring the result to the visible part of the DOM using `innerHTML`.  If you do, that will certainly lose the bounding box information that was attached to the original DOM tree.

Finally, you should use the unpacked version of MathJax if you want to do debugging, as that is far more readable.  Add `unpacked/` before `MathJax.js` when you load it (so you have `.../unpacked/MathJax.js?config=...`).

**Comment by devon** [comment]
I already switch to unpacked version for debug a moment ago.

I understand it should be very helpful if I can write a simple page to reproduce the problem. But it's hard for me to do that, because the problem only occurs in a complicated situation. We use mathjax in an html editor, and there are a lot of js/css etc.

Yes, I copy the rendered equation data with `innterHTML`, but the original element is not `display:none`. It's a content editable DIV. We can double click the Div and edit the tex equation. MathJax will render the equeation when DIV lose focus.  `MathJax.Hub.Queue(["Typeset", MathJax.Hub, $element[0]]);`

```
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
    jax: ["input/TeX","output/HTML-CSS"],
    tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]},
    messageStyle: "normal",
    TeX: {
        MAXBUFFER: 100*1024, // Set size of buffer in bytes
    },
    imageFont: null,
    showMathMenu: false,
    skipStartupTypeset: true,
    showProcessingMessages: false
});
</script>
```

I'm new to MathJax, and I will trying to track down the root of the problem. You tips will be very helpful.

**Comment by devon** [comment]
Solve the problem. It's like #1014.

We cached the render data into database, and reload it when open the same document again. There are about three id for div/span when render s equation. And the id is not unique if we cache the old equation.

I modify all three GetID to uuid, everything works.

**Comment by pkra** [comment]
Thanks for the update; glad you could track this down.
