### ISSUE TITLE
MathML content not working in Chrome

### ISSUE THREAD

**Issue by bminano** [mathjax/MathJax#1041]
I have detected this issue after the latest version was released.
MathML content extension does not recognise the content tags, showing an error "Unknown node type:apply", but no error on the console. This behavior is shown in Chrome, Firefox seems to work properly.

With a local MathJax 2.4 the content is displayed as expected.

My configuration is the following:
Chrome version Versión 36.0.1985.125
Ubuntu 12.04.4 LTS

**Comment by pkra** [comment]
Thanks for the report. Can you provide a live sample (e.g., on jsbin etc) that exhibits the issue?

**Comment by bminano** [comment]
I created a sample at http://jsbin.com/kitavosuci/1/edit
It is a bit tricky. When the body loads a mathML content from a string is loaded as the child of a div.
Then an update is requested to MathJax. It works in my Firefox, but not in Chrome.
What I see is that the error ("Unknown node type:apply") is not shown, but the content is not rendered correctly.
I hope this could help.

**Comment by davidcarlisle** [comment]
If you change mt:math and /mt:math to lose the "mt:" then it works on
Chrome. The original content extension using xslt was basically immune to
the use of namespace prefixes as xslt normalises that all away, but that
was more or less an accidental side effect of the use of XSLT rather than
an intention to make prefixed elements work for html, in general in html
prefixed elements aren't  expected to work I think. (Note I'm not a mathjax
developer so I can't really speak to how far it's supposed to work now, but
I did contribute the original XSLT version, so can say something about how
come it used to work.)

**Comment by bminano** [comment]
Hi David,

You're right, it works without the prefix. What it is strange is that 
something happened in version 2.5 that changed the behaviour.
But I think it is a kind of bug, because it works on Firefox with 
prefixes, so maybe this is a browser problem.
And also it seems enough to remove the prefixes only for math element, 
and not the children.

On 03/02/15 13:10, David Carlisle wrote:
> If you change mt:math and /mt:math to lose the "mt:" then it works on
> Chrome. The original content extension using xslt was basically immune to
> the use of namespace prefixes as xslt normalises that all away, but that
> was more or less an accidental side effect of the use of XSLT rather than
> an intention to make prefixed elements work for html, in general in html
> prefixed elements aren't expected to work I think. (Note I'm not a mathjax
> developer so I can't really speak to how far it's supposed to work 
> now, but
> I did contribute the original XSLT version, so can say something about how
> come it used to work.)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mathjax/MathJax/issues/1041#issuecomment-72639991>.
>

-- 
--
Un saludo,
Borja Miñano
IAC3 - Universitat de les Illes Balears
Mateu Orfila Building. Office F-213.
Cra.Valldemossa km. 7,5 E-07122
Palma de Mallorca. Balears. Spain.
Phone: +34 971 173 000 ext. 1318

**Comment by pkra** [comment]
> What it is strange is that something happened in version 2.5 that changed the behaviour.

Not quite surprising. The extension was re-written from scratch for 2.5

> But I think it is a kind of bug, because it works on Firefox with prefixes, so maybe this is a browser problem.

I think that depends on your actual content. The jsbin sample was using HTML5 and so the namespace will lead to trouble. But assuming your actual content is xhtml this should be fine.

> And also it seems enough to remove the prefixes only for math element, and not the children.

I'm guessing MathJax isn't picking up the prefixed math element, and once it does, MathJax's own sanitization clears up the rest.

**Comment by dpvc** [comment]
As mentioned above, use of namespaces in HTML5 is a bit awkward.  It seems that browsers differ in how they treat the results.

David Carlisle's suggestion of removing the `mt:` from the `<mt:math>` and `</mt:math>` tags is one approach to the problem.  Another would be to add `xmlns:mt="http://www.w3.org/1998/Math/MathML"` to the `<html>` element, declaring that namespace for the document.  MathJax looks there for namespaces for MathML and will locate math elements tagged with those namespaces like yours.  But the namespace needs to be declared in the `<html>` tag for that to work automatically.

I also notice that your example parses the XML string, but ends up converting it back to a string in the end to be used with jQuery's `append()` function.  That certainly seems unnecessary in this example, but perhaps it is just because this is a simplified one.  But it seems to me that you could just pass your `xml` variable directly into `$("#A").append(xml)` and avoid all the XML parser complication.

**Comment by bminano** [comment]
Thank you for the information.
It is still a bit strange for me that works differently in different 
browser. Anyway, I will take it into account.

On 04/02/15 18:26, Davide P. Cervone wrote:
>
> As mentioned above, use of namespaces in HTML5 is a bit awkward. It 
> seems that browsers differ in how they treat the results.
>
> David Carlisle's suggestion of removing the |mt:| from the |<mt:math>| 
> and |</mt:math>| tags is one approach to the problem. Another would be 
> to add |xmlns:mt="http://www.w3.org/1998/Math/MathML"| to the |<html>| 
> element, declaring that namespace for the document. MathJax looks 
> there for namespaces for MathML and will locate math elements tagged 
> with those namespaces like yours. But the namespace needs to be 
> declared in the |<html>| tag for that to work automatically.
>
> I also notice that your example parses the XML string, but ends up 
> converting it back to a string in the end to be used with jQuery's 
> |append()| function. That certainly seems unnecessary in this example, 
> but perhaps it is just because this is a simplified one. But it seems 
> to me that you could just pass your |xml| variable directly into 
> |$("#A").append(xml)| and avoid all the XML parser complication.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mathjax/MathJax/issues/1041#issuecomment-72898260>.
>

-- 
--
Un saludo,
Borja Miñano
IAC3 - Universitat de les Illes Balears
Mateu Orfila Building. Office F-213.
Cra.Valldemossa km. 7,5 E-07122
Palma de Mallorca. Balears. Spain.
Phone: +34 971 173 000 ext. 1318

**Comment by pkra** [comment]
@bminano yes, it's a pain. The jsbin example is plain HTML5 (not xHTML) and so the output ends up invalid as HTML5 does not allow namespace prefixes and only a few namespaces like MathML and SVG.
