### ISSUE TITLE
IE9/10/11 webFont: 9 second load for most fonts

### ISSUE THREAD

**Issue by Loginisalreadytaken** [mathjax/MathJax#1043]
Error (might not be related to this issue):
CSS3117: @font-face failed cross-origin request. Resource access is restricted. (about:blank)

TeX: No error, quick load
STIX-Web: Error, quick load
Asana-Math: Error, **slow** load
Neo-Euler: Error, **slow** load
Gyre-Pagella: Error, **slow** load
Gyre-Termes: Error, **slow** load
Latin-Modern: Error, **slow** load

alert(MathJax.Message.Log()) says "Can't load web font..." but eventually they are loaded anyway.

See the page at http://foshin.com .Currently Latin-Modern is selected, but it behaves and looks about the same with all fonts that "load slowly".

**Comment by pkra** [comment]
Thanks for reporting. I can reproduce the issue. 

The CORS headers are fine btw. Perhaps this is another case of #950 .

**Comment by dpvc** [comment]
OK, it looks like the problem is in your configuration, where you have 

```
		"availableFonts": ["Asana-Math"],
		"preferredFont": "Asana-Math",
```

The `availableFonts` and `preferredFont` tell MathJax what *local* fonts to look for.  The `Asana-Math` font is a web font (a specially modified version of Asana for use with MathJax), and won't be available on anyone's local system, so there is no use in trying to check for it.  Apparently, IE is having trouble with the attempt, and it tries waiting for it to arrive, and times out after 10 seconds when it doesn't find it.  Then it loads the Latin-Modern font.

Changing these lines to

```
		"availableFonts": [],
		"preferredFont": null,
```

prevents MathJax from attempting to loco for local fonts at all, and so you get the Latin-Modern font directly.  The solves the problem for me.  It also solves the problem with the square roots from issue #1044, which I don't understand at all.  Apparently, the attempt to load the Asana font messing up wither MathJax or IE.  I will have to look into it further, but if you change the lines above, you won't need to apply the fix for the square roots.

**Comment by louy2** [comment]
http://setosa.io/ev/eigenvectors-and-eigenvalues/

I am getting CORS error on this page.

**Comment by pkra** [comment]
@louy2 I'm afraid I'm unable to reproduce any issues on FF48 / Win10 using your page (using saucelabs to test). You might want to provide more information (but please file a new issue since this one is IE specific).

**Comment by louy2** [comment]
@pkra 
Thanks for response. Before opening I rechecked and found that CORS is caused by HTTPS Everywhere blocking HTTP requests. It doesn't affect usage.

**Comment by pkra** [comment]
@louy2 glad you could figure it out. That's unfortunately outside MathJax's control.
