### ISSUE TITLE
IE9/10/11 webFont: "broken" square root lines

### ISSUE THREAD

**Issue by Loginisalreadytaken** [mathjax/MathJax#1044]
I use certain settings, like "matchFontHeight": false and adjust the font-size manually with CSS, but it makes no difference if I remove/change any.

Asana-Math, Gyre-Pagella, Gyre-Termes, Latin-Modern

See the page at http://foshin.com .Currently Latin-Modern is selected, but it behaves and looks about the same with all the fonts above.

**Comment by pkra** [comment]
Thanks for reporting this here. I can reproduce the issue. We'll investigate it.

**Comment by dpvc** [comment]
MathJax uses one of the characters in the font to create the horizontal rules.  It looks like the LatinModern font uses a combining character as its rule character, which is not a great idea, as combining characters are notoriously troublesome.  This seems to be the cause of the bad alignment of the lines for the square roots for the single-character roots.

Moreover, the characters used for the repeating parts when this character is stretched are stored in the private-use area (PUA) of one of the fonts (I'm not sure why), and IE seems to be having some trouble showing these.

My own test files show the square roots correctly for these situations, but I can confirm that your site does show them incorrectly.  That may be due to CSS issues.

One work around would be to change the character used as the rule character.  Unfortunately, nearly every horizontal character seems to be aliased to the combining character, and that makes things a bit more difficult.  The natural replacement is the minus sign at U+2122.  This is *not* aliased, but its extension characters are in the PUA, and don't show up.  Fortunately, the minus can be used as the extenders, and so you can fix up the data to make it work.

Here is one way:  add

``` html
<script type="text/x-mathjax-config">
MathJax.Hub.Register.LoadHook("[MathJax]/jax/output/HTML-CSS/fonts/Latin-Modern/fontdata.js",function () {
  var FONTDATA = MathJax.OutputJax["HTML-CSS"].FONTDATA;
  FONTDATA.RULECHAR = 0x2212;
  delete FONTDATA.DELIMITERS[0x2212].stretch.left;
  delete FONTDATA.DELIMITERS[0x2212].stretch.right;
  FONTDATA.DELIMITERS[0x2212].stretch.rep = [0x2212,"LatinModernMathJax_Main"];
});
</script>
```

to your page just before the script that loads MathJax.js itself.  This will arrange for the overline data to not use combining characters, which works for me.  See if it works for you.

**Comment by dpvc** [comment]
See #1043 for a problem with the configuration that seems to cause this.  If you fix the configuration, you won't need to use the patch given above.
