### ISSUE TITLE
TeX input: treat double quote as an ORD  [WAS: Extra space when Unicode symbols are followed by quotation marks]

### ISSUE THREAD

**Issue by gronostajo** [mathjax/MathJax#1045]
### Summary

This input:

```
← "b
```

Produces following output with CSS, fast HTML and SVG renderers:

![image](https://cloud.githubusercontent.com/assets/1347866/6045800/2f95a344-ac9d-11e4-9c64-d6797f39fd8b.png)

There's a space between quotation mark and letter in the output. Single quotes are affected too, but only with arrows:

![image](https://cloud.githubusercontent.com/assets/1347866/6045827/595f501c-ac9d-11e4-83cc-81bd1555772d.png)

Other Unicode symbols aren't affected:

![image](https://cloud.githubusercontent.com/assets/1347866/6045840/71bf196c-ac9d-11e4-998c-2977054cd97b.png)

"Pretty quotes" from Unicode aren't affected too.
### Steps to reproduce
1. Go to http://cdn.mathjax.org/mathjax/latest/test/sample-dynamic.html
2. Try rendering one of the following lines:

```
← 'b
← "b
↕ "b
↙ 'b
➔ 'b    (this one actually needs extra space)
➛ "b    (same here)
```

Pretty quotes work:

```
← ”b    (Unicode U+201D)
```

These work with single quotes, but not with double quotes:

```
♣ 'b
☃ 'b
```

![image](https://cloud.githubusercontent.com/assets/1347866/6046115/993a56d0-ac9f-11e4-98d6-178957e0bf6a.png)
### Browsers and versions

I've tested this in following browsers:
- Chrome 42.0.2288.6 dev-m (64-bit)
- Chrome 39.0.2171.99 (32-bit)
- Firefox 35.0.1
- Internet Explorer 11.0.9600.17501

MathJax versions:
- 2.3
- 2.5
- possibly other versions too

**Comment by dpvc** [comment]
For the most part, the results you are getting are correct.  The only ones that aren't are the ones with the standard double-quote (U+0022), and not because there is space between the quotation mark and the b that follows, but because there isn't space between the arrow and the quotation mark.

In TeX, the amount of spacing between adjacent characters is determined by the "class" of the two characters.  For example, a binary operator like `+` gets some extra space when it is between two letters, but a relation like `<` gets a little more space.  The TeX classes are ORD (for *ordinal*, like regular letters), OP (for *operator*, like sums), BIN (for *binary operator*, like `+`), REL (for *relation*, like `<`), OPEN (for *opening delimiters*, like open brackets), CLOSE (for *closing delimiters*, like close brackets), PUNCT (for *punctuation*, like commas), and INNER (for things like fractions).

TeX's arrows are of class REL, so they get the largest amount of space, and so `\leftarrow b` would have space between the arrow and the b.  The single quote is a special character that produces prime notation, and in TeX, it produces a special superscript that is the prime character.  Superscripts and subscripts embellish a character without changing its spacing.  So `\leftarrow ' b` would produce an arrow with a prime (with no intervening space) followed by the b separated by REL spacing.  That is exactly what you picture in your first image above, and is the correct rendering since your unicode arrow U+2190 is treated as `\leftarrow`.

In your second image, however, the cloverleaf gets class ORD (as does the b), and there is no extra space between characters of type ORD.  The prime does not affect the spacing, since it just embellishes the first character (the cloverleaf).  So there should be no extra spacing in this case, and that is exactly what your image shows.  Similarly for your snowman, which is also class ORD.

MathJax uses a table to look up the TeX classes for the various characters that you enter.  Because MathJax is intended for mathematical typesetting, its tables include mathematical symbols, but not the many other possible unicode characters, like your snowman.  When it encounters those, it assigns them TeX classes based on the Unicode block in which they fall.  For example, the "Arrows" block from U+2190 to U+2200 gets class REL, while the General Punctuation block from U+2000 to U+206F gets class PUNCT.  Most blocks get class ORD, and that includes the Dingbats at U+2700 to U+27BF, which is where your cloverleaf and snowman are found.

The last two arrows from your list in step 2 above are also in the Dingbats block, so are given class ORD.  Although it would have been possible to treat these as arrows of class REL, these are not mathematical arrows, but dingbats, so don't have the same meaning as mathematical arrows, and were classed as ORD instead.  That is why the spacing is different for them than for the other mathematical arrows that you tried.  You are correct to say that they don't have enough space between the arrow and the quotation mark, however.  That is because these characters are not in MathJax's fonts, and so MathJax doesn't know the true bounding boxes for these characters (it only has data about the characters that are in its own fonts).  These characters are found by your browser in some other font that is installed on your system, and MathJax doesn't know what that is.

In v2.5, MathJax no longer tries to measure the widths of the various characters that it uses, relying on its internal measurements instead (the measuring process was an significant speed bottleneck).  This works well in general, but unknown characters like this is one place where measuring was helpful.  If you want to be more accurate with unknown characters like this, you can re-activate the measuring process by setting the `noReflows` value in your configuration (see the example at the bottom of this message).

MathJax's list of TeX classes for the various characters is based on the MathML [operator dictionary](http://www.w3.org/TR/MathML3/appendixc.html).  The TeX classes are obtained heuristically from the spacing, properties, and form listed in the operator table.  For example, characters that are marked as "fence" in the table are given class OPEN if they have a prefix form and CLOSE if they have a postfix form.  In the case of the "pretty" close quote, this character gets class CLOSE (it is a fence in postfix notation).  There is no extra space between a REL and a CLOSE or between a CLOSE and an ORD, so you get the spacing that you see in your example.

That only leaves the ones with U+0022 (double quote).  TeX treats this as an ORD, which would put space between the left-arrow and the quotation mark, and no extra space between the quotation mark and the b.  But MathJax incorrectly assigns it class REL.  TeX puts no extra space between two REL characters, so MathJax has the arrow next to the quotation mark with no space between, but there is space between a REL and an ORD, so MathJax puts space between the quotation mark and the b.  It should be the other way around (space before the quotation mark, and none after).

TeX has commands to let you alter than class of a symbol, so you could use `\mathord{"}` to get the spacing around the quotation mark correct.  You could also add the following

	<script type="text/x-mathjax-config">
	MathJax.Hub.Register.StartupHook("mml Jax Ready",function () {
	  MML.mo.prototype.OPTABLE.postfix['"'] = MML.mo.OPTYPES.ACCENT;
	});
	</script>

to your page just before the script that loads MathJax.js itself.  That would define the data for the double quote properly.

If you want to get the Dingbat arrow widths correct, add

	<script type="text/x-mathjax-config">
	MathJax.Hub.Config({
	  "HTML-CSS": {
	    noReflows: false
	  }
	});
	</script>

as well.

**Comment by dpvc** [comment]
The double quote problem is resolved in v3.
