### ISSUE TITLE
Different sized parentheses in \binom or \choose

### ISSUE THREAD

**Issue by asgerix** [mathjax/MathJax#1053]
When I insert a binomial coefficient in an equation array like this:

\begin{eqnarray} C & = & {n \choose k} \\ \end{eqnarray}

The first parenthesis is rendered smaller than the second.

**Comment by dpvc** [comment]
Thanks for the report.  This is due to a problem with the way the `eqnarray` environment (and similar ones) try to arrange for the spacing at the beginning of the second and later columns interacting badly with the implementation of `\mathchoice` that is used by `\choose` and similar macros.

This is fixed in the `issue1053` branch of my fork of MathJax.

**Comment by dpvc** [comment]
A reduced test case is

``` latex
\begin{eqnarray} & {n \choose k} \end{eqnarray}
```
