### ISSUE TITLE
MathJax incompatible with rem scaling

### ISSUE THREAD

**Issue by aahdahl** [mathjax/MathJax#1056]
Hello,

We are running MathJax2.5 and have found that when styling the "span" element with "scale=<any number>rem" (eg:
span {
  font-size: 0.9rem;
}
), MathJax seems to be unable to calculate the size of the text in the formula. Therefore the text sometimes overlap parentheses etc.

**Comment by pkra** [comment]
Could you create a live sample, e.g., using codepen, jsbin etc, which exhibits the problem? Please also try to provide more detailed information on your setup (see https://github.com/mathjax/MathJax/blob/master/CONTRIBUTING.md#bug-reports).

**Comment by sectokia** [comment]
I had a similair issue, but I am not sure its anything to do with MathJax because it happens on the browsers that don't support rem in the first place.

*Summary*
When using 'rem' css font size, then zooming the browser, elements can over lap (on browsers that don't support rem?)

*Steps to reproduce*
1. Make sure browser zoom is 100%.
2. Open this HTML below in browser.
3. Wait for math to render.
4. Zoom in using browser (CTRL+mouse wheel up/down or zoom menu).
5. Observe the last bracket starts overlapping and/or touching the text.

*Example HTML*
```HTML
<!DOCTYPE HTML>
<HTML><HEAD><TITLE>TEST</TITLE>
<script src='https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=AM_HTMLorMML-full'></script>
<STYLE>span {font-size: 0.9rem;}</STYLE>
</HEAD><BODY><span>Hello World`(asdf)(a+3)`Hello World</span></BODY>
</HTML>
```

*Version*
I have only tried on:
MathJax: latest
Chrome 27.0: The right barcket overlapps H in hello world.
IE8.0: The right bracket touches the H at some zoom levels.

**Comment by dpvc** [comment]
MathJax reserves space for the math using units of ems (which are font-size relative).  Its determination of the em-to-pixel ratio is done empirically, and is subject to some inaccuracy.  That is very sensitive to the scaling, and the em-to-pixel value for one zoom level doesn't necessarily carry over to others perfectly.  So there are sometimes artifacts like the ones you are experiencing when you zoom.  Reloading the page at the zoomed magnification should produce the proper spacing.

These effects depend both on the operating system, the font size, and the browser in use.  Since you are asking about IE8, I assume you are using Windows XP; these inconsistencies are more noticeable in that setting than in more modern operating systems.  For example, I am not able to reproduce the problem in Windows 7 with Chrome or IE, and do not see them in Mac OS in Chrome.

Microsoft ended support for Windows XP in April 2014, and Chrome is dropping Windows XP in April 2015.  MathJax is considering dropping support for IE8 as well.  I'm afraid that if you are restricted to that environment, you may find problems of this sort inevitable.

**Comment by sectokia** [comment]
I get the problem on Win7 enterprise SP1 with IE 8.0.7601 and Chrome 27.0.1453.

It's hard to get rid of IE8 support because it's the default and most widely used browser for windows 7 in enterprise and even academic institutions :-(, as its bundled with Win7.

Either way I do not think it is a problem worth worring about. Hardly no one uses REM when you do use REM it doesn't work on IE8 or Chrome <30 anyway.

So it's really up to the user to not use REM if they want zooming to work on older browsers that don't support REM.

**Comment by aahdahl** [comment]
Hey, thanks for the responce. Unfortunatly we have to support IE8 and above. We have also tried this on IE9 and 10, and the same issue is experienced. And it does not seem to be related to zooming, as the initial renderin displays these artifacts, and refreshing does not remove them.

**Comment by dpvc** [comment]
@aahdahl, does sectokia's example file above cause the problem for you?  Are you also using Windows 7?  I don't have that old a version of Chrome to test on, but haven't been able to reproduce the problem in IE10 or current versions of Chrome.  I do see the result I describe above for IE10 in IE8 Standards document mode (but not IE9 or IE10 modes).  That is, it only affects zoomed results, and reloading at the new zoom level corrects the problem.

Also, this really has nothing to do with rem units *per se*.  It just has to do with the size of the font in the element that contains the math.  So I get the same results, for example, using 

``` html
<!DOCTYPE HTML>
<HTML><HEAD><TITLE>TEST</TITLE>
<script src='https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=AM_HTMLorMML-full'></script>
</HEAD><BODY><span style="font-size:0.9em">Hello World`(asdf)(a+3)`Hello World</span></BODY>
</HTML>
```
where the sizing for the span is in em rather than rem.

It is probably not a good idea to style the base span element, as MathJax uses them internally all over the place.  (E.g., styling `span {font-size:0.9em}` would cause lots of problems for MathJax.)  Can you use a span with a class and style the class instead?  If not, perhaps

``` html
<style>
.MathJax span {font-size: inherit}
</style>
```

would help.
