### ISSUE TITLE
support for tensor (left) indices

### ISSUE THREAD

**Issue by quantenschaum** [mathjax/MathJax#1059]
Is there support for tensor indices on the left of the symbol, like provided by the [tensor package](http://www.ctan.org/tex-archive/macros/latex/contrib/tensor), [leftidx package](http://www.ctan.org/pkg/leftidx) or [mathtools prescript](http://www.ctan.org/pkg/mathtools)?

**Comment by pkra** [comment]
No, but implementing those would be straight forward to implement since one can use multiscripts.

FWIW, the supported core macros are documented at http://docs.mathjax.org/en/latest/tex.html and third party extensions are at https://github.com/mathjax/MathJax-third-party-extensions. If somebody is interested, creating a third party extension is probably the best way to start.

**Comment by dpvc** [comment]
The mathtools package is available now in v3.
