### ISSUE TITLE
v2.5+ and IE9 MathPlayer issues

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1074]
Moving https://github.com/mathjax/MathJax-website/issues/25 here.

There are issues with the MathPlayer handshake, noticeable on www.mathjax.org and math.stackexchange.com

**Comment by NSoiffer** [comment]
I tried to look at things from the MathPlayer to get some ideas. I used IE11 and compatibility modes and they seem to replicate what Steve saw (2.3 works, 2.5 doesn't). Using that...

IE8 emulation works, IE9 doesn't on a local MJ page grabbing the latest MJ. In IE9, the math briefly displays correctly, and then displays (twice) as just the characters.

I tried it with and without the BHO enabled and the results were the same. The BHO detects MJ and doesn't process the body, but it does try to add the <?import ...> statement to attach the namespace to the object tag. For reasons I don't understand, the call to get the namespaces in the document fails when MJ is there (i.e., the script to load MJ is in the head) and works fine when it isn't. It fails even on the onemathematicalcat.org pages which render fine and look to be MJ 2.2.

I've included what the developer tool says is in the DOM for the IE9 and IE8 modes below (I omitted the MJ style info that was added to the head for IE8).  I see three differences of note:

1.  IE8 has an object tag in the head -- I added it to the page and reloaded and it didn't help.
2.  IE8 has an import tag in the body. I tried adding that and a object tag to the body. It didn't help, but it wasn't in the DOM either.
3.  IE8 adds the mml prefix. I modified the BHO to run and add the prefix, but that didn't help -- MJ removed it. I doubt this is the problem though because the BHO doesn't modify the MathML to add a prefix and it displays ok when MathJax isn't there.

I remain baffled as to what MJ is doing that is causing MP to fire and then rewrite the page in such a way as it isn't rendering anymore.


====================== DOM ================
```html
IE 9 -- mj
<html lang="en" xmlns:m = "http://www.w3.org/1998/Math/MathML" XMLNS:[default] http://www.w3.org/1998/Math/MathML = "http://www.w3.org/1998/Math/MathML"><head>
  <meta charset="UTF-8">
<title>2-Point Form</title>
<!-- Copyright (c) 2009-2011 Design Science, Inc. -->

  <script src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" type="text/javascript">
  </script><object id="mathplayer" classid="clsid:32F66A20-7614-11D4-BD11-00104BD3F987"></object>


<style type="text/css"></style><style type="text/css"></style><style type="text/css"></style><style type="text/css"></style><style type="text/css"></style><style type="text/css"></style><style type="text/css"></style></head><body><div id="MathJax_Message" style="display: none;"></div>
<p>This content is from Wikipedia's entry on linear equations</p>
<h4>Two-point form</h4>
<p>
<object id="[default] http://www.w3.org/1998/Math/MathMLPlayer" classid="clsid:32F66A20-7614-11D4-BD11-00104BD3F987"> </object> 
 
<span style="text-align: center; display: block;"><span class="MathJax_Preview"></span><div class="MathJax_MathML" id="MathJax-Element-1-Frame"><span class="MathJax_MathContainer" style="display: inline-block; white-space: nowrap; position: relative;"><span style="display: inline-block;"><math display="block" xmlns="http://www.w3.org/1998/Math/MathML" style="display: inline-block; cursor: pointer;"><mrow><mi>y</mi><mo>−</mo><msub><mi>y</mi><mn>1</mn></msub><mo>=</mo><mfrac><mrow><msub><mi>y</mi><mn>2</mn></msub><mo>−</mo><msub><mi>y</mi><mn>1</mn></msub></mrow><mrow><msub><mi>x</mi><mn>2</mn></msub><mo>−</mo><msub><mi>x</mi><mn>1</mn></msub></mrow></mfrac><mo>(</mo><mi>x</mi><mo>−</mo><msub><mi>x</mi><mn>1</mn></msub><mo>)</mo><mo>,</mo></mrow></math></span></span></div><script id="MathJax-Element-1" type="math/mml"><math style="display: inline-block; cursor: pointer;" display="block" xmlns="http://www.w3.org/1998/Math/MathML">
<mrow><mi>y</mi><mo>−</mo><msub><mi>y</mi><mn>1</mn></msub><mo>=</mo><mfrac><mrow><msub><mi>y</mi><mn>2</mn></msub><mo>−</mo><msub><mi>y</mi><mn>1</mn></msub></mrow><mrow><msub><mi>x</mi><mn>2</mn></msub><mo>−</mo><msub><mi>x</mi><mn>1</mn></msub></mrow></mfrac><mo>(</mo><mi>x</mi><mo>−</mo><msub><mi>x</mi><mn>1</mn></msub><mo>)</mo><mo>,</mo></mrow>
</math></script></span>
</p>
</body></html>
```

IE8 -- mj
```html
<HTML lang=en xmlns:m = "http://www.w3.org/1998/Math/MathML" XMLNS:[default] http://www.w3.org/1998/Math/MathML = "http://www.w3.org/1998/Math/MathML"><HEAD><TITLE>2-Point Form</TITLE>
<META charset=UTF-8><!-- Copyright (c) 2009-2011 Design Science, Inc. -->
<SCRIPT src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" type=text/javascript>
  </SCRIPT>

<OBJECT id=mathplayer classid=clsid:32F66A20-7614-11D4-BD11-00104BD3F987></OBJECT>
</HEAD>
<BODY>
<DIV id=MathJax_Message style="DISPLAY: none"></DIV>
<P>This content is from Wikipedia's entry on linear equations</P>
<H4>Two-point form</H4>
<P>
<OBJECT id="[default] http://www.w3.org/1998/Math/MathMLPlayer" classid=clsid:32F66A20-7614-11D4-BD11-00104BD3F987></OBJECT><SPAN style="TEXT-ALIGN: center; DISPLAY: block">
<DIV class=MathJax_MathML id=MathJax-Element-1-Frame><SPAN class=MathJax_MathContainer style="WHITE-SPACE: nowrap; POSITION: ; DISPLAY: inline-block" isMathJax="true" jaxID="NativeMML"><SPAN style="DISPLAY: inline-block" isMathJax="true"><SPAN style="TEXT-ALIGN: center; DISPLAY: block"><?import namespace = m urn = "http://www.w3.org/1998/Math/MathML" implementation = "#MathPlayer" /><m:math style="CURSOR: pointer; DISPLAY: inline-block" display="block" xmlns="http://www.w3.org/1998/Math/MathML" isMathJax="true"><m:mrow isMathJax="true"><m:mi isMathJax="true">y</m:mi><m:mo isMathJax="true">−</m:mo><m:msub isMathJax="true"><m:mi isMathJax="true">y</m:mi><m:mn isMathJax="true">1</m:mn></m:msub><m:mo isMathJax="true">=</m:mo><m:mfrac isMathJax="true"><m:mrow isMathJax="true"><m:msub isMathJax="true"><m:mi isMathJax="true">y</m:mi><m:mn isMathJax="true">2</m:mn></m:msub><m:mo isMathJax="true">−</m:mo><m:msub isMathJax="true"><m:mi isMathJax="true">y</m:mi><m:mn isMathJax="true">1</m:mn></m:msub></m:mrow><m:mrow isMathJax="true"><m:msub isMathJax="true"><m:mi isMathJax="true">x</m:mi><m:mn isMathJax="true">2</m:mn></m:msub><m:mo isMathJax="true">−</m:mo><m:msub isMathJax="true"><m:mi isMathJax="true">x</m:mi><m:mn isMathJax="true">1</m:mn></m:msub></m:mrow></m:mfrac><m:mo isMathJax="true">(</m:mo><m:mi isMathJax="true">x</m:mi><m:mo isMathJax="true">−</m:mo><m:msub isMathJax="true"><m:mi isMathJax="true">x</m:mi><m:mn isMathJax="true">1</m:mn></m:msub><m:mo isMathJax="true">)</m:mo><m:mo isMathJax="true">,</m:mo></m:mrow></m:math></SPAN></SPAN></SPAN></DIV>
<SCRIPT id=MathJax-Element-1 type=math/mml><math style="CURSOR: pointer; DISPLAY: inline-block" display="block" xmlns="http://www.w3.org/1998/Math/MathML"><mrow><mi>y</mi><mo>−</mo><msub><mi>y</mi><mn>1</mn></msub><mo>=</mo><mfrac><mrow><msub><mi>y</mi><mn>2</mn></msub><mo>−</mo><msub><mi>y</mi><mn>1</mn></msub></mrow><mrow><msub><mi>x</mi><mn>2</mn></msub><mo>−</mo><msub><mi>x</mi><mn>1</mn></msub></mrow></mfrac><mo>(</mo><mi>x</mi><mo>−</mo><msub><mi>x</mi><mn>1</mn></msub><mo>)</mo><mo>,</mo></mrow> </math></SCRIPT>
</SPAN></P>
<BLOCKQUOTE></BLOCKQUOTE></BODY></HTML>
```

**Comment by dpvc** [comment]
@NSoiffer, I have finally gotten the chance to look into this, and think I have some more information to add.  I downloaded MathPlayer4 beta and tried it with IE9 on Windows 7.  I got similar results to yours.  

> I remain baffled as to what MJ is doing that is causing MP to fire and then rewrite the page in such a way as it isn't rendering anymore.

I think what you are seeing is MathJax's new Fast Preview, not MathPlayer.  My experiments suggest that MathPlayer is not being triggered, but the Fast Preview does show the math temporarily and then it is replaced by the native MathML, which doesn't render.

Further experimenting indicates that when MathJax used `document.createElementNS()` to create the math elements, MathPlayer does not get triggered, but if MathJax creates elements named `<m:math>` (after setting up the namespace, which it does), that *does* trigger MathPlayer.

This seems to work in IE9 in all emulation modes, and it does seem to work in IE11 in IE7 mode, but I can't seem to find how to enable Enterprise mode in IE11.  The on-line documentation sends me to use the Group Policy Editor to modify the Internet Explorer settings, but the required "Use Enterprise Mode" item is not listed for me (perhaps I need to update).  Without Enterprise mode, MathJax's attempts to set up MathPlayer lead to crashes.  So I can't really test it in IE11.

Can you try out the following file in IE11 Enterprise mode and see if that works?

``` html
<!DOCTYPE html>
<html>
<head>
<title>Test MathPlayer4 in IE9 and IE11</title>
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  "CHTML-preview": {disabled: true}
});
MathJax.Hub.Register.StartupHook("NativeMML Jax Ready", function () {
  var MML = MathJax.ElementJax.mml,
      HUB = MathJax.Hub;
  MML.mbase.Augment({
    NativeMMLelement: function (type) {
      var math = (HUB.Browser.mpNamespace ? document.createElement("m:"+type) :
                                            document.createElement(type));
      math.isMathJax = true;
      return math;
    }
  });
});
MathJax.Hub.Queue(function () {
  var BROWSER = MathJax.Hub.Browser;
  var output = document.getElementById("output");
  output.innerHTML = 
    "Has MathPlayer: "+(BROWSER.hasMathPlayer ? "Yes" : "No")+"<br>" +
    "MathPlayer Imported: "+(BROWSER.mpImported ? "Yes" : "No")+"<br>" +
    "MathMML Namespace: "+(BROWSER.mpNamespace ? "Yes" : "No")+"<br>" +
    "createElementNS: "+(document.createElementNS ? "Yes" : "No")
});
</script>
<script src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

</head>
<body>

<p>
\[x = \frac{-b\pm\sqrt{b^2-4ac}}{2a}\]
</p>

<div id="output">
</div>

</body>
</html>
```

If it doesn't work, can you tell me what the data at the bottom of the page indicates?  (It should list some yes/no values for four different values.)  Thanks.

**Comment by dpvc** [comment]
The proposed fix is in the `issue1074` branch of my fork of MathJax.

**Comment by dpvc** [comment]
=> Merged.

**Comment by NSoiffer** [comment]
My apologies for not getting back to you sooner. I didn't see this email
until more emails in thread showed up for some reason...

It did work for me and gave the values:
Has MathPlayer: Yes
MathPlayer Imported: Yes
MathMML Namespace: Yes
createElementNS: No

I'm not sure local pages give the same test as remote ones, but on the
other hand, I don't know that they don't.

Using enterprise mode:
With MathPlayer installed, "Enterprise Mode" should show up in the IE Tools
menu. This is because MP writes a key into the registry that turns on the
menu item. MS in their wisdom apparently decided users should not be able
to turn it on for local pages though, so if you open a local page, you need
to use the developer tools to turn it on (which is what I did for your
example).

    Neil

**Comment by dpvc** [comment]
Thanks for the update, and the info on Enterprise mode.  I'm glad that this helped.  I have merged the change into the develop branch.

Davide
