### ISSUE TITLE
Improve font-fallback behavior

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1077]
Implement a better font-fallback behavior. When a character is not covered by the primary font, use a secondary font (e.g., STIX) that includes the necessary glyph.

Might even help resolve #919, #795, #497 and #316

**Comment by sammarshallou** [comment]
Sorry this is not a very helpful contribution but just to comment that I came across this today when trying to figure out why the apE entity didn't work for me in MathML, and it would be really great if a fallback could be implemented.

Personally I was initially a bit taken aback since I'd read the documentation page about MathML support that said it supports 100% of characters which I had assumed meant everything in the MathML entitity lists at the spec; I don't think it mentions that this only applies if you select a (non-default) font... :)

**Comment by dpvc** [comment]
> I'd read the documentation page about MathML support that said it supports 100% of characters

I can't find the reference to that.  Can you point it more specifically out so it can be fixed?

**Comment by sammarshallou** [comment]
Sorry. I'm not sure the MathJax documentation is actually wrong in any way, it just perhaps wasn't where I expected! May be user error...

http://docs.mathjax.org/en/latest/mathml.html

Has a list 'Supported MathML commands' which under 'Deficiencies' does not mention any character limitations.

This then links to W3C test suite results (so it's not your documentation at all) http://www.w3.org/Math/testsuite/results/tests.html - under 'Characters' this says '100%'. if you look in the detail at the top, which I didn't look at previously, you can see that in the configuration they set it to use STIX-Web.

The current behaviour IS accurately documented on this page:
http://docs.mathjax.org/en/latest/font-support.html

So I guess what confused me is seeing the '100%' test suite result without noticing that this only applies when selecting the STIX font.

**Comment by dpvc** [comment]
I don't think that passing the test suite means that every character is available in the MathJax fonts.  It means that MathJax properly processes the unicode values and typesets them so that they will be displayed if an appropriate font is available.  Since unicode specifies hundreds of thousands of characters, no font is going to cover all of them, and the default MathJax fonts certainly don't.  The STIX fonts cover a much larger range (though certainly not all of unicode either).

That being said, better documentation of the exact coverage of the different web fonts MathJax makes available would clearly be a good thing.

**Comment by sammarshallou** [comment]
Oh, I see. To clarify, I certainly don't expect it to work with every Unicode character - I had (very likely incorrectly, as you say) assumed that the test suite meant they checked the list of defined entities in the MathML standard, which is 'only' thousands rather than hundreds of thousands...

**Comment by pkra** [comment]
Thanks for commenting, @sammarshallou. Fonts and Unicode coverage is a messy topic. Just like browsers themselves, we are to limited by the fonts on the system; providing webfonts is one way of working around this but it cannot solve all problems. The argument for passing those tests is that MathJax does the best it can with Unicode points not covered by the fonts. Additionally, for the longest time, MathJax had to work around broken browser implementations where Unicode support beyond the BMP was erratic. I don't really know a succinct way of improving the documentation, but I've created https://github.com/mathjax/MathJax-docs/issues/106

Note to self: the OP does not adequately describe the complexity of the existing fallback mechanisms and which kinds of improvements we have in mind here.
