### ISSUE TITLE
how to set the TeX/mhchem.js version to 3

### ISSUE THREAD

**Issue by a358003542** [mathjax/MathJax#1083]
the mhchem package version 3 is add more features like:

\ce{0.5H2O} , right now the dot symbol is interpret as the dot beside the crystal water in complex compound  .

the in-math environment  \ce{$A$}

and the bond command .

**Comment by dpvc** [comment]
The MathJax mhchem extension was developed from mhchem v3.10, so it is already version 3.  From the change log in the documentation  for v3.19 (the current version as of this writing), there seem to be four changes that are not in MathJax's version:

1.  The addition of `\bond{1}`, `\bond{2}` and `\bond{3}`,
2.  The use of decimal numbers as in your example above,
3.  The use of a distance after line breaks, as in `\\[10pt]`,
4.  A change in the way that super- and subscripts are laid out (staggered rather than directly above one another).

The extension already processes dollar signs within `\ce`, as in `\ce{$A$}`, but in MathJax `\ce` can only be used within math mode, so you would need to use `\(\ce{$A$}\)` no just `\ce{$A$}` by itself.

For 1 above, you can use `\bond{-}`, `\bond{=}` and `\bond{#}` (or some other forms as well).  For 2, you can use `\ce{$0.5$H20}` as a work-around.

If you want to add these features to the mhchem extension, you could modify the [mhchem.js](https://github.com/mathjax/MathJax/blob/master/unpacked/extensions/TeX/mhchem.js) file and make a pull request to have your fixes included in the official version.  The first two would be straight-forward to add.  The third would snot be hard.  The fourth would take a little more work, but is also not too hard.

**Comment by a358003542** [comment]
thanks , that is very helpful.

**Comment by mhchem** [comment]
This is the author of the original mhchem LaTeX package. I will create a JavaScript parser for mhchem in 2016 that should yield more compatibility between LaTeX and MathJax.

**Comment by mhchem** [comment]
The current version of mhchem.js support all the things mentioned here, like $\ce{0.5 H2O}$. See https://mhchem.github.io/MathJax-mhchem/ or examples.
This issue can be closed.

**Comment by pkra** [comment]
> This issue can be closed.

Hm. Tricky since this issue is so old and so much has happened since. 

While the original question can now be answered ([positively](http://docs.mathjax.org/en/latest/tex.html#mhchem)), we have not yet made the new version the default and do not ship it alongside the core  (given the amount of breaking changes). 

I would be ok with closing this issue and opening a new one to track the planned change in MathJax v3 (to default to the new mhchem).

**Comment by dpvc** [comment]
MathJax v3 now uses the current version.
