### ISSUE TITLE
output of expression (with unicode chars) overlaps with following text 

### ISSUE THREAD

**Issue by iwinux** [mathjax/MathJax#1086]
## Summary

The TeX expression `$A、P、D、B$四点共圆，$AB$所对圆心角的度数是$90°$` is rendered incorrectly in MathJax 2.5. I guess the unicode character (Chinese, actually) `、` causes the problem - if I replace it with comma `,`, everything is all right.

The following screenshots demonstrate the problem.

### 2.4-latest - correct

![dynamic_preview_of_textarea_with_mathjax_content](https://cloud.githubusercontent.com/assets/98864/6568932/a64888a6-c71b-11e4-8a97-89bcc8b8be35.png)

### 2.5-latest - incorrect

![dynamic_preview_of_textarea_with_mathjax_content](https://cloud.githubusercontent.com/assets/98864/6568939/e1da4102-c71b-11e4-83be-4aedd486b5eb.png)

Not sure what changes in 2.5 cause this. Any ideas?

## Technical Details

* MathJax: [2.5-latest](https://github.com/mathjax/MathJax/tree/v2.5-latest)
* OS: OS X 10.10.2
* Browser: both Google Chrome 41.0.2272.76 (64-bit) and Mozilla Firefox 35.0

**Comment by FuGardenia** [comment]
中文兼容性不好👎

**Comment by FuGardenia** [comment]
啥时候修复此bug？

**Comment by liaofeng** [comment]
:+1:

**Comment by NanoJeoMichael** [comment]
same problem

**Comment by iwinux** [comment]
Also reproduced in develop branch:

![dynamic_preview_of_textarea_with_mathjax_content](https://cloud.githubusercontent.com/assets/98864/6569295/c291d920-c722-11e4-93bc-010b7749ff37.png)

**Comment by shenfei** [comment]
same problem +1

**Comment by pkra** [comment]
Thanks for the report. We'll look into it.

**Comment by dpvc** [comment]
This is due to the use of U+3001 (IDIOGRAPHIC COMMA) within the math.  This is not a character that MathJax has in its fonts, so it is an "unknown" character.  MathJax v2.4 did a lot remeasuring of the elements as it typeset, but that has a significant performance penalty.  So v2.5 eliminated that (for the most part) in order to speed things up.  We added some of those back in v2.5.1, but it appears that that wasn't sufficient for your case.

If you add

    MathJax.Hub.Config({
      "HTML-CSS": {
        noReflows: false
      }
    });

to your configuration block, that should provide the v2.4 measuring behavior, which should resolve the problem for you for now.

**Comment by iwinux** [comment]
@dpvc Thanks! I'll try it later. 

BTW: is there any configuration to make such chars "known"? I've tried the following

```javascript
MathJax.Hub.Config({
  'HTML-CSS': {
    // all kinds of Chinese fonts
    undefinedFamily: "'Microsoft YaHei', 'Hiragino Sans GB', 'WenQuanYi Micro Hei', STXihei, SimHei, sans-serif",
  },
})
```

but it doesn't seem to help.

**Comment by dpvc** [comment]
MathJax needs more than just the name of a font where the character can be found.  MathJax's font data files include information about the bounding box of the characters (among other things), so that information would need to be available to MathJax before it could handle the characters properly.  So what you have done does tell MathJax what fonts to suggest to the browser for finding the characters, it doesn't give MathJax the information to use those character precisely.  The `noReflows` solution is the only real option at this point.

**Comment by dpvc** [comment]
The issue should be resolved by commit b8a48d9cd7c2ebec0ca26aa1ef7f5aa2a7f62275 that resolves #1158.

**Comment by iwinux** [comment]
@dpvc I'd test it later. Thanks for all your help :+1:

**Comment by dpvc** [comment]
@iwinux, if you want to test against the commit listed above, you should probably use the `hotfix-2.5.2` branch, as it includes a second related fix that may help with your use of characters that are outside of the MathJax fonts.
