### ISSUE TITLE
STIX-Web font data for stretchy integral is incorrect

### ISSUE THREAD

**Issue by dpvc** [mathjax/MathJax#1092]
The integral is marked as a horizontal stretchy character rather than a vertical one, so integrals don't stretch properly for STIX-Web.  This affects both HTML-CSS and SVG.  The local STIX font doesn't include the integral as stretchy at all (even though it could).

**Comment by pkra** [comment]
(From the User Group posting)

The MathJax fonts don't include the needed characters to make a stretched integral sign, so the integral is not one of the characters that MathJax will stretch.  The STIX-Web font does include the needed characters, so you could switch to that font.  Unfortunately, there is an error in the data for the stretchy integral in that font, so you would need to include some configuration to fix that.  You could put

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  "HTML-CSS": {fonts: ["STIX-Web"]},
  "SVG": {fonts: ["STIX-Web"]}
});
(function () {
  function FixStretchyIntegral(renderer) {
    var FONTDIR = "[MathJax]/jax/output/"+renderer+"/fonts/STIX-Web";
    MathJax.Hub.Register.LoadHook(FONTDIR+"/fontdata.js",function () {
      MathJax.OutputJax[renderer].FONTDATA.DELIMITERS[0x222B].dir = "V"; 
    });
    MathJax.Hub.Register.LoadHook(FONTDIR+"/fontdata-extra.js",function () {
      var FONTDATA = MathJax.OutputJax[renderer].FONTDATA;
      FONTDATA.DELIMITERS[0x222B].dir = "V";
      FONTDATA.DELIMITERS[0x222B].stretch.ext = FONTDATA.DELIMITERS[0x222B].stretch.rep;
    });
  }
  FixStretchyIntegral("HTML-CSS");
  FixStretchyIntegral("SVG");
})();
</script>

in your file just before the script that loads MathJax.js itself.  That will correct the data when the font data files are loaded, so that stretchy integrals will stretch properly.

**Comment by dpvc** [comment]
The `font-fixes` branch of my fork of MathJax fixes this.

**Comment by dpvc** [comment]
==> Merged.

**Comment by dpvc** [comment]
==> In testsuite

MathMLToDisplay/Characters/issue1092.html
