### ISSUE TITLE
Meta: dealing with HTML5 fragments

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1128]
From the backlog.
- handle foreign content better (#487)
- tolerate HTML in mtext elements
- switch from XML to HTML parser
  - sanitize stray HTML nodes (e.g., plain text) into mtext elements
    - probably useful as a separate htmltidy-like library.

**Comment by pkra** [comment]
Possibly useful (to use or contribute to) https://github.com/cure53/DOMPurify

**Comment by dpvc** [comment]
Wrapping stray text into `<mtext>` elements should be easy to do.  Allowing non-text inside token elements is more work, but should be done, as `<mglyph>` and `<malignmark>` are supposed to be allowed there now, but currently aren't.

**Comment by pkra** [comment]
A bit academic for now, but in HTML5 we can get some funky things to validate, e.g., including a complete math tag in an mtext element.

**Comment by pkra** [comment]
> Allowing non-text inside token elements is more work, but should be done, as <mglyph> and <malignmark> are supposed to be allowed there now, but currently aren't. 

I'm not following.

**Comment by pkra** [comment]
And hit post comment by accident.

Is that related to MathML or HTML fragments?

**Comment by dpvc** [comment]
> I'm not following.

I meant to say that even though the spec allows `<mglyph>` inside `<mtext>` and other token elements, for example, MathJax doesn't always handle this correctly.  Any correct handling is accidental at this point, and there are lots of places where MathJax assumes that the contents of token elements is only text.  As part of the ability to allow arbitrary HTML inside token elements, all of those places will have to be fixed.  I was mostly saying that we need to do that anyway, since the MathML spec already includes a couple of cases where that is allowed, but noting that it is not isolated to one or two places, but will require a general cleanup of how that is handled.

**Comment by pkra** [comment]
Ah! Thank for the additional information!
