### ISSUE TITLE
placement of braces with \mathscr vs. \scr and other codes

### ISSUE THREAD

**Issue by orangeplanet** [mathjax/MathJax#1134]
The placement of braces in MathJax appears to make a difference in \mathscr vs. \scr, \mathfrak vs. \frak, and \mathcal vs. \cal.   See https://jsfiddle.net/4nfo1joa/
 
It looks as thought \scr has to be encased in outer grouping braces to contain it properly: {\scr P}.  If it isn't set up this way, then all the lowercase letters that follow in the string come out as Roman and all the uppercase letters inherit the script.  \scr{P} doesn't keep the target isolated the way {\scr P} does.   The same pattern occurs with \mathfrak vs. \frak.  Almost the same thing happens with \cal: if it isn't coded as {\cal P}, then all the uppercase variables inherit the calligraphic setting, but the lowercase variables go to italic. 

Is this expected behavior for these commands or a bug?

**Comment by pkra** [comment]
I thought that's expected behavior but I admit I don't know how one usually does `\scr` in actual TeX.

@dpvc ?

**Comment by dpvc** [comment]
These are how those macros are supposed to work.  The macros like `\cal` (and `\rm`, `\bf`, `\it`, etc.) are Plain TeX macros, which work as switches:  they change the current font until another change is made.  In contrast, the macros `\mathcal` (and `\mathrm`, `\mathbf`, `\mathit`, etc.) are LaTeX macros, and they take arguments that are typeset in the given font.  In Plain TeX, one does `{\cal P}` to get a calligraphic "P", while in LaTeX it is `\mathcal{P}`.

In the early days of TeX, computers war much slower, and passing arguments incurred a certain performance cost, so many Plain TeX marcros work like these switches .  Typesetting large sections of text in a particular font by passing the text as an argument would have been prohibitively slow.  Nowadays, this is no longer a concern, but in the late 1970's, that was important.

There is also a technical issue concerning the timing of when TeX decides what category reach input token belongs to.  This is done when the token is first parsed, and that means that when an argument is passed to a macro, all the category codes have already been set for the tokens in the argument.  Since some macros work by changing the way category codes are assigned, using arguments could disrupt the ability of this macros to function.  So macros that may work over large sections of text (like font changes) are better handled by *not* using arguments.  This usually doesn't affect mathematical expressions, which are relatively short, but since `\rm`, `\bf`, etc., are used for text as well as mathematics, their use as switches rather than macros taking arguments was a reasonable decision.

When LaTeX was built on top of TeX, Lamport tried to normalize the syntax somewhat, and moved to arguments for everything, for consistency.  Bur the original Plain TeX macros are supported in MathJax, as well as the newer LaTeX ones.
