### ISSUE TITLE
MathJax on Github pages wont display after I installed the link in the head

### ISSUE THREAD

**Issue by csrgxtu** [mathjax/MathJax#1138]
hi, I am using MathJax on my github blogs [csrgxtu](http://csrgxtu.github.io), and I included the cdn  of mathjax, and write down some math symbols, upload the page to github, and it wont display, please check [Writing Mathematic Fomulars in Markdown](http://csrgxtu.github.io/2015/03/20/Writing-Mathematic-Fomulars-in-Markdown/). I am using Google Chrome browser in Ubuntu 14.04, and it just display the latex source code of the math symbols.

**Comment by pkra** [comment]
The inline configuration block has to come before MathJax is loaded; otherwise MathJax starts up without being configured to use `$` as delimiters. Removing the first script tag pointing to MathJax should do the trick.

(You can also remove the `MathJax.Hub.Queue (...)` part in the inline block; it doesn't do anything for your page.)
