### ISSUE TITLE
Add support for stmaryrd

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1143]
- Add support for the actual font
- Add TeX macros from the stmaryrd package.

**Comment by pkra** [comment]
The TeX macros could easily start as a third party extension right away.

**Comment by Jean-Abou-Samra** [comment]
One special case is integer interval brackets, which have double bars, resembling `[[𝑎,𝑏]]` or `[| a, b|]`
In `stmaryrd`, these are provided as `\llbracket` and `rrbracket`. They can be mimicked using `[\![a, b]\!]` but it looks ugly in subscripts.
They are somewhat special since they are the only commands in `stmaryrd` that can work with \left and \right (see the [documentation of stmaryrd](http://mirrors.ircam.fr/pub/CTAN/fonts/stmaryrd/stmaryrd.pdf)). Since they are more common than the other symbols contained in this package, I would humbly suggest to make them available in the base package.

**Comment by dpvc** [comment]
@Jean-Abou-Samra, we will be working on expanding the font support in MathJax v3 during this coming summer.  That will make it easier to top the things you are asking for.

**Comment by contradictioned** [comment]
Sorry to dig this up, but is stmaryrd really supported? Especially w.r.t. \llbracket and \rrbracket I didn't manage to get this running.

**Comment by pkra** [comment]
>  is stmaryrd really supported?

No it isn't (though I have a draft for a third party extension somewhere that could become open source).

Much of the St Mary Rd font is covered by Unicode nowadays so with a good font (e.g., v4) you can just map them to Unicode positions. E.g., https://github.com/AmerMathSoc/mathjax-unicode-math does a ton of that, including llbracket, rrbracket.

**Comment by contradictioned** [comment]
Ok, thanks for the clarification :)

**Comment by pkra** [comment]
Happy to help. Feel free to ping me by email to see if I can get the extension into a publishable state.
