### ISSUE TITLE
Mathml renders to Unexpected text node: ' '

### ISSUE THREAD

**Issue by lovesh** [mathjax/MathJax#1149]
I have the following MathML code
```html
<math>
 <mrow>
  <mo stretchy='false'>(</mo><mn>3</mn><mo>+</mo><mi>i</mi><mo stretchy='false'>)</mo><mtext>&#x00A0;(z</mtext><mo>+</mo><mtext><mover accent='true'>
   z
   <mo>&#x00AF;</mo>
  </mover>
  )&#x2013;(2</mtext><mo>+</mo><mtext>i)&#x00A0;(z&#x2013;<mover accent='true'>
   z
   <mo>&#x00AF;</mo>
  </mover>
  )&#x00A0;</mtext><mo>+</mo><mtext>14&#x00A0;</mtext><mi>i</mi><mo>=</mo><mn>0</mn><mo>,</mo><mtext>&#x00A0;&#x00A0;then&#x00A0;</mtext><mi>z</mi><mover accent='true'>
   <mi>z</mi>
   <mo>&#x00AF;</mo>
  </mover>
  </mrow>
</math>
```
This gives a `Unexpected text node: ' '`. I verified it here http://cdn.mathjax.org/mathjax/latest/test/sample-dynamic-2.html

**Comment by davidcarlisle** [comment]
The input isn't valid to the mathml dtd/schema, you have mover inside mtext.

**Comment by dpvc** [comment]
The MathML is invalid in other ways as well.  For example, the first and second `z` need to be enclosed in something like `<mi>...</mi>`.  That is the "text node" that MathJax is talking about, since the enclosing tag for the `z` is `<mover>`, and that is not a token element, so can't have children that are plain text.

**Comment by lovesh** [comment]
@davidcarlisle @dpvc Thanks
