### ISSUE TITLE
Windows 10 meta-issue (especially IE and Project Spartan / Microsoft Edge)

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1150]
For those testing out the Windows 10 preview, please add observations here.

While we mostly do not address issues in unreleased software, we will track how issues progress (on both ends).

* MathML related problems in Spartan and IE. 
  * [fixed by Spartan/Edge] mml2jax seems to have trouble. The basic MathML test does not run; no error in the console; `MathJax.Message.log()` lists the config and the fontdata but gets me a "attached page has modified the eval function. script diagnostics might not work correctly". 
  * Examples with MathML in custom-script tags work fine.

**Comment by dpvc** [comment]
I just tried the Windows 10 preview, and didn't have any trouble with the `mml2jax` extension using the MathML example on  the CDN.  Are you still having trouble with it?

**Comment by pkra** [comment]
> Are you still having trouble with it?

Yes, I still see this with the MathML sample from the CDN. 

Do you have the Windows Preview with Project Spartan installed? I had to manually activate the "fast updates" to get the update to the Preview that ships Project Spartan. Not sure if it became the default in the mean time.

MathJax loads and after manually adding MathML in a script element, queuing `Typeset` works (for that script element).

**Comment by dpvc** [comment]
OK, you were right, I didn't have a late enough version.  It didn't seem to have a way to update the preview version, however, so I had to install a fresh copy from build 10049.  After a few crashes, I was able to get it running, and test with Project Spartan.

The issue is with how MathJax checks for math elements with namespaces while trying not to add the same element that it got when it looked for math tags without namespaces.  It expects the namespace versions to have namespace prefixes, but Spartan only finds `<math xmlns="http://www.w3.org/1998/Math/MathML">` via `getElementsByTagNameNS()` (whereas other browsers also find it via `getElementsByTagName()` directly), and in that case the prefix is empty.  So I need to alter the way MathJax avoids duplicates from these two calls.

**Comment by pkra** [comment]
> So I need to alter the way MathJax avoids duplicates from these two calls.

I would hold off on that until Spartan is closer to a release.

**Comment by dpvc** [comment]
OK.  Should this be removed from the v2.6 milestone, then?

**Comment by pkra** [comment]
Spartan has been renamed to Microsoft Edge; I updated the title of the issue.

On the bright side, the issue with mm2jax seems fixed.

**Comment by pkra** [comment]
I cannot reproduce this issue anymore so I'm guessing this was fixed in Edge before its release.
