### ISSUE TITLE
Remap | in STIX font data [was: "Bad alignement of \vert"]

### ISSUE THREAD

**Issue by ergever** [mathjax/MathJax#1154]
When typing `$\vert x \vert$` the vertical line is align to the baseline and according to TeX this should be lower.
See an example here: http://jsfiddle.net/AqDCA/541/

**Comment by pkra** [comment]
Hm. I'm not seeing anything unusual in that sample (i.e., it matches TeX behavior for me). Can you share a screenshot and more details on your system (browser, OS versions etc.).

**Comment by ergever** [comment]
Sorry, I didn't test other browser:
* on ubuntu 14.04 with firefox 37.0.1 -> bad align:
![firefox](https://cloud.githubusercontent.com/assets/11850607/7044426/9bb25702-ddf3-11e4-8a80-2eca830fb084.png)
* on ubuntu 14.04 with chromium 41.0.2272.76 -> bad align:
![chromium](https://cloud.githubusercontent.com/assets/11850607/7044434/b50d7f56-ddf3-11e4-8a1a-9e0d25f052ed.png)
* windows 7 with IE11 or chrome 41.0.2272.118 or firefox 31.5.0 -> OK:
![explorer](https://cloud.githubusercontent.com/assets/11850607/7044458/e84b9786-ddf3-11e4-8d86-03861bbea2ee.png)

This is with the latest MathJax from github and the default.js configuration.
Thanks you for your interest in this bug.

**Comment by ergever** [comment]
By installing on ubuntu the packages fonts-mathjax* the correct font for | is used and the behavior is as expected. I thought that MathJay download automatically the woff fonts as needed but it's apparently not the case!

**Comment by pkra** [comment]
re-opening since this is definitely a bug. Can you tell us which version of the STIX fonts you have installed on your system?

**Comment by dpvc** [comment]
The vertical line character "|" in the stix fonts doesn't descend below the baseline, so when the STIX fonts are used, absolute values look like the ones in your first two images.  The third one shows the MathJax web font, in which the vertical line does extend below the baseline.  You have the STIX fonts installed locally on your ubuntu machine, but not on the Windows machine, which accounts for the difference in font choice.  MathJax will use the locally installed STIX fonts in preference to the web fonts (for performance reasons), unless you change the configuration to prevent that.  On the other hand, it will use locally installed MathJax fonts in preference to local STIX fonts, which is why it changed when you installed the MathJax fonts locally.  MathJax only uses web-based fonts if you don't have either MathJax or STIX fonts installed locally.

See the discussion on the [MathJax User's Forum](https://groups.google.com/d/msg/mathjax-users/MNPKV_6Hy28/FtjuyWSvIp4J) for a work-around if you are managing your own pages.

**Comment by dpvc** [comment]
@pkra, I'm not sure I'd call it "definitely" a bug, as as whether the vertical line descends below the baseline is a font-design decision.  There is nothing that says absolute values must look like they do in the TeX fonts (though I do prefer it that way myself).

**Comment by pkra** [comment]
@dpvc yes, sorry. I should've written "I want to understand what's going on" -- thanks for clarifying.

**Comment by dpvc** [comment]
We can think about whether we should make the remapping indicated in the link I gave above be the default (if he character is used in an `<mo>`).  I'm not sure.

**Comment by ergever** [comment]
OK thank you for the explanation and the workaround, now I understand what's going on.
The vertical bar of the STIX fonts is definitely buggy: in a pdf generated by LaTeX this is the \big version of \vert which is a bug! But that's another story.

**Comment by pkra** [comment]
@dpvc we could record it but we should probably wait for STIX 2.0 to come out

**Comment by pkra** [comment]
renamed and added to font milestone.

**Comment by dpvc** [comment]
The `font-fixes` branch of my fork of MathJax includes a patch that swaps the variant form (which has a descender) and the normal form (which doesn't).

**Comment by dpvc** [comment]
==> Merged.

**Comment by dpvc** [comment]
==> In testsuite

MathMLToDisplay/Characters/issue1154.html
