### ISSUE TITLE
Show Braille... Option 

### ISSUE THREAD

**Issue by larsvoigt** [mathjax/MathJax#1164]
Do you plan to support [show braille](https://www.dessci.com/en/products/mathplayer/manual.htm#show_braille) option from the native mathplayer 
to show braille math code Nemeth or Marburg in future version of mathjax? 
Is it technically possible to realize that in general?

Thanks Lars

**Comment by pkra** [comment]
I'm not exactly sure what you're after.

If you're asking whether MathJax can generate Nemeth/Marburg etc Braille, then the answer it no (at least right now). Since our internal format is MathML, this would require a converter from MathML to Braille. If there's a JavaScript (or some other transpilable language) MathML-to-Braille converter out there, it would probably be easy to add one. The only one I'm aware of is Natbraille and I don't know how useful it would be for this.

If you're asking whether MathJax could expose Braille that's already been generated, then annotaxion-xml is probably the way to go, at least for the "Show Math" menu anyway; for other forms of exposure, this would require #938 to be resolved.

**Comment by NSoiffer** [comment]
MathPlayer's "show braille" option isn't really useful for than demos -- it displays the dots on the screen that would be sent to a refreshable braille display. That's useless for someone who is blind.

MathPlayer makes use of the open source liblouis library, but that's not in JS and is windows-only, so there's problems there for hooking up with MathJax. Also, you'd need to write drivers for the various refreshable devices. I don't know how much work that is, but it probably isn't too bad. Whether it can be done with JS in a browser though is not clear (is writing to a device an option or is that outside the sandbox?)

**Comment by larsvoigt** [comment]
Sorry for my late response. Thanks for your time @pkra @NSoiffer and your helpful information.
Now its clear that to migrate this feature is a difficult technical problem and perhaps unnecessary.
I forgot to say thank you for mathjax!

**Comment by pkra** [comment]
@larsvoigt could you clarify what you were actually after? I'm tending towards leaving this open as a feature request -- if I understand what the actual request is :-)
