### ISSUE TITLE
Configuration issue which leads to render problems

### ISSUE THREAD

**Issue by scaljeri** [mathjax/MathJax#1167]
I have the following MathJax configuration:

    MathJax.Hub.Config({
                  tex2jax: { inlineMath: [['$','$'],['\\(','\\)']] },
                  displayAlign: 'left',
                  messageStyle: 'none',
                  showMathMenu: false,
                  showProcessingMessages: false,
                  skipStartupTypeset: true,
                  extensions: ["tex2jax.js", "mml2jax.js", "asciimath2jax.js"],
                  jax: ["output/HTML-CSS", "input/TeX", "input/MathML", "input/AsciiMath"],
                  'HTML-CSS': {
                      availableFonts: [],
                      linebreaks: {automatic: true},
                      preferredFont: null, // force Web fonts
                      webFont: 'STIX-Web'
                  }
              });

As far as I know, I load all the extensions I need, but for the following LaTeX formula I get an Error

    x=0\phantom{\rule{5px}{0ex}}\vee \phantom{\rule{5px}{0ex}}x=1\frac{1}{3}

The error is:

    Undefined control sequence \rule

Here is a [Demo](http://jsfiddle.net/AqDCA/551/). I found out that it matters how I load MathJax. When I get the error MathJax is loaded as follows:

    http://cdn.mathjax.org/mathjax/latest/MathJax.js?delayStartupUntil=configured

Now, when I change this to

    http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML-full

It works as expected ([DEMO](http://jsfiddle.net/AqDCA/552/))
What I would like to know is what exactly goes wrong when I get the error. Is this expected behaviour ? And how should I change my configuration to solve this error ?

**Comment by dpvc** [comment]
MathJax does not implement the `\rule` control sequence (though it has its own non-standard `\Rule` macro that is similar).  So both versions are invalid from MathJax's perspective.  The difference between the two configurations is that the `TeX-AMS-MML_HTMLorMML-full` configuration includes the `noUndefined` extension, which allows undefined macros to be rendered as the macro name in red (without producing an error message). That is why the second one succeeds in producing output.  But it is **not** the output you are actually expecting

If you use the MathJax contextual menu (you will need to re-enable it in your configuration) to view the source as MathML code, you will see

``` html
<mphantom>
  <mtext mathcolor="red">\rule</mtext>
  <mrow class="MJX-TeXAtom-ORD">
    <mn>5</mn>
    <mi>p</mi>
    <mi>x</mi>
  </mrow>
  <mrow class="MJX-TeXAtom-ORD">
    <mn>0</mn>
    <mi>e</mi>
    <mi>x</mi>
  </mrow>
</mphantom>
```

which is the `\rule` in red followed by the `5px` and `0ex` rendered literally.  The `\phantom` prevents that from being displayed, but it is there.  That is why the spaces are so much wider than 5px.

Since you appear to be wanting spaces (not actually rule lines) why not just use `\hskip 5px` or `\hspace{5px}` instead?

**Comment by scaljeri** [comment]
Thanks a lot for pointing this out. This solved the issue. I get formulas from a third party, so I have to find out what they are actually trying to do, but now I can actually see the formula!!

**Comment by dpvc** [comment]
OK, great.  I'm closing this issue, then.
