### ISSUE TITLE
mlabeledtr and minlabelspacing implementation

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1190]
I'm not sure what the spec wants the effect of `minlabelspacing` to be and I'm not sure what our implementation is trying to do.

More generally, I don't (fully) understand how our `mlabeldtr` implementation works. I think we're following the spec's ["suggestion" (fourth paragraph)](http://www.w3.org/Math/draft-spec/chapter3.html#id.3.5.3.1) -- is that correct @dpvc? 

However, I also don't fully understand that "suggestion" (e.g., is the "shift down" just referring to matching the row the label is labelling?). In particular, I don't understand what the spec's "suggestions" would suggest when the row+label are too wide for the mtable's container (overlap? shift away? shift where? outside the table?).

Anyway, it looks like MathJax adds the space from `minlabelspacing` to both sides of the "inner" mtable (by which I mean the mtable/mtr without the label). Naively reading spec I would have expected that `minlabelspacing` defines the minimal amount of space that guaranteed to be added between the label and the row it's labelling. In particular, I would only have expected space to be added one one side label.

**Comment by dpvc** [comment]
I think you are right that `minlabelspacing` is supposed to be the minimum distance between the label and the actual table.  MathJax actually puts this space on both sides of the label so that it can be used on either side of the table.

The suggestion seems to be the fourth paragraph, not the third (the third says the label doesn't count in centering, which is not a suggestion).

We do not follow the suggestion, which wouldn't actually work as described.  What we actually do is put the table in a container that is `width:100%` and the label is put in a box with `position:absolute`, so it effectively adds no width to the equation (and can overlap it).  To prevent overlap, the `min-width` of the container for the table is set to accommodate the equation and the label (and the `minlabelspacing`). 

How that works depends on the alignment of the table.  If it is aligned to the left or the right,  (`displayAlign` is `"left"` or `"right"`, or the `<math>` tag has `indentalign="left"` or `\indentalign="right"`),  then the `min-width` is set to the table width plus the width of the label plus twice the `minlabelspacing` (since that is added on both sides of the label).

If the table is centered (`displayAlign` is `"center"` or the `<math>` tag has `indentalign="center"`), then *twice* the label width and *four* times the `minlabelspacing` is added.  As I describe in #957, this is required in order to keep the equation centered.  Because the equation is centered, in order to force a space of size *x* on the right, you need an equal space of *x* on the left, so you need to add twice the minimum space needed for the label and its spacing.  This does mean that there will be wasted space on the side of the equation without the label, but that can't be helped if you want the equation to be centered.

**Comment by dpvc** [comment]
In terms of the "shifting down", they mean that when there isn't enough room for the table and the label together (as in the examples where we currently get overlapping), then the label should be placed *below* the equation it labels.  E.g., 

```
+--------------------------------+
|  equation that is really long  |
|                        (label) |
+--------------------------------+
```

We do not do this, and I don't see a good way to have it do this automatically when you resize the window.  (It could be set up that way if the initial size is too small, I guess, but would not reformat when the window is made larger.)

**Comment by dpvc** [comment]
I'm not sure what the "spec limitation" refers to.  Does the "Needs documentation" mean we need to document the fact that MathJax doesn't implement the spec suggestion?  Or that it doesn't make the distinction between `side` set to `right` compared to `rightoverlap`?

**Comment by pkra** [comment]
Thanks for all of this! 

RE `minlabelspacing`. 

Would you say the current behavior is a bug? (I.e., should we track it as such).

RE spec reference

Thanks. I edited my OP to say "fourth paragraph".

RE spec vs our implementation.

That was mostly what I was after -- thanks!

RE the shift down. 

I had thought that as well but re-reading the spec I wasn't sure anymore. Maybe I should ask the WG ;-) I would agree that we don't have to do this but could do it the way you describe. I'm not sure the user experience would be very good with the shift actually (e.g., with linebreaking it could easily get confusing). 

Re spec limitation

For lack of a better tag since I didn't understand where the issue lies. But I guess it is a limitation that the spec does not specify this.

Re needs documentation

I want to document the current behavior since it's left open by the spec.

**Comment by dpvc** [comment]
> RE `minlabelspacing`: Would you say the current behavior is a bug?

The only part that I consider a bug is the `minlabelspacing` being on both sides of the label.  That could certainly be handled differently for left and right alignment.

> I had thought that as well but re-reading the spec I wasn't sure anymore.

The "suggestion" really only deals with the special case where the table is centered, and doesn't actually work even then unless the label is made to be width 0.  it is also only for the case where `side` is `left` or `right`, not the overlap variants, which are the ones that I find most confusing.  The only description is the in the table of attributes for `<mtable>` just above the section you link to, and it says:

> The variants "leftoverlap" and "rightoverlap" are useful when the table fits with the allowed width when the labels are omitted, but not when they are included: in such cases, the labels will overlap the row placed above it if the rowalign for that row is "top", otherwise it is placed below it.

I had originally thought that the overlap versions would mean what we are currently seeing (label overlaps the equation), but this sounds like the labels is still placed below (or above) the row, and the difference is in whether that puts extra space between the rows to accommodate the moved label or not.  I'm not sure how useful that is, but I suppose that if the next (or previous) line is very short, it might be possible to put the label there without overlapping the math.  But then it would look like the label is on the *next* (or previous) row, so I'm not sure how that helps.

> Maybe I should ask the WG

Sure, why not?

> with linebreaking it could easily get confusing

Yes, mixing line breaking with equation numbers seems fraught with danger.

> I guess it is a limitation that the spec does not specify this.

OK, that's fine.

> I want to document the current behavior since it's left open by the spec.

OK.

**Comment by pkra** [comment]
Closing in favor of https://github.com/mathjax/MathJax-docs/issues/159.
