### ISSUE TITLE
linebreaking problem with repetitive fractions on math.SE

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1198]
[Reported on meta.stackexchange](http://meta.stackexchange.com/questions/257540/math-stackexchange-com-s-design-breaks-when-entering-long-mathematic-formulae#).

[Sandbox example on math.SE](http://meta.math.stackexchange.com/questions/370/formatting-sandbox/20657#20657) but reproducible; affects HTML-CSS and SVG output).

Seems like we should be able to do something about it?

**Comment by dpvc** [comment]
The MathML spec allows line breaks only at `<mo>` elements or `<mspace>` elements (or within token elements).  Because the TeX input jax does not insert invisible times `<mo>` elements automatically (since it would need a semantic understanding of the underlying mathematics to do so), the expression has no valid breakpoints.  The semantic enrichment we are currently doing would insert the needed nodes.  Short of allowing breaks at locations not indicated in the spec, I don't see how to improve the result.

**Comment by pkra** [comment]
Thanks for the background! Will think about it some more.
