### ISSUE TITLE
\genfrac fails with some delimiters (again)

### ISSUE THREAD

**Issue by PeterLuschny** [mathjax/MathJax#1199]
As I already reported in #1033 \genfrac fails with some
delimiters with 2.5-latest which work with 2.4-latest.

Some examples: http://luschny.de/temp/bugs.html

**Comment by dpvc** [comment]
OK, it is the dot delimiter that is failing (the other delimiters from 1033 have been fixed).  The dot fails because it returns an empty delimiter, and a test for the existence of the delimiter was failing because it was empty.  It will be fixed in the next release.  In the meantime, you can use

``` html
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: {Augment: {
    Parse: {
      GetDelimiterArg: function (name) {
        var c = this.trimSpaces(this.GetArgument(name));
        if (c == "") return null;
        if (c in TEXDEF.delimiter) return c;
        TEX.Error(["MissingOrUnrecognizedDelim","Missing or unrecognized delimiter for %1",name]);
      }
    }
  }}
});
</script>
```
just before the script that loads MathJax.js itself to fix the problem.  Alternatively, you can use `{}` rather than `{.}` for the empty delimiter.

**Comment by PeterLuschny** [comment]
Since we're at it, how do I write the Eulerian case \genfrac<>{0pt}{}{n}{k}? I tried several things which did not work (in the context of HTML of course).

**Comment by dpvc** [comment]
Well, your example worked for me as in in Firefox and Safari.  Can you tell me the environment where it doesn't for you?  So I can't really test my solutions since the original worked fine for me as well.

In any case, you could try  `\genfrac{<}{>}{0pt}{}{n}{k}` or ` \genfrac\langle\rangle{0pt}{}{n}{k}`, both of which also work in LaTeX.  The latter in particular should not cause problems in HTML, but I think the former should as well.

**Comment by dpvc** [comment]
=> in testsuite

LaTeXToMathML/frac/issue1199.html
