### ISSUE TITLE
Literal greek converts to wide-spaced MJX-TeXAtom-ORD

### ISSUE THREAD

**Issue by flying-sheep** [mathjax/MathJax#1203]
Hi, the HTML renderer renders `<span class=mrow><span class=mo>σ</span></span>` with little space around it, but the MathML renderer creates `<mrow class=MJX-TeXAtom-ORD><mo>σ</mo></mrow>` which is far wider than the contained `<mo/>`.

i think it should rather render as `<mi>` like `\sigma`.

**Comment by dpvc** [comment]
Even the actual TeX program does not deal well with unicode characters outside the ASCII range (U-0000 to U-007F), and to get support for that, you need to use an extended version of TeX like XeTeX or LuaTex.  MathJax's treatment of non-ASCII characters is only slightly better.

When MathJax sees a character that is not a special character (like `\` or `{`), MathJax uses a pattern to tell if it is a letter (which are put in `<mi>`) and another one to tell if it is a number (which it puts in `<mn>`); everything else gets put into `<mo>`.  The letter and number patters only create ASCII characters.  But you can modify those patterns to include other characters, like the Greek letters.  Add

``` html
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: {Augment: {Definitions: {letter: /[a-z\u0391-\u03A9\u03B1-\u03C9]/i}}}
});
</script>
```
to your page just before the script that loads MathJax.js itself.  That will make upper- and lower-case Greek letters be treated as letters (rather than "other") and they will be put into `<mi>` elements instead.

**Comment by flying-sheep** [comment]
Many thanks for the workaround!

However, MathJax is used in too many places to not fix such things at the source.

Maybe MathJax wants to use [XRegex](http://xregexp.com/) or similar to get sane regexes that know that “ä”, “è”, and “α” are letters.

**Comment by RemedialGenius** [comment]

