### ISSUE TITLE
Stretchy characters have gaps between the pieces on IE 10/11 with Gyre Pagella

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1211]
For an example, see Eq.3 at https://www.osapublishing.org/oe/fulltext.cfm?uri=oe-23-14-18589

Does not happen on MS Edge.

**Comment by dpvc** [comment]
There is code in the HTML-CSS jax's font-detection process that tries to work around the fact that the extra web fonts have inconsistent names in the PC and Mac font name fields.  This allows locally installed versions of the web fonts to be used (at least in some cases).  It turns out that that code was interfering with the detection of the actual web fonts.

I have fixed this in the `issue1211` branch of my fork of MathJax.

**Comment by pkra** [comment]
That's great! This looks like it can be cherry-picked, is that correct?

**Comment by pkra** [comment]
Ah, nevermind my question about cherry-picking. I think the original source of this report uses the CDN.

**Comment by dpvc** [comment]
=> Merged.
