### ISSUE TITLE
TeX input,  amsmath: change `\sideset` implementation to generate multiscripts

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1217]
As per F2F and additional feedback from AMS math folks, multiscripts seem to be the desired output.

**Comment by pkra** [comment]
(Maybe try to push it into 2.6...)

**Comment by dpvc** [comment]
Does the self-assignment mean you are planning to implement it yourself?  If so, I could give some suggestions about one approach that should work fairly easily.

**Comment by pkra** [comment]
> Does the self-assignment mean you are planning to implement it yourself? 

Yes. Since I realized my other plan is [basically done](https://github.com/mathjax/MathJax/blob/develop/unpacked/extensions/TeX/mhchem.js#L463-L471). But I don't mind being beaten to it.

> If so, I could give some suggestions about one approach that should work fairly easily.

That'd be great!

**Comment by dpvc** [comment]
My suggestion is to use `ParseArg()` to get the arguments and parse them as MathML. This should give you a MathML element for each argument.  Since the prescript and postscript arguments should look like `(_a^b)`, you should get back an `msubsup` (or potentially an `msup` or `msub`, or possibly just an empty `mrow` if the argument is empty).  You can check this using the `type` property of the returned MathML, or via `instanceof`.  The children of the mml element are in its `data` property, and its `sub` and `sup` properties give the indices into the array for the proper element (since they differ for `msubsup`, `msub`, and `msup`).  E.g., 
```
SideSet: function (name) {
  var sub, sup, presub, presup;
  var mml = this.ParseArg(name);
  if (mml instanceof MML.msubsup) {sub = mml.data[mml.sub], sup = mml.data[mml.sup]}
    else this.Error(["SideSetArg","Argument should include only super- and subscripts"]);
  ...
}
```

(Here MML = MathJax.ElementJax.mml that can be set globally.)

I think that should give you a good start.

As for the multi scripts macro that you cite above, it is part of the mhchem package, and only handles a single pre sup, pre sub, sup, and subscript, so is not a completely general solution.  The tensor package and `\prescript` from math tools both allow multiple scripts on either side.  Doing that is a bit more complicated, and my technique from above can't really be used for that.  So there is still work to be done for a complete mmultiscripts implementation.
