### ISSUE TITLE
\boxed with \text and nested math

### ISSUE THREAD

**Issue by orangeplanet** [mathjax/MathJax#1224]
\boxed runs into a problem if it contains \text with nested math.  See https://jsfiddle.net/w5kv6a95/  (MathJax seems to think there's a missing closing brace, but there's not.)  The only way around it appears to be going in and out of \text to keep the math and the words separated.

**Comment by dpvc** [comment]
It looks like it has to do with the dollar delimiters specifically.  If you use `\(...\)` within the `\text{}` it seems to work.  I'll check into it, but that is a work-around for now.

**Comment by dpvc** [comment]
OK, it turns out that when MathJax looks for matching dollar signs in `\text` (and other similar macros like `\hbox`), it doesn't take bracing into account, and so something like `\hbox{$\text{words $x$ words}$}` will end up causing the math to be matched as `$\text{words $` and `$words }$`.  As it happens, `\boxed` is defined essentially as `\def\boxed#1{\fbox{$\displaystyle{#1}$}}`, so when you use `$` delimiters inside the box, they get incorrectly matched with the ones in the definition.

MathJax should take the braces into account, but currently doesn't.

**Comment by dpvc** [comment]
This is fixed in the `issue1224` branch of my fork of MathJax.

**Comment by dpvc** [comment]
=> Merged

**Comment by dpvc** [comment]
=> in testsuite

LaTeXToMathML/issue1224.html
