### ISSUE TITLE
localize new error message hint

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1230]
Continuation of https://github.com/mathjax/MathJax/pull/1216

https://github.com/mathjax/MathJax/blob/develop/unpacked/MathJax.js#L2333-L2336 need to be localized.

[Side comment. This seems to be getting closer to the grey area where UI meets code; the language we use in our code is English (`unpacked/MathJax.js`, `MathJax.Hub.lastError`, JavaScript keywords) and won't be localized.]

**Comment by dpvc** [comment]
> This seems to be getting closer to the grey area where UI meets code

There are lots of places where this is true (e.g., TeX error messages that include the macro name).  The localization of this should turn the error message into an substitution string like `"Error: %1"` where the message is added into it, and the hint could be `"Debugging tip: use %` and inspect %2"` where the `unpacked/MathJax.js` and `Mathjax.Hub.lastError` are substituted in.

The TeX messages need similar treatment so that macros and other fixed values are not translated (we ran into this before).  That would also allow us to switch rtl to ltr for those values, if needed.

**Comment by dpvc** [comment]
The `issue1230` branch of my fork of MathJax includes localization (plus tries harder to find the file and line number from the error object).

The localization strings will have to be added to the localization files for TranslateWiki.  There are four new ones for this.

**Comment by dpvc** [comment]
=> Merged.

**Comment by dpvc** [comment]
=> in testsuite

API/Localization/issue1230.html
