### ISSUE TITLE
Website: Typographical error

### ISSUE THREAD

**Issue by Augustin-Zidek** [mathjax/MathJax#1237]
Hi,

the function f(a)=12πi∮γf(z)z−adz on mathjax.org contains a typographical error: the differential d should be upright (\mathrm). See http://tex.stackexchange.com/questions/14821/whats-the-proper-way-to-typeset-a-differential-operator

Regards,
Augustin

**Comment by dpvc** [comment]
Despite the ISO standard that is cited in your reference, there is considerable disagreement about what the proper form for the "d" in an integral is.  Even the reference you give shows that.  I am one of those who feel that the italic "d" is the correct form (I don't consider the "dx" to be a differential in this setting, but that is not a debate I'm interested in having here).

Note that the [HTML5 spec](http://www.w3.org/html/wg/drafts/html/master/syntax.html#named-character-references) lists `&DifferentialD;` as U+2146 (DOUBLE-STRUCK ITALIC SMALL D), a usage I've never actually seen in print, and find quite distasteful; but you can see that there are at least several different (and inconsistent) published standards for this character.

Personally, I think the use of black-board bold (i.e., double-struck) letters in print is much more unsettling (since it was used on the blackboard as a substitute for what would have been standard bold in print) than the use of italics for the "dx" in an integral.  But that battle is lost.

@pkra, since you maintain the website, you can render it however you like, but I don't think there is sufficient agreement (certainly not in the Mathematics community) to call this an error.  Personally, I'd leave it as is.

**Comment by pkra** [comment]
> I don't think there is sufficient agreement (certainly not in the Mathematics community) to call this an error. Personally, I'd leave it as is.

Couldn't agree more.
