### ISSUE TITLE
Why some times the single dollar fails to work?

### ISSUE THREAD

**Issue by kemaswill** [mathjax/MathJax#1239]
I have add the following script to the head.html to enable using single dollar as in-line delimiter:

```
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    tex2jax: {
      inlineMath: [ ['$','$'], ["\\(","\\)"] ],
      processEscapes: true
    }
  });
</script>

<script type="text/javascript"
    src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>
```

However, the MathJax sometimes fails to parse the single dollar delimiter so that I have to switch to double dollar, following is an example:

where $w_{j_1}$ and $w_{j_2}$ are two vectors with length $k$ , and $k$ is a used-defined parameter.

Does anyone know why?

**Comment by dpvc** [comment]
It is difficult to tell without seeing an actual page where this is actually occurring, but I suspect that you are using blog software that uses Markdown syntax.  In Markdown, underscores (_) are used to produce italics, and since Markdown is processed before MathJax runs, you are probably getting something like 

    where $w<em>{j</em>1}$ and ...

But since MathJax doesn't allow HTML elements within the math delimiters, it will not process this expression.

You may be able to get it to work with

    where $w\_{j\_1}$ and ...

to prevent Markdown from processing the underscores.  There may be other issues with bad interactions between Markdown and MathJax.
