### ISSUE TITLE
Some fonts causing math to render at wrong size in Firefox 4.

### ISSUE THREAD

**Issue by c-spencer** [mathjax/MathJax#125]
Using the Crimson Text font from Google Font API causes Math to render around 50% expected size. I checked with another web font (Maven Pro) which rendered correctly.

Minimal example: https://gist.github.com/1000213

Renders as expected in Safari and Chrome. This is on OS X 10.6.7.

**Comment by dpvc** [comment]
MathJax uses the ex-height of the font surrounding the mathematics to determine the scaling factor used for the math (so that the ex-height of the math font will match the ex-height of the font around it).  It turns out that the exHeight value in the OS/2 table for the Crimson Text font is way too small, and apparently Firefox uses the OS/2 table for the ex-height, while Safari and Chrome use something else (not sure exactly what).

You can see that the font is in error by the following example:

```
<!DOCTYPE html>
<html>
  <head>
    <link href='http://fonts.googleapis.com/css?family=Crimson+Text' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Maven+Pro' rel='stylesheet' type='text/css'>
    <style>
      .exblock {
        display: inline-block;
        width: 1ex;
        height: 1ex;
        background-color: red;
      }
    </style>
  </head>
  <body>
    <div style="font-family: 'Maven Pro'">
      Maven Pro: x<span class="exblock"></span>x
    </div>
    <div style="font-family: 'Crimson Text'">
      Crimson Text: x<span class="exblock"></span>x
    </div>
  </body>
</html>
```

This doesn't involve MathJax in any way.  It puts a red box with height and width of 1ex between two x's.  Ideally, the box would be as high as the x's on either side, which it is (at least pretty close) in Safari and Chrome, but isn't in Firefox.  The exHeight value for Crimson Text is 125, which is about 5 times too small for the font.  So it looks to me like a bug on the Crimson Text font.  You might want to report this to Google.

In the meantime, you can use the `minScaleAdjust` value in the `HTML-CSS` section of your MathJax configuration to prevent the math from getting too small:

```
MathJax.Hub.Config({
  extensions: ["tex2jax.js"],
  jax: ["input/TeX","output/HTML-CSS"],
  tex2jax: {inlineMath: [["%%","%%"]]},
  "HTML-CSS": {minScaleAdjust: 100}  // don't let math font shrink
});
```

This will make sure the math font is at least at its natural size (which may be too big, so you might need to adjust the 100 to be something else).  This could help until the font's ex-height is fixed.

Davide
