### ISSUE TITLE
Review mml3.js updates for v2.6

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1250]
Just a tracking issue to remember to check for udpates.

**Comment by pkra** [comment]
@dpvc I wanted to add 

```javascript
MathJax.Hub.Config({
  "HTML-CSS": {
    styles: {
      ".MathJax_Display span": {
        "direction": "ltr !important",
        "display": "inline-block !important"
      }
    }
  }
});
```

to the `mml3.js` extension but it doesn't seem to work. What am I'm doing wrong?

**Comment by dpvc** [comment]
By "not working" do you mean the styles are not being inserted into the page, or do you mean that the result of adding them isn't what you expect it to be?

**Comment by pkra** [comment]
They didn't seem to be inserted into the page.

**Comment by dpvc** [comment]
The configuration for HTML-CSS probably has already completed by the time the extension is loaded, and so the styles are already in place before you add these into the HTML-CSS configuration.  You may just have to add the style sheet yourself via a call to `MathJax.Ajax.Styles()`.

In any case, I think you want `".MathJax span"` not `".MathJax_Display span"` otherwise you will miss the inline math.

**Comment by pkra** [comment]
Ah, ok. I had followed the wrong example then. That works.

**Comment by pkra** [comment]
=> Merged.
