### ISSUE TITLE
v2.6 beta gives [Math processing error] 30 seconds after successfully rendering text on windows phone webview

### ISSUE THREAD

**Issue by pankajsejwal** [mathjax/MathJax#1270]
With this 2.6 beta release for windows phone 8.1 webview, problem of not being able to retain rendered text has been solved to some extent but now exactly after 30 seconds it shows [Math processing error].
May be for now people can write logic to reprint it before every 30 seconds but it creates a flicker once which looks odd in apps.

**Comment by pkra** [comment]
Thanks for the feedback. Can you provide more information? A live sample that reproduces the problem in a browser would be ideal, more information on your setup would help, too.

**Comment by pankajsejwal** [comment]
I have this small html page that I render,


<!DOCTYPE html>
<HTML>
<HEAD>
<STYLE TYPE="text/css">.math </STYLE>
<SCRIPT SRC="MathJax.js?config=TeX-AMS-MML_HTMLorMML"></SCRIPT>
</HEAD>
<BODY><font size=10/> \[a=\frac{\mathrm{sin}\left( x\right) }{2}+1\]   </body> </html>

I have stripped unnecessary(for me) files and kept a trimmed version of 2.6beta in my project.
I am working with Visual studio 2013, windows phone 8.1, Also if I view this file in any browser, including IE it never causes a problem but on webview it does. Is there any more information I need to provide ? 
Usually on browsers the text should get rendered or I should get [math processing error] but here both happen which is strange !!

**Comment by pankajsejwal** [comment]
I have created a minimal zip of the project which is available at 

https://drive.google.com/file/d/0B36DQjLI_-hxZE5wclVJRHdmNHM/view?usp=sharing

Just open the project with visual studio and launch with some mobile simulator and wait for 30 seconds after app is launched.
Also note that I have a stripped version of v2.6beta but it doesn't seem to be a problem because if I use browser to view the same html file that I am trying to render onwebview, its flawless, works fine.

**Comment by pkra** [comment]
I'm afraid we don't have the resources to debug windows phone apps. 

Since the problem happens after the rendering is complete, I would suggest to start by disabling the AssistiveMML extension, see http://docs.mathjax.org/en/v2.6-latest/options/assistive-mml.html.

**Comment by dpvc** [comment]
A delay like the one you are experiencing usually indicates that some auxiliary file is not loading and MathJax is waiting for it to load and eventually timing out.  The AssistiveMML extension will not cause "Math Processing Error" messages, since it doesn't run until after the visual output is already in place.

To see if any files aren't being loaded, you can look at the output of MathJax.Message.Log().  I'm not sure what debugging facilities you have with the windows phone, but if you can execute that in a debugging console, that should show if anything is timing out.  If you can't execute it interactively, you might be able to get the app to output the result using something like

```
<script type="text/x-mathjax-config">
MathJax.Hub.Queue(function () {alert(MathJax.Message.Log())});
</script>
```

*before* the script that loads MathJax.js itself.  

I suspect it is the web fonts.  I see that you have only included the WOFF and SVG fonts.  You can drop the SVG fonts, as they will not be used by any modern browser.  It may be that you have to add in the EOT fonts; depending on what `documentMode` is being triggered, it may be that MathJax is asking for the EOT fonts.  You could do

```
<script>
alert(document.documentMode);
</script>
```
to find out what the `documentMode` is.

Let us know what you find from these and we will see if that leads to anything.

**Comment by pankajsejwal** [comment]
Based on suggestion above I found that problem was caused because of removing "png" folder in Tex rather than EOT. If I keep it, it works fine.

The logging script output gives
Loading [MathJax]/config/Tex-AMS-MML_HTMLorMML.js
Loading [MathJax]/jax/output/HTML-CSS/jax.js
Loading [MathJax]/jax/output/HTML-CSS/fonts/TeX/fontdata.js
Loading web-font Tex/Math/Italic
Loading web-font Tex/Main/Regular

And documentmode = 11.

I am highly thankful to people here for taking time to suggest me which helped me resolve my problem.

**Comment by pkra** [comment]
>  I found that problem was caused because of removing "png" folder in Tex rather than EOT.

This sounds strange to me. It might mean the app is not able to load the webfonts at all (maybe a variant of http://docs.mathjax.org/en/latest/installation.html#ie9-and-remote-fonts ?) and falling back to the PNG fonts.

Is the output from MahtJax.Message.Log maybe cut-off? If MathJax fails to load webfonts, it will fallback to PNG-based "fonts". This would also be noted on MathJax's about pop-up (via the MathJax menu) and it would show at high zoom levels (as blurry PNGs instead of fonts).

**Comment by pankajsejwal** [comment]
First I want to apologize that the output mentioned above if from web browser and not mobile. I messed up, webview won't allow alerts and popups so I tested on web browser. 
I tested now again by setting it as inner html and now I can see it on mobile, details are

Loading[MathJax]/config/TeX-AMS-MML_HTMLorMML.js 
Loading[MathJax]/jax/output/HTML-CSS/jax.js
Loading[MathJax]/jax/output/HTML-CSS/fonts/TeX/fontdata.js
Loading web-font/TeX/Size2/Regular Can't load web font
TeX/Size2/Regular Web-fonts not available -- using image fonts instead
Loading[MathJax]/jax/output/HTML-CSS/imageFonts.js
Loading[MathJax]/fonts/HTML-CSS/TeX/png/imagedata.js

I couldn't recover documentmode though. Your assumption that web-fonts have not been loaded is correct. Have I deleted some file I shouldn't have had ?

**Comment by pkra** [comment]
> Have I deleted some file I shouldn't have had ?

Not necessarily but I would try adding the eot and otf versions of the fonts. 

You might also run into security-measures for resource loading blocking webfonts.

But from a quick google search it seems windows phone apps have had issues with loading fonts, e.g., http://stackoverflow.com/questions/14347667/webfont-in-windows-phone-8-html5-app and it seems you might have to declare the fonts in your manifest to have them included in the build http://blogs.msdn.com/b/lighthouse/archive/2014/03/15/how-to-use-custom-font-in-windows-phone-8-application.aspx.

If all else fails, you might want to give our SVG output a try.

**Comment by pankajsejwal** [comment]
I tried with adding eot and otf versions and removing png but it didn't solve the problem. I will try SVG in future, I have tonnes of work pending in my app and I will have to live with png at least for now. Thanks for help :)

**Comment by pankajsejwal** [comment]
I have one more question, how do I disable the 30 second wait time, I want it not wait at all. Which file I should look into?

**Comment by pkra** [comment]
If you want to force PNGs fonts, you need to disable all other forms, e.g., have something like this in your MathJax configuration

`"HTML-CSS": {availableFonts: [], preferredFont: null, webFont: null, imageFont: "TeX"}`

**Comment by pankajsejwal** [comment]
@pkra :+1:  yes, indeed it does the needed work. It takes less than a second now. I am just so thankful to you. :)
