### ISSUE TITLE
2.6-beta: CommonHTML output removed from DOM on math.SE

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1271]
Report from meta.math.SE http://meta.math.stackexchange.com/a/21535/26910. I can see it there but can't reproduce it in a plain environment.

**Comment by dpvc** [comment]
This is due to the noErrors extension, which needs to be updated for the new CommonHTML output (it currently has the code for the old CommonHTML output, now called PreviewHTML, so that needs to be updated).

You should be able to see the problem when noErrors is enabled and you use an equation with an error in it, like an extra or unclosed brace.

**Comment by dpvc** [comment]
This is fixed in the `issue1271` branch of my fork of MathJax.

**Comment by dpvc** [comment]
=> Merged
