### ISSUE TITLE
Getting rid of the Flash of Unstyled Content?

### ISSUE THREAD

**Issue by lancejpollard** [mathjax/MathJax#131]
When the page loads, even if all that's on there is 1 equation, you first see the unstyled equation, then a half a second later it renders with MathJax (I'm on Safari).

Is there a way to prevent this?  Maybe forcing rendering at a specific point?

**Comment by Mohanson** [comment]
The FOUC problem comes from the plugin named **fast-preview**,  close it plz ~

```
MathJax.Hub.Config({
  extensions: ["fast-preview.js"],
  "fast-preview": {
    disabled: true
  }
});
```

**Comment by dpvc** [comment]
@Mohanson, at the time this issue was started, the fast preview didn't exist, so that is certainly not what the poster was concerned about.  As discussed above, the issue is that the original TeX code (or whatever format was used) will be displayed until MathJax loads all its components and processes the math.  That is a different issue, and will still be the case even with fast preview turned off.

Also, if you are just going to disable face preview, why load it in the extensions array in the first place.  The reason for the disable option is that fast-preview is loaded by the combined configuration files (no need to add it to extensions by hand), so there needs to be a way to turn it off in that situation.

**Comment by pmorch** [comment]
I know this is a closed issue, but I'd like to suggest a modified workaround to the one @dpvc  suggests that uses shortcodes and Mathjax 3:

Put this in the page source somewhere. I put it in `layouts/partials/head-additions.html`, but perhaps that is specific to the ananke theme:

```
{{- if or (.HasShortcode "mathjax/block") (.HasShortcode "mathjax/inline") -}}
<style>
.has-mathjax {
    visibility: hidden;
}
</style>

<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>

<script>
window.MathJax = {
  startup: {
    pageReady: () => {
      return MathJax.startup.defaultPageReady().then(() => {
        for (let element of document.getElementsByClassName("has-mathjax")) {
            element.style.visibility = "visible"
        }
      });
    }
  }
};
</script>
{{- end -}}
```

Put this in `layouts/shortcodes/mathjax/block.html`:
```
<div class="has-mathjax">
{{ .Inner }}
</div>
```

And this in `layouts/shortcodes/mathjax/inline.html`:
```
<span class="has-mathjax">{{ .Inner }}</span>
```

Now you can put this in your page source:
```
Mathjax block:
  
{{< mathjax/block >}}
\[a \ne 0\]
{{< /mathjax/block >}}

Inline shortcode {{< mathjax/inline >}}\(a \ne 0\){{< /mathjax/inline >}} with
Mathjax.
```
