### ISSUE TITLE
line-breaking: option to prevent overflow

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1327]
For long-term reference. MathJax's line-breaking algorithm sometimes allows overflow in favor of lots of whitespace. As an author, I often need to be sure that no overflow occurs. A configuration option would be useful here.

**Comment by dpvc** [comment]
There already are parameters for it, though it takes a bit of work to set them.  There is a collection of parameters that are in a property of the internal mbase element that can be used to control the line breaking.  Among them is a penalty for when the breakpoint is past the actual width of the line, and you can set that to a much higher value if you want to suppress that option.  This (untested) code should do it:

```
MathJax.Hub.Register.StartupHook("HTML-CSS multiline Ready",function () {
  var PENALTY = MathJax.ElementJax.mml.mbase.HTMLlinebreakPenalty;
  PENALTY.toobig = 1000000;
});
```

The SVG and CommonHTML output jax have similar penalty objects (called `SVGlinebreakPenalty` and `CHTMLlinebreakPenalty`).  I suppose there could be a global penalty object that is part of the main config object that would replace these, but when the HTML-CSS line breaking was written, there was no SVG or CHTML output, and since these line breaking parameters didn't affect the NativeMML output, it seemed that they should be output jax specific.  In hindsight, that might not have been the best choice.

**Comment by pkra** [comment]
> There already are parameters for it, though it takes a bit of work to set them.

Ah. great!

>  I suppose there could be a global penalty object that is part of the main config object that would replace these,

Right. It's in the v3.0 milestone so that we can revisit this if we want.

**Comment by pkra** [comment]
Hm... Can't get it to work though :-( http://codepen.io/pkra/pen/YwKmPM

**Comment by dpvc** [comment]
Two reasons for that:  the first was my mistake -- I left out the `prototype` in

```
var PENALTY = MathJax.ElementJax.mml.mbase.prototype.HTMLlinebreakPenalty
```

The second is that the example you are using includes an `align` environment, meaning it makes an `mtable`, and the line breaking for tables isn't very good.  It breaks each cell to the full width, with our regard to the content of other cells.  So the first expression should be restricted to the width of the box, the the other will overrun the right hand edge by the width of the first column.

**Comment by pkra** [comment]
> I left out the prototype 

Hm... I could've sworn I tried that. Oh well -- works now. Thanks!

> the line breaking for tables isn't very good. 

Yes, that was basically my intention (though not to point out problems in MathJax)

> It breaks each cell to the full width, with our regard to the content of other cells. So the first expression should be restricted to the width of the box, the the other will overrun the right hand edge by the width of the first column.

Thanks for the background info. It also looks like line-broken cells end up being centered (e.g., at 400px the cell (4,2) looks odd). Doesn't matter for me here though.

**Comment by dpvc** [comment]
How the lines are aligned is controlled by the element's [indentation attributes](http://www.w3.org/TR/MathML3/chapter3.html#presm.lbindent.attrs), in particular, from `indentalign` and `indentshift`.  These are initialized by the `displayAlign` and `displayIndent` values, if I recall correctly.  So in a context where displayed equations are centered, lines produced by line breaking will be centered as well.

I suppose `indentalign` could be taken from the column alignment.  I think line breaking in `mfrac` and other containers may set it to `left` and set the `indetnshift` to 0 if not otherwise specified, but I haven't checked to verify that.
