### ISSUE TITLE
[HTML-CSS output] msubsup with maction rendering issue

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1332]
Originally reported at https://github.com/mathjax/MathJax-RespEq/issues/43

Minimal(?) sample:

```html
<math>
<msubsup>
      <mrow>
        <mo fence="true" stretchy="true" ></mo>
        <mrow>
          <maction actiontype="toggle">
            <mtext mathcolor="blue">&#x25C2;+&#x25B8;</mtext>
              <mi>a</mi>
          </maction>
          <mo>|</mo>
        </mrow>
      </mrow>
      <mi>y</mi>
      <mi>x</mi>
    </msubsup>
</math>
```

**Comment by pkra** [comment]
To describe the visual result: the sub/sup appears on the far left, ie., attached to the empty mo not the `|`, overlapping the mtext element from the maction.

**Comment by dpvc** [comment]
I suspect it is due to the fact that the `<mtext>` paired with `<mo>` is an embellished operator, and the layout is getting confused by the width of the base in that case.  I will have to check further.  In any case, a slightly reduced case is

```
<math display="block">
  <msubsup>
    <mrow>
      <mo></mo>
      <mrow>
        <mtext>xx</mtext>
        <mo>|</mo>
      </mrow>
    </mrow>
    <mi>y</mi>
    <mi>x</mi>
  </msubsup>
</math>
```

**Comment by dpvc** [comment]
It turns out that the width of mrows that contain embellished operators that could stretch but don't actually have to was being computed incorrectly (he width of the core mo was being used rather than the complete operator).  That is why the embellished operator in this case was causing the problem.

So an even more reduced test case is

```
<math display="block">
  <mrow mathbackground="red">
    <mrow>
      <mtext>x</mtext>
      <mo>|</mo>
    </mrow>
  </mrow>
</math>
```

Here the red background color will be too small (it should cover the complete expression, but will only cover about half of the "x").

The `issue1332` branch of my fork of MathJax includes the fix for this.

**Comment by dpvc** [comment]
=> In testsuite

MathMLToDisplay/issue1332.html

**Comment by dpvc** [comment]
=> Merged
