### ISSUE TITLE
Lower sign misinterpreted

### ISSUE THREAD

**Issue by dschrempf** [mathjax/MathJax#1335]
Hello,

I am trying to export a LaTeX code block from Emacs Org mode into HTML and have a problem when using lower (<) signs (maybe it also happens with greater signs but I did not check that).

E.g., the following HTML code leads to an error when viewing the file because the '<' sign is interpreted in a wrong way (I don't know how but it seems to be interpreted as part of a tag) and MathJax does not succeed then.  I.e., the Firefox HTML syntax checker shows the line `\end{equation}...` in red in the HTML file.

HTML code:

    \begin{equation}
      \text{if } 0<i<N
    \end{equation}</li>
    </ul>

If I add spaces in-between, it works fine.

HTML code:

    \begin{equation}
      \text{if } 0 < i < N
    \end{equation}</li>
    </ul>

This might just be a problem of HTML failing to parse the source code, but it leads to unexpected behavior.  I have also posted this on the Org mode mailing list and they referred me to here.

Best wishes,
Dominik

**Comment by dpvc** [comment]
You are correct that it is due to the `<i` being interpreted as n HTML tag by the browser.  This is explained further in the [MathJax Documentation](http://docs.mathjax.org/en/latest/tex.html#tex-and-latex-in-html-documents).  Remember that you are creating an HTML document, not a TeX document, so you have to keep in mind the implications of that.  Mostly, that means you have to be careful about your use of `<` in situations like this.  Since the browser interprets the HTML long before MathJax runs, MathJax can't do anything about this issue, so I'm marking this "expected behavior".

**Comment by dschrempf** [comment]
Thank you.

Hm, this combination is used often in Mathematics though so it might be worth to check it during Org mode HTML export.  I will ask people over there.
