### ISSUE TITLE
linebreaking "stops" within an expression 

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1339]
I don't have time to dig deeper right now but the (not minimal) example below triggers some interesting behavior.

If the available width is smaller than the width of the brace, then the base gets line-breaking, but the rest of the equation (after that group) won't. Fun fact, this won't happen after re-writing it via semantic enrichment.

```latex
I_\nu(\nu^{-1},1)
=\underbrace{\frac{\pi^2}{4}\ln\left(\frac{(1+\nu)^{1+\nu}}{\nu^\nu}
\right)-\frac{7\zeta(3)}{8}\nu}_{\text{Let this be
C}}+2\int^\frac{1-\nu}{1+\nu}_1\frac{\chi_3(v)}{(1+v)^2}{\rm d}v
=C-\left.\frac{2\chi_3(v)}{1+v}\right|^\frac{1-\nu}{1+\nu}_1+2\int^\frac{1-\nu}
{1+\nu}_1\frac{\chi_2(v)}{v(1+v)}{\rm d}v
=C+(1-\nu)\chi_3\left(\frac{1-\nu}{1+\nu}\right)-\frac{7\zeta(3)}{8}
-\left.{\color{white}{\frac{1}{1}}}2\chi_2(v)\ln(1+v)\right|^\frac{1-\nu}{1+\nu}
_1+\int^\frac{1-\nu}{1+\nu}_1\frac{\ln(1+v)\ln\left(\frac{1+v}{1-v}\right)}{v}{
\rm d}v
=C+(1-\nu)\chi_3\left(\frac{1-\nu}{1+\nu}\right)-\frac{7\zeta(3)}{8}
+2\chi_2\left(\frac{1-\nu}{1+\nu}\right)\ln\left(\frac{1+\nu}{2}\right)+\frac{
\pi^2}{4}\ln{2}
+\frac{1}{2}\int^\frac{1-\nu}{1+\nu}_1\frac{
\ln^2(1+v)-\ln^2(1-v)+\ln^2\left(\frac{1-v}{1+v}\right)}{v}{\rm d}v
```

![linbreaking](https://cloud.githubusercontent.com/assets/426686/11872120/f7ce80b8-a4d3-11e5-84d0-25fda3769edc.png)

**Comment by dpvc** [comment]
If this is in your codepen where you adjusted the `toobig` penalty, remember that you have effectively prevented line breaks outside the box, and since the `+2...~ is past the width of the box, those are all considered invalid breakpoints.  So this is "expected behavior" for that situation.  If you relax the `toobig` setting, you should get breaks occurring again in the rest of the expression.

**Comment by pkra** [comment]
I see. Thanks.
