### ISSUE TITLE
[CommonHTML] Anomaly caused by accented character inside \text{}

### ISSUE THREAD

**Issue by cebola2** [mathjax/MathJax#1353]
I have come across an anomaly in MathJax for which I tried to furnish the proverbial minimal example but failed. I can nevertheless furnish a page without apparent problems, indicate the very slight change that will trigger the problem and screenshots of both.

The page is https://cdi2tp.math.tecnico.ulisboa.pt/praticas/3

To see the problematic area expand the last "Solução" by clicking the black triangle to its left. You will see something like this.
![screenshot at 2016-01-20 21 28 47](https://cloud.githubusercontent.com/assets/1136663/12463940/5bb0a2aa-bfbe-11e5-80a3-77b01f3e05b8.png)

If one adds an acute accent to character a in the word contrario in the begin{cases}\end{cases} structure, then one gets what follows.

![screenshot at 2016-01-20 21 30 23](https://cloud.githubusercontent.com/assets/1136663/12463907/2b15092e-bfbe-11e5-8202-1647bd2e4fcb.png)

My attempts at replicating this in simpler circumstances have failed miserably so far.

**Comment by pkra** [comment]
Thanks for reporting this. 

I see the problem in Chrome and Firefox; it only seems to affect the CommonHTML output. We'll look into it.

**Comment by dpvc** [comment]
MathJax doesn't know the bounding boxes for characters that are not in the MathJax fonts (like the accented letters), and so it must measure them in order to determine their size.  But when an element is in a container with `display:none` (as contents of the `<details>` element effectively are), the browser doesn't lay out the content, and returns `0` for any measurement MathJax makes.  This means MathJax gets the wrong size for those characters when they are typeset while they are not visible.

The HTML-CSS output jax moves the math to a non-hidden location in this case, but CommonHTML doesn't.  Perhaps that should be done here as well.

**Comment by dpvc** [comment]
The `issue1353` branch of my fork of MathJax includes a work-around.

**Comment by dpvc** [comment]
=> Merged

**Comment by dpvc** [comment]
=> In test suite

MathMLToDisplay/Characters/issue1353.html
