### ISSUE TITLE
[MathZoom] no way to zoom on mobile device

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1362]
On an iPad, neither hover nor click are available in the menu and double-click to zoom has no effect.

**Comment by dpvc** [comment]
There is no notion of hover for the iPad, and clicking is used for other things, so those two are removed from the menu for mobile devices by design.  I suspect that double-click now is trapped earlier by the browser to do its own zooming effect, so may no longer be available for MathJax, or we need to hook into it differently.

**Comment by pkra** [comment]
Sorry for late night filing; I was aware of the first part. I mostly didn't want to forget to revisit the zoom in 3.0. E.g., we could look into [pointer events](http://caniuse.com/#feat=pointer) (IE/Edge have it, FF is about to, Chrome intends to, though Safari is opposed).
