### ISSUE TITLE
[TeX input] negative hspace with overlap

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1372]
I came across this hackish piece of content

```latex
\begin{equation*}
 E_nF_nE_n(V,V')=\begin{cases}
 (\frac {v^{2\lambda '_n}-1}{v^2-1}+\frac {v^{2\lambda _{n+1}'+2}-1}{v^2-1} +v^{D-2|V_n|-2}-1)v^{-\lambda '_n-2\lambda _{n+1}'+1},\\
 {} &\hspace {-142pt}{\mathrm{if}}\ V_n \overset {1}{\subset } V'_n,\\
 v^{-\lambda '_n-2\lambda _{n+1}'+1}, &\hspace {-142pt}{\mathrm{if}}\ |V_n \cap V'_n|\!=\!|V_n|-1\ {\mathrm{and}}\ V_n\!\not \subset \! V'_{n+1},\\
 (v^2+1)v^{-\lambda '_n-2\lambda _{n+1}'+1}, &\hspace {-142pt}{\mathrm{if}}\ |V_n \cap V'_n|\!=\!|V_n|-1\ {\mathrm{and}}\ V_n \!\subset \! V'_{n+1},\\
 0, &\hspace {-142pt}{\mathrm{otherwise}}, 
\end{cases} 
\end{equation*}
```

MathJax renders this with some overlap in the fourth line while LaTeX is fine. Is this due to the use of `pt` units?

Anyway, I'm ok with marking this as expected behavior but just wanted to check.

**Comment by dpvc** [comment]
Explicit spacing in MathJax doesn't always match up exactly with that in LaTeX.  Measurements like `em`, `pt`, etc. don't always correspond.  For example, some documents use 10pt fonts as their default others use 12pt, and some allow an option to set which is used, so what MathJax should consider to be a pt in relation to the size of the font is not clear.  And should it use the TeX idea of a pt (72.27pt per inch) or the browser idea of a pt (72pt per inch)?  So there is some ambiguity about how the space should correspond to LaTeX.

A better way to do this would have been to add the `\hspace{-142pt}` to the end of the *first* line, or use `\rlap{}` around the first line (so that TeX thinks it is not as wide as it is) and *not* include `\hspace` on the other lines.  That would make sure they don't overlap their previous column.

**Comment by pkra** [comment]
Thanks, @dpvc. I'll pass it along.
