### ISSUE TITLE
Is there a way to embed MathJax in a single html file?

### ISSUE THREAD

**Issue by ionelmc** [mathjax/MathJax#1378]
Is there any way to have everything in a single html file? 

Right now you have to be able to serve lots of files like extensions or fonts.

It would be very nice to allow this sort of special use. It doesn't need to be pretty or efficient.

**Comment by pkra** [comment]
Something lik https://github.com/pkra/MathJax-single-file requires a bit of hackery.

**Comment by ionelmc** [comment]
@pkra awesome stuff. What are your plans regarding that build? Do you publish releases anywhere?

**Comment by pkra** [comment]
>  What are your plans regarding that build? 

This is mostly a favor for the Readium project. Though I hope to experiment with a CommonHTML build in the next few weeks.

> Do you publish releases anywhere?

Not beyond the repo itself. We'll be working towards an easier work flow for MathJax v3.0.

**Comment by ionelmc** [comment]
@pkra Interesting. Is there anywhere I can read more about Readium and CommonHTML? Googling don't seem to turn up anything relevant.

**Comment by ionelmc** [comment]
Also, how hard would it be to include the tex extension?

**Comment by pkra** [comment]
> Is there anywhere I can read more about Readium and CommonHTML?

Readium http://readium.org/. CommonHTML is the output introduced in MathJax v2.6.

> Also, how hard would it be to include the tex extension?

I think not hard. The difficult part is the SVG output and its "fonts". But let's move this conversation over to the repo?

**Comment by pkra** [comment]
FYI there's now an example build with TeX input, SVG output in my repo.

**Comment by gabyx** [comment]
Whats the status here? for version 3

**Comment by dpvc** [comment]
@gabyx, MathJax v3 already includes single-file builds of the main input/output combinations (e.g., `tex-svg.js`), so you don't need to make those yourself.  Also, MathJax v3 provides the tools for making your own custom builds that include exactly the pieces of MathJax that you need.  See, for example, the [customization](https://github.com/mathjax/MathJax-demos-web#customization) section of the [MathJax web demos](https://github.com/mathjax/MathJax-demos-web) repository, and the [custom component](https://github.com/mathjax/MathJax-demos-web/blob/master/custom-component/custom-component.html.md) and [custom build](https://github.com/mathjax/MathJax-demos-web/blob/master/custom-build/custom-mathjax.html.md) examples in particular.

**Comment by gabyx** [comment]
Thanks for this helpfull information! I was stumbling accross how to embedd the missing fonts. But its said that with a next release these things are tackled (maybe) and we get some documentation on how setup custom fonts, especially when we want to base64 include the mathjax default fonts, which come not with the single-builds **I guess**?

**Comment by dpvc** [comment]
@gabyx, correct, the web fonts aren't included for CommonHTML, but they are bundled with the SVG (since they are paths defined in javascript, not actual fonts).  It would be possible to override the web-font mechanism to refer to fonts defined through `data:` URIs, but I don't have the time at the moment to put together an example.  

You could probably do it by loading the TeXFonts object from the `output/chtml/fonts/tex.js` file and setting the `defaultFonts` property to one that includes the fonts as `data:` URIs in place of the web URLs that are in the `src` properties currently:

https://github.com/mathjax/MathJax-src/blob/32213009962a887e262d9930adcfb468da4967ce/ts/output/chtml/fonts/tex.ts#L262-L369

Something like

``` javascript
import {CHTMLFontData} from 'mathjax-full/js/output/chtml/FontData.js';
import {TeXFont} from 'mathjax-full/js/output/chtml/fonts/tex.js';

TeXFont.defaultFonts = {
  ...CHTMLFontData.defaultFonts,

  '@font-face /* 1 */': {
      'font-family': 'MJXTEX',
      src: 'url("data:font/woff;base64,...") format("woff")'
    },

   ...

};
```

should do it.

There are some reasons you may not want to do this, however.  See [Web font anti-pattern: data URIs](https://www.zachleat.com/web/web-font-data-uris/) for some discussion of this.

Sorry I can't check out the details for you.  If you get it to work, let us know.
