### ISSUE TITLE
[HTML-CSS, Safari 9] unexpected clipping

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1398]
[Via the user group](https://groups.google.com/d/msg/mathjax-users/oNhrNyl9MBg/l7oe9CL-BQAJ).

[This sample](http://www.engandmath.com/math.html) sees some unexpected clipping in the HTML-CSS output, e.g., the paragraph ending with

```latex
\begin{equation}\label{asy}
    \lvert H(j\omega) \rvert\simeq
    \begin{cases}
    H_0=\dfrac{G}{\omega_0}		& \text{if }	\omega \ll \omega_0  \\
    H_R=\dfrac{G}{\omega}			& \text{if }	\omega \gg \omega_0 
    \end{cases}
    \end{equation}
```

has the `\omega` clipped.

Reproduced on Safari 9 via Saucelabs ([screencapture](https://saucelabs.com/beta/tests/bdd7f6ba46074671bcc674f7c6ce8c71)).

[The CommonHTML output does not have the clipping problem but the spacing between the lines of the cases seems too tight.]

**Comment by dpvc** [comment]
I am not able to reproduce it on the [test page](http://cdn.mathjax.org/mathjax/latest/test/sample-dynamic-2.html), and the sample page seems no longer to be available, so I can't check the original.  I do see it in your screen capture, but can't really investigate it myself.

> the spacing between the lines of the cases seems too tight.

Actually, actual LaTeX output is even tighter:

![latex](https://cloud.githubusercontent.com/assets/432782/13422898/bbdd9ba8-df65-11e5-8762-9b5e481ff9ad.png)

MathJax does try to have a pixel at least between rows, but using `\\[5px]` or something like that would help in this case.  It is the use of `\dfrac` that is causing the tightness (the cases are set in text mode rather than display mode for a purpose).

**Comment by pkra** [comment]
> I am not able to reproduce it on the test page, and the sample page seems no longer to be available, so I can't check the original. I do see it in your screen capture, but can't really investigate it myself.

I also couldn't reproduce it on any test page; I'm guessing it was CSS interference. Marked as Cannot Reproduce.

> Actually, actual LaTeX output is even tighter:

Ouch ;-)

> It is the use of \dfrac that is causing the tightness

Ah, thanks for that pointer.

**Comment by pkra** [comment]
From the user group: sample now at http://www.engandmath.com/math_first_order_systems.php. I haven't had the time to check it out yet.
