### ISSUE TITLE
root path configuration no longer works

### ISSUE THREAD

**Issue by edemaine** [mathjax/MathJax#1399]
I am loading MathJax via JQuery in a Meteor application, which requires manual root path configuration.  Here is what I've been doing (which worked in MathJax from December 16, 2015):

```
window.MathJax = {root: '/mathjax'}
$.getScript('/mathjax/MathJax.js', ...callback...)
```

After loading, I see that `MathJax.Hub.config.root` is properly set to `"/mathjax"`.  But the latest MathJax tries to load from `/jax/...` instead of `/mathjax/jax/...`.

I've spent some hours trying to debug the issue.  Definitely `Ajax.config.root` doesn't get set to `Hub.config.root`, but I'm not quite sure why.  Another problem seems to be a combination of `PATH` and `BASE.Ajax.fileURL` with the expression `PATH[match[1]]||this.config.root` which sees that `BASE["MathJax"]` is set to `""` and so it ignores `Ajax.config.root`.

**Comment by edemaine** [comment]
As a temporary fix, I can manually change two these lines to get the intended behavior:

```
PATH[BASENAME] = "/mathjax";
...
BASE.Ajax = {
  ...
  config: {
    root: "/mathjax"
```

**Comment by pkra** [comment]
> `window.MathJax = {root: '/mathjax'}`

Hm, I think that code should never have worked. Have you tried

```javascript
window.MathJax = {
	  Ajax: {root: "/mathjax"}
	};
```
?

**Comment by edemaine** [comment]
Thanks for the suggestion.  I'm afraid that setup produces the exact same results.

**Comment by pkra** [comment]
Could you share a minimal example perhaps?

**Comment by edemaine** [comment]
Sure thing:

```
window.MathJax = { Ajax: { root: '/mathjax' } }
$.getScript('MathJax.js')
```

Complete "working" directory of necessary files (including MathJax and jQuery): [badjax.zip](https://github.com/mathjax/MathJax/files/151706/badjax.zip)

In Chrome I see requests for `/extensions/MathMenu.js?rev=2.6.1` etc., but I want to see `/mathjax/extensions/MathMenu.js?rev=2.6.1` etc.

**Comment by dpvc** [comment]
It turns out that you have to assign to `MathJax.Ajax.config.root` directly.  Try

    MathJax = {AuthorInit: function () {MathJax.Ajax.config.root = "/mathjax"}}
    $.getScript('MathJax.js');

I've incorrectly said that you could do it through the `Ajax` configuration block (or the `root` property of the main block), but that turns out not to be the case.  You have to set the value directly, as the Ajax module doesn't use a config block (it probably should), and the main `root` property is copied to the Ajax config only when MathJax is loaded normally through a script tag in the page.

Peter is right in saying that your code should never have worked.  The way the root is handled was not changed in 2.6, and there are past reports of the same problem (see [this post](https://groups.google.com/forum/?fromgroups#!topic/mathjax-users/UT9qMPPwbzg) for example, where I incorrectly suggest Peter's approach, and the OP's last message indicated that he had to set the value directly).

**Comment by pkra** [comment]
Thanks for providing this. I have to apologize for missing the `getScript` bit in the OP. 

I think this is expected behavior due to [jQuery's implementation](https://github.com/jquery/jquery/blob/master/src/ajax/script.js) for `getScript`. The script is always injected as first child of head, so in your example the configuration will end up **after** the call to load MathJax. In that case, MathJax won't be able to detect the configuration (but quirky browser parsing optimizations can make that work at random, depending on page content, connection etc).

I think you can get around this by using your own configuration file and passing it to MathJax by means of a query string.

**Comment by pkra** [comment]
Ooops. @dpvc posted in between and GitHub didn't update my page.

**Comment by pkra** [comment]
> I've incorrectly said that you could do it through the Ajax configuration block (or the root property of the main block), but that turns out not to be the case. You have to set the value directly, as the Ajax module doesn't use a config block (it probably should), and the main root property is copied to the Ajax config only when MathJax is loaded normally through a script tag in the page.


Thanks for correcting me there.

**Comment by dpvc** [comment]
> Thanks for correcting me there.

It is my fault, as you simply used what I had said before.  This behavior should be fixed.  I will open a new issue for it.

**Comment by edemaine** [comment]
The `AuthorInit` callback works, so that's a good fix for now.  I'll look forward to #1403 as a cleaner fix.

Thanks, and sorry for the confusion.  (I must have manually modified in the past and overlooked it when updating...)

I'd also suggest adding some documentation about setting the root -- I can't be the only one doing this -- but maybe that should wait until there's a clean solution (#1403).

**Comment by dpvc** [comment]
PR #1525 includes a fix for this.  I think it should handle your situation as well.

**Comment by pkra** [comment]
Sorry for the labeling noise.  #1403 is the related bug.
