### ISSUE TITLE
Vertical bar in jupyter notebook markdown

### ISSUE THREAD

**Issue by sjlite** [mathjax/MathJax#1406]
A vertical bar seems to be appearing at the right-hand side of every latex expression (e.g., the below). I've upgraded to mathjax 2.6.1, but this seems to persist. Very possible I've missed something silly -- any additional advice?

<img width="81" alt="screen shot 2016-03-06 at 3 54 42 am" src="https://cloud.githubusercontent.com/assets/12721261/13553234/3afe77a2-e350-11e5-9656-0cbb42fe6d48.png">

**Comment by sjlite** [comment]
In ipython notebook*

**Comment by dpvc** [comment]
Make sure that you clear the browser cache and *restart the browser* (several browsers require that to really clear the old copy of MathJax).  Make sure that you are getting the new version by using the MathJax contextual menu to select "About MathJax" and check the version that is displayed.  I suspect you are still getting 2.5, either from the cache, or because your page isn't using the correct location for your 2.6.1 version.

**Comment by meir0001** [comment]
Thanks very much.

 

Regards, 

 

Brian
