### ISSUE TITLE
not able to get asciimath operator above and bellow when using fraction

### ISSUE THREAD

**Issue by survivant** [mathjax/MathJax#1408]
I wanted to asciimath to create my formula.  I wanted to create a basic formula : Mean.  
But I'm not able to get the index (i=1) under the SUM operator.   I was able to find the syntax in TEX that output the good format, but I wasn't able to make it works for asciimath .  

$$\overline{x} = \frac{\sum\limits_{i=1}^n x_i}{n}$$

`bar(x)=(sum_{i=1}^n x_i)/n` 
`bar(x)=\frac{sum_{i=1}^n x_i}n`
`bar(x)=1/n sum_{i=1}^n x_i`  // that one is the patch.

I force displaystyle: true, but that didn't help.

```javascript
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    showProcessingMessages: false,
    linebreaks: { automatic: true},
    tex2jax: { inlineMath: [['$','$'],['\\(','\\)']] },
    AsciiMath: {
    displaystyle: true,
    decimalsign: "."
  }
  } );
</script>

**Comment by pkra** [comment]
AFAIK that's expected behavior. The MathJax configuration option only sets the displaystyle on the top-level element; but the fraction negates that effect. Since asciimath has no means of a local override, there's nothing MathJax can do to change that. You might want to file a feature request upstream at https://github.com/asciimath/asciimathml.
