### ISSUE TITLE
lspace and rspace attributes affecting parent elements.

### ISSUE THREAD

**Issue by ostomachion** [mathjax/MathJax#1412]
When an mrow element contains exactly one mo element and zero or more mtext elements, lspace and rspace attributes on the mo apply to the entire mrow.

Tested on Windows 7 with the latest versions of Chrome, Firefox, Safari, and IE 11.

https://jsfiddle.net/ostomachion/9or7zu2t/1/
http://i.imgur.com/XGXJBuq.png

In the example, every colon is an mo element with lspace and rspace attributes set to 20px.

**Comment by pkra** [comment]
@dpvc will correct me but I think this is the correct behavior for "embellished operators"; see for example https://www.w3.org/Math/draft-spec/mathml.html#chapter3_id.3.1.4.

**Comment by ostomachion** [comment]
I guess you're right. I didn't look into the spec enough.
An [embelished operator](https://www.w3.org/Math/draft-spec/mathml.html#chapter3_id.3.2.5.7.3) can be an mrow whose arguments consist (in any order) of one embellished operator and zero or more space-like elements. And the definition of [space-like elements](https://www.w3.org/Math/draft-spec/mathml.html#chapter3_id.3.2.7.4) includes mtext.

**Comment by dpvc** [comment]
Peter is correct, this is the correct behavior because the mrow forms an embellished operator.  While this definition of embellished operator is often the correct behavior, it has also been a source of problems for people in the past, when something becomes an embellished operator unexpectedly.  My own feeling is that MathML is being too smart for its own good, here, and doesn't give you any reasonable way to override the behavior.  If you could specify `lspace` and `rspace` on elements other than `<mo>`, for example, that would help.
