### ISSUE TITLE
\dot breaks \color ?

### ISSUE THREAD

**Issue by dginev** [mathjax/MathJax#1417]
One of our Authorea users brought to our attention that his "blue dotted W" macro wasn't rendering successfully in MathJax, so I am propagating the request here. 

Minimal example:
```tex
Broken: ${\color{blue}\dot{W}}$
Renders great: $\dot{{\color{blue} W}}$
```

I am guessing the expected MathML for the broken example is something on the lines of:
```xml
    <mover accent="true">
      <mi mathcolor="#0000FF">W</mi>
      <mo mathcolor="#0000FF">&#x2D9;</mo>
    </mover>
```

Thanks for the support!

**Comment by dpvc** [comment]
The default `color` macro in MathJax takes two arguments, the color and the math to be colored.  This is in contrast to the LaTeX implementation, where `\color` is a switch that changes the active color.  So `{\color{blue}\dot{W}}` will act like `\color{blue}{\dot} W`, which is invalid, since it will try to processes `\dot` without any argument.  So you would need `\color{blue}{\dot W}` instead.

If you want the LaTeX-style color command, you must load the color extension via

```
  TeX: {extensions: ["color.js"]}
```

in your MathJax configuration, or via `\require{color}` within an expression on the page.

**Comment by dginev** [comment]
Thanks for the explanation and the recipe on getting the TeX behaviour! It works like a charm.

It was a bit of a gotcha for us, since we weren't aware MathJax has decided to reinterpret some of the standard LaTeX macros. Is there a list of other known differences, so that we can prepare for similar situations with other commands?

Thanks again, I am closing here.

**Comment by dpvc** [comment]
There are very few (intentional) differences.  The `\color` macro is the major one, plus some relaxed syntax for `\llap`, `\rlap`, `\raise`, and `\lower`.  See #133, #1694, and #29 for some discussions of these issues.
