### ISSUE TITLE
[Menu] move from offsetWidth to getBoundingClientRect for positioning [was `.MathJax_Menu` does not exceed a `left` property of >627]

### ISSUE THREAD

**Issue by DizzyZane** [mathjax/MathJax#1434]
Test case: http://dizzyzane.web.fc2.com/markdown/tests/tests.html & http://dizzyzane.web.fc2.com/markdown/tests/tests.html#top (same page, different colouration)

The menu will not go into the right half of the column on a 1280px wide monitor.

Chrome version: Version 51.0.2704.0 canary (64-bit)

Firefox: 45.0.1

**Comment by dpvc** [comment]
MathJax tries to keep the menu within the space allocated to the `document.body` so that the menu is shown within the space of the document when possible (e.g., if the document is in an iframe, it needs to stay within that iframe's space).

Your `document.body` has CSS that sets `max-width: 768px`, so when MathJax asks for the `document.body.offsetWidth`, it gets 768 and thinks that is the size of the space it has to work with.  unfortunately, with an `auto` margin, the `document.body.offsetLeft` is still 0, not the size of the margin, and so MathJax thinks that the document body is flush left.

It may be possible to use `getBoundingClientRect()` to get the correct offset of the body.  The computation of the correct position is pretty fragile, and there are a number of situations like this where it fails.  It may be possible to resolve it in a future release.

@Peter, this might also help with the incorrect positioning of the menu in Readium.

**Comment by pkra** [comment]
@dpvc Readium turned off the menu I think. But it might be useful for the next iteration of the menu.

**Comment by dpvc** [comment]
The `issue1434` branch of my fork of MathJax includes code to better handle the situation when the document body has margins or is scrolled.

**Comment by dpvc** [comment]
==> Merged

**Comment by dpvc** [comment]
==> In testsuite

UI/math-menu/issue1434.html
