### ISSUE TITLE
Double quote inconsistency in CommonHTML font

### ISSUE THREAD

**Issue by booleanbetrayal** [mathjax/MathJax#1439]
I've noticed a bias in how MathJax renders quotations in TeX formulas (both in-formula and within the `\text` directive). It appears that the font favors a closing "right" double-quote rendering. This appears to be relegated to CommonHTML fonts only, but it is evident with the following on the sample modal (default settings):

__CommonHTML rendering mode__

<img width="889" alt="screen shot 2016-04-11 at 11 30 07 am" src="https://cloud.githubusercontent.com/assets/981825/14436195/cbaff060-ffd8-11e5-9e19-88a477dd546b.png">

__HTML-CSS rendering mode (others look similar with "agnostic" quotes)__

<img width="885" alt="screen shot 2016-04-11 at 11 31 36 am" src="https://cloud.githubusercontent.com/assets/981825/14436288/2ce0387c-ffd9-11e5-8a2a-cb85e9edbdb2.png">

Possibly related: https://github.com/mathjax/MathJax/issues/1045

**Comment by dpvc** [comment]
> It appears that the font favors a closing "right" double-quote rendering.

That is correct behavior, and is consistent with actual LaTeX.  Here is the LaTeX output for your example:

![testlatex](https://cloud.githubusercontent.com/assets/432782/14436936/e64205f8-ffec-11e5-8459-96cd1e170af1.png)

The only difference is the spacing in the math-mode version (more on this in a moment).

The reason for this is that TeX fonts have the glyph for the double-right-quote character in the position of the ASCII double-quote (") (i.e, U+0022), and since you have used the same character on both sides of your expression, you should get the same character in both places.  TeX does not do "smart quotes" like some word-processors do.  Indeed, the "proper" way to do quotation marks in TeX is to do ``` ``quoted material'' ``` using two single open quotes at the beginning and two single close quotes at the end.  Using the single character for the double-quote has always been incorrect in TeX.

The reason that you are only seeing this in CommonHTML and not HTML-CSS is that you appear to have the STIX fonts installed on your system, and the HTML-CSS output will use that, when available, in preference to the MathJax TeX fonts.  It turns out that in the STIX fonts, the double-quote character (U+0022) is direction-agnostic (as in your second image), so you don't care that they are both the same character, rather than the smart quotes (U+201C and U+201D).  If you forced HTML-CSS to use the TeX fonts in preference to STIX, then you would get the same thing.  You would also get that from SVG output.

If you really want to use smart quotes, then either enter them directly as unicode character (“ and ”) or using `\unicode{x201C}` and `\unicode{x201D}`.  Note, however, that inside `\text{}`, macros aren't processed, so you would need to use `\unicode{}` outside of any `\text{}` macro.

The issue with the spacing is because TeX treats the double quote as a punctuation character, and so uses the punctuation rules for it (see the *TeXBook* chapter 18, page 170), but since MathJax is only intended for mathematics (not text), it doesn't have the character classes for every possible character (only those that occur in math).  

If you are running your own site and want to add the proper class for the double quote, you could use

```
<script type="text/x-mathjax-config">
MathJax.Hub.Register.StartupHook("mml Jax Ready",function () {
   MathJax.ElementJax.mml.mo.prototype.OPTABLE.infix['"'] = [0,3,6];
});
</script>
```
somewhere *before* the script that loads `MathJax.js` itself.

**Comment by booleanbetrayal** [comment]
Thanks for the detailed breakdown @dpvc ! The `\unicode` macro can work around any edge cases we might have with our content. Thanks again!
