### ISSUE TITLE
maths equations are not rendering at display

### ISSUE THREAD

**Issue by konceptjee** [mathjax/MathJax#1444]
I am facing some problem in Mathjax on current project using mathjax & ajax at same time. What is happening ajax query is pulling the mathematics equation ( which is in Latex form)  from sql database (dynamic in nature)  in a online kind of test but mathjax is not rendering the mathematics equations at display as attached. What is the reason ? If I do referesh 4-5 times than it will display equation.

Please note that I am not from computer science & IT background , no clue about what is happening , this problem is faced by one of the developer in the project.

![image](https://cloud.githubusercontent.com/assets/18501770/14581509/cf9420d8-040c-11e6-9c92-6a5837eab4e6.png)

![image](https://cloud.githubusercontent.com/assets/18501770/14581515/df25f8e6-040c-11e6-8380-9578d06ac8c6.png)

**Comment by dpvc** [comment]
Without more details about what you code is actually doing (like code snippets or a minimal working example), we can't do much to help you.  But I suspect you are not telling MathJax to re-typeset the page once the ajax call has succeeded.  

You should probably read the documentation on [dynamic pages](http://docs.mathjax.org/en/latest/advanced/typeset.html) in MathJax.  Then if you still have questions, post them to the [MathJax user's forum](http://docs.mathjax.org/en/latest/advanced/typeset.html) rather than here (this issue tracker is for bug reports).
