### ISSUE TITLE
support linebreaks in munder

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1449]
It would be nice if something like the following would work. 

```html
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <munder>
    <mrow class="MJX-TeXAtom-OP MJX-fixedlimits">
      <munder>
        <mrow>
          <mi>f</mi>
          <mo stretchy="false">(</mo>
          <mi>t</mi>
          <mo>+</mo>
          <mn>1</mn>
          <mo stretchy="false">)</mo>
        </mrow>
        <mo>&#x23DF;<!-- ⏟ --></mo>
      </munder>
    </mrow>
    <mrow class="MJX-TeXAtom-ORD">
      <mtext>distance at&#xA0;</mtext>
      <mo linebreak="newline"></mo>
      <mtext>time&#xA0;</mtext>
      <mi>t</mi>
      <mo>+</mo>
      <mn>1</mn>
    </mrow>
  </munder>
</math>
```

**Comment by dpvc** [comment]
If you remove the `class="MJX-TeXAtom-ORD"` from the mrow surrounding the line break, it will work.  It turns out that the TeXAtom node is not considered a container whose contents can be broken.  Perhaps that needs to be changed.  You may also wish to add `indentalign="center"` to the mo that is used to obtain the newline.

**Comment by pkra** [comment]
Oh, nice! I shouldn't have been so lazy (constructing this example in TeX) ;-).

**Comment by dpvc** [comment]
The `issue1449` branch of my fork of MathJax includes a fix for this.

**Comment by dpvc** [comment]
==> Merged.

**Comment by dpvc** [comment]
==> In testsuite

MathMLToDisplay/Topics/LineBreak/issue1449.html
