### ISSUE TITLE
MathJax <mi mathvariant=“double-struck”> Common HTML not displaying properly in iOS and Android mobile

### ISSUE THREAD

**Issue by WebStew** [mathjax/MathJax#1451]
**Issue Summary**

Converting our current MathJax rendering option from HTML-CSS to commonHTML is no longer rendering mathvariant="double-struck" characters in some instances.

**Steps to Reproduce**

Visit [CodePen](http://codepen.io/Terminalpunk/pen/pyxPWV) with iPhone 6 Chrome or Samsung Galaxy S5 Chome

**Technical Details**

- MathJax Version: v2.6
- Output : CommonHTML
- Client : iPhone 6 Chrome Version 50.0 iOS 9.3.1 
- Client : Samsung Galaxy S5 Android Version 5 Chome Version 39.0

![double-struck](https://cloud.githubusercontent.com/assets/1636565/14888650/46085c94-0d53-11e6-878f-158662e7372b.PNG)

**Comment by dpvc** [comment]
When you make a reference to a double-strick character like

```
<mi mathvariant="double-struck">&#x1D53D;</mi>
```

you are actually over-specifying the variant.  The character `&#x1F53D;` is already double-struck, so there should be no need to specify `mathvariant="double-struck"` in this case.  The CommonHTML should still handle this situation correctly, but currently doesn't. What's happening is that MathJax doesn't actually find this character in its fonts and so makes a Unicode reference hoping that the character can be found in some font installed on your system.  When you view this from a desktop machine, you apparently have fonts that do include these character positions (perhaps the STIX fonts?), and so the system can display them.  Most mobile devices don't have fonts for these, so they are not being displayed there.

The example that *does* work on the mobiles uses the double struck P, which is at `&#x2119;`, and it turns out that CommonHTML does properly recognize the characters in the Letterlike Symbols block where this one is found, so it is handled properly for you (but note the missing double-struck B and G in the equations including the P's).  The reason that the double-struck B (and G) works in the initial equation is that you used

```
<mi mathvariant="double-struck">B</mi>
```

rather than using the Math Alphabet reference at `&#x1D539;`.

The CommonHTML output *should* translate the Math Alphabetic references to the proper locations in its own font, but it isn't currently doing so (the HTML-CSS and SVG output do, which is why it worked for you before).  This should be fixed, but for now, you could use

```
<mi mathvariant="double-struck">F</mi>
```

rather than

```
<mi mathvariant="double-struck">&#x1D53D;</mi>
```

until we produce a fix for this.

**Comment by dpvc** [comment]
The `issue1451` branch of my fork of MathJax includes the fix for this.

**Comment by WebStew** [comment]
Hey @dpvc 

Many thanks for your swift and detailed responses. Do you have a rough time frame on how long it takes to get this into your latest CDN endpoint?

**Comment by pkra** [comment]
> Do you have a rough time frame on how long it takes to get this into your latest CDN endpoint?

Not at this time.

**Comment by dpvc** [comment]
Until the new version is out, you can add

```
<script type="text/x-mathjax-config">
MathJax.Hub.Register.StartupHook("CommonHTML Jax Ready",function () {
  var CHTML = MathJax.OutputJax.CommonHTML;
  var GETCHARLIST = CHTML.getCharList;
  CHTML.Augment({
    getCharList: function (variant,n) {
      if (n > 0xFFFF && this.FONTDATA.RemapPlane1) {
        var nv = this.FONTDATA.RemapPlane1(n,variant);
        n = nv.n; variant = nv.variant;
      }
      return GETCHARLIST.call(this,variant,n);
    }
  });
});
</script>
```

to your pages, just *before* the script that loads MathJax.js, and that should patch MathJax's CommonHTML output to handle the notation you are currently using.

**Comment by dpvc** [comment]
==> Merged.

**Comment by dpvc** [comment]
==> In testsuite

MathMLToDisplay/Characters/issue1451.html
