### ISSUE TITLE
\widehat over \bigotimes mispositioned in inline style

### ISSUE THREAD

**Issue by orangeplanet** [mathjax/MathJax#1469]
When \widehat is placed over \bigotimes, it looks okay in a display but is pushed to the right when using inline style.  See https://jsfiddle.net/do8m603q/

**Comment by dpvc** [comment]
Thanks for the working example.  The reason for this is because `\widehat{\bigotimes}` produces the MathML

```
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mrow class="MJX-TeXAtom-ORD">
    <mover>
      <mo>&#x2A02;<!-- ⨂ --></mo>
      <mo>&#x005E;<!-- ^ --></mo>
    </mover>
  </mrow>
</math>
```

and it turns out that U+2A02 (N-ARY CIRCLED TIMES OPERATOR) defaults to having `movablelimits`being true in the operator dictionary.  So the `<mover>` is being converted to `<msup>` automatically in text mode.

A workaround for now would be to use `\widehat{\bigotimes\nolimits}` instead, though I know that is awkward.  It would be possible to use a TeX input jax pre-filter to add the `\nolimits` for you.

**Comment by dpvc** [comment]
The `issue1469` branch of my fork of MathJax includes a fix for this.

**Comment by dpvc** [comment]
==> Merged.

**Comment by dpvc** [comment]
==> In testsuite

LaTeXToMathML/above-below/issue1469.html
