### ISSUE TITLE
LaTeX input: Missing space between align columns 

### ISSUE THREAD

**Issue by gunterkoenigsmann** [mathjax/MathJax#1472]
Dear all,

LaTeX leaves a small horizontal space between elements of the align environment so
```
\begin{array}
1&2\\
13&4
\end{array}
```
is output as

```
1 2
3 4
```

MathJax currently outputs it as
```
12
34
```

One minimal example:
```
<!DOCTYPE HTML>
<HTML>
  <HEAD>
    <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
      displayAlign: "left",
      context: "MathJax"
      })
    </script>
    <script type="text/javascript"
	    src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML">
    </script>
    <link rel="stylesheet" type="text/css" href="TableForm_htmlimg/TableForm.css"/>
  </HEAD>
  <BODY>
    \[
    \tag{\%{}t1}\label{t1} \begin{align}1 & 2\\
    3 & 4\end{align}
    \]
  </BODY>
</HTML>
```

**Comment by dpvc** [comment]
The actual output for your (first) example is

![mj-234](https://cloud.githubusercontent.com/assets/432782/15270759/872190ea-19f8-11e6-8b1b-380f2c09d325.png)

although I suspect you meant to use `3` not `13` as the lower left-hand entry).

This is actually correct output, because `\begin{array}` expects an argument (that gives the alignment of the columns).  E.g., I suspect you really want

```
\begin{array}{cc}
1&2\\
3&4
\end{array}
```

to get two centered columns.  Without the `{cc}`, the array used your first entry (`1`) as the array column definitions, and cine MathJax ignores anything that isn't `c`, `l`, `r`, `|`, or `:` in the column pattern, it ignored the `1`.  Then the next thing was `&`, which indicated a blank cell at the upper left.

Your complete-file example includes a link to a CSS file that you have not provided.  If you are not seeing the spacing between the columns, it may be that something there is interfering with the layout, as your CSS can bleed into the MathJax output.  Without that, I can't reproduce the output you describe.

**Comment by dpvc** [comment]
Your full-file example used `\begin{align}` rather than the `\begin{array}` as in your original example.  Again, I am not able to reproduce the result that you describe.  My output is

![mj-1234](https://cloud.githubusercontent.com/assets/432782/15270784/e621f73c-19f9-11e6-8b6e-381e247e824d.png)

which seems to have the correct amount of space.  As above, it may be that your CSS file is causing the problem.  If you remove it, is the output correct?

**Comment by gunterkoenigsmann** [comment]
Then thanks a lot and I have to excuse for all the noise I've caused. Didn't have the css file, either but I did mis-interpret how the align function was supposed to work. Have changed wxMaxima to use an array environment instead - which works fine.

**Comment by dpvc** [comment]
The align environment is designed for aligning equations at their equal signs (or other relations), not producing arrays, and it does not need to be enclosed in math delimiters, e.g.,

```
\begin{align}
  a &= b + c \\
     &= d + e + f
\end{align}
```

whereas the array environment is for creating matrices and other tabular arrays.
