### ISSUE TITLE
Mathjax in html select option

### ISSUE THREAD

**Issue by RichardDumoulin** [mathjax/MathJax#1476]
Hi!

When I use Mathjax content in a select option, for example : 

```
<select>
	
<option value="0">abc </option>
<option value="1">|| x = 2 y ||</option>

</select>
```

On Firefox 46.0.1 : The formula is displayed correctly if the value is NOT selected.  When I select the value with the formula, I see : x = 2 y x = 2 y  

On Chrome 50.0.2661.102 m, I see x = 2y  x = 2y.  The Mathjax formatting is not working in a select.

Could you please let me know if this is a bug or if a workaround is available?

I use the latest version of MathJax on the CDN : https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

Please let me know if you have any question.

Thanks a lot!

Richard

**Comment by dpvc** [comment]
You can not use MathJax output inside a `<select>` element.  The contents of the `<option>` elements are plain text, not HTML (see the [HTML5 Spec](http://www.w3.org/TR/html5/forms.html#the-option-element) which says the content model is text).  Since MathJax output consists of lots of HTML tags, it can't appear inside `<option>` tags.  So you can't use MathJax inside standard browser pop-up menus.  You would have to go with some form of pop-up replacement that implements more sophisticated pop-up menus.  There certainly are packages that do that.  See for example the answers to [this post](http://stackoverflow.com/questions/11237807/can-i-use-html-tags-in-the-options-for-select-elements) on StackExchange for some samples.

**Comment by RichardDumoulin** [comment]
Thanks for the clairification, it make sense.  I will close the issue!

Thanks again! :)
