### ISSUE TITLE
Reprocess on moved DOM element results in duplication of MathJax element

### ISSUE THREAD

**Issue by PhilBroadbent** [mathjax/MathJax#1488]
**Short Description:**
I have a problem where if a DOM element containing a MathJax element is moved, and reprocess is called, that element is rendered twice. 

**Long Description:**
The actual scenario is our API uses MathJax and our client, who embeds our API, also load it with a different config (They use TeX-AMS_HTML - but I’ve tried with many configs and all, excluding default.js, result in this error). 
Client first loads one div with MathJax elements on, they then do a drag and drop on one of the elements
They then load another div with MathJax elements in, and the element which was moved is reprocessed incorrectly and shows a duplicated element. All elements below it are all weirdly shifted, but not duplicated.

I’m not sure how MathJax knows when an element has been processed, but moving the element on the DOM (drag and drop) seems to result in this reference being lost - and so it’s processed again. Calling the below simulates the above scenario (i.e. with only a single section with MathJax in)

`MathJax.Hub.Queue(["Reprocess",MathJax.Hub]);`

**Things I've tried:**
- Of course, removing their second reference resolves this issue but this isn’t possible (we actually have a check to see if MathJax is on the page already, and if so don’t load - this resolved a case of this we had a while back, but doesn’t resolve this particular issue). 
- I saw another bug recently ([1384](https://github.com/mathjax/MathJax/issues/1384)) which also had duplication, so I pulled develop branch which has the fix in and pointed my local to use it and the same config file however the issue still remained.
- I have also found that removing **fast-preview** from the config remove this issue so am wondering whether it’s something to do with fast-preview, or just some fundamental thing in MathJax itself?

Any suggestions please?

**Comment by pkra** [comment]
Can you provide a live sample (your own page or via jsbin/codepen etc)?

**Comment by dpvc** [comment]
It sounds like the drag-and-drop may be handled by setting `innerHTML` on some container element rather than actually moving the original DOM element.  That means any information that MathJax has stored with the DOM elements is lost, and so are any event handlers and other non-attribute-based data.  One way to test this is to see if the MathJax menu is still active on the math after it has been moved.  If not, then that is the likely cause.  Since MathJax uses non-attribute data attached to the DOM elements to track its internal state, that information is lost.

So I suspect that it is a bad use of setting `innerHTML` rather than inserting a DOM node directly.

I'm not sure why you are calling `Reprocess` instead of just `Typeset` or `Process`.  There should be no reason to retypeset existing math if you move it correctly.  `Reprocess` would force all existing math to be retypeset for no reason (unless you need equation numbers to change, or later math depends on macros that might be new in something earlier).  Finally, if there is a new div with new math, why not just typeset the one div rather than the whole page?

**Comment by PhilBroadbent** [comment]
Thanks for your responses. Having look futher into the code after your above comment regarding innerHTML, I found we were not using innerHTML, however, we were cloning the component. We are doing this as we have a use case whereby the original element can be dragged but it must remain in place, and a copy made at the dropzone.

I have modified the code now such that I first remove the MathJax elements (using `getAllJax` and `Remove()`) , then I clone the DOM element (I.e. the raw LaTex node), and later call MathJax render again and this has solved the issue.
