### ISSUE TITLE
Font not reset in TeX boxes

### ISSUE THREAD

**Issue by mhchem** [mathjax/MathJax#1492]
Is this deviating behavior intentional? (I think, I even read a MathJax introduction that praised the less-verbose MathJax way of achieving a goal.)

    $\mathbf{a\fbox{a}a\rlap{a}}$

LaTeX:
![image](https://cloud.githubusercontent.com/assets/16336692/15621308/4d9a73b0-2460-11e6-9008-bf565f6b8a43.png)

MathJax:
![image](https://cloud.githubusercontent.com/assets/16336692/15621314/5ccce3fe-2460-11e6-8448-a1e7ed44be81.png)

**Comment by dpvc** [comment]
In true LaTeX, both `\fbox` and `\rlap` produce text-mode content.  MathJax only implements math-mode macros, not text mode, so text mode is not very useful in MathJax.  In math-mode, the `\llap` and `\rlap` macros often lead to constructs like `\llap{$...$}` and `\rlap{$...$}`.  MathJax's initial tex2jax implementation didn't handle this kind of thing well, and since MathJax doesn't really do text mode anyway, it seemed helpful to make the contents of `\llap` and `\rlap` be math mode automatically.  The efficacy of that decision could be debated, but that is the current state of things.

As for the font being retained in text-mode, because MathJax doesn't process macros inside text mode, there is no way to switch fonts within `\text{}` and the other text-mode macros, so MathJax retains the font selection within text mode so that you can do things like `\bf\text{bold text}` or `\sf\text{sand-serif text}`.  While inconsistent with TeX, this is a compromise to allow some control over the text-mode font.

In your case, you could use `\mathrm{\fbox{...}}` and `\rlap{\mathrm{...}}` if you want to guarantee the roman font.

**Comment by mhchem** [comment]
I almost thought that it was intentional, but then I stumbled across #1321. With your explanation I completely understand your reasoning and the difference between the issues. That was very helpful.

**Comment by dpvc** [comment]
OOPS! Deleted my message when I meant to edit it (for a typo).  Do you still have a copy in email?  I would like to put it back.

**Comment by dpvc** [comment]
For the record, here'e the original message again:

In true LaTeX, both `\fbox` and `\rlap` produce text-mode content.
MathJax only implements math-mode macros, not text mode, so text mode is
not very useful in MathJax. In math-mode, the `\llap` and `\rlap` macros
often lead to constructs like `\llap{$...$}` and `\rlap{$...$}`.
MathJax's initial tex2jax implementation didn't handle this kind of
thing well, and since MathJax doesn't really do text mode anyway, it
seemed helpful to make the contents of `\llap` and `\rlap` be math mode
automatically. The efficacy of that decision could be debated, but that
is the current state of things.

As for the font being retained in text-mode, because MathJax doesn't
process macros inside text mode, there is no way to switch fonts within
`\text{}` and the other text-mode macros, so MathJax retains the font
selection within text mode so that you can do things like `\bf\text{bold
text}` or `\sf\text{sand-serif text}`. While inconsistent with TeX, this
is a compromise to allow some control over the text-mode font.

In your case, you could use `\mathrm{\fbox{...}}` and
`\rlap{\mathrm{...}}` if you want to guarantee the roman font.
