### ISSUE TITLE
Need check for undefined imgEmWidth error in imageFonts.js

### ISSUE THREAD

**Issue by brassogre** [mathjax/MathJax#1494]
I was running the unpacked version of MathJax from a bundle in an OS X app with Webkit.
My math was rendering correctly at first, but then after 15 seconds, I was getting the following error:
Math Processing Error,[object HTMLScriptElement],TypeError: undefined is not an object (evaluating 'this.imgEmWidth.length')

After tracking the issue down, I found that something was calling initImg: function (span) in jax/output/HTML-CSS/imageFonts.js

The this.imgEmWidth.length in the following was failing because this.imgEmWidth is undefined.

        for (var i = 0, m = this.imgEmWidth.length-1; i < m; i++)
          {if (this.em <= this.imgEmWidth[i]) break}

I fixed it just by wrapping these 2 lines with 
if (this.imgEmWidth) {

}
and with that fix, my correctly rendered math was not replaced with a Math Processing Error.

I don't know the code-base enough to know whether the function should never be called with an undefined imgEmWidth.

**Comment by dpvc** [comment]
The 15 second delay suggests that MathJax is trying to load its fonts, but is failing to do so, and is switching to image mode.  I doubt try much that you installed the image fonts as part of your bundle, so you certainly don't want that to happen.  (Indeed, you should set `imageFont: null` in the `HTML-CSS` block of your MathJax configuration to prevent it from switching to image fonts of you haven't included them with your app.)  The error message you are getting is due to the lack of the image fonts in your trimmed-down version of MathJax.

So the question is why the fonts aren't loading.  Did you install them in your app?  What do you see if you add

```
<script>
MathJax.Hub.Queue(function () {alert(MathJax.Message.Log())});
</script>
```
after the script that loads MathJax.js?

**Comment by brassogre** [comment]
Your diagnosis was correct. I had a font designated as available without copying it into my app. Your advice fixed all my issues. (Though I was not able to get the MathJax.Message.Log() info.)

Still, I don't think MathJax should signal a missing font error by throwing an undefined object error in the imgEmWidth. That's not reporting the problem where it should be reported. My preference would be for it to switch to the image font if the image is not rendering correctly, and if the image font is set as null, just leave the initial rendering as is. So I would still suggest adding the wrapping code, which at least gets closer to a better behavior. Or throw a missing font error instead.

Thanks!

**Comment by dpvc** [comment]
> I don't think MathJax should signal a missing font error by throwing an undefined object error in the imgEmWidth.

It doesn't.  The message log will have a message about the font being unavailable and that it is switching to image fonts.  The image fonts are the fallback, but you removed them from your installation without properly informing MathJax of that by setting `imageFont: null`.  The error message about the undefined object is not because of the missing web font, but because of the missing data files that you removed.  If you take away the MathJax data files for the image fonts, and it tries to use those fonts, certainly things will go wrong.  That is not a situation that MathJax should have to handle gracefully.

> My preference would be for it to switch to the image font if the image is not rendering correctly, and if the image font is set as null.

That is what is supposed to happen, but it does rely on your not having removed parts of the MathJax code.  The data files for the image fonts are where the `imgEmWidth` value is defined.  It is better to have MathJax produce a math processing error so that you can replace the missing files than to silently ignore the fact that the data wasn't loaded and let you think that things are OK when they aren't.  The math processing error message is an indication of a fairly catastrophic problem (and I think missing data files classify as that), so that is telling you that something serious is wrong.  The message log would have told you about the data file failing to load.  Preventing the error from occurring would mean you were never alerted to the problem, and would never have fixed it.  I maintain that this is correct behavior.

**Comment by pkra** [comment]
>  If you take away the MathJax data files for the image fonts, and it tries to use those fonts, certainly things will go wrong. 

@dpvc we excluded them from the npm package for sanity reasons; that might catch a dev unaware. Perhaps we can come up with an idea for communicating that better to npm users (e.g., via an installation warning on npm or some such thing).

**Comment by dpvc** [comment]
Can we set `imageFont: null` as the default in the version used for npm?  As I recall, it is coming from a separate branch anyway, so why not just change that default for that branch?

**Comment by pkra** [comment]
> As I recall, it is coming from a separate branch anyway, so why not just change that default for that branch?

I'm afraid it is no longer a separate branch. The releases correspond to our git tags.

**Comment by brassogre** [comment]
Thanks. I take it the "data files for the image fonts" are also in the font folder along with the image fonts themselves. It was not obvious that a needed component would be in that folder. It looks mostly optional.

**Comment by dpvc** [comment]
>  I take it the "data files for the image fonts" are also in the font folder along with the image fonts themselves.

Yes, that is correct.

> It was not obvious that a needed component would be in that folder. It looks mostly optional.

It is optional, provided you set `imageFonts: null` in the `HTML-CSS` block of your MathJax configuration.  See the [FAQ](http://docs.mathjax.org/en/latest/misc/faq.html?highlight=imagefont#the-mathjax-font-folder-is-too-big-is-there-any-way-to-compress-it) for some documentation on this, as well as the [MathJax Users Forum](https://groups.google.com/d/msg/mathjax-users/2SrqHRd9tmA/sGNOKBAbAb4J).
