### ISSUE TITLE
MathJax.Hub.Queue variable as a third param

### ISSUE THREAD

**Issue by Krzysiu-lifeinmobile** [mathjax/MathJax#1495]
Hi!

I use a MathJax with VueJS and with a lot of situation I need rerender a MathJax element on my page.
I want to use a variable as a third param in MathJax.Hub.Queue() function, to rerender MathJax formula in my site, something like this:

```
var el = '.formula1'
MathJax.Hub.Queue(["Typeset", MathJax.Hub, el]);
```

Everything is ok, when I insert a string directly to function, but when I change the string on variable, something is wrong.. I don't understand it..

Could someone help me with this problem? :)

**Comment by dpvc** [comment]
Note that the element ID passed to the `Typeset()` function is not a CSS selector, it is an actual element ID.  Your `el` value looks like you are trying to use a class name (it begins with a dot), but unless you have an element with the attribute `id=".formula1"`, this isn't going to work.

You don't really provide enough information to give you much assistance.  You should provide a minimal working example using codebin or jsfiddle, for example so that we can help you better.

**Comment by dpvc** [comment]
Also, we prefer that you don't cross post your question to several places at once, as that makes it harder for us to answer your question (or it leaves your question unanswered in several locations).  You should go back to the other places you've posted the question and point them to this issue tracker.
