### ISSUE TITLE
[CommonHTML] equation label not properly aligned in large arrays with many labels

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1500]
Examples

* Tags become vertically lower than the cell

```latex
 \begin{eqnarray} 
 a \tag{tag}\\ 
 a \tag{tag}\\ 
 a \tag{tag}\\ 
 a \tag{tag}\\ 
 a \tag{tag}\\ 
 a \tag{tag}\\ 
 a \tag{tag}\\ 
 a \tag{tag}\\ 
 a \tag{tag}\\ 
 a \tag{tag}\\ 
  \end{eqnarray}
```

* Tags become vertically higher than the cell

```latex
\begin{eqnarray} 
&& a \tag{tag}\\ 
&& a \tag{tag}\\ 
&& a \tag{tag}\\ 
&& a \tag{tag}\\ 
&& a \tag{tag}\\ 
&& a \tag{tag}\\ 
&& a \tag{tag}\\ 
&& a \tag{tag}\\ 
 \end{eqnarray}
```

Screenshot (combined)

![labels](https://cloud.githubusercontent.com/assets/426686/15747209/f6ecc8aa-28d9-11e6-9099-d05302adb2e2.png)

**Comment by pkra** [comment]
Oh wow. 1500 bugs!

**Comment by dpvc** [comment]
It turns out that there were several issues that contributed to this.  One was that the heights of the lines were being adjusted to the wrong value (argh).  But there were also issues with empty cells (it turns out inline-block node with no text content align differently from those with text content), and with nodes whose height is less than the midpoint of the font (didn't appear in your examples, but did in my own tests).

I think I have taken care of all of them in the `issue1500` branch of my fork of MathJax.

**Comment by dpvc** [comment]
==> Merged.

**Comment by dpvc** [comment]
> Oh wow. 1500 bugs!

Well, because pull requests use the same numbers as issues (and we've been using more pull requests lately), there aren't really 1500 bugs.  There are 1220 issues (not all of them bugs) and 204 pull requests as of this posting.  So I'm not sure what the other items 76 are!

**Comment by pkra** [comment]
> So I'm not sure what the other items 76 are!

Hm... the numbers I see do add up (maybe you had a filter on?) But yes, over 200 PRs in total -- still awesome :-)

**Comment by dpvc** [comment]
==> In testsuite

MathMLToDisplay/Presentation/TablesAndMatrices/issue1532.html
