### ISSUE TITLE
Force Firefox to render just in HTML

### ISSUE THREAD

**Issue by maliknur** [mathjax/MathJax#1502]
By default Firefox (ver 46) renders MathJax in MML, so can't switch it to HTML-CSS view
tried following, but still mml instead of html renders

```
        MathJax.Hub.Config({
          MMLorHTML: { prefer: { Firefox: "HTML" } },
          jax: ["input/TeX", "output/HTML-CSS"]
        });
```

**Comment by dpvc** [comment]
> By default Firefox (ver 46) renders MathJax in MML

That is false.  For configurations that use `config=` with a combined configuration ending in `HTMLorMML`, all browsers use HTML-CSS except for IE with MathPlayer installed.  No combined configuration file selects MathML output for any other browser.  If you are getting MathML, then it may be because you have used the MathJax contextual menu to select NativeMML output.  Right-click on any typeset mathematics and select "Math Settings" then "Math Renderer" to see which renderer is selected.  Switch to the one you want.  Or clear the cookie for your site and reload the page.

You have not given the complete configuration for your site, which would include the script that loads MathJax.js.  That is the line that contains the combined configuration file (if any) that you used.  It is not really possible to diagnose your problem without that information.  A link to the actual page you are working with would be even better.

**Comment by maliknur** [comment]
Oh right, sorry that mathml was inside of iframe and MathJax library couldn't reach it from outer html. Therefore at the moment of rendering Firefox used native mathml instead of to following MathJax's settings. I'm closing an issue.
