### ISSUE TITLE
Setting renderer with reveal.js

### ISSUE THREAD

**Issue by blubbsy** [mathjax/MathJax#1506]
Hi,

iam trying to use MathJax in combination with reveal.js, but i want to have the same font i use with reveal.js also for equations. How is this possible? I noticed that when i choose manually PreviewHTML as renderer i obtain the desired font (CommonHTML creates slightly thicker letters). 

For this i added `MathJax.Hub.setRenderer("PreviewHTML");` (at line 35) to the [math.js](https://github.com/hakimel/reveal.js/blob/master/plugin/math/math.js) provided with reveal.js, but then i receive a "Math processing error" (CommongHTML, SVG etc works fine). Why is this so, how can i fix it and did some has this problem too?

Greetings,

Blubbsy

**Comment by pkra** [comment]
> How is this possible?

The documentation at http://docs.mathjax.org/en/latest/font-support.html describes MathJax's font support. In short, you cannot use arbitrary fonts with MathJax (except by doing a lot of development work). The PreviewHTML is also not independent of the fonts but designed for a Times-like font.

> For this i added MathJax.Hub.setRenderer("PreviewHTML"); (at line 35) to the math.js provided with reveal.js, but then i receive a "Math processing error"

Please provide a live sample that exhibits the problem.

**Comment by blubbsy** [comment]
Well then i think the times-like font is the one i want. 

I uploaded the whole project (reveal.js with the plugins and mathjax) to https://www.dropbox.com/s/049ffrrtl4epz3m/Demonstration.7z?dl=0 . The slide shows the described problem and the math.js is modified as mentioned above. I hope that is what you wanted.

**Comment by pkra** [comment]
> I hope that is what you wanted.

An actually hosted page is preferrable, if only for security.

From a quick look, this example loads fine for me from a webserver but has issues if loaded from file://. However, Reveal is throwing an error in the console and is generally broken so I'd suggest you start looking into that.

**Comment by dpvc** [comment]
Note that there are output features that are no implemented by the PreviewMath renderer.  For example, the stretchy accents are not implemented (e.g. `\overrightarrow` does not stretch), and the placement of many accents will not be ideal (e.g. `\overline`, `\overbrace`).  Equation numbers aren't implemented.  Vertical stretchy characters are only placed approximately, and the larger they are the uglier they will be.

So if you choose to use it, beware that not everything will look as good as the other renderers.  Also note that the weight of the fonts is highly dependent on the operating system that you are using.  Windows font renderings are often much thinner than the corresponding Mac and Unix renderings, and so others may not see the mismatch that you see.

Finally, you might want to consider using HTML-CSS output with the STIX fonts rather than the default MathJax TeX fonts.  Those look more like the Times font.

**Comment by dpvc** [comment]
If you want to change to PreviewHTML output, then you should change [lines 13 to 22](https://github.com/hakimel/reveal.js/blob/master/plugin/math/math.js#L13-L22) to be

```
	loadScript( options.mathjax, function() {

		MathJax.Hub.Config({
			jax: ["input/TeX","output/PreviewHTML"],
			extensions: ["tex2jax.js","AssistiveMML.js"],
			TeX: {
				extensions: ["noErrors.js","noUndefined.js","AMSmath.js","AMSsymbols.js"]
			},
			messageStyle: 'none',
			tex2jax: {
				inlineMath: [['$','$'],['\\(','\\)']] ,
				skipTags: ['script','noscript','style','textarea','pre']
			},
			skipStartupTypeset: true
		});
```
