### ISSUE TITLE
real LaTeX's error-correcting behavior

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1517]
[Over on Wikmedia's phabricator](https://phabricator.wikimedia.org/T136932), they're collecting problems from the switch to MathJax on the Wikipedia backend.

The particular example I link to has something like ` {\mathop {\max} }\limits_a^b` where real LaTeX gives a warning that it will ignore `\limits` -- yet MathJax just fails.

I'm wondering whether or not such error-correcting behavior would be a reasonable feature request.

@dpvc has this ever come up?

**Comment by dpvc** [comment]
When I process `{\mathop {\max} }\limits_a^b`, I get the message `\limits is allowed only on operators`.  Of course, if you have the noErrors extension in play, you will get the original TeX in a box.  In mathjax-node, I get the output `TeX parse error: \limits is allowed only on operators` on the error output.  I don't know what method does with the errors, but if it is not reporting them in some way, that is something they would need to work on, as MathJax already does report the error.

**Comment by dpvc** [comment]
Sorry, I misunderstood.  You want to have an error reported but have MathJax go on.

**Comment by dpvc** [comment]
The reason this wasn't done is that there is no obvious place to put the error message (unless you want to ignore the error entirely).  The error console will not be seen by anyone.  An alert is too intrusive.  Do you have something in mind for where that should go?

**Comment by pkra** [comment]
I'm not after the error message, actually. I'm interested in the error-correcting behavior, i.e., still getting a result despite incorrect input. 

Here's what pdfTeX gives me.

```
...
! Limit controls must follow a math operator.
l.10 $ {\mathop {\max} }\limits
                               _a^b$
I'm ignoring this misplaced \limits or \nolimits command.
...
```

What I'm after is the final line  about `I'm ignoring this misplaced \limits or \nolimits command`. Despite the error, pdfTeX still continues and produces an output.

Anyway, it sounds like this has not come up which is what I wanted to know :smiley:

**Comment by dpvc** [comment]
> What I'm after is the final line about I'm ignoring this misplaced \limits or \nolimits command. 

Right, but where do you want that to go?  If it goes in the console, no one will see it (when running in the browser), and if you put it in place of the math, this precludes showing the math.  So I just don't know ho two give you the rest you are looking for.

Also, when I run the example you give in either LaTeX or plain TeX, I get the error message (but not the "I'm ignoring..." message), but the process stops for me to do something about it.  I suspect that the result may be dependent on the document class or some other package that you are using.  In any case, it doesn't seem to happen in `\documentclass{amsart}` for me with no other packages loaded, so that may be why no one is asking for it.

> Despite the error, pdfTeX still continues and produces an output.

For the most part, in my experience, when TeX tries to auto-recover from a problem (missing brace, or missing `$`), it usually makes things worse.  I would rather tell people what is wrong and have them fix it than to continue to process incorrect TeX so that they have no incentive to fix it.

**Comment by pkra** [comment]
> would rather tell people what is wrong and have them fix it than to continue to process incorrect TeX so that they have no incentive to fix it.

Thanks, that's what I wanted to know. :+1:
