### ISSUE TITLE
Certain formulas prevent MathJax from finishing rendering

### ISSUE THREAD

**Issue by paweldudek** [mathjax/MathJax#1518]
First of all I'd like to say thank you for building such an awesome piece of open source software! You guys rock! 

Second of all I'm not super experienced with LaTex and JS so I might have missed a ticket for this issue - this might be a duplicate. If so then I'm sorry!

Alas, to the point. I'll be short. Entering following formula:

```
$$\begin{aligned}|A_1\cup\dots \cup A_n|&=\sum_i|A_i|-\sum_{i<j}|A_i\cap A_j|\\&+\sum_{i<j<k}|A_i\cap A_j\cap A_k|-\dots+(-1)^{n+1}|A_1\cap\dots\cap A_n|\end{aligned}$$
```

hangs MathJax - I'm not getting any rendered output.

### Issue Summary

We're using MathJax to render LaTex formulas into SVGs and then display them in our app. One of our users recently reported that entering this formula prevented LaText from being displayed. 

I did a bit of digging and it looks like this formula prevents any sort of output after MathJax hits it and tries to parse it.

### Steps to Reproduce

1. Use the aforementioned formula in MathJax
2. MathJax hangs and doesn't produce any output

Expected: MathJax should return a rendered formula. 

I've also tried using this formula in Live Demo mode on your website and here's the result I got (both browsers, see below): 

<img width="889" alt="screen shot 2016-06-10 at 11 14 23" src="https://cloud.githubusercontent.com/assets/968513/15959756/8e7d4e88-2efc-11e6-8948-0a616e15bd85.png">

### Technical details:

* MathJax Version: 2.6
* Client OS: Mac OS X 10.11.5
* Browser: Happened on both Safari Version 9.1.1 (11601.6.17) and Chrome Version 51.0.2704.84 (64-bit)

**Comment by pkra** [comment]
This is expected behavior.

If you don't  escape `<` `>` (and `&`), browser might parse them as element (or for `&` entity) names, leading to erratic DOM results.

Since this happens long before MathJax gets to the equation, there's nothing MathJax could do to work around this -- the DOM simply contains no discernible mathematics to pick up.

If you escape your strings properly, you shouldn't have any trouble.

You might also want to check out the docs of the noErrors and noUndefined extension, http://docs.mathjax.org/en/latest/tex.html#noerrors etc.

**Comment by paweldudek** [comment]
@pkra thanks for the info 🎉 that was the exact issue! 

I'm closing this issue as it's working as expected. 

One idea that came to my mind - perhaps it'd be nice to add escaping to aforementioned Live Demo? That would make experience consistent (aka that formula *should* work). 

Or display information that this formula contains unescaped characters and thus it will not render correctly. 

I'd love to do this myself, but my JS/HTML skills are a bit... rusty. 😉 Should I add this to https://github.com/mathjax/MathJax-website ?

**Comment by dpvc** [comment]
One is allowed to enter HTML in the demo, and so unescaped characters are legal, and you are seeing the behavior the you would get if you entered that formula in an actual web page.  it is not clear to me how one would identify this situation (other than looking for "foreign" tags, like the `<j>` tag that your equation would introduce).  But foreign tags are also legal, so such a test would be quite fragile.

**Comment by dpvc** [comment]
>  (aka that formula *should* work)

No, that formula should *not* work in an HTML page.  That's the point.  If you entered what you did in an HTML page and ran MathJax on it, you would get the same output you see above.  That's part of how HTML works, and MathJax can't resolve that in an HTML page, because the conversion to HTML tags has been completely long before MathJax runs.  So it can't spot this or fix it for you.

Some more information about the fact that you are entering HTML at the top of the demo is the only thing I can think of that would help the situation.  This is implicit in the fact that you are allowed to enter MathML tags, but it could be stated more explicitly.

**Comment by paweldudek** [comment]
@dpvc I see the point now, I forgot you can also input plain HTML there. Adding logic to validate input in this case sounds insanely complicated. You're completely right, this works exactly as it should right now. 

Adding some sort of information that you're entering HTML there (and thus certain MathJax formulas might not work due to escaping) would be a nice touch there. 

Sorry for the confusion and once again thanks for the feedback and the awesome framework you're building 🚀

**Comment by dpvc** [comment]
Thanks for the kind words!

**Comment by paweldudek** [comment]
Np, you deserve it! I've added an issue on website repo to keep track of this!
