### ISSUE TITLE
Problem with mathml and !

### ISSUE THREAD

**Issue by scaljeri** [mathjax/MathJax#1553]
When I render

    <math><mstyle displaystyle="true"><mrow><mfrac><mrow><mn>24</mn></mrow><mrow><mrow><mn>5</mn></mrow>!</mrow></mfrac>

I get the following error

![unspecified 2](https://cloud.githubusercontent.com/assets/1078741/16660404/690d4e96-446e-11e6-8382-3888a5d04a24.png)

Any ideas why MathJax throws this error ?

I'm using the 'latest' mathJax and have the following config:

![unspecified](https://cloud.githubusercontent.com/assets/1078741/16660528/f7221ffe-446e-11e6-87d1-532557ca4a24.png)

**Comment by dpvc** [comment]
The error message is because the exclamation point is not enclosed in a MathML tag as it should be.  You probably want `...</mrow><mo>!</mo></mrow>...`.  In MathML all text must be enclosed in some form of MathML token element (like `<mn>`, `<mi>`, `<mo>`, `<mtext>`, etc.), and a text node outside of a token element produces the message you are receiving.

**Comment by scaljeri** [comment]
Thanks a lot for pointing that out, I missed that one!
