### ISSUE TITLE
Margins in mathjax using latex

### ISSUE THREAD

**Issue by libedinsky** [mathjax/MathJax#1559]
When using latex in mahtjax, all the text appears in only one line, going beyond the margins of the box. For example, if in http://cdn.mathjax.org/mathjax/latest/test/sample-dynamic-2.html I put:

Margin Margin Margin Margin Margin Margin Margin Margin Margin Margin Margin Margin Margin Margin Margin Margin Margin
$\text{Margin Margin Margin Margin Margin Margin Margin Margin Margin Margin Margin Margin Margin Margin Margin Margin Margin }$

The text that is not in latex, stays in the box of the preview and the text in latex goes over the margin of the box. Is there any way to compile so that the text (or equations) stay in the previously defined box?

**Comment by pkra** [comment]
MathJax supports automatic line-breaking but it's not turned on by default (for performance reasons), cf. http://docs.mathjax.org/en/latest/output.html#automatic-line-breaking.

**Comment by libedinsky** [comment]
Thanks!

**Comment by dpvc** [comment]
Note:  MathJax's line breaking really only applies to displayed equations (in-line equations will line break only of they are longer than a full line), and the contents of `\text{}` will not be broken, just as it would not be in actual LaTeX.

It is not clear what situation you are actually dealing with but the example you give should *not* be broken because LaTeX doesnt break within the `\text{}` macro.

**Comment by libedinsky** [comment]
I just want to write a regular math problem that has to fit into a window, which includes text and equations. I tried using text not inside the $$ delimiters, and that actually breaks the line when they get to the width of the window, but then, when I put an equation inside: $ x^2 $, the font changes, so it looks weird with the text. That's why I tried to put \text{} because that maintains the font style of the equations and the text. But if there is no line breaking with the \text{} macro , then I should find a different solution. Any ideas?

**Comment by dpvc** [comment]
> when I put an equation inside: `$ x^2 $`, the font changes, so it looks weird with the text. ... Any ideas?

Yes, change the font of the surrounding text to match the math fonts better.  For example, use Times or another serifed font rather than Arial or other sans-serif font.  If you want to be even more consistent, you can use the MathJax_Main font as your text font (using an `@font-face` CSS directive, and you can even use the fonts from the MathJax CDN that way).  You may need to adjust the `line-height` CSS, since the font is not designed to be used outside of MathJax, and so is a bit taler and deeper than you might want it to be.

**Comment by libedinsky** [comment]
Thanks for your answer. I actually managed to change the font of the surrounding text and it actually looks better.

**Comment by dpvc** [comment]
Glad you got it to work.
