### ISSUE TITLE
new line not recognized 

### ISSUE THREAD

**Issue by libedinsky** [mathjax/MathJax#1561]
In the mathjax demo: 
"$\mathrm{q} \approx 0,04. \\\ $ But..." reads fine the new line ( \\\ ). 
But in http://cdn.mathjax.org/mathjax/latest/test/sample-dynamic-2.html, it doesn't recognize the new line. Not sure how to make the newline appear.

**Comment by dpvc** [comment]
New lines in in-line math don't work the way you might expect.  They are really only appropriate for displayed math.  The results also vary depending on the renderer.  Note that the sample-dynamic-2 page uses the HTML-CSS renderer, while the demo page at mathajx.org uses the CommonHTML renderer.

With the HTML-CSS renderer, line breaks in in-line math would produce something like

```
     blah blah blah   math-line-1   blah blah blah
                                math-line-1
```

where the two lines of the math are put into a box as wide as the widest line, and aligned with the rest of the text on its top line.  Since your second line is empty, you don't notice this with HTML-CSS output.

In the CommonHTML output, however, newlines force the in-line math to produce full-width boxes (the HTML-CSS approach turned out to be a source of confusion, like yours, and so the newer CommonHTML output handled it differently).  That is why the MathJax demo acts differently.

In any case, you are trying to use the math to do what the HTML page itself should be doing.  A better approach would be to use

```
    $\mathrm{q} \approx 0,04.$ <br/> But...
```

instead.  Do the page formatting in HTML, and the math formatting in MathJax.
