### ISSUE TITLE
Multiple font declarations cause incorrect width calculations

### ISSUE THREAD

**Issue by jmlear** [mathjax/MathJax#1566]
Check out this jsfiddle: https://jsfiddle.net/8rzov37b/

When you have two conflicting font declarations, MathJax calculates the width to be larger than it should be.

**Comment by dpvc** [comment]
The problem is the styling of `.math`.  You should not style any of the MathJax output classes with CSS that changes the size of the element (like your `font-size` does) as that will mean that MathJax won't know the size of the elements properly (as you have seen).  You also can't change the font used by the math using CSS (you can only do this via the MathJax configuration, and then only to one of the fonts for which MathJax has the font data available).

If you are trying to change the size of the math, then you should set the `scale` configuration option in the `"HTML-CSS"` block of your MathJax configuration (see the [documentation](http://docs.mathjax.org/en/latest/configuration.html#using-in-line-configuration-options) for how to do that).  

Alternatively, you could set the `font-size` in for the `.math_expression` class that you are using to wrap the mathematics.

**Comment by jmlear** [comment]
Thank you @dpvc . I understand that we should not use the .math class for styling, but now I'm not sure how to make the Math display the right size any more. If you just change the css to .math_expression we get a smaller final font when Mathjax renders it. Could you possibly show what would need to be done using the fiddle to yield the same result just without the extra trailing space?

**Comment by dpvc** [comment]
Add

```
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  "HTML-CSS": {scale: 114}
})
</script>
```

to your page somewhere *before* the script that loads MathJax.js itself, and remove the CSS for the `.math` selector.
