### ISSUE TITLE
Error depends on request rate, packed vs. unpacked, and (maybe) large parentheses

### ISSUE THREAD

**Issue by skieffer** [mathjax/MathJax#1571]
Hi, and first let me say thank you for this excellent software! It has allowed me to make some nice web applications I could never have made without it. : )

I'm having an issue that I can't seem to resolve. I'm using the latest commit of MathJax as of this date, d4ab1b3....

When typesetting mathematics dynamically in a page, I sometimes get "Math Processing Error", and it seems to depend on three things:

  (1) the rate at which requests are sent to MathJax
  (2) whether I'm using the minified or unpacked version of MathJax.js
  (3) (maybe) whether extra-large parentheses are being typeset

I have created a simple page that demonstrates the problem: http://skieffer.info/mjissue.html
and I also paste the full html below.

Note in particular that the problem only occurs with the minified version of MathJax.js.
If I try it with the unpacked version, the problem goes away! This makes it really hard to debug!

Honestly I'm not sure if this is a bug or if I'm just following an unrecommended design pattern,
but the page I've linked above is quite simple.

For me the issue arises in all browsers I've tested: Opera 38.0, Chrome 51.0.2704.103, Firefox 47.0, and Safari 9.1.1. I'm on OS X 10.11.5.

Hope you can help.
Thanks.

```html
<!DOCTYPE html>
<html>
<head>
<style>
li {
    padding: 7px 0px;
}
a {
    display: inline-block;
    padding: 10px;
    margin: 10px;
    border: ridge;
    border-radius: 8px;
    background: gray;
    color: black;
    text-decoration: none;
}
body {
    font-family: "Helvetica Neue", Helvetica, sans-serif;
    font-size: 20px;
}
#mainBox {
    margin: auto;
    width: 500px;
}
#textBox {
    text-align: justify;
    padding-top: 16px;
}
#buttonBox {
    text-align: center;
}
</style>
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    extensions: ["tex2jax.js"],
    jax: ["input/TeX", "output/SVG"],
    tex2jax: {
      inlineMath: [ ['$','$'] ]
    },
    "SVG": { availableFonts: ["TeX"] }
  });
</script>
<script type="text/javascript" src="mathjax/MathJax.js?config=TeX-AMS-MML_SVG-full"></script>
<script>
function f1() {
    addItem("$\\left(a\\right)$")
}

function f2() {
    addItem("$\\left(a^2\\right)$")
}

function addItem(tex) {
    var li = document.createElement('li');
    li.innerHTML = tex;
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, li]);
    document.getElementById("list")
            .appendChild(li);
}
function clear() {
    var list = document.getElementById("list");
    while (list.hasChildNodes()) {
        list.removeChild(list.lastChild);
    }
}
</script>
</head>
<body>
<div id="mainBox">
    <div id="textBox">
        <h1>MathJax Issue</h1>
        <p>
        These buttons ask MathJax to typeset some TeX.
        Button 1 always works. Try it.
        </p>
        <p>
        Now try Button 2. Keep clicking. If you click slowly, it won't work, but
        if you click fast enough, it will.
        </p>
        <p>
        What's going on?
        </p>
        <p>
        The only difference is that Button 1 typesets $\left(a\right)$ while
        Button 2 typesets $\left(a^2\right)$.
        </p>
        <p>
            The problem only occurs with the minified version of MathJax.js,
            not with the unpacked version.
        </p>
    </div>
    <div id="buttonBox">
        <a href="javascript:f1()">Button 1</a>
        <a href="javascript:f2()">Button 2</a>
        <a href="javascript:clear()">Clear</a>
        <ol id="list"></ol>
    </div>
</div>
</body>
</html>
```

**Comment by pkra** [comment]
Thanks for the report. We'll take a look.

**Comment by dpvc** [comment]
The problem, here, is that you are trying to run MathJax on an HTML fragment the is not part of the page (your `addItem()` function calls `MathJax.Hub.Queue(["Typeset",MathJax.Hub,li])` before the `li` is attached to the page).  Under some circumstances, MathJax must look up elements in the page via their ids; but if the typeset element is not *in* the page, that will fail.  Stretchy characters (like the parentheses in your second example) are one such case, this is why it fails when the first one doesn't.

The reason that there is a difference between the packed and unpacked versions is that the packed combined configuration files actually includes all the code for all the components they load, whereas the unpacked combined configuration files only set up the loading to occur when they are needed.  Note that the MathJax `Typeset()` call is asynchronous, so that it may return before the typesetting has occurred (when it needs to load external resources).  In the unpacked case, since the MathJax files are *not* already loaded, the `Typeset()` needs to load some external files, and so the `MathJax.Hub.Queue()` call returns before the typesetting is complete, and the `li` is then added to the page, so by the time MathJax needs to look up elements by their ids, they actually *are* in the page.  On the other hand, with the unpacked files, the resource is already loaded, and so the typesetting can be performed without loading anything else, so the `MathJax.Hub.Queue()` performs the complete `Typeset()` call before returning.  In this case, the `li` *hasn't* been added to the page when it is needed, so you get the error.

Although you are using the SVG output, you should note that the "fast-preview" is on by default, and it is actually that component that is needing to look up element ids.  So one solution would be to disable that in your configuration (you probably don't need it if you are only adding one equation at a time anyway).  E.g.,

```
MathJax.Hub.Config({
  "fast-preview": {disabled: true}
});
```

The SVG output doesn't need to look things up by id, so that would be one way to avoid the problem.  But since users can change the output renderer via the contextual menu, a better way would be to insert the `li` *before* calling MathJax to do the typesetting.

**Comment by skieffer** [comment]
Thank you for this thorough explanation!

I'm now adding the elements to the page before typesetting, and that works like a charm. Simple solution -- maybe I should have tried it myself first. I'm taking down my demo page.

Just to add to your explanation, I guess when a lot of requests were made quickly with "Button 2" in my example, the elements had time to get added to the page before they got their turn in the queue to be typeset, and that's why there was the speed effect. (But it's irrelevant because they should be added to the page before typesetting anyway!)

Many thanks. : )
