### ISSUE TITLE
Square root displays without the top line on iPad's (Safari)

### ISSUE THREAD

**Issue by jmlear** [mathjax/MathJax#1578]
Got to this link on an iPad: https://test87-tn8.pearsondev.com/client/index.html?username=LGN021036581&password=35M23ELM
Press "Start Test Now"
Press "Start Section"
Notice the square root is not displayed properly.

**Comment by dpvc** [comment]
You are using a very old version of MathJax (2.4.0), and should update to the current version (2.6.1) before reporting errors.  A lot has changed since v2.4.0.  Try updating and see if the problem persists.  If so, report again here, but I suspect you may better better results with 2.6.1.  Also, you could switch to the new (and faster) CommonHTML output rather than the more fragile and slower HTML-CSS output.

**Comment by jmlear** [comment]
Sorry about that I thought I saw that it wasn't working on the new version of Mathjax, but I just tested again and it is working there. Thanks.

**Comment by dpvc** [comment]
No problem.  Glad it is working for you now.
