### ISSUE TITLE
Expressions after ampersands in \cases are not rendered

### ISSUE THREAD

**Issue by mattrajca** [mathjax/MathJax#1579]
In the following simple example, I cannot get the `\ge` and `\le` expressions after the `&` in the `\cases` statement rendered. This also applies to any other TeX such as `\delta`s, `\sum`s, etc.

Sample code:

```
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	
	<script type="text/x-mathjax-config">
		MathJax.Hub.Config({
						   tex2jax: { inlineMath: [['$','$']], displayMath: [['$$', '$$']], processEscapes: true },
						   TeX: { Macros: {
						   }
						   }});
						   
						   
	</script>
	
	<script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_CHTML-full"></script>
</head>

<body>

<p>$ \cases{x & y \ge 2 \cr 0 & y \le 2} $</p>

</body>
</html>
```

Output:

<img width="181" alt="screen shot 2016-08-12 at 5 06 55 pm" src="https://cloud.githubusercontent.com/assets/123372/17638370/3b8e2e06-60af-11e6-91a6-5c96a8e27c2a.png">

This happens on the latest build of Chrome and the latest preview of Safari 10.

**Comment by dpvc** [comment]
This is correct behavior.  The `\cases` macro typesets the second column in text mode (not math mode), just as TeX does.  Since MathJax doesn't process macros in text mode, your expression produces the output you are seeing.  (In actual TeX, you would get an error message about a missing dollar sign when `\ge` is used in text mode.)

You should either use

    \cases{x & $y \ge 2$ \cr 0 & $y \le 2$}

or use the `cases` LaTeX environment:

    \begin{cases}
    x & y \ge 2 \\
    0 & y \le 2
    \end{cases}
