### ISSUE TITLE
Feature request: support \bigsqcap

### ISSUE THREAD

**Issue by kathode** [mathjax/MathJax#1588]
It seems that MathJax only supports \bigsqcup but not \bigsqcap.

Is there any particular reason, or do you have a suggestion as how to get the other working?

Thanks

**Comment by pkra** [comment]
The reason is that the default MathJax fonts (derived from Computer Modern) do not have a glyph for the character. For the same reason, this macro requires extra LaTeX packages.

You could use the Unicode point directly to define a macro, e.g, `\newcommand{\bigsqcap}{\mathop ⨅}` or via the configuration (see http://docs.mathjax.org/en/latest/tex.html#defining-tex-macros), but note that unless you use a font that includes the glyph (e.g., STIX), MathJax will have to fallback to a system font -- which is not ideal but in this case probably ok (see http://docs.mathjax.org/en/latest/font-support.html#character-fallbacks).

See also the feature request https://github.com/mathjax/MathJax/issues/1221 -- St Mary Rd is probably the most common choice for a LaTeX package that provides this macro.

**Comment by kathode** [comment]
Thank you for the prompt and helpful answer. The suggestion worked ok!
