### ISSUE TITLE
\class{test}{\href{...}{...}}: class is applied to child of <a>, not to <a> itself (HTML-CSS and CommonHTML)

### ISSUE THREAD

**Issue by TomasRiker** [mathjax/MathJax#1600]
Consider the following code:
`\class{test}{\href{http://www.example.org}{Link}}`

One would expect the `test` CSS class to be applied to the `<a>` element generated by `\href`. But instead, it is applied to the first child of the `<a>` element (see screenshot below).

This happens with both HTML-CSS and CommonHTML. I don't know if it's intended behavior, but I find it a bit strange. I stumpled upon this because my selector `a.someClass` didn't yield any elements.

![nesting](https://cloud.githubusercontent.com/assets/295205/17892966/1e021c10-6944-11e6-9263-0b04b3e46a7a.png)

**Comment by pkra** [comment]
I would actually expected a different result -- a span with class=test around an anchor with href -- since macros are completely independent from each other.

Anyway. I would have guessed this is expected behavior but looking at the generated MathML they are actually put together correctly (an mrow with both the class and the href), so this surprises me after all.

@dpvc is this more a bug or a feature request?

**Comment by dpvc** [comment]
Thinking about what the TeX should produce in terms of HTML is the wrong way to look at this, because the TeX conversion isn't to HTML, its to MathML (and then from MathML to HTML).  SO you have to think about those two parts separately.

So first, what MathML should the expression generate?  The `\href{}{}` macro is supposed to add an `href` attribute to its content; how should that work?  If the content is a single MathML node, like `<mi>x</mi>`, then it is natural to make that `<mi href="...">x</mi>`.  If the content is several MathML nodes, then you would need to surround them with an `<mrow>` and add the `href` attribute to that:  `<mrow href="..."><mi>x</mi><mo>+</mo><mn>1</mn></mrow>`.

The `\class{}{}` macro acts similarly:  if the content is a single element, it is given the `class` attribute with the name provided; if it is more than one element, they are placed in an `<mrow>` with the proper class.

In your case, the `Link` produces `<mi>L</mi><mi>i</mi><mi>n</mi><mi>k</mi>`, so `\href{http://www.example.com}{Link}` produces `<mrow href="http://www.example>
  <mi>L</mi><mi>i</mi><mi>n</mi><mi>k</mi>
<mrow>`, and `\class{test}{\href{http://www.example.com}{Link}}` add the `class` attribute to that, generating

```
<mrow class="test" href="http://www.example>
  <mi>L</mi><mi>i</mi><mi>n</mi><mi>k</mi>
</mrow>
```
as the final result.

Then the question becomes: what HTML should this produce?  Of course, this is dependent on the output renderer selected, but in the CommonHTML output that you are using, each MathML element corresponds to a `<span>` in the HTML output, and the attributes like `class`, `id`, and `data-*` attributes from the MathML node are applied to the corresponding `<span>`.  So the `class="test"` is put on the `<span>` element (i.e., the element that directly corresponds to the `MathML element`).  Of course, the `href` can't be put on the `<span>`, since a span doesn't accept an `href` attribute.  Instead, in order to make the link, the `<span>` is enclosed in an `<a>` node that produces the link.

While I suppose it would be possible to put the `class`, `id`, and other attributes on the `<a>` rather than the `<span>` in this case, there are advantages to being able to rely on the fact that the nodes associated with the MathML elements are always spans, and that their structure is consistent (not sometimes an `<a>` and sometimes a `<span>`).  For example, the `<span>` is the element whose bounding box is the correct one for the element (the `<a>` may not be).

The long and the short of it is that, with the current TeX input jax, you can't set the class for the `<a>` element that is produced by the CommonHTML output, only the `<span>` that is the result of the MathML element with the class.

The only alternative I can see would be to *always* wrap the content in an `<mrow>` for both `\href` and `\class`, so that `\class{test}{\href{xyz.html}{x}}` would produce

```
<mrow class="test">
  <mrow href="xyz.html">
    <mi>x</mi>
  </mrow>
</mrow>
```

but

```
<mi class="test" href="xyz.html">x</mi>
```

seems much preferable, both from the point of view of the generated MathML, as well as the resulting HTML output (since generated HTML will be simpler, and the more complicated the HTML is, the slower the page becomes, so we don't want to produce MathML structures that are any more complicated than necessary).  In any case, this would *still* not put the class on the HTML `<a>` element, since now the class and link are not even on the same MathML element.

> since macros are completely independent from each other

I'm not sure what that means, and there certainly is no rule that says macros can't interact with each other, or that one macro applied to the result of another must act as though that result is enclose in braces.

Also, since `\class` is not a standard LaTeX macro, there is no standard that applies to it, so we can define it to do whatever we like.

> is this more a bug or a feature request?

I do not consider it a bug.  I'm not sure I think it is a feature request, either.  If one were to move `class` and `id` attributes to the `<a>`, then that would make referring to the `<span>` element more complicated, and sometimes you *do* want to refer to the `<span>`.  In the absence of a mechanism in TeX to distinguish the two, I think a simple, consistent rule (the attributes go on the associated `<span>`) is the best choice.

**Comment by pkra** [comment]
Thanks for correcting me, @dpvc.

> I'm not sure I think it is a feature request

I suppose having a way to specify a class on an anchor might be a useful feature.

**Comment by TomasRiker** [comment]
Thanks for the detailed feedback.
I wouldn't insist on being able to set the class on the `<a>` element itself. However, the current behavior is confusing because it "inverts" the nesting order. In TeX, `\class` is outside and `\href` is inside, but in the HTML generated the element that gets the class is inside the `<a>` element.
