### ISSUE TITLE
comma is not interpreted as decimal point in german latex numbers, but as list entries adding space

### ISSUE THREAD

**Issue by christianhueser** [mathjax/MathJax#1615]
In case of writing numbers with comma as decimal point extra space is put between comma and first decimal digit. This does not happen, for example, for decimal numbers in fractions.

Is this a bug or is there a configuration to tell MathJax to treat comma as decimal point?

Many thanks for pointing to a solution or fixing this issue.

**Comment by dpvc** [comment]
This is how TeX and LaTeX work.  The comma is treated as punctuation (not a decimal), and the spacing is due to that.  The reason that you don't get it in fractions (in inline-equations) is because the numerator and denominator in an in-line fraction are typeset using the rules for super- and subscripts, in which extra spacing is suppressed.  If you used a display-style fraction, the numerator and denominator will be typeset in in-line style, and will have the spacing.

The TeXbook recommends that you use `3{,}14159` if you are using a comma as a decimal place.  That will produce the result you want in MathJax.

See [issue 169](https://github.com/mathjax/MathJax/issues/169#issuecomment-2040235) for an alternative approach that allows you to configure how MathJax handles numbers so that it will switch the use of commas and periods.

**Comment by christianhueser** [comment]
Splendid. I tried the solution with the curly brackets and it worked. Thanks for the immediate response.
