### ISSUE TITLE
Mathjax does not render on chrome in hosting but render on chrome in localhost?

### ISSUE THREAD

**Issue by diz123** [mathjax/MathJax#1618]
Hi, i have a problem when runing Mathjax on chrome in hosting.
My website runing ok on localhost when upload to my hosting it's not working
I tested on firefox it's ok and opera still ok too 
Any ideal for that problem ?

**Comment by pkra** [comment]
Without a link to a live page, there's not much to say, I'm afraid. Do you get any errors in the developer console? Do you have Chrome extensions that might interfere?

**Comment by hprofit** [comment]
This sounds similar to what I'm experiencing. I can retrieve the base MathJax.js file which pulls down MathMenu.js and MathZoom.js, but no other extensions within Chrome (localhost or not). I've tried pointing to an apache deployment, a simple http-server, our dev and QA deployments, and even went as far as trying:
`<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/2.2-latest/MathJax.js" defer></script>`

All yielded the same results.

https://gyazo.com/71bac7549a0d1c6d92d65e1f36f2a558

No console errors, no 404's, no toast messages (just that it's Loading MathMenu and MathZoom, nothing else). This happens in Chrome 53 on OSX and Chrome (version unknown at the moment) within a Windows 7 VM. Stranger still is it _only_ seems to happen on _my_ machine and no one else's. It's not my extensions as I don't have those running within the VM and even after disabling all of them the problem still occurs.

**Comment by pkra** [comment]
@hprofit again, not much to say without a live page. I would suggest to try clearing the browser cache to ensure that it is not due to file corruption (Chrome developer tools => network tab => disable cache, or via the Chrome settings but then include a restart of Chrome). 

Also, your screenshot shows that MathJax v2.2 is being loaded. That version was released over 3 years ago and has numerous bugs that have been fixed since then; if you can, please try the latest version.

**Comment by dpvc** [comment]
@hprofit, you do not include a configuration file (via the `?config=...` option following `MathJax.js` in the `src` attribute), so unless you are including an in-line configuration block (we can't tell since you didn't give a complete example), then MathJax will not have been told what input format you are planning to us, nor what output format you want to provide.  So it won't load or register any pre-processors, and so won't look for any math on the page.

See the [documentation](http://docs.mathjax.org/en/latest/configuration.html#using-a-configuration-file) for more details about loading a configuration file.  And as Peter says, you might want to update to the current version of MathJax.
