### ISSUE TITLE
[MathML+useMathMLspacing:true] two adjacent fractions have no space 

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1626]
This was reported on the User Group.

Something like .

``` html
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mfrac>
    <mi>a</mi>
    <mi>b</mi>
  </mfrac>
  <mfrac>
    <mi>a</mi>
    <mi>b</mi>
  </mfrac>
</math>
```

will have the fraction lines touch (all outputs). 

Up to v2.3, the rendering had some space between the fractions (and without useMathMLspacing that's still the case of course).

Was this an intentional change?

**Comment by dpvc** [comment]
This was due to the changes for issue #547.  A solution would be to remove the `&& !this.useMMLspacing` from [line 2581](https://github.com/mathjax/MathJax/blob/master/unpacked/jax/output/HTML-CSS/jax.js#L2581) in the HTML-CSS jax (and the corresponding lines [2482](https://github.com/mathjax/MathJax/blob/master/unpacked/jax/output/CommonHTML/jax.js#L2482) and [1782](https://github.com/mathjax/MathJax/blob/master/unpacked/jax/output/SVG/jax.js#L1782) in the CHTML and SVG jax).  Alternatively,  one could use something other than the TeX `nulldelimiterspace` value for the `useMMLspacing` case.

**Comment by dpvc** [comment]
The `issue1626` branch of my fork of MathJax fixes this.

**Comment by dpvc** [comment]
==> Merged

**Comment by dpvc** [comment]
==> In testsuite

MathMLToDisplay/Presentation/GeneralLayout/mfrac/issue1626.html
