### ISSUE TITLE
Can't correctly compile inequality!!

### ISSUE THREAD

**Issue by mtrstudio** [mathjax/MathJax#1628]
As a simple example:

(1) `$P\left(  1<X<2,2< Y<3\right)  $` --->this does not compile, (no space before X)
(2) `$P\left(  1< X<2,2< Y<3\right)  $` --->this does compile, (there is a space before X)

The same issue happens to the `<` after Y, and any other similar situation!!

I believe this is a bug!!

**Comment by dpvc** [comment]
See the [documentation](http://docs.mathjax.org/en/latest/tex.html#tex-and-latex-in-html-documents) concerning issues with math in HTML documents (where `<` is used by the HTML language to introduce tags).   Since the HTML parsing is done well before MathJax runs, there is really nothing that MathJax can do about that.
