### ISSUE TITLE
[MathML output] Firefox adds unexpected whitespace [was: Alignment class added in math with parentheses]

### ISSUE THREAD

**Issue by Kgilstrap02** [mathjax/MathJax#1632]
Hello,
I seem to be having an issue in which MathJax applies alignment to cells of a table in which there is math that includes parentheses. The HTML table has assigned alignment that aligns all of the contents to the right of each cell unless specified otherwise. After rendering the table through MathJax, however, any table cell that contains MathML with parentheses is assigned a left alignment. Strangely, this change occurs when using both <mfenced> elements as well as parentheses contained within <mo> tags.

I've attached the page in Firefox where this problem is apparent, as well as the HTML code for the table where this change is occurring.

Thank you for any help you can provide.

![mathjax realignment](https://cloud.githubusercontent.com/assets/22619456/19082670/242c25cc-8a2d-11e6-8229-bd053f2618a4.PNG)
[MathJax realignment HTML Table.txt](https://github.com/mathjax/MathJax/files/508976/MathJax.realignment.HTML.Table.txt)

**Comment by dpvc** [comment]
This is not due to the `text-align` attribute (*every* math expression has that set to `left`).  It is actually a bug in Firefox's native MathML rendering that doesn't always determine the width of a MathML element correctly when it is inside an element with `display:inline-block` set.  That expression is getting extra white-space on the right due to that width bug in Firefox.  So it is still right-aligned, but it has extra width that it shouldn't.

You might be able to get around that by using the following CSS:

    td .MathJax_MathContainer, td .MathJax_MathContainer > span {display:inline!important}

to replace the `display:inline-block` with `display:inline`, but I'm not sure if that will have adverse consequences for some expressions.

**Comment by pkra** [comment]
Should we close this? 

We don't expect native MathML implementations to improve (and we don't file upstream bugs for them anymore).

**Comment by dpvc** [comment]
I'm OK closing it.  I don't expect to do anything in MathJax to work around it.
