### ISSUE TITLE
Support \colonequals from colonequals

### ISSUE THREAD

**Issue by a3nm** [mathjax/MathJax#1639]
The command "\colonequals" from the colonequals package does not appear to be supported. Would it be possible to add support for it to MathJax?

**Comment by dpvc** [comment]
You can use `\def\colonequals{:=}` to get a definition for this, but if you are concerned about the size of the colon compared to the equal sign, you can always call on the Unicode character for it (though this will rely on the fonts installed on your reader's computer):  `\mathrel{\unicode{x2254}}`.  You can set up your configuration to define these automatically if you wish.  See the [documentation](http://docs.mathjax.org/en/latest/options/TeX.html).

**Comment by a3nm** [comment]
OK, this Unicode-based solution is a pretty fine (if unintuitive)
workaround. If you don't think adding support for \colonequals following
the existing colonequals package is relevant, please feel free to close
the issue. Thanks a lot for your help with this!

**Comment by pkra** [comment]
> If you don't think adding support for \colonequals following
the existing colonequals package is relevant, please feel free to close
the issue. 

This issue is marked as a feature request in our backlog; this means the MathJax team has no specific plans to implement at this time (but of course contributions are possible). 

Note that there are various LaTeX packages that implement macros with results similar to `\colonequals` and that other factors (such as font glyph coverage) might also factor into an implementation.

**Comment by dpvc** [comment]
MathJax v3.2 has `\coloneqq` in the mathtools extension.  Perhaps that is sufficient.

**Comment by pkra** [comment]
And https://github.com/AmerMathSoc/mathjax-unicode-math also provides `coloneq`.
