### ISSUE TITLE
Line-breaking in mlabeledtr

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1647]
This thread on [meta.math.SE](http://meta.math.stackexchange.com/questions/25180/tag-mathjax-spills-to-the-right-of-main-text-body) boils down to support for automatic line-breaking within `mlabeledtr`s.

**Comment by dpvc** [comment]
The real issue isn't the label (which would have line breaking applied if it were wider than the available width for the table, just like any other cell), but that there is (1) no line breaking inside `<mtext>` elements, which is what surrounds the contents of the tag, and (2) cells aren't broken unless the whole cell is wider than space available for the table (rather than checking the widths of columns and breaking when their sum is too wide).

**Comment by pkra** [comment]
Thanks for correcting me. Should we close this and open two new issues?

**Comment by dpvc** [comment]
I think (2) is already #892.  I don't think (1) has an issue yet, but it is certainly one of the MathML features not yet implemented (we don't currently have line breaking within any token elements, so this applies to `<mi>`, `<mo>`, etc., as well).

**Comment by pkra** [comment]
Closing in favor of #892 and #1648.
