### ISSUE TITLE
Is there a possibility to use bare parser?

### ISSUE THREAD

**Issue by nickkolok** [mathjax/MathJax#1649]
Thank you very much for MathJax, comrads!
I use it in my projects and I'm very satisfied with it.

But now I need a bare LaTeX parser, i. e. I don't need rendering, macro expanding, etc. I need a function which gets a string and returns tree-like object, something like HTML node tree.

Could such function be found in MathJax?

**Comment by dpvc** [comment]
I'm not sure I understand your question.  The HTML node tree *is* the rendering, so I don't know what you mean by not needing rendering.  Also, macro expansion is an integral part of LaTeX processing, so I don't know what you mean by not needing that.  MathJax's internal format is essentially MathML, so it is possible to obtain that, if that is what you are after.

**Comment by nickkolok** [comment]
Thanks for your answer!

I'll try to say more clear. I need a function that takes, for example, this TeX code:
```
So that
\begin{equation}
  E = m c^2
\end{equation}
```
And returns smth like this:
```
[
  {
    nodetype: 'text',
    nodecontent: 'So that',
  }, {
    nodetype: 'equation',
    nodecontent: [
      {
        nodetype: 'text',
        nodecontent: 'E',
.....
      }
    ]
  }

]
```

**Comment by dpvc** [comment]
No, MathJax does not contain a function that does that.

**Comment by nickkolok** [comment]
Thanks.
May be, there is a lexer which splits string into lexems, so that the code above will turn into
```
[
'So that',
'\\begin',
'{',
'equation',
'}',
...
]
```
?

**Comment by dpvc** [comment]
No, MathJax doesn't work that way.  Because the original math is inside the browser DOM, MathJax first walks the DOM looking for math delimiters like `$$` or `\begin{equation}` and when it finds them, it locates the close delimiter and pulls that math out of the DOM, replacing it with a special DOM node that marks it as math for later processing.  Later on, MathJax will retrieve the math and run its TeX input processor on it.  But that doesn't work by tokenizing the string and then processing the tokens, as your example suggests.  Because TeX is a macro language, MathJax processes the string by identifying the first macro (or other character) and processing that, and continuing in that way until the sting is exhausted.  Macros are allowed to modify how the following characters are tokenized, and that prevents pre-tokenizing the whole string.
