### ISSUE TITLE
[CommonHTML] font size too small with css columns

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1664]
Reported on [stackoverflow](https://stackoverflow.com/questions/40657422/mathjax-font-size-shrinks-when-playing-with-position-css-attribute).

Firefox and Edge (didn't test IE) are affected. Chrome and Safari look ok. HTML-CSS and SVG are both fine on all.

Sample from SO:

```html
<html>
	<head>
		<meta charset="utf-8">
		<script type="text/javascript" async
		  src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML">
		</script>
		<style media="screen">
			ol {
				counter-reset: list;
			}
			ol > li {
				list-style: none;
				/*removing this property fixes MathJax size but breaks markers*/
				position: relative;
			}
			ol > li:before {
				counter-increment: list;
				content: counter(list, decimal) ") ";
				position: absolute;
				left: -1.4em;
			}
			.twocolumns {
		    -webkit-column-count: 2;
		    -moz-column-count: 2;
		    column-count: 2;
			}
		</style>
	</head>
	<body>
		<div class="twocolumns">
			<ol>
				<li>\(2 \times 5\)</li>
				<li>\(4 \times (2 +11)\)</li>
				<li>\(4 \times 5 - 2 \times 7\)</li>
				<li>\(4 \times (87 - 45) + 5 \times 2\)</li>
			</ol>
		</div>
	</body>
</html>
```

**Comment by dpvc** [comment]
MathJax uses a relatively tall box (60ex high) to determine the ex-height of the surrounding font, and it looks like FF and Edge both do something funny with the size of that box in the multi-column setting.  They seem to override both the width and height set by MathJax for this box, and so MathJax gets the wrong ex-height (and so sets the wrong font scaling).  Since both FF and IE does it, perhaps it is the correct behavior by the HTML or CSS spec, and WebKit is getting it wrong.

In any case, it turns out that adding `overflow:hidden` to the CSS for the test element used by MathJax resolves the problem (the browsers don't screw up the height in that case, for reasons beyond my comprehension), so adding

```
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  CommonHTML: {
    styles: {".mjx-ex-box-test": {overflow: "hidden"}}
  }
});
</script>
```

should resolve the issue.

**Comment by dpvc** [comment]
The `issue1664` branch of my fork of MathJax includes the fix.

**Comment by dpvc** [comment]
==> Merged.

**Comment by dpvc** [comment]
It looks like for current versions of Firefox, this is only triggered if a packed combined configuration file is used, and the test suite doesn't provide for that, so I can't write a test for it.  Thus I'm marking this as "no test needed".

**Comment by dpvc** [comment]
PS, I have hand tested that the solution (of the extra CSS) still works.
