### ISSUE TITLE
MathJax breaks when archiving links with archive.org (this wasn't the case earlier)

### ISSUE THREAD

**Issue by kitroti** [mathjax/MathJax#1679]
It seems that MathJax no longer works when looking at links from archive.org, for example try

1. old: https://web.archive.org/web/20141009173831/http://math.stackexchange.com/questions/49229/why-can-all-quadratic-equations-be-solved-by-the-quadratic-formula

2. recent: https://web.archive.org/web/20161217100857/http://math.stackexchange.com/questions/837772/determine-the-values-of-the-ratio-xy-if-2x2-xy-3y2-0?noredirect=1&lq=1

The "Fast Preview" works at first and then it breaks when it tries to render HTML/CSS.

I don't know from this error stems, but it's really important to have it working given the value of archiving content.

**Comment by pkra** [comment]
Both links work fine for me in HTML-CSS. However, the second breaks when I switch to SVG output.

The problem lies with the Internet Archive. They use their own copy of MathJax (not the CDN) and we have no control over what they load (or mirror since I'm guessing that's how they get a copy). You might want to reach out to them instead.

**Comment by kitroti** [comment]
Thanks @pkra, I'll try to contact the Internet Archive to investigate on this crucial issue.

Here is a screenshot of how the page looks for me (HTML-CSS):

![](https://web.archive.org/web/20161219121636/https://cdn.pbrd.co/images/bFKayMvt8.png)

**Comment by pkra** [comment]
Thanks for the follow up. I've also reached out to them. 

Closing this issue since it is not an issue with MathJax.

**Comment by dpvc** [comment]
@kitroti, it looks like MathJax has triggered its "image fonts" rather than its web-based fonts, and that some of the images are not being loaded (or are being loaded very slowly).  If you reload the page, does it help?

Your links work fine for me, but that may be because I have the MathJax fonts installed locally, so image fonts are not triggered.  Web-based fonts need to be sent using special server configuration in some circumstances, and it is likely that the archiver doesn't have that set up, so the fonts are not being received properly by your browser, which is why it switched to image fonts.  If you are doing this only for your own personal use, you could install the [MathJax fonts](https://github.com/mathjax/MathJax/tree/master/fonts/HTML-CSS/TeX/otf) locally, and that should allow you to see the results properly.
