### ISSUE TITLE
LaTeX-to-MathML-renderer regarding {,} incorrect

### ISSUE THREAD

**Issue by Blijbol** [mathjax/MathJax#169]
I'm a Dutch speaker and I use {,} to be able to use a comma as a
decimal separator, as described here:
http://www.tex.ac.uk/cgi-bin/texfaq2html?label=dec_comma

In MathJax, this works correctly when rendering LaTeX in HTML-CSS-
mode, but when using the MathML-renderer, this doesn't work if there
are less than three digits behind the decimal separator.

**Comment by janwh** [comment]
As a future reference for others coming here, wanting to replace decimal points with decimal comma: The above-mentioned regex did not work out for me, when in fact the snippet below does:

```javascript
<script type="text/x-mathjax-config">
MathJax.Hub.Register.StartupHook("TeX Jax Ready",function () {
  MathJax.InputJax.TeX.Definitions.number =
    /^(?:[0-9]+(?:\{,\}[0-9]{3})*(?:\,[0-9]*)*|\,[0-9]+)/
});
</script>
```

**Comment by dpvc** [comment]
@janwh, note that your pattern is for using commas *without* enclosing braces as the decimal place indicator, whereas the original post was asking about using `{,}` as the indicator.  So your needs seem to be different from the original poster's.

Also, the default for MathJax is to allow braced commas as thousands separators and period as decimal place, as in `1{,}234{,}567.89`, as it would be written in standard TeX.  Your pattern changes the period to a comma, but doesn't change the thousands indicator, so you would enter `1{,}234{,}567,89`, which would be displayed as `1,234,567,89`.  I suspect that is not what you want for thousands.  The pattern I gave above switched the roles of `{,}` and `.`, so that you would enter `1.234.567{,}89`.  You may wan to consider changing the `\{,\}` in your pattern to whatever you want to use as the thousands separator (or eliminate the `(?:\{,\}[0-9]{3})*` entirely if you don't want to use thousands separators).
