### ISSUE TITLE
alignat: incorrect space before the equal sign [was: possible bug in alignat]

### ISSUE THREAD

**Issue by jason-s** [mathjax/MathJax#1690]
```
$$\begin{alignat}{2}
a &= \frac{1}{2}b+c+d &=& e        \\
f &= \frac{2}{3}g+h   &=& i+j+k
\end{alignat}$$ 
```

in https://cdn.mathjax.org/mathjax/latest/test/sample-dynamic-2.html renders like this:

![image](https://cloud.githubusercontent.com/assets/738893/21909738/6c001ce4-d8d6-11e6-8f01-97dfa4c178f5.png)

Note the small space before the `e` and `i`.

**Comment by jason-s** [comment]
oh, could be user error on my part;

```
$$\begin{alignat}{2}
a &= \frac{1}{2}b+c+d &&= e        \\
f &= \frac{2}{3}g+h   &&= i+j+k
\end{alignat}$$ 
```

This looks better.

![image](https://cloud.githubusercontent.com/assets/738893/21909980/6e71d4f8-d8d7-11e6-95be-fa4451b5057b.png)

**Comment by dpvc** [comment]
This is (almost) correct behavior for the `alignat` environment.  (In fact, there should be less space between the d and the equal sign.  This is actual LaTeX output:

<img width="411" alt="latex" src="https://cloud.githubusercontent.com/assets/432782/21966121/8c846e04-db3b-11e6-9334-87bfc258b17d.png">

The `alignat` environment is meant to produce columns of equations that are of the form

        a = b      c + c = d + d
    a + a = b + b      c = d

that is coded as

```
\begin{alignat}
        a &= b  &    c + c &= d + d \\
    a + a &= b + b  &    c &= d
\end{algnat}
```

Note that you do *not* put `&` after the equal signs.

If you are leaving out the left-hand side of an equality (like the `c + c` above), then you have to leave that column empty.  LaTeX makes special provisions for the equal signs to be properly spaced, but only does it every other column.  MathJax incorrectly modifies the spacing very *every* column, which is why there is space between the `d` and `=`.  Your extra `&` between `=` and `e` is why there *isn't* the correct space at that location.

**Comment by dpvc** [comment]
Ive marked this "accepted" because of the incorrect space before the equal sign (which should only happen in even columns, not odd-numbered ones), not because of the missing space after the equal, which is correct behavior.

**Comment by dpvc** [comment]
The `issue1690` branch of my fork of MathJax includes a fix for this.

**Comment by dpvc** [comment]
==> Merged.

**Comment by dpvc** [comment]
==> In testsuite

LaTeXToMathML/environments/issue1690.html
