### ISSUE TITLE
Stacked mhchem bonds render badly

### ISSUE THREAD

**Issue by mhchem** [mathjax/MathJax#1698]
Stacked mhchem bonds render badly, recently (tested with Chrome and Firefox on Windows).

See https://mhchem.github.io/MathJax-mhchem/ section Bonds.
![image](https://cloud.githubusercontent.com/assets/16336692/22783151/dcdd28ee-eeca-11e6-9303-3167948ebd1c.png)

I am pretty sure nothing within mhchem.js changed. The definition is exactly as David did it.

    "~-": "{\\begin{CEstack}{}\\tripledash\\\\-\\end{CEstack}}",
    "~=": "{\\raise2mu {\\begin{CEstack}{}\\tripledash\\\\-\\\\-\\end{CEstack}}}",
    "~--": "{\\raise2mu {\\begin{CEstack}{}\\tripledash\\\\-\\\\-\\end{CEstack}}}",
    "-~-": "{\\raise2mu {\\begin{CEstack}{}-\\\\\\tripledash\\\\-\\end{CEstack}}}",

    CEstack:       ["Array",null,null,null,"r",null,"0.001em","T",1]

Should I try to adapt mhchem.js or is this a core issue?

**Comment by dpvc** [comment]
It turns out that the bounding box information for the minus (U+2212) was not consistent with the ones used by TeX, and this caused minus and plus in super- and subscripts to be misaligned.  So v2.7 adjusted those bounding boxes unfortunately, that is causing the spacing problems you are seeing, here.

The CEstack never did work as well as I had hoped. So I'd recommend replacing with something like

    \mathbin{\raise2mu{\rlap{\lower.2em{-}}\rlap{\raise.37em{\trippledash}}-}}

for `~=` (though you might want `\mathord` rather than the `\mathbin`).  Similar constructs could be used for `~-` and `-~-`.  That should mean you no longer need the CEstack definition, as well.

**Comment by mhchem** [comment]
I will take care of it in mhchem.js.
