### ISSUE TITLE
Display Math should use <span> instead of <div>

### ISSUE THREAD

**Issue by geyang** [mathjax/MathJax#1707]
Hey @pkra @dpvc 

Thanks for maintaining this important library! I have contributed PR's to this project before, and would like to raise an issue that has been there for a while.

Over the years the default rendering for the display math has always been rendering it as a `div`, because the default CSS styling for a `div` is a block display element. 

However, this is semantically wrong. The semantic HTML requires that each element inside the `p` tag has to be an inline element. Display math could just be a `display: block` styled `<span>` element instead of a `<div>`, which is a semantic block element.

All browsers enforce this rule, automatically breaking a `<p>` paragraph into multiple paragraphs with `math-display` sprinkled in between. As a result, during a typical page load, the html that the page serves will be mutate:

```html
<p>I love MathJax!!!
\begin{align}\text{with some text.}\end{align}
The paragraph continues with 
$$\text{some more display math :D}$$
and the paragraph ends.</p>
```

as soon as `MathJax` renders, this wonderful and correct `html` gets turned into this:

```html
<p>I love MathJax!!!</p>
<div class="math math-display" alt="\begin{align}\text{with some text.}\end{align}"><script/></div>
<p>The paragraph continues with </p>
<div class="math math-display" alt="\text{some more display math :D}"><script/></div>
<p>and the paragraph ends.</p>
```

It is fine for `MathJax` to mutate the inline text node the math is in, but it should not affect the parent paragraph element. By inserting `<div>` tags however, MathJax is introducing semantic errors in the html, and as a result, the browser breaks the paragraphs into multiple pieces.

What is your oppinion? Thanks! 😄 

Ge

**Comment by dpvc** [comment]
This has come up before (see [this forum post](https://groups.google.com/forum/#!topic/mathjax-users/hnNmdpAm_4Q) for example, and [my response](https://groups.google.com/d/msg/mathjax-users/hnNmdpAm_4Q/FpNG6GOASwcJ) in particular).  Your claim that the paragraph will be broken is not quite right (as I explain in my response linked above).  That would be true only if you save the resulting HTML and loaded it again, as the example I list in my response shows.  The HTML that you says is the result of MathJax is not actually the result.

Note also that the CommonHTML output *does* use `<span>` elements rather than `<div>` elements.  It is only the HTML-CSS and SVG output that do.

**Comment by dpvc** [comment]
MathJax v3 no longer use divs (or spans) for this.
