### ISSUE TITLE
Improve mathjax.org security

### ISSUE THREAD

**Issue by drinkingink** [mathjax/MathJax#1716]
Scanning with this tool https://securityheaders.io/?q=mathjax.org&followRedirects=on shows that there are missing security headers like HSTS, CSP and others.

**Comment by pkra** [comment]
Closing this since it is not an issue with MathJax (the software which is what this repo is about).

If you are thinking about www.mathjax.org, then you might want to file an issue on https://github.com/mathjax/mathjax-website (but I for one can't quite see an associated risk -- happy to learn more).
