### ISSUE TITLE
accessible.js causes errors

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1719]
Adding the deprecated `accessible.js` configuration causes errors.

Example at https://jsbin.com/harotuhalo/1/edit?html,output

**Comment by pkra** [comment]
This is primarily to document this for anyone running into issues. The configuration will be removed in v3.

**Comment by dpvc** [comment]
Your sbin loads two configuration files (the `TeX-AMS_HTML-full` configuration, and then the `Accessible` configuration later).  This causes several components to be loaded a second time, and it turns out that this causes some confusion for MathJax.  Removing the `?config=TeX-AMS_HTML-full` from the script that loads `MathJax.js` allows the example file to work (with the `Accessible` configuration).

**Comment by dpvc** [comment]
I'm marking this "expected behavior" since mixing combined configurations is expected to cause problems.
