### ISSUE TITLE
Formula code from html

### ISSUE THREAD

**Issue by sassanh** [mathjax/MathJax#1720]
Is it possible to extract the formula from a rendered MathJax html code? The html code is stored in a file not in a dom.

**Comment by pkra** [comment]
That depends on what you've stored. The output is followed by a script tag that includes the original source. If that's not stored then you probably cannot.

See also https://github.com/mathjax/MathJax/issues/1699

**Comment by sassanh** [comment]
Actually the exact problem is that I want to be able to edit the MathJax output in tinymce. It'll make the edited formula look ugly because things don't expand as you enter new text (for example if I add some text under the root sign, the root sign doesn't expand.) But if every span in the output had a data attribute that indicates its place in the main latex or mathml code, then it'd be possible to reconstruct the latex/mathml code based on the edited MathJax output and re-render the output.

**Comment by pkra** [comment]
Sounds like https://github.com/mathjax/MathJax/issues/1108. 

>  But if every span in the output had a data attribute that indicates its place in the main latex or mathml code, then it'd be possible to reconstruct the latex/mathml code based on the edited MathJax output and re-render the output.

In generality, that's not possible for TeX input due to macros getting in the way. In addition, MathJax does not have a connection between TeX input and its output.

In modern text editors, the current model seems to be to separate the internal model of the editor from the rendering completely. That's probably a good approach for math editing as well.

Since we've seen many attempts disappear again, it might be a good idea to seek out similar projects and join forces. For example, a very recent one on my radar has been https://github.com/ianlucas/mathjax-editor.

**Comment by sassanh** [comment]
Thanks, https://github.com/ianlucas/mathjax-editor seems to be working smoothly.
