### ISSUE TITLE
Unexpected extra space in underscore while setting mtextFontInherit

### ISSUE THREAD

**Issue by TungTh** [mathjax/MathJax#1726]
Given the following text 
"This is an example with $\undersert{A}{\underline{\text{sample input}}}$ and some other things"

the CommonHTML is used, 
the mtextFontInherit is set to true,
and the style of the containing div of the formula is set to "display: none", 

The problem happens when the stype of the containing div is set to display: block. 
There are unexpected extra spaces after the text
![image](https://cloud.githubusercontent.com/assets/213165/24609924/d6760f38-18a6-11e7-8c4f-abd8b9a1235e.png)

**Comment by pkra** [comment]
That's probably expected behavior. On the one hand, MathJax needs to measure the string in \text{} when using `mtextFontInherit`. On the other hand `display:none` prevents measurements which is why MathJax moves the content elsewhere for rendering (then moves it back). If that other location has significantly different CSS, the measurement will not match the actual context.

But without a live sample we can't know for sure, so you might want to share one that exhibits the problem.

**Comment by TungTh** [comment]
Thank you for your explanation.
Please find the sample code in the attachment.
[extraSpace.zip](https://github.com/mathjax/MathJax/files/890335/extraSpace.zip)

**Comment by dpvc** [comment]
Peter is correct that this is due to your use of `display:none`, where MathJax can't measure the content as it needs to for `mtextFontInherit`.  Instead, it uses a temporary `<div>` as a child of the `<body>` element to measure it.  Since the body font is Arial while the `#content` div uses `Times New Roman`, that means MathJax gets the wrong measurement.

Instead, try using `visibility:hidden; overflow:hidden; height:0px` instead of `display:none`, and have your show-me button remove those properties.  Better yet, use a class with those properties and just remove the class name.

**Comment by TungTh** [comment]
Thank you for your detail explanation.
