### ISSUE TITLE
Display abnormal for limit

### ISSUE THREAD

**Issue by YO-LUN-CHIEN** [mathjax/MathJax#1728]
The code is normal :
`
<math xmlns='http://www.w3.org/1998/Math/MathML' display='inline'>
  <mo>&because;&nbsp;</mo>
  <munder>
    <mo>lim</mo>
    <mrow>
      <mi>x</mi>
      <mo>&rarr;</mo>
      <mi>c</mi>
    </mrow>
  </munder>
  <mi>f</mi>
  <mo>&ApplyFunction;</mo>
  <mfenced open = "(" close = ")">
    <mi>x</mi>
  </mfenced>
  <mo>&nbsp;=&nbsp;</mo>
  <mi>L</mi>
  <mo>&nbsp;&ne;&nbsp;</mo>
  <mn>0</mo>
</math>
`
`
<math xmlns='http://www.w3.org/1998/Math/MathML' display='inline'>
  <mo>&nbsp;&therefore;&nbsp;</mo>
  <munder>
    <mo>lim</mo>
    <mrow>
      <mi>x</mi>
      <mo>&rarr;</mo>
      <mi>c</mi>
    </mrow>
  </munder>
  <mfrac>
    <mn mathsize="1.2">1</mn>
    <mrow>
      <mi mathsize="1.2">f</mi>
      <mo mathsize="1.2">(</mo>
      <mi mathsize="1.2">x</mi>
      <mo mathsize="1.2">)</mo>
    </mrow>
  </mfrac>
  <mo>&nbsp;=&nbsp;</mo>
  <mfrac>
    <mn mathsize="1.2">1</mn>
    <mi mathsize="1.2">L</mi>
  </mfrac>
</math>
`

The code is abnormal :
`
<math xmlns='http://www.w3.org/1998/Math/MathML' display='inline'>
  <mo>&because;&nbsp;</mo>
  <munder>
    <mo>lim</mo>
    <mrow>
      <mi>x</mi>
      <mo>&rarr;</mo>
      <mi>c</mi>
    </mrow>
  </munder>
  <mi>f</mi>
  <mo>&ApplyFunction;</mo>
  <mfenced open = "(" close = ")">
    <mi>x</mi>
  </mfenced>
  <mo>&nbsp;=&nbsp;</mo>
  <mi>L</mi>
  <mo>&nbsp;&ne;&nbsp;</mo>
  <mn>0</mo>
  <mo>&nbsp;&therefore;&nbsp;</mo>
  <munder>
    <mo>lim</mo>
    <mrow>
      <mi>x</mi>
      <mo>&rarr;</mo>
      <mi>c</mi>
    </mrow>
  </munder>
  <mfrac>
    <mn mathsize="1.2">1</mn>
    <mrow>
      <mi mathsize="1.2">f</mi>
      <mo mathsize="1.2">(</mo>
      <mi mathsize="1.2">x</mi>
      <mo mathsize="1.2">)</mo>
    </mrow>
  </mfrac>
  <mo>&nbsp;=&nbsp;</mo>
  <mfrac>
    <mn mathsize="1.2">1</mn>
    <mi mathsize="1.2">L</mi>
  </mfrac>
</math>
`

Because and therefore of math is separated in the normal code.
Because and therefore of math is combined in the abnormal code.

**Comment by dpvc** [comment]
Neither example is valid MathML.  You nave `<mn>0</mo>` in both where you probably mean `<mn>0</mn>` (incorrect closing tag).  If this appears in an HTML page (as opposed to an XHTML page), the way the browser resolves this inconsistency depends on the surrounding tags.  In the first case, your `</math>` tag closes the math immediately after the incorrectly closed `<mn>` tag, and so the `<mn>` get closed because of that.  But in your second case, the unclosed `<mn>` is not closed immediately, and so the `<mn>` ends up getting the remaining expressions as child nodes.  So they are not displayed correctly.

The solution is to properly close the `<mn>` with `</mn>` not `</mo>`.

**Comment by YO-LUN-CHIEN** [comment]
I am sorry for I didn't find the mistake. 
You are right.
Thank you very much.
