### ISSUE TITLE
content-mathml.js and namespaces

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1755]
Cf. https://github.com/mathjax/ctop/issues/34 

It currently breaks when content has namespace prefixes.

In particular, it cannot be used together with mml3.js

**Comment by davidcarlisle** [comment]
arguably it's user error to have prefixes if the content is served as tex/html  as the pseudo-xml parser used for <math>  in text/hml puts everything in the mathml namespace  but with "local name" being the name as given rather than the part after the :  . Any xmlns:xxx attribute is simply ignored.

that said, it would presumably be easy enough to ignore prefixes when matching the element names in the javascript  if you wanted to be kind to the user rather than rigorously follow some quirk in the standards.

I'm not sure how much of my original version still survives here, let me know if you want me to do anything but I would guess any of you are rather better at javascript than me as I'm very much an "occasional user" where javascript is concerned.

**Comment by dpvc** [comment]
The `issue1755` branch of my fork of MathJax resolves this issue.

**Comment by dpvc** [comment]
==> In Testsuite

MathMLToDisplay/Content/issue1755.html

**Comment by dpvc** [comment]
==> Merged.
