### ISSUE TITLE
SVG Rendering can't select images

### ISSUE THREAD

**Issue by DaveBGld** [mathjax/MathJax#1762]
When selecting SVG rendering, the images created can't be selected or copied... 

I am creating a page that allows users to copy math content to MSWord. I thought that rendering to SVG and copying the images would be a solution, but I am having the problem described above.

Thanks!

Dave

**Comment by ickc** [comment]
Why would you expect it to work? And why you think this is an issue of MathJax?

**Comment by pkra** [comment]
> When selecting SVG rendering, the images created can't be selected or copied.

This  is outside of MathJax's control. It is due to browsers (and OSs) not having a suitable APIs for copy&pasting HTML with SVG content. Cf. https://www.w3.org/TR/clipboard-apis/#mandatory-data-types-1

> I am creating a page that allows users to copy math content to MSWord.

Microsoft Word does not support inline SVG content (only SVG as separate files inserted as images).
