### ISSUE TITLE
underline() is not working in preview html option

### ISSUE THREAD

**Issue by shahpiyushn** [mathjax/MathJax#1771]
(AB)_16 = (underline{" "})_8

Asciimath.

underline() is working fine in HTML-CSS and common html option but
it is not working in MathRenderer->preview html option.

So please solve this issue.

**Comment by pkra** [comment]
As the name suggests, the PreviewHTML output is not meant for production.

I've marked this as a feature request but we have no plans to work on this.

**Comment by dpvc** [comment]
Just to elaborate on Peter's comments, the PreviewHTML output is designed to make a fast, but possibly imperfect, rendering of the math so that is is available as quickly as possible, while one of the more accurate output processors does a more careful rendering, at which point the PreviewHTML version is replaced.  It is not intended to be the final rendering.

One of the things that makes it faster than the more accurate renderings is that it does not try to load web fonts, and so has to make due with a standard text font (it uses Times).  It also doesn't load metric information about the font (like the other renderers do) to save time, and so it doesn't know the actual size of any character and only makes guesses based on a heuristic.

The AsciiMath `underline()` command uses U+0332 (combining low line), which is a rather esoteric character, and not one that PreviewHTML knows anything about.  So it guesses at the size, and it is not correct about it in this case (combining characters are not something PreviewHTML handles); so the layout is off for this construction.

Also, if a character is not in the Times font, and I didn't check to see if U+0332 is or not), PreviewHTML will request it anyways and hope that the browser will find it in some font on the reader's system, but some browsers are better at finding them than others.  In particular, IE often won't show the character even if it is available in some system font.  The may be what is happening for you.

Finally, some browsers have trouble displaying combining characters when there is not previous character for it to combine with (as is the case here).  IE, for example, sometimes doesn't show them, and there are problems with Safari, and some other browsers as well.  Perhaps that is the source if the problem you are having.

In any case, Peter is correct that this is unlikely to change.  You should use one of the final renderers for your output rather than the PreviewHTML renderer.

**Comment by dpvc** [comment]
MathJax v3 no longer includes a PreviewHTML renderer.
