### ISSUE TITLE
[HTML-CSS]  Chrome59, Windows 7: inline-mode exponent causes erroneous vertical placement

### ISSUE THREAD

**Issue by imallett** [mathjax/MathJax#1772]
### Issue Summary

Exponent in an inline-mode equation causes the term to be pushed downward. Some other tags in the document seem to be necessary to trigger. Does not seem to be an issue in Firefox.

### Steps to Reproduce

Please see short, self-contained example: [https://pastebin.com/DE6pgaGJ](https://pastebin.com/DE6pgaGJ). Notice how the `c^2` is erroneously pushed downward by 1px.

### Technical details

* MathJax Version: 2.7.1
* Client OS: Windows 7 Pro
* Browser: Chrome 59.0.3071.104

**Comment by pkra** [comment]
Thanks for the report. Confirmed on this specific combination. But e.g., I don't see the problem on linux.

**Comment by dpvc** [comment]
Because the document has no `DOCTYPE` directive, Chrome will operate in [Quirks Mode](https://en.wikipedia.org/wiki/Quirks_mode), which is less reliable than Standards Mode.  If you add 

```
<!DOCTYPE html>
```

at the top of the document, the page should display properly.  Note that [HTML5 requires a `DOCTYPE`](http://dev.w3.org/html5/html4-differences/#doctype), so if you want your pages to perform properly in modern browsers, you should include this `DOCTYPE` as the first line in your HTML files.
