### ISSUE TITLE
[TeX] vcenter: SVG (and HTML-CSS) should match CommonHTML behavior

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1804]
Via https://github.com/mathjax/MathJax/issues/1802#issuecomment-314244105

The CommonHTML output renders content following `vcenter` incorrectly.

Minimal example `$\vcenter{a\\b}y$` - the `y` will be moved far to the right of the `vcenter` content.

**Comment by davidcarlisle** [comment]
in tex, using vcenter like that would produce a box that is `\hsize` (so typically `\textwidth`) wide so `y` will be somewhere off page.) you'd need `\vcenter{\hbox{a}\hbox{b}}`  (not saying mathjax has to follow tex exactly but....

**Comment by dpvc** [comment]
David is, of course, correct (and there will also be an indent on the first line inside the `\vcenter`).  Unfortunately, `\vcenter{\hbox{a}\hbox{b}}` will not work as desired in MathJax.  This is because, in TeX, `\vcenter{}` produces a text box in vertical mode, and MathJax does not implements text-mode (and so doesn't have a vertical mode for it).  So this will just produce "ab" vertically centered (not the "a" above the "b").

The `\vcenter` macro is one of the place where MathJax intentionally differs from TeX.  Because MathJax doesn't do text-mode material, in MathJax, the contents of `\vcenter{...}` is in math mode, in order to avoid having to do `\vcenter{\hbox{$...$}}` as you would in TeX. 

Also, because MathJax doesn't have a reasonable way to break an in-line math expression, `$a\\b$` produces the "a" above the "b" in an unbreakable box, so in in-line mode, that produces unexpected results.  We have had complaints about this (in particular for automatic line breaks), because the text of the page can flow around it in unexpected ways.  So for CommonHTML, `$a\\b$` produces a box that is full-width so that the text will not appear next to it accidentally.

So the result you are seeing is the expected result in CHTML, though it is a change from HTML-CSS and SVG (which should be modified to do the same thing).  Coincidentally, it also corresponds more closely to what will happen in LaTeX in the case of `\vcenter{a\\b}`.  But LaTeX will not break something like `${a\\b}$`, while MathJax will, so perhaps MathJax's `\\` needs to be made smarter about where it should break (e.g., only inside `\vcenter` and at the top level of the expression)?

In any case, I should not have suggested `\vcenter{a\\b}`.  I was testing it in HTML-CSS, where the behavior is different, so didn't catch it at the time.

**Comment by pkra** [comment]
I've renamed the issue.

**Comment by dpvc** [comment]
In testsuite:

MathMLToDisplay/issue1804.html
