### ISSUE TITLE
Formulas render only when cache was cleared.

### ISSUE THREAD

**Issue by lk-geimfari** [mathjax/MathJax#1805]
I have site which dynamically render some data from the server to front, so when I tried post content which use mathjax, formulas are rendered incorrectly, but if I cleaned up cache everything is okay. 

Do someone has any ideas why?

By default:
![image](https://user-images.githubusercontent.com/15812620/28062821-ce5362ea-6637-11e7-9417-a1cefeadc610.png)

When I clean up cache, history and reload the page all looks pretty nice:
![image](https://user-images.githubusercontent.com/15812620/28062808-bf733b10-6637-11e7-81fc-e4bcbd237235.png)

Browser: **Chrome 58.0.3029.110 (64-bit)**
OS: Ubuntu **16.04**
MatJax: **2.7.1**

**Comment by pkra** [comment]
Please share a link to a live example exhibiting the problem.

**Comment by lk-geimfari** [comment]
@pkra Of course: http://bit.ly/2tDzfYs. This site uses Cyrillic, I hope that you will not be embarrassed. Just look at first element in output.

**Comment by pkra** [comment]
The configuration block needs to be placed *before* the call to MathJax.js, see http://docs.mathjax.org/en/latest/configuration.html#using-in-line-configuration-options. 

Otherwise, there will be a race condition between fetching MathJax.js and parsing enough of the page to expose the configuration. On a fresh cache, that race will work out, with cached resources, it won't.

But, you should no longer use cdn.mathjax.org, see https://www.mathjax.org/cdn-shutting-down/ for more information. The redirect at cdn.mathjax.org might also be affecting the race.

**Comment by lk-geimfari** [comment]
@pkra I understand you. Thank you very much!

**Comment by pkra** [comment]
No problem. Good to hear you could resolve the issue.
