### ISSUE TITLE
Symantec is identifying AMSmath.js as malicious

### ISSUE THREAD

**Issue by countslaurel** [mathjax/MathJax#1807]
Are you, MathJax, aware of this situation? Is there a modified version of AMSmath.js that I can use to avoid this problem?

It's in MathJax version 2.6.1. I want to attach a copy of the file but couldn't because Outlook won't even allow a colleague to email this file to me.

**Comment by pkra** [comment]
Thanks for raising this issue.

We're not aware of any issues. Anti-virus heuristics have false positives like this from time to time and they usually disappear by themselves; there's relatively little we can do about them, I'm afraid. 

You seem to indicate this is a problem when using email; is this correct? (I'm actually surprised that JS files are not simply blocked by Outlook these days.)

Also, you see this problem with the latest version of MathJax as well?

Finally, do you have a pointer to more information (e.g., an official Symantec page)?

**Comment by countslaurel** [comment]
We did download the latest MathJax version to see if an update would help, but the new AMSmath.js file, dated 4/25/17, was also stripped out by Outlook when we attempted to email. 

The problem is not only in email; it is just that we are using email as a simple test (maybe, from your email, it is not a good test). We use MathJax for our documentation and provide needed files in our product build. The issue came from a client who had a problem installing our product. The AMSmath.js file got quarantined by Symantec. They are asking that we either 1) get a modified file or 2) get Symantec to whitelist the file. 

We have not had the client install the new MathJax files in their implementation. Do you think that would help?

No, at this point, we have an issue logged by our client. I am also planning to reach out to Symantec but wanted to check with you first. As far as you know this file is good? (We have no other complaints from other clients using different antivirus systems.) If you let me know this, I will work with Symantec to confirm. 

Thank you.

**Comment by pkra** [comment]
> As far as you know this file is good?

As far as we know, yes. Anyone can check out the the file itself here on GitHub as well as its history over the past 6 years. MathJax is used by thousands of sites and applications, and reaches over 180 million users each month. I'm relatively certain more than a few people would notice such a problem.

Of course we have no way of confirming that the file that reached your client has not been tampered with.

**Comment by countslaurel** [comment]
So I scanned with latest version AMSmath.js file on my machine, using Symantec Endpoint Protection, and it found a tracking cookie.  Is that expected?  Thank you, Laurel

**Comment by dpvc** [comment]
While MathJax does store user preferences in a cookie (if they make changes to those preferences in the MathJax contextual menu, the AMSmath.js file is no involved in that.  There is no cookie code in that file at all (no reference to "cookie" at all).  So I'm not sure why Symantec would be flagging that.  Can you see if your copy of AMSmath.js matches the one [here](https://github.com/mathjax/MathJax/blob/master/unpacked/extensions/TeX/AMSmath.js) (the unpacked version) or [here](https://github.com/mathjax/MathJax/blob/master/extensions/TeX/AMSmath.js) (the minified version)?

If you are using the minified version (i.e., your URL does **not** include `/unpacked/` in it), and if you are using one of the combined configuration files (i.e., are using `?config=...` in the URL that loads MathJax), then the content of the `AMSmath.js` file is included in the config file, so you do not need to ship the `AMSmath.js` file itself.

Does Symantec complain about any of the (minified) combined configuration files (the ones in the top-level `config` directory, as opposed to the `unpacked/config` directory)?  Since these contain the code from `AMSmath.js`, I would expect that if `AMSmath.js` gets flagged, so should the combined configurations.  But they include the minified code, so perhaps that isn't being flagged by Symantec.
