### ISSUE TITLE
MathJax 2.7.1  test example sample-mml.html  not working on IE 6-8

### ISSUE THREAD

**Issue by vonxing** [mathjax/MathJax#1825]
SCRIPT1028:Expected identifier, string or number
MML_HTMLorMML-full.js，line: 57，colume: 387

IE9+ is fine

**Comment by pkra** [comment]
Thanks for the report. This is due to https://github.com/mathjax/MathJax-a11y/issues/202 and is fixed in 2.7.2-beta1 (and thus will be fixed in the next release). You can disable the accessibility extensions  to work around the problem, cf. http://docs.mathjax.org/en/latest/options/extensions/a11y-extensions.html.
