### ISSUE TITLE
Define $$$...$$$ as $$\begin{eqnarray}...\end{eqnarray}$$

### ISSUE THREAD

**Issue by josephernest** [mathjax/MathJax#1844]
How to define a custom command such as:

     $$$...$$$ 

which would be translated into:

    $$\begin{eqnarray}...\end{eqnarray}$$

?

I think this would be super useful, quite often.

**Comment by dpvc** [comment]
Add

```
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  tex2jax: {
    displayMath: [['\\[','\\]'], ['$$','$$'], ['$$$','$$$']]
  }
});
MathJax.Hub.Register.LoadHook("[MathJax]/extensions/tex2jax.js", function () {
  var TEX2JAX = MathJax.Extension['tex2jax'];
  var CREATE = TEX2JAX.createMathTag.bind(TEX2JAX);
  TEX2JAX.createMathTag = function (mode,tex) {
    if (this.search.end === '$$$') {
      tex = '\\begin{eqnarray}'+tex+'\\end{eqnarray}';
    }
    return CREATE(mode,tex);
  }
});
</script>
```

to your file just *before* the script that loads `MathJax.js` itself.  This overrides the `tex2jax` method that creates the internal script tag used to store the math, and modifies the tex to be stored to include the `\begin{eqnarray}...\end{eqnarray}` when the delimiters are `$$$...$$$`.

**Comment by josephernest** [comment]
Thanks @dpvc. In fact I'm currenty using MathJax inside an editor thanks to [pagedown extra](https://github.com/jmcmanus/pagedown-extra) and [thanks to this code](http://dev.stackoverflow.com/content/js/mathjax-editing.js) (isn't it your code by the way?). So here is what I currently have:

    var converter = Markdown.getSanitizingConverter();
    Markdown.Extra.init(converter);
    var editor = new Markdown.Editor(converter, '');
    var mjpd1 = new mjpd();

    ...

    MathJax.Hub.Config({"HTML-CSS": { preferredFont: "TeX", availableFonts: ["STIX","TeX"], 
        linebreaks: { automatic: true }, EqnChunk: (MathJax.Hub.Browser.isMobile ? 10 : 50) }, 
        tex2jax: { inlineMath: [ ["$", "$"], ["\\\\(","\\\\)"] ], displayMath: [ ["$$","$$"], ["\\[", "\\]"], ], 
        processEscapes: true, ignoreClass: "tex2jax_ignore|dno" },
         TeX: {  noUndefined: { attributes: { mathcolor: "red", mathbackground: "#FFEEEE", mathsize: "90%" } 
        }, Macros: { href: "{}" } },
         messageStyle: "none", skipStartupTypeset: true });

        mjpd1.mathjaxEditing.prepareWmdForMathJax(editor, '', [["$", "$"]]);

Where should I add your `MathJax.Hub.Register.LoadHook(...);` code? 
Shouldn't this be triggered after each keypress in the editor?

**Comment by dpvc** [comment]
Yes, that is my code that you link to, written for the StackExchange network and their configuration.  It will require slight modifications to work properly in your situation.  On StackExchange, they only use `$...$` and `$$...$$` delimiters, and the code doesn't take any others into account, so you would need to fix that.  For example, your configuration seems to use `\\(...\\)` and `\[...\]` as delimiters.  The preview code should be modified to include these, and the new `$$$...$$$`, in its computations.

To make it work, you would fits add `["$$$","$$$"]` to the `displayMath` array in your configuration above so that MathJax will process them later.  Then add the `MathJax.Hub.Register.LoadHook()` call after your `MathJax.Hub.Config()` above.

Then in `mathjax-editing.js`:

* Change line 77 to 
   
           var SPLIT = /(\${1,3}|\\(?:begin|end)\{[a-z]*\*?\}|\\[\\{}$()\[\]]|[{}]|(?:\n\s*)+|@@\d+@@|`+)/i;

* Change line 193 to

                        if (block.charAt(0) === '$' || block === '\\[' || block === '\\(') {

* Remove line 27 (`var inline = "$";`)

* Remove line 268 (`inline = delimiters[0][0];`)

* Change line 266 to 

            function prepareWmdForMathJax(editorObject, wmdId) {

* Change your last line in the code block you provided above to

    mjpd1.mathjaxEditing.prepareWmdForMathJax(editor, '');

*  Change `["\\\\(","\\\\)"]` to `["\\(","\\)"]` in your configuration above.

That should take care of it, assuming what you really want is `\(...\)` not `\\(...\\)` as the alternative inline delimiters.

> Shouldn't this be triggered after each keypress in the editor?

The hook only need to run when the `tex2jax.js` file is loaded, as it modified the tex2jax preprocessor itself to handle `$$$...$$$`.  So whenever tex2jax is run by MathJax, it will properly handle your new delimiters.  The hook only has to be used once initially to set that up.

**Comment by josephernest** [comment]
Thanks a lot @dpvc for your detailed answer. 

> On StackExchange, they only use $...$ and $$...$$ delimiters

That's totally fine for me, I don't know why I still had \\(...\\) and \[...\] in my code (probably from a copy/paste). Having just `$...$`, `$$...$$`, `$$$...$$$` is totally fine for me.

**Comment by dpvc** [comment]
OK, then line 77 should be

    var SPLIT = /(\${1,3}|\\(?:begin|end)\{[a-z]*\*?\}|\\[\\{}$]|[{}]|(?:\n\s*)+|@@\d+@@|`+)/i;

and 193 should be

    if (block.charAt(0) === '$') {

**Comment by josephernest** [comment]
Thanks again @dpvc. Even after a few hours, I cannot make it work here:

    github.com/josephernest/writing

Could you have a look if you manage to add `$$$...$$$`? Thanks in advance.

Live demo here: https://josephernest.github.io/writing/
(CTRL + SHIFT + H for help)

**Comment by dpvc** [comment]
I've modified your `mathjax-editing_writing.js` file, available at this [gist](https://gist.github.com/dpvc/880f630b8322af6f9fd7ba2fe8aea2b5).  I'm afraid I didn't update the comments at the top, however, so you might want to `diff` this against your original and do that.  The changes are basically what I indicated above, though the line numbers were different due to your comments at the top (my line numbers were based on the original version of the file that you linked to).

I also changes your main .html file to add the needed configuration.  Here is the updated `togglemathjax` function.  I've reformatted the existing `MathJax.Hub.Config()` call in order to make it more readable here.  Also, I modified the macro for `\href`, since the one used would leave both the link URL and the link text in the output.  This one removes the link URL.  I'm not sure if you just copied that, or if you actually are trying to disable `\href`.  If you are, then I would recommend using the `Safe` extension instead, as it handles this situation (and a number of others) with more flexibility and care.  Finally, I replaced your setting of the MathJax queue's internal `pending` value to `MathJax.Hub.Cancel()`; it is a bad idea to alter MathJax's internal state like that.

``` javascript
togglemathjax = function(enabled) {
    if (enabled) {
        if (!latexenabledonce)
        {
          MathJax.Hub.Config({
            "HTML-CSS": {
              preferredFont: "TeX", availableFonts: ["STIX","TeX"],
              linebreaks: { automatic: true },
              EqnChunk: (MathJax.Hub.Browser.isMobile ? 10 : 50)
            },
            tex2jax: {
              inlineMath: [ ["$", "$"] ],
              displayMath: [ ["$$","$$"], ["$$$","$$$"] ],
              processEscapes: true,
              ignoreClass: "tex2jax_ignore|dno"
            },
            TeX: {
              noUndefined: {
                attributes: {
                  mathcolor: "red",
                  mathbackground: "#FFEEEE",
                  mathsize: "90%"
                }
              },
              Macros: { href: ["#2", 2] }
            },
            messageStyle: "none",
            skipStartupTypeset: true
          });
          MathJax.Hub.Register.LoadHook("[MathJax]/extensions/tex2jax.js", function () {
            var TEX2JAX = MathJax.Extension['tex2jax'];
            var CREATE = TEX2JAX.createMathTag.bind(TEX2JAX);
            TEX2JAX.createMathTag = function (mode,tex) {
              if (this.search.end === '$$$') {
                tex = '\\begin{eqnarray}'+tex+'\\end{eqnarray}';
              }
              return CREATE(mode,tex);
            }
          });
          mjpd1.mathjaxEditing.prepareWmdForMathJax(editor, '');
          latexenabledonce = true;
          if (editor.refreshPreview !== undefined)
              editor.refreshPreview();
        }
        else {
            MathJax.Hub.Cancel();
            MathJax.Hub.Queue(["Typeset", MathJax.Hub, "wmd-preview"]);
        }
    }
    else {
        MathJax.Hub.queue.pending = 1; 
        if (editor.refreshPreview !== undefined)
            editor.refreshPreview();
        else {
           MathJax.Hub.Config({ skipStartupTypeset: true });
        }
    }
}
```

These changes worked for me.

**Comment by josephernest** [comment]
This is great! Can you post a pull request with your code on https://github.com/josephernest/writing? Then I'm sure to use exactly the same code you used. Thank you very much once again @dpvc.
