### ISSUE TITLE
Feature Request: Add 3rd Party extensions

### ISSUE THREAD

**Issue by deJagerF** [mathjax/MathJax#1851]
Greetings

I know it is possible to add extensions to MathJax.
I don't know if it has been discussed, but would it be possible to add the extensions to the base config files.
This will assist new users to get the extensions to work.

Regards
Francois

**Comment by pkra** [comment]
Thanks for filing this request.  

Personally, I think this request is too broad.

By their nature, 3rd party extensions are 3rd party and not part of the core product. The extensions in this repository come with the promise of the MathJax Consortium to take responsibility of the code and provide maintenance and development. It's not practical to extend this to arbitrary extensions.

However, individual 3rd party extensions have moved into the core (e.g., mhchem3, texvc-wikimedia) and if an extension finds wide spread uses, we naturally consider requests to add it to the core.

I suspect the situation is a bit more complicated at the moment since we shut down our CDN at cdn.mathjax.org which also hosted copies of the extensions formerly stored in https://github.com/mathjax/MathJax-third-party-extensions. 

If the problem is primarily with configurations, then perhaps the documentation at http://docs.mathjax.org/en/latest/options/ThirdParty.html needs to improve. Any suggestions would be welcome.

**Comment by deJagerF** [comment]
Greetings

Thanks for the feedback.
I understand your concern that you don't want to be responsible for non-core code.

The config is mentioning to place certain information at various locations within the config file. Where exactly and how not to break the config file is my concern, as I can see that some lines are ended by , other are delimited by {}.

Regards
