### ISSUE TITLE
[STIX-web] Unicode points that can be faked

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1858]
STIX does not have a glyph for U+2006 but it seems easy to handle internally.

**Comment by pkra** [comment]
Renamed the issue because here's a longer list:

* straight forward
    * U+2001 (em quad) not in STIXMathJax_Main,STIXMathJax_Monospace,STIXMathJax_Latin,STIXMathJax_Alphabets,STIXMathJax_Marks,STIXMathJax_Arrows,STIXMathJax_Operators,STIXMathJax_Symbols,STIXMathJax_Shapes,STIXMathJax_Misc,STIXMathJax_Variants,STIXMathJax_Size1
    * U+2006 (six per em) not in STIXMathJax_Main,STIXMathJax_Monospace,STIXMathJax_Latin,STIXMathJax_Alphabets,STIXMathJax_Marks,STIXMathJax_Arrows,STIXMathJax_Operators,STIXMathJax_Symbols,STIXMathJax_Shapes,STIXMathJax_Misc,STIXMathJax_Variants,STIXMathJax_Size1
    * U+2009 (thin space) not in STIXMathJax_Main,STIXMathJax_Monospace,STIXMathJax_Latin,STIXMathJax_Alphabets,STIXMathJax_Marks,STIXMathJax_Arrows,STIXMathJax_Operators,STIXMathJax_Symbols,STIXMathJax_Shapes,STIXMathJax_Misc,STIXMathJax_Variants,STIXMathJax_Size1
    * U+2204 (negated exists) not in STIXMathJax_Main-italic,STIXMathJax_Normal-italic,STIXMathJax_Script-italic,STIXMathJax_DoubleStruck-italic,STIXMathJax_SansSerif-italic,STIXMathJax_Latin-italic,STIXMathJax_Alphabets-italic,STIXMathJax_Marks-italic,STIXMathJax_Misc-italic,STIXMathJax_Variants-italic,STIXMathJax_Size1
    * U+25FB (white medium square) not in STIXMathJax_Main-italic,STIXMathJax_Normal-italic,STIXMathJax_Script-italic,STIXMathJax_DoubleStruck-italic,STIXMathJax_SansSerif-italic,STIXMathJax_Latin-italic,STIXMathJax_Alphabets-italic,STIXMathJax_Marks-italic,STIXMathJax_Misc-italic,STIXMathJax_Variants-italic,STIXMathJax_Size1
    * U+2217 (asterisk operator) not in STIXMathJax_Main-italic,STIXMathJax_Normal-italic,STIXMathJax_Script-italic,STIXMathJax_DoubleStruck-italic,STIXMathJax_SansSerif-italic,STIXMathJax_Latin-italic,STIXMathJax_Alphabets-italic,STIXMathJax_Marks-italic,STIXMathJax_Misc-italic,STIXMathJax_Variants-italic,STIXMathJax_Size1
    * U+2E (full stop) not in STIXMathJax_SansSerif
* unclear
    * U+210F (Planck constant over two pi) not in STIXMathJax_Main-italic,STIXMathJax_Normal-italic,STIXMathJax_Script-italic,STIXMathJax_DoubleStruck-italic,STIXMathJax_SansSerif-italic,STIXMathJax_Latin-italic,STIXMathJax_Alphabets-italic,STIXMathJax_Marks-italic,STIXMathJax_Misc-italic,STIXMathJax_Variants-italic,STIXMathJax_Size1
    * U+32 (2) not in STIXMathJax_Fraktur
    * U+2B (+) not in STIXMathJax_Fraktur
    * U+30 (0) not in STIXMathJax_Fraktur
    * U+31 (1) not in STIXMathJax_Fraktur
    * U+394 (Greek Capital Delta) not in STIXMathJax_Fraktur
    * U+2E (full stop) not in STIXMathJax_Fraktur
    * U+2111 (black letter capital I) not in STIXMathJax_Fraktur
    * U+211C (black letter capital R) not in STIXMathJax_Fraktur

**Comment by dpvc** [comment]
The web fonts data files (that is, all the fonts other than the MathJax TeX and local STIX fonts) all have serious problems as they don't have the proper fallbacks for most of the variants.  E.g., the Fraktur variant doesn't fall back to normal variant for characters not in the Fractur font.  This general issue is already in the font milestone as #904.

How critical is this in the short term for you?  I have tried not to modify the data files for these by hand too much because they were generated programmatically (though there have been some changes).  To fix this properly, I'd have to fix the code that generates them, and that would take some time, since it is (a) not code I wrote, and (b) written in python, which I haven't used very much and don't know very well (so would involve lots of looking things up).  Or I could modify them by hand (some more) and just give up on the programmatic generation of these files for now.  We are going to be having to redo all of that for v3 anyway (which is another reason I haven't spent any time on this).  But if you need it for mathjax-node that might be reason to do something about it now.

BTW, it would be better to list missing character by MathML variant, not by the STIX font files.  The SVG output looks up character by variant, and it is the linking of fonts to variants that needs to be improved.  The CommonHTML output added a "chaining" feature that allowed one variants to fall back on another one, and that could be added to the SVG (and HTML-CSS) output.  Right now, the chaining data is in the font data file, but a default chaining tree might be able to be used so that the webfoot data files don't need to be altered.

**Comment by pkra** [comment]
> This general issue is already in the font milestone as #904.

Ok. [I hadn't considered 904 as a meta issue.]

> How critical is this in the short term for you?

Not critical at all. I was collecting this information in a client project and wanted to record it here so I don't forget about it.

> BTW, it would be better to list missing character by MathML variant, not by the STIX font files.

Copy that. (I don't always have that information though.)

**Comment by pkra** [comment]
Just another note (not really relevant for development but perhaps for anyone who runs into this).

It turns out `\square` creates U+25FB which is then not found in STIX. That seems unlikely or more likely to be a fontdata issue than an actually missing glyph. What's slightly odd is that it still gets an italic style applied so the fallback glyph will be italicized.

**Comment by pkra** [comment]
Forgot to add: `\style{font-style:normal}{\square}` finds an upright glyph in STIX-web.

**Comment by pkra** [comment]
Here's another fun one: `\mathscr{,}` (because authors forget to move the comma outside).
