### ISSUE TITLE
$a - b$ spaces differently to $a-b$

### ISSUE THREAD

**Issue by Pecnut** [mathjax/MathJax#1860]
Hi guys,
I find that on the version of MathJax installed on my WordPress site - Simple Mathjax - that $a - b$ gives different spacing to $a-b$. The former spaces like "a -b", and the latter spaces like "a - b". 
Do you know if this is a generic MathJax problem? If not, I'll pester the author of the WordPress plugin.
Cheers.

**Comment by pkra** [comment]
I can't reproduce the issue. Please post a link to a live example that exhibits the problem.

IIRC, the wordpress rich text editor converts the dash in `a - b` to an emdash; this would explain differences in rendering.

**Comment by Pecnut** [comment]
Aha, you're right. Even using the plain text editor on Wordpress, it converts `a - b` to an en dash. Trying to do `$a–b$` with an en dash replicates the odd spacing behaviour seen with `$a - b$`. 

Thank you! Annoying but at least I understand what's happening.

**Comment by pkra** [comment]
Thanks for the follow up. It's very strange that even the plain text editor does this. 

Turns out, this has come up on our mailing list. See  https://groups.google.com/forum/#!msg/mathjax-users/MXqOpqPeBF4/OTeVmRHRnXkJ;context-place=searchin/mathjax-users/tex$20replace%7Csort:date for a hack you could use.
