### ISSUE TITLE
[HTML-CSS][FF][MacOS] supscripts can be too close to base

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1869]
Reported at https://stackoverflow.com/questions/47344711/mathjax-exponent-too-close-from-term.

I could reproduce this on MacOS 10.12, FF 57.

It might be specific to STIX fonts (CommonHTML and SVG are fine).

**Comment by dpvc** [comment]
As you suspected, this is due to the font metrics of the STIX fonts.  The italic "j" extends to the left of its bounding box by .124em (which amounts to a pixel or two at usual sizes), while the TeX font's italic "j" only extends to the left by .012em (1/10 as much).  So when the superscript "j" is placed net to the "v" in the STIX fonts, the bottom of the "j" extends to the left of its bounding box by a few pixels, and bumps the base "v".  This is inherent in the metrics of the STIX fonts.  I would be hesitant to change the metrics for fear for making other situations worse.

**Comment by dpvc** [comment]
I've marked it "accepted" but I'm not sure what else to mark it as, since there doesn't seem to be another applicable label.  Should we have a "font bug" label?

**Comment by pkra** [comment]
> Should we have a "font bug" label?

Sounds good to me but  `upstream` is perhaps enough?

I've added this issue to the "a future font release" milestone because when we switch to STIX2 (which is really a new font) we can check if this kind of problem is resolved.

**Comment by dpvc** [comment]
"Upstream" is good, thanks.

Yes, checking the situation with STIX2 is a good idea.

**Comment by dpvc** [comment]
It turns out that this is probably actually due to the same issue as #1923.  So I'm remarking this as a duplicate of that.

**Comment by dpvc** [comment]
Fixed by #1923.
