### ISSUE TITLE
tex2jax.js#balanceBraces does not appear to be a "real" option

### ISSUE THREAD

**Issue by zhantongz** [mathjax/MathJax#1871]
It seems like the[ only times](https://github.com/mathjax/MathJax/search?utf8=%E2%9C%93&q=balancebraces&type=) `balanceBraces` occurs are in configs.

The example given in documentation `$y = x^2 \hbox{ when $x > 2$}$` also does not reflect any change in behaviour when setting the option `false` (I tried with https://www.checkmyworking.com/misc/MathJax-play-area/).

**Comment by pkra** [comment]
That's a fun catch. It seems to go back all the way to the original introduction for v2 (5 years ago). https://github.com/mathjax/MathJax/commit/522b743b5679afdf7b0c1ea363c8344d8aeca9dd#diff-9d4fe5e8491f0f95c7487fba6b84fd57

**Comment by dpvc** [comment]
Not sure what happened, there.  It was meant as a backward-compatibility switch for sites that had used MathJax v1.x that had the older behavior.  Apparently I messed things up somewhere in the v2.0 development and lost the code that implemented it.  Since there was no outcry about it, I guess there was no need for concern about the backward compatibility.  In any case, I think the configuration parameter should be removed, both from the configurations and the documentation, since it is not needed.

**Comment by dpvc** [comment]
==> Merged.
