### ISSUE TITLE
Sum between expressions does not render with subscripts

### ISSUE THREAD

**Issue by Lionex** [mathjax/MathJax#1873]
This renders, as two block expressions with the expression I'm trying to write separated at the sum
```
$$
\\text{DirectBias}_C = \\frac{1}{|N|}
$$

$$
\\sum_{\\vec{w}\\in N}
|\\cos\\left(\\vec{w},\\mathbb{g}\\right)|^C
$$
```
![seperated](https://user-images.githubusercontent.com/14112725/33282585-11df1016-d377-11e7-9caf-8e1adff8f048.png)

This does not render, with the whole expression together
```
$$
\\text{DirectBias}_C = \\frac{1}{|N|}
\\sum_{\\vec{w}\\in N}
|\\cos\\left(\\vec{w},\\mathbb{g}\\right)|^C
$$
```
![expression-together](https://user-images.githubusercontent.com/14112725/33282592-16e7722e-d377-11e7-9b0c-7a4f3789033c.png)

It works if I don't have the subscript for the sum.  It seems that the _ is removed (I am using markdown), but no matter what I do I can't get it to show up.

![together_no_subscript](https://user-images.githubusercontent.com/14112725/33282641-3db42ff0-d377-11e7-8c33-40332ae387ee.png)

**Comment by Lionex** [comment]
This renders,
```
$$
\\text{DirectBias}_C = \\frac{1}{|N|}
\\sum_w|\\cos\\left(\\vec{w},\\mathbb{g}\\right)|^C
$$
```
![single-letter](https://user-images.githubusercontent.com/14112725/33282946-426013c4-d378-11e7-8c4f-bbac847582f8.png)

but this does not
```
$$
\\text{DirectBias}_C = \\frac{1}{|N|}
\\sum_{w}|\\cos\\left(\\vec{w},\\mathbb{g}\\right)|^C
$$
```

the only difference being `w` vs `{w}`

**Comment by Lionex** [comment]
Rendered in html instead:
![html](https://user-images.githubusercontent.com/14112725/33283060-a7092162-d378-11e7-8568-975db1d89c83.png)

**Comment by dpvc** [comment]
Note that in your first message, in the image that is un-rendered, not that from the "`C`" through the "`\sum`" is in italics.  That suggests that the content-management system that you are using uses underscores to delimit text in italics, and so the page will be shipped to the browser as
```
$$
\\text{DirectBias}<em>C = \\frac{1}{|N|}
\\sum</em>{\\vec{w}\\in N}
|\\cos\\left(\\vec{w},\\mathbb{g}\\right)|^C
$$
```
or something similar.  MathJax does not process text that includes HTML tags, and so it will appear as you have indicated.  You may need to use `\_` in place if `_` in order to prevent that, or otherwise mark the math as material that should not be processed by the content management system (verbatim text).  How you do that will depend on the system you are using, so you should consult the documentation for that in order to work out how to accomplish this.  

In any case, it is not an issue within MathJax itself.

**Comment by Lionex** [comment]
Ah, I usually do escape the underscores but I hadn't caught that it was the previous subscript that was causing the parse error, thank you for getting back to me!
