### ISSUE TITLE
Improve Usability: Add "Copy" entry to Context Menu

### ISSUE THREAD

**Issue by q2apro** [mathjax/MathJax#1886]
Currently you provide this context menu: 

![image](https://user-images.githubusercontent.com/6764548/34115818-4e6b01f8-e41f-11e7-8425-30f9f60ec89b.png)

So everyone, worldwide, using Mathjax has to go to `Show Math As`, then in our case `TeX Commands`, which will open a new window: 

![image](https://user-images.githubusercontent.com/6764548/34115879-8065e6b4-e41f-11e7-926e-da8d5741132a.png)

Now the user has to mark all text inside this window, then CTRL + C to copy it. 

This is a hell lot of steps just to copy the TeX code! 

Please add a "Copy as TeX" entry to the main entries, best on top. That would help many users!

Related: https://tex.meta.stackexchange.com/q/821/63540

**Comment by pkra** [comment]
Duplicate of #1663.

Note that "copy as TeX" won't always be available as it depends on the input. Also, page authors can easily set up more refined ways to allow "real" copy&paste (by adding hidden content that will be copied instead of the selection).

**Comment by q2apro** [comment]
Wow, mentioned at: 
https://github.com/mathjax/MathJax/issues/1117
https://github.com/mathjax/MathJax/issues/1663
and now here. 

You should definitely consider this, a serious request by the community.

PS: How to implement it? Can you give an example of `more refined ways to allow "real" copy&paste`.

**Comment by dpvc** [comment]
Historically, access to the clipboard was considered a security risk, since you could get access to the last copied text, and that could be things like a password, or banking information, etc.  So Browsers did not allow javascript to have access to the clipboard.  When MathJax was originally designed (10 years ago!), there was no reliable cross-browser means of doing copy and paste over time, some fragile approaches, or ones relying on flash applets or other external technologies, became available, but these could well have been shut down by browser makers as security risks.

It is only relatively recently that libraries like [clipboard.js](https://github.com/zenorocha/clipboard.js) have become available, and only in the middle of last year did the last holdout (Safari) begin to provide the tools needed to support it (in Safari 10).  So it is only recently that the browsers that MathJax targets could even support such a feature.  (A desire by the community is not always enough to make something possible.)

Our current development efforts ate going to the version 3 rewrite, so it is unlikely that major new features will be added to v2.x in the near future.  But since MathJax is an open-source project, it is possible for others to contribute this type of feature.  One could [write an extension](http://docs.mathjax.org/en/latest/advanced/extension-writing.html) that loads clipboard.js, [waits for the "MathMenu Ready" signal](http://docs.mathjax.org/en/latest/advanced/signals.html#creating-a-listener) and uses the menu API (not well documented -- you'd have to [look at the code](https://github.com/mathjax/MathJax/blob/master/unpacked/extensions/MathMenu.js)) to add one or more "copy as" menu items (there are two natural forms that you might want: the original input format, and the generated MathML) that call the clipboard.js code to copy the appropriate text. I wouldn't recommend removing (or taking over) the current "Show math as" menus, as some people use them just to be able to see the original TeX code for educational purposes.

I consider this an intermediate-level project, but one that certainly could be done by a community member with an interest in contributing to MathJax.

**Comment by q2apro** [comment]
Why to make it so complicated?

**Idea:**
Just add an option `Show as plain Latex` which either replaces the mathjax rendered formulas with their latex code OR adds the latex code below the formula. No clipboard action needed.

**Comment by dpvc** [comment]
There is already such an option (the PlainSource renderer).

**Comment by jabobian** [comment]
`Render as plain Source` is missing at the V3.2, where only rendering as CHtml and SVG are available, what a pity!
Please supply other options!

**Comment by dpvc** [comment]
@jabobian, please see [this comment] for a work-around for now.
