### ISSUE TITLE
MathJax tests fall back to image fonts in Firefox 57 on Linux

### ISSUE THREAD

**Issue by mitya57** [mathjax/MathJax#1891]
What I did:

- Cloned the latest master branch of this repository.
- Opened `test/index.html` in Firefox (57.0.1).
- Got the message: “The browser you are using does not seem to support web-based fonts, so we can't test the MathJax web fonts with this browser (image fonts have been used instead).”

The renderer is set to HTML-CSS by default. If I select CommonHTML, then it does not fall back to images, but uses my system font (Liberation Serif) instead, which does not look nice.

[The online demo page](https://www.mathjax.org/#samples) works fine, it uses local STIX fonts with HTML-CSS renderer and WOFF MathJax fonts with CommonHTML renderer. So it looks like an issue with local pages only.

I tried running Firefox with a clean profile, got the same resuls. I have `fonts-stix` Debian package installed, but not `fonts-mathjax`.

Everything works fine in Chromium (63.0.3239.84).

I reproduced this on two systems: one running Debian GNU/Linux sid amd64 and another running an almost clean installation of Ubuntu 17.10 amd64.

*P.S. Happy holidays!* 🎄 ⛄️

**Comment by mitya57** [comment]
The original bug description was wrong about the online demo, it actually works fine. Please read the updated description instead.

**Comment by dpvc** [comment]
This is the expected behavior.  See [the documentation](http://docs.mathjax.org/en/latest/installation.html#firefox-and-local-fonts) for more details.  The issue is that the Firefox's interpretation of the same-domain-origin policy prevents it from loading web fonts from a `file://` URL.  The `test/index.html` is set up to only use web fonts, not local fonts, so this fails for Firefox.

That is only a problem for local pages, not ones served through a web server, and even for local pages, the HTML-CSS output will use locally install STIX or MathJax fonts rather than web fonts (other than on pages like `index.html` that specifically forbid that).  The CommonHTML output would use locally install MathJax fonts (but not STIX fonts), if available; it does not have an image fallback method.

**Comment by mitya57** [comment]
> The CommonHTML output would use locally install MathJax fonts (but not STIX fonts), if available.

Where should the MathJax fonts be installed? I now have the Debian `fonts-mathjax` package installed (it ships fonts in `/usr/share/javascript/mathjax/fonts/HTML-CSS/`), but it does not help: the CommonHTML output still uses my system font.

I am the maintainer of MathJax package in Debian, and I am now preparing a new upload. Does it make sense to move the fonts to some other location? Will it break something? Local files are quite an important uses case for a Debian package, because we have lots of locally installed documentation.

**Comment by dpvc** [comment]
> Where should the MathJax fonts be installed?

I'm not a Debian user, so I can't test it, but according to the [Debian Wiki](https://wiki.debian.org/Fonts#Manually), they should either be in
`/usr/local/share/fonts` (for system-wide use), or `~/.local/share/fonts` or `~/.fonts` (for user-specific use), and need to have the correct permissions (group and world read permission) on the directory and fonts.  Finally, you need to run `fc-cache` after installing the fonts.

One can customize the directories searched, so it would be possible to add `/usr/share/javascript/mathjax/fonts/HTML-CSS/` to the font path (assuming the `.otf` files are in that directory).  See the documentation for details.

> Does it make sense to move the fonts to some other location? Will it break something?

I can only tell you that this location is not used by directly by MathJax itself, so changing it would not affect MathJax.  I can't tell you whether it would affect any other uses.

**Comment by mitya57** [comment]
Ok, thanks for your response!
