### ISSUE TITLE
[HTML-CSS]] stretchy horizontal character shows gap in chrome 

### ISSUE THREAD

**Issue by varunkn07** [mathjax/MathJax#1896]
![issue](https://user-images.githubusercontent.com/20451860/34821472-d00e0638-f6e9-11e7-9566-21edd3dcd906.JPG)

Issue found on google chrome. if we add AP or PA with vector symbol a broken arrow will be displayed. It's  working fine when the letters are in italic or bold style. In case of regular style the issue appears.

**Comment by dpvc** [comment]
Thanks for the report.  It turns out that the HTML-CSS output jax is misplacing the right-most glyph in multi-character stretchy horizontal characters.  The fix is easy, and will be in the next release of MathJax.  For now, you can use

```
<script type="text/x-mathjax-config">
MathJax.Hub.Register.StartupHook("HTML-CSS Jax Ready", function () {
  var HTMLCSS = MathJax.OutputJax["HTML-CSS"];
  var EXTEND = HTMLCSS.extendDelimiterH.bind(HTMLCSS);
  HTMLCSS.Augment({
    extendDelimiterH: function (span,W,delim,scale,font) {
      var result = EXTEND(span,W,delim,scale.font);
      var right = span.firstChild.childNodes[1];
      var x = parseFloat(right.style.left);
      right.style.left = HTMLCSS.Em(x - right.bbox.lw);
      console.log(right);
      span.bbox.w -= right.bbox.lw;
    }
  });
});
</script>
```
right *before* the script that loads `MathJax.js` itself in order to work around the problem.  (When you move to the new version, you should remove this patch.)

Alternatively, you could switch to the CommonHTML output (or SVG output), which don't have this issue.

**Comment by varunkn07** [comment]
Ok. Thank you

**Comment by dpvc** [comment]
==> In testsuite
MathMLToDisplay/Topics/StretchyChars/issue1896.html
