### ISSUE TITLE
this.text is null (MathJax.js:19:29656)

### ISSUE THREAD

**Issue by Trolli07** [mathjax/MathJax#1918]
Hello,

We have a particular problem with MathJax on the Moodle platform of one of our customers.

The error is: this. text is null (https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_HTMLorMML)

Here is the most information I can provide.

This is on moodle platform.
Using the MathJax library in a Scorm.
On the first display of Scorm, sometimes (sometimes not) this error is displayed.
If you disable the browser cache, this error appears almost systematically.

I can provide you with enough information so that you can replicate this error locally, but it takes some times.

We did not find any information about this bug in your issues tracker or on google.
Do you have any suggestions for solutions?
Don't hesitate to ask us more informations.

Kind regards,

Olivier

**Comment by dpvc** [comment]
Can you provide access to a live page that shows the problem?

Can you indicate how MathJax is loaded into the page, and any in-line configuration that is used?

**Comment by Trolli07** [comment]
Yes.

Open Firefox, clear your cache, disable your cache and enable debug.
Go here : http://olivier.cblue.be/moodle/mod/scorm/player.php?scoid=2&cm=6&display=popup
Login : mathjax
Password : MathJax123!

On my Moodle platform the problem does not appear systematically, but appears some times.

When the scorm is almost empy, that's the result of the problem "TypeError: this.text is null"

I just know that https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_HTMLorMML is loaded in the <head> tag of the iframe then the orthers are require in JS.

Which in-line configuration ?

Kind regards,

Oliiver

**Comment by Trolli07** [comment]
I have suspend the account created, I have to wait for our client's approval to share their scorm.
I'll keep you informed.

Kind regards,

Olivier

**Comment by Trolli07** [comment]
The account has now full access to the scorm :)

Kind regards,

Olivier

**Comment by dpvc** [comment]
Thanks, I've taken a look, and the situation seems to indicate that some part of the javascript used on the page within the iframe is setting `document.body.innerHTML` (probably from a copy of `document.body.innerHTML` that has been modified by a regular expression substitution or some such thing).  This means that all the elements on the page are rebuilt, and that means that the elements that MathJax created are also replaced by new versions.  MathJax caches the pointers to some of the elements it uses, and so those pointers point to the old elements not the new ones.

One of the elements cached in this way is the one used for the message display at the lower left corner of the window.  For this specific element, if it has been rebuilt by modifying `document.body.innerHTML` as described above, MathJax will try to reattach to the new copy (or create a new one if its old one wasn't copied), but it looks like there is a slight problem with this when there hasn't been a message already displayed: there are actually two pointers being cached, and one of them isn't recreated properly in that case.  This is the `this.text` that is being reported in your error message.

The easiest work-around for now would be to configure MathJax to not display messages, which should cause MathJax to never reference that broken pointer.  You can do that by adding

```
    messageStyle: "none"
```

to the `MathJax.Hub.Config()` call in the `HM.ConfigureMathJax()` function in `HM.js`.  This will disable the message area in the lower left.  Alternatively, if you want to retain the messages, it would be possible to use other configuration to override the function that is not working properly.  Let me know if you need to keep the messages going.

Technically, your page is not configuring MathJax properly, as the `HM.ConfigureMathJax()` is not coming at the right place, and there may be timing issues, even with my suggestion that you turn off the messages.  The configuration may be coming too late, and the first attempt to use the message (the one that is causing the error) may already have occurred.  In that case, my suggestion above won't work, and you may have to modify how you are configuring MathJax so that the configuration is in the right place for it to be done at the correct time.  So if setting `messageStyle` doesn't work, we may have to do more drastic changes.  Let me know how it goes.

**Comment by Trolli07** [comment]
Hello,

Thank you for your clear and precise answer and the proposed solution provided!

It works well for me, I'm waiting for a return from our client.

I saw that you created a new issue and fixed it, when will it be available?

Thanks again :)

Have a really good day.

Kind regards,

Olivier

**Comment by dpvc** [comment]
> I saw that you created a new issue and fixed it, when will it be available?

The v2.7.3 release is in its final stages and should be out very soon (potentially this week).

**Comment by Trolli07** [comment]
Thank you :)

Kind regards,

Olivier
