### ISSUE TITLE
mathit with index fail to compile when used in a line with other index expressions

### ISSUE THREAD

**Issue by yunxing** [mathjax/MathJax#1931]
Repro: 

Goto http://markx.herokuapp.com/, copy past following code. Notice the difference between expression 3 and 4 is that x doesn't have a index.

\\[ \begin{split} \mathit{coefficient}_l &= 1 \left( frac{x_{ijkl} - \mu_l}{\sigma^2_l+\epsilon} \right) \end{split} \\] -- doesn't render 

\\[ \begin{split} \mathit{coefficient} &= 1 \left( frac{x_{ijkl} - \mu_l}{\sigma^2_l+\epsilon} \right) \end{split} \\] -- renders

\\[ \begin{split} \mathit{coefficient_l} &= 1 \left( frac{x_{ijkl} - \mu_l}{\sigma^2_l+\epsilon} \right) \end{split} \\] -- renders

\\[ \begin{split} \mathit{coefficient}_l &= 1 \left( frac{x - \mu_l}{\sigma^2_l+\epsilon} \right) \end{split} \\] -- renders

**Comment by dpvc** [comment]
Since your document is in Markdown, you need to be aware that Markdown runs before MathJax does, and so the underscores in your first expression are being interpreted as indicating italics (notice the italics indoor output between the `|` and the `{ijkl}`).  That means Markdown has inserted `<em>` tags or something equivalent in order to get the italics, and since Mathjax doesn't allow HTML tags within the math it processes, that expression is not processed.

The reason the multiple underscores in the other documents don't cause problems is because the initial underscore must have a word break before it and the final one a word break after it.  That occurs in your first expression (the `|` is not a letter before the first underscore, and the `{` is not a letter after the second one), whereas in the others the underscores are either preceded or followed by letters, so do not indicate italics to Markdown, and so no `<em>` is inserted, and MathJax can process the math.

See #1873 for an issue describing the same problem, and the [MathJax documentation](http://docs.mathjax.org/en/latest/tex.html#tex-and-latex-in-html-documents) for more details on how you might avoid that.
