### ISSUE TITLE
Libertinus Math support

### ISSUE THREAD

**Issue by kiwi0fruit** [mathjax/MathJax#1932]
There is a nice looking font: Libertinus Serif / Libertinus Math. As far as I know it's the best-looking serif font. And Libertinus Math is an OpenType math font for use in OpenType math-capable applications like LuaTeX, XeTeX or MS Word 2007+.

It would be nice to have it in MathJax.

**Comment by alerque** [comment]
Just a comment: when making requests like this it generally does not help to overstate your case. I'm a heavy user of Libertinus fonts including publishing whole books in them and using them my default for many on-screen applications. I love them and agree they look great. However dogmatically asserting as fact "the best-looking serif font", something which is inherently opinion based, somewhat discredits the weight of your reports. Just tell it like it is, you have a preference.

Also please clarify what's going on here because there is no point in asking MathJax to — what? Bundle it? Support it? — if the math font doesn't support it in turn. Why did you open an issue on the font project for this? One or the other of these issues seems like it must have the cart before the horse. What is actually needed here?

**Comment by dpvc** [comment]
This does look like a useful font to know about.  @alerque, MathJax does need to know about the fonts that it uses, and so to use libertinus with MathJax, we would have to make the needed support files, at the least, and probably package web versions of the fonts as well (like we do with the STIX-web, Neo-Euler, and other MathJax web fonts.  So this is an appropriate request here.

@kiwi0fruit, we are in the process of a major update to MathJax v3, and will be redoing the fonts as part of that project.  We appreciate knowing about this font, and will look into its suitability for MathJax at that time.  Any updates to MathJax v2.x fonts will have to wait until after that.

**Comment by kiwi0fruit** [comment]
@dpvc Sounds great)

**Comment by kiwi0fruit** [comment]
Closing as italic Greek looks rather poor in Libertinus Math. And it's unlikely to change. See comparison with STIX Two Math:
![libertinus_vs_stix2](https://user-images.githubusercontent.com/19735117/55552455-95230a80-5707-11e9-82df-ed88491cfe03.png)
(surely you can reopen it if needed).
