### ISSUE TITLE
[2.7.3] [SVG] [STIX] changes to stretching parentheses

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1933]
I was testing 2.7.3 and my visual regression tests caught the following oddity:

Reduced test case:

```
$${{\left( \int \int \right)}^\frac{1}{2}}. $$
```

Using 2.7.3 with SVG output using STIX fonts, MathJax is using stretchy parentheses - in v2.7.2 it was using Size3 parentheses.

Oddly enough

``
$${{\left( \int \right)}^\frac{1}{2}}. $$
``

is using stretchy ones in 2.7.2 as well. (But not with two integrals or any other additional content).

I'm wondering if this is expected behahvior. Size3 looks a bit better to me but I could easily be wrong.

**Comment by pkra** [comment]
It might be specific to TeX input.

**Comment by dpvc** [comment]
I can reproduce in Safari, in both TeX and MathML.  I'll check into it.

**Comment by dpvc** [comment]
OK, the source of the issue is that the centering of the large operators isn't being taken into account in determining the height and depth of the mrow containing the stretchy characters.  The TeX versions of the integral are already centered, but the STIX ones are not, so it makes a difference there.  The effect is to make the mrow taller (and less deep) than it should be, but since the stretchy parentheses have `symmetric="true"` by default, it looks for a character of twice the height (or depth, whichever is larger), so gets one that is too big.

The reason it worked in version 2.7.2 is that there was an extra mrow being inserted incorrectly between the parentheses (and around the integrals), and the actual final bounding box of an mrow actually *is* being computed correctly (taking centering into account), so in the incorrect MathML was being rendered properly (because the height and depth for the mrow around the integrals is correct).  But that extra mrow is only being inserted between parentheses when there is more than one item in-between, so it is *not* inserted for the single integral, which is why it *doesn't* render properly.

It turns out that the extra mrow was introduced in version 2.7.0, so the incorrect size is used for all previous versions as well.  (So only 2.7.0 to 2.7.2 had the right size, but only accidentally.)

I have created a branch with the fix, and will make a PR.

**Comment by dpvc** [comment]
==> Merged.

**Comment by dpvc** [comment]
==> In testsuite
LaTeXToMathML/delimiters/issue1933.html
