### ISSUE TITLE
MathMenu.js and MathZoom.js 404 not found

### ISSUE THREAD

**Issue by NPersonal** [mathjax/MathJax#1934]
I use mathjax in my project of React.
npm install:
`npm install mathjax`
npm run:
`npm run dev`
this is request error info in chrome browser :

> Request URL:http://mydomain/extensions/MathMenu.js?V=2.7.2
Request Method:GET
Status Code:404 Not Found
Remote Address:127.0.0.1:80
Referrer Policy:no-referrer-when-downgrade

> Request URL:http://mydomain/extensions/MathZoom.js?V=2.7.2
Request Method:GET
Status Code:404 Not Found
Remote Address:127.0.0.1:80
Referrer Policy:no-referrer-when-downgrade

Remark: For some reason, i point mydomain to my local. I don't think this has anything to do with error.

**Comment by NPersonal** [comment]
I try manual paths for MathMenu and MathZoom, and this issue is resolved.
But math can't not render. here is my code:
` 
import MathJax from 'mathjax/MathJax.js'

export default class QuoteChapterModal extends Component {
 componentDidMount () {
    // MathJax.Hub.Queue(['Typeset', MathJax.Hub])
    window.MathJax.Hub.Queue(['Typeset', window.MathJax.Hub, ReactDOM.findDOMNode(this)])
  }

  componentDidUpdate () {
    // MathJax.Hub.Queue(['Typeset', MathJax.Hub])
    window.MathJax.Hub.Queue(['Typeset', window.MathJax.Hub, ReactDOM.findDOMNode(this)])
  }

 render() {
   return <div>\(ax^2 + bx + c = 0\)</div>
 }
}`

**Comment by dpvc** [comment]
MathJax determines the location of its files by looking for the `<script>` tag that loaded it.  It looks like you are loading MathJax via an `import` statement, so I suspect MathJax is not able to determine where its external files live.  It may be possible to configure MathJax's root directory to point to the URL where MathJax's files are found, but if you are using a package manager like webpack, it won't include MathJax's files, and so you may not be able to do that.  It might be better simply to include a `<script>` tag in you pages that loads MathJax from one of the CDNs that serve it.  Otherwise, you may need to manually include the MathJax files into your package, and configure the MathJax root to point to the URL where they can be found.
