### ISSUE TITLE
Bug: Set Notation

### ISSUE THREAD

**Issue by QL568A6** [mathjax/MathJax#1938]
### Issue Summary
Does not render set notation letters without \mathbb{...} despite documentation. (ex. `\R` is listed in the "Supported LaTeX commands" section, but produces a red "\R")
### Steps to Reproduce

1. Open MathJax demo page or other supported page (ex. StackExchange question)
2. Type `$\R$` or `$$\R$$`

This is a bug because the documentation does not match the reality of the engine.

### Technical details

* MathJax Version: Current
* Client OS: Windows 8
* Browser: Opera 50.0.2762.67 and Firefox 58.0.1

**Comment by dpvc** [comment]
Notice that in the [documentation](http://docs.mathjax.org/en/latest/tex.html#r), the `\R` macro is listed as being part of the `mediawiki-texvc` extension, so in order to use it, you need to load that extension.  It is not loaded by default on StackExchange, but you could force is by using `\require{mediawiki-texvc}`.  Note, however, that this will define lots of other macros as well, and your macros will apply to the rest of the page, not just your answer.  It might be better just to define the macro you need, e.g., `\def\R{\mathbb{R}}`, before using it.
