### ISSUE TITLE
\overline in Firefox Linux

### ISSUE THREAD

**Issue by cebola2** [mathjax/MathJax#1939]
This issue seems to be specific to the desktop version of Firefox on Linux. Observed on Firefox 58.0.2 and 59.0.1 (64-bit) for Linux Mint.

The length of the horizontal line created by a long \overline oscilates between too short and too long depending on screen magnification.

The particular example below is from https://cdi2tp.math.tecnico.ulisboa.pt/sumarios_teoricas uses $ \overline{[0,1]\cap\mathbb{Q}}=[0,1]$

The image corresponds to 100% magnification.
![imagem](https://user-images.githubusercontent.com/1136663/36841187-6f007598-1d3f-11e8-9e2b-6efdb04531a4.png)

The same example will render too long at 120%, 133% and 150%, just about right at 110% and 170%, etc.

No such effects are visible on Chrome on Linux or on Firefox for Android or Windows.

**Comment by cebola2** [comment]
This is still present in MathJax 2.7.4.

**Comment by dpvc** [comment]
> This is still present in MathJax 2.7.4.

Yes, as you can see, there were no fixes included in this, and it was not part of the 2.7.4 milestone.

The reason is that there probably isn't anything to be done about it.  The fact that the results vary according to the zoom scaling suggest that the issue is most likely due to pixel round-off issues.  The widths of the various characters are given in values that include decimal parts of a pixel, and MathJax's computation of the width of a run of characters (like `[0,1] ∩ ℚ` in your example) is the the sum of the individual widths, so it uses an over-line of that width.  When browsers render the characters, however, they have to place them within the pixels on screen, and they may round the placements to nearest pixel positions, for example.  That may mean that the characters displayed do not have exactly the width that MathJax computed; furthermore the actual width of the characters may vary depending on the scale because different roundings are used for different scalings.  Because you sometimes see the line too long and sometimes too short, this is probably the effect you are seeing. 
Note that, since you are using the CommonHTML output jax, the exact same HTML and CSS are used for all browsers and operating systems.  So the fact that you are seeing the correct results in Chrome, and in Firefox for other platforms, suggests that MathJax's computations of the line width are correct, and that it is Firefox's rendering of the characters that is the source of the problem.  

Because the over-line is also made up of several characters, the positioning issues can be exacerbated (the rounding of the two different runs of characters are not identical).  Although the over-line could have been produced in other ways than as a string of characters itself, other accents (like over-braces and over-arrowss) would be harder to do in a way that would match the rounding no matter what they were.

I'm going to mark this as a browser bug because of these reasons.

**Comment by cebola2** [comment]
Thanks for the detailed explanation. I will enter a bug in Firefox' Buzilla.
