### ISSUE TITLE
HTML-CSS paths sometimes contain "/TeX/TeX/" instead of just "/TeX/"

### ISSUE THREAD

**Issue by instantname** [mathjax/MathJax#1945]
# Description

Not sure if this is a misconfiguration or a bug. With the configuration described below, I get a few 404 errors with paths such as, but not limited to:

  - "GET /static/MathJax-2.7.2/jax/output/HTML-CSS/fonts/TeX/TeX/fontdata.js?V=2.7.2 HTTP/1.1"
  - "GET /static/MathJax-2.7.2/fonts/HTML-CSS/TeX/TeX/woff/MathJax_Main-Regular.woff?V=2.7.2 HTTP/1.1"
  - "GET /static/MathJax-2.7.2/fonts/HTML-CSS/TeX/TeX/otf/MathJax_Size1-Regular.otf?V=2.7.2 HTTP/1.1"

The files are obviously not found because of the repetition of "TeX/" in the paths.

All problematic paths contain "HTML-CSS". In my logs, these errors appear mainly with the Safari browser, although I also see Firefox sporadically. Unfortunately I could not test myself on Safari, so I don't know how equations are displayed, nor how to produce the error myself.

# Configuration

MathJaX is loaded locally:

```
<script type="text/javascript" async src="/static/MathJax-2.7.2/MathJax.js?config=TeX-AMS_CHTML,https://mysite.com/mathjax-local.js&amp;locale=de"></script>
```
with mathjax-local.js contents being:
```
MathJax.Hub.Config({
    extensions: ["tex2jax.js"],
    jax: ["input/TeX", "output/HTML-CSS"],
    showMathMenu: false,
    tex2jax: {
	inlineMath: [ ['$','$'] ],
	displayMath: [ ['$$','$$'] ],
	processEscapes: true,
	processRefs: false,
	processEnvironments: false,
	ignoreClass: "disable-tex2jax",
	processClass: "enable-tex2jax"
    },
    "HTML-CSS": { availableFonts: ["TeX"] },
    CommonHTML: { scale: 95 }
});
MathJax.Ajax.loadComplete("https://mysite.com/mathjax-local.js");
```

**Comment by dpvc** [comment]
I haven't seen any other reports of this occurring, so I suspect it has something to do with your setup.

The messages are coming from the HTML-CSS output jax, which is a bit odd since you have specified the CommonHTML output jax in your `config=` parameter when loading `MathJax.js`.  That may be because you have `output/HTML-CSS` in your `mathjax-local` file.  In fact, you don't need the `extensions` or `jax` arrays at all, because those are already loaded by the `config=TeX-AMS_CHTML` configuration.  Try taking those lines out of your local configuration and see if that clears it up.

The only way I can see that you could get this double directory name is if the HTML-CSS's `loadComplete()` call is being performed twice for the `jax.js` file.  The only way I could see that happening is if the `jax.js` file is loaded twice.  Can you tell from your logs whether that is happening?  (It may to show up in the logs, as the browser should use the cached version for the second one, but it is worth a look.)
