### ISSUE TITLE
can't unzip 

### ISSUE THREAD

**Issue by kingwood** [mathjax/MathJax#1948]
unzip downloaded zip file !

**Comment by dpvc** [comment]
The zip file available from the "Clone or download" button on the MathJax GitHub page unpacks just fine for me.  Perhaps your file didn't fully download; you might try downloading it again.  If that doesn't work, make sure the downloaded file name has ".zip" as an extension before trying to unpack it.  Otherwise, you would need to give more information about your situation (e.g., the system you are working on, the zip program you are using, any error messages you receive, etc).  

Note, however, that (since the zip file is fine), this is really not a MathJax issue, so we may not be able to help you.
