### ISSUE TITLE
Wrong handling of MathML with prefixed elements

### ISSUE THREAD

**Issue by regina-henschel** [mathjax/MathJax#1951]
If the MathML-elements are prefixed, then the script does not work. With the attached document (rename from .txt to .xhtml) [XHTML_NS_global.txt](https://github.com/mathjax/MathJax/files/1822806/XHTML_NS_global.txt)
 and Seamonkey 2.48 I get the error message
`Error parsing MathML: XML-Verarbeitungsfehler: nicht wohlgeformt Zeile Nr. 1, Spalte 49:<math xmlns="http://www.w3.org/1998/Math/MathML":math xmlns:math="http://www.w3.org/1998/Math/MathML"> ------------------------------------------------^ 
`
The same happens, if the xmlns-attribute is in the `<math>`-element.

The same file without script works fine in Seamonkey.

**Comment by dpvc** [comment]
OK, it turns out that MathJax's MathML input jax uses a regular expression substitution to insert an `xmlns` parameter into the serialized MathML before parsing it (because MathML from HTML pages don't include one in general), but this regular expression gets confused when the prefix is `math`.   The error is in [line 212](https://github.com/mathjax/MathJax/blob/master/unpacked/jax/input/MathML/jax.js#L212-L215), which incorrectly matches when the prefix is `math`.

It is easily fixed, and if you insert

```
<script type="text/x-mathjax-config">
<![CDATA[
MathJax.Hub.Register.StartupHook("MathML Jax Ready", function () {
  var MathML = MathJax.InputJax.MathML;
  MathML.Parse.Augment({
    preProcessMath: function (math) {
      if (math.match(/^<[a-z]+:/i) && !math.match(/^<[^<>]* xmlns:/)) {
        math = math.replace(/^<([a-z]+)(:math)/i,'<$1$2 xmlns:$1="http://www.w3.org/1998/Math/MathML"')
      }
      // HTML5 removes xmlns: namespaces, so put them back for XML
      var match = math.match(/^(<math( ('.*?'|".*?"|[^>])+)>)/i);
      if (match && match[2].match(/ (?!xmlns=)[a-z]+=\"http:/i)) {
	math = match[1].replace(/ (?!xmlns=)([a-z]+=(['"])http:.*?\2)/ig," xmlns:$1 $1") +
               math.substr(match[0].length);
      }
      if (math.match(/^<math[ >]/i) && !math.match(/^<[^<>]* xmlns=/)) {
        // append the MathML namespace
        math = math.replace(/^<math/i,'<math xmlns="http://www.w3.org/1998/Math/MathML"')
      }
      math = math.replace(/^\s*(?:\/\/)?<!(--)?\[CDATA\[((.|\n)*)(\/\/)?\]\]\1>\s*$/,"$2");
      return math.replace(/&([a-z][a-z0-9]*);/ig,this.replaceEntity);
    }
  });
});
]]>
</script>
```
into your file just *before* the script that loads MathJax.js itself, that should resolve the issue for you until it is fixed in MathJax.  Alternatively, you can use a different prefix (one that doesn't have `math` as its first four characters).

**Comment by regina-henschel** [comment]
Thank you for your fast respond. Using a different prefix works.

**Comment by dpvc** [comment]
==> In testsuite
Parsing/issue1951.html
