### ISSUE TITLE
rendering is taking too much time

### ISSUE THREAD

**Issue by dverma4u** [mathjax/MathJax#1952]
I am using mathjax with my react-native quiz application. But it is taking too much time in loading the question with all four options and downgrading the performance of application.
I tried putting loader when webview loads but loader stays only untill the webview loads and rending of mathematical questions still takes more time to display.
Any way by which we can reduce the rendering time or put a loader/activity indicator on rending too?

**Comment by dpvc** [comment]
Without more information about how your application works, how it interacts with MathJax, and what MathJax configuration you are using, it is not possible to answer your question about reducing rendering time.

As for showing a loader during rendering, consider [this post](https://stackoverflow.com/questions/42982417/displaying-spinner-until-mathjax-loaded-even-with-direct-anchors-url) as an example.  You use `MathJax.Hub.Queue()` to queue a function that turns off the load indicator, and it will not run until after MathJax finishes typesetting the page (since the initial typesetting has been queued before your function).

Finally, note that this is not the best place to ask such questions.  This issue tracker is for reporting errors in MathJax.  Asking questions about how to do things is better done on the [MathJax User Forum](https://groups.google.com/forum/?fromgroups#!forum/mathjax-users) where more people will see it.
