### ISSUE TITLE
Some expression can't be display correcttly

### ISSUE THREAD

**Issue by peterjixian** [mathjax/MathJax#1955]
`\(A={ x∈R | -3<x<2}, B={x∈R|\(x^2\)-4x+3≥0},\)`   can't be display correcttly!

**Comment by dpvc** [comment]
You don't say what you mean by not displaying correctly, and since there are several issues with your expression, I'm not sure which one you are referring to.

* First, `\(` and `\)` are not defined (unless you have defined them earlier in your page), so that can cause the expression to produce an error (depending on your configuration).
* Second, since braces are special characters in TeX, you need to use `\{` not `{` to get a literal brace in the output.
*Third, since the mathematics is part of an HTML page that is parsed as HTML before MathJax runs, you have to be careful about the use of HTML special characters like `<` and `&`.  For example, the `<x` in your `-3<x<2` will look like the start of an `<x>` tag to the browser, and that will cause problems for MathJax when it tries to read the math later on.  Putting spaces around these is one way to avoid that problem.  Using `\lt` or `&lt;` instead is another.

There are also some stylistic issues (these don't prevent the math from being typeset, but do cause it to render poorly):

* You should use `\mid` rather than `|` within set notation (this will improve the spacing around the bar, and fix the spacing of the minus sign before the 3).
* For sets in set-builder notation, it is customary to use `\,` spacing inside the braces.
* Although you can use characters like `∈` and `≥`, it may be better to use the TeX commands for these (`\in` and `\ge`) to avoid potential encoding problems.
* I suspect that the comma in the middle of your mathematics is actually a comma that is part of the sentence, not the mathematics, so you should probably break the expression into two separate ones.
* In printed mathematics, the set `R` of real numbers is usually printed as a boldface R, so `{\bf R}` or `\mathbf{R}` is better than `R` by itself.

To I'd suggest the following instead:

```
\(A = \{\, x\in{\bg R} \mid -3 < x < 2\,\}\), \(B = \{\, x\in{\bf R} \mid x^2-4x+3 \ge 0\,\}\),
```
