### ISSUE TITLE
Rendering style error

### ISSUE THREAD

**Issue by Dandezmay** [mathjax/MathJax#1957]
Hi, I got some troubles for using mathjax.

I use the Mathjax with Hexo to build my blog, but something didn't work as I expected.

Some elements' subscript isn't displayed as an subscript, this subscript are single number like '0', but letter is not affected:
![image](https://user-images.githubusercontent.com/17449060/37994325-c7ee86d6-3243-11e8-97c6-63d488d44fc0.png)

Simultaneously, they works very well on my native Markdown Editor:
![image](https://user-images.githubusercontent.com/17449060/37994535-70a8edf2-3244-11e8-8d2f-d574609998e5.png)

By the way, This elements are all other elements' superscript(for example, 'ω_0' is an exponent of 'e' in the formula). I don't sure where did the problem come from.

This is my Mathjax's config, what should I do now?
![image](https://user-images.githubusercontent.com/17449060/37994865-68c211ee-3245-11e8-98a8-b7ebbc7ae383.png)

**Comment by dpvc** [comment]
I suspect that there is some interaction between the CSS on the page and the MathJax output.  For example, the page could have set the minimum font size, and that would prevent MathJax from making the sub-subscript as small as it should.

Is it possible to post a link to the page in question so that we can look at the actual DOM elements?

**Comment by Shiratsuyu** [comment]
Thank you for your reply.

![image](https://user-images.githubusercontent.com/17449060/38151786-4bb81ce8-3497-11e8-960f-a9fdb00dc0f4.png)

Okey, I published the article at the moment. And I checked out some syntax error in config file.

this is address of the article: [三角到指数形式的傅里叶展开推导](http://blog.matsuyoi.com/2018/03/27/exponential-fourier/).

![image](https://user-images.githubusercontent.com/17449060/38151908-b9e1518a-3497-11e8-9757-359e0e714d52.png)

And I still can't resolve the problem which the subscript don’t be rendered correctly.

![image](https://user-images.githubusercontent.com/17449060/38151616-945a69c0-3496-11e8-8ea1-a11f06e7a192.png)

I tried to change the render of mathjax, well... the SVG-render can correctly display the subscript, but HTML-CSS-render still doesn't work. Although this a solution, but the problem still exist. Isn't it?

![image](https://user-images.githubusercontent.com/17449060/38151876-9b2e59ae-3497-11e8-94ea-51fd1277df56.png)

I am not sure what trouble was happened, because I am not a professional JavaScript Developer. 

So now what should I provide for it? I mean this issue.

**Comment by Shiratsuyu** [comment]
Nearly forgot, I thought it's a font problem.

**Comment by dpvc** [comment]
Thanks for the link to the actual page.  The expression renders correctly for me in Safari, Chrome, and Firefox on Mac OS X.  

<img width="595" alt="subscript" src="https://user-images.githubusercontent.com/432782/38156275-b706cf00-344a-11e8-991c-af12b824a153.png">

What browser and OS are you using?  Can you check the browser preferences and see if there is a minimum font size specified own your browser?

**Comment by Shiratsuyu** [comment]
Amazing. I am keep using Chrome to preview the rendering effect. I didn't try other browser for this. This page is rendered correctly at Safari indeed. Although it still have some error...(those font file are all existed)

![image](https://user-images.githubusercontent.com/17449060/38159683-441ab74a-34e0-11e8-8125-4634ecb51a55.png)

emm...... I didn't expect HTML-CSS render's  behavior is not consistent at different browser.

![image](https://user-images.githubusercontent.com/17449060/38159590-39543888-34de-11e8-93b8-92d637f3d0b7.png)

I am using macOS too. I don't think operator system is the reason of this problem.

Now I realized choosing the HTML-CSS render is not a good idea. spent time for loading fonts is too long, and font file seriously affected hexo's performance. The most important is, rendering affects are inconsistent at different browser.

At last, Chrome has a option for minimum-fontsize? Why you can get a same affect form Chrome and Safari?

**Comment by dpvc** [comment]
The link you listed in your earlier message no longer works for me, so I can't investigate the problem any longer.  

> rendering affects are inconsistent at different browser.

MathJax tries hard to make the rendering the same in all browsers, but sometimes there are differences in how browsers display certain things, and so I asked what browser and OS you were using so I could try the same environment that you are using.  I am unable to produce the results from your initial screen.

> Chrome has a option for minimum-fontsize?

Yes.  Use the Chrome -> Preferences menu.  This should get you the "Settings" panel in Chrome.  Click on "customize fonts" (In the Appearance" block).  The second item should be "minimum font size".  Change that to the smallest allowed and see if that improve the situation for you.

> Why you can get a same affect form Chrome and Safari?

I don't understand the question.  If you are asking _how_ to get the same effect from both browsers, that _should_ happen automatically.  The fact that you are getting different effects suggests that your Chrome setup may be interfering with MathJax's output, such as through the minimum font size described above.
