### ISSUE TITLE
Equation/Text are hiding

### ISSUE THREAD

**Issue by dverma4u** [mathjax/MathJax#1976]
I am facing styling issue with mathJax on react Native webview.
Sometimes equation and text get hidden and did not displayed properly.
I tried changing height and width of webview but still facing the same issue.

**Comment by dpvc** [comment]
There is not enough information here to analyze your situation.  You would need to provide much more detail about what you are doing and how you are doing it.

Note, however, that this from is for posting reports about bugs in MathJax, not for asking general questions about using MathJax.  That would be better done in the [MathJax Users' Forum](https://groups.google.com/forum/?fromgroups#!forum/mathjax-users).  For your question, it might be best to ask the React Native community, since it is much more likely that that has to do with how to use React than how to use MathJax.
