### ISSUE TITLE
Stopped rendering math symbols

### ISSUE THREAD

**Issue by ovirchenko** [mathjax/MathJax#1984]
Could anyone help me?  In all my course pages LaTex math symbols stopped displaying. And instead of beautiful math equations and chem formulas I’ve got this http://prntscr.com/j8mh2r and http://prntscr.com/j97rda. What problems have I got? How to fix this?

**Comment by ovirchenko** [comment]
I suppose scripts are running. I am not seeing any errors in console. Except may be this: http://prntscr.com/j9kakj

**Comment by dpvc** [comment]
The element in your image is perfectly fine, and indicates that MathJax is loaded and running.  But the image also shows a red "x" followed by a 1, which does indicate an error message, if you had looked at the "Console" tab rather than the "Elements" tab.

I checked the website indicated in your image, and while MathJax does load, it is not being configured properly, and that is likely what is causing the problem for you.  MathJax is being loaded by the tag

```
<script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?ver=4.9.5'></script>
```
relatively early in the page, and it is a synchronous load, so it will block loading the rest of the page until MathJax.js is loaded, and run.  This script does not load a configuration file (via `?config=...`), and there is no in-line configuration at this point, so MathJax has no configuration, and will not process anything at this point.

There is a script at the end of the page 

```
<script type="text/javascript" defer src="http://biobrainster.com/wp-content/cache/autoptimize/js/autoptimize_c3da62635f2223d0ac5c8bcec308b179.js"></script>
```

that includes the lines

```
window.MathJax = {
    jax: ["input/TeX", "output/HTML-CSS"],
    extensions: ["tex2jax.js"],
    messageStyle: "none",
    showMathMenu: !1,
    showMathMenuMSIE: !1,
    TeX: {
        extensions: ["AMSmath.js", "AMSsymbols.js", "noErrors.js", "noUndefined.js"]
    }
};
```

which is a MathJax configuration, but since it is at the end of the file (and is marked `defer` in any case), this file isn't run until *after* MathJax is loaded, and so it is not available when MathJax needs it.  Moreover, the form of configuration that it uses is the one that sets the `MathJax` variable itself, which means that when it runs after MathJax is loaded, this actually *replaces* MathJax by this configuration.

So the way your site is configuring MathJax prevents it from working.  Has the content management system been updated recently?  Or reconfigured recently?  If so, whoever is in charge needs to fix the way it is being handled so that the configuration is in place *before* MathJax.js is loaded.  That could be done by having the `<script>` element that loads MathJax.js be created dynamically in the `autoptimize_c3da62635f2223d0ac5c8bcec308b179.js` file (after the configuration is set up) rather than being explicitly included at the top of the HTML file.

**Comment by ovirchenko** [comment]
Thanks a lot for the explanation. I am not sure about update. It appeared after all the pages started to lead to 404 page somehow. So I added this
`<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>`
in the .htaccess file. The problem gone but math symbols too))
So I will be trying to fix this

**Comment by dpvc** [comment]
I doubt that has anything to do with the problem.  The issue is in how MathJax is configured, not how the server is configured.  The problem that I saw was in the order and timing of the javascript files that the site loads.
