### ISSUE TITLE
\color different from LaTeX

### ISSUE THREAD

**Issue by Debenben** [mathjax/MathJax#1991]
$\color{lightgray} lightgray \color{gray} gray \color{darkgray} darkgray$

renders 

![screenshot from 2018-05-03 22-15-05](https://user-images.githubusercontent.com/35615783/39600918-8b267dfe-4f20-11e8-93e2-42563809df8b.png)

(Debian/Firefox/all rendering options e.g. on math.stackexchange)

where only the first letter gets colored and darkgray is lighter than gray. The expected result is

![screenshot from 2018-05-03 22-15-42](https://user-images.githubusercontent.com/35615783/39601030-ec66cf88-4f20-11e8-9f78-006f08382fa7.png)

(pdfLaTeX with xcolor package)

**Comment by zorkow** [comment]
This is true. To get the desired effect, you need to give the coloured text as parameters to the color command:
```LaTeX
\color{lightgray} {lightgray} \color{gray} {gray} \color{darkgray} {darkgray}
```
We might be able to achieve xcolor compatibility in the upcoming version 3.

**Comment by dpvc** [comment]
As @zorkow points out, the default definition of `\color` takes an argument rather than being a switch, as in LaTeX.  The `color` extension, however, redefines it to be LaTeX compatible.  Add

```
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: {extensions: ["color.js"]}}
});
</script>
```

to your page just **before** the script that loads `MathJax.js` itself in order to load the extension.

**Comment by Debenben** [comment]
Sorry, I did not know that \color had a different behavior without the color extension. I think it would be a good idea to make the default behavior in the upcoming version 3 either "unknown command \color" or compatible with LaTeX.

When I add the color extension there is still the minor issue of darkgray not being darker than gray:

![screenshot from 2018-05-04 16-34-12](https://user-images.githubusercontent.com/35615783/39633792-49606dbe-4fb9-11e8-997e-e9a07ad880ee.png)

I tried to fix it myself, but I couldn't find a definition of darkgray anywhere.

**Comment by dpvc** [comment]
The named colors are the 68 divps colors listed [here](https://github.com/mathjax/MathJax/blob/50c333cc695066b9d27f713035b44c9ef78ab658/unpacked/extensions/TeX/color.js#L41-L109).  If you use a color name other than these, it is interpreted as an HTML color name, and it turns out that, for HTML colors, `darkgray` is lighter than `gray`.  

Note that the color extension is based on the LaTeX color package, not xcolor, and the names `light gray`, `grey`, and `darkgray` are not defined in that package.

You can use `\definecolor` to create your own named colors if you want.

**Comment by Debenben** [comment]
Thanks again, then it is expected behavior and the confusing HTML color names are at fault.

**Comment by dpvc** [comment]
Right!
