### ISSUE TITLE
Centering in limits

### ISSUE THREAD

**Issue by cebola2** [mathjax/MathJax#1997]
Latex centers subscripts in displayed limits as, e.g.,
![imagem](https://user-images.githubusercontent.com/1136663/40277685-5087907c-5c1b-11e8-80f5-3ce1f0da1679.png)
MathJax centers subscripts in limits somewhat to the right of where they should be
![imagem](https://user-images.githubusercontent.com/1136663/40277704-b8fa153a-5c1b-11e8-82c1-cdc377823997.png)
The examples come from
https://cdi2tp.math.tecnico.ulisboa.pt/texto/7

**Comment by dpvc** [comment]
OK, I finally tracked this down.  It turns out to be a rather complex interaction between the fast preview, the assistive extensions, and some code that tries to handle special cases of MathML spacing when TeX spacing is being used.

The easiest fix for now is probably to add

```
MathJax.Hub.Register.StartupHook("mml Jax Ready", function() {
  MathJax.ElementJax.mml.mo.prototype.useMMLspacing = 0x03;
})
```

to your configuration script for MathJax.  That will disable the MathML spacing that is causing the issue.

**Comment by cebola2** [comment]
Thanks! It works perfectly. Will a more permanent fix be in version 3?

**Comment by dpvc** [comment]
The MathML spacing issue that is at the heart of the problem is handled differently in v3, and there is no fast preview, so it should not be something that will affect version 3.

**Comment by cebola2** [comment]
Great! Closing...

**Comment by dpvc** [comment]
I'm reopening the tracker.  I'd still like to fix it for v2.

**Comment by dpvc** [comment]
==> In testsuite
MathMLToDisplay/issue1997.html
