### ISSUE TITLE
Asciimath with variable name of more than one letter not rendered properly

### ISSUE THREAD

**Issue by Wrufesh** [mathjax/MathJax#2001]
let us say i have two variable:
**_unit1_** and **_unit2_**

and my equation is: unit1/unit2 then =>
it is rendered like
 _unit (1/u) nit2_

How to use variable name containing more than one letter?

**Comment by zanedp** [comment]
How does one have a variable named `length` without it being rendered as <= n > h? 

Using `"length"` makes it be in roman text, appearing to be a unit of measure rather than a variable.

**Comment by dpvc** [comment]
@zanedp, it's ugly, but you could use `l{:eng:}th` to get that (the brace groups break up the `le` and `gt` that are causing the problems.  This is semantically wrong, however, so people using screen readers will not get very good results.

**Comment by zanedp** [comment]
Was this fixed? Maybe, a solution would be  requiring spaces around operators?

**Comment by dpvc** [comment]
@zanedp, this is an issue with the AsciiMath language, not with MathJax itself.  MathJax incorporates the AsciiMath processed verbatim, so we don't control how that works.  You might want to raise the issue on [their issue tracker](https://github.com/asciimath/asciimathml/issues).

> Using "length" makes it be in roman text, appearing to be a unit of measure rather than a variable.

Multi-letter variable names normally *are* typeset in upright rather than italic text.  The math italics font is not designed for mutli-letter identifiers (see the poor rendering of *office* for example).  So `"length"` actually produces the result preferred by math typesetting conventions.
