### ISSUE TITLE
First steps of using MathJax with Angular 5

### ISSUE THREAD

**Issue by dikey94** [mathjax/MathJax#2009]
Hi guys,
I have to admit the MathJax is great. Thanks!

I'm going to use MathJax with Angular 5 application.
My angular based front-end application will be sending 2 things to the back-end:
- svg image with rendered input formula
- input text

What's the preferable way to install the lib?

I'd appreciate any support.
Thanks.

**Comment by dpvc** [comment]
I'm afraid I don't know Angular, but a quick google search found [this](https://colcarroll.github.io/ngMathJax/) example.  Perhaps that helps.

In any case, it would probably be better to ask your question in the [MathJax Users Forum](https://groups.google.com/forum/?fromgroups#!forum/mathjax-users), rather than here.  This is the issue tracker for MathJax bugs, not a general question forum.

**Comment by EnKrypt** [comment]
@dpvc That's for angularjs / Angular 1

There are other solutions around for Angular 2+ using Directives which is now deprecated as well.

Looks like for now, if you're using Angular 6 or 7, you've no choice but to stitch together your own solution.
