### ISSUE TITLE
[SVG output] class attribute is lost when href attribute is present

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#2030]
Minimal example below.

```
<math>
  <mrow class="value" href="url">
    <mtext>no class!</mtext>
</mrow> 
 <mrow class="value">
    <mtext>yes class!</mtext>
  </mrow>
</math>
```

**Comment by pkra** [comment]
I noticed that the other outputs will add the class to a descendant. Maybe that's related.

(FWIW it does not seem ideal to me to have the class somewhere other than the `<a>`, even more so in this case compared to https://github.com/mathjax/MathJax/issues/1600#issuecomment-242103452.)

**Comment by pkra** [comment]
D'oh. Of course it's exactly the same way an the class appears attached to the group.

So this is just expected behavior.

Sorry for the noise.

**Comment by pkra** [comment]
Hm... This is a problem when you want to style the resulting SVG with CSS. As opposed to the CSS outputs, the most practical styling will use the rect -- but there's no way to do so when you can only put a class name on the next sibling.

**Comment by pkra** [comment]
Looking at SVGsaveData

https://github.com/mathjax/MathJax/blob/50c333cc695066b9d27f713035b44c9ef78ab658/unpacked/jax/output/SVG/jax.js#L1159-L1171

It seems to me if `SVGaddHref` was called at the end, the result might be more intuitive. Maybe something for v3 (which I haven't looked at yet).

**Comment by dpvc** [comment]
> the class appears attached to the group.

I was going to point that out, but you found it yourself, so I didn't have to.

The SVG output is inconsistent with the other two output jax in that it currently puts the class that identifies the MathML element type onto the surrounding `<a>` element, rather than on the same element that gets the user-provided classes.  I was going to suggest that that might be what needs to be changed.  Your suggestion about moving line 1159 would do that, I think, so that might be the best approach.

> As opposed to the CSS outputs, the most practical styling will use the `rect`

The `rect` is there as a target for the mouse events (since otherwise you would have to click on the "ink" of one of the glyphs), not for CSS styling.  Since this `rect` only appears for elements with `href` attributes, using it for styling would make for inconsistent results.  That is, if you had

    <mi class="bgcolor" href="...">Background</mi><mi class="bicolor">No Background</mi>

and used

    <style>
      .bgcolor rect {fill: red}
    </style>

only the first one would get the background color (since there is no `rect` in the second one to be styled).

I think moving the `mjx-svg-mi` class to the `<g>` element where the user's classes go, as your suggestion of moving `SVGaddHref()` would do, is the better solution.

**Comment by pkra** [comment]
> Since this rect only appears for elements with href attributes, using it for styling would make for inconsistent results.

Sure but that was the scope of my statement -- I was only interested in styling links.

> I think moving the mjx-svg-mi class to the <g> element where the user's classes go

Either way there's no way to specify the class of the actual `<a>`; for me, that's a serious problem (enough of a problem to write my own extension) but arguably just another design flaw of MathML.

**Comment by pkra** [comment]
> While your needs may be limited, they set a precedent that we can't support more widely.

Right. I closed the issue because I no longer meant to suggest a change here.

**Comment by dpvc** [comment]
OK, thanks.  Since you added more comments, I wasn't sure.  I guess they were for v3.
