### ISSUE TITLE
tex2jax: "}" as the end of math mode

### ISSUE THREAD

**Issue by sstenchlak** [mathjax/MathJax#2034]
It doesn't work when you use "}" as the end of math mode if the equation contains braces. E.g.

`tex2jax: {
        inlineMath: [ ["\\equation{","}"] ]
}`
`some text \equation{\frac{1}{n} > 0} some text`

I'm guessing the problem is that https://github.com/mathjax/MathJax/blob/419b0a6eee7eefc0f85e47f7d4f8227ec28b8e57/unpacked/extensions/tex2jax.js#L239 is not evaluated when `search.end === "}"`.

**Comment by dpvc** [comment]
You are correct, the search's paren count (`search.pcount`) isn't getting decremented when the end delimiter is `}`.  A solution would be to remove the `else` on the previous line

https://github.com/mathjax/MathJax/blob/419b0a6eee7eefc0f85e47f7d4f8227ec28b8e57/unpacked/extensions/tex2jax.js#L238

so that the paren count is handled even when the end delimiter is a paren.

You can patch this in your own pages by putting

```
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  tex2jax: { inlineMath: [ ["\\equation{","}"] ] }
});
MathJax.Hub.Register.LoadHook("[MathJax]/extensions/tex2jax.js", function () {
  MathJax.Extension.tex2jax.endMatch = function (match, element) {
    var search = this.search;
    if (match[0] === search.end) {
      if (!search.close || search.pcount === 0) {
        search.close = element;
        search.cpos = this.pattern.lastIndex;
        search.clen = (search.isBeginEnd ? 0 : match[0].length);
      }
      if (search.pcount === 0) {
        search.matched = true;
        element = this.encloseMath(element);
        this.switchPattern(this.start);
      }
    }
    if (match[0] === "{") search.pcount++;
    else if (match[0] === "}" && search.pcount) search.pcount--;
    return element;
  };
});
</script>
```

in your pages just **before** the script that loads `MathJax.js` itself.

**Comment by dpvc** [comment]
In testsuite:

LaTeXToMathML/issue2034.html
