### ISSUE TITLE
Why do not support footnotesize

### ISSUE THREAD

**Issue by jxgu1016** [mathjax/MathJax#2039]
$\footnotesize{hello}$ does not work well as others like $\tiny{hello}$, $\huge{hello}$.
Is that a bug or not?

**Comment by dpvc** [comment]
Since footnotes are part of the text apparatus of the document, and MathJax only handles math notation, `\footnotesize` didn't fit into its mission.  Any footnotes on the page will be formatted by the surrounding HTML, and MathJax doesn't have any way to determine what size might be used for footnotes.  So it doesn't really make sense to implement `\footnotesize` in MathJax.

You can, of course, define your own version of `\footnotesize`.  E.g., you could use `\let\footnotesize=\small` and then for the rest of the page, `\footnotesize` would be defined to produce smaller letters.  You can add this to your page configuration using

```
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: {Macros: {footnotsize: ["\\small"]}}
});
</script>
```
just *before* the script that loads MathJax.js itself.

If the size you want doesn't match any of the pre-defined sizes, you could use

```
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: {Augment: {Definitions: {macros: {footnotesize: ['SetSize', .9]}}  // 90% of normal
});
</script>
```

instead.

**Comment by jxgu1016** [comment]
thx
