### ISSUE TITLE
can't escape html tag

### ISSUE THREAD

**Issue by DayuanJiang** [mathjax/MathJax#2044]
- the code: `$a^{<t>}$ is the hidden state at time step $t$.`
- result: $a^{}isthehiddenstateattimestept$.
- test page: [http://www.jiang.jp/blog/test/](http://www.jiang.jp/blog/test/)  

It seems <t> inside $...$ is treated as a html tag.

**Comment by dpvc** [comment]
> It seems inside $...$ is treated as a html tag.

Yes, that is correct.  Since the browser parses the page as HTML long before MathJax runs, the `<t>` is parsed as a tag before MathJax sees it.  If you are using `<` and `>` in your math, you need to either use the HTML entities for them, as in `$a^{&lt;t&gt;}$`, or the macros `\lt` and `\gt`, as in `$a^{\lt t\gt}$`.  Spaces can sometimes prevent the parsing as tags, as in `$a^{< t >}$`.  See the [documentation](http://docs.mathjax.org/en/latest/tex.html#tex-and-latex-in-html-documents) for more details. 

In any case, I think you really want `$a^{\langle t\rangle}$`, since `\langle` and `\rangle` are delimiters, while `<` and `>` are relations and both will be too wide, and will get the wrong spacing in text and display styles (i.e., outside of super- and subscripts).
