### ISSUE TITLE
"\\" do not render a newline.

### ISSUE THREAD

**Issue by DayuanJiang** [mathjax/MathJax#2045]
`$$ a \\ b $$` should render

a
b

But I only get 

a b 

in my blog. 
And this is my test page [http://www.jiang.jp/blog/test/](http://www.jiang.jp/blog/test/) .
I use python-markdown to convert the code to html. Dose this the reason "`\\`" do not work?
I know this issue maybe not related to mathjax but I have googled for near 1 hour and didn't find anyone who had the same problem.

**Comment by dpvc** [comment]
Markdown uses the backslash (`\`) as an escape character to prevent a special character from having its usual meaning, and `\\` means include a literal `\`.  This means your `\\` is being turned into a `\` by markdown, so the HTML page that MathJax processes only has a single `\`, not a double one, and that does not produce a new line.

You will need to double all the backslashes (so use `\\\\` rather than `\\`), and will probably have to use `\_` instead of `_`, if your flavor of Markdown uses `_` to indicate italics.

See the MathJax [documentation](http://docs.mathjax.org/en/latest/tex.html#tex-and-latex-in-html-documents) for more details about using MathJax in HTML and Markdown documents.
