### ISSUE TITLE
[STIX-web] hat and italic correction in 2.7.5

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#2050]
Hats seem to have lost their italic correction in 2.7.5 (I'm guessing after #1923).

Example: $\hat{f}$.

**Comment by dpvc** [comment]
I think this is actually the skew values that are at issue, but yes, it is probably due to the change to using the Math Alphabets rather than the usual ASCII alphabet.

**Comment by pkra** [comment]
> I think this is actually the skew values that are at issue

Ah, my lack of foo is showing. Thanks for giving it a quick check!

**Comment by dpvc** [comment]
It turns out we are both right.  The italic correction is  not actually stored in the MathJax fonts (in fact, italic correction is the wrong word for it, since that is about spacing used to correct the distance between two adjacent letters, and depends on both the letters).  Instead, MathJax uses the difference between the right-bearing and the width of the glyph as a surrogate for the italic slant of the character.  This is not perfect, but is generally good enough.

Because the metrics for the main alphabet (the text italic characters that were used prior to 2.7.5) are different from the math italic characters (now being used), that does change the italic correction values being used, and that is what is causing the difference in placement of the accents.  But because this is not a separate value that can be changed (it is derived from other bounding box data), that can't be used to correct it, here.  

Instead, TeX provides a "skew" value to correct accent positions on a character-by-character basis, and MathJax does store these in the fonts.  It turns out that the STIX fonts don't include any skew values (not for either alphabetic position), so the italic correction was doing the whole job in the past.  It would be possible to determine skew values for the math italic characters and add them to the fonts to improve the positioning.  They could probably be computed automatically from the difference in the italic correction values for the two alphabets.

The italic correction was always a hack, and probably needs to be re-worked.  One possible solution would be to use the italic slant for the font (which should be a common value for all characters in the font), together with the height of the glyph to determine the italic offset of the accent.  That would make the "fake" italic correction unnecessary, and could reduce the need for skew values.  It would be worth a try.

**Comment by pkra** [comment]
Thanks for the background, Davide.

**Comment by dpvc** [comment]
I've added skew values for italic and bold-italic characters in the STIX Math Alphabet block.  I ended up doing these by hand, as there were no skew values to work from, and I could not come up with a good automated approach.  The other character sets could use skew values as well, but that will need to wait until the font redo this summer.

**Comment by dpvc** [comment]
In testsuite:

MathMLToDisplay/Presentation/ScriptsAndLimits/issue2050.html
