### ISSUE TITLE
[SVG] big delimiters spacing in 2.7.5

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#2052]
Spacing around an equality has changed in 2.7.5 when using STIX-web fonts.

E.g.,  $$\|xxx\|=\Big \|xxx\Big \|$$ has noticeably less space to the right of the equality sign.

Likely another consequence of #1923; is this expected?

**Comment by dpvc** [comment]
It is not due to #1923, as it only affects SVG, and it affects all the fonts.

It turns out that it is [this commit](https://github.com/mathjax/MathJax/pull/2024/files), but I haven't looked into why it is having that effect.

**Comment by pkra** [comment]
Thanks for looking into it!

**Comment by dpvc** [comment]
This turns out to be caused by a bug in the handling of `mstyle` when it contains a stretchy operator.  The spacing (and background color, etc) was added before the stretching was performed, and was lost when the stretched output was used to replace the original unstretched version.  I have made a PR to fix the issue.

**Comment by dpvc** [comment]
In testsuite:

LaTeXToMathML/delimiters/issue2052.html
