### ISSUE TITLE
MathJax printer friendly version

### ISSUE THREAD

**Issue by gingerYD** [mathjax/MathJax#2057]
I try to convert a page with MathJax formulas to a printer-friendly page. In the print version, the formulas are being showed as plain text (without latex rendering). Do I have to do some additional configuration to MathJax work perfectly in print version?

I test MathJax sample website https://www.mathjax.org/#samples using this website https://www.printfriendly.com/, and get the same result.

Is MathJax currently not compatible with printer-friendly feature?

**Comment by dpvc** [comment]
MathJax is a javascript library that needs to run in the browser in order to typeset the mathematics in the page.  It appears that printerfriendly.com removes scripts from the page, and so that prevents MathJax from running.  So I guess the answer is yes, MathJax is not compatible with the printerfriendly web service.

Davide
