### ISSUE TITLE
Issue on equation overline. 

### ISSUE THREAD

**Issue by varunkn07** [mathjax/MathJax#2064]
I created an equation using MS word.
![overline issue word](https://user-images.githubusercontent.com/20451860/46457541-53ed8480-c7d0-11e8-8438-866a4471615f.JPG)
The overline looks good here but when we use it in our content using mathjax, the overline is not stretching. 
![overline issue](https://user-images.githubusercontent.com/20451860/46457976-d88cd280-c7d1-11e8-8fe7-bb9a9984acce.JPG)

The issue is showing in all browsers(checked in chrome and firefox). The overline should be stretched. i think there is an issue with mathjax render.

**Comment by dpvc** [comment]
Can you provide the MathML that is being generated?  Is is not clear what character is being used for the overline, or what attributes may be in use for the MathML elements involved.  There are a number of factors that control how accents are handed, and I can't tell which might need to be changed without seeing the MathML that you are producing.

For example:

```
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mover>
    <mrow>
      <mi>A</mi>
      <mo>+</mo>
      <mi>B</mi>
    </mrow>
    <mo>&#x00AF;</mo>
  </mover>
</math>
```

produces the result you are looking for.

**Comment by dpvc** [comment]
Note that what you have provided is the MathJax HTML output, not the MathML input.  What I was looking for was your original format before MathJax typesets it.

In any case, it looks like the character that is being used for the overline is a minus sign (or perhaps a hyphen -- I can't tell without the original input format).  Whether a character stretches or not by default is specified in the [MathML operator dictionary](https://www.w3.org/TR/MathML3/appendixc.html), and neither the hyphen-minus (U+002D) nor the minus sign (U+2212) are listed as stretchy in the operator dictionary.  So MathJax will not stretch these by default.  You would need to specify `stretchy="true"` explicitly on the `<mo>` in order for MathJax to stretch that character.  E.g., 

```
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mover>
    <mrow>
      <mi>A</mi>
      <mo>+</mo>
      <mi>B</mi>
    </mrow>
    <mo stretchy="true">-</mo>
  </mover>
</math>
```

would produce the result you are looking for.  Adding `accent="true"` would also be a good idea.

In any case, this is not a bug.  It is the correct behavior for the MathML that (it appears) you are using.  If you can provide the actual MathML, not the HTML output of MathJax, we can confirm that.  One way would be to use the contextual menu (right-click or command-click) on the MathJax typeset expression and use the "Show Math As -> Original MathML" option to get the underlying MathML input.

**Comment by varunkn07** [comment]
This is the MathML,
`<mml:math xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math">
	<mml:mover accent="true">
		<mml:mrow>
			<mml:mi>A</mml:mi>
			<mml:mo>+</mml:mo>
			<mml:mi>B</mml:mi>
		</mml:mrow>
		<mml:mo>-</mml:mo>
	</mml:mover>
	<mml:mo>=</mml:mo>
	<mml:mi> </mml:mi>
	<mml:mover accent="true">
		<mml:mrow>
			<mml:mi>A</mml:mi>
		</mml:mrow>
		<mml:mo>-</mml:mo>
	</mml:mover>
	<mml:mo>.</mml:mo>
	<mml:mi> </mml:mi>
	<mml:mover accent="true">
		<mml:mrow>
			<mml:mi>B</mml:mi>
		</mml:mrow>
		<mml:mo>-</mml:mo>
	</mml:mover>
</mml:math>`

 Client copies the equations from MS Word. The input doesn't contain any 'stretchy' attribute. So we need to add 'stretchy="true"' to the MathML every time when we copy equation from the MS Word.
I think that would be difficult. Because our content contains huge collection of equations and adding 'stretchy="true"' to all the <mo> may cause other issues. Can you provide a solution ?

**Comment by dpvc** [comment]
It is unfortunate that Word uses a minus sign for the overline, since that is the wrong character for it, and it doesn't stretchy by default.  It is also unfortunate that their display is non-standard in stretching the minus (though they are allowed to do that since the operator dictionary in Appendix C of the MathML specification is non-normative).

If you are not willing to adjust the MathML to conform to the MathML specification's operator dictionary, there are a couple of alternatives you could try.  One would be to use a post-filter on the MathML input to looks for `<mover>` or `<munderover>` elements with `<mo>-</mo>` in the over position and add the `stretchy="true"` at that point.  This has the advantage of producing better output in the "Show Math As -> MathML" menu item, but has the disadvantage of requiring more processing (as every expression must be scanned).

Alternatively, you could modify the MathJax operator dictionary to make the minus sign stretchy by default.  This has the advantage of being more efficient, but the disadvantage of treating the MathML in a non-standard way (like Word is doing).  To do this, add

```
<script type="text/x-mathjax-config">
MathJax.Hub.Register.StartupHook("mml Jax Ready", function () {
    MathJax.ElementJax.mml.mo.prototype.OPTABLE.infix['-'][3] = {stretchy: true};
});
</script>
```

to your page just **before** the script that loads `MathJax.js` itself.  That will make the minus sign stretchy by default.

**Comment by kavibvaidya** [comment]
If someone is interested,  the above solution no longer seems to be working. The issue is that there is another renderer that is set to default. To solve it, use the following in the hub.config:

`jax: ["input/TeX", "output/HTML-CSS"],`

so the overall code should be in the lines of:

`MathJax.Hub.Config({
         jax: ["input/TeX", "output/HTML-CSS"],
        tex2jax: {inlineMath: [["$","$"],["\\(","\\)"]],
                skipTags: ["ul", "ol", "li"],
                processEscapes: true,
            }
      });`

In the javascript region.

**Comment by dpvc** [comment]
@kavibvaidya, nothing has changed in MathJax since the solution above was posted, so if it is not working for you, there may be something wrong with your configuration.  The changes you suggest will not resolve the issue (without the original solution), and the full configuration you give is inappropriate for most uses (in particular, the `skipTags` value is not something that most people would want to use).

If you want to post a link to a page the exhibits the problem, where you have tried the solution I posted above, we can see if we can figure out what is happening for you.

**Comment by kavibvaidya** [comment]
@dpvc  The link to the page is [here](http://docs.mathjax.org/en/latest/configuration.html) here, I looked at this example 
![image](https://user-images.githubusercontent.com/33428632/48974086-c9244b80-f002-11e8-9bdb-758eb5647097.png)

Here I have noticed that we can define an output format. Then I checked my output type and it was "preview HTML", which is the root of the issue. 

I have tried the solution that you have mentioned, but that did not work. I removed that script (to avoid unknown side effects) and then tried this and it worked. One thing that may cause this is that I have not used CDN, and I have a local copy. Basically the default is `stretchy:false` is in "preview HTML" and `stretchy:true` is "HTML-CSS"

**Comment by dpvc** [comment]
If you used this configuration and are getting the "Preview HTML" renderer, then you have probably changed the renderer using the MathJax contextual menu.  That is a personal change, not one to the site, so it only affects you.  Others visiting the site will get the HTML-CSS output that is specified (unless they also change it using the menu).

You are right that PreviewHTML output will not handle the overline, as PreviewHTML doesn't support *any* horizontal stretching; it is not intended to be used as the final output form (thus the "Preview" in its name).  Your claim that "the above solution no longer seems to be working" is incorrect; it is not working for you because you have changed to a renderer in which horizontal stretching doesn't work at all.  It has nothing to do with the solution above and whether it is working in the output renderers for which it was intended.

Also, I didn't ask for a pointer to the documentation page, but to your own page that contains the math where the overline isn't stretching.  That way, I could look at the actual code that is being used, and see the rest of the context of the page, which might also be affecting it.

**Comment by kavibvaidya** [comment]
No I did not use this configuration when I got the "Preview HTML" renderer. **I fixed the issue with this configuration.** My page uses user input to render the math into the format that they want, so I am unsure how I can give that to you. But rest assured, this is the only configuration that I used. The only other time I use mathjax is when I compile the user input using `MathJax.Hub.Queue(["Typeset",MathJax.Hub,newtext])` where newtext is a new DOM object that I would be appending.  Also, I have never changed the renderer before this, so I think the default is "Preview HTML".

Also now that we know that mathjax has not been changed, I can edit my post saying that this could be an alternative fix. Will that be fine?

**Comment by dpvc** [comment]
> I can edit my post saying that this could be an alternative fix.

This is not an alternative fix.  It is not a fix to the original poster's issue *at all*.  It may be a "fix" to your having used PreviewHTML originally, but that is not the original poster's issue.  That issue had to do with whether the minus sign is stretchy by default or not.  That is, the original issue reported here was about whether

```
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mover>
    <mrow>
      <mi>A</mi>
      <mo>+</mo>
      <mi>B</mi>
    </mrow>
    <mo>-</mo>
  </mover>
</math>
```

will have the minus sign stretched over the `A + B` or not.  Your configuration will not cause this to be stretchy; indeed, your configuration will not process this at all, since the example is MathML but your configuration will only process mathematics in TeX format.  It would be very difficult to produce the situation reported by the original poster using TeX input, so the problem does not occur for users of the TeX input format.  So your "solution" is unrelated to the actual issue at hand (it can't even be used to try out the poster's example.)

None of MathJax's output renderers will stretch the minus sign by default because the operator dictionary that is used to determine the default stretchability of operators does not list the minus sign as stretchable.  That has nothing to do with which output renderer is used, and switching from PreviewHTML to HTML-CSS doesn't change that.  The only solution to making the minus sign stretchable by default is to modify the operator table, as in my response above.  Your configuration doesn't do that, so will not solve the original poster's problem.

> I have never changed the renderer before this, so I think the default is "Preview HTML".

This is not the case.  One usually loads a configuration file by adding `?config=[config-file-name]` after `MathJax.js` in the script tag that loads MathJax (you don't list the script tag that you are using, so we can't tell if you have done that or not).  The renderer used by MathJax will be determined by the configuration file you load (e.g., `?config=TeX-AMS_SVG` will load the SVG output renderer).  None of the predefined configuration files use PreviewHMTL as their final rendering (they do use it temporarily as a quick intermediate rendering, which is replaced later by a more careful rendering produced by one of the other output renderers).

If you don't load one of these pre-defined configuration files, then your other option is to use `MathJax.Hub.Config()` to configure MathJax (as in your example), in which case you specify the input and output formats; there is no default for these, so it will be whatever you explicitly specify.  If you don't specify an input and output format, then no math will be processed.

If you ended up with PreviewHTML as the final format on your page, then either you configured it to be that yourself, or you changed the renderer by using the MathJax contextual menu, or something has gone wrong and the final format is not being produced.  That could be due to a configuration issue, or some other problem.  But without access to the page where it is happening, we can't tell what that might be.  

> My page uses user input to render the math into the format that they want, so I am unsure how I can give that to you.

All I wanted was the URL for the page.  There must be some URL for the page in order for your users to be able to access it, so I was just asking for that.  I was going to look into why your original configuration (which you never provided) might have been causing a problem, but that is unlikely to happen at this point.

**Comment by kavibvaidya** [comment]
@dpvc  I see. All I wanted to do was to point people in the right direction. Should I make another issue for that? Or like a note so that it is easier for people to view it online? 

For reference, I was using `{% static 'MathJax/MathJax.js' %}?config=TeX-MML-AM_CHTML` in django for importing the file. I am new to developing, so I have not figured out how to deploy websites yet.  I think this is the one that is mentioned in the documentation. However, I have tunneled my localhost to annotex.net, which you can access if my laptop is available to take requests. Also, please note that I have not used stretchy:true anywhere on the website, but $\overline{A+B}$ still works.

**Comment by dpvc** [comment]
> Should I make another issue for that?

No, I think there is sufficient discussion here.

> please note that I have not used stretchy:true anywhere on the website, but `$\overline{A+B}$` still works.

As I said above, the issue in this thread is about using a minus sign for the overline.  The TeX `\overline` macro does not use a minus sign for the overline, so whether `\overline` works or not is not the issue here.  Again, as I mentioned above, you will not be able to produce the problematic MathML from within TeX (without using some of MathJax's TeX extensions).  So what happens with TeX input is unrelated to the issue that is the subject of this issue tracker.  The fact that PreviewHTML does not display *any* horizontal stretchy characters (which seems to be the problem you are dealing with) is a separate issue, but not one that needs to be reported, as that is one of the limitations of the PreviewHTML output.

**Comment by miloush** [comment]
> It is unfortunate that Word uses a minus sign for the overline, since that is the wrong character for it

That is not exactly true. Word has two "overline" characters, one is called _bar_ and it is under _Accents_, the other one is called _overbar_ and it is under _Overbars and Underbars_. Natively it uses 0305 for _bar_ and 00AF for _overbar_. In MathML, it uses 002D for _bar_ with `accent="true"`, while it uses 00AF for _overbar_ with `accent="false"`. In LaTeX, it uses `\bar` for _bar_ and `\overline` for _overbar_.

They are not equivalent, however. Apart from different thickness, more importantly when used on adjoining characters, the former overline does not join, while the latter does:

<img src="https://github.com/user-attachments/assets/ab6a16dc-122a-4b55-8b48-bc3f0e24f909" />

<details>
<summary>MathML</summary>
<content>
<code>&lt;math xmlns="http://www.w3.org/1998/Math/MathML"&gt;
  &lt;mover accent="true"&gt;
    &lt;mrow&gt;
      &lt;mn&gt;123&lt;/mn&gt;
    &lt;/mrow&gt;
    &lt;mo&gt;-&lt;/mo&gt;
  &lt;/mover&gt;
  &lt;mi&gt; &lt;/mi&gt;
  &lt;mover accent="true"&gt;
    &lt;mrow&gt;
      &lt;mn&gt;1&lt;/mn&gt;
    &lt;/mrow&gt;
    &lt;mo&gt;-&lt;/mo&gt;
  &lt;/mover&gt;
  &lt;mover accent="true"&gt;
    &lt;mrow&gt;
      &lt;mn&gt;2&lt;/mn&gt;
    &lt;/mrow&gt;
    &lt;mo&gt;-&lt;/mo&gt;
  &lt;/mover&gt;
  &lt;mover accent="true"&gt;
    &lt;mrow&gt;
      &lt;mn&gt;3&lt;/mn&gt;
    &lt;/mrow&gt;
    &lt;mo&gt;-&lt;/mo&gt;
  &lt;/mover&gt;
  &lt;mi&gt; &lt;/mi&gt;
  &lt;mover accent="false"&gt;
    &lt;mrow&gt;
      &lt;mn&gt;123&lt;/mn&gt;
    &lt;/mrow&gt;
    &lt;mo&gt;¯&lt;/mo&gt;
  &lt;/mover&gt;
  &lt;mi&gt; &lt;/mi&gt;
  &lt;mover accent="false"&gt;
    &lt;mrow&gt;
      &lt;mn&gt;1&lt;/mn&gt;
    &lt;/mrow&gt;
    &lt;mo&gt;¯&lt;/mo&gt;
  &lt;/mover&gt;
  &lt;mover accent="false"&gt;
    &lt;mrow&gt;
      &lt;mn&gt;2&lt;/mn&gt;
    &lt;/mrow&gt;
    &lt;mo&gt;¯&lt;/mo&gt;
  &lt;/mover&gt;
  &lt;mover accent="false"&gt;
    &lt;mrow&gt;
      &lt;mn&gt;3&lt;/mn&gt;
    &lt;/mrow&gt;
    &lt;mo&gt;¯&lt;/mo&gt;
  &lt;/mover&gt;
&lt;/math&gt;
</code>
</content>
</details>

I am not disputing whether minus should be stretchy or not by default, but suggesting that 00AF is the "correct" character or that it corresponds to `\overline` does not seem to be always the case.

**Comment by dpvc** [comment]
@miloush, I stand by my claim that using a hyphen-minus (U+002D) for an accent is a bad choice.  As you point out, this is not what it uses natively (though I don't know what "natively" actually refers to).  Their own rendering (that you show in your image) is likely not based on their MathML output, but on their own internal structure that is rendered using their own approach, and translated into "equivalent" MathML or LaTeX when those forms are requested.  I'm fairly certain that your image does *not* show minus signs in the first two of your four examples.

I agree that the LaTeX translations to `\bar` and `\overline` are appropriate ones.  Note, however, that in LaTeX, `\bar` is not stretchy, so `\bar{123}` would not produce your first example, but rather 

<img width="246" height="160" alt="Image" src="https://github.com/user-attachments/assets/b9cb395c-c092-4bb4-b30a-2b2c2ca5ed8e" />

so their output in MS Word and in LaTeX are already not consistent.  The LaTeX `\bar` generates an accent that would usually be called a "macron" accent; indeed the [unicode-math symbols list](https://texdoc.org/serve/unimath-symbols.pdf/0) (section 7) indicates `\bar` is a macron, and suggests U+0304 (combining macron) is the appropriate character for this.  The choice of U+0305 (combining overline) is a less-desirable choice since there is a specific macron accent, particularly in light of your desire that it show a separation when used on adjacent numbers (U+0305 is often wider than U+0304 and may cause adjacent versions to touch).

When used in MathML, the accent character will appear alone within an `<mo>` tag, and it is awkward to use a combining character without a character to combine with, so I prefer to use the non-combining forms of the combining accents.  For U+0305, the non-combining form is U+00AF (macron), which is why I say that is the "correct" character for that situation.

As for `\overline`, LaTeX itself does not use a character for this, as it uses rules to construct the overline, and so the unicode-math symbol table does not list `\overline`.  It is not treated as an accent by TeX, which may be why it is marked as `accent="false"` by Word, though I think that is also a poor choice in this case.  By marking it `accent="false"`, that means not just that there should be a bit more space between the base and the overline, but also that the overline will be rendered with one higher `scriptlevel` (like `\scriptstyle` in TeX).  That the character will be in a smaller font, so may very well be *thinner* when rendered than one marked as `accent="true"`.  The output you should obviously doesn't do that, again suggesting that the Word output is not based on its MathML representation.

Why own feeling is that the overline should use `accent="true"` and an overline character like U+0305, but a non-combining version.  The natural one would be U+203E (overline), whereas U+00AF would be OK but less appropriate.  MathJax actually uses U+2015 (horizontal bar) for both `\overline` and `\underline` to guarantee a consistent look between the two.

Your suggestion that the `\bar` should leave a gap when used on successive bases while `\overline` should not is reasonable, but it has less to do with the character used than with whether that character is stretchy or not.  The actual size of the characters involved depends on the font, but you are more likely to get the gap using U+00AF than U+0305 for `\bar`, since the macron is more likely to be smaller than the overline accent.  The use of a hyphen-dash might lead to them touching in successive uses, as the hyphen might be longer than the macron accent, for example.

So I would say that *bar* should produce `<mo accent="true" stretchy="false">&#x00AF;</mo>` while *overline* should produce `<mo accent="true" stretchy="true">&#x203E;</mo>` (or perhaps `&#x00AF;`).  Whether the latter should be thicker or not will depend on the font (but using `accent="false"` will make it more likely to be thinner).

One of the reasons that the hyphen-minus doesn't work well for *bar* in MathJax is that, in TeX fonts, the height and depth for the minus is set to be the same as that of a plus (so that when it is used in superscripts, like `Na^-` and `Cl^+`) it will be positioned properly.  So when used as an accent, the minus sign ends up being positioned too high because of its unexpected depth.  That is part of what the original poster is seeing with the raised bar.

Finally, MathJax has the ability to remap accent characters, so it would be possible to configure it to map the hyphen-minus to U+00AF when used as an accent.  That would allow the MS Word generated MathML to display more like how it does in Word, since U+00AF doesn't have extra depth and is stretchy by default (though the overline version will be thinner since it has `accent="false"`):

<img width="408" height="94" alt="Image" src="https://github.com/user-attachments/assets/5199bc9f-06cd-4c69-a0ce-216d5bed91ec" />
