### ISSUE TITLE
The Mathjax web display on Mobile phone (Android) is shrinking

### ISSUE THREAD

**Issue by dirkncl** [mathjax/MathJax#2067]
The Mathjax web display on Mobile phone (Android) is shrinking, is there a solution? ...
---------------------------------------------------------------------------------------
https://rawgit.com/dirkncl/Mathematics/master/LatexMathjaxGraph.html
I tried to assemble the latexmathjax.js latex document from Peter Jipsen combining with Peter Jipsen asciisvg plus 2d and 3d graphics from Astex (Mike Ziggler).
This experiment can prove that actually we can make Document Latex itself with Mathjax as the main engine.
The main experiment actually originated from Peter Jipsen, but he did not mix it in one package. Hopefully Peter Jipsen reads this and can develop it into "Jiptex Document" or "JipMJTex Document" with a better and more complete graphic design.

**Comment by dpvc** [comment]
Sometimes mobile devices scale the page after MathJax has measured the font sizes, and so it can get the scaling wrong.  The first thing you should try is using the [viewport meta](http://docs.mathjax.org/en/latest/output.html#viewport-meta-tag) tag described in the MathJax documentation.  Otherwise, you might try the [MatchWebFonts](http://docs.mathjax.org/en/latest/options/other/MatchWebFonts.html) extension, which tries to adjust to changing font sizes due to web fonts (but might catch this situation as well).  If all else fails, try setting `matchFontHeight` to `false` in the configuration block for your output format.  E.g., 

```
MathJax.Hub.Config({
  'HTML-CSS': {
    matchFontHeight: false
  }
});
```

**Comment by dirkncl** [comment]
Thank you Mathjax for the solution.
I tried the first option, -- content = "width = device-width, initial-scale = 1" --
the solution is solved but still I enter
     / * *********** * /
     "'HTML-CSS': {\ n" +
     "matchFontHeight: false \ n" +
     "}, \ n" +
     / * *********** * /
as a complement.

Dirk L. Nicolaas.
from Indonesia.

**Comment by dpvc** [comment]
OK, glad it worked.
