### ISSUE TITLE
accessibility explorer disables automatic linebreaks

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#2073]
When the accessibility explorer is activated, the re-rendered expression loses automatic linebreaks. When the explorer and collapse are disabled, automatic linebreaks work again. I noticed this for the CommonHTML output but I suspect it holds for all outputs.

**Comment by dpvc** [comment]
I am not able to reproduce this.  In my example, line breaking, explorer, and collapsing all seem to work together for me with CHTML.  Can you provide an example?

It turns out that line breaking causes problems for the maction elements (the clicking isn't properly handled), and the walker highlighting doesn't take broken lines into account, but the line breaking certainly is occurring while the other two extensions are in play.

Of course, the maction elements doe cause additional nesting, and the semantic analysis can as well, so perhaps that is making some line breaks less desirable?

**Comment by pkra** [comment]
Does this work for you? https://jsbin.com/fogamejufo/edit?html,output

**Comment by dpvc** [comment]
No, but putting an extra `\\` at the end of the `H_5` line does cause the line breaks to occur.  So there is something funky going on, and it has to do with the content of the expression.  For example, `\[x\\y\\x\]` works fine, but `\[x,\\y,\\z\]` doesn't.

**Comment by dpvc** [comment]
It seems to be connected to the mactions, as `\[x\\y\\z\]` doesn't produce one, while `\[x,\\y,\\z\]` does.  But `\[x,\\y,\\z\\\]` also does, so that is weird.  The latter has an element *after* the maction and the former doesn't, so that seems to be related.  But if I paste the MathML output from the one that doesn't break into the interactive MathML lab, it does break.  So something strange is going on somewhere.

**Comment by pkra** [comment]
Thanks for looking into it. It's not a real issue for me, I just thought I should report it.
