### ISSUE TITLE
display error in an iframe

### ISSUE THREAD

**Issue by CaiHandsome** [mathjax/MathJax#2079]
Issure summury:

I met a display question,when I use mathjax to process the DOM in iframe,the root mark was rendered in wrong.

This is my test code:

### code### 
<!DOCTYPE html>
<html>
<head>
<title>MathJax MathML Test Page</title>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<script type="text/javascript" src="../MathJax.js?config=MML_HTMLorMML-full"></script>
</head>
<body>
<p>
<div id = "test1">
</div>
<iframe id='design_frame' name='design_frame' width='100%' height='100%' border="1" >
</iframe>
<script>
var divp1 = document.getElementById("test1");
divp1.innerHTML = "<math><mrow><msqrt><mi>x</mi></msqrt></mrow></math>";

var designFra=document.getElementById("design_frame");
var designWin=designFra.contentWindow;
var designDoc=designWin.document;
 
designDoc.body.innerHTML = "<math><mrow><msqrt><mi>x</mi></msqrt></mrow></math>";

MathJax.Hub.Queue(["Typeset",MathJax.Hub,designDoc.body]);
</script>
</p>
</body>
</html>
###code### 

with the result:
![03w 2 y45 j761m1a x0](https://user-images.githubusercontent.com/40056586/48525971-e2215400-e8c0-11e8-9b26-211d62183c9a.png)

 You can see the the root mark is correct in div above, but separated in iframe below.So I think it's not font problem.

Technical details

    MathJax Version: 2.7.5
    Client OS: win10
    Browser: chrome
    Output: HTML-CSS

THANK YOU

**Comment by dpvc** [comment]
In order to run MathJax inside an iframe, you need to load MathJax.js in the iframe itself; you can't use the MathJax txt is loaded in the page containing the iframe.  One of the reasons for this is that MathJax has to insert CSS into the page, but it will have done that to the container page, not the iframe, so the iframe is missing the needed CSS.  That is why you are getting the wrong spacing and the wrong fonts in the iframe.

There are other potential issues as well with trying to use the outer MathJax in the inner iframe, but the CSS is the issue you are seeing here.

**Comment by CaiHandsome** [comment]
Thank you very much for your answer.
I tried to load mathjax in an iframe and call mathjax, the code is as follows：

			designFra=document.getElementById("design_frame");
			designWin=designFra.contentWindow;
			designDoc=designWin.document;
			var oScript= document.createElement("script"); 
			oScript.id = "oScript1"; 
			oScript.type = "text/javascript"; 
			oScript.src="../MathJax-2.7.5/MathJax.js?config=MML_HTMLorMML-full"; 
			var oTag1 = designDoc.getElementById("oScript1"); 
			if(!oTag1){ 
			designDoc.body.append(oScript); 
			}	
			var doc = $('#design_frame').contents()[0];
			var script = doc.createElement('script');
			script.text = "MathJax.Hub.Queue(['Typeset',MathJax.Hub])"
			doc.head.appendChild(script);

But the page prompts：
![p of_1n5fx w03 2 3z9o1](https://user-images.githubusercontent.com/40056586/49326792-7e6e7a80-f592-11e8-9910-2f65589f65d1.jpg)

 I don't know where the problem is.

Technical details

MathJax Version: 2.7.5
Client OS: win10
Browser: chrome
Output: HTML-CSS

Thank you very much.

**Comment by dpvc** [comment]
Without seeing the complete page, it is hard to tell what might be going wrong.

It looks like you are are using your own copy of MathJax from your server.  Here are some ideas:

* Did you install the full 2.7.5, including the fonts? 
* Are there any error messages in your browser console that might shed light on the situation?
* How about errors in the server log related to the fonts?
* Did you set the access-control settings for fonts on your server, as described [here](http://docs.mathjax.org/en/latest/installation.html#cross-domain-linking)?

If you are loading the file using a `file://` URL, that might also be the issue, since your MathJax seems to be in a higher directory, which some browsers consider to be a different origin, and so the same-origin policy may be preventing the fonts from loading in that case.

Here is a sample file that works for me.  Perhaps it can give you some ideas for your own setup.

```
<!DOCTYPE html>
<html>
<head>
<title>MathJax in iframe</title>
<script>
window.onload = function () {
  var doc = document.getElementById("design_frame").contentWindow.document;
  var config = doc.createElement("script");
  config.type = "text/x-mathjax-config";
  config.text = [
    "MathJax.Hub.Config({",
    "  tex2jax: {",
    "    inlineMath: [['$','$'], ['\\\\(','\\\\)']]",
    "  }",
    "});",
    "function Typeset() {MathJax.Hub.Queue(['Typeset', MathJax.Hub])}"
  ].join("\n");
  doc.body.append(config);
  var script = doc.createElement("script"); 
  script.src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_HTML-full"; 
  doc.body.append(script); 
};

var Update = function () {
  var text = document.getElementById('input').value;
  var win = document.getElementById("design_frame").contentWindow;
  var doc = win.document;
  doc.body.append(doc.createTextNode(text));
  win.Typeset();
}
</script>
</head>
<body>

<iframe id='design_frame' border="1" style="width:100%; height:15em"></iframe>
<textarea id="input" rows="8" style="width:100%"></textarea><br />
<button onclick="Update()">Add Content</button>

</body>
</html>
```

This provides a type-in area where you can enter text and math, and an "Add Content" button that will append your text to the iframe above and typeset any math that was entered.  See if that doesn't work for you, and if that will let you work out the issue you are having.

**Comment by dpvc** [comment]
PS, note that the example uses TeX input.  You could change it to use MathML input, but would have to use `innerHTML` to add the text in order to get the MathML tags to be turned into actual tags in the body of the iframe.
