### ISSUE TITLE
MathJax slowing down after repeated use.

### ISSUE THREAD

**Issue by kavibvaidya** [mathjax/MathJax#2082]
Hi,

I am working on a project that allows users to input MathML, see preview and submit and edit there inputs repeatedly. This process works fine in the beginning, but after repeated use, the browser seems to slow down considerably. I think that the issue is with MathJax because I see MathJax messages on the bottom left. Is this because of some inefficiency on my side, a bug in MathJax or because there is a lot of MathJax present on the page? In any case, can someone suggest a solution?

Regards,

Kavi

**Comment by dpvc** [comment]
Without more details about how your page operates, it is not really possible to tell where the problem lies.  If you are adding more and more math to the page (as opposed to replacing old math with new), then yes, a slowdown is inevitable.  As the math is added to the page, the page DOM becomes more complicated (the HTML inserted by MathJax is complex and deeply nested), so that makes updates to the page slower and slower.  Redrawing the page is one of the most time-consuming tasks of the browser, and MathJax does cause several repaints during its processing.

One way to help reduce the cost of this is to ask MathJax to process math in batches.  If you are typesetting each equation individually, for example, that will be the least efficient output.

But again, without any real idea how your code works, we can only offer you general guidance.
