### ISSUE TITLE
Vertical misalignment of arrays

### ISSUE THREAD

**Issue by kwkbtr** [mathjax/MathJax#2083]
Minimal test case: https://jsbin.com/vedulobegu/1/edit?html,output

The top padding of (the first line of) a LaTeX `array` changes depending on existence of horizontal rules inside the array.
In the above test case, top edges of two `array`s are misaligned with each other.
It seems that the difference comes from this code: https://github.com/mathjax/MathJax/commit/577b37ee60cd86b782366cda069594c3bb76ef41#diff-2f75a19c51cea069923d362e44d2deb0R154
Is this expected behavior? Is there any workaround to align them?

**Comment by dpvc** [comment]
> Is this expected behavior?

Yes, this is the expected behavior at the moment.  In fact, the commit that you reference specifically established this behavior (as described in the commit message).

The easiest way to get the two to be the same size would be either to add padding to the one without the line to make it the same size as the other, or to add negative margin to the one with the line to remove the extra padding that it gets because of the line.

The first could be handled via:

```
\bbox[padding: .5ex .4em]{\begin{array}{ll}
        AB & CD\\
        EF & GH\\
        IJ & KL
        \end{array}}
```
to match the extra frame spacing that the line forces on the array, while the second would be
```
\bbox[margin: -.5ex 0]{\begin{array}{ll}
        AB & CD\\
        EF & GH\\ \hline
        IJ & KL
        \end{array}}
```
to remove the extra vertical spacing from the array with the line.  (You could use -.4em in place of the 0, but because the lines do extend .4em beyond the array, you might not want to do that.)

**Comment by kwkbtr** [comment]
Thank you for the answer.

> In fact, the commit that you reference specifically established this behavior (as described in the commit message).

I do not understand why this behavior is introduced.
The commit message *"Make mtable row and column lines extend through frame spacing even when no frame is used"* is about how far lines extend and it seems to me that it is unrelated to padding above first lines of arrays.
I hope this issue to be addressed, but I will try the workaround you suggested at the moment.

P.S. I am trying various features of MathJax currently and amazed by its quality and flexibility. Thank you for the great library!

**Comment by dpvc** [comment]
> I do not understand why this behavior is introduced.

It has to do with how the underlying MathML is handled (since the TeX is turned into MathML).  In version 3, the lines will not extend as they do in v2.  In version 2, any line causes the MathML frame spacing to be used (and the frame spacing is in both directions).  The TeX conversion to MathML could have set the frame spacing to 0, but didn't in v2.

> I am trying various features of MathJax currently and amazed by its quality and flexibility. Thank you for the great library!

You are welcome, and thank you for the kind words.
