### ISSUE TITLE
Mathjax not rendering properly, sporadically in iframe

### ISSUE THREAD

**Issue by parthi2929** [mathjax/MathJax#2090]
I am trying to use iframe in my blog, and the iframe contains mathjax equations. Below is one messed up rendering when I use a html containing latex equation as iframe. 

![image](https://user-images.githubusercontent.com/11896263/49388951-29c22f80-f74b-11e8-8292-0b14b95ffc0a.png)

[Here](https://www.rparthiban.com/articles/udacity/udacity_st101/12_problem_set_2/#) is the link where the problem is observed.  (Any part except first one)

However, when the respective individual html files which I viewed via iframe, are viewed separately, such a behaviour is not observed. Example [here](https://www.rparthiban.com/articles/wp-content/uploads/2018/12/122-ud_st101-Part_2.html)

So I understand because somehow I load multiple iframes, this is happening. What could be the cause? Do we have any workaround to avoid such behaviour? I am loading mathjax from CDNjs, as below in header.php file of wordpress

```php
	<script type="text/x-mathjax-config">
		MathJax.Hub.Config({
			tex2jax: {
				inlineMath: [ ['$','$'], ["\\(","\\)"] ],
				processEscapes: true
			}
		});
	</script>
	<script type="text/javascript"
		src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML-full.js">
	</script>	
```

My wordpress details are WordPress 4.9.8 | PHP 7.1.18 | Apache | MySQL 5.6.39-cll-lve
Chrome browser Version 70.0.3538.110

**Comment by dpvc** [comment]
The iframes used for the second through fifth parts are initially styled with `display: none`, which means that the browser will not actually lay out their contents.  MathJax needs to measure the available width in order to do line breaking, and to do so, it needs the iframes to be laid out so that it can measure widths of the math containers.  That is not possible when the iframe is `display:none`, and so MathJax gets a width of 0 for all containers, which is why you are getting the bad line breaking and placement.

There are two possible solutions:

1.  You could use something like `visibility: hidden; height: 1px; overflow: hidden; position: absolute; top:-1px` for the iframes rather than `display:none` for the disabled iframes (use a class so that it is easy to add and remove these styles).  Then MathJax will be able to measure the containers properly, but the content still won't be visible.

2.  You could disabled MathJax's initial typesetting within the iframes, and only call MathJax to typeset them once the iframe is revealed.  (That would require looking up the defaultWindow from the iframe and calling its copy of MathJax in order to typeset the math.)

Note also that the configuration and MathJax call that you list above is **not** the one used in the iframes, which each has its own copy of MathJax.  These are configured via

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML"></script>
    <!-- MathJax configuration -->
    <script type="text/x-mathjax-config">
    MathJax.Hub.Config({
        tex2jax: {
            inlineMath: [ ['$','$'], ["\\(","\\)"] ],
            displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
            processEscapes: true,
            processEnvironments: true
        },
        // Center justify equations in code and markdown cells. Elsewhere
        // we use CSS to left justify single line equations in code cells.
        displayAlign: 'center',
        "HTML-CSS": {
            styles: {'.MathJax_Display': {"margin": 0}},
            linebreaks: { automatic: true }
        }
    });
    </script>
    <!-- End of mathjax configuration -->
```

Note that this is using version 2.7.1 rather than 2.7.5, and it also has the configuration block in the wrong place (the `<script type="text/x-mathjax-config">` should come **before** the script that loads `MathJax.js` itself).

**Comment by parthi2929** [comment]
Oh the latter mathjax script in iframe is straight out of jupyter notebook's nbconvert export. I should notify them this then. Further,

1. In method 1, the content would become visible then when I set for eg visibility:hidden, right?  
2. Since I export notebook, I have control over iframe. I did not understand "calling the copy of mathjax". what exactly is meant by that?

**Comment by dpvc** [comment]
> mathjax script in iframe is straight out of jupyter notebook's nbconvert export. I should notify them this then.

Yes, that would be good (if it hasn't been reported already).

> In method 1, the content would become visible then when I set for eg `visibility: hidden`, right?

No, with `visibility:hidden`, the content will no show until you remove the `viability: hidden` (and the rest of the CSS that I listed above).  This will look the same as if you used `display: none`, but since the browsers do lay out the contents of elements with `visibility: hidden`, this should allow MathJax to make proper measurements within the iframe.

> Since I export notebook, I have control over iframe so I guess I could inject any patch if required. I did not understand "calling the copy of mathjax". what exactly is meant by that?

You don't need to inject anything, but just need to execute the `MathJax.Hub.Typeset()` command of the MathJax that is within the iframe.  Something like

```
var fMathJax = document.getElementById("ifrm_2").contentWindow.MathJax;
fMathJax.Hub.Queue(['Reprocess', fMathJax.Hub]);
```
should do the trick (once the frame is visible).
