### ISSUE TITLE
Vector magnitude notation $\|$ cannot be rendered in markdown table.

### ISSUE THREAD

**Issue by HI-01** [mathjax/MathJax#2108]
Hello,
I am trying to display the vector magnitude notation `$\|$` in a table using markdown. For example, the magnitude of velocity vector `$\|v\|$`. It can be rendered properly in jupyter notebook; however, it cannot be rendered properly in the nbviewer. Could you help me out?
Project with problem: '[OrbitSimulation - Github](https://github.com/HI-01/OrbitSimulation/blob/master/Orbital%20Simulation.ipynb)', very last section of list of variables
Example:
|`v`|list|$\|\mathbf{v}\|$|$\mathrm{m/s}$|The magnitude of $\mathbf{v}$|
Thanks!

**Describe the bug**
The vector magnitude notation `$\|$` cannot be rendered correctly in a table using markdown. 

**To Reproduce**
1. Go to '[OrbitSimulation - Github](https://github.com/HI-01/OrbitSimulation/blob/master/Orbital%20Simulation.ipynb)' or '[OrbitSimulation - nbviewer](https://nbviewer.jupyter.org/github/HI-01/OrbitSimulation/blob/717fd81642d0881617d5d61243e33ea38c2e18cf/Orbital%20Simulation.ipynb)'
2. Scroll down to 'Rocket Variables' (the very end of the project)
4. See error: notation displayed incorrectly

**Expected behavior**
Render of the vector magnitude notation "double vertical lines". ||v||
Desired render example from jupyter notebook:
![Figure 1](https://user-images.githubusercontent.com/28213746/50636197-2e6b4500-0f90-11e9-87da-1555e71c0f68.png)

**Screenshots**
Undesired render from nbviewer:
![default](https://user-images.githubusercontent.com/28213746/50636414-f0baec00-0f90-11e9-98e6-e7bdb822400c.png)
Undesired render from Github:
![default](https://user-images.githubusercontent.com/28213746/50636305-85711a00-0f90-11e9-8562-0e3f53356caa.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 1803]
 - Browser [Firefox; Chrome]
 - Version [64.0; 66.0.3359.139]

Thank you.

**Comment by dpvc** [comment]
I suspect that the issue is that there is a bad interaction between the table package you are using in Markdown and the LaTeX notation.  It looks like the source Markdown uses `|` as the table cell separator, and that seems to be treating the `|` in `\|` as such a separator (this is clearest in the nbviewer version).

So you may need to escape the math in some way.  Try `\\|` or `\\\|` and see if that works.  Otherwise, you could use alternatives that don't include `|`, such as `\vert` and `\Vert`.
