### ISSUE TITLE
Prevent re-rendering Inline styles changes 

### ISSUE THREAD

**Issue by sajanpaul** [mathjax/MathJax#2112]
Hi I developed a highlighter pen plugin which used to highlight HTML content 
It's work by wrapping mark tag around selected content

by its works flow the targeted content will be removed from the DOM, append to a mark element  add re-add to content,

 sometimes after re-add the Mathjax changing the inline style of rendered elements and its case to break the equation, there is any way to prevent this..?

![image](https://user-images.githubusercontent.com/4005745/51295764-29ea6600-1a3f-11e9-92db-2300501645b6.png)

**Comment by dpvc** [comment]
It is not clear from your description how you are treating nested content.  For example, if you have 

    this is <b>bold text</b> in a sentence

and what to highlight "is bold", then your mark tagging would produce something like

    this <mark>is <b>bold</mark> text</b> in a sentence

and that would be invalid markup (the nesting is incorrect), and you would probably lose the bold on "text".  Instead, you would need to do

    this <mark>is <b>bold</b></mark><b> text</b> in a sentence

and so would have to duplicate tags (or build duplicate structures) when you marking is not all at the same level in the DOM hierarchy (i.e., when the parent element of the start and end of the mark is not the same).  Are you doing that?

Alternatively, you might be producing

    this <mark>is </mark><b><mark>bold</mark> text</b> in a sentence.

using multiple marks to represent one selection?

While these approaches might work for simple examples like this, when CSS is involved, splitting elements (like the `<b>` above) may have unwanted consequences.  For example, CSS can style based on position in the hierarchy (what is the parent or what is the sibling to the left or is this the first element of the parent, etc.), one you introducing additional elements into that tree may disrupt those CSS selectors.  

MathJax uses a LOT of very delicate CSS, so inserting tags into MathJax output is going to cause problems.  I don't see any reasonable way to avoid that.  Manipulating the DOM in this way is bound to cause such problems, even on content that is not from MathJax.  For example, how do you handle  a section that starts outside a table and ends inside it?

Rather than inserting your market directly into the DOM and splitting up elements, it might be better to produce some sort of overlay (with transparent colors) that sits on top of the page (with absolute positioning).  You would have to look up the bounding boxes of the elements to include in your selection, but you would not have to disrupt the existing DOM structure to do it.  Absolute positioning has its own problems (e.g., it would not respond to changing window sizes as the text reflows, for example).  So there are trades-offs the you have to consider.

But I don't think you will get your current approach to interact well with MathJax output.

**Comment by sajanpaul** [comment]
Hi sorry for my late replay,
actually, my code doesn't break any markup structure, it's not just 'document.exec' it identifies the starting and ending of selection and travels to  common ancestor level then take a decision to where to put the mark tag,  it works in a good way
for example if someone select 'is bold' text 

` this is <b>bold text</b> in a sentence`

the mark tag will be added like this

` this<mark> is</mark> <b><mark>bold</mark> text</b> in a sentence`

if someone selects like this  

```
<td>apple</td>
<tr>
  <td>orange</td>
  <td>banana</td>
</tr></tobody><table><p > i  <span>like </span>  <b>fruit</b>  <i> salad
```

the mark will be added like this

```
<td><mark>apple</mark></td>
<tr>
  <td><mark>orange</mark></td>
  <td><mark>banana</mark></td>
</tr></tobody><table><p > <mark> i  <span>like </span>  <b>fruit</b> </mark>  <i> <mark>salad</mark>
```
for some cases it doesnt added mark tag inside partialy selected element fo example
`This is an  <span class="label"> IMPORTANT <span>  article`

if someone selects the text 'This is an  IMPO' then  the tag will be added like this

`<mark> This is an  <span class="label"> IMPORTANT <span>  </mark> article`

because the selector `span.label` has a special meaning and highlighter know that it's considering as a single unit, do not break it.

this is the same way it dealing with mathjax equations, it won't break any equation structure the entire equation is considered as a single unit 

this is a sample non rendered structure for **ax<sup>2</sup>+bx+c=0** 

```
<span class="math-eq">
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mi>a</mi><msup><mi>x</mi><mn>2</mn></msup>
  <mo>+</mo> <mi>b</mi><mi>x</mi>
  <mo>+</mo> <mi>c</mi> <mo>=</mo> <mn>0</mn>
</math>
</span>
This is a nice equation
```
 even  the selection is made for 'bx' the whole equation ( span.math-eq) will be marked

and my real problem is that 
 my plugin replace this selected equation ( span.math-eq  element )with a mark tag the mark tag contains the duplicate of removed dom

after replacing in some occasion the mathjax is re-rendering inline styles of the duplicated equation (not always only some time) is there is any way to prevent this ..?

   also, I think that this is an inapproripate way to asking help by opening  an issue in GitHub, I should do this in some kind of community forum so I kindly requesting to admin to delete this issue, 
I will move this issue to the community forum or StackOverflow 

Thank you

**Comment by dpvc** [comment]
OK, it sounds like your inserting of tags should work.  But depending on how you accomplish the insertion, that could be the source of the problem.

If you are using `innerHTML` to change the DOM, then that will cause MathJax to think the math is new math on the page and it will be typeset again the next time you typeset the page.  If you are not using `marker = document.createElement('mark')` to create your markers and `marker.appendChild()` to insert the marked elements into the marker, then that may be the source of the problem.  Without more detail about the actual code you are running, it is hard to tell.
