### ISSUE TITLE
MathJax.js not rendering when installed via npm in angular 7 

### ISSUE THREAD

**Issue by NaveenMysuru** [mathjax/MathJax#2114]
<script type="text/javascript">
     MathJax.Hub.Config({
        tex2jax: {
            inlineMath: [['$','$'], ['\\(','\\)']],
            processEscapes: true
            }
      });
    </script>
    <script type="text/javascript" src="../node_modules/mathjax/MathJax.js"></script>

after installing via npm with types, as per documentation, i have included above script in index.html . but getting 404 not found.

**Comment by dpvc** [comment]
If you are getting a 404 error for `MathJax.js`, then the URL in the script tag is probably incorrect.  Since you are using `../node_modules/mathjax/MathJax.js` that suggests that the HTML file you are viewing is located in a subdirectory of the the directory containing `node_modules`, (e.g., your main directory contains `node_modules` and `html` and the web page you are viewing is `html/index.html`); is that correct?  If not, then you need to adjust your script `src` attribute.

If the 404 error is not for `MathJax.js`, then which file is it for?

Also, are you loading the page via a server (a `http://` URL) or from a local file (from a `file://` URL)?  If you are using a server, are you sure the `node_modules` directory is available to the server (i.e., it is in the server's file system, and has appropriate permissions to allow the wen server to access the files)?  Have you checked the server log to see if there are any helpful messages there?

Finally, there are several issues with your configuration.  First, it should have `type="text/x-mathjax-config"` not `type="text/javascript"`, otherwise the browser will try to run it, and since it is before MathJax is loaded, you will get an error about `MathJax` not being defined.

But even if you change that, you still have not configured any input or output processors, so MathJax will not perform any actions.  You either should include one of the combined configuration files via the script tag that loads `MathJax.js`, as in 

```
<script type="text/javascript" src="../node_modules/mathjax/MathJax.jsconfig="TeX-AMS_CHTML"></script>
```

if you need to include something like

```
<script type="text/x-mathjax-config">
 MathJax.Hub.Config({
    jax: ['input/TeX', 'output/CHTML'],
    extensions: ['tex2jax.js'],
    tex2jax: {
        inlineMath: [['$','$'], ['\\(','\\)']],
        processEscapes: true
    }
  });
</script>
```

in order to load an input and output processor, and a preprocessor to find the TeX-formatted math on the page.  You may want other extensions as well (like the AMSmath and AMSsymbols extensions).

Finally, I'm not very familiar with Angular, but you may need to do more to properly integrate MathJax with Angular.  See for example [this post](https://stackoverflow.com/a/16646667/502334) for one person's approach.
