### ISSUE TITLE
less-than sign error

### ISSUE THREAD

**Issue by supidea** [mathjax/MathJax#2116]
ex:
$4<BD<10$
it can't work 

$4 <BD<10$
have a space before '<' , it work...

mathjax 2.7.5  latest

**Comment by pkra** [comment]
See https://docs.mathjax.org/en/latest/tex.html#tex-and-latex-in-html-documents

**Comment by dpvc** [comment]
Since the tags on the page are interpreted long before MathJax gets to run, there is really nothing that can be done from MathJax's end of things.  You would need to modify your data, either in the database itself, or in a pre-processing phase before sending it to the HTML page.  It would be best to send

```
sdfsdfeo$4&lt;BD&lt;10$
```

instead.  If your database doesn't include HTML tags, or if the math is stored separately so that you can easily identify it, then you could probably just do a search-and-replace to replace `<` by `&lt;` globally (and `>` by `&gt;`, and `&` by `&amp;`, though that should be done before the other two).  If your data include HTML tags or the math isn't separate, then it will be harder to fix.
