### ISSUE TITLE
Rendering Problem with dynamic page

### ISSUE THREAD

**Issue by agmorpheus** [mathjax/MathJax#2119]
Hello,

I have a dynamically loading website. There are content pages and a start page, each using a template. In this template different javascripts are integrated. On the content pages the MathJax script is loaded.
Now it's like this: If I call a content page for the first time, equations are displayed correctly. If I call another content page, everything is still fine. But if I call the start page in the meantime and then a content page again, then the equations are no longer displayed correctly. Then I have to do a complete browser refresh, only then it runs again. 
The following code is executed every time a content page is loaded:
MathJax.Hub.Queue(["Typeset", MathJax.Hub, this.viewTarget]);

I've tried everything possible, but can't get it to work that when the start page is called in the meantime, the equations are displayed correctly afterwards.

![image](https://user-images.githubusercontent.com/16916776/52418610-b17f3e00-2aee-11e9-9620-6a512db31f2b.png)

Do you have an idea were the problem lies?

**Comment by dpvc** [comment]
There is not enough information to provide a meaningful answer.  Without more details about how your code works, we really can't give you much advice.  For example, it is not clear what "call a content page" means.  A minimal (non)working example in jsfiddle or codebin would be best, or access to a live page that you are working on.

It sounds like you may be landing the content pages into separate iframes (since you say they include MathJax in each page).  If that is the case, your `MathJax.Hub.Queue(["Typeset", MathJax.Hub, this.viewTarget]);` must be done within the iframe itself, not the main page.

Without more details about how your code actually works, there is not much more we can say.

**Comment by agmorpheus** [comment]
Thanks for the answer. The whole thing is not so easy to explain, but I'll give it a try: 
We have browser application that can load three types of pages (templates):
- Home 
- content page
- search page
The templates contain the structure of a page, including the scripts that have to be loaded. The template for the content pages contains e.g. the MathJax script, the other templates do not. 
The templates are all dynamically loaded via Javascript, so there are no classic page jumps. The whole DOM is exchanged when switching from home to a content page. If a template is loaded, further contents within the template are exchanged, so that you see then the desired contents.

MathJax works when the content template is loaded for the first time. I can also load more content pages, but as soon as the DOM is completely swapped, i.e. the script is unloaded and then reloaded at a later time, it won't work anymore.

I hope it's clearer now and you have a hint.

Translated with www.DeepL.com/Translator

**Comment by dpvc** [comment]
It is not clear what "the whole DOM is exchanged" means.  If you are doing something like setting `document.body.innerHTML`, then that might be part of the problem, since MathJax inserts some hidden elements into the page that it needs in order to make measurements and so on.  If you swap out the DOM, you will lose those elements, and MathJax will not be able to make the measurements it needs.  Have you checked the console log to see if there are any error messages there that might be related to this?

Also, simply inserting the `<script>` tag that loads MathJax will not make MathJax run again.  Since the `MathJax` variable is already in place, loading MathJax again will do nothing (the `MathJax.js` script checks for `MathJax` already existing, and does nothing if it does).  It is also not efficient to load `MathJax.js` multiple times.

You should probably look at the [documentation](http://docs.mathjax.org/en/latest/advanced/typeset.html) for information about how to use MathJax when there is dynamically loaded content on the page, as in your case.
