### ISSUE TITLE
Mathjax can be edited like mathquill, is it possible?

### ISSUE THREAD

**Issue by dirkncl** [mathjax/MathJax#2127]
The development of HTML / javascript technology is so fast, something that was once impossible, can now be possible.
Without a javascript program, Mathjax can be edited directly like Mathquill, to refine the editing it can be tricked with a simple program from JavaScript.

Roughly all html pages can be edited with a new html syntax, but we should take the important elements.

1. Examples for all htm pages can be edited:
~~~html
<body contenteditable = 'true'>
Equation*:

\begin{equation*}
E = mc^2
\end{equation*}

<hr>
Brackets:

\[E = mc^2\]

Brackets tagged:

\[E = mc^2\tag{x}\]

</body>
~~~
2. examples for elements:
~~~html
<div contenteditable = 'true'>\[E = mc^2\tag{x}\] </div>
<span contenteditable = 'true'>\[E = mc^2\tag{x}\] </ span>
~~~
3. with a piece of javascript:
~~~html
<span id = 'sp'> 
\begin {equation}
E = mc ^ 2
\end {equation}
</span>
<script>
document.getElementById ('sp'). ondblclick = function () {return document.getElementById ('sp'). setAttribute ('contenteditable', 'true')};
   document.getElementById ('sp'). onclick = function () {return document.getElementById ('sp'). setAttribute ('contenteditable', 'false')};
</script>
~~~

**Comment by dpvc** [comment]
MathJax replaces the original TeX margin with complicated HTML spans or SVG tags in order to accomplish the typeset layout of the mathematics.  Once that is done, the original TeX code is no longer available to be edited, and editing the resulting spans or SVG tags is not appropriate.  So using `contenteditable` is not going to work as you would hope.

You would need to remove the typeset math and replace the original TeX code, let the user edit that, and then re-typeset the result.  That is possible, but non-trivial.

There are a number of editing options already available out there.  Most are markdown editors that allow you to edit a markdown document on one window and see a live preview in another.  You can find such examples by googling [mathjax markdown online editor](https://www.google.com/search?q=mathjax+markdown+online+editor) for instance.

**Comment by dirkncl** [comment]
Thank you for the explanation.
It's clear that the core of Mathjax has been fixed.
To vary it is up to anyone who wants to develop it in the form of MathJax-third-party-extensions.
Ok, thanks.
