### ISSUE TITLE
[TeX input] reset mathvariant in text mode 

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#2131]
E.g., `\mathbf{bold \text{ not bold} }` makes `not bold` bold. However, in real LaTeX, that's not the case.

**Comment by pkra** [comment]
In particular, this also affects \tag{} content.

**Comment by dpvc** [comment]
This was actually intentional.  Because MathJax doesn't process macros in text mode, and in particular, something like `\text{\bf x}` would not work, MathJax maintains the outside font inside the `\text{}` content.  This is, in fact, how `\textbf{}` and similar macros work.  E.g., `\textbf` is defined as  `\mathord{\bf\text{#1}}` .

The issue with `\tag{}` is unintentional, however.

For now, you can work around these by using a TeX put jax pre-filter to convert `\text` to `\textrm` and `\tag{.*}` to `{\rm\tag{$1}}`.

**Comment by pkra** [comment]
> This was actually intentional. 

Could you clarify if you are willing to change this behavior in general? (Either in the core or at least in the text-macros extension in #2051.)

**Comment by dpvc** [comment]
The text-macros extension #2051 already resets to normal (i.e., doesn't retain the surrounding font), so that already does what you ask.

I'm not against changing the behavior, but it is not a high-priority item at the moment, other than fixing the `\tag` problem (though it might be able to be handled at the same time that the `\tag` issue is fixed).

**Comment by pkra** [comment]
Thanks for clarifying.
