### ISSUE TITLE
doesn't support some latex

### ISSUE THREAD

**Issue by Harrypotterrrr** [mathjax/MathJax#2138]
such as,
```latex
$$
L =  \underbrace{ \frac{1}{N} \sum_i L_i }_\text{\normalfont {data loss}}   +   \underbrace{ \lambda R(W) }_\text{regularization loss}
$$
```
and this,
```latex
$$
L = \frac{1}{N} \sum_i \sum_{j\neq y_i} \left[ \max(0, f(x_i; W)_j - f(x_i; W)_{y_i} + \Delta) \right]  + \lambda \sum_k\sum_l W_{k,l}^2
$$
```

How can I solve this? thanks for your patience and help!

**Comment by Victorfy** [comment]
@Harrypotterrrr did you solve that problem?
can't display `\underbrace`

**Comment by Harrypotterrrr** [comment]
@Victorfy  hmmm If my memory serves me right. I think I append escape char fron of `\`. that is `\/underbrace`? I turn to use another way to deal with this tricky problem.

**Comment by dpvc** [comment]
There is no problem with underbrace, as MathJax handles that just fine.  Indeed, both expression are processed fine by MathJax (other than the `\normalsize` inside the `\text`, which isn't processed).  The problem is likely that you are entering your mathematics in a content management system that uses Markdown syntax, where underscores indicate italics.  Because your expressions have multiple underscores, in something like `\sum_i L_i`, Markdown may be treating `_i L_` as meaning italics, and converting it to `<em>i L</em>`.  Since MathJax doesn't process math containing HTML tags like `<em>`, this will prevent the math from being typeset.  You may have to use `\_` in place of `_`.

In any case, it has nothing to do with the `\underbrace` itself, which is fine.
