### ISSUE TITLE
Wandering integral limits

### ISSUE THREAD

**Issue by cebola2** [mathjax/MathJax#2139]
Integral limits may slide to the right of the integral symbol when line breaking occurs. Check the outer limits in the last triple integral in the first section of https://cdi2tp.math.tecnico.ulisboa.pt/test.php . Depending on the browser this will be visible in one of the examples, at least in the last one. The problem disappears if one avoids line breaking.
![Screenshot_2019-04-19 CDI II — Taguspark — Teste](https://user-images.githubusercontent.com/1136663/56419102-07abf280-6291-11e9-989b-ade6010d7f4a.png)

**Comment by EmanuelPrima** [comment]
Unfortunately this is very common for me un sites such that math.StackExchange.

**Comment by dpvc** [comment]
This turns out to be a problem in the line breaking code that neglected to remove the italic correction for integrals when they are moved to the new line.  It affects all three output formats (HTML-CSS, CHTML, and SVG).  I have made a commit the fixes it, but unfortunately, there is no easy means to patch it locally, so you will have to wait for the next version of MathJax for the fix.

**Comment by dpvc** [comment]
In testsuite:

MathMLToDisplay/Presentation/ScriptsAndLimits/issue2139.html
