### ISSUE TITLE
Using \newline instead of \\ causes rendering failure

### ISSUE THREAD

**Issue by Strilanc** [mathjax/MathJax#2141]
This latex input:

    a = b \newline c =d

produces this mathjax error output:

![image](https://user-images.githubusercontent.com/79941/56627481-d74eb600-65fa-11e9-8bec-7dcdb83755c4.png)

But it should produce the same output as this input:

    a = b \\ c =d

which produces:

![image](https://user-images.githubusercontent.com/79941/56627492-e46ba500-65fa-11e9-9e60-ff0f21c13254.png)

Somewhat surprisingly, `\newline` starts working when inside of bmatrix blocks or aligned blocks.

**Comment by dpvc** [comment]
Currently in MathJax, `\newline` is equivalent to `\cr`, and so it can only be used inside alignments.  If you disabled the `noErrors` extension, you would get the message "Misplaced \newline", indicating the problem is that the `\newline` is used in a location where it is not allowed.

Of course, in actual LaTeX, neither `\\` nor `\newline` produce line breaks in math mode, and so what these "should" do is debatable.  But I suspect that for the purposes of MathJax, producing the actual line break would be a reasonable result.

**Comment by dpvc** [comment]
In testsuite:

LaTeXToMathML/issue2141.html
