### ISSUE TITLE
Bug: MathJax misconfigurations when Configurations are set by external JS file

### ISSUE THREAD

**Issue by hishamshatnawi** [mathjax/MathJax#2142]
### Issue Summary
MathJax is mixing wrong configurations when these configurations are set by an external JS call

First, these are the configurations intended to be set: 
`/* MathJax Configurations  */
MathJax.Hub.Config({
        "HTML-CSS": {scale: 70, linebreaks: {automatic: true, width: "container"}},
        SVG: {linebreaks: {automatic: true, width: "25%"}},
        menuSettings: {zoom: "Click"},
        skipStartupTypeset: true
    });`
### Steps to Reproduce
For example : https://www.tandfonline.com/doi/full/10.1080/17513758.2016.1216613

1. In browser's console: check MathJax configurations by typing : `MathJax.Hub.config`

You can see that 'HTML-CSS' has wrong "linebreaks" configurations as its 
`{ automatic: true, width: "25%" }` while its width was configured to be "container", this is the configurations for it :
` "HTML-CSS": {scale: 70, linebreaks: {automatic: true, width: "container"}}`

The "25%" came from SVG's configurations as it's set to be : `SVG: {linebreaks: {automatic: true, width: "25%"}}`
Most probably, the 2nd configuration overwrites the 1st one.
![image](https://user-images.githubusercontent.com/30464053/56656907-61505a80-669f-11e9-827a-176549dec49b.png)

2- MathJax configurations file is called by jQuery, retrieving this file (Check Network tab in browser's debugger):
https://www.tandfonline.com/templates/jsp/_style2/_tandf/pb2/js/mathJaxConfiguration.js?_=1556103521850

3- These configurations are initialized by the following in HTML body : 
`<script type="text/javascript">
    window.MathJax = {
        AuthorInit: function () {
            $.getScript( '/templates/jsp/_style2/_tandf/pb2/js/mathJaxConfiguration.js' );
        }
    };
</script>`

4- Reproducing this bug on localhost will not work unless you use tunnelling software like Ngrok for example.

5- As a workaround, this is solved by getting rid of $.getScript call and placing the configurations directly in script tag, like this : 

`<script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
   MathJax.Hub.Config({
        "HTML-CSS": {scale: 70, linebreaks: {automatic: true, width: "container"}},
        SVG: {linebreaks: {automatic: true, width: "25%"}},
        menuSettings: {zoom: "Click"},
        skipStartupTypeset: true
    });
</script>`

6- Another way of getting proper configurations, is by delaying MathJax before initializing MathJax configurations (i.e: by debugging MathJax code in browser). You will notice that MathJax will have the proper configurations.

Screenshot for proper configurations when using changing the configurations like in step 5: 
![image](https://user-images.githubusercontent.com/30464053/56657518-e5571200-66a0-11e9-81a7-b76b618156f2.png)

### Technical details
* MathJax Version: 2.7.0 , Applicable on newer versions
* Client OS: Any
* Browser: Any

**Comment by dpvc** [comment]
I am not able to reproduce the issue you are having.  The configuration is correct in the three browsers that I tested with.  What browser and OS are you using?  Are you sure you're not getting an earlier version of the `mathJaxConfiguration.js` file from your browser cache?  I don't see how the SVG configuration could be overwriting the HTML-CSS configuration.

MathJax does have a number of different ways to accomplish its configuration, but unfortunately the jQuery `getScript()` approach you are using isn't one of them, and although it may work in some circumstances, it may fail in others.  That is because `getScript()` is not synchronous, so your `AuthorInit()` function will return **before** the script is loaded and run, and so MathJax will continue its startup process before your configuration is even in place.

Wouldn't it be easier just to have the `mathJaxConfiguration.js` be

```
window.MathJax = {
    "HTML-CSS": { scale: 70,  linebreaks: { automatic: true, width:"container" } },
    SVG: { linebreaks: { automatic: true, width:"25%" } },
    menuSettings:{zoom: "Click"},

    /* This is necessary to lazy loading. */
    skipStartupTypeset: true
};
```

and use

```
<script type="text/javascript" src="/templates/jsp/_style2/_tandf/pb2/js/mathJaxConfiguration.js"></script>
```

rather than the indirection using jQuery?

If you are trying to avoid `<script>` tags that load file synchronously, then you should use MathJax's `delayStartupUntil` option to make sure MathJax waits for your configuration to be loaded.  For example

```
<script type="text/javascript">
window.MathJax = {
  AuthorInit: function () {
    $.getScript('/templates/jsp/_style2/_tandf/pb2/js/mathJaxConfiguration.js',
      function () {MathJax.Hub.Configured()});
  }
};
</script>
<script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML,delayStartupUntil=configured"><script>
```

would used the callback from the `getScript()` function to tell MathJax that your configuration is complete.  Alternatively, you could put the `MathJax.Hub.Configured()` call into the `mathJaxConfiguration.js` file.

Finally, it would also be possible to use

```
<script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML,https://www.tandfonline.com/templates/jsp/_style2/_tandf/pb2/js/mathJaxConfiguration.js"><script>
```

with no other in-line MathJax script, provided you added the line

```
MathJax.Ajax.loadComplete('https://www.tandfonline.com/templates/jsp/_style2/_tandf/pb2/js/mathJaxConfiguration.js');
```

at the bottom of that file.  (If you need to have the `?_=1556103521850` at the end of the file, and if that changes from user to user, then that approach would not work, since the URL used to load the configuration file would need to match the one in the `loadComplete()` call exactly.)

So there are a number of possible ways that you might be able to do the kind of (non-blocking) configuration that you are looking for in a way that will work with MathJax.

As for the HTML-CSS configuration, I'm unable to reproduce that.  If you remove the SVG configuration block from your `MathJax.Hub.Config()` call, what happens then?
