### ISSUE TITLE
[CHTML] Wrong sqrt render when argument is missing

### ISSUE THREAD

**Issue by den-low** [mathjax/MathJax#2143]
Mathjax render \sqrt command wrong then argument is missing, for example: $\sqrt[1234]{}$

**Comment by EmanuelPrima** [comment]
What do you mean by "wrong"?

At least in [math.SE](https://math.stackexchange.com) when writing `$\sqrt[1234]{}$` the output is:

![Output](https://user-images.githubusercontent.com/40039900/56856253-dc7a7080-692c-11e9-9731-cd06c9f78a53.png)

which seems reasonable to me, because no argument has passed to the root command.

What kind of problems do you get? Could you please link a page containing the issue?

**Comment by den-low** [comment]
I try a MathJax demo at: https://www.mathjax.org/#demo and get a following behaviour https://gyazo.com/7b9dded3dfc8cab5f5c3ebfc26082ea7

**Comment by dpvc** [comment]
The issue only affects CommonHTML output.  I will need to look into it further.

**Comment by dpvc** [comment]
In testsuite:

MathMLToDisplay/issue2143.html
