### ISSUE TITLE
Fractions rendering poorly in Chrome on Android

### ISSUE THREAD

**Issue by RiderOfGiraffes** [mathjax/MathJax#2151]
Rendering of some equations works fine in Firefox on Ubuntu, but spacing and sizing are inappropriate and render the text unreadable and in some cases undisplayed in Chrome on Android.  Examples here: https://www.solipsys.co.uk/new/MathJaxTest.html

Thanks.

**Comment by dpvc** [comment]
Some browsers on mobile devices will rescale the page after MathJax has already determined the sizes that it needs to use, and that will mean that MathJax's output won't match the surroundings.  That appears to be what is happening fo you, here.

One solution is to add

    <meta name="viewport" content="width=device-width, initial-scale=1">

to the document `<head>`.  This prevents the rescaling so that MathJax's sizing will be correct.  See the [MathJax documentation](http://docs.mathjax.org/en/latest/output.html#viewport-meta-tag).

**Comment by RiderOfGiraffes** [comment]
Thanks for the reply - I have work to do, updating every page on my site, but at least there's a solution.

Cheers.

[Closed]

**Comment by RiderOfGiraffes** [comment]
Unfortunately the "fix" hasn't worked completely.  Please see here:

https://www.solipsys.co.uk/MathJaxProblems/NonRepeatingDecimals.html

That was viewed on the following:

android 5.1 patch 2016-03-01
kernel 3.4.2-g89906d6
chrome 74.0.3729.147

The results can be seen in these screenshots:

https://www.solipsys.co.uk/MathJaxProblems/Screenshot_2019-05-26-17-28-26.png
https://www.solipsys.co.uk/MathJaxProblems/Screenshot_2019-05-26-17-28-42.png
https://www.solipsys.co.uk/MathJaxProblems/Screenshot_2019-05-26-17-29-44.png
https://www.solipsys.co.uk/MathJaxProblems/Screenshot_2019-05-26-17-31-15.png

The code does contain in the <head> section:

  <meta name="viewport" content="width=device-width, initial-scale=1">

Advice and assistance welcome ... thank you.

**Comment by dpvc** [comment]
Well, it works for me.  Here is a screenshot:

![Screenshot_20190526-141036](https://user-images.githubusercontent.com/432782/58385671-20ab7000-7fc2-11e9-80a2-415d8500371e.png)

The only difference I see is that you are using Android 5.1 and I'm using 8.1.  You're 5.1 is over three years old (an eternity in web years, especially mobile web years).  I don't recall when Android started to support the viewport meta, but from your screen shots, it looks like your browser is not performing the viewport meta tag.  That could be because you are getting a cached version of the page, or because Android 5.1 doesn't support it (even though you are using a current version of Chrome, it could be calling on system-level libraries that don't support the viewport meta).  

You could try clearing the browser data (from the history page) and see if that clears it up.  If not, other than upgrading the version of Android, I'm not sure what to tell you.

**Comment by RiderOfGiraffes** [comment]
It's being reported by one of my readers.  They already had a clean cache (always the first thing I ask them to do) so it's not that.

So I'm guessing that  just have to say to my reader(s) that their browser is unsupported - is that it?

**Comment by RiderOfGiraffes** [comment]
From my reader:

> My "Moto G" has the latest of everything Motorola has made available for it.
> I don't imagine I can upgrade Android manually beyond the level offered by Motorola.
> Anyway if it looks ok on more modern Android devices then I guess this is case closed.

Assuming you can't suggest anything else, thanks for your time.

**Comment by dpvc** [comment]
It's not the browser, but the OS version, apparently.

There are some other options, however.  The HTML-CSS renderer, which you are using, is the oldest one available in MathJax, and is somewhat fragile.  You could switch to either the CommonHTML or the SVG renderer, both of which are more reliable.  If you aren't using MathML input, use either `TeX-AMS_CHTML` or `TeX-AMS_SVG` rather than `TeX-AMS-MML_HTMLorMML`.  My tests suggest that either of this will work for you without the viewport meta tag.  They are also both faster than HTML-CSS, so that is a plus.  Try that out and see if that helps your user.

I also see that you are using MathJax v2.7.1; the current version is 2.7.5, so I'd recommend upgrading to that while you are at it.

**Comment by RiderOfGiraffes** [comment]
OK ... I don't actually know anything about MathJax, nor about HTML or CSS, but here is what I take from your comment.  Currently I have:

https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML

Instead I should have:

https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_SVG

or

https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_CHTML

I'll try that and see what happens, but if I've got it wrong I'd appreciate some further details.

And again, thank you.

**Comment by dpvc** [comment]
You have it right.  Give either of those a try.

**Comment by RiderOfGiraffes** [comment]
That seems to be working - thank you.

Update of 1100 pages now in progress ...

**Comment by dpvc** [comment]
Good luck with the update.  Glad we were able to find something that worked for you.

**Comment by RiderOfGiraffes** [comment]
Cheers.
