### ISSUE TITLE
Uncaught TypeError: Cannot read property 'firstChild' of null

### ISSUE THREAD

**Issue by apio1** [mathjax/MathJax#2157]
Hello, I know there was another similar issue #1840 on Sep 18, 2017, but it was not resolved. 

I'd like to provide a preview of another page containing MathJAX code to the visitors of my side. This preview page is shown in a popup window when a visitor clicks a link. 

In most cases, it works like intended and all math formulae are rendered correctly. But I observed that sometimes, especially when the formulae on the preview page contain line breaks, the Mathjax rendering process stops with the following error 

xypic.js?V=2.7.0:5208 Uncaught TypeError: Cannot read property 'firstChild' of null
    at Object.PHTMLstretchV (TeX-AMS_HTML-full.js?V=2.7.0:57)
    at Object.PHTMLstretchChild (TeX-AMS_HTML-full.js?V=2.7.0:57)
    at Object.toPreviewHTML (TeX-AMS_HTML-full.js?V=2.7.0:57)
    at Object.PHTMLaddChild (TeX-AMS_HTML-full.js?V=2.7.0:57)
    at Object.PHTMLdefaultSpan (TeX-AMS_HTML-full.js?V=2.7.0:57)
    at Object.toPreviewHTML (TeX-AMS_HTML-full.js?V=2.7.0:57)
    at Object.PHTMLaddChild (TeX-AMS_HTML-full.js?V=2.7.0:57)
    at Object.PHTMLdefaultSpan (TeX-AMS_HTML-full.js?V=2.7.0:57)
    at Object.toPreviewHTML (TeX-AMS_HTML-full.js?V=2.7.0:57)
    at Object.postFilter (TeX-AMS_HTML-full.js?V=2.7.0:58)

In order to reproduce the error, you can go to https://www.bookofproofs.org/branches/multiplicativity-of-the-legendre-symbol/ 

You should be getting a correct rendering of the preview page, when you click on the links "prime number", "completely multiplicative" and "integers". But if you click on the link "Legendre symbols", you should see the preview page without rendered formulae, (e.g. "$\left(\frac 1p\right)=1$ for all $p > 2.$") The above error message is shown in the console of the browser, once you preview this erroneous page.

Curiously, the same erroneous page is rendered correctly if it is NOT loaded via AJAX in a popup window but loaded directly (see link https://www.bookofproofs.org/branches/legendre-symbol/)

I'm using MathJAX 2.7. Is there a workaround to get around this issue?

**Comment by dpvc** [comment]
The problem is related to the fact that the information is being displayed in a pop-up dialog that has style `display:none` while the math is being typeset.  Because elements with `display:none` are not rendered by the browser, MathJax can't determine the sizes of things (like the surrounding fonts) and so it is best not to try to render math inside such a container.  It looks like this is causing problems for the fast preview (PreviewHTML) renderer.

There are a couple of possible solutions.  One is to not use `display:none` but instead use `visibility:hidden; height: 1px; width: 1px; overflow: hidden; position:absolute; left: -10px;` or some similar method of making the display not visible, but still be rendered by the browser (so MathJax can get the measurements it needs).

Alternatively, it looks like disabling the fast preview would resolve the issue.  Use

```
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  'fast-preview': {disabled: true}
});
</script>
```

just *before* the script that loads `MathJax.js` itself.

It also looks like switching to the CommonHTML output rather than the older HTML-CSS output renderer might also help.  Use `TeX-AMS_CHTML-full` rather than `TeX-AMS_HTML-full` as your configuration file to get the CommonHTML output renderer instead.

**Comment by apio1** [comment]
I disabled the fast preview and changed to `TeX-AMS_CHTML-full`. Now, it is working!!! Thank you for your valuable suggestions!
