### ISSUE TITLE
Can mathjax expression load without MathJax.js ?

### ISSUE THREAD

**Issue by mohdsafadsaal** [mathjax/MathJax#2161]
Hi ,

We want to load following mathjax html string only with mathjax css styling. 
Is there anyway to load without following snippet in our html 

"<script type="text/javascript"
  src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>"

We dont want to load js script since it would take some rendering time in our client native apps(iOS/Android).

Please let us know if there any solution for native mobile apps to load MathjAx in WebView.

**Comment by dpvc** [comment]
I'm sorry, but I'm confused by your question.  You say 

> We want to load following mathjax html string

but the only strong that I see is the `<script>` tag that loads the MathJax.js itself, which you also say you *don't* want to do.  So I'm confused about what you want.

If you want to preprocess your page using MathJax so that it doesn't have to run in the browser, you might consider [`mathjax-node`](https://github.com/mathjax/mathjax-node), or more specifically, the [`mathjax-node-page`](https://github.com/pkra/mathjax-node-page/) wrapper for it.

You may also want to consider [MathJax version 3](https://github.com/mathjax/MathJax-v3), which is currently in beta with a final release being prepared.  There are examples of how to run MathJax via the command line on individual expressions or on an entire page in the [MathJax 3 node demos](https://github.com/mathjax/mj3-demos-node) repository.  MathJax 3 renders considerably faster than MathJax 2, so perhaps using it in the browser would be acceptable for you.  There are examples in the [MathJax 3 browser demos](https://github.com/mathjax/mj3-demos) repository.
