### ISSUE TITLE
[TeX] multiple definitions cause unexpected result

### ISSUE THREAD

**Issue by bernander** [mathjax/MathJax#2171]
### Issue Summary
MathJax bombs on consecutive macro definitions (but not if first macro used before defining second macro).

### Steps to Reproduce

See minimalist file at http://uofoj.com/bug.htm
which includes the following lines that fail:
$$
\def\Test1#1#2{{ #1, #2 }}
\def\Test2#1#2{{ #1, #2 }}
\Test1{aa}{bb}
\Test2{aa}{bb}
$$

What works: switching the middle lines, so that \Test1 is used before \Test2 is defined.
However, this also stops working if \Test1 is used later, after \Test2 (as a fifth line).

This is a bug because... we cannot define several consecutive macros at the top, then use them later. 

### Technical details

* MathJax Version: 2.7.5 (from CDN)
* Client OS: MacOS 10.14
* Browser: Chrome, Safari, Firefox

**Comment by dpvc** [comment]
It turns out this is not a bug.  Here's why:

In TeX, macro names are either one character (e.g., `\#`), or a sequence of alphabetic characters (e.g., `\sqrt`).  Note, however, that **numbers** are not allowed as part of a multi-character macro name.  In your case, both definitions define a macro called `\Test`, so your second definition redefines the first one.

When you do `\def\Test1#1#2{{ #1, #2 }}`, the macro name is `\Test` and the template for the macro usage is `1#1#2`, which means that `\Test` must be followed by a `1` and then two arguments.  When you do `\def\Test2#1#2{{ #1, #2}}` you are redefining `\Test` to have the template `2#1#2`, which is a `2` and then two arguments.

So after your second definition, `\Test1{aa}{bb}` no longer satisfies the template for `\Test` since `1{aa}{bb}` doesn't start with a `2`, as the definition of `\Test` now requires.  So MathJax complains that the "Use of \Test doesn't match its definition", which is exactly what it is supposed to do.

On the other hand, if you do

```
$$
\def\TestA#1#2{{ #1, #2 }}
\def\TestB#1#2{{ #1, #2 }}
\TestA{aa}{bb}
\TestB{aa}{bb}
$$
```

then it will work as you expect it to.

**Comment by bernander** [comment]
Thanks! Sorry for the incorrect report.
