### ISSUE TITLE
No \mathrel spacing next to ampersands in align environment

### ISSUE THREAD

**Issue by JohnTasto** [mathjax/MathJax#2175]
When using a `\mathrel` next to an `&`, the side next to the `&` loses its extra spacing.
```
\begin{align}
  x {\mathrel{R}} y  &&  x \mathrel{R} y  &&  x &    \mathrel{R} y  \\
  x {\mathrel{R}} y  &&  x \mathrel{R} y  &&  x & {} \mathrel{R} y  \\
  x {\mathrel{=}} y  &&  x \mathrel{=} y  &&  x &    \mathrel{=} y  \\
  x {         = } y  &&  x          =  y  &&  x &             =  y  \\
\end{align}
```
![mathrel](https://user-images.githubusercontent.com/5026892/62419801-bbb56b80-b63d-11e9-807f-ea381ac76aca.png)

The first line is how I believe it should be _written_, whereas the second line is how I believe it should _look_, fixed using an empty block. Oddly, when using an `=` (which is already a relation) inside `\mathrel`, it has correct spacing, shown in the third line. The fourth line is just a normal relation without `\mathrel`.

Live example: [JS Bin](https://jsbin.com/saqutiy/edit?html,output)

**Comment by JohnTasto** [comment]
I just noticed `\mathbin` does the same thing, but even more so: One adjacent `&` removes the extra spacing from both sides.

**Comment by dpvc** [comment]
This has to do with the translation of the LaTeX code into the internal MathML.  In order to have a leading operator in a column be treated as though it is in infix position (rather than prefix position), MathJax needs to add an empty element, like you have done in your second line.  MathJax's processing of the `align` environment looks for leading operators and adds in the blank element automatically.  This is based on looking for `<mo>` MathML elements in its internal structure.  In your case, however, the `\mathrel{R}` generates an `<mi>R</mi>` (plus a container that marks it as a REL) rather than an `<mo>, and MathJax misses it.  MathJax should look for the `\mathrel` (and `\mathbin`) container in addition to the `<mo>`, so that needs to be fixed.

The reason that the `\mathbin` loses space on both sides is that when a BIN item appears first in an expression, it is treated by TeX as a unary prefix operator, and there is no space between that and the term that follows.  E.g. `$+x$` should have no space between the `+` and the `x`.

**Comment by dpvc** [comment]
In testsuite:

LaTeXToMathML/environments/issue2175.html
