### ISSUE TITLE
'\frac' nested in a '^{}' display a too short line in chrome

### ISSUE THREAD

**Issue by Sicalxy** [mathjax/MathJax#2178]
### Issue Summary
the line of '\frac' nested in a '^{}' is too short in chrome
 - This won't happen when the font is big, only happened when the font is small.
 - When I check the elements ```span.mjx-line```, I found that if I turn off the ```font-size: 70.7%``` inherited from ```span.mjx-sup```, the line of the \frac wound be suitable.

### Example
For example,
```$$(x + y)^{\frac {a + b + c}{2}}$$```
In **chrome**, the line under "a + b + c" is too short:
![mjx-chrome](https://user-images.githubusercontent.com/25261922/62791928-c1f58d00-bb00-11e9-98b3-bbb76f82c638.png)
However, it displayed correctly in **firefox** even the font is small:
![mjx-firefox](https://user-images.githubusercontent.com/25261922/62792029-f701df80-bb00-11e9-93f1-17c16187b4a7.png)

### Technical details:
MathJax Version: 2.7.5
OS: linux
Browser:
**BAD** Chrome 75.0.3770.142 (64 bit) 
**GOOD** Firefox 68.0.1 (64 bit)

**Comment by dpvc** [comment]
The size of the numerator and denominator are actually what are at fault here, as they should be smaller (as in the Firefox image).  I suspect that the browser's minimum font size is interfering with MathJax being able to set the fonts to their correct (smaller) size.  You might try changing your Chrome preferences to allow a smaller minimum size and see if that works.  Otherwise, you could switch to SVG output, which doesn't use fonts that will be affected by the browser settings.

Unfortunately, MathJax can't force the browser to use font sizes smaller than the minimum set in the browser, and doesn't know that the browser is not respecting the sizes that it has set.

**Comment by Sicalxy** [comment]
Thank you! @dpvc 
## Minimum Font Size
"Chrome - Settings - Customize Fonts - Minimum font size" set to small enough, like ``6``:

![2019-08-11-chrome](https://user-images.githubusercontent.com/25261922/62872427-0d51aa80-bd50-11e9-8ca4-1753f4fb426e.png)

## SVG Output of Mathjax
Use configuration file like ``TeX-MML-AM_SVG`` or ``TeX-AMS-MML_SVG``:

``<script type="text/javascript" src="path-to-MathJax/MathJax.js?config=TeX-MML-AM_SVG"></script>``

or

```javascript
MathJax.Hub.Config({
  jax: ["input/TeX","input/MathML","input/AsciiMath","output/HTML-CSS","output/NativeMML", "output/PreviewHTML"],
  extensions: ["tex2jax.js","mml2jax.js","asciimath2jax.js","MathMenu.js","MathZoom.js", "fast-preview.js", "AssistiveMML.js", "a11y/accessibility-menu.js"],
  TeX: {
    extensions: ["AMSmath.js","AMSsymbols.js","noErrors.js","noUndefined.js"]
  }
});
```

More details: [Combined Configurations](https://docs.mathjax.org/en/latest/config-files.html)
