### ISSUE TITLE
[v3] Incorrect spacing around super- and subscripts

### ISSUE THREAD

**Issue by cebola2** [mathjax/MathJax#2187]
\subset seem to have lost spacing to its right in version 3.00.
An example is line 10 of
https://logrus.math.tecnico.ulisboa.pt/texto/3
Screenshot obtained from Firefox 69.0 on Linux
![Screenshot_2019-09-05 CDI II — TP — Página 3(2)](https://user-images.githubusercontent.com/1136663/64375905-e4ef6000-d01e-11e9-8729-4873dc0fcd19.png)

**Comment by zorkow** [comment]
I can confirm this. It seems to be related to the superscript.
```LaTeX
A\subset\mathbb{R}
```
looks fine, while
```LaTeX
A\subset\mathbb{R}^n
```
or
```LaTeX
A\subset\mathbb{R}^n
```
does not.

**Comment by cebola2** [comment]
This seems to also affect \in

**Comment by dpvc** [comment]
This turns out to be a bad default `texClass` for the base class used for superscripts and subscripts.  It is set to `TEXCLASS.NONE` when it should be `TEXCLASS.ORD`, so the spacing is wrong.  There effect only occurs when the base of the exponent is not just a simple symbol, but something like `\mathbb{...}` or even just `{...}`.

**Comment by dpvc** [comment]
I've made a PR that fixes the issue.
