### ISSUE TITLE
Two weird errors

### ISSUE THREAD

**Issue by felipellrocha** [mathjax/MathJax#2207]
Hi,

I'm trying to use MathJax with a project of mine, and i'm running into two weird issues:

`Misplaced &amp;` when trying to render (with node) something like:
```
      7x      &= 7z  \\
      8x +1y  &= 5z+2w  \\
      1y      &= 3z  \\
      3y      &= 6z+1w
```
and `Undefined control sequence \\newenvironment` when trying to render something like this: `\\newenvironment{linsys}[2][m]{\\begin{array}[#1]{@{}*{#2}{rc}r@{}} }{\\end{array}}`

What am I doing wrong?
```
import mathjax from 'mathjax';

const TeX = require('mathjax-full/js/input/tex.js').TeX;
const HTMLDocument = require('mathjax-full/js/handlers/html/HTMLDocument.js').HTMLDocument;
const liteAdaptor = require('mathjax-full/js/adaptors/liteAdaptor.js').liteAdaptor;
const STATE = require('mathjax-full/js/core/MathItem.js').STATE;

const AllPackages = require('mathjax-full/js/input/tex/AllPackages.js').AllPackages;

const typeset = macros => {
  const tex = new TeX({
    packages: ['base', 'ams'],
    inlineMath: [['\\[', '\\]']],
    inlineMath: [['\\(', '\\)']],
    processEnvironments: true,
  });
  const html = new HTMLDocument('', liteAdaptor(), {InputJax: tex});
  const MmlVisitor = require('mathjax-full/js/core/MmlTree/SerializedMmlVisitor.js')
    .SerializedMmlVisitor;
  const visitor = new MmlVisitor();
  const toMathML = node => visitor.visitTree(node, html);

  toMathML(html.convert(`\\(\n ${macros} \n\\)`, {display: true, end: STATE.CONVERT}));

  return {
    // could clean this up with a bit of currying...
    display: content => {
      return toMathML(html.convert(content, {display: true, end: STATE.CONVERT}));
    },
    inline: content => {
      return toMathML(html.convert(content, {display: false, end: STATE.CONVERT}));
    },
  };
};

const tex = typeset();
const math = tex.display(block.content);
```

**Comment by dpvc** [comment]
The first error is probably because your system needs to be inside some multi-line environment, like `\begin{align}...\end{align}` or a similar environment.  Without that, the ampersands are outside of an alignment, and so are misplaced.  If this math is stored in a javascript string, then you will nee to use `\\\\` in place if `\\` (as you have done in your other example).

The second error is because you have not included the `newcommand` package in the TeX input jax that you created, so it is not defined.  You have loaded `AllPackages`, but have only told TeX to use the `base` and `ams` packages, which don't include `\newenvironment`.  You either need to use `packages: ['base', 'ams', 'newcommand'],` or perhaps `packages: AllPackages,` if you want to have all the packages enabled.

There are a couple of other issues, however.  In 

```
  const tex = new TeX({
    packages: ['base', 'ams'],
    inlineMath: [['\\[', '\\]']],
    inlineMath: [['\\(', '\\)']],
    processEnvironments: true,
  });
```

you have two `inlineMath` entries, so only the second one will be used.  Do you mean the first one to be `displayMath`?

Also, you don't need the `toMathML()` around the first call to `html.convert()`, since that is just to define the macros.  There is no need to waste effort serializing the result.  And you don't need the math delimiters, since you are passing a TeX math string and indicating whether it is display or in-line with the `display` value in the options object.  So

```
html.convert(macros, {display: true, end: STATE.CONVERT});
```

should be sufficient, there.

There is also no need to pass `html` to `visitor.visitTree()` (that was needed in earlier versions, but was dropped some time ago).

Finally, there is no need to import `mathjax`, since you aren't using it (you create the `HTMLDocument` directly rather than call `mathjax.document()`).

**Comment by felipellrocha** [comment]
That solved those issues. I'm now getting this issue:`\\begin{align*} ended with \\end{array}`

When trying to compile this:
```
\newenvironment{linsys}[2][c]{
\begin{array}[#1]{@{}*{#2}}
}{
\end{array}}

\\begin{align*}
  \\begin{linsys}{3}
        x_1 &+  &6x_2  &   &      &=  &9  \\\\
            &   &-x_2  &-  &2x_3  &=  &-7 \\\\
            &   &      &   &3x_3  &=  &9 
   \\end{linsys}
\\end{align*}
```

Any ideas on how to fix that?

**Comment by dpvc** [comment]
Without your modified code, it is hard to tell.  But this works for me:

```
const TeX = require('mathjax-full/js/input/tex.js').TeX;
const HTMLDocument = require('mathjax-full/js/handlers/html/HTMLDocument.js').HTMLDocument;
const liteAdaptor = require('mathjax-full/js/adaptors/liteAdaptor.js').liteAdaptor;
const STATE = require('mathjax-full/js/core/MathItem.js').STATE;

const AllPackages = require('mathjax-full/js/input/tex/AllPackages.js').AllPackages;

const MmlVisitor = require('mathjax-full/js/core/MmlTree/SerializedMmlVisitor.js').SerializedMmlVisitor;
const visitor = new MmlVisitor();
const toMathML = node => visitor.visitTree(node);

const macros = '\\newenvironment{linsys}[2][c]{\\begin{array}[#1]{@{}*{#2}}}{\\end{array}}';
const block = {
  content:
`\\begin{align*}
  \\begin{linsys}{3}
        x_1 &+  &6x_2  &   &      &=  &9  \\\\
            &   &-x_2  &-  &2x_3  &=  &-7 \\\\
            &   &      &   &3x_3  &=  &9 
   \\end{linsys}
\\end{align*}`
};

const typeset = macros => {
  const tex = new TeX({packages: AllPackages});
  const html = new HTMLDocument('', liteAdaptor(), {InputJax: tex});

  if (macros) {
    html.convert(macros, {display: true, end: STATE.CONVERT});
  }

  return {
    display: content => {
      return toMathML(html.convert(content, {display: true, end: STATE.CONVERT}));
    },
    inline: content => {
      return toMathML(html.convert(content, {display: false, end: STATE.CONVERT}));
    },
  };
};

const tex = typeset(macros);
const math = tex.display(block.content);

console.log(math);
```

**Comment by felipellrocha** [comment]
That worked beautifully, thanks!
