### ISSUE TITLE
Question: will MathJax v2 be kept maintained in the future

### ISSUE THREAD

**Issue by drify** [mathjax/MathJax#2215]
Will new issues be accepted, or others need to fork the project and fix the problems themselves?

Is there any schedule of when the old version will retire?

Thank you and sorry for bothering you.

**Comment by dpvc** [comment]
We will continue to update v2 for now.  This will likely be only for bug fixes rather than new features, however, as active development is now concentrated in version 3.  While there is no specific date for retiring v2 at this point, not all features from v2 have been migrated to v3 yet (of the ones planned for migration), so certainly v2 will be maintained at least until that occurs, and for an appropriate time thereafter.
