### ISSUE TITLE
MathJax v3 won't render inside SVG within HTML

### ISSUE THREAD

**Issue by roualdes** [mathjax/MathJax#2229]
I'm trying out the following example, but with no luck.  Any thoughts, tips, and/or solutions would be much appreciated.

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
  </head>
  <body>
    <text>\( \xi \) works.</text>
    <div></div>
    <svg width="150" height="100"> <!-- comment => works -->
      <g transform="translate(0,20)">
        <text>But \( \pi \) doesn't.</text>
      </g>
    </svg> <!-- here too -->
  </body>
</html>
```

My real goal is to include MathJax inside a d3 generated SVG, but the above is the most minimal reproducible example I could develop.

There's some other discussions in similar spirit, none of which contains a solution to the above: 1) issue #394 has a comment that "SVG-in-HTML" should work, but I believe that's what I have above (please correct me if I'm wrong); 2) this [bitbucket](https://bitbucket.org/jason_s/svg_mathjax/src/default/) has a JS enabled copy and paste solution that claims to work for some, but doesn't for me; and 3) there's a [d3 Block](http://bl.ocks.org/larsenmtl/86077bddc91c3de8d3db6a53216b2f47) with a MathJax v2 solution that doesn't work with MathJax v3.

Thanks in advance for your time.

**Comment by dpvc** [comment]
> issue #394 has a comment that "SVG-in-HTML" should work, but I believe that's what I have above (please correct me if I'm wrong)

You haven't done what the issue suggests, which is to use HTML embedded in the SVG using `foreignObject`.  MathJax's CommonHTML output produces HTML, and that can't be inserted directly into an SVG, it must be in an HTML island via `foreignObject`.  If you use that, MathJax will process the math.

The reason the math in the `<text>` element that is outside the SVG is processed is that `<text>` is treated as a custom HTML element in that case, not an SVG element, and since it is part of the HTML tree (not an SVG tree), MathJax can process its math.

Here is an example:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
  </head>
  <body>
    <text>\( \xi \) works.</text>
    <div></div>
    <svg width="300" height="50">
      <foreignObject x="0" y="20" width="300" height="50">
        <div xmlns="http://www.w3.org/1999/xhtml">
        But \( \pi \) doesn't.
        </div>
      </foreignObject>
    </svg>
  </body>
</html>
```

But since the `foreignObject` requires a width and height, you have to compute those yourself.

**Comment by roualdes** [comment]
My mistake.  Thank you for your time and this simple example.
