### ISSUE TITLE
The color of a subscript or superscript followed by math space text is white

### ISSUE THREAD

**Issue by EmanuelPrima** [mathjax/MathJax#2232]
I am using [math.SE site](https://math.stackexchange.com/) and when I try to write `$a_b\text{ c}$` the color of the rendered math is white:

![Example 1](https://user-images.githubusercontent.com/40039900/68078232-83463a80-fdb0-11e9-8a61-0fcf30c501ab.png)

Also in this site: http://rinconmatematico.com/foros/ when I write the code `\(a^b\text{ a}\)` I get the math text `a` but `a^b` is not displayed:

![Example 2](https://user-images.githubusercontent.com/40039900/68078266-50507680-fdb1-11e9-949a-4fd750ded3a9.png)

Can it be solved?

**Comment by EmanuelPrima** [comment]
Whoops, it seems to be a duplicate of issues #2227 and #2228. I'm waiting confirmation.

**Comment by dpvc** [comment]
Yes, this is the same issue.  If you switch to the CommonHTML or SVG output, it will render properly for you.

**Comment by EmanuelPrima** [comment]
> Yes, this is the same issue. If you switch to the CommonHTML or SVG output, it will render properly for you.

Thank you. It is a solution.

I am curious about why HTML-CSS gives the problems. Maybe because the parser is not so good?

**Comment by dpvc** [comment]
> I am curious about why HTML-CSS gives the problems. Maybe because HTML-CSS parser is not so good?

It is not because of the apprising (which is done by the TeX input jax, and is the same in all three output formats).  It is because the HTML-CSS output uses different techniques from the CommonHTML and SVG output, and there is a recent change to Chrome that causes a bug where it allows line breaking to occur in situations where it shouldn't.  In particular, it appears that Chrome incorrectly allows a line break to occur in the non-breaking spaces that HTML-CSS uses for the space in your `\text{}` command.  This causes the `a^b\text{ c}` to cause a line break between the `a^b` and the `c`, and that causes both of the lines to fall outside the clipping region for the expression, so they disappear.  

The reason that the browser thinks a line break is needed is because MathJax has set the widths of the containers it uses for the expressions explicitly to the size needed, but there is a bug in MathJax that causes the container size to not take into account the font scaling factor, and that means the width is too small, and the browser wants to break the math at the space.  That is supposed to be prevented by the CSS ops the container and the fact that the space is a non-breaking space, but Chrome's bug is allowing it.  So there are problems on both sides.

The reason the other two output formats don't have this problem is that the the SVG output is an image format, so no line breaking occurs in that, and the CommonHTML output uses very different techniques for its layout (and gets the width right) so that line breaking isn't an issue.
