### ISSUE TITLE
Tables fail to render in Safari

### ISSUE THREAD

**Issue by entangledloops** [mathjax/MathJax#2251]
For some reason, some of my tables fail to render on my iPad and iPhone.
They work in other mobile browsers on the same devices, as well as desktop browsers (Firefox/Chromium, Windows/Linux).
You can view the source here: [http://entangledloops.com/shootout](http://entangledloops.com/shootout).

I attached a screenshot of what the failed rendering looks like (it only happens for some tables, and exclusively on Safari). If I use Chrome on my iPad, it renders fine.

![IMG_0068](https://user-images.githubusercontent.com/3599701/69893970-8d832800-12cd-11ea-807f-bc9e778009c3.jpg)

**Comment by dpvc** [comment]
The problem is that iOS tries to identify things like dates, telephone numbers, etc., and make links out of them.  You will notice that the seven-digit numbers like 1017072 are shown in blue, which means they have been made into links.  Because MathJax won't process HTML tags, like the `<a>` used for the links, the main that contains those numbers will not be processed.  You will have to fool iOS into not thinking it is a number.  One way would be to use commas, like `1{,}017{,}072`, or maybe even just adding some spaces would do.  You'll have to experiment to see what does it.

**Comment by entangledloops** [comment]
Ah, interesting. Thanks for letting me know.

**Comment by entangledloops** [comment]
For posterity, this fixed it:
`<meta name="format-detection" content="telephone=no">`

[https://stackoverflow.com/questions/226131/how-to-disable-phone-number-linking-in-mobile-safari](https://stackoverflow.com/questions/226131/how-to-disable-phone-number-linking-in-mobile-safari)
