### ISSUE TITLE
`\\` doesn't work directly，is it a feature or bug?

### ISSUE THREAD

**Issue by YohnWang** [mathjax/MathJax#2252]
for example, write 
```
$$ 
f(x)=x+b \\
g(x)=x^2
$$
```
in mathjax2, newline will display,but in mathjax3,it's gone,it must be written like 
```
$$
\begin{gather}
f(x)=x+b \\
g(x)=x^2
\end{gather}
$$
```
So,is it a feature or bug?
Thank you.

**Comment by dpvc** [comment]
> is it a feature or bug?

It is a function that hasn't yet been ported to version 3.  As indicated in the [documentation](http://docs.mathjax.org/en/latest/upgrading/v2.html), not every feature of v2 is available in v3, and some have yet to be converted.  Line breaks are one of the big ones yet to be converted.  So for now, this is "expected behavior".  Line breaking will be added in a future release.
