### ISSUE TITLE
[svg] mis-measuring text size in svg rendering with a font-family on svg container

### ISSUE THREAD

**Issue by dcaillibaud** [mathjax/MathJax#2257]
When displaying svg MathJax rendering in a container having a different font-family than body's one, measureText is doing some mistakes.

With a LaTeX string composed by some text then a math expression :
- if **body is serif & svg container sans-serif**, math expression is too far to the left => **text is overriding math**
- if body is sans-serif & svg container serif, math expression is too far to the right => too much space between text and math

see this simple example https://www.mathgraph32.org/mathjaxBug_2019-12-06.html

html/css/js source : 

```
<!DOCTYPE html>
<html>
<head>
  <title>MathJax mis-measuring</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
  <style type="text/css">
    body {
      font-family: serif;
      font-size: 18px;
    }
    #errors p {
      color: #a00;
      border: #600 solid 1px;
      margin: 0.5em;
      padding: 0.5em 1em;
    }
    #small {
      font-family: sans-serif;
      font-size: 12px;
    }
    #big {
      font-family: Roboto;
      font-size: 24px;
    }
  </style>
</head>
<body>

<ul>This page show a Mathjax bug about text size in svg rendering, leading to text overriding math expression
  <li>font-family and font-face are inherit, but text size detection is failing a bit, as you can see with this sample where math override text, « : - » becomes ÷ because math is displayed a little bit too far to the left (text block override math block)<br>
    If you swap serif/sans-serif (sans-serif on body and serif on #small), math is displayed too far to the right in serif case (too much space and no more overriding)
  </li>
  <li>svg.mtextInheritFont: true seems ok if done before MathJax loading but not after, already in this <a href="https://github.com/mathjax/MathJax/issues/2189">issue</a> (cf comments in source code, to reproduce it comment the config before loading and uncomment the one after loading)</li>
</ul>

<p>LaTeX string, change it and rendering will occurs on blur</p>
<textarea id="latex" cols="80" rows="5">\text{some text before math : }-\frac{\sqrt{2}}{2}</textarea>

<div id="errors"></div>

<div id="normal">
  <p>normal (as body : serif), MathJax svg embed in our svg</p>
  <svg id="svgnormal" width="800" height="100"></svg>
  <p>And raw MathJax output</p>
  <div></div>
</div>

<hr>
<div id="small">
  <p>small sans-serif, MathJax svg embed in our svg</p>
  <svg id="svgsmall" width="800" height="100"></svg>
  <p>And raw MathJax output</p>
  <div></div>
</div>

<hr>
<div id="big">
  <p>big Roboto, MathJax svg embed in our svg</p>
  <svg id="svgbig" width="800" height="100"></svg>
  <p>And raw MathJax output</p>
  <div></div>
</div>

<script type="application/javascript">
  // if this config is done after loading, mtextInheritFont: true is ignored by tex2svgPromise
  // can be https://github.com/mathjax/MathJax/issues/2189
window.MathJax = {
  svg: {
    // @see http://docs.mathjax.org/en/latest/options/output/svg.html#the-configuration-block
    mtextInheritFont: true
  }
}
</script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js"></script>

<script type="application/javascript">
/* global MathJax */
/**
 * log & show error
 * @param {Error} error
 */
function showError (error) {
  console.error(error)
  const errors = document.getElementById('errors')
  const p = document.createElement('p');
  const txt = document.createTextNode(error.message)
  p.appendChild(txt)
  errors.appendChild(p)
  p.addEventListener('click', () => errors.removeChild(p))
}

/**
 * Render the latex string in our 3 svg
 * @param {string} latex
 */
function render (latex) {
  // empty errors
  const errors = document.getElementById('errors')
  while (errors.hasChildNodes()) errors.removeChild(errors.lastChild)
  // typeset latex
  MathJax.tex2svgPromise(latex).then((html) => {
    svgs.forEach(svg => {
      // empty parent svg
      while (svg.hasChildNodes()) svg.removeChild(svg.lastChild)
      // get MathJax svg
      const jaxSvg = html.cloneNode(true).firstElementChild
      // and rendering it in our svg
      svg.appendChild(jaxSvg)
    })
    // same rendering directly mathjax html in parent
    containers.forEach(container => {
      container.removeChild(container.lastChild)
      container.appendChild(html.cloneNode(true))
    })
  }).catch(showError)
}

/* Mathjax config
MathJax.config = {
  svg: {
    // @see http://docs.mathjax.org/en/latest/options/output/svg.html#the-configuration-block
    // changing this here, after MathJax Loading, doesn't change anything on rendering (serif for everybody)
    mtextInheritFont: true
  }
} /* */

const ids = ['normal', 'small', 'big']
// ours svg
const svgs = ids.map(suffix => document.getElementById(`svg${suffix}`))
// and containers
const containers = ids.map(id => document.getElementById(id))

// a listener on latex change
document.getElementById('latex').addEventListener('blur', event => render(event.target.value))

// initial latex rendering on load
render(document.getElementById('latex').value)
</script>
</body>
</html>
```

**Comment by dpvc** [comment]
I have finally had the chance to look into your situation more closely, for potentially including a fix in v3.0.2.  It turns out, however, that the issue is "expected behavior" in the sense that you are using both `mtextInheritFont: true` and `MathJax.tex2svgPromise()` to create the your output.  Here's why:  `MathJax.tex2svgPromise()` does not know where you are going to insert the resulting SVG, and so it doesn't know the surrounding font.  So when it needs to determine the size of the `\text{}` string that you are using during the layout process, it uses the font of the body element (as the best guess it can make).  If you insert the SVG into a location that has a different font, that measurement may be incorrect, as you have found out.

Without better contextual information, there is not much MathJax can do about this, as no matter *what* measurement was made, it would be incorrect in some settings where the surrounding font is different.  One can not really expect that changing the surrounding font will result in accurate positioning when the position was computed for a different font.

The `mtextInheritFont` option probably needs to be changed not to inherit from the surroundings, but to provide a fixed font to use fort the text instead.  That way MathJax can determine the correct size regardless of the placement of the resulting SVG (or HTML in the case of CommonHTML output).

As for the configuration issue, changing the `MathJax.config` values after MathJax has loaded is not a supported use-case.  It may work for some options, but definitely will not work for others.  For example, the input and output options are passed to the input and output jax when they are created, and they use internal copies of the options from then on, so changing the `MathJax.config` object will not affect those options.

In any case, by doing

```
MathJax.config = {
  svg: {
    mtextInheritFont: true
  }
};
```

after loading MathJax, you not only set the `mtextInheritFont` value, but also remove all other svg output options (since you are replacing the svg block with the new one).  If you were to check the value of `MathJax.config.svg` before this assignment, you would see that there were other values in that object (defaults that have been set during MathJax's startup).  By deleting those, you would cause MathJax to malfunction; but fortunately, MathJax no longer uses `MathJax.config.svg` once the output jax is set up (unless you were to ask for it to be recreated), and so this didn't cause problems.  But it also doesn't affect the configuration in use.

In any case, the fix (which is to deprecate `mtextInhertiFont` and institute something like `mtextFont` instead) will need to wait until a later release.

**Comment by dpvc** [comment]
PS, instead of converting to SVG outside of the page, had you inserted the TeX into the page at the desired locations and typeset them in place, the inherited font would have worked as you expected, and the measurements would have been correct in each case.  Of course, it would have been a slightly different SVG in each case.

**Comment by dcaillibaud** [comment]
Thanks for digging this and for the detailed and usefull explanations.
