### ISSUE TITLE
Latex comments are not always properly ignored

### ISSUE THREAD

**Issue by Sjlver** [mathjax/MathJax#2271]
Latex comments are not always properly ignored like they should be. Consider the following example:

```
$$
\renewcommand{\foo}{\mathop{\rm foo}}
%\renewcommand{\}{}
$$

Hi $\foo$
```

Entering this at https://www.mathjax.org/#demo produces this result:

<img width="1070" alt="Screenshot 2019-12-19 at 20 47 45" src="https://user-images.githubusercontent.com/72059/71204649-e75d8900-22a0-11ea-8b6f-b6cb00f4d2b5.png">

Changing the second line to `%\renewcommand{}{}` (removing the backslash) works:

![image](https://user-images.githubusercontent.com/72059/71204730-1e339f00-22a1-11ea-9259-6b04cee07a31.png)

Note that the line is actually commented out (i.e., starts with `%`)

**Comment by dpvc** [comment]
The issue is caused by the fact that MathJax tries to find the math delimiters before processing any of the contents, and requires balanced braces as it does so.  Since the bracing is not balanced in `\renewcommand{\}{}` (since `\}` acts as a control sequence, there is no close brace for the open break just before it), this means that MathJax can't find the close `$$` because there is still an open brace that is unmatched.

The delimiter matching doesn't currently take comments into account, but it probably should.
