### ISSUE TITLE
`min-width`is not changed for the formulas `\begin{equation}...\end{equation}`

### ISSUE THREAD

**Issue by OlgaRedozubova** [mathjax/MathJax#2280]
For `\begin{equation}...\end{equation}` the size of the container is not changed regardless of the value containerWidth

```
\begin{equation}
\begin{aligned}
\mathbb{P}\left[X_{n+1}=i_{n+1} | B\right]=& \mathbb{P}\left[X_{n+1}=i_{n+1} | B \cap A_{1}\right] \mathbb{P}\left[A_{1} | B\right] \\ &+\mathbb{P}\left[X_{n+1}=i_{n+1} | B \cap A_{2}\right] \mathbb{P}\left[A_{2} | B\right] \\=& \mathbb{P}\left[X_{n+1}=i_{n+1} | B \cap\left\{X_{n}=i_{n}\right\}\right] \mathbb{P}\left[X_{n}=i_{n} | B\right] \\ &+\mathbb{P}\left[X_{n+1}=i_{n+1} | B \cap\left\{X_{n}=-i_{n}\right\}\right] \mathbb{P}\left[X_{n}=-i_{n} | B\right] 
\end{aligned}
\end{equation}
```

But for this formula everything works

```
\begin{aligned}
\mathbb{P}\left[X_{n+1}=i_{n+1} | B\right]=& \mathbb{P}\left[X_{n+1}=i_{n+1} | B \cap A_{1}\right] \mathbb{P}\left[A_{1} | B\right] \\ &+\mathbb{P}\left[X_{n+1}=i_{n+1} | B \cap A_{2}\right] \mathbb{P}\left[A_{2} | B\right] \\=& \mathbb{P}\left[X_{n+1}=i_{n+1} | B \cap\left\{X_{n}=i_{n}\right\}\right] \mathbb{P}\left[X_{n}=i_{n} | B\right] \\ &+\mathbb{P}\left[X_{n+1}=i_{n+1} | B \cap\left\{X_{n}=-i_{n}\right\}\right] \mathbb{P}\left[X_{n}=-i_{n} | B\right] 
\end{aligned}
```

![screenshot-localhost_3000-2020 01 02-12_04_27 (1)](https://user-images.githubusercontent.com/32493105/71673237-ee949480-2d80-11ea-8c2c-e076302db1bc.png)

I have also tried to set `docTeX.options.OutputJax.minwidth = ..`
But I see that this value is re attributed https://github.com/mathjax/MathJax-src/blob/master/ts/output/svg.ts#L265

Please, tell me how I can change the container's width in this case.

**Comment by OlgaRedozubova** [comment]
Thank you so much for your reply.

I use the `tags: "ams"` option. In the previous screenshot, the numbering is not visible since it is hiding.
I want to clarify in the example below, it turns out that the `min-width` for the formulas ` \begin {equation} ... \end {equation}` exceeds the width of the container
because of this, part of the formula is hidden.
Is there a way to reduce the `min-width` for the formulas `\begin{equation} ... \end{equation}`?

![ezgif com-video-to-gif (55)](https://user-images.githubusercontent.com/32493105/71692578-f53bff80-2db2-11ea-9918-062e4469b710.gif)

```
\begin{equation}
\begin{aligned}
\mathbb{P}\left[X_{n+1}=i_{n+1} | B\right]=& \mathbb{P}\left[X_{n+1}=i_{n+1} | B \cap A_{1}\right] \mathbb{P}\left[A_{1} | B\right] \\ &+\mathbb{P}\left[X_{n+1}=i_{n+1} | B \cap A_{2}\right] \mathbb{P}\left[A_{2} | B\right] \\=& \mathbb{P}\left[X_{n+1}=i_{n+1} | B \cap\left\{X_{n}=i_{n}\right\}\right] \mathbb{P}\left[X_{n}=i_{n} | B\right] \\ &+\mathbb{P}\left[X_{n+1}=i_{n+1} | B \cap\left\{X_{n}=-i_{n}\right\}\right] \mathbb{P}\left[X_{n}=-i_{n} | B\right] 
\end{aligned}
\end{equation}
```
```
\begin{equation*}
\begin{aligned}
\mathbb{P}\left[X_{n+1}=i_{n+1} | B\right]=& \mathbb{P}\left[X_{n+1}=i_{n+1} | B \cap A_{1}\right] \mathbb{P}\left[A_{1} | B\right] \\ &+\mathbb{P}\left[X_{n+1}=i_{n+1} | B \cap A_{2}\right] \mathbb{P}\left[A_{2} | B\right] \\=& \mathbb{P}\left[X_{n+1}=i_{n+1} | B \cap\left\{X_{n}=i_{n}\right\}\right] \mathbb{P}\left[X_{n}=i_{n} | B\right] \\ &+\mathbb{P}\left[X_{n+1}=i_{n+1} | B \cap\left\{X_{n}=-i_{n}\right\}\right] \mathbb{P}\left[X_{n}=-i_{n} | B\right] 
\end{aligned}
\end{equation*}
```

**Comment by dpvc** [comment]
Equations that are too wide for the container do extend past the right-hand side of the container.  Automatic line breaking can help in some cases but (as mentioned) that is not yet ported to version 3, and it is not very effective with tables (which is how the `aligned` environment is implemented), so it would not be very helpful here even so.

As I mentioned, the minimum width is the actual minimum required size for the expression and its label (when the equation is centered), and it can not be reduced without damaging the rendering.  The second example you give doe not contradict that because it has no label.  If the container we a bit less wide, that one would extend beyond the right-hand side as well.

The only option to get a reduced is to reduce the size of the font surrounding the expression.  You could do that by adding a `span` or `div` that has CSS that reduces the font size.  E.g.,

```
<div style="font-size: 90%">
\begin{equation}
\begin{aligned}
\mathbb{P}\left[X_{n+1}=i_{n+1} | B\right]=& \mathbb{P}\left[X_{n+1}=i_{n+1} | B \cap A_{1}\right] \mathbb{P}\left[A_{1} | B\right] \\ &+\mathbb{P}\left[X_{n+1}=i_{n+1} | B \cap A_{2}\right] \mathbb{P}\left[A_{2} | B\right] \\=& \mathbb{P}\left[X_{n+1}=i_{n+1} | B \cap\left\{X_{n}=i_{n}\right\}\right] \mathbb{P}\left[X_{n}=i_{n} | B\right] \\ &+\mathbb{P}\left[X_{n+1}=i_{n+1} | B \cap\left\{X_{n}=-i_{n}\right\}\right] \mathbb{P}\left[X_{n}=-i_{n} | B\right] 
\end{aligned}
\end{equation}
</div>
```

but this has to be done by hand (MathJax doesn't have an automatic way to do that).

Alternatively, you could arrange for the `div` to have `overflow: scroll` so that it can be scrolled to the right or left to expose the rest of the equation.
