### ISSUE TITLE
postProcess error while rendering math content in web page 

### ISSUE THREAD

**Issue by mba8487143** [mathjax/MathJax#2302]
Here i am using math jax to render data on web page but i am en-counting an error  of HTML-CSS postProccess
![matherror](https://user-images.githubusercontent.com/15572239/72893625-4e0c1180-3d3b-11ea-8ea5-7910c6dd03f4.png)

**Comment by dpvc** [comment]
Your page (given in the URL in your screen shot) contains MathJax output, and that is what is causing the problems for you.  MathJax uses `id` attributes to identify the elements that it creates, and because you have copied those ids from a previous run of MathJax, there are already elements in the page that have the ids that MathJax needs to use to create its new output.  That makes the page invalid (ids must be unique), and when MathJax tries to look up an element by its id, it will get the one that was in the page originally rather than the new one that it created for the output.  Because MathJax stores additional information (that is not in the element attributes, and hence not saved in your original HTML document), it crashes when it looks for that information an it isn't there (it's only on the newly created elements, but because the ids are duplicated, it gets the elements originally in the page that don't have the additional data).

So you should not store previous MathJax output and run MathJax on that a second time, but rather should store the original TeX or MathML and have MathJax reprocess it.  Either that or keep the processed math and don't run MathJax again.  Note, however, that the HTML-CSS output is browser dependent, so the output that one user gets may not work with other users.  If you want to store MathJax output for reuse, you should use CommonHTML output or SVG output instead, as these are browser independent.

In addition, there are several other issues with your page.  First, you are using a very old version (2.6.1) of MathJax (nearly 4 years old).  The current version is 2.7.7.  This version doesn't crash on your page, though it also doesn't remove the original MathJax rendering, so you will see every equation twice.  (If you moved the original MathJax output in the `MathJax_Preview` span that precedes it, then it would be removed when MathJax runs and the new output would supersede the saved output.)

There are a number of problems with your MathJax configuration.  First, you re configuring AsciiMath, though you aren't loading the AsciiMath input jax (the `TeX-AMS-MML_HTMLorMML` configuration loads TeX and MathML input formats, bit not AsciiMath).  Then you have configured `\(` and `\)` delimiters for **both** inline and display math (it can only be used for one or the other).  Also, if you want to support earlier versions of IE, you should not have extra commas before closing braces.  Finally, the MathJax configuration should come **before** loading MathJax, so you should do something like

```
    <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        CommonHTML': {
          mtextFontInherit: true
        },
        tex2jax: {
          inlineMath: [
            ['$$', '$$'],
            ['\\(', '\\)']
          ],
          displayMath: [
            ['$$$', '$$$'],
            ['\\[', '\\]']
          ],
          processEscapes: false
        }
      });
   </script>
   <script src="https://cdn.jsdelivr.net/npm/mathjax@2.7.7/unpacked/MathJax.js?config=TeX-AMS_CHTML"></script>
```
