### ISSUE TITLE
Danish characters er not generated in correct size

### ISSUE THREAD

**Issue by TubsDK** [mathjax/MathJax#2305]
On PC the following $$(2 \cdot (\text{det føæårste led}\cdot \text{det andet led}))$$ 

generates the special danish characters øæå in a different size eg taken from https://www.mathjax.org/#demo 

![image](https://user-images.githubusercontent.com/8876269/73068707-28eae080-3eac-11ea-8a0f-953c508ab348.png)

On mac sizes are generated correctly.

**Comment by dpvc** [comment]
The MathJax fonts only include a limited number of glyphs, and the Danish characters that you cite are not among them.  So when MathJax encounters them, it has to rely on the system fonts to provide them.  The font used by the system may not match the MathJax fonts very well, and that is the case here.  MathJax tries to scale the system font to match the height of the lower-case letters, but that relies on ex-size of the font in use surrounding the math.  Not all fonts have the ex-height properly set, and MathJax's ability to determine the ex-size is only approximate, so small differences like this are possible.  The fact that Mac version works better than the PC version is probably due to the fact that a different font is used in each case, or the size of the surrounding font is different.

**Comment by soegaard** [comment]
The size difference is rather large:

![image](https://user-images.githubusercontent.com/461765/113548593-1744b300-95f0-11eb-8c46-60ffb8b9e9aa.png)

Is there a way to lobby for Danish characters to be added to the MathJax charset?

**Comment by dpvc** [comment]
You can probably improve the output, but it is hard to tell you how, since you haven't included your configuration, or any information about how you are using MathJax.  E.g., which output processor are you using?  Are you running Mathjax in the browser, or pre-processing on the server?  If in the browser, are you calling `MathJax.typeset()` or `MathJax.tex2chtml()` or `MathJax.tex2svg()`?  Have you tried setting `mtextInheritFont: true` in the output jax's configuration block?

Without these details, it is difficult to advise you how to proceed.
