### ISSUE TITLE
Multiple \sum not rendered

### ISSUE THREAD

**Issue by oonid** [mathjax/MathJax#2306]
Hi,

I'm using Mathjax 2.7.7 with markdown,
I have no problem with \sum until I have to write two sums.

This one rendered correctly:
```
$-\sum_{i=1}^m y\_iln(p\_i) + (1 - y\_i)ln(1 - p\_i)$
```

This one was not rendered, I have tried to give space between \sum but still not rendered:
```
$-\sum_{i=1}^n\sum_{j=1}^m y\_{ij} ln(p\_{ij})$
```

I looked at some examples on SO and SE, but found the syntax quite similar.
What syntax should I try next?

thank you.

**Comment by dpvc** [comment]
Because many versions of Markdown uses underscores to indicate italics, when you get the second underscore, that triggers Markdown to insert `<emph>` or `<i>` tags into the document.  MathJax will not process math if it contains HTML tags, so that prevents your expression from being rendered.

Notice that you have used `\_` for the subscripts for `y` and `p` in your expression.  If you use `\_` for your `\sum` operations as well, that should do the trick.

See the documentation on [interactions with content-management systems](http://docs.mathjax.org/en/latest/input/tex/html.html#interactions-with-content-management-systems) for more detail.

**Comment by oonid** [comment]
yes, it does the trick.
thank you for the reference, I have read the reference before when looking for the subscripts, not expect that have the same behavior for the \sum 's subscripts.
I'm closing the issue. thank you.
