### ISSUE TITLE
Font size in display:none div on mobiles

### ISSUE THREAD

**Issue by Ved-vampir** [mathjax/MathJax#2314]
Hi!
I'm using MathJax v3 for some data in hidden blocks. On computer all is ok, behavior in usual and hidden block is similar. But on mobile (android chrome, for example) font size of mathematics in hidden blocks is smaller. I found such problem here https://github.com/mathjax/MathJax-docs/wiki/Dealing-with-display:none , but I cannot move this solution to v3. Help, please, what I can do here. Example you can see here http://kornev-school.ru/g7pervpr.html , if you open hidden block by clicking "Показать решение" on mobile, you'll see this problem.
Thanks

**Comment by dpvc** [comment]
MathJax can't measure the surrounding font when the math appears in a container having `display:none` (as described in the link you found about that).  So your results may be poor (as you have found) if you use math in such blocks.  The link you gave suggests alternatives to using `display:none` that allow mathJax to properly size the math (using `visibility:hidden`), so that is one possible solution.  Another would be to set the `matchFontHeight:false` in the configuration for the MathJax output renderer you are using.  For example

```
MathJax = {
  chtml: {
    matchFontHeight: false
  }
}
```

This will cause MathJax not to scale the output to try to match the surrounding font.

It may also help to include

```
<meta name="viewport" content="width=device-width">
```

in your document `<head>`, as that can improve the results in some instances.
