### ISSUE TITLE
[svg] Munderover not rendered correctly

### ISSUE THREAD

**Issue by WoodcuttingLVL99** [mathjax/MathJax#2317]
Using MathJax 3 MML-SVG and munderover gets rendered incorrectly. MathJax 2.7.6 does not have the same issue. It's because the mstyle has mathsize of 140%.
Result link: https://i.ibb.co/hDp5d9P/Capture.png 
and source MathML:

`<math xmlns="http://www.w3.org/1998/Math/MathML" id="mml_m11" overflow="scroll"><mrow> <mi>T</mi> <mi>E</mi> <msub> <mi>R</mi> <mrow> <mi>H</mi> <mi>F</mi> </mrow> </msub> <mo>=</mo> <munderover> <mstyle mathsize="140%" displaystyle="true" stretchy="false"> <mo>∑</mo> </mstyle> <mrow> <mi>n</mi> <mo>=</mo> <mn>1</mn> </mrow> <mi>N</mi> </munderover> <mi>E</mi> <msub> <mi>R</mi> <mrow> <mi>A</mi> <mi>L</mi> <mo>,</mo> <mi>H</mi> <mi>F</mi> <mo>,</mo> <mi>n</mi> </mrow> </msub> <mo>+</mo> <munderover> <mstyle mathsize="140%" displaystyle="true" stretchy="false"> <mo>∑</mo> </mstyle> <mrow> <mi>m</mi> <mo>=</mo> <mn>1</mn> </mrow> <mi>M</mi> </munderover> <mi>E</mi> <msub> <mi>R</mi> <mrow> <mi>E</mi> <mi>L</mi> <mi>V</mi> <mo>,</mo> <mi>H</mi> <mi>F</mi> <mo>,</mo> <mi>m</mi> </mrow> </msub></mrow></math>`

**Comment by dpvc** [comment]
OK, it looks like the scaling is not fully being taken into account.  It does work if you use

    <mo mathsize="140%">∑</mo>

rather than

    <mstyle mathsize="140%" displaystyle="true" stretchy="false"> <mo>∑</mo> </mstyle>

if that is possible for you.  If not, it might be possible to write a MathJax MathML input pre-filter that moves the `mathsize` from the `mstyle` tag to the contained `mo` automatically until this bug is fixed.

Also note that it is an error only in the SVG output, so an alternative would be to switch to the CommonHTML output, if that is possible.
