### ISSUE TITLE
When using `mtextInheritFont: true` setting, rendering in browser and node app differs

### ISSUE THREAD

**Issue by OlgaRedozubova** [mathjax/MathJax#2329]
For node app when using `mtextInheritFont: true` setting after `\text{...}`, additional spacing is added. 

![screenshot-github com-2020 02 12-14_52_56](https://user-images.githubusercontent.com/32493105/74346682-99ed2c00-4db8-11ea-96f8-e992da8a5b85.png)

Tex:  `\forall a \in \mathcal{N} \text{ if }a\neq 0, \text{ then } \exists a ^{-1}\in \mathcal{N} \ni`

Please let me know how I can solve this problem, as I need to use the setting and get the same result for browser and node app.

**Comment by OlgaRedozubova** [comment]
After adding `mtextInheritFont: true ` option, the spacing after `\text{ some text }` is calculated incorrectly.

Using `mtextInheritFont: true`
For browser - spacing in the first formula is increased, and in the second one - decreased.

![screenshot-localhost_3000-2020 02 13-11_15_57 (1)](https://user-images.githubusercontent.com/32493105/74428156-23f0cf80-4e61-11ea-8779-69ea9e530f7d.png)

For node apps - spacing for both formulas are increased too much

![screenshot-localhost_3000-2020 02 13-11_18_59](https://user-images.githubusercontent.com/32493105/74428215-3d921700-4e61-11ea-84d0-b8e08e8b81e0.png)

Without `mtextInheritFont` option - `तऀ` symbol is divided into 2 parts but in browser and node app spacing in correct.

![screenshot-localhost_3000-2020 02 13-11_14_04](https://user-images.githubusercontent.com/32493105/74428266-54d10480-4e61-11ea-94ca-7cba22c257f7.png)

Looking forward to getting your answer.

**Comment by dpvc** [comment]
For characters that aren't in MathJax's fonts (like the `तऀ` symbol), or the `\text{}` strings when `mtextInheritFonts` is true, MathJax doesn't have the bounding box information, and so doesn't know the size of the characters.  In the browser, MathJax can measure the width of the string using the browser's `getBoundingClientRect()` function, or the `offsetWidth` property on an appropriate container for the string.  But in node applications, those functions aren't available.  The LiteDOM does not have access to those measurements, and so has to make an estimate.  That is based purely on the number of characters in the string, and is likely to be incorrect, as in your case.  Without access to actual font information, there is little MathJax can do to get the actual widths properly.

One option would be to use something like Puppeteer (an automated headless Chromium) to do the conversion, since that contains a real browser DOM that can do the measurements properly.  For example, if you

```
npm install puppeteer
npm install mathjax-full
```

then the node appliaction

```
const puppeteer = require('puppeteer');

//
//  Get the TeX string to process
//
const math = process.argv[2] ||
      '\\forall a\\in\\mathcal{N} \\text{ if } a\\neq 0, \\text{ then } \\exists a^{-1}\\in\\mathcal{N} \\ni';

//
//  The HTML page for puppeteer that loads MathJax.
//
const html = `
<!DOCTYPE html>
<html>
<head>
<title>Testing Puppeteer</title>
<script>
const mjReady = new Promise((ok, fail) => {
  window.MathJax = {
    svg: {
      mtextInheritFont: true
    },
    startup: {
      pageReady() {
        MathJax.startup.defaultPageReady().then(ok).catch(fail);
      }
    }
  }
});
</script>
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js"></script>
</head>
<body>
</body>
</html>
`;

//
//  Open the HTML page above in Puppeteer and use MathJax in that page
//  to convert the TeX to SVG, and print the result.
//
(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto(`data:text/html,${encodeURIComponent(html)}`);
  await page.goto(`file://${process.cwd()}/test.html`);
  const result = await page.evaluate((math) => {
    return mjReady.then(() => MathJax.tex2svg(math).firstChild.outerHTML);
  }, math);
  console.log(result.replace(/\&nbsp;/g, '\&#xA0;'));
  await browser.close();
})();
```

would convert a TeX string to an SVG string handling unknown characters and inherited fonts in the same way that the (Chrome) browser does. You may also need to set the body font in the document above to better match your situation.

Note, however, that unknown characters may act differently on different browsers and OSes, since they rely on the fonts installed on the user's system, so you might not get the same results from this for all users.  Pre-processing unknown or inherited fonts is fragile at the moment.

**Comment by dpvc** [comment]
Also, note that there are some bugs with `mtextInheritFont: true` in v3 in both CommonHTML and SVG output.  See #2257 and #2187.

**Comment by pdmosses** [comment]
> Also, note that there are some bugs with `mtextInheritFont: true` in v3 in both CommonHTML and SVG output. See #2257 and #2189.

`mtextInheritFont: true` in v3 in SVG output also upsets the scrolling to labelled equations, targeting the baseline instead of the top of the equation. (This doesn't happen in CHTML output.)

For example, add this option to the [equation-refs demo](https://mathjax.github.io/MathJax-demos-web/equation-refs.html) and change the output to SVG, then click on a link to `(1)`: only the lower part of the equation is visible (using Safari and Firefox).

**Comment by dpvc** [comment]
> `mtextInheritFont: true` in v3 in SVG output also upsets the scrolling to labelled equations

OK, I can reproduce that, and will investigate.  I am going to start a new issue for this problem, since it is not related to this issue.
