### ISSUE TITLE
Unknown node type "body" when compiling MathML in v3.0.1

### ISSUE THREAD

**Issue by hubgit** [mathjax/MathJax#2330]
Using `mathjax-full@3.0.0` it was possible to use this code to convert MathML to SVG:

```js
import { MathML } from 'mathjax-full/js/input/mathml'
import { SVG } from 'mathjax-full/js/output/svg'
import { HTMLAdaptor } from 'mathjax-full/js/adaptors/HTMLAdaptor'
import { HTMLDocument } from 'mathjax-full/js/handlers/html/HTMLDocument'

const doc = new HTMLDocument(document, new HTMLAdaptor(window), {
  InputJax: new MathML(),
  OutputJax: new SVG(),
})

const svg = doc.convert(`<math xmlns="http://www.w3.org/1998/Math/MathML"><mrow><mi>A</mi><mo>=</mo></mrow></math>`)

console.log(svg.innerHTML)
```

Using `mathjax-full@3.0.1` an error is thrown when using the same code:

```
Uncaught Error: Unknown node type "body"
    at MathMLCompile.error (MathMLCompile.ts:320)
    at MathMLCompile.makeNode (MathMLCompile.ts:125)
    at MathMLCompile.compile (MathMLCompile.ts:95)
    at MathML.compile (mathml.ts:145)
    at HTMLMathItem.AbstractMathItem.compile (MathItem.ts:327)
    at Object.renderMath (MathDocument.ts:167)
    at RenderList.renderConvert (MathDocument.ts:211)
    at HTMLMathItem.AbstractMathItem.convert (MathItem.ts:319)
    at HTMLDocument.AbstractMathDocument.convert (MathDocument.ts:633)
```

It seems to go wrong around this line in `MathDocument`:

```
mitem.start.node = this.adaptor.body(this.document)
```

which sets `mitem.start.node` to the `body` of this.document, which suggests that [this commit](https://github.com/mathjax/MathJax-src/commit/35eb4bbc049b7692513fdb0036ca1250c70a145c) might be to blame.

**Comment by dpvc** [comment]
Thanks for the report.  I can reproduce the problem, and will check into it.

**Comment by dpvc** [comment]
Your are right, the setting of `math.start.node` turns out to be the culprit.  For the MathML input jax, that node usually points to the MathML node in the document, and its absence meant that the MathML was in `math.math` as a string that needed to be parsed in order to get the MathML tree.  Setting the start node prevented that parsing from being performed, and its content was taken as the MathML itself (the body not that is reported in the error).  The start node was being set appropriately for TeX strings, but not MathML strings.

If you use

``` javascript
  InputJax: new MathML({forceReparse: true}),
```

that should get around the problem for now.

**Comment by dpvc** [comment]
I've created a pull request to resolve the issue.
