### ISSUE TITLE
valign not working on mglyph

### ISSUE THREAD

**Issue by wspilot** [mathjax/MathJax#2360]
I am using an svg (also tried an .png) as mglyph and it has to align with the descender line of the preceding character. Whatever value or unit I use, the glyph stays on the base line.
Ubuntu 19.10
Firefox 73.0.1
Chrome Version 80.0.3987.87 (Official Build) (64-bit)
See attached html and svg file. Note: I had to rename the files toto .txt because .svg and .html are not accepted as type. Please remove the .txt extension.
[bugTest0.svg.txt](https://github.com/mathjax/MathJax/files/4266759/bugTest0.svg.txt)
[bugtest0.html.txt](https://github.com/mathjax/MathJax/files/4266765/bugtest0.html.txt)

**Comment by dpvc** [comment]
OK, it turns out that the `mglyph` code is looking for `voffset` rather than `valign`, and that the alignment direction is reversed.  Not sure how that happened, but thanks for reporting the issue.  I will fix it in the next release.

In the meantime, you can use the following code

``` html
    <script>
      MathJax = {
        startup: {
          ready() {
            MathJax.startup.defaultReady();
            MathJax.startup.input[1].postFilters.add((args) => {
              args.data.walkTree((node) => {
                if (node.isKind('mglyph')) {
                  const attributes = node.attributes;
                  if (attributes.isSet('valign')) {
                    const y = attributes.get('valign');
                    attributes.set('voffset', y.charAt(0) === '-' ? y.slice(1) : '-' + y);
                  }
                }
              });
            });
          }
        }
      }
    </script>
```

to post-filter the MathML input to look for `mglyph` elements and convert the `valign` attributes to `voffset` (switching the direction of the shift so that it displays properly).

**Comment by dpvc** [comment]
I've made a pull request to resolve the issue.

**Comment by wspilot** [comment]
FYI
I just found out that it does work in V 2.7.5

**Comment by dpvc** [comment]
Yes, the error occurred during the v3 rewrite.  The name of the attribute was incorrectly entered in the v3 code.
