### ISSUE TITLE
Is there a way to support "[latex]...[/latex]"?

### ISSUE THREAD

**Issue by zhaokaifengcom** [mathjax/MathJax#2361]
Before I use MathJax on my blog, I am using a plugin to show math formulas and the plugin need use "[latex]...[/latex]" to identity. Now, MathJax works well on my site, but as long as I disable the plugin, all the math formulas that write in "[latex]...[/latex]" will fail.
What should I do to make MathJax support "[latex]...[/latex]"? thank you.

**Comment by dpvc** [comment]
It is not clear if you want `[latex]...[/latex]` to be in-line or displayed math, but I'm assuming in-line math, and that `[Latex]...[/Latex] will be displayed math.

If you are using version 3 of MathJax, then use

``` html
<script>
MathJax = {
  tex: {
    inlineMath: [['[latex]', '[/latex]'], ['\\(', '\\)']],
    displayMath: [['[Latex]', '[/Latex]'], ['$$', '$$'], ['\\[', '\\]']]
  }
};
</script>
```

 in order to add these delimiters to the standard ones.  If you already have other configuration settings, you will need to merge this into your existing configuration.

If you are using version 2, use

``` html
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  tex2jax: {
    inlineMath: [['[latex]', '[/latex]'], ['\\(', '\\)']],
    displayMath: [['[Latex]', '[/Latex]'], ['$$', '$$'], ['\\[', '\\]']]
  }
});
</script>
```

to accomplish the same thing.

**Comment by dpvc** [comment]
Note:  This issue tracker is intended for reporting bugs in MathJax, not asking general questions about MathJax.  The [MathJax Users Forum](https://groups.google.com/forum/?fromgroups#!forum/mathjax-users) is a better place for that, as more people will see it and may be bale to respond.

**Comment by zhaokaifengcom** [comment]
> Note: This issue tracker is intended for reporting bugs in MathJax, not asking general questions about MathJax. The [MathJax Users Forum](https://groups.google.com/forum/?fromgroups#!forum/mathjax-users) is a better place for that, as more people will see it and may be bale to respond.
It works! Thank you for your guidance, thank you!!!
