### ISSUE TITLE
How to learn the MathJax API quickly?

### ISSUE THREAD

**Issue by ghost** [mathjax/MathJax#2362]
I am looking to learn the MathJax API and the inner workings of MathJax relatively quickly, but I am having trouble with it at the moment. Since the API section of the documentation is not written yet, I find it hard to get a hold of what's actually going on inside.

Is there maybe any old documentation that explains that and is still mostly accurate? Or could maybe somebody explain it briefly (or give a starting point for looking through the code myself)?

**Comment by dpvc** [comment]
Because v3 is a complete rewrite, there is no old documentation to call on.  The best place right now is the [MathJax node demos](https://github.com/mathjax/MathJax-demos-node#mathjax-demos-node) repository and the examples it contains.  Look at the [direct](https://github.com/mathjax/MathJax-demos-node/tree/master/direct#non-component-based-examples) approach for the lowest level access.  The README in that directory gives the overview of what you need to do to set up and call MathJax conversion functions.  

The basic idea is that there is one ore more input jax to convert math from an input format like TeX or AsciiMath into MathJax's internal format (basically MathML), and an output jax to convert that internal format into he desired output format (HTML or SVG currently).  You create and configure these separately via instantiating the appropriate objects.  (See `ts/output/chtml.ts` and `ts/output/svg.ts`).  

These both work within a context that MathJax calls a `MathDocument` (`ts/core/MathDocument.ts`).  The idea is that there could be various document formats (HTML, Markdown, etc), and how these are handled may differ, and the MathDocument mediates that.  The only MathDocument class currently implemented is the `HTMLDocument` class (`ts/handlers/html/HTMLDocument.ts`).  You need to register the document type with MathJax so that it can process documents of that type.  

Because we want to be able to process HTML documents server-side as well as in the browser, the internal format of the HTML document may not be an actual browser DOM (which is not available in node applications, for example).  There are several different DOM implementations for node (and even in the browser, there are specialized DOM's like React's virtual DOM, and things like ShadowDOM that need to be treated specially), so MathJax abstracts the actions it needs to perform on a DOM using a `DOMadaptor` object (`ts/core/DOMadaptor.ts`, with implementations in `ts/adaptors`).  MathJax provides a `LiteDOM` class for implementing a minimal DOM for server-side use (very minimal) in `ts/adaptors/lite`.    The `HTMLDocument` class doesn't know what type of DOM you are actually using, and does all its DOM manipulation via the adaptor that you provide when you register the HTML document type.

Once you have registered the document type and created the input and output jax, you create the `MathDocument` via `mathjax.document()`, passing it the DOM to be use, or a string to be parsed into a DOM, together with any configuration options, which includes the input and output jax.  The document contains the methods to call to perform typesetting of the DOM, or conversion of math strings to DOM elements or internal MathML, etc.  The main entry points are the `render()` and `convert()` methods.  These each cause a sequence of functions to be called, called `renderActions`, which you can control through the options passed when creating the document.

The standard functions for `render()` include: finding the math in the document, compiling the math to internal MathML, getting the metrics for the surrounding fonts, typesetting the math, and updating the document.  You can see these here:

https://github.com/mathjax/MathJax-src/blob/e9b75064ae86ffda179dd86df74bb603eb1416d4/ts/core/MathDocument.ts#L511-L520

Some extensions add more commands to this list (e.g., the menu extension adds a render action to add the menu event handlers to the typeset output before inserting them into the document).  The `convert()` function performs similar actions.

Math that is found in the document is stored in a `MathItem` object (`ts/core/MathItem.ts`, but also see `ts/handlers/html/HTMLMathItem.ts').  These are stored in a list within the `MathDocument`, so that they can be processed for the various render actions, but can be created separately for things like `convert()`.  The `MathItem` contains methods for compiling the math string into the internal format, and converting that into the output format (HTML or SVG), and the render actions list calls these when you use the document's `convert()` command.

I think that is the basic overview.  I hope that gets you started.
