### ISSUE TITLE
Why does MathJax use MathML as it's internal format?

### ISSUE THREAD

**Issue by leontepe** [mathjax/MathJax#2363]
What were the reasons for choosing MathML as the internal format? What makes it suitable for this use case? And what additions were made to the MathML format for MathJax's purposes?

**Comment by dpvc** [comment]
> What were the reasons for choosing MathML as the internal format? What makes it suitable for this use case?

MathML was designed as an interchange format for programs dealing with mathematics, and so was a natural choice for MathJax's internal format.  We wanted to be able to handle input from various formats (LaTeX, MathML, AsciiMath), and to generate different output formats (HTML-CSS, SVG, MathML), using an established standard would helped make that possible.  For MathML input and output, the conversion to and from the internal format was easy.  Since AsciiMath already produced MathML as its output, that format was easy to support.  The LaTeX input was the more challenging part, and MathJax's TeX input jax is essentially a TeX-to-MathML converter.

Similarly, the HTML-CSS, CommonHTML, PreviewHTML, and SVG output formats are all essentially MathML to HTML or SVG processors.  This separation of input and output via a common internal format makes it possible to mix-and-match any input format with any output format.  That is why using an interchange format like MathML was useful and natural.  

Because MathML is ams established standard, we could leverage things like AsciiMath with little change.  Had we used some other custom format, we would have had to make custom converters for formats like AsciiMath and MathML rather than simply using the standard format they already produce.

> And what additions were made to the MathML format for MathJax's purposes?

We tried to keep this to a minimum, but in order to fully support TeX input, we did need to add one non-standard node type internally (the TeXAtom node to handle setting the TeX class for an arbitrary sub-expression, which affects the spacing).  We also needed a few extra internal attributes in a few places, which we expose as class names on the generated MathML.  But over all, there were very few such additions.

**Comment by leontepe** [comment]
> Similarly, the HTML-CSS, CommonHTML, PreviewHTML, and SVG output formats are all essentially MathML to HTML or SVG processors.

What exactly are CommonHTML and PreviewHTML? I have read CommonHTML/CHTML throughout the documentation and code a lot and couldn't find a definition of it on the web. And I have no clue what PreviewHTML is. This seems to be something MathJax specific, right? What are the purpose of these two?

> We also needed a few extra internal attributes in a few places, which we expose as class names on the generated MathML. But over all, there were very few such additions.

Are the `<mjx-script>` DOM elements MathJax produces within `<mjx-msup>` an example of this? This doesn't match the standard MathML markup, right?

Also, what I don't really understand: is MathJax always using LaTeX style (spacings etc.) to typeset the mathematics? Because even when I use the `mml-chtml.js` combined component file, the output looks similar to TeX output (or at least the fonts used seem to be the same).

And how did you guys (the MathJax team) learn MathML when developing MathJax? I am trying to learn MathML right now but the resources on the internet covering that are extremely scarce and I don't want to read through the whole MathML documentation/specification, since it is kind of long and a tough ride to understand.

And thanks a lot for your thorough explanations, this really helps me out a lot. I am sorry for the many questions, but as of now some parts are still confusing to me. But I think after this I will mostly be able to keep going on my own x). Thanks!

**Comment by dpvc** [comment]
> What exactly are CommonHTML and PreviewHTML?

These are the names of two of MathJax's output renderers.  The original formatter was `HTML-CSS`, back in 2009, which uses browser-specific hacks to get everything to work.  Then cam the `SVG` output renderer, which was faster and largely browser-independent.  `PreviewHTML` was used to create a quick (but less accurate) preview version of the math that could be displayed while the higher-quality version was being created.  But it can also be selected as the final output format using the MathJax contextual menu.  Finally, `CommonHTML` is MathJax's most recent output format, roughly the same speed as `SVG`, and also browser-independent.  The `CommonHTML` (CHTML) and `SVG` output formats have been ported to version 3, but the older and slower `HTML-CSS` renderer will not.  The `PreviewHTML` renderer probably won't be ported either, as v3 is fast enough not to need previews in most situations.

> Are the `<mjx-script>` DOM elements MathJax produces within `<mjx-msup>` an example of this? 

No.  These are not part of the internal format, and aren't part of MathJax's extensions to MathML.  They are part of the layout generated by the CommonHTML output format to handle the `<msup>` MathML element.  The output from MathJax tried to mirror the internal MathML (by including elements that correspond to the MathML), but there are additional DOM elements needed to get the layout correct in HTML and SVG.  The internal format is still MathML, and MathJax only added one additional node type to that.

> is MathJax always using LaTeX style (spacings etc.) to typeset the mathematics?

The default is to use TeX spacing for both the CHTML and SVG output, but both renderers have a 'mathmlSpacing' option that you can set to 'true' to cause the output to use MathML spacing rules instead.  The fonts will still be the MathJax TeX fonts, but the spacing will be as specified for MathML.

> And how did you guys (the MathJax team) learn MathML when developing MathJax?

From reading the specification, which is the only authoritative description.  I have not looked for other resources.  Agreed that it is not an easy read, and not as clear in some places as it might be.
