### ISSUE TITLE
Subscripts and superscripts show too big in Firefox

### ISSUE THREAD

**Issue by carlesfernandez** [mathjax/MathJax#2366]
Hi,

I'm trying to upgrade to Mathjax 3 in my Jekyll website, in which I'm currently using Mathjax 2.7.6. My javascript is:

```
<script>
MathJax = {
  tex: {
    tags: "ams",
    packages: {'[+]': ['ams', 'noerrors', 'color']}
  },
  chtml: {
    scale: 1.05,
    minScale: 1
  },
  options: {
    ignoreHtmlClass: 'tex2jax_ignore',
    processHtmlClass: 'tex2jax_process',
    renderActions: {
      find_script_mathtex: [10, function (doc) {
        for (const node of document.querySelectorAll('script[type^="math/tex"]')) {
          const display = !!node.type.match(/; *mode=display/);
          const math = new doc.options.MathItem(node.textContent, doc.inputJax[0], display);
          const text = document.createTextNode('');
          node.parentNode.replaceChild(text, node);
          math.start = {node: text, delim: '', n: 0};
          math.end = {node: text, delim: '', n: 0};
          doc.math.push(math);
        }
      }, '']
    }
  },
  loader: {
    load: ['[tex]/ams', '[tex]/noerrors', '[tex]/color']
  }
};
</script>
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script type="text/javascript" id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>
```

Maths look good in Chrome and Safari, but not Firefox. Without setting the `cthml` option parameters, math font size shows extremely small in Firefox (but not in other browsers). The font size can be enlarged with those parameters (I've tried other combinations, such as  `minScale=0.5` and `matchFontHeigh=false`) but then the font size for subscripts and superscripts is just too large, and looks ugly.

For instance:

In all browsers, including Firefox, when using MathJax 2.7.6 with the following config:
```
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({ TeX: { extensions: ["color.js"], equationNumbers: { autoNumber: "AMS" }}, CommonHTML: {scale: 105, minScaleAdjust: 100}});
</script>
```

![image](https://user-images.githubusercontent.com/4881484/76161724-490df080-6136-11ea-8a06-7442810193ce.png)

Same equation when changing to Mathjax 3, in Firefox 73 for macOS:

![image](https://user-images.githubusercontent.com/4881484/76161761-abff8780-6136-11ea-9ad8-494c575fecfe.png)

This latter equation, with Mathjax 3, looks just as it did with MathJax 2.7.6 in Chrome and Safari, so it seems a Firefox-only issue.

Any idea on how to fix that?

**Comment by dpvc** [comment]
I am not able to reproduce the result.  Can you give an example page that exhibits the problem?

**Comment by carlesfernandez** [comment]
Hi @dpvc,

The page is at https://gnss-sdr.org

The code is at https://github.com/gnss-sdr/geniuss-place

**Comment by dpvc** [comment]
Sorry, I meant a page that is running MathJax v3.  This one is at 2.7.6, which doesn't exhibit the problem.

**Comment by carlesfernandez** [comment]
I don't have an example online, since I couldn't fix this issue for Firefox.

I found this issue by replacing in the online example the call to MathJax 2.7.6 by MathJax 3. If it is of help, I can create a simple demo page and put it online.

**Comment by dpvc** [comment]
> If it is of help, I can create a simple demo page and put it online.

Yes, that would help, thanks.

**Comment by carlesfernandez** [comment]
Ok, there it is. I've reproduced the same website, but now using MathJax 3.

Check it online, for instance: https://carlesfernandez.github.io/web-test/docs/sp-blocks/observables/ 

In this instance, I still can see differences in the subscript/superscript font size in Firefox with respect to other browsers.

**Comment by dpvc** [comment]
OK, thanks.  I see the same thing now, but haven't yet figured out what is the cause.  Can you leave the site up for a bit?

**Comment by carlesfernandez** [comment]
Yes, no problem, I will leave it online.

Thanks for looking into it!

**Comment by dpvc** [comment]
OK, I've figured out what is going on.

MathML (the internal format for MathJax) has a value that specifies the minimum font size that MathJax will use for super- and subscripts, and it is set to 8px by default.  Now, MathJax does all its measurements internally in relative units of ems, and number of pixel per em is determined by matching the MathJax fonts to the surrounding font by making their ex-heights the same.  MathJax does that by measuring the ex-height of the surrounding font (in pixels).  That measurement is "fragile" in some ways, and it does rely on the surrounding font having a correct ex-height and MathJax being able to measure it properly.

It turns out that either your main text font has a bad ex-height, or Firefox is getting the ex-height wrong, because the ex-height is not correct for that font in Firefox (but is own other browsers).  Font metrics are a real mess, and most fonts include separate metrics for Windows and Mac environments, and it may be that these are not consistent in this font, and Firefox is using one of them while other browses are using the other.  I haven't tried to look any further than that.  I have seen similar issues in Google fonts in the past.

In any case, one solution is to change the script minimum size to be in ems rather than pixels, so that the px-per-em value isn't used.  That is probably the easiest work around for now.  Use

``` html
<script>
MathJax = {
  startup: {
    ready() {
      const MmlMath = MathJax._.core.MmlTree.MmlNodes.math.MmlMath;
      MmlMath.defaults.scriptminsize = '.1em';
      MathJax.startup.defaultReady();
    }
  }
}
</script>
```

I think this will work around the problem for now.

**Comment by dpvc** [comment]
I'm marking this as "upstream" as I suspect it is really the ex-height setting in the Ovo font that is the problem, and I don't really have another label that makes sense.

**Comment by carlesfernandez** [comment]
This solution works great. Thank you!
