### ISSUE TITLE
\begin{equation} can not rendered correctly

### ISSUE THREAD

**Issue by JimmyChoooooo** [mathjax/MathJax#2375]
Hi,
I'm using Mathjax 3.0.1, but i found these codes can not be rendered correctly if I use tex2svg.
`a=bbbbbb\begin{equation} y=x^2 \end{equation}`
These two formulas will overlap.
But it will be fine when I use CHTML or the Collapsible Math option be chosen.
If I use array environment, another problem arises, the letter y is missing. Whether it's SVG or CHTML.
`a=bbbbbb\begin{array} =x^2 \end{array}`
I'm so confused. 
Thank you.

**Comment by dpvc** [comment]
Neither expression is valid LaTeX.  For the first, the `equation` environment is a top-level environment, and should not be used as part of a larger expression, and you have done here.  It should produce an error in this case, but currently doesn't (it would do so in actual LaTeX).

For your second expression, the `array` environment takes an argument that gives the alignment specification for the array.  In your case, since you have not provided one, the argument is taken as the first character that follows (as the LaTeX parsing rules dictate).  That is, the `y` is taken as the column alignment template, which turns out to be a meaningless one, but it does mean that `y` is not part of the actual array in that case.

So the second expression is properly rendered.  The first should produce an error, but barring that, the output is not specified, since it is invalid markup.

**Comment by dpvc** [comment]
PS, this issue tracker is for reporting bugs in MathJax or making feature requests.  General questions about how things work are better asked in the [MathJax User's Forum](https://groups.google.com/forum/?fromgroups#!forum/mathjax-users), where more people are likely to see it and potentially provide an answer.
