### ISSUE TITLE
No bbox in \sqrt argument?

### ISSUE THREAD

**Issue by t-k-** [mathjax/MathJax#2379]
### Issue Summary

Is that expected to raise error for a bbox in `\sqrt` argument?

### Steps to Reproduce:
Render this snippet:
```
 \sqrt[\bbox[red]{3}]{8} 
```

### Technical details:

* MathJax Version: in https://mathjax.github.io/MathJax-demos-web/input-tex2svg.html
* Browser: Chromium 80.0.3987.106

**Comment by t-k-** [comment]
It looks like it is rooted in the way MathJax handles square brackets argument reduce? So if I define a new command to avoid having recursive square brackets in the argument, it will work just fine:
```
\newcommand{\bb}[1]{\bbox[red]{#1}} 
\sqrt[\bbox{\bb{3}}]{8} 
```

**Comment by dpvc** [comment]
Unfortunately, this is, in fact, correct behavior, as that is how actual LaTeX operates as well.  For example, `\sqrt[\sqrt[3]{x}]{y}` will throw an error in actual LaTeX because the bracket argument ends up being `\sqrt[3` (it ends at the first `]`) and that causes an error when it is processed.  MathJax also ends the bracket argument at the first `]`, just as LaTeX does.

The way you get around that is to use braces within the brackets: `\sqrt[{\sqrt[3]{x}}]{y}`.

In your case, `\sqrt[{\bbox[red]{3}}]{8}` would do the trick.  That is just how LaTeX works, I'm afraid.

**Comment by t-k-** [comment]
@dpvc Thank you. It explains everything.
