### ISSUE TITLE
mfrac linethickness causes render issues

### ISSUE THREAD

**Issue by andreeapescar** [mathjax/MathJax#2381]
When **linethickness** is set, the fractions don't render properly, the line height is wrong ( `<math><mrow><mo>-</mo><mfrac linethickness="1"><mn>1</mn><mn>3</mn></mfrac></mrow></math>`).

I tried to render in multiple ways:
![image](https://user-images.githubusercontent.com/20281464/77524786-a1602480-6e90-11ea-84f0-aa51a6b04e1a.png)

And this how it renders:
![image](https://user-images.githubusercontent.com/20281464/77524813-ac1ab980-6e90-11ea-8b33-8e7fe15d8fcd.png)

The ones that have linethickness="1" set don't render properly.
(I observed that `em` is used to render that line.)

Is there any fix for this?
Thank you!

**Comment by dpvc** [comment]
The display for `linethickness="0"` is also correct, as that means there should be no line, which is what you are seeing.

Note that `line thickness` is a length, and so should either have units or be a named length (like `medium`).  Unitless lengths are deprecated, and are available only for backward compatibility.  They are supposed to represent a multiple of the default length, and so in that sense, the result is incorrect, but it turns out that MathJax treats `linethickness="1"` as `linethickness="1em"` in this case.  That needs to be fixed.

It is not clear what result you are looking for.  If `linethickness="1"` is supposed to produce the normal line thickness, then you could use `linethickness="medium"`.  Otherwise, use an explicit unit to get the size you want.

It is possible to use a MathML pre-filter to convert unitless line thickness to multiples of .06em (the size of `medium`).  How that is done differs between version 2 and version 3, so I would need to know which you are using in order to advise you further.

**Comment by dpvc** [comment]
I've made a pull request to fix the unitless `linethickness` value in version 3.

**Comment by andreeapescar** [comment]
Thank you for your quick response!

You are right, `The display for linethickness="0" is also correct`, I am sorry for that mistake.

I thought linethickness="1" is supposed to produce the normal line thickness, without having to replace "1" with "medium".

What I need this for:
I get a string like: "<math><mrow><mo>-</mo><mfrac linethickness="1"><mn>1</mn><mn>3</mn></mfrac></mrow></math>" and I have to render it as html, which I do with `dangerouslysetinnerhtml`) without having to parse the string.

I am using mathjax-full "^3.0.0".

I assume that after your PR is merged, linethickness="1" will produce normal line thickness, right?

**Comment by dpvc** [comment]
> I thought linethickness="1" is supposed to produce the normal line thickness

It is, but that usage is discouraged by the [MathML specification](https://www.w3.org/TR/MathML3/chapter2.html#type.length):

"A number without a unit is interpreted as a multiple of the reference value. This form is primarily for backward compatibility and should be avoided, prefering explicit units for clarity."

> I assume that after your PR is merged, `linethickness="1"` will produce normal line thickness, right?

After it is merged, it will be in the `develop` branch.  This will become part of v3.0.2 when `develop` is merged into `master`.  At that point, the `mathjax-full` package will be updated, and you can use `npm install` to get the fixed version.

In the meantime you could use something like

``` javascript
mml = mml.replace(/ linethickness\s*=\s*"([1-9][0-9]*(?:\.[0-9]*)?)"/g, 
          function (match, n) {return ` linethickness="${parseFloat(n)*.06}"`})
```

in order to work around the problem for now.

**Comment by andreeapescar** [comment]
Awesome. Thanks a lot for helping! 👍
