### ISSUE TITLE
Will it be more efficient if I take tex --(sever_side)--> mml --(client_side)--> chtml

### ISSUE THREAD

**Issue by zq1997** [mathjax/MathJax#2383]
My blog page has lot's of math content and I want to speed its rendere up.

I know there is sever side rendere `tex2chtml` in Mathjax v3, but it seems that I must specify the `em`, `ex`, `width` values, I don't like to make any hypothesis on my readers' devices.

Therefore, I have an idea that I rendere `mml` output on server side with nodejs and use `mml2chtml` in client's browser. My question is will it be faster on the client side (compared with totally `tex2chtml` in browser)? and how much faster?

**Comment by dpvc** [comment]
> will it be faster on the client side (compared with totally tex2chtml in browser)? 

Probably not.  The TeX processing is relatively fast compared to the layout, plus you are introducing another parsing (of the MathML), so you lose some of your gain in any case.

You might try preprocessing to SVG rather than CHTML, as the `em` and `ex` sizes are less crucial there, and will only affect conversion of explicit dimensions in non-relative units (e.g., `\hskip 3px`) and the processing of characters that aren't in MathJax's fonts.

Alternatively, you could consider using Puppeteer to preprocess the page, as this will be able to look up `em` and `ex` sizes.

**Comment by zq1997** [comment]
Thank you, very nice solution with `tex2svg`, but as `\displaylines` seems not works in `tex2svg` (You know , I need it because `\\` is not ported yet.)

**Comment by dpvc** [comment]
>  as `\displaylines` seems not works in `tex2svg`

`\displaylines` works for me in SVG output.  Can you saw what is happening for you?  Do you perhaps need to use `\\\\` in place of `\\` ?

**Comment by zq1997** [comment]
ah， sorry.
I added `\displaylines` automatically in `findScript`, but since I user severe side rendere, it is not called now.
Yes, it does break lines, thank you.
