### ISSUE TITLE
Incorrect viewBox size in exported SVG

### ISSUE THREAD

**Issue by rysavyjan** [mathjax/MathJax#2390]
### Issue Summary

We are using MathJax 3 with NodeJS 10 (Windows platform) to render TeX to SVG files.
Exported SVG has (sometimes) incorrect viewBox size, so content is clipped.

### Steps to Reproduce:

Modify tex2svg from MathJax-demos-node:

```
git diff
diff --git a/component/tex2svg b/component/tex2svg
index daac42e..1a26de1 100755
--- a/component/tex2svg
+++ b/component/tex2svg
@@ -1,4 +1,4 @@
-#! /usr/bin/env -S node -r esm
+﻿#! /usr/bin/env -S node -r esm

 /*************************************************************************
  *
@@ -88,7 +88,7 @@ MathJax = {
     startup: {
         typeset: false,
         pageReady: () => {
-            MathJax.tex2svgPromise(argv._[0] || '', {
+            MathJax.tex2svgPromise(argv._[0] || 'ČÉŮ日本語', {
                 display: !argv.inline,
                 em: argv.em,
                 ex: argv.ex,
@@ -102,7 +102,7 @@ MathJax = {
                 if (argv.css) {
                     console.log(adaptor.textContent(MathJax.svgStylesheet()));
                 } else {
-                    console.log(adaptor.outerHTML(node));
+                    console.log(adaptor.innerHTML(node));
                 };
             }).catch(err => console.log(err));
         }
```

Run following command ```node -r esm tex2svg >out.svg```

Open out.svg with Inkscape:
![image](https://user-images.githubusercontent.com/46950152/78028191-e8518c80-735e-11ea-955f-7654b61490a0.png)

Diacritic and right side is clipped. Note that this problem could be reproduced just with simple string containing one character.

Is there any method how to setup MathJax to export viewBox correctly?

Thank you for great work!

### Technical details:

* MathJax Version: 3.0.1
* Client OS: Windows 10
* NodeJS: v10.19.0

**Comment by dpvc** [comment]
This is (essentially) a duplicate of #2329.  See [this response](https://github.com/mathjax/MathJax/issues/2329#issuecomment-586371301) for why that is, and for a suggestion about how you might proceed.  Note, however, that even the Puppeteer solution may not be perfect, since the font used to render the characters that are not in the MathJax fonts will come from the user's system fonts, and those may not be the same from user to user.  If you can supply a web font for them, that would improve the situation.

Also, note that MathJax's CSS for SVG output sets `overflow: visible` for the SVG elements that it creates, so you may want to include that CSS if you can.  That would prevent the clipping.

**Comment by rysavyjan** [comment]
Thank you for explanation, great support!
