### ISSUE TITLE
Cramped style not respected

### ISSUE THREAD

**Issue by NSoiffer** [mathjax/MathJax#2395]
### Issue Summary
I find this surprising enough to think that maybe I'm doing something wrong (and I didn't find an issue about this)...

TeX has a notion of "cramped" which causes superscripts to be lower in a number of cases such as in accents, overlines, fractions (denominators), and subscripts.  Here's a latex rendering:
![image](https://user-images.githubusercontent.com/1545836/78419214-6086af00-75f8-11ea-8d99-c00ad7fc3035.png)

The position of the '2' in x^2 is lowered in first instance except for the fraction, where it is the second instance (the denominator).

However, MathJax doesn't reduce the superscript position. Here's [a codepen that shows that](https://codepen.io/nms/pen/VwLOgPM). Here's a screen shot of that:
![image](https://user-images.githubusercontent.com/1545836/78419264-fc181f80-75f8-11ea-8252-f9b62ab16767.png)

[To be honest, my sons happened to be looking at what I was doing and liked the MathJax rendering better...]

### Steps to Reproduce:
This is the header
```
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script type="text/javascript" id="MathJax-script" async
  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js">
</script>
```

and this is the input
```
\[ \hat{x^2} x^2\]
\[ \overline{x^2} x^2 \]
\[ \frac{x^2}{x^2} \]
\[ a_{x^2}a^{x^2} \]
```

**Comment by dpvc** [comment]
Thanks for the report.  MathJax is supposed to handle the cramped styles (what is listed as "prime" styles in appendix G of the TeXBook).  In version 2, properties like "primestyle" where stored in the same place as the MathML attributes, and that caused difficulty in distinguishing the two, so in version 3, they are stored in two separate places.  Unfortunately, when translating the code that determines the superscript offsets to version 3, I neglected to switch the location, so was looking for the prime style in the wrong place.  So it never appeared to be set.

I will make a pull request to fix the problem.  It also turns out that there was a problem handling the prime style in display mode, which I will also fix.
