### ISSUE TITLE
Spacing in expression with greek letters and powers (MathJax 3)

### ISSUE THREAD

**Issue by dainiak** [mathjax/MathJax#2406]
### Issue Summary

MathJax v2 renders like this:
![image](https://user-images.githubusercontent.com/2994860/79330970-191aef80-7f23-11ea-8066-ff1d100daf1b.png)
Whereas MathJax v3.0.5 renders the formula almost with no spacing between the base and the power:
![image](https://user-images.githubusercontent.com/2994860/79331053-3ea7f900-7f23-11ea-9608-b6788376851c.png)

Also there is a difference in vertical alignment of the power, arguably MJv2 does a better job here, making the formula vertically tighter.
Otherwise using MJv3 with pleasure, thank you!

### Steps to Reproduce:

$\beta^{p^k\cdot(p-1)}$

### Technical details:

* MathJax Version: 2.7.4 vs 3.0.5
* Client OS: Windows 10
* Browser: Chrome 81.0.4044.92

**Comment by dpvc** [comment]
There do seem to be some spacing issues there.

There are several heights used in TeX depending on the style (e.g., display versus text), and whether the style should be further "cramped" (like inside a square root or fraction).  It looks like the display height is being used where text height should be used.  I will need to look into that, as well as the horizontal distances.

**Comment by dpvc** [comment]
I have finally gotten the chance to work on this (as I was working on other super- and subscript issues), and it turns out that the vertical positioning in v2 was wrong, and the v3 heights are correct.  The horizontal positioning is wrong, however, and that is due to the fact that MathJax doesn't have all the italic correction information that TeX does.  MathJax "fakes" that data, but that doesn't always work well.  In v2, the layout put the `scriptspace` tex font parameter spacing in the wrong place, which accounts for the extra spacing there, but v3 corrected that error.  In order to compensate for the missing italic correction information, I've made a pull request that adds a small space between the base and the exponent.  It is not exactly like in TeX, but is an improvement.
