### ISSUE TITLE
MathJax output bigger/bolder than original LaTeX output?

### ISSUE THREAD

**Issue by leontepe** [mathjax/MathJax#2410]
I have the feeling that MathJax renders the math a little bit bigger or bolder than the original LaTeX compiler does. Although I do think it, in some way, looks better or a little bit cleaner, I would still like to know whether this is intended? And also, if it is, what were the reasons for this? Just to make the output look better? And how was this actually achieved on a technical level?

**Comment by leontepe** [comment]
Also, kind of unrelated, but is it possible to contact you „privately“ to maybe have a chat with you about MathJax? I think I have lots of questions and I would love to talk about them in a quicker way when you are free sometime instead of opening new Issues on here each time. What do you think? @dpvc

**Comment by leontepe** [comment]
I just had the idea (correct me if this is wrong) that it might be due to some kind of anti-aliasing that's included in MathJax or the browser (I don't know which one) that makes the MathJax-rendered math look a little bit cleaner, but also a little bit bolder at the same time. This is at least my speculation.

Seems so weird to me that the web-ported version of LaTeX actually looks better than if I open a `pdflatex` rendered PDF on my local PC lol.

**Comment by dpvc** [comment]
> I have the feeling that MathJax renders the math a little bit bigger or bolder than the original LaTeX compiler does. 

When TeX was developed in the late 1970s, printer technology was somewhat different than it is today.  Personal laser and inkjet printers were not yet available, and desktop printers were "dot matrix" printers with resolutions from around 50 to 150 dpi.  Professional printing was at resolutions of 1200 and above.  Converting TeX to print was a several-step process, and involved running TeX to produce a `.dvi` file of device independent information, and then converting that dvi file to a final printable form that was specific for your printer.  This involved having an appropriate print driver, along with appropriate fonts for the resolution of your printer.  the dvi processor would generate these itself using a program called `metafont` that took an abstract description of the fonts and rasterized them to the specific pixel resolutions needed for your printer.  

The metafont descriptions of the fonts included parameters that would allow you to tune the output to your printers characteristics.  For example, some laser printers operate by having the laser mark the black parts of the page, while others use the laser to mark the white parts (write-black versus write-white printers).  Which technology was used affects the quality of the output, and in particular how thin lines are rendered, and it was often advantageous to adjust the metafont parameters to compensate for these issues, in addition to the raw resolution issues.

TeX installations included definitions for various printers, so that you could take advantage of the work others had already put into tuning metafont to the printer you had.  Many of these definitions are [still available](https://ctan.org/pkg/modes?lang=en), though the low-resolution dot-matrix printers are no longer listed there.  you will find low-resolution screen preview modes listed, however, along with 300dpi laser printers and other (by today's standards) low-resolution printers.

So the weight and quality of the fonts used in LaTeX output are not constant, they depend on the driver used to generate the output.  These days, most people use `pdflatex` to generate PDF files from LaTeX source in one step (the tex and dvi steps are both done together).  There are still hold-overs to the past, however, and you still can use `dvips` to produce postscript output, for example.  The `pdflatex` program now uses postscript outline fonts rather than the original bitmap fonts that TeX would produce, but the parameters of these fonts are still geared toward printing (pdf is a print format originally), and so assume a high resolution output device.

Screens are low-resolution in comparison (up until recently, 72 to 96 pixels per inch were the most common resolutions), and output generated for higher resolution printing is not always optiomal for screen viewing.  Most `pdflatex` output will look a bit thin and anemic on screen.  

Furthermore font rendering technology differs widely by operating system (and even by browser within an operating system).  When MathJax was originally written more than 10 years ago, the rendering engines on the Mac and in Windows were substantially different in quality, with the results for the same font on a Mac being heavier, and on the PC being much thinner.  The MathJax fonts needed to work reasonably well in both, so we generated versions using `metafont` settings that were somewhat heavier than usual for laser-printer output (what you would see in a PDF document) so that on Windows they were not spindly and anemic, but not too heavy so that on a Mac they were not overly dark.  It was certainly a compromise, but one that tried to make the output reasonable in both cases.

Also, because of the very low resolution of computer screens (compared to print), and the small scale often used for the fonts (which get even smaller in super- and sub-scripts), parts of the letters could disappear of they were not thick enough (e.g.,the vertical part of a plus could disappear, making it looks like a minus, and a minus sign could disappear altogether).  A heavier font helps make that sort of problem less likely.

But you are wrong to think that LaTeX produced only one style of output.  That was controlled by the dvi driver and the node settings used any metafont, and varied from printer to printer.  So there was not one definitive LaTeX result.

> I would still like to know whether this is intended? And also, if it is, what were the reasons for this? 

Yes, it was intentional.  See the description above.

> how was this actually achieved on a technical level?

The parameters in the mode definition file for metafont where altered to make the letters a bit heavier.  But since browsers don't use TeX bitmap fonts (they use postscript outline files in .otf or .tts or now .woff formats), the TeX bitmap fonts had to be converted to outline fonts.  This was done using a program called `mftrace` which renders the bitmaps at large resolutions and then traces their edges to produce the needed bezier curves and straight lines.  That introduces some imprecision to the results, but is generally good enough for screen use.

We are looking at replacing the 10-year-old MathJax TeX fonts with new versions as we work on the v3 font support this summer.

**Comment by dpvc** [comment]
> is it possible to contact you „privately“ to maybe have a chat with you about MathJax? I think I have lots of questions and I would love to talk about them in a quicker way when you are free sometime instead of opening new Issues on here each time. What do you think?

No, I am not prepared to offer that service.  I can sometimes take time to answer questions like this here because the answer is available to everyone and so my effort can be useful not just to you but to others with the same question.  So I'm willing to put in the time for that reason.  A private conversation does not provide that advantage, and I am not willing to spend my limited time in that way.

**Comment by dpvc** [comment]
Note that this issue tracker is intended for reporting bugs in MathJax.  General questions are better asked in the [MathJax Users' Forum](https://groups.google.com/forum/?fromgroups#!forum/mathjax-users) where they can be seen by others who could potentially respond.

**Comment by leontepe** [comment]
> We are looking at replacing the 10-year-old MathJax TeX fonts with new versions as we work on the v3 font support this summer.

@dpvc What exactly will change with the release of these new TeX font versions? Will there be significant improvements in font rendering quality?

> A private conversation does not provide that advantage, and I am not willing to spend my limited time in that way.

Well, I had to at least shoot my shot, haha. I very much understand that though.

> Note that this issue tracker is intended for reporting bugs in MathJax. General questions are better asked in the MathJax Users' Forum where they can be seen by others who could potentially respond.

Okay, got it. I will be posting my questions there instead in the future.

And once again, thanks a lot for your always very thorough explanations, this really helps out a lot. :)

**Comment by dpvc** [comment]
> What exactly will change with the release of these new TeX font versions? 

There will be a choice of fonts that can be used to typeset the mathematics (e.g., the MathJax TeX fonts, or STIX fonts, or several other fonts)

> Will there be significant improvements in font rendering quality?

It may be that we take portions of the Latin Modern fonts as the base MathJax fonts rather than the ones we generated ourselves.  The quality is probably a bit better for those (though they are thinner).  But the main improvement will be in available characters and in particular the characters needed to make stretchy versions of some of the ones that are not handled well with the current fonts.

**Comment by paeifbnaeufbpae** [comment]
Hey @dpvc.

> The parameters in the mode definition file for metafont where altered to make the letters a bit heavier.

I suppose you are talking about the `blacker` mode parameter here. Do you still remember the exact value used for it? I'm estimating it was around 10?

**Comment by dpvc** [comment]
@paeifbnaeufbpae, according to the [makefile](https://github.com/mathjax/MathJax-dev/blob/c385ab91ea8839ca30319b3ec9e746e1c817a92f/fonts/OTF/TeX/Makefile#L28), it looks like it was 15.
