### ISSUE TITLE
Offline converter only mode

### ISSUE THREAD

**Issue by solomax** [mathjax/MathJax#2414]
Hello,

First of all thanks for great library :)
I'm one of the developers of Apache OpenMeetings https://openmeetings.apache.org/

Right now we are using 
1. MathJax 2.7.5 in offline mode (thanks to https://github.com/pkra/MathJax-single-file)
2. Formulas are being entered in TeX format, converted to SVG and displayed using http://fabricjs.com/

Everything seems to work as expected. (via `Typeset` and `MessageHook`)

Recently I 
1. turn strict CSP ON
2. noticed the new `3.0.5` version has been released

With strict CSP it turn out MathJax performs DOM manipulations and injecting stylesheets
**Is it possible to turn this OFF?**

Version `3.0.5` seems to have `tex-svg-full` which seems to be what I need, BUT
1. I found no way to create non-minified version of this JS, **Is this possible?**
2. It still injects stylesheets, **Is it possible to turn this off?**
3. Documentation states there is no `Typeset` and `MessageHook` anymore, **maybe there is an option to perform TeX->SVG conversion using Promise or something similar so I can get Errors if any?**

Thanks in advance for your answers
(Please let me know if I should post to some other place)

**Comment by solomax** [comment]
Thanks a lot for detailed answer :)
I'll try to migrate and will report back :)

**Comment by dpvc** [comment]
PS, if you want to work off-line, then you may be able to use a nodes-based server-side solution rather than an in-browser one.  You could use Puppeteer for that, or use MathJax's node support to do what you normally would do in a browser.  See the [MathJax node demos](https://github.com/mathjax/MathJax-demos-node) page for examples.  The documentation for that is sparse, but the examples may be sufficient together with the web documentation.

**Comment by solomax** [comment]
Thanks,
We have back-end in Java, no node in the stack :)

**Comment by solomax** [comment]
Hello @dpvc,

I would like to post an update
I moved our JS build to npm and was able to implement standalone (offline) MathJax
Thanks for the pointer!

The only minor issue: I would like to get parse error in catch in below code
```
MathJax.tex2svgPromise('\\sqrt')
        .then((x) => console.log(MathJax.startup.adaptor.innerHTML(x)))
        .catch((err) => console.log(err.message));
```
currently I workaround this :)

Thanks a lot for the help!

**Comment by dpvc** [comment]
Since my original response to you, we have added easier support for the `formatError()` function, so the configuration is easier to manage.  For example:

``` javascript
MathJax = {
  tex: {
    formatError(jax, error) {throw Error('TeX error: ' + error.message)}
  },
  startup: {
    typeset: false,
    pageReady() {
      return MathJax.tex2svgPromise('\\sqrt')
        .then((x) => console.log(MathJax.startup.adaptor.innerHTML(x)))
        .catch((err) => console.log(err.message));
    }
  }
}
```

This causes the `catch()` function to run for me.  If that doesn't work for you (with a current version of MathJax), then can you give more details about your configuration?

**Comment by solomax** [comment]
thanks a million!
totally missed this part :(((

now everything works without extra parsing :)

**Comment by dpvc** [comment]
Glad you got it to work.
