### ISSUE TITLE
Problem with rendering diacritic in SVG mode

### ISSUE THREAD

**Issue by kpalatzky** [mathjax/MathJax#2421]
### Issue Summary

There are problems with the display of some diacritcs. I have tested this directly on the MathJax website under the #demo section.

### Steps to Reproduce:

1. Go to https://www.mathjax.org/#demo
2. Insert the Formula: `<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"><mi>Ĥ</mi></math>`
3. May press "Render HTML"

Here you can see that the "H" and the "^" part are not displayed correctly one above the other, but overlap

### Technical details:

* MathJax Version: 3.0.5 (See Website MathJax.version)
* Client OS: Windows 10 (Latest)
* Browser: Chrome 81.0.4044.122

### Screenshot

![image](https://user-images.githubusercontent.com/18258842/80596996-7fc20200-8a27-11ea-9e4a-09c701e468b1.png)

**Comment by dpvc** [comment]
Your example uses the two-character sequence U+0048 U+0302 (an H with a combining circumflex accent), but this is not how accented characters are meant to be specified in MathML.  The MathML specification indicates that these should be formed with `<mover>` elements; see the documentation on [combining characters](https://www.w3.org/TR/MathML3/chapter7.html#chars.comb-chars):

> there are many combining characters that are intended to be used for the many accents of numerous different natural languages. Some of them may seem to provide markup needed for mathematical accents. <b>They should not be used in mathematical markup</b>. Superscript, subscript, underscript, and overscript constructions as just discussed above should be used for this purpose. [bold added]

The [mover documentation](https://www.w3.org/TR/MathML3/chapter3.html#presm.mover) gives examples of how this should be done.  For instance, your expression would be

```
<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">
  <mover>
    <mi>H</mi>
    <mo stretchy="false">^</mo>
  </mover>
</math>
```

It is also possible to use the single-character accented letter from the Latin Extended-A Unicode block, U+0124.  For example

```
<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline">
    <mi>&#x124;</mi>
</math>
```

Note, however, that this character is not in the MathJax fonts, so it will be taken from a system font, and so may not match the rest of the math quite so well.

The reason that your version doesn't work well in MathJax is that the combining circumflex (U+0302) is designed to work with lower-case letters, so doesn't fit properly with upper-case ones.  That is why it is not high enough.  Since MathML suggests that you use the `<mover>` construction for such characters, MathJax doesn't include code to try to reposition the combining character.
