### ISSUE TITLE
How to load the downloaded mathjax cdn in angular 7

### ISSUE THREAD

**Issue by rakesh2293** [mathjax/MathJax#2422]
**<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>**
instead of this above link i am passing js file as below in  angular 7 index.html 
 **<script type="text/javascript"   src="configuration\src\js\MathJax.js"></script>**
or
**<script type="text/javascript"   src="configuration\src\js\MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>**
**so it's showing 500 error**
**Please team can you resolve this issue ASAP** 
mathjax version is 2.7.5

**Comment by dpvc** [comment]
FIrst, note that version 2.7.1 is rather old.  The current 2.x version is 2.7.8.  The current version over all os 3.0.5, so you may wish to consider using that rather than 2.7 unless you have legacy code that calls on v2's application interface (which has changed in v3).

If your server is an Apache server, the 500 error means that there is an "internal server error", so suggests a misconfiguration of your server.  See [this site](https://www.ionos.com/community/server-cloud-infrastructure/apache/how-to-fix-http-error-code-500-internal-server-error/) for some suggestion on how to proceed, or google "apache 500 error" to see other options.

The main step will be to look at the server logs to see if there is more information there about the error and what is causing it.

Another thing to check is that you have actually included the complete MathJax installation in your `configuration/src/js` and not just the `MathJax.js` file, which is not all that is needed.  See the [v2 documentation](http://docs.mathjax.org/en/v2.7-latest/installation.html) for how to obtain the full MathJax installation for v2, and the [v3 documentation](http://docs.mathjax.org/en/latest/web/hosting.html) for how to do that for version 3.
