### ISSUE TITLE
 Maximum call stack size exceeded

### ISSUE THREAD

**Issue by rakesh2293** [mathjax/MathJax#2424]
Hi Team 
This is the issue i am facing now can you please tell me why it's causing like this
**Mathjax version- 3.0.5
angular varsion -  6.0.3**

and how i implemented is 
added this code inside the app.component.ts file
  require('mathjax').init({
      loader: {load: ['input/tex', 'output/svg']}
    }).then((MathJax) => {
      console.log('MathJax',MathJax)
      const svg = MathJax.tex2svg('\\frac{1}{x^2-1}', {display: true});
      console.log(MathJax.startup.adaptor.outerHTML(svg));
    }).catch((err) => console.log(err.message));

and added this **<script src="node_modules/mathjax/es5/tex-chtml.js"></script>** in index.html file 
but i am getting the  **Maximum call stack size exceeded** in chrome console 
so team can you please reply for this issue

**Comment by dpvc** [comment]
It is not clear whether you are trying to write a server-side node application or a browser-based web application.  There are some differences in how those two are handled, and you are mixing both techniques.  The `require('mathjax').init()` approach is for node-based applications, and will not work in a browser (even if you webpack it is use it in some other bundler), while the `<script>` tag is for in-browser use (though you seem to be using MathJax out of your `node_modules` directory you may wish to move the `mathjax/es5` directory from `node_modules` to somewhere more convenient on your server).

I suspect you are trying to do this in the browser (though unless the TeX string is being provided by a user via a web form, you probably should be doing a server-side node application).  In that case, you should do something like

``` html
<script>
MathJax = {
  startup: {
    pageReady() {
      MathJax.startup.defaultPageReady()
        .then(() => {
          const svg = MathJax.tex2svg('\\frac{1}{x^2-1}', {display: true});
          console.log(MathJax.startup.adaptor.outerHTML(svg));
        })
        .catch((err) => console.log(err.message));
    }
  }
}
</script>
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js"></script>
```

to do that.  Note that I added the missing backslash in the string needed for `\frac`.  I also changed the file being loaded from `tex-chtml.js` to `tex-svg.js` in order to get the SVG output jax rather than the CommonHTML output jax.

Alternatively, as a node application, use just

``` javascript
require('mathjax').init({
  loader: {load: ['input/tex', 'output/svg']}
}).then((MathJax) => {
  const svg = MathJax.tex2svg('\\frac{1}{x^2-1}', {display: true});
  console.log(MathJax.startup.adaptor.outerHTML(svg));
}).catch((err) => console.log(err.message));
```

in a file by itself and use node to execute that file.

See the [MathJax web demos](https://github.com/mathjax/MathJax-demos-web) page for examples similar to this for using MathJax v3 in a web page, and the [MathJax node demos](https://github.com/mathjax/MathJax-demos-node) page for examples of how to use MathJax v3 in node applications in several different ways.

**Comment by dorthrithil** [comment]
I experienced the same issue with MathJax in Angular when experimenting with different ways to load it. Turned out that I missed to remove a reference in the bundled scripts from `angular.json` before including the same `script` via script tag. So I guess the double include caused MathJax to go into an infinite loop. 
After removing one of the references everything worked fine.
