### ISSUE TITLE
problem rendering valid latex, array, text in V3

### ISSUE THREAD

**Issue by nasser1** [mathjax/MathJax#2431]
### Issue Summary

Mathjax  V3 does not correctly render the following latex. it does not handle {\small \text{}..}} 

Any browser.

### Steps to Reproduce:

Simply load the following small HTML file in your browser to see the problem.

```
<!DOCTYPE html> 
<html lang="en-US" xml:lang="en-US" > 
<head><title></title> 
<meta  charset="utf-8" /> 
<meta name="generator" content="TeX4ht (https://tug.org/tex4ht/)" /> 
<meta name="viewport" content="width=device-width,initial-scale=1" /> 
<link rel="stylesheet" type="text/css" href="foo.css" /> 
<meta name="src" content="foo.tex" /> 
 <script> window.MathJax = { 
     tex: { tags: "ams", 
     inlineMath: [ ["\\\(","\\\)"] ], 
     displayMath: [ ['$$','$$'], ["\\[","\\]"] ], 
     processEscapes: true, processEnvironments: true, 
     packages: ['base', 'color', 'ams'] }, 
     loader: { load: ['[tex]/color', '[tex]/ams'] } }; 
 </script> 
 <script type="text/javascript" async="async" id="MathJax-script" 
    src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js">
 </script>  
</head><body>
<!--l. 18--><p class="noindent">
 \[\begin{array} [c]{c}
  \text{{\small bottom edge}}\\ \text{{\small bottom edge}}\\ \end{array}
  \begin{bmatrix} \alpha &amp; 2\\ 1 &amp; \alpha \\ \end{bmatrix}
 \] 
 </p> 
</body> 
</html>
```

Any other information you want to share that is relevant to the issue
being reported. Especially, why do you consider this to be a bug? What
do you expect to happen instead?

Please see [https://tex.stackexchange.com/questions/543136/problem-using-tex4ht-in-mathjax-mode-when-using-array-with-text](https://tex.stackexchange.com/questions/543136/problem-using-tex4ht-in-mathjax-mode-when-using-array-with-text)

### Technical details:

* MathJax Version:  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js">
* Client OS: Windows 10
* Browser: Any

### Supporting information:

Please see [https://tex.stackexchange.com/questions/543136/problem-using-tex4ht-in-mathjax-mode-when-using-array-with-text](https://tex.stackexchange.com/questions/543136/problem-using-tex4ht-in-mathjax-mode-when-using-array-with-text)

it has screen shot.

**Comment by dpvc** [comment]
MathJax only implements math-mode macros, not tex-mode macros, and so inside `\text{}` and the other macros that produce text-mode material, macros and special characters are not processed, with only a few exceptions.  That is, the contents of `\text{}` are presented verbatim.  The main exception is that math delimiters are handled so that math is processed inside `\text{}` (e.g., `\text{ for $x>1$}`) and some escaping is processed (e.g., `\text{ for a price of \$12.50}`.

In version 2, there is a new [text-macros](https://github.com/mathjax/MathJax/blob/legacy-v2/unpacked/extensions/TeX/text-macros.js) extension that implements some additional text-mode features, but this has not been ported to version 3 yet.

This is one of the [differences between MathJax and actual TeX](http://docs.mathjax.org/en/latest/input/tex/differences.html).
