### ISSUE TITLE
[question] How can we have different SVGs "appear" to have the same point size on a page?

### ISSUE THREAD

**Issue by maxkrieger** [mathjax/MathJax#2437]
Hi, we're working with MathJax on https://github.com/penrose/penrose, it's been working great so far with v3, but we ran into an issue we're not sure how to get around:

We're working in an environment where MathJax rendered svgs are positioned and sized in an absolute way.

What results is that SVGs with text that has additional ascenders or just upper vs lowercase letters have bigger absolute heights:

![image](https://user-images.githubusercontent.com/2660634/81867307-79ab4580-953e-11ea-861d-9f6c13b95585.png)

or with sub/superscripts:
![image](https://user-images.githubusercontent.com/2660634/81867456-bc6d1d80-953e-11ea-83fb-c64e69a39d46.png)

(the $x$ should appear the same regardless of its sub/superscripts).

**Is there a way to render text with the same "font size" but with a stable "optical size" (the height/proportions of the SVG?).** Eg: I would want each SVG in my examples above to appear with the same size, since they're based on the same font-size. Maybe a hack to pad things to a constant height?

We're using MathJax 3 with an implementation based off of https://github.com/mathjax/MathJax-demos-node/blob/master/direct/tex2svg (located here: https://github.com/penrose/penrose/blob/master/react-renderer/src/utills/CollectLabels.tsx#L2-L52)

(possibly related? #1186)

Thanks!

**Comment by dpvc** [comment]
Sorry to take so long in getting back to you on this.

I see in your code that you are trying to measure the SVG by using `getBBox()` inside a temporary SVG element.  You don't really need to do that because the SVG element generated by MathJax already includes that information in its `viewBox`, `width`, `height` and `style` attributes.  The `viewBox` has the size in the internal units of the SVG, which are consistent across all the expressions produced by MathJax.  If you determine the width and height from that, and use a constant scaling factor to scale the expressions to the size you need (the same factor for every expression) that should make for consistent sizes in your output.

Alternatively, the `width` and `height` attributes are already computed from the `viewBox` numbers, and you could scale those by a constant factor, which should give you a consistant resulting size in your output.  The `style` attribute contains a `vertical-align` value that gives the position of the baseline relative to the height of the svg, so you can align the expression vertically.  You can relate these back to the `viewBox` values by noting that the `width` (in `ex` units` corresponds to the width (in internal units) in the `viewBox`, and so the `vertical-align` value (in `ex`) can be translated back to internal units if you need that.

I think that will work better for you than trying to use the browser to measure the size.

I note that you are using the `liteDOM` adaptor.  Since you are workin in the browser, you may want to choose the browser adaptor instead, as the `liteDOM` is rather limited, and there is no need to load that extra code when the browser has a DOM implementation built in.

**Comment by maxkrieger** [comment]
Thanks so much for your help, I've finally gotten around to approaching this. I have just one more question...

> The `style` attribute contains a `vertical-align` value that gives the position of the baseline relative to the height of the svg, so you can align the expression vertically.

This is exactly what I need and seems to have fixed it! I wanted to double check something:

In our implementation we're getting `width="0" height="0"` for the SVG output, likely due to the use of liteAdaptor. I got around this by assuming that the internal units are determined by [the `ex` argument in `convert()`](https://github.com/mathjax/MathJax-src/blob/32213009962a887e262d9930adcfb468da4967ce/ts/core/MathDocument.ts#L692). Then I multiplied the `ex` argument to convert the `vertical-align` back into internal units. Is this approach reasonable? Code is here https://github.com/penrose/penrose/blob/4011e3de5003c1a1eb6f96a0a7ed398142361bd3/react-renderer/src/utils/CollectLabels.tsx#L53-L56

> I note that you are using the `liteDOM` adaptor. Since you are workin in the browser, you may want to choose the browser adaptor instead, as the `liteDOM` is rather limited, and there is no need to load that extra code when the browser has a DOM implementation built in.

This is because we may want to run this code on a server/headlessly, but that's good to know!

**Comment by maxkrieger** [comment]
@dpvc Thanks so much for your help, I've switched away from the liteDOM adaptor and, with some hacks, I've gotten your solution to work. I had one remaining unrelated question which I can open an issue for: how do you use `convert` (https://github.com/mathjax/MathJax-src/blob/master/ts/core/MathDocument.ts#L689) and also set the font size?

Are you restricted to the font size of the `body`? Do you have to create a temporary element in the DOM and do the inline processing?

**Comment by dpvc** [comment]
> how do you use convert ... and also set the font size?

I'm not entirely sure what you are asking.  Since the SVG is scaled to whatever size you want, I'm not sure what "setting the font size" actually means in this context.  

The `em` and `ex` values are probably what you are asking about, as they are usually obtained from the surrounding font.  The `em` value will be the font size (in pixels), and the `ex` is the height of the lower-case 'x' in the font (in pixels).  These are used when TeX dimensions are converted to the internal measurements.

> Are you restricted to the font size of the `body`?

No.  You can use whatever `em` and `ex` size you want.

> Do you have to create a temporary element in the DOM and do the inline processing?

No.  The `convert()` function does not require a container element to work in.

**Comment by maxkrieger** [comment]
> I'm not entirely sure what you are asking. Since the SVG is scaled to whatever size you want, I'm not sure what "setting the font size" actually means in this context.
> 
> The `em` and `ex` values are probably what you are asking about, as they are usually obtained from the surrounding font. The `em` value will be the font size (in pixels), and the `ex` is the height of the lower-case 'x' in the font (in pixels). These are used when TeX dimensions are converted to the internal measurements.

ah sorry - for context, we want to support the CSS units `pt`, `em`, `px`, etc in Penrose. If the user species `20pt` we want to send that information along to MathJax and perhaps it can give us some pixel values. Whether it's virtually or determined by the browser. The `em` values might work!

**Comment by dpvc** [comment]
When you say "a users specified `20pt`", where are they doing this?  Inside the TeX, or somewhere else?  If it is inside the TeX code, MathJax will use the `em` value to convert their `20pt` into corresponding `em` units.  So as long as you give the right `em` value to MathJax, all should be well.  If you mean outside MathJax somewhere (like how big they want the math to be), then you will need to take their `20pt` into account when you work out the scaling factor for the SVG.  The font sizes is the `em` size, and since there are 1000 internal SVG units to an `em`, you would want to scale it so that 1000 units = 20pt, or 50 units per `pt`.  So if the `viewBox` ended up being 800 units tall, you would want to scale the SVG to be  800/50 = 16 pt tall.  So setting the SVG's CSS to have `height: 16pt` (and the corresponding width computation for the width) would give you the correct size.
