### ISSUE TITLE
Using class{} with Asciimath - regression in version 2.7.8

### ISSUE THREAD

**Issue by sqlpac** [mathjax/MathJax#2450]
Hi

### Issue summary:

Regression in version 2.7.8 when using class { } { } in AsciiMath expressions.
It works well with version 2.7.5, 2.7.6, 2.7.7

(Chrome/Windows)

### Steps to Reproduce: using class{} / asciimath, when switching from 2.7.5/2.7.6/2.7.7 to 2.7.8, it does not work anymore 

    <style>
      .fo { font-size: 1.8em; color: blue; }
    </style>
    …
    
    <script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/latest.js?config=AM_CHTML-full'></script>
    …
    <p>
    ` = 1/5^4[ (81+144, 108+192), (108+192, 144+256)] = 1/5^4 [ (225, 300), (300, 400)] `   avec   `class{fo}{225/25 =9, 300/25 = 12, 400/25 =16}`
    </p>

### Technical details:

* MathJax Version: 2.7.8
* Client OS: Windows 10
* Browser: Chrome 83

### Supporting information:

 * https://www.sqlpac.com/tmp/docs/lab-mathjax.html

Best regards

**Comment by dpvc** [comment]
This actually works fine with v2.7.8.  The problem is that, now that v3 is out, CDNJS is no longer picking up any new versions of v2.  Since v2.7.8 came after v3.0 was released, it is not available on CDNJS.  In order to get v2.7.8 you will need to switch to another CDN that does include that version.  I would recommend

```
https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=AM_CHTML-full
```

which will get you the latest version of v2 (no need for `latest.js` in this case).

**Comment by sqlpac** [comment]
Hi
Perfect, very clear. Thank you very much.
