### ISSUE TITLE
MathJax swallows tags after execution

### ISSUE THREAD

**Issue by cout-DOMINIC** [mathjax/MathJax#2452]
@dpvc 
Sorry for my very short issue report. I was just to fast typing in my frustration. But now I know what my problem was. Thanks for your help. Cheers

**Comment by cout-DOMINIC** [comment]
```
	<tr>
		<td><div>
		<p>
                       TEST1
               </p>
			</div>
               </td>

	         <td><div id="enFormula">
			<math:math>
				<mstyle displaystyle="true"> <mo></mo> </mstyle>
			</math:math>
			<script type="math/asciimath"></script>
			</div>
		</td>

		<td><div>
		<p>
                       TEST2
               </p>
                        </div></td>

	</tr>
```

- TEST 1 is visible
- enFormula is visible
- TEST 1 is not visible

**Comment by dpvc** [comment]
I am not able to reproduce your results.  Can you provide a complete HTML page that exhibits the problem?  Your snippets are insufficient.  For example, you don't say what MathJax combined configuration you are using (e.g., what input and output format are being used), or what version of MathJax you are using, or what browser you are using.  (You ignored most of the template for the issue submission.)  You also don't indicate what the contents of the element with `id="_formulaEN_id"` is that is being inserted into the page.  

Your snippet includes some MathML and an empty script tag for AsciiMath input.  You don't indicate which input format you are using, so I don't know which of these two will be the jax that is obtained from `MathJax.Hub.getAllJax('enFormula')[0]`.  But since your call to `["Text", math, 'p = ' + source.value]` would only make sense for the AsciiMath element, I'm assuming you are using AsciiMath input, so something like `MathJax.js?config=AM_CHTML` rather than `MathJax.js?config=TeX-MML-AM_CHTML`, which would process both inputs, where the first jax would be the MathML element; it would not make sense to set this element's text to something starting with `p =`.

If I use your example with the `AM_CHTML` configuration, and some sample input in a `<textarea id="_formulaEN_id">`, everything works fine for me.

So you will need to provide a complete example in order to get any additional help.
