### ISSUE TITLE
MathJax web demo tex-mml.html appears broken

### ISSUE THREAD

**Issue by cl4yton** [mathjax/MathJax#2453]
The web demo "MathJax v3 with TeX input and MathML output" appears to be broken.

Browsers (with clean cache and history):
Chrome version 83.0.4103.97 (Official Build) (64-bit)
Firefox version 77.0.1 (64-bit)

Attempts to load the page
https://mathjax.github.io/MathJax-demos-web/tex-mml.html

... consistently result in error:
```
Uncaught (in promise) Error: MathJax retry
    at Object.e.retryAfter (core.js:formatted:3301)
    at o.checkLoading (menu.js:formatted:229)
    at Object.renderDoc (core.js:formatted:1639)
    at M.renderDoc (core.js:formatted:1655)
    at o.I.render (core.js:formatted:1807)
    at Object.pageReady (tex-mml.html:23)
    at startup.js:formatted:926
```

**Comment by dpvc** [comment]
Thanks for the report.  It does appear that the demo needs updating after some recent changes.  

The main fix is to add

```
      menuOptions: {
        settings: {
          assistiveMml: false
        }
      },
```

inside the `options` configuration block in order to disable the assistive MathML output.  It is the dynamic loading of the assistive MathML extension that was causing the error you are seeing, and since you will be generating the MathML directly, there is no need for this extension.

You may also want to add

```
      ready() {
        MathJax.startup.defaultReady();
        MathJax.startup.document.menu.menu.findID('Accessibility', 'AssistiveMml').disable();
      },
```

just inside the `startup` configuration block.  This will disable the menu item for the assistive MathML item so that it can't be turned on by the user.

Finally, changing

```
      pageReady: () => MathJax.startup.document.render()
```

to

```
      pageReady() {
        MathJax._.mathjax.mathjax.handleRetriesFor(() => {
          MathJax.startup.document.render();
        });
      }
```

so that if anything else has to be dynamically loaded, it will be handled properly.

I will make these changes to the example in the demos repository.

**Comment by dpvc** [comment]
I've made the update.

**Comment by cl4yton** [comment]
Thank you @dpvc , works seamlessly for me now, and thank you for the explanation.
