### ISSUE TITLE
Characters with a diacritic in a math environment renders small in chrome

### ISSUE THREAD

**Issue by Sjiep** [mathjax/MathJax#2461]
### Issue Summary

The rendering of characters that use a diacritic symbol, e.g. é, ô, ü as text inside a math environment looks a bit strange on Chrome since they become smaller then the surrounding text. Is this a bug in Chrome or Mathjax?

With Chrome
![image](https://user-images.githubusercontent.com/5003111/85694689-a45cf200-b6d7-11ea-842a-a95ce037c6ed.png)

For Firefox the rendering is ok.
![image](https://user-images.githubusercontent.com/5003111/85694747-b5a5fe80-b6d7-11ea-9527-431cc884ee65.png)

Rendered outside a math environment
![image](https://user-images.githubusercontent.com/5003111/85695378-45e44380-b6d8-11ea-9159-1da1e04dcce5.png)

### Steps to Reproduce:

Run the following tex snippet on the mathjax demo page
```
$$
\text{Longueur du côté opposé à }\alpha
$$
Longueur du côté opposé à
```
check the rendered output in Chrome and Firefox

### Technical details:

* MathJax Version: 2.7.0 and 3.0.5
* Client OS: Ubuntu 20.04
* Browser: Chrome 83.0.4103.106, Firefox 77.0.1

**Comment by dpvc** [comment]
The reason for this is that the MathJax fonts don't include characters with diacritical marks, and so when such a character is used, it must be taken from a different font.  The font will be a system font (one installed on the reader's computer), but MathJax doesn't know what font that will be, or what its font characteristics are.  MathJax sets the font size to be the size of the surrounding font, but if the diacritical is not taken from that font, the size may not match exactly.  The system font used may be different for different users (you can see that the diacritical characters in your Chrome image is different from the ones in the Firefox (and outside of math) images, not just in their size, but also in their shape: they are not the same font in both images, and if the ex-height of the two fonts are not the same as the text font surrounding the math, then that could account for the difference you are seeing.

MathJax has a setting that controls whether it should use its own fonts, or try to use the surrounding text font for text-mode material like that within `\text{}` macros.  If you enable that, the text will all come from the same font.  In version 3, you would use

``` javascript
MathJax = {
  chtml: {
    mtextInheritFont: true
  }
};
```

to enable that feature.  Unfortunately, there is a bug that prevents it from working entirely properly in v3 (see #2401 and #2189), which will be fixed in the next release.  In the meantime, you can add

``` css
mjx-utext {
  font-family: MJXZERO, sans-serif
}
```

(or substitute whatever the surrounding font is for `sans-serif` above) to your CSS in order to work around the problem until the next release.

**Comment by Sjiep** [comment]
Thanks for your detailed answer!
