### ISSUE TITLE
MathJax equations is not mobile responsive?

### ISSUE THREAD

**Issue by DibasDauliya** [mathjax/MathJax#2465]
I have this equation of MathJax in my site, while viewing the size of the site in mobile view, all the other text are responsive but the equations of mathJax are not responsive.
How can I make these responsive, can you please help me? I've attached the screenshot below.

This is my equation:

``` latex
$\begin{align}
\text{Power set of A, P(A)} & = \{ \emptyset, \{ x\}, \{ y\}, \{ z\}, \{ x, y\}, \{ y, z\}, \{ x, z\}, \{ x, y, z\} (again) \emptyset, \{ x\}, \{ y\}, \{ z\}, \{ x, y\}, \{ y, z\}, \{ x, z\}, \{ x, y, z\} (again) \emptyset, \{ x\}, \{ y\}, \{ z\}, \{ x, y\}, \{ y, z\}, \{ x, z\}, \{ x, y, z\}\} \\
\end{align}$
```

I tried to add this but still is not responsive:

``` html
        <script type="text/x-mathjax-config">
        MathJax.Hub.Config({
         "HTML-CSS": { linebreaks: { automatic: true } },
                 SVG: { linebreaks: { automatic: true } }
        });
        </script>
```

Screenshot:
![Screenshot (409)](https://user-images.githubusercontent.com/51583004/86532621-41473880-beeb-11ea-9e8b-710cc9ef80e9.png)

**Comment by dpvc** [comment]
The `align` environment produces a table, and line breaking with tables is not as good as you might like.  The line breaking within a cell is done based on the full width of the expression, and doesn't take into account the material in other columns. In your case, the right-hand-side of the equal sign is in a column, and that is broken to the full width of the mobile device.  Because your initial column contains a long text string (that is not breakable), the right-hand-side of the expression (broken to the full width of the divide) may extend too far to the right by the width of the left-hand-side of the equal sign.

Of course, this example doesn't require an `align` environment since it is just one equality.  If you remove the alignment, the expression will wrap appropriately:

``` latex
$$
\text{Power set of $A$, $P(A)$} = \{ \emptyset, \{ x\}, \{ y\}, \{ z\}, \{ x, y\}, \{ y, z\}, \{ x, z\}, \{ x, y, z\} (again) \emptyset, \{ x\}, \{ y\}, \{ z\}, \{ x, y\}, \{ y, z\}, \{ x, z\}, \{ x, y, z\} (again) \emptyset, \{ x\}, \{ y\}, \{ z\}, \{ x, y\}, \{ y, z\}, \{ x, z\}, \{ x, y, z\}\}
$$
```

produces

<img width="449" alt="wrap" src="https://user-images.githubusercontent.com/432782/88096072-16ecb080-cb64-11ea-87e3-d2b0e0fd2799.png">

Wrapping within tables is on our list of things to improve, but is a complicated process.

As an aside, note that your initial expression

``` latex
$\begin{align}
\text{Power set of A, P(A)} & = \{ \emptyset, \{ x\}, \{ y\}, \{ z\}, \{ x, y\}, \{ y, z\}, \{ x, z\}, \{ x, y, z\} (again) \emptyset, \{ x\}, \{ y\}, \{ z\}, \{ x, y\}, \{ y, z\}, \{ x, z\}, \{ x, y, z\} (again) \emptyset, \{ x\}, \{ y\}, \{ z\}, \{ x, y\}, \{ y, z\}, \{ x, z\}, \{ x, y, z\}\} \\
\end{align}$
```

does not need the outer dollar signs, as the `\begin{align}...\end{align}` will be picked up by MathJax as a math block automatically.  Also, the `align` environment is a display-style environment, so should not be within in-line delimiters in any case.

**Comment by DibasDauliya** [comment]
@dpvc I tested with same code in mine but its is still not responsive as of your screenshot. Can you please share me your JavaScript for the configuration of MathJax?
Mine is:
```
<script type="text/javascript">
        window.MathJax = {
            TeX: {
              extensions: ["mhchem.js"]
            },
            tex2jax: {
              inlineMath: [
                ['$', '$'],
                ["\\(", "\\)"]
              ]
            }
          };
        </script>
        <script type="text/x-mathjax-config">
            MathJax.Hub.Config({
              tex2jax: {inlineMath: [["$","$"],["\\(","\\)"]]}
            });
            
          </script>
        
        <script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_CHTML">
        </script>
```

And, another thing, as you said $ sign should not be in ```\begin{align}...\end{align}```??. Is my following code wrong? I don't want  those math to be in the center of the screen 
BUT I want to align the text after "A &cup; B =" serially. So wraped ```\begin{align}...\end{align}``` with the dollar sign. 

```
<li class="ans">Here, <br>To Prove: A - B = A &cap; $\overline{B}$, where A and B are subset of &cup; <br><br>
        Taking L.H.S, <br>
        $\begin{align}
        \overline{A \cup  B}  & = \{x : x \in A - B\} \\
 & = \{x : x \in \text{A and x} \notin B\} \\ 
 & = \{x : x \in \text{A and x} \in \overline{B}\} \\ 
 & = \{x : x \in A \cap \overline{B}\} \\ 
\end{align}$
    </li>
```

**Comment by dpvc** [comment]
This is the file I tested with

``` html
<!DOCTYPE html>
<html>
<head>
<title>Test of mobile linebreaks</title>
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  tex2jax: {inlineMath: [['$','$']]},
  "HTML-CSS": { linebreaks: { automatic: true } },
  CommonHTML: { linebreaks: { automatic: true } },
  SVG: { linebreaks: { automatic: true } }
});
</script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS_HTML">
</script>
</head>
<body>

$$
\text{Power set of $A$, $P(A)$} = \{ \emptyset, \{ x\}, \{ y\}, \{ z\}, \{ x, y\}, \{ y, z\}, \{ x, z\}, \{ x, y, z\} (again) \emptyset, \{ x\}, \{ y\}, \{ z\}, \{ x, y\}, \{ y, z\}, \{ x, z\}, \{ x, y, z\} (again) \emptyset, \{ x\}, \{ y\}, \{ z\}, \{ x, y\}, \{ y, z\}, \{ x, z\}, \{ x, y, z\}\}
$$

</body>
</html>
```

It uses the latest version of MathJax (2.7.8) rather than version 2.7.4 that you are suing, but that shouldn't be an issue.  I also used a smaller configuration file (`TeX-AMS_HTML`) than you are.

Note that your configuration does not turn on automatic line breaks, so that may be why your test didn't work.  Your original message indicated that you used

``` html
        <script type="text/x-mathjax-config">
        MathJax.Hub.Config({
         "HTML-CSS": { linebreaks: { automatic: true } },
                 SVG: { linebreaks: { automatic: true } }
        });
        </script>
```

but that doesn't appear in your configuration above.  Also, note that you turned on line breaks for HTML-CSS and SVG output formats, but not for CommonHTML, but you are loading `TeX-MML-AM_CHTML`, which uses CommonHTML output.  Since line breaks are not enabled for CommonHTML, that could also be the source of your problem.


You don't need the 

``` html
           <script type="text/x-mathjax-config">
            MathJax.Hub.Config({
              tex2jax: {inlineMath: [["$","$"],["\\(","\\)"]]}
            });
          </script>
```

in your configuration, since it is already included in the previous configuration just above it.  

> Is my following code wrong?

Yes, you should not use dollar signs around `\begin{align}...\end{align}`.  The `align` environment is a display-style environment, and it acts as math delimiters all by itself, so there is no need for any other delimiters around it.  If you want to use an alignment in an in-line setting, use `$\beign{aligned}...\end{aligned}$`, as the `aligned` environment is the corresponding in-line version.

I would recommend

``` html
<li class="ans">Here, <br>
To Prove: $A - B = A \cap \overline{B}$, where $A$ and $B$ are subset of $\cup$ <br><br>
aking L.H.S, <br>
$\begin{aligned}
        \overline{A \cup  B}  & = \{x : x \in A - B\} \\
                              & = \{x : x \in \text{A and x} \notin B\} \\ 
                              & = \{x : x \in \text{A and x} \in \overline{B}\} \\ 
                              & = \{x : x \in A \cap \overline{B}\} \\ 
\end{aligned}$
</li>
```

> BUT I want to align the text after "A ∪ B =" serially. So wraped `\begin{align}...\end{align}` with the dollar sign.

As I said, line breaking within tables (which is what the `align` and `aligned` environments produce) can lead to equations that exceed the width of the container, as in your case.  If you don't want that to happen, you can't use an environment that produces tables.  That means you can't reserve space on the left and will have to accept centering.  It may be that this will be fixed in the future, but for now that is the situation.

Finally, I would recommend using math mode for all mathematical expressions rather than mixing HTML, entities, and math as you do with `To Prove: A - B = A &cap; $\overline{B}$`, which is better as `To Prove: $A - B = A\cap \overline{B}$`.  This will produce more consistent results, and will allow proper support for screen readers and those with other assistive needs.

**Comment by DibasDauliya** [comment]
@dpvc I replaced my config code of MathJax with yours and it is now working. 👍 

> Note that your configuration does not turn on automatic line breaks, so that may be why your test didn't work. Your original message indicated that you used

Yes, exactly.

I replaced my config code with yours it it worked. 👍 Okay, my problem is solved and I'm going to close the issue.

Before, I want to take a advice from you that, people say, putting MathJax config's js above the `</body>` makes it load faster. Is it true? What can I do to make the equation load faster in slow internet connection?

**Comment by dpvc** [comment]
> putting MathJax config's js above the `</body>` makes it load faster. Is it true?

No, not really.  It will make the *page* appear sooner (with the math not yet processed), but will probably make the math show up slower.  MathJax won't do any of its typesetting until the DOMContentLoaded event occurs, and that won't happen until the `</body>` in any case.  But MathJax can do things like process the configuration, load the needed files (like the `TeX-AMS_CHTML` file), set up CSS style and pre-load some fonts before the `</body>`.  The earlier MathJax is loaded, the sooner it can start doing those tasks.

The file I list above has a `<script>` tag that will prevent the rest of the page from loading until MathJax.js is downloaded, so that means the page will not show up at all until then.  (It was just a test file, not optimized for production use.)  Adding the `defer` or `async` attribute will prevent MathJax from blocking the page, so that might make your (un-typeset) page appear sooner for your users, giving the impression of a faster page.  But it will put off MathJax doing its work until later (`defer` will act much like putting the MathJax script at the bottom of the page, while `async` will run MathJax's startup code as soon as it is downloaded.  You can experiment with these and see which works best for you.

As for the actual typesetting, there is not much you can do to speed that up.  Note that HTML-CSS is the slowest output processor, with CommonHTML and SVG being roughly equivalent (CommonHTML is usually a bit faster, but not always).

**Comment by DibasDauliya** [comment]
Oh, Thank you so much. 🥇 
> The file I list above has a <script> tag that will prevent the rest of the page from loading until MathJax.js is downloaded, so that means the page will not show up at all until then. (It was just a test file, not optimized for production use 

So, In the nutshell, What would be the **BEST** configuration method for the MathJax **during production** in your view? Can you please please share the code that you use during production (I mean complete HTML document just containing codes for MathJax configuration)?

**Comment by dpvc** [comment]
> What would be the *BEST* configuration method for the MathJax *during production* in your view?

There is no one answer to that.  It depends on the kind of web site you run, that nature of your content, the expected users for your site, and what your priorities are.

A good general approach is to put the `Mathjax = {...}` configuration in the document head followed by the script that loads the MathJax component, with an `async` attribute.  That is the setup used for the examples in the [MathJax web demos](https://github.com/mathjax/MathJax-demos-web#mathjax-demos-web) repository.  You can see the code there.
