### ISSUE TITLE
Attempting to set the enrichSpeech option results in an error in v3

### ISSUE THREAD

**Issue by Cdplourde** [mathjax/MathJax#2467]
I followed the docs [here](http://docs.mathjax.org/en/latest/options/accessibility.html?highlight=enrichspeech#the-configuration-block)

When attempting to set the 'enrichSpeech' option (using text-mml-chtml.js):

` 
 MathJax = {
   options: {
     enrichSpeech: 'deep'
   }
 }
`

The error `MathJax(?): Invalid option "enrichSpeech" (no default value)` occurs.

**Comment by dpvc** [comment]
The reason is that the extension is not included in `tex-mml-chtml.js`, and so you must load it explicitly (in addition to setting how much speech to include).  You should use

``` html
<script>
MathJax = { 
  options: {enrichSpeech: 'deep'},
  loader: {load: ['a11y/semantic-enrich']}
};
</script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
```

I admit that the documentation is not clear on this.  I am in the process of updating it for v3.1, and will add more information about loading the extension.
