### ISSUE TITLE
insert the same style to head repeatedly, cause the website too lag

### ISSUE THREAD

**Issue by jerryc127** [mathjax/MathJax#2468]
```html
script.
  window.MathJax = {
      loader: {
        source: {
          '[tex]/amsCd': '[tex]/amscd',
          '[tex]/AMScd': '[tex]/amscd'
        }
      },
      tex: {
        inlineMath: [['$', '$'], ['\\(', '\\)']],
        tags: 'ams',
      },
      options: {
        renderActions: {
          findScript: [10, doc => {
            document.querySelectorAll('script[type^="math/tex"]').forEach(node => {
              const display = !!node.type.match(/; *mode=display/);
              const math = new doc.options.MathItem(node.textContent, doc.inputJax[0], display);
              const text = document.createTextNode('');
              node.parentNode.replaceChild(text, node);
              math.start = {node: text, delim: '', n: 0};
              math.end = {node: text, delim: '', n: 0};
              doc.math.push(math);
            });
          }, '', false],
        }
      }
    }

script(type="text/javascript" id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js")
```

it will insert the same style(id = MJX-CHTML-styles) to head repeatedly, cause the website too lag

![eee](https://user-images.githubusercontent.com/16351105/87008812-e0737500-c1f6-11ea-8e6c-6676095d9edd.gif)

**Comment by dpvc** [comment]
If you call MathJax to typeset the page more than once, the style element will be updated.  For the CHTML output jax, this is because information about the characters used in your math is part of the stylesheet, and so if those characters change (due to new content on the page), the stylesheet must be updated.

It looks like your site might be a blog or Q&A site; is each post is loaded separately and typeset by MathJax, that could account for the multiple updates to the stylesheet.  It would be possible to disable the output of the stylesheet during the individual typesetting calls, and have your system update the stylesheet once after all the content has been loaded (or you could simply postpone the typesetting altogether until all the content is loaded and then typeset the complete page once, which would be more efficient than typesetting the parts separately as they come in).

**Comment by jerryc127** [comment]
if i change the src to 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js'
it work
but use the 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'
it insert the same style to head repeatedly, i try to record, it need to 31 seconds to finish. it is unusual,
how to solve it ?

**Comment by jerryc127** [comment]
This problem appeared in the localhost test
I try to push to github page. it work..

**Comment by dpvc** [comment]
OK, thanks for the update.
