### ISSUE TITLE
Fontsize in MathML

### ISSUE THREAD

**Issue by Vaclav-Laurin** [mathjax/MathJax#2479]
Hi!

I can't increase font size of the MathML equations (that inserted in MS Word by Python-docx).
Standart MathML attributes like mathsize or maxsize or scriptminsize don't work.
There are no any problems with the running of code but MathML equation has CambriaMath font with font size 11 (I need to make it 14).
Any others attributes for setup the math font (like fontweight or fontcolor others) don't work.

What I do wrong?

Here is an example of code that I used:
``` import docx
    from sympy import*
    from sympy.abc import*
    from sympy.printing.mathml import mathml
    from lxml import etree    
    
    math_ml = '''
    <math xmlns="http://www.w3.org/1998/Math/MathML" mathsize='50pt' fontweight='bold'>
        <mstyle>
        <msub>
            <mi>t</mi>
            <mi>Н-Р</mi>
        </msub>
        <mi>=</mi>
        <mfrac>
        <msrow>
            <msub>
                <mi>t</mi>
                <mi>Н</mi>
                </msub>
                <mi>+</mi>
                <msub>
                    <mi>t</mi>
                    <mi>Р</mi>
                </msub>
                <mi>+</mi>
                <msub>
                    <mi>t</mi>
                    <mi>Д</mi>
                </msub>
            </msrow>
            <mn>60</mn>
        </mfrac>
        </mstyle>
    </math>'''

    tree = etree.fromstring(math_ml)
    mml2omml_stylesheet_path = 'MML2OMML.XSL'
    xslt = etree.parse(mml2omml_stylesheet_path)
    transform = etree.XSLT(xslt)
    new_dom = transform(tree)

    doc = docx.Document ()
    p = doc.add_paragraph()
    p._element.append(new_dom.getroot())

    report.save('Report.docx')```

**Comment by dpvc** [comment]
Your code does not seem to involve MathJax in any way, so it is probably misplaced to report the issue here.  The problem is probably with the XSLT stylesheet that is converting the MathML, but again, that has nothing to do with MathJax.  It may be that the xsl file doesn't handle `mathsize` and `fontweight` properly, for example.  Note that `fontweight`, 'fontfamily`,  `fontsize`, `color`, `background` and similar attributes are deprecated in MathML3 in favor of directly setting `style` properties, or using `mathsize`, `mathcolor`, and `mathbackground`.  There never was a `fontcolor` attribute.

From a Google search, the xsl stylesheet you are using appears to be a Microsoft product, so you will have to report the issue to them.

As an aside, your MathML is not correct.  The `<msrow>` tag should only appear within `<mstack>` or `< mlongdiv>`, so is missed here.  It should just be an `<mrow>`.  Also, your `<mi>=</mi>` and `<mi>+</mi>` probably should be `<mo>=</mo>` and `<mo>+</mo>` to get the semantics and the spacing correct.  Finally, your `<mstyle>` is unneeded, since it sets no styles.  Your indenting is also off, though that doesn't affect the output.

Finally, although you are not using MathJax, MathJax does render the MathML properly (once the `<msrow>` is changed to an `<mrow>`), in the larger font size, and with bold.
