### ISSUE TITLE
&prime; entity in mml-svg output displays incorrectly

### ISSUE THREAD

**Issue by sakertp** [mathjax/MathJax#2480]
The &prime; entity does not display correctly using mml-svg output.

The following tagging `<mo>&prime;</mo>` does not display correctly using mml-svg output, although it does display correctly using mml-chtml output. I'm running Windows 10 and IE 11 32 bit mode. I'm also referencing the following script "polypill.min.js?features=es6".

Compare the output of <mo>&prime;</mo> using both mml-svg output and mml-chtml output. The character only displays correctly using the mml-chtml output. I consider this a bug because the prime character does not display correctly.

Technical details:

* MathJax Version: 3.0
* Client OS: Windows 10
* Browser: IE 11 32 bit

**Comment by dpvc** [comment]
I am not able to reproduce your issue.  The prime is properly rendered for me.  Can you be more specific about what "does not display correctly" means?  Can you give the complete expression you are trying to view?  And your full MathJax configuration?  Or better yet, a minimal (non-)working example page?

**Comment by sakertp** [comment]
David,

I should be able to provide you with a sample file and screen shots soon. Thank you for your help.

Tom Saker

________________________________

**Comment by sakertp** [comment]
I attached a screen shot and the HTML file. You'll just have to remove the .txt extension from the HTML file and update the path to MathJax and the polypill script. Let me know if you need additional information. Thanks.

![mml-svg_output_bug_#2480_screenshot](https://user-images.githubusercontent.com/68758609/89672589-e8383f00-d8b2-11ea-9524-723628d8e907.png)
[mml-svg_output_bug#2480.html.txt](https://github.com/mathjax/MathJax/files/5042843/mml-svg_output_bug.2480.html.txt)

**Comment by dpvc** [comment]
Your second expression is (simplified bit):

``` html
<math display="block">
  <mi>T</mi>
  <mo>′</mo>
</math>
```

however, the MathML specification considers the prime to be a pseudo script, and it [suggests](https://www.w3.org/TR/MathML3/chapter7.html#chars.pseudo-scripts) that this should be encoded as a superscript:

``` html
<math display="block">
  <msup>
    <mi>T</mi>
    <mo>′</mo>
  </msup>
</math>
```

In this situation, the prime will be reduced in size and raised, as any other superscript would, and so the glyph for the prims is larger and lower than you are expecting so that it displays properly in the preferred notation for MathML.  While your encoding is not illegal, the specification indicates that "such forms should generally be avoided."

So this is the the expected output from MathJax for this construct.  If you use the superscript notation, you will get the result you are looking for.

**Comment by sakertp** [comment]
Unfortunately I use MathFlow for tagging and don't think I can control the underlying tagging. I will test the tagging you suggested.
