### ISSUE TITLE
<msqrt> displays incorrectly using mml-chtml output

### ISSUE THREAD

**Issue by sakertp** [mathjax/MathJax#2481]
<msqrt> displays incorrectly using mml-chtml output.

<msqrt> displays incorrectly using mml-chtml output, although it displays correctly using mml-svg output.
I'm also referencing the following script "polypill.min.js?features=es6".

### Steps to Reproduce:

``` html
<msqrt>
    <mrow>
        <mfrac>
            <mrow>
                <mn>123</mn>
            </mrow>
            <mrow>
                <mi mathvarient='normal'>xxx></mi>
            </mrow>
        </mfrac>
    </mrow>
</msqrt>
```

I consider this a bug because the square root symbol in the above tagging doesn't display contiguously. It looks like a check mark next to the fraction with a line above the fraction and they do not touch each other.

### Technical details:

* MathJax Version: 3.0
* Client OS: Windows 10
* Browser: IE 11 32 bit

**Comment by dpvc** [comment]
I am not able to reproduce your result.  The square root that you provided renders properly with both SVG and CHTML output for me.  Can you be more specific about what "displays incorrectly" means in this case?  And can you provide a complete (non-)working example file that illustrates your issue?

**Comment by sakertp** [comment]
David,

I should be able to provide you with a sample file and screen shots soon. Thank you for your help.

Tom Saker

________________________________

**Comment by sakertp** [comment]
I attached a screen shot and the HTML file. Let me know if you need additional information.

![mml-chtml_output_bug_#2481_screenshot](https://user-images.githubusercontent.com/68758609/89671798-9cd16100-d8b1-11ea-861e-3371ae5f6c18.png)
[mml-chtml_output_bug#2481.html.txt](https://github.com/mathjax/MathJax/files/5042811/mml-chtml_output_bug.2481.html.txt)

**Comment by dpvc** [comment]
It looks like the fonts are not being downloaded, which is the source of the issue in this case.  There are two possibilities for why that might be the case.  Either the browser is configured to not allow the page to change fonts, or you are losing the file using a `file://` URL rather than an `http://` URL.  I suspect that this is the case, but it is not clear form your message whether you are going through a web server or not.

The reason `file://` URLs are a problem is due to IE's same-origin security policy, which (for local files) is considered to be the directory containing the HTML file you are viewing, and any subdirectories.  Since you are loading MathJax from `../../MathJax/mml-chtml.js`, that is not considered the same origin as the HTML page.  Loading javascript from another origin is allowed (like loading from a CDN), but not loading other kinds of files, like fonts.  So MathJax itself can load, but not its fonts.

I suspect that is what is happening for you.  You may need to run a web server locally in order to test your pages if you have been using `file://` URLs.  Even a simple one like `python -m SimpleHTTPServer 8000` should do it for you (if you have python installed).

So I suspect that this is not a MathJax bug, but the normal operation of IE in a local-file situation.

**Comment by sakertp** [comment]
You are correct in your assumption. I am loading MathJax from a local drive. I will test it using a web server.
