### ISSUE TITLE
tex-mml-svg.js  typeset got unnecessary mjx-assistive-mml node in 3.0.5

### ISSUE THREAD

**Issue by qq240814476** [mathjax/MathJax#2482]
I use tex-mml-svg to transform tex to svg, when i use typeset in 3.0.0 , i got just mjx-math node.

But when i update 3.0.5, I got not both mjx-math node and mjx-assistive-mml node 

how can i just got result same as 3.0.0, which i should config?

**Comment by dpvc** [comment]
If you are using this within a web page, then you should leave the assistive MathML in place, so that users with visual limitations can use screen readers to read the math in your page.  Your sighted users can turn this off using the MathJax contextual menu in the "Accessibility" submenu by unchecking the "Insert Hidden MathML" option.

If you are creating svg to be saved to a file, you may find it easier to use the [node-based command-line tools](https://github.com/mathjax/MathJax-demos-node) rather than a web page.  Otherwise, you can also use the contextual menu to prevent the assistive MathML from being inserted.

**Comment by qq240814476** [comment]
> If you are using this within a web page, then you should leave the assistive MathML in place, so that users with visual limitations can use screen readers to read the math in your page. Your sighted users can turn this off using the MathJax contextual menu in the "Accessibility" submenu by unchecking the "Insert Hidden MathML" option.
> 
> If you are creating svg to be saved to a file, you may find it easier to use the [node-based command-line tools](https://github.com/mathjax/MathJax-demos-node) rather than a web page. Otherwise, you can also use the contextual menu to prevent the assistive MathML from being inserted.

thank u very much ！👍🏻👍🏻👍🏻
