### ISSUE TITLE
Missing utils folder inside mathjax 3.0.5

### ISSUE THREAD

**Issue by pankajt1983** [mathjax/MathJax#2483]
Hi Team,

I am using mathjax v3.0.5 in my sample nodejs application for converting MathML expressions to SVG imags. The conversion seems to be working but I am seeing this error at the end of the program. The `utils` folder seems to be missing altogether.

(node:3224) UnhandledPromiseRejectionWarning: Error: Cannot find module '/home/dev/workspace/mathjax-poc/node_modules/mathjax/es5/util/entities/a.js'

Any way i can resolve them. Thanks!

**Comment by dpvc** [comment]
If you are using MathJax components, you should include `'input/mml/entities'` in the `load` array of your `loader` configuration block.  E.g.,

``` javascript
MathJax = {
}

**Comment by dpvc** [comment]
If you are using MathJax components, you should include `'input/mml/entities'` in the `load` array of your `loader` configuration block.  E.g.,

``` javascript
MathJax = {
  loader: {
    load: ['input/mml/entities']
  }
}
```

in order to load all the entity definitions (MathJax only initially includes entities for common mathematical use).

If you are importing MathJax modules directly, you should use

``` javascript
import 'mathjax-full/js/util/entities.all.js';
```

to accomplish the same thing.  (You will need the `mathjax-full` package rather than just `mathjax` in that case.)

**Comment by pankajt1983** [comment]
Thanks, it worked.
