### ISSUE TITLE
Color of reference link to an equation in SVG output cannot be customized using CSS

### ISSUE THREAD

**Issue by songcai** [mathjax/MathJax#2485]
### Issue Summary

When using SVG output (`tex-svg.js`), if I use `\eqref` to refer to a labelled display equation, the link color in the rendered HTML is "blue" by default. This is governed by the following code chunk in `tex-svg.js`:

```
'mjx-container[jax="SVG"] > svg a':{fill:"blue",stroke:"blue"}},
```

There is no documentation for MathJax 3 on how to customize the link color (for example, using "red") in SVG output without changing the original `tex-svg.js`. The closest I found is some instruction given [here](http://docs.mathjax.org/en/latest/upgrading/v2.html#output-changes) on using CSS to change text font in SVG output. According to this, I experimented to put the following style sheet in HTML header before invoking tex-svg.js:

```
<style>
    mjx-container > svg a {
        fill: red;
        stroke: red;
    }
</style>
```
However, this does not have any effect on the color of the links to equations.

Now, here are my questions: 
  * Is CSS the correct way to change the color of the link generated by `\eqref` in SVG output? If so, what is the correct way of writing the CSS and putting it in HTML header. 
  * Or, is it true that in MathJax 3, the link color in SVG output is not customizable by users?

### Technical details:

* MathJax Version: 3.0.5 (latest commit: 72aba4aafd2ebfb1bda3c9445c69f4b2e7956b84)
* Client OS: macOS Cantalina 10.15.6
* Browser: Firefox 78.0.2, Safari 13.1.2 (15609.3.5.1.3)

### Supporting information:

Source code of a minimal example HTML:

```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
  <title>Minimal Example.html</title>
  <style>
    mjx-container > svg a {
      fill: red;
      stroke: red;
    }
  </style>
  <script type="text/javascript" id="MathJax-script" async
    src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js">
  </script>
</head>
<body>

<p>Here is a labelled display equation:<span class="math display">\[
\begin{align}\label{eq}
  a + b = c. \tag{1}
\end{align}
\]</span>

<p>Referring to the above equation using <code>\eqref{eq}</code> gives
a blue-colored link: <span class="math inline">\eqref{eq}</span>,
although I tried to customize the color to red using CSS in the
header of the HTML.<p>

</body>
</html>
```

**Comment by dpvc** [comment]
The reason your CSS fails is that it is less specific than the CSS used by MathJax (since you use just `mix-container` while MathJax uses `mix-container[jax="SVG"]`, so MathJax's CSS takes precedence.  But adding the missing `[jax="SVG"]` is not enough to get your CSS to be used since MathJax will add its CSS to the end of the `<head>`, and so its CSS will override yours again.

You could use `! important` to make your override the CSS that follows, or you could make your CSS more specific than MathJax's, for example:

``` html
<style>
    mjx-container[jax="SVG"] > svg a[href] {
        fill: red;
        stroke: red;
    }
</style>
```

Here, the addition of `[href]` makes the selector more specific, so it will override MathJax's less-specific one.

This was discussed recently in the [MathJax User's Forum](https://groups.google.com/forum/?fromgroups#!topic/mathjax-users/fsnBE-oxlKQ).

**Comment by songcai** [comment]
Thanks!

Both methods (adding `!important` and uisng `[href]`) worked for me.

I did try using `mix-container[jax="SVG"]` but as you said, using that alone is not enough.
