### ISSUE TITLE
\,, interpreted as a macro instead of a space followed by a comma

### ISSUE THREAD

**Issue by bdtc** [mathjax/MathJax#2488]
### Issue Summary

A backslash followed two commas is interpreted as a single macro instead of as a thin space followed by a comma.

### Steps to Reproduce:

`A \,, B` should show a thin space then a comma.

### Technical details:

`cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js` as of 07/31/2020.

### Supporting information:
```
<!DOCTYPE html>
<html lang="en-US">
<head>
<meta charset="UTF-8" />

<script
         id="MathJax-script"
         src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"
></script>

</head>
<body>

<p>
\[a \„ b\]
</p>

</body>
</html>
```

**Comment by dpvc** [comment]
> `A \,, B` should show a thin space then a comma.

It does.  The problem is that that is not what is in your example page.  The example page has `a \„ b`, where the `„` is the single unicode character U+201E (DOUBLE LOW QUOTATION MARK), not the two commas that are in your "steps to reproduce".  Because `\` followed by a single (non-alphabetic) character forms a control sequence (i.e., macro name), `\„` *is* in fact a single macro, and should produce the undefined macro error.  So this is the correct behavior.

**Comment by bdtc** [comment]
Sure enough.  It turns out that lmodern and several other TeXGyre fonts have a ligature for two commas in a row, similar to two backward or forward quotes.  I didn't notice them being picked up by pdftotext for the Lwarp package.  Sorry.  The comma ligature is now disabled for Lwarp's MathJax conversion, so all is good.

**Comment by dpvc** [comment]
Ah, ligatures.  I hadn't thought of that.  I wondered how you had produced the U+201E character.  Of course, there are some languages that use low right-hand quotation marks, so that makes sense.  Thanks for the info.
