### ISSUE TITLE
Double prime marker in MathML looks smaller in size when enclosed in <mi> in v2.7.7

### ISSUE THREAD

**Issue by sadhikay** [mathjax/MathJax#2498]
When the double prime marker is declared with the following syntax in mathml it looks smaller in size in v2.7.7.
But when the same syntax is used to declare double prime marker in mathjax version 2.7.0 it looks alright.

```
<msup>
   <mrow>
      <mo>&#x2220;</mo>
      <mi>H</mi>
   </mrow>
   <mi>&#x2033;</mi>
</msup>
```
**Version: 2.7.7**
<img width="50" alt="Screen Shot 2020-08-13 at 6 11 08 PM" src="https://user-images.githubusercontent.com/22182896/90195978-66ec1b00-dd90-11ea-8a9c-d9822fb41c15.png">

**Version: 2.7.0**
<img width="59" alt="Screen Shot 2020-08-13 at 6 04 45 PM" src="https://user-images.githubusercontent.com/22182896/90195822-196fae00-dd90-11ea-8bea-4917c3b6fc49.png">

**Observation**
In v2.7.7 if the double prime marker is enclosed in **`<mo>`**  instead of **`<mi>`** then it looks normal in size. 
```
<msup>
   <mrow>
      <mo>&#x2220;</mo>
      <mi>H</mi>
   </mrow>
   <mo>&#x2033;</mo>
</msup>
```
**Version: 2.7.7** - Double prime marker declared as **`<mo>`**
<img width="55" alt="Screen Shot 2020-08-13 at 6 17 46 PM" src="https://user-images.githubusercontent.com/22182896/90196413-4ec8cb80-dd91-11ea-8961-d2e59bea07a0.png">

Is there any reason behind the difference in appearance based on the syntax?
Is it required to declare prime markers as operators **`<mo>`** and not as identifiers  **`<mi>`** in v2.7.7?

**Comment by dpvc** [comment]
> Is there any reason behind the difference in appearance based on the syntax?

Yes.  The primes are an instance of a [pseudo script](https://www.w3.org/TR/MathML3/chapter7.html#chars.pseudo-scripts), which require somewhat special treatment during layout.  In normal fonts, U+2033 is reduced in size and slightly raised, so that when you have the two adjacent characters `H` and U+2033 it will look correct (`H″`).  But in MathML, the placement of scripts are handled through `<msup>` and similar constructions, and for these, the characters in the script are reduced in size and raised by the layout engine instead.  So the character used for U+2033 must not *itself* be reduced and raised, since that would cause a double reduction and raising (as in your first 2.7.7 example).

For this reason, MathJax has larger, un-raised version of U+2033 and similar prime characters so that they they are used in superscripts, they will be the correct size and placement.  That means MathJax must determine when to use the standard (reduced and raised) versions, or the variant (larger and un-raised) versions.  The alternative forms are triggered by being inside a `<mo>` that is the sole element in a superscript.  Both being a `<mo>` and being in a superscript are required conditions for the substitution of the larger size.

The reason this is not done in other situations is that some people use `<mi>H</mi><mo>&#x2033;</mo>` outside of an `<msup>`, so the larger form should *not* be used in this case.  Also, some people use `<mi>H&#x2033;</mi>` to make a single identifier that is `H″`, so it is inappropriate to do the substitution within `<mi>` elements.  (These two constructions are discouraged by the MathML specification, but they do appear in the wild).  Only the operator form causes the larger variant to be used.

This substitution feature was added in the CommonHTML output somewhere after version 2.7.0 (I don't recall which version it was), so that accounts for the difference you are seeing between 2.7.7 and 2.7.0 (in the older versions, U+2033 was always the larger form).  The SVG and HTML-CSS output still use the older format, with only the larger characters.

> Is it required to declare prime markers as operators `<mo>` and not as identifiers `<mi>` in v2.7.7?

This is the recommended encoding.  The primes are operators, not identifiers (they operate on the base), so they should be `<mo>` not `<mi>`.
