### ISSUE TITLE
Chinese should be convert to <mi> not <mo>

### ISSUE THREAD

**Issue by qq240814476** [mathjax/MathJax#2501]
mo tag only use for oprators, chinese should use mi tag

```js
const result = Mathjax.tex2mmlSync('中文');
console.log(result) 
// <math xmlns="http://www.w3.org/1998/Math/MathML"><mo>&#x4E2D;&#x6587;</mo></math>
// it should be 
// <math xmlns="http://www.w3.org/1998/Math/MathML"><mi>&#x4E2D;&#x6587;</mi></math>
```

**Comment by qq240814476** [comment]
thank u very much! Btw, what should I do to put chinese or other characters into  <mtext> tag ?

**Comment by dpvc** [comment]
I'm not sure I understand the question.  First, are you using LaTeX or MathML for your input format.  Your original question uses TeX, so I assume that is what you are using.  But in that case, you simply enter the characters as you did in the example you gave.  Use unicode characters for the ones that you want.  I would recommend using `\text{中文}` if you are entering words rather than variables in your formulas.  You can also use `\unicode{xE42D}` to enter a character by its unicode code point.  You can also use and HTML entity like `&#xE42D;` if you are authoring in HTML (if you are using Markdown or something similar, this may not come through properly).

**Comment by dpvc** [comment]
Also note that version 3.2 is more nuanced about the MathML tag that it uses for different ranges of unicode characters.  So Chinese characters are now in `<mi>` automatically.
