### ISSUE TITLE
Problems with using local MathJax in ie11

### ISSUE THREAD

**Issue by TreshUp** [mathjax/MathJax#2506]
### Issue Summary

Hi, thank you for your awesome work. I'm using local Mathjax mml-chtml.js from master branch. My local website displays great in Chrome, Firefox and Edge. but i have an error in ie11 ver. 11.133917763.0 - "Symbol is undefined in mml-chtml.js". Can you suggest anything? Thank you.

### Technical details:

* MathJax Version: 3.05
* Client OS: Windows 10
* Browser: ie11 ver. 11.133917763.0

### Supporting information:
![image](https://user-images.githubusercontent.com/23707542/90871527-a6c88900-e3b4-11ea-946d-935520afb102.png)

<script async="" id="MathJax-script" src="../assets/MathJax/mml-chtml.js" type="text/javascript"></script> - sript tag

This is the line with error:
Object.defineProperty(e,"__esModule",{value:!0});var n=(i.prototype[Symbol.iterator]=function(){var t=0,e=this.items;return{next:function(){return{value:e[t++],done:t>e.length}}}},i.prototype.add=function(t,e){void 0===e&&

Example: https://pastebin.com/8H8rzqub

**Comment by TreshUp** [comment]
> Have you included the polyfill recommended in the [documentation](https://docs.mathjax.org/en/latest/web/start.html#browser-compatibility)? That is needed for IE. This is the kind of error message you will get without it.

Thank you so much, i forgot to look into documentation and didn't find anything in issues. Thanks!

**Comment by nisha2107** [comment]
@TreshUp after reading your above comment i found that you are able to successfully work with local math-jax in your project. 
I am also trying to add mathjax version 3 locally in my project so that there is no more conversion time of equations. 

Steps I took :
Added mathjax version 3.0.0 in a local folder and then reference the "tex-chtml.js" in index.html. 

But my conversion are not happening in browser. 

Could you please help me with steps you took for successful local integration. 

Thanks in advance!

**Comment by TreshUp** [comment]
@nisha2107 Sorry for long reply, i didn't see your message. The question is relevant?
