### ISSUE TITLE
Numbers not being placed inside square root symbol in chrome

### ISSUE THREAD

**Issue by dominicwojciechowski86** [mathjax/MathJax#2509]
### Issue Summary

works fine in IE,

### Technical details:

* MathJax Version: 3.0.1
* Client OS: windows 10 home 1903
* Browser: Chrome Version 85.0.4183.83 

### Supporting information:

<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3.0.1/es5/tex-mml-chtml.js"></script>
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mrow>
    <msqrt>
      <mn id="var1">16</mn>
    </msqrt>
  </mrow>
</math>

this produces:
![image](https://user-images.githubusercontent.com/27436678/91219555-b9272780-e712-11ea-986b-526eec8f7b5e.png)

**Comment by dpvc** [comment]
You have not provided sufficient information to address your issue.  You have left the bug report template without adding any of the details specific to your situation.

**Comment by dominicwojciechowski86** [comment]
Sorry, the code is:
`<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mrow>
    <msqrt>
      <mn id="var1">16</mn>
    </msqrt>
  </mrow>
</math>`

**Comment by dpvc** [comment]
Well, the equation helps, but you have not indicated anything about your configuration.  Are you using version 2 or version 3?  What output renderer?  What OS are you running on.

your equation works fine for me in Chrome (84.0.4147.135) on Mac OS X (10.14.5):

<img width="80" alt="sqrt-16" src="https://user-images.githubusercontent.com/432782/91220426-24a8cf00-e6ea-11ea-9f36-7f7451635f60.png">

There may be CSS or other features of your page that are interfering with MathJax.  Perhaps you can link to a page that exhibits the problem you are seeing?

**Comment by dominicwojciechowski86** [comment]
MathJax Version: 3.0.1
Client OS: windows 10 home 1903
Browser: Chrome Version 85.0.4183.83

I have found that the problem only occurs when I change the number using 
document.getElementById("var1").innerHTML = y;

If I just put a a number in the the tags it works fine but if try to change the number using JS then the problem occurs.

**Comment by dominicwojciechowski86** [comment]
Here is the full code for the page:
<!DOCTYPE html>
<html lang="en">
<head>

    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3.0.1/es5/tex-mml-chtml.js"></script>


<script>

    function makerange(a,b) {
            var integer= Math.floor(Math.random() * a) + b;
            return integer;
    }
       window.onload= function() {
           var x = makerange(11,3);
           var y= x*x;

           document.getElementById("var1").innerHTML = y;
            document.getElementById("var2").innerHTML = x;
       }
    </script>

    <meta charset="UTF-8">
    <title>Title</title>


</head>
<body>
<div id="question">
    <math xmlns="http://www.w3.org/1998/Math/MathML">
  <msqrt>
    <mn id="var1">125</mn>
  </msqrt>
</math>

</div>

<div id="answer">
    <p id="var2"></p>

</div>

</body>
</html>

**Comment by dpvc** [comment]
Ah, you see, you left out the most important information in your earlier posts!  The fact that you are modifying the expression is the key issue, because the original MathML has been replaced by either HTML or SVG output by MathJax (depending on the configuration you are using, which in your case would be HTML).  By replacing the innerHTML of the element with id `var1`, you are actually replacing some of the MathJax output, which is more complicated than just some text (which is what you are replacing it with).

MathJax does not provide an API for altering sub-formulas of a typeset expression, so you will not be able to do what you are trying to do (at least not the way you are doing it).  Instead, you must replace the entire expression (the whole `<math>` element), and have MathJax re-typeset it.

In your example, it may be sufficient to simply put off typesetting until after your expression has been altered (it is not clear if you are going to be chasing the question multiple times.)  In this case, you can simply tell MathJax not to typeset the page initially, and then when you have modified the page, ask MathJax to typeset it.  Here is an example that implements that:

``` html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Delay typesetting until the math is ready</title>
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script>
MathJax = {
  startup: {
    typeset: false
  }
};
</script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3.1.0/es5/mml-chtml.js"></script>
<script>
function makerange(a,b) {
  var integer = Math.floor(Math.random() * a) + b;
  return integer;
}
window.onload = function () {
  var x = makerange(11,3);
  var y= x*x;
  document.getElementById("var1").innerHTML = y;
  document.getElementById("var2").innerHTML = x;
  MathJax.startup.promise.then(function () {
    MathJax.typesetPromise().catch(function (err) {console.log(err)});
  });
};
</script>

</head>
<body>

<div id="question">
  <math xmlns="http://www.w3.org/1998/Math/MathML">
    <msqrt>
      <mn id="var1">125</mn>
    </msqrt>
  </math>
</div>

<div id="answer">
  <p id="var2"></p>
</div>

</body>
</html>
```

If you will be making multiple changes to the question, then you need a different approach.  One possibility would be to have a "template" `<math>` element to which you make changes, then clone it and insert it into the page, and finally re-typeset it.  Here is an example that implements that:

``` html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>Use MathML template</title>
<script>
Question = {};
MathJax = {
  startup: {
    pageReady() {
      const div = document.createElement('div');
      div.innerHTML = '<math xmlns="http://www.w3.org/1998/Math/MathML"><msqrt><mn id="var1">125</mn></msqrt></math>';
      Question.template = div.firstChild;
      Question.var = Question.template.querySelector('#var1');
      Question.div = document.getElementById('question');
      Question.ans = document.getElementById('answer');
      document.getElementById('newQuestion').disabled = false;
    }
  }
}
</script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3.1.0/es5/tex-chtml-full.js"></script>
</head>
<body>

<script>
function makerange(a,b) {
  var integer = Math.floor(Math.random() * a) + b;
  return integer;
}
function showQuestion() {
  var x = makerange(11,3);
  var y= x*x;
  Question.var.innerHTML = y;
  Question.ans.innerHTML = x;
  Question.div.innerHTML = "";
  Question.div.appendChild(Question.template.cloneNode(true));
  MathJax.typesetClear();
  MathJax.typesetPromise().catch((err) => console.log(err));
}
</script>

</head>
<body>

<input id="newQuestion" type="button" value="New Question" onclick="showQuestion()" disabled />
<br><br>

<div id="question">
</div>

<div id="answer">
  <p id="var2"></p>
</div>

</body>
</html>
```

Perhaps one of these will do what you need.

**Comment by dominicwojciechowski86** [comment]
Thanks you for your help.
