### ISSUE TITLE
Insert html in MathJax and extra space below and above the text during fraction

### ISSUE THREAD

**Issue by DibasDauliya** [mathjax/MathJax#2510]
I have a html "`<span class="round">a</span>`" which makes the round circle over the text. I want to insert it inside the mathjax as of the below picture. Can you please help me, how can I do that?

![image](https://user-images.githubusercontent.com/51583004/91258080-38584200-e78b-11ea-8964-228476e28948.png)

This is the code of this picture:
```
<li class="ans">Solution, <br>
                $\begin{aligned}
                \text{Given, }
                \text{f(x)} & = \text{3x - 4} \\
                \text{g(x)} & = \text{a (let)} \\
                f^{-1}g(x) & = \frac{\text{3x + 2}}{\text{3}} \\
                \end{aligned}$
                <div class="min-space"></div>
                $\begin{aligned}
                \text{To find, }
                \text{g(x)} & = \text{?} \\
                f^{-1}\left(\frac{1}{2}\right) & = \text{?} \\
                \end{aligned}$
                <div class="space"></div>
                For, f<sup>-1</sup>(x), <br>
                $\begin{aligned}
                \text{f(x)} = \text{y} &= \text{3x - 4} \\
                \text{or, } \frac{\text{y + 4}}{3} &= \text{x} \\
                \text{Interchanging the } & \text{value of x and y, we get,} \\
                \text{or, } \frac{\text{x + 4}}{3} &= \text{y} \\
                \therefore f^{-1}(x) &= \frac{\text{x + 4}}{3} \\
                \end{aligned}$ ---- <span class="round">a</span>
                <!-- error -->
                <div class="space"></div>
                $\begin{aligned}
                \text{Again, }
                f^{-1}g(x) &= \frac{\text{3x + 2}}{\text{3}} \\
                \text{or, } f^{-1}(a) &= \frac{\text{3x + 2}}{\text{3}} \\
                \text{or, a + 4} &= \text{3x + 2} \\
                \therefore \text{a} = \text{g(x)} &= \text{3x - 2} \\
                \therefore f^{-1}\left(\frac{1}{2}\right) = \frac{\text{1 + 8}}{\text{6}} &= \frac{\text{3}}{\text{2}}
                \end{aligned}$
            </li>
```

<hr>

and, about extra space, I mean that, if we wrap the texts in the fraction with `\text{} ` to makes extra spacing. I've try to clarify more in figure below 👇 

![image](https://user-images.githubusercontent.com/51583004/91259084-80786400-e78d-11ea-9230-04d5a2016f4b.png)

I want to wrap text in fraction with '\text{}' because I want to make it's styling inherent. 
How can I remove that extra space ? 😢

**Comment by DibasDauliya** [comment]
@dpvc why I'm ignored? 😭

**Comment by dpvc** [comment]
> why I'm ignored?

I have only so much time for answering questions, and there are too many questions to keep up with, at times.  I have to prioritize those that I do answer.  I tend to answer those that move the project forward before those that done.  That means that actual bugs are addressed first, and then questions whose answers either illuminate an important feature or whose answer provides useful examples for others as well as the original poster.

Those why try to speed up my response through "pestering" tend to have the opposite effect, and tend to slow down my response to them (I tend to reset the clock on each such message).  

Over the last several weeks, most of my time was taken up with trying to get versions 2.7.9 and 3.1.0 released, and following that I spent a full week doing nothing but upgrading several servers in my department.  Now I am trying to get course materials ready for classes that start next week, and have to retool much of it for remote education due to the pandemic.  All of this has limited my time for answering MathJax questions.

I answered your original post in order to illustrate `mtextFontInherit`, and to correct your LaTeX.  You have rejected my recommendations for proper LaTeX usage and continue to use `\text{}` inappropriately.  Explaining to you why what you are doing is bad practice takes time and energy that I don't really have.  

Traditionally mathematics is typeset in italics specifically to make it *not* be the same as the surrounding text, so that when you write things like "let *a* be a real number" it is easy to distinguish the "a" as a variable rather than the word "a".  So using `\text{}" around everything is a bad idea.  Not only does it make it harder to read, it also causes the spacing to be wrong (spacing in mathematics is different than spacing in textual material), plus it is not semantically correct, and that will cause problems for those using assistive technology like screen readers, as the mathematics will not be pronounced correctly.  Similarly, your use of `o` rather than `\circ` is incorrect, and not only looks wrong, but will produce bad results for screen readers.

Because you now have `mtextFontInherit` set, the contents of `\text{}` will be shown in the surrounding font.  MathJax doesn't know the bounding-box information for the characters in that font, and so has to make assumptions about the sizes of the characters.  This leads to bad spacing if you use this in place of normal mathematics (it is OK to use for actual text, but not for mathematical notation).  That is what is leading to the extra vertical space in your fractions; MathJax doesn't know how big the characters are, and so uses a default size that is large enough to match the largest characters, and that is too large for many of them, but it is the best it can do.  That is why it is OK for textual material but not mathematics, where the size is more important.

As for the circled A, MathJax does not allow HTML within the mathematics that it processes.  There are other alternatives, however.  You could use `\unicode{x24B6}` (or perhaps `{\Large\unicode{x24B6}}` as one option.  Or just `(A)` should be easy enough.  Another possibility is `\class{round}{A}`, though MathJax will not take account of the larger size that your CSS will cause the A to have when you do this.

Finally, there is a [StackOverflow](https://stackoverflow.com/questions/58883048/mathjax-or-similar-render-arbitrary-html-element-inside-expression/58956935#58956935) response that gives you a way to include HTML in the math (the second code example in the post), that you could use if you really need to use HTML inside the math.

**Comment by DibasDauliya** [comment]
Thank you. I'll reformat all my equations. :)

> Now I am trying to get course materials ready for classes that start next week, and have to retool much of it for remote education due to the pandemic.
Can I join this class?

**Comment by dpvc** [comment]
> Can I join this class?

I'm afraid that it is for Union College students only.

**Comment by DibasDauliya** [comment]
😞😖 please?

**Comment by dpvc** [comment]
If you want to apply for admission to Union College, and are accepted and matriculate, then you would be able to take the course.  Union students pay substantial tuition for the courses they take, and it would be inappropriate for me to make them available to others outside of Union, even if that was what I wanted to do.

**Comment by DibasDauliya** [comment]
there is no international payment gateway in our country yet. but I really want to know more and best practice of MathJax 😥

**Comment by dpvc** [comment]
The courses I am teaching are not about MathJax.  They are regular undergraduate courses in Calculus and proof techniques for Math majors.

**Comment by DibasDauliya** [comment]
Oh wow. Just one yes no question 😅. Is root2 and -root2 same? I think it
is same because root2 = plusminus root2 and minus root2 makes it same.
Is it? Please?

**Comment by dpvc** [comment]
> Is root2 and -root2 same?

No, as I show below.

>  I think it is same because root2 = plusminus root2

This is not correct (at least not the way you mean it).  Note that sqrt(*x*) is a *function*, and so can have only one value (not two).  The definition of sqrt(*a*) is the *positive* value whose square is *a*.  That means that sqrt(4) is 2, not -2.  A square root is never negative.  This is the graph of *y* = sqrt(*x*):

<img src="https://user-images.githubusercontent.com/432782/92379953-518bb780-f0d6-11ea-9ea9-34c7764c70df.jpg" alt="graph of y=sqrt(x)" width="70%">

Note that it is always above the *x*-axis (so always positive).  It has no negative values.

The reason that you think as you do is that there *are* two solutions to an expression like *x*<sup>2</sup> = 4; either *x* = 2 or *x* = -2 satisfies the equation.  The problem is that most people don't get there through legitimate means.  The usual thought is that you take square root on both sides:

<p>
<i>x</i><sup>2</sup> = 4, so<br>
sqrt(<i>x</i><sup>2</sup>) = sqrt(4)
</p>

So far, this is OK, but then most people then say sqrt(*x*<sup>2</sup>) = *x* and sqrt(4) = ± sqrt(4), as you did, to get the solution; but both of these are false.  Note that sqrt(*x*<sup>2</sup>) it **not** equal to *x* in general.  For example, you know that sqrt(4) = 2 (never -2) since it is the *positive* value whose square is 4.  But when *x* = -2, then *x*<sup>2</sup> = (-2)<sup>2</sup> = 4, so sqrt(*x*<sup>2</sup>) = sqrt(4) = 2 ≠ -2 = *x*, so sqrt(*x*<sup>2</sup>) ≠ *x* when *x* = -2.  That is, sqrt(*x*<sup>2</sup>) ≠ *x* in general.

What *is* true is that sqrt(*x*<sup>2</sup>) = |*x*|.  So the correct next step in the series above is

<p>
<i>x</i><sup>2</sup> = 4, so<br>
sqrt(<i>x</i><sup>2</sup>) = sqrt(4), so<br>
|<i>x</i>| = 2
</p>

(Note that both sides are positive).  But there are two values of *x* where |*x*| = 2, namely *x* = 2 or *x* = -2.  That is how you get two values for *x*, not through the square root on the right, which is always positive, but through the absolute value that you get on the left.

The complete argument is then

<p>
<i>x</i><sup>2</sup> = 4, so<br>
sqrt(<i>x</i><sup>2</sup>) = sqrt(4), so<br>
|<i>x</i>| = 2, so<br>
<i>x</i> = 2 or <i>x</i> = -2.
</p>

Personally, I don't approve of the "±" notation because it leads to bad interpretations like the one you have made (which is very common).  It doesn't mean both values, as many people think; it is shorthand for an "or" statement (one or the other), and treating its as a "single" value in the expression clouds its meaning.  I prefer "*x* = 2 or *x* = -2", not "*x* = ±2", which students tend not to fully understand and tend to handle improperly when they use it.

Note that when you say sqrt(2) = ±sqrt(2) as you did in your message, you have fallen for this trap.  You said that this means sqrt(2) = -sqrt(2), which is not what it says (you have taken "±" to mean an "and" statement when it is an "or").  When we say "*x* = ±2" that means "either *x* = 2 **or** *x* = -2", not "*x* = 2 **and** *x* = -2".  There is no *x* that makes both equalities true (as that would require 2 = -2, since a single *x* would be equal to both), so the "and" statement can never be true.

So "sqrt(2) = ±sqrt(2)" is true in the sense that it means "sqrt(2) = sqrt(2) or sqrt(2) = -sqrt(2)" and since the first of these is true, the statement as a whole is true (the fact that the second is false doesn't matter, since "A or B" is true if one or the other is true; it doesn't require both).  But that is not what you meant when you said "root2 = plusmins root2" above.  You have taken this to mean "sqrt(2) = sqrt(2) and sqrt(2) = -sqrt(2)", which is **not** true because the second is false ("A and B" is true only when both A and B are true).  Note that *x* = -*x* is only true when *x* = 0, but sqrt(2) is not equal to 0, so sqrt(2) ≠ -sqrt(2).

The "±" leads to sloppiness both of notation and of thought, which (unfortunately) is all too common.  Careful handling of the notation and the wording (e.g., the difference between "and" and "or") is critical to the proper handling of the underlying ideas, and that is crucial to getting (and understanding) the correct solutions.

**Comment by DibasDauliya** [comment]
In this solution I should write &therefore; x = 11 or x = -11 instead of &PlusMinus;11, right?
![image](https://user-images.githubusercontent.com/51583004/92386598-cc36f000-f133-11ea-97cd-b160be60b2ca.png)

and, in this question of geometric series:
**Find the number of terms of the given series: 2 - 2&Sqrt;2 + 4 - 4&Sqrt;2 + ... + 16.**

common ratio will be -sqrt(2) and if I use this value {-sqrt(2)} to find the number of terms, I cannot get the answer. Is this question wrong? Before, I solved using "-sqrt(2) = sqrt(2)" which is wrong method. Can you please suggest me to solve this?


Thank you so very much. Union college's students are very lucky to have a teacher like you ❤

**Comment by dpvc** [comment]
> In this solution I should write ∴ x = 11 or x = -11 instead of ±11, right?

That is my preference, but you are not required to follow my preference.  You are not in my course.  You instruct may have his or her own preferences in this regard.

> Is this question wrong?

No.

> Can you please suggest me to solve this?

I could, but we have moved far from MathJax at this point, and that puts this discussion outside of the scope of this issue tracker.  I answered your question about square roots because I was already preparing that material for the course I am teaching, but this forum is not a general question-and-answer forum.  You might try  the [Math StackExchange](https://math.stackexchange.com) or [MathOverflow](https://mathoverflow.net), which are set up as math question-and-answer sites.

**Comment by DibasDauliya** [comment]
Can you show me the step where base is equal to compare the power. It seems putting random number is <i>n</i> and getting the answer. So, I want that step where base is equal. I've asked question [here](https://math.stackexchange.com/questions/3819695/find-the-number-of-terms-of-the-given-series-2-2%e2%88%9a2-4-4%e2%88%9a2-16)
