### ISSUE TITLE
How to configure global when making a customized build?

### ISSUE THREAD

**Issue by perqin** [mathjax/MathJax#2518]
I am porting MathJax to a special js runtime where neither 'global' in node nor 'window' in browser are available. So,
1. How can I configure the 'global' object for a customized build?
2. Is it possible to configure and run MathJax without relying on any global objects? I just need to convert latex string into svg.

Thanks for any helpful ideas in advance.

**Comment by dpvc** [comment]
The MathJax components architecture is dependent on a global variable to mediate the communication between the various components, so you will abandon the components and use direct access to the MathJax modules.  You can see how this is done in the [direct](https://github.com/mathjax/MathJax-demos-node/tree/master/direct) folder of the [MathJax node demos](https://github.com/mathjax/MathJax-demos-node) repository.  The [tex2svg](https://github.com/mathjax/MathJax-demos-node/blob/master/direct/tex2svg) example would be a good starting point.  You can remove the `yards` stuff (that gets command-line arguments) and export a function that does the `tex2svg` conversion via the `html.convert()` function.  If you are running this in a browser, you can substitute the `browserAdaptor` for the `liteAdaptor` so that you use browser DOM elements rather than the LiteDOM elements (so you don't need to load that library).

I think that should be pretty straight forward, but you can ask questions if you need help.,

**Comment by perqin** [comment]
Thanks for your help! (Sorry that I'm so late to reply)
I follow the node demos and now it works. I'm closing this issue.
I also removed the `components` directory because I'm using MathJax "directly". For now it works fine.
