### ISSUE TITLE
AMSCD sometimes sensitive to space at \begin {CD}

### ISSUE THREAD

**Issue by bdtc** [mathjax/MathJax#2531]
### Issue Summary

Sometimes, but not always, amscd seems to be sensitive to a space between `\begin` and `{CD}`.

### Technical details:

MathJax v3 latest.  Firefox.

### Supporting information:

```
<!DOCTYPE html>
<html lang="en-US">
<head>
<meta charset="UTF-8" />

<script
         id="MathJax-script"
         src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"
></script>

</head>

<body>
\(\DeclareMathOperator {\End }{End}\)

\(\DeclareMathOperator {\cov }{cov}\)

\(\DeclareMathOperator {\non }{non}\)

\(\DeclareMathOperator {\cf }{cf}\)

\(\DeclareMathOperator {\add }{add}\)

The following does not work with a space between \begin and {CD},
saying Misplaced @:
\begin{equation}
\begin {CD} S^{{\mathcal {W}}_\Lambda }\otimes T @&gt;j&gt;&gt; T\\ @VVV @VV{\End P}V\\ (S\otimes T)/I @= (Z\otimes T)/J \end {CD}
\end{equation}


The following works with or without a space between \begin and {CD}:
\begin{equation}
\begin {CD} \cov (\mathcal {L}) @&gt;&gt;&gt; \non (\mathcal {K}) @&gt;&gt;&gt; \cf (\mathcal {K}) @&gt;&gt;&gt; \cf (\mathcal {L})\\ @VVV @AAA @AAA @VVV\\ \add (\mathcal {L}) @&gt;&gt;&gt;
\add (\mathcal {K}) @&gt;&gt;&gt; \cov (\mathcal {K}) @&gt;&gt;&gt; \non (\mathcal {L}) \end {CD}
\end{equation}

</body>

</html>
```

**Comment by dpvc** [comment]
This turns out to be the same issue as #2511, and there is already a fix for it in 3.1.1, which we hope to release by this weekend.  The first time an auto-loaded extension (in this case, `amscd`) is used, if there is a space after the `\begin`, MathJax gets confused (it doesn't take the space into account when it tries to reprocess the command).

The solutions for now are to either not use the space, load the `amscd` extension explicitly rather than autoloading it, or use `tex-chtml-full.js` instead of `tex-html.js`.
