### ISSUE TITLE
using multiple \eqref's inside an equation

### ISSUE THREAD

**Issue by parhizkari** [mathjax/MathJax#2540]
### Issue Summary

When multiple \eqref{}'s are used inside an equation, the number of the equations shown are all correct, but sometimes some of them link to wrong equations.
I'm in Firefox, in Lubuntu.

### Steps to Reproduce:

A minimal example to show the behavior:
```
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<script>window.MathJax = {tex:{tags:"ams"}};</script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg-full.js"></script>
</head>
<body>
Hello ...
\begin{align}
\cdots\label{eq1}\\
\cdots\label{eq2}\\
\cdots\label{eq3}
\end{align}
now test referring to the equations inside another equation
\begin{equation}
\eqref{eq1},\,\eqref{eq2},\,\eqref{eq3}:\qquad \ldots
\end{equation}
</body>
</html>
```
You can also try it with only first two equations, then both links will link to the second, the eq2.

### Technical details:

* MathJax Version: 3.1.2
* Client OS: Lubuntu
* Browser: Firefox 80 64bit

### Supporting information:

 * no error in the console

**Comment by dpvc** [comment]
OK, I can reproduce the issue using your example file.  I will have to look into it.  So clue what is happening at this point.

**Comment by dpvc** [comment]
I spoke too soon, I do know what it is.  It is actually issue #2530.  The SVG output uses a transparent `<rect>` object as a hotbox for the `<a>` element so that you don't have top be over the ink of the glyph but anywhere it its bounding box.  But because the hitboxes are misplaced, the one for the reference to equation 3 lies on top of the one for equation 1, and so clicking on it links to an unexpected equation.

There is already a proposed fix, but I haven't posted a configuration that will do a patch on the fly.  I will see about posting when as soon as I can.

**Comment by parhizkari** [comment]
Thanks a lot

**Comment by dpvc** [comment]
@parhizkari, here is a configuration that patches the link issue:

``` javascript
MathJax = {
  startup: {
    ready() {
      const {SVGWrapper} = MathJax._.output.svg.Wrapper;
      const place = SVGWrapper.prototype.place;
      SVGWrapper.prototype.place = function (x, y, node) {
        place.call(this, x, y, node);
        if ((x || y) && !node && this.node.attributes.get('href')) {
          const translate = 'translate(' + this.fixed(x) + ', ' + this.fixed(y) + ')';
          const rect = this.adaptor.previous(this.element);
          this.adaptor.setAttribute(rect, 'transform', translate);
        }
      };
      MathJax.startup.defaultReady();
    }
  }
}
```

**Comment by parhizkari** [comment]
It worked great, fantastic, thank you :+1:
