### ISSUE TITLE
MathJax.svgStylesheet() returns null

### ISSUE THREAD

**Issue by jano-m** [mathjax/MathJax#2542]
### Issue Summary

As of version 3.1.0, Mathjax.svgStylesheet() returns null instead of a copy of stylesheets.

### Technical details:

* MathJax Version: 3.1.0-3.1.2

**Comment by dpvc** [comment]
Thanks for the report.  This is due to commit [dc0c2f7](https://github.com/mathjax/MathJax-src/commit/dc0c2f7441179a8c4721c49e06b1665c9c14484f) that was to prevent the SVG stylesheet from being updated unnecessarily.  But it also disabled the `MathJax.svgStylesheet()` function after it is called once or the initial typesetting occurs.

If you disable the initial typesetting (by setting `MathJax.startup.typeset` to false in your configuration, that should let you call `Mathjax.svgStylesheet()`.  Alternatively, you could set `MathJax.startup.document.outputJax.svgStyles = null` before calling it.  Or you could just use `MathJax.startup.document.outputJax.svgStyles` itself, which will point to the actual stylesheet in use.
