### ISSUE TITLE
Next line tag having 2 line spaces.

### ISSUE THREAD

**Issue by AnkitaS-addweb** [mathjax/MathJax#2544]
Hello Team, 

I have a website, https://georgiatestprep.com/ which have multiple Questions with Mathematical equations, and I am unable to set up the new line and new paragraph Tag, if you can help me to figure this out, it will be great.

When I use `\\` tag it is taking 2 lines space, attaching a screenshot for reference. 

![2020-09-21_17-01](https://user-images.githubusercontent.com/47100553/93761952-5602b500-fc2c-11ea-9d2c-018cf1c6f303.png)

Please help me to figure this out.

**Comment by dpvc** [comment]
It is not clear what you are asking for.  MathJax is for handling the mathematics on the page; other formatting tasks, like new paragraphs, should be handled by HTML, not MathJax.  So I'm not sure what you are attempting.

Your screen shot indicates that you have a display-mode math element containing the TeX code

    \:\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:

which just produces some space (rather inefficiently, since `\hskip 5em` would be easier), so that means you are making a displayed equation with no visible content.  Since displayed equations are offset from the surrounding text by 1em on the top and bottom, you are getting 2em of space around your empty equation, which is roughly two blank lines.  That is the correct output for what you have in the page.  (Also, I don't see the `\\` that you indicate you used, and instead see a bunch of `\:` macros.)

So again, I'm confused about what you want to accomplish.
