### ISSUE TITLE
'\left \right' is not rendered in ghost blog 

### ISSUE THREAD

**Issue by ML2jinmyoung** [mathjax/MathJax#2552]
Hello! I added Mathjax to ghost blog.
Most of them are well rendered, but 'left \right' (or \mathcal) is not rendered as follow.
<img width="767" alt="스크린샷 2020-09-28 오후 6 19 13" src="https://user-images.githubusercontent.com/52397255/95423753-95dfd100-097c-11eb-8e14-2f7ce9d54350.png">

I've changed Mathjax version and configurations, but still not solved.  

Here is my MathJax config. 

```
<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_HTML"></script> 
<script type="text/javascript"
   		src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_CHTML">
</script>
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    jax: ["input/TeX","output/HTML-CSS"], 
    TeX: {
     
      extensions: ["tex2jax.js", "TeX/AMSmath.js", "TeX/AMSsymbols.js"],
      equationNumbers: {
      autoNumber: "AMS"
      },
      tags: "AMS"
    },
    tex2jax: {
      inlineMath: [ ['$','$'], ["\\(","\\)"]  ],
      displayMath: [ ['$$','$$'],["\\(","\\)"]  ],
      processEscapes: true
    },
    loader: {load: ['[tex]/ams']},
  	tex: {packages: {'[+]': ['ams']}}
  });
</script>
```

I couldn't figure out what is the problem.

**Comment by dpvc** [comment]
There are a number of errors in your configuration, but the reason your expression isn't being rendered is because the TeX is not valid.  Since braces are used for grouping, in order to get a brace included in the output, you need to use `\{` and `\}` not just `{` and `}`.  So it should be `\left\{ ... \right\}` not `\left{ ... \right}`.

As for the configuration, you seem to be loading two copies of MathJax, which inefficient and unnecessary (the second one will do nothing other than take time).  Your configuration script should go *before* the script that loads MathJax (so that it is available to MathJax when it loads); see the [documentation](http://docs.mathjax.org/en/v2.7-latest/configuration.html#using-in-line-configuration-options) for details.  Because you are loading the TeX-AMS_HTML configuration file, you don't need to specify the `jax` array or the TeX `extensions` array, as these are already handled by the TeX-AMS_HTML combined configuration file.  Finally, you are using version 2.7.5 (note that the latest version of v2 is 2.7.9), but have included version 3 configuration options (`loader`), which will have no effect on version 2.

**Comment by ML2jinmyoung** [comment]
Thank you for your quick answer.
I included \ when I wrote from the md file, but I found that` \left \ `changed to` \left `when it was rendered. I don't know the exact cause, but when I switched to `\left \\`, the problem was solved.
I fixed the configuration as you pointed out. Thank you.
