### ISSUE TITLE
tex-svg.js:1 Uncaught Error: MathJax retry when using "\cancel" package

### ISSUE THREAD

**Issue by SocialAnxty** [mathjax/MathJax#2557]
### Issue Summary

When trying to use the \cancel package I am getting the error 

tex-svg.js:1 Uncaught Error: MathJax retry
    at Object.Q.retryAfter (tex-svg.js:1)
    at Object.L [as RequireLoad] (tex-svg.js:1)
    at u (tex-svg.js:1)
    at Q.parse (tex-svg.js:1)
    at t.parse (tex-svg.js:1)
    at t.parse (tex-svg.js:1)
    at t.controlSequence (tex-svg.js:1)
    at Q.t.parse (tex-svg.js:1)
    at t.parse (tex-svg.js:1)
    at t.parse (tex-svg.js:1)

when using MathJax.typeset(); for live rendering, but it only happens when "\cancel X" for example is first typed. As soon as the error pops up, if I simply delete or add anything to the text field, the error does not happen and the mathjax renders correctly.

### Technical details:

* MathJax Version: 3 = Using the cdn https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js
* Client OS: Windows OS
* Browser: Chrome Version 86.0.4240.75 (Official Build) (64-bit)

Does anyone have any idea how I could fix this?

**Comment by andi1984** [comment]
@SocialAnxty What is the "cancel" package you're speaking about? I also get this error, but to me it seems some sort of timing issue. If I reduce network speed with the devtools the error isn't happening anymore, but when I speed up to my normal connection speed the error is happening again.

So yes, I can confirm that I get some same error message since last ~1-2 months, but not before. But in my case I'm not sure if also this cancel package is used. I'll try to find out.

**Comment by SocialAnxty** [comment]
@andi1984 when I use \cancel{a} or anything with \cancel it happens is what I mean. 

I got around it by just calling MathJax.typeset(); with a slight delay after the error. "Retrying" as it says basically lol. On the second MathJax.typeset(); it renders as it should.

**Comment by dpvc** [comment]
The `tex-svg.js` component does not include all the extensions to MathJax, but they are set up to autoload when first used.  The `\cancel` macro is one such macro (from the `cancel` extension).  The loading of extensions is asynchronous, and so if you want to process math that includes such extensions, you need to use the promise-based typesetting commands.  So you should use `MathJax.typesetPromise()` rather than `MathJax.typeset()` if you are going to want to allow autoloaded extensions.

Your alternatives are to use `tex-svg-full.js` rather than `tex-svg.js` since that includes all the extensions (but is a larger download for your users), or to disable the autoload feature (which will lead to undefined macros instead of the retry error (which is MathJax indicating that it is loading an extension, telling `typesetPromise()` to wait for that and try the expression after it is loaded).
