### ISSUE TITLE
MathJax requires unsafe "Content Security Policy"

### ISSUE THREAD

**Issue by mikkorantalainen** [mathjax/MathJax#256]
The current MathJax implementation uses following features that are not considered safe in modern world and cannot be used with default Content-Security-Policy (http://www.w3.org/TR/CSP/) headers:
- JavaScript evaluation of strings (new Function() with a string or eval()) (1)
- Inline style attributes inserted via JavaScript (2)

It's debatable if issue (2) should be fixed but at least (1) should be fixed because Content-Security-Policy does not have enough granularity to allow MathJax to execute as a trusted script and in the same time do not interpret every other JavaScript file as specially trusted. Currently, if one wants to use MathJax, he must allow eval() everywhere. The issue (1) also causes bug #130 (MathJax is incompatible with ECMAScript 5 strict mode).

Currently the only way to make MathJax to work, even if one uses locally installed MathJax code, is to use following CSP HTTP headers (the deprecated "options" header is included for Firefox 13.0  and lesser):

```
X-Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; options eval-script
X-WebKit-CSP: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'
```

These headers will allow some CSP provided protection and still allow MathJax to work, if MathJax is distributed from the same origin as the page content.

**Comment by kaushalmodi** [comment]
I am still seeing this issue. See https://github.com/mathjax/MathJax/issues/1988.

**Comment by dpvc** [comment]
@kaushalmodi, see [my comment above](https://github.com/mathjax/MathJax/issues/256#issuecomment-38032431) about how to avoid the problem, or my comment to the issue you link to.  You have to change how you configure MathJax if you are using a CSP that restricts script execution.

**Comment by mkamensky** [comment]
Was (2) in the original issue ever resolved? It seems that mathjax v3 still inserts <style> tags into the head

**Comment by scruel** [comment]
For MathJax version 3, the issue still exists.
I am writing Tampermonkey scripts which can't include other script file to load the configuration, also I will get CSP related errors while MathJax loading its fonts.
![image](https://user-images.githubusercontent.com/16933298/224209750-b764773c-3131-4d5f-b0a6-15641f5b92aa.png)

**Comment by dpvc** [comment]
@scruel,  you say:

> For MathJax version 3, the issue still exists.

Your issue is not the same as either (1) or (2) in the original message.  (1) has been resolved in v3 (and could be avoided in v2 by using the `MathJax={...}` form of configuration).  (2) is not going to be something we are able to avoid easily, but there is code in a [comment](https://github.com/mathjax/MathJax/issues/2665#issuecomment-814296897) to another issue that may be able to address that using nonces (but read the full thread for some caveats).

To be able to use MathJax with a CSP, you would need to include the CSN from which you obtain MathJax in the font-src and script-src directives (as well as allowing in-line styles).  If you are trying to insert MathJax into a page that has a CSP that you don't control, and if the CDN is not included there, then you may not be able to do it.

You may have better luck using the SVG output rather than CHTML, since that doesn't load fonts, only javascript, but if you can't load external javascript files, then that may limit what you are able to do.
