### ISSUE TITLE
mathjax.typeset cause memory leak

### ISSUE THREAD

**Issue by KevinZhoutianyi** [mathjax/MathJax#2567]
### Issue Summary

I am making an online markdown editor, and use Mathjax to deal with the math equation in the show-area of markdown.

To call mathjax dynamically, as long as user press any key, I will call mathjax.typeset to do the conversion.

However, after call typeset multiple times, the memory leak happens in chrome.

Is there any way to clear all the memory(JS heap) used by mathjax?

### Technical details:

mathjax/3.0.5
chrome

**Comment by dpvc** [comment]
When you replace content on the page that includes typeset mathematics, you ned to tell MathJax that the content has been removed so that it can free the structures it uses internally to maintain that mathematics.  See the documentation on [updating previously typeset content](https://docs.mathjax.org/en/latest/web/typeset.html#updating-previously-typeset-content) for more details.  The `MathJax.typesetClear()` function used to do that was updated in version 3.1.0  (see the [What's New in 3.1](https://docs.mathjax.org/en/latest/upgrading/whats-new-3.1.html#v3-1-typesetclear) page) to allow you to specify the elements on the page that are being updated.

**Comment by KevinZhoutianyi** [comment]
Thank you soooo much. It works! love you

**Comment by dpvc** [comment]
Glad that did the trick.
