### ISSUE TITLE
LaTeX mathspec package: disable double quote character

### ISSUE THREAD

**Issue by bdtc** [mathjax/MathJax#2568]
The LaTeX mathspec package makes the double quote character `"` active, which adds extra space around whatever follows.  There is also a `\"` macro which accepts a string of characters terminated by `"` and adds space around each.

I would like to emulate mathspec, and am not currently concerned about adding the extra space.  `\"` can be nullified easily.

Is there a simple way to nullify the double quote character `"` in math, but leave it alone inside `\text`?

**Comment by bdtc** [comment]
... using MathJax 3 ...

**Comment by bdtc** [comment]
No longer required.  I neutralized the double quotes at the source, but the method used has the unfortunate effect of also neutralizing them inside `\text`.  It could still be useful to be able to neutralize the `"` character outside of `\text`, but the current emulation for the mathspec package will probably be sufficient.  There are certainly higher priorities, so this issue may be closed.

**Comment by dpvc** [comment]
Sorry not to get back to you when you were needing this.  I have just finished teaching my first totally remote term, which required all of my time.

In any case, here is a configuration that will cause " to be ignored in math mode (but not in text-mode):

``` html
<script>
MathJax = {
  startup: {
    ready() {
      const special = MathJax._.input.tex.MapHandler.MapHandler.getMap("special");
      const Macro = MathJax._.input.tex.Symbol.Macro;
      const Ignore = function (parser, c) {};
      special.add('\"', new Macro('\"', Ignore, []));
      MathJax.startup.defaultReady();
    }
  }
};
</script>
```

It would be possible to change `Ignore()` to be a function that reads the next character and puts space around it, like `mathspec` does, but I suspect you really don't need that at the moment, since you aren't changing the font to a non-math font, which is what that feature is supposed to support.
