### ISSUE TITLE
Why not use fonts outside mathjax?

### ISSUE THREAD

**Issue by josephjohnston** [mathjax/MathJax#2578]
Of course mathjax fonts are only intended for mathjax, but why exactly should they not be used outside of mathjax?
For example, below compares the mathjax regular sans-serif font to some fallback sans-serif font.
The  regular text but not the mathjax text is selectable, telling me the mathjax font is not a regular font for styling text, and I'd like to know why.
I'd understand why it isn't selectable if it was inserted using the css `content` property, but here I just type the text and load the web font as I would any other.
With the burden of already loading perhaps more than several mathjax fonts, I was hoping to use some of them as custom fonts for styling other content beyond math.
```html
<html>
<head>
    <style>
        @font-face {
            font-family: MJXTEX-SS;
            src: url("https://cdn.jsdelivr.net/npm/mathjax@3.1.2/es5/output/chtml/fonts/woff-v2/MathJax_SansSerif-Regular.woff")
                    format("woff");
        }
        .first {
            font-family: MJXTEX-SS;
        }
        .second {
            font-family: sans-serif;
        }
    </style>
</head>
<body>
    <p class="first">math jax sans-serif</p>
    <p class="second">regular sans-serif</p>
</body>
</html>
```

**Comment by dpvc** [comment]
> why exactly should they not be used outside of mathjax?

Who said they shouldn't?  One reason you might not want to is that the font metrics are different for math fonts than for text fonts.  This is most noticeable with the math italic versus the main italic font.  (Try it with the word "office" for example.)  It's the same reason you don't write text in math mode without `\text{}` or one of the other text-mode macros.

> The regular text but not the mathjax text is selectable

This is actually not correct.  Both are selectable, but you just don't notice that the MathJax font is selected.  That is because some of the font metrics are set in an unusual way so that they can be positioned and sized properly for use in math layout.  In particular, they have nearly zero height and depth, so the selection background is essentially non-existent.  If you add

``` css
        ::selection {
          color: red;
        }
```

to your `<style>` element, for example, you will find that the MathJax text is being selected just fine.  (Or if you copy and paste after selecting the MathJax text, you will see that it has been copied.)

The MathJax TeX fonts are still the ones from version 2, and are planned to be replaced by new ones during our major work on font revision (started last summer, and continuing in Q1 and perhaps Q2 of 2021).  It is likely that the fonts will be better suited to regular text use at that point, though the depth will probably be larger than one would like for standard text use.  The zero height and depth will probably need to be changed, as it is the source of a rendering problem with Safari.

**Comment by josephjohnston** [comment]
Thank you for your explanation. I look forward to the new fonts.

**Comment by josephjohnston** [comment]
@dpvc Any update on the new fonts to replace those from version 2?

**Comment by dpvc** [comment]
@josephjohnston, still working on the release that will include those.  I expect early Q2, if all goes well.  I know it has been a long time.  I had hoped for last summer, but due to some personal circumstances, and depletion of funds, we were not able to get the release out before I had to go back to teaching in the fall.

**Comment by josephjohnston** [comment]
I understand, thank you for clarifying.
