### ISSUE TITLE
Render $$\text{N^*}$$error using tex-svg-full.js in Mat...@3.1.2, which was normal in version 3.0.5, but not normal after the update

### ISSUE THREAD

**Issue by z649319834** [mathjax/MathJax#2579]
Render $$\text{N^*}$$error using tex-svg-full.js in Mat...@3.1.2, which was normal in version 3.0.5, but not normal after the update？

**Comment by dpvc** [comment]
This is because the `textmacros` extension was added in v3.1, and the `-full` version includes all the extensions.  The `textmacros` extension processes macros and special characters in text mode (which is not the case without the `textmacros` extension), and since `^` is only allowed in math mode, not text mode, this is flagged as an error when the `textmacros` extension is in use.


You can disable the `textmacros` extension using

``` html
<script>
MathJax = {
  tex: {
    packages: {'[-]': ['textmacros']}
  }
}
</script>
```

just before the script that loads `tex-svg-full.js`.

**Comment by z649319834** [comment]
> This is because the `textmacros` extension was added in v3.1, and the `-full` version includes all the extensions. The `textmacros` extension processes macros and special characters in text mode (which is not the case without the `textmacros` extension), and since `^` is only allowed in math mode, not text mode, this is flagged as an error when the `textmacros` extension is in use.
> 
> You can disable the `textmacros` extension using
> 
> ```
> <script>
> MathJax = {
>   tex: {
>     packages: {'[-]': ['textmacros']}
>   }
> }
> </script>
> ```
> 
> just before the script that loads `tex-svg-full.js`.
Since MathJax@3.1.2 includes all the extensions, why add 'TextMacros' by default and remove' TextMacros' if there will be other exceptions? Currently, MathJax@3.1.2 is widely used in the company's business, so I don't want to cause other problems. Please give me more advice

**Comment by dpvc** [comment]
> why add 'TextMacros' by default and remove' TextMacros' if there will be other exceptions?

I don't understand the question.  The `textmacros` is included in the `-full` component because all extensions are included.  That is what asking for the `-full` version does.  Because the `textmacros` extension changes how the contents of `\text{}` is processed, in particular, it now processed some text-mode macros and special characters, the does mean some existing content may now be handled differently, and some content can cause errors.  For example, prior to v3.1, `\text{\error}` would not produce an error, but now it will.

If some of your content causes such errors, then you either need to change the content, or change the packages loaded to not include `textmacros`.

> MathJax@3.1.2 is widely used in the company's business, so I don't want to cause other problems

Removing the `textmacros` package should make `\text{}` in v3.1.2 act like it did in v3.0.5, if that is what you are asking about.

It would be possible to make a custom build of `tex-svg-full.js` that does not include `textmacros` that you host on your own site and load from there, if that is what you want.

**Comment by z649319834** [comment]
> > why add 'TextMacros' by default and remove' TextMacros' if there will be other exceptions?
> 
> I don't understand the question. The `textmacros` is included in the `-full` component because all extensions are included. That is what asking for the `-full` version does. Because the `textmacros` extension changes how the contents of `\text{}` is processed, in particular, it now processed some text-mode macros and special characters, the does mean some existing content may now be handled differently, and some content can cause errors. For example, prior to v3.1, `\text{\error}` would not produce an error, but now it will.
> 
> If some of your content causes such errors, then you either need to change the content, or change the packages loaded to not include `textmacros`.
> 
> > MathJax@3.1.2 is widely used in the company's business, so I don't want to cause other problems
> 
> Removing the `textmacros` package should make `\text{}` in v3.1.2 act like it did in v3.0.5, if that is what you are asking about.
> 
> It would be possible to make a custom build of `tex-svg-full.js` that does not include `textmacros` that you host on your own site and load from there, if that is what you want.

Thank you very much for your answer!!!
