### ISSUE TITLE
Input like "${t_2}^\circ\ce C$}" renders failed

### ISSUE THREAD

**Issue by wkh1234** [mathjax/MathJax#2580]
use  https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

render: 
![image](https://user-images.githubusercontent.com/35245044/101625604-98cb7080-3a56-11eb-9a7a-02878d1acffb.png)

I want render：

![image](https://user-images.githubusercontent.com/35245044/101625671-b698d580-3a56-11eb-9efd-37848182ce5b.png)

**Comment by dpvc** [comment]
Thanks for the report.  It turns out that this is due to an issue with autoloading tex extensions.  When the `mhchem` extension is loaded to process the `\ce`, the space between `\ce` and `C` is lost, and the macro becomes `\ceC`, which is not defined.  That is the source of the issue, here.

One solution would be to use `\ce{C}` rather than `\ce C`, and another would be to force `mhchem` to be loaded initially rather than autoloaded via

``` javascript
MathJax = {
  loader: {load: ['tex/mhchem']},
  tex: {packages: {'[+]': ['mhchem']}}
};
```

**Comment by dpvc** [comment]
I have made a pull request to resolve the issue.
