### ISSUE TITLE
NPEs with iframe for pwa in v2.7.9

### ISSUE THREAD

**Issue by alderg** [mathjax/MathJax#2582]
### Issue Summary

We have a PWA that adds MathJax.js (v2.7.9) and its dependent files to the cache. If we're using this app inside an iframe, we get null pointer exceptions like this one:

TypeError: Cannot read property 'Init' of undefined
at Object.Message (https://app.diagrams.net/math/MathJax.js:19)
at Function.execute (https://app.diagrams.net/math/MathJax.js:19)
at cb (https://app.diagrams.net/math/MathJax.js:19)
at Object.Process (https://app.diagrams.net/math/MathJax.js:19)
at Object.call (https://app.diagrams.net/math/MathJax.js:19)
at Function.WAITEXECUTE (https://app.diagrams.net/math/MathJax.js:19)
at cb (https://app.diagrams.net/math/MathJax.js:19)
at Object.Process (https://app.diagrams.net/math/MathJax.js:19)
at Object.call (https://app.diagrams.net/math/MathJax.js:19)
at Function.WAITEXECUTE (https://app.diagrams.net/math/MathJax.js:19)

Is this a known issue? What could be causing this? My understanding is that MathJax.Message.Init should be initialized at this point in time (or any asynchronous code in MathJax.js).

### Steps to Reproduce:

Not sure how to reproduce. It seems to be more frequent inside iframes. App is at https://app.diagrams.net

### Technical details:

* MathJax Version: 2.7.9
* Client OS: Mac OS X 11.0.1
* Browser: Chrome 87.0.4580.88

### Supporting information:

 * https://app.diagrams.net

**Comment by dpvc** [comment]
The error message is peculiar, certainly.  I don't know if it actually refers to the MathJax.Message.Init() function, as there are lots of Init functions, and it could be referring to one of those.  I don't see how the Message object could have been created without its Init function.

The structure of the message suggests that it may be occurring during the loading of one of MathJax's components (like the loading of the input or output Jax the first time it is used).  

* Does the problem occur for both SVG and HTML output?  
* Have you tried using the CommonHTML rather than HTML-CSS output jax?
* When you say the application is in an iframe, do you mean that https://app.diagrams.net itself is running in the iframe, or that you are calling MathJax on material that is inside an iframe?
* Can you run `MathJax.Messagse.Log()` in the browser console when this happens and see if there are any error messages there?

You might consider loading MathJax from a combined configuration file and see if that helps.  From the `app.min.js` file, I see a function `Editor.initMath` that would need to be altered to do that.  You might consider changing it to 

``` javascript
    Editor.initMath = function(a, b) {
        a = null != a ? a : DRAW_MATH_URL + "/MathJax.js?config=TeX-MML-AM_" + ("html" == urlParams["math-output"] ? "HTMLorMML" : "SVG") + '-full';
        Editor.mathJaxQueue = [];
        Editor.doMathJaxRender = function(a) {
            window.setTimeout(function() {
                "hidden" != a.style.visibility && MathJax.Hub.Queue(["Typeset",
                MathJax.Hub, a])
            }, 0)
        };
        var e = null != urlParams["math-font"] ? decodeURIComponent(urlParams["math-font"]) : "TeX";
        b = null != b ? b : {
            "HTML-CSS": {
                availableFonts: [e],
                imageFont: null
            },
            SVG: {
                font: e,
                useFontCache: !1
            },
            tex2jax: {
                ignoreClass: "mxCellEditor"
            },
            asciimath2jax: {
                ignoreClass: "mxCellEditor"
            }
        };
       ... // etc.
    };
```

Those are my initial thoughts.  See if any of those help.

**Comment by alderg** [comment]
Turns out we called initMath twice in some specific case. Thanks for your pointers, they helped us to resolve the issue (and the combined configuration file is better, anyway).

**Comment by dpvc** [comment]
Glad you were able to work it out.  Thanks for letting us know.
