### ISSUE TITLE
Document option to disable noundefined extension for TeX in v3

### ISSUE THREAD

**Issue by dorthrithil** [mathjax/MathJax#2587]
**Is your feature request related to a problem? Please describe.**
I don't wan't users to be able to save invalid TeX.

**Describe the solution you'd like**
The library should throw an error if invalid TeX is entered while `noundefined` is disabled.

**Describe alternatives you've considered**
v 2.7 where this was possible: `TeX: { noUndefined: { disabled: true } }`

**Comment by dpvc** [comment]
There is already a way to do that:

``` javascript
MathJax = {
  tex: {
    packages: {'[-]': ['noundefined']}
  }
}
```

which will remove the `noundefined` extension from the packages loaded by the TeX input jax.

The general process for this is listed at the end of the [Configuring MathJax](https://docs.mathjax.org/en/latest/options/index.html#configuring-mathjax), though it could be mentioned in the extension configuration sections for `noundefioned` and `noerrors`.

**Comment by dorthrithil** [comment]
Good to hear that the option still exists. The documentation could be a little more precise here, yes. Especially it's not clear that removing the extension will lead to new errors which was mentioned in the v2 documentation. Thanks for clarifying this!

(Not sure if I should close this or keep it open for you as a reminder to fix the documentation)

**Comment by dpvc** [comment]
I will leave it open and mark it as needing documentation.

**Comment by dorthrithil** [comment]
OK, so I disabled the `noundefined` extension and get rendered error messages like `undefined control sequence \abcdef` now. But I cannot detect whether such an undefined sequence was entered because in the code there is no error thrown. Is there another option to enable this hidden somewhere? I looked through the docs but couldn't find anything. Here's my code:

```js
MathJax.tex2svgPromise(`\abcdef`, options).then(function (node) {
    outputElement.appendChild(node);
    MathJax.startup.document.clear();
    MathJax.startup.document.updateDocument();
}).catch(function (err) {
    console.log(err); // This is not called for undefined sequences
});
```

**Comment by dpvc** [comment]
> Is there another option to enable this hidden somewhere? I looked through the docs but couldn't find anything.

Use the `formatError` option in the `tex` block, as documented [here](https://docs.mathjax.org/en/latest/options/input/tex.html#tex-formaterror).  (You could find it by searching for "Error".  The first entry is "TeX Error Formatting" which leads you to a description of this option.)  You can use something like

``` javascript
MathJax = {
  tex: {
    formatError(jax, err) {throw err}
  }
}
```

to cause TeX input error to be fatal (they will trigger your `catch` function.

Also note that when MathJax inserts an error message, it marks it with the `data-mjx-error` attribute, so you could do something like

``` javascript
function (node) {
  const errNode = node.querySelector('[data-mjx-error]');
  if (errNode) {
    // do something with the error (errNode.getAttribute('data-mjx-error') will be the error message).
  } else {
    // process normally
  }
}
```

BTW, you may get better results if you insert the math into the page and call `MathJax.typsetPromise()` rather than typesetting outside of the page and then inserting the result.  This will allow MathJax to properly determine the size of the surrounding font, the wrapping width (for when that is implemented), and other values that improve the output.  For example, characters that are not in the MathJax fonts will be able to be measured properly that way.

Also, you may want to look at the [documentation](https://docs.mathjax.org/en/latest/web/typeset.html#handling-asynchronous-typesetting) about handling asynchronous typesetting and chain your promise calls so that you don't accidentally call MathJax while it is already running.
