### ISSUE TITLE
Input like "\hat{\mu}_{i}" renders failed

### ISSUE THREAD

**Issue by fenghestat** [mathjax/MathJax#2589]
### Issue Summary

The input "is the standard deviation, \\(e_{it} = r_{it} - \hat{\mu}_{i}\\), and $m_{i}$ is the number of non-missing." failed to render.

![image](https://user-images.githubusercontent.com/74480108/102959168-d2679700-44ac-11eb-926d-e7a2e273ee5a.png)

The same issue seems applies to \bar{e}_{t}. It seems that I have an unclosed string, 

![image](https://user-images.githubusercontent.com/74480108/102959369-47d36780-44ad-11eb-91ab-adb1fad51367.png)

### Steps to Reproduce:

I wrote this formula in a markdown file using Sublime Text 3.

setting in MarkdownPreview

    "enable_mathjax": true,
    "js": [
    "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js",
    		"res://MarkdownPreview/js/math_config.js",
    ],

math_config.js

MathJax.Hub.Config({
  extensions: ["tex2jax.js"],
  jax: ["input/TeX", "output/HTML-CSS"],
  tex2jax: {
    inlineMath: [ ['$','$'], ["\\(","\\)"] ],
    displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
    processEscapes: true
  },
  "HTML-CSS": { fonts: ["TeX"] }
});

### Technical details:

* MathJax Version: 2.7.7
* Client OS: Windows 10
* Browser: 87.0.4280.88

**Comment by pkra** [comment]
This renders fine at https://www.mathjax.org/#demo.

Since you're using markdown, your markdown processor very likely interferes, converting consecutive underscores into italics. Depending on your markdown processor, there might be a custom way to write LaTeX syntax so this doesn't happen. Otherwise \\_ might be a workaround to escape the underscore handling in markdown. 

See also the many other issues on the topic, e.g., https://github.com/mathjax/MathJax/issues?q=markdown+underscore

**Comment by dpvc** [comment]
Also see the documentation about [interactions with content management systems](https://docs.mathjax.org/en/latest/input/tex/html.html#interactions-with-content-management-systems).

Note that some of your text appears in italics (e.g., `{t} \right)^{2}` following an underscore) which suggests that Peter's analysis is correct.

**Comment by fenghestat** [comment]
Thank you, pkra and dpvc! \_ works for me.
