### ISSUE TITLE
mathcd in custom element renders only after a change made to the source text

### ISSUE THREAD

**Issue by jxxcarlson** [mathjax/MathJax#2590]
### Issue Summary

The discussion below is relevant to [minilatex.lamdera.app](https://minilatex.lamdera.app) as demonstrated in [this demo app](https://jxxcarlson.github.io/app/mathjax/).

(1) matchcd commutative diagram renders only after the user makes a change to the source text or pushes **Full Render** or **Restore** buttons.  This suggests that the problem has to do with when certain chunks of code are loaded.

(2) arrows too short in Chrome, OK in Firefox.  This suggests a font loading problem.

Alas, I don't know how to solve these issues.

### Steps to Reproduce:

1. Go to https://jxxcarlson.github.io/app/mathjax/ in Firefox
2. The app will load with two math elements, the first correctly rendered, the second, which uses amscd, showing the source instead of the rendered text.
3. In the source window, add text or change it.  Alternatively, press the button **Restore** or **Full Render**.  The commutative diagram will be rendered correctly. 

The relevant code is in https://github.com/jxxcarlson/jxxcarlson.github.io/tree/master/app/mathjax

Davide, this is not a bug in MathJax *per se*, but rather in my use of it.  I am using the custom element code you kindly provided me. Here are the assets used:  

```
├── custom-element-config.js
├── math-text.js
├── mathjax-text.js
└── style.css
```
The mathjax-text.js element is a clone of math-text.js, but that is how the app refrences mathjax for the CD environment, as it is an experiment.

### Technical details:

* MathJax Version: 3 from https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
* Client OS: Mac OS X 11.0.1
* Browser: Chrome 87.0.4280.88 

### Supporting information:

 * [Link to demo app](https://github.com/jxxcarlson/jxxcarlson.github.io/tree/master/app/mathjax)
 * [Link to the code](https://github.com/jxxcarlson/jxxcarlson.github.io/tree/master/app/mathjax)
 * Console errors:
 
 ```
 Uncaught Error: MathJax retry
    at Object.e.retryAfter (tex-chtml.js:1)
    at Object.y [as RequireLoad] (tex-chtml.js:1)
    at f (tex-chtml.js:1)
    at e.parse (tex-chtml.js:1)
    at t.parse (tex-chtml.js:1)
    at t.parse (tex-chtml.js:1)
    at p.BeginEnd (tex-chtml.js:1)
    at e.parse (tex-chtml.js:1)
    at t.parse (tex-chtml.js:1)
    at t.parse (tex-chtml.js:1)
```

 *  MathJax configuration and the script tag that loads MathJax itself: 
 
 Here is how MathJax is configured in `custom-element-config.js`

```
MathJax = {
  tex: {inlineMath: [['$', '$'], ['\\(', '\\)']]},
  options: {
    skipHtmlTags: {'[+]': ['math-element']}
  },
 ```

And here is how MathJax and associated resources are loaded in `index.html`:

```
    <!-- Load MathJax code -->
    <script src="assets/custom-element-config.js"></script>
    <script src="assets/math-text.js"></script>
    <script src="assets/mathjax-text.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>
```
### Screenshot when app loads

![image](https://user-images.githubusercontent.com/679991/103020150-f14e4380-4515-11eb-86aa-154df4bb66b9.png)

## Screenshot after making a change in the source or pushing Re-render or Restore

![image](https://user-images.githubusercontent.com/679991/103020212-03c87d00-4516-11eb-8139-fe2facc4d437.png)

**Comment by dpvc** [comment]
> This suggests that the problem has to do with when certain chunks of code are loaded.

You are correct, this is due to an attempt to autoload the `amscd` component.  The current `typesetShadow()` method is not set up to handle loading of additional components, which is an asynchronous process, whereas `typesetShadow()` is synchronous.  

There are two solutions:  either load `tex-chtml-full.js` rather than `tex-xhtml.js`, so that all the extensions are already loaded and no asynchronous loads must be made, or make a promise-based version of `typesetShadow()` that handles asynchronous loads properly.  Since you are not really using the synchronous nature of the typesetting, you might be able to get away with the latter, though you might have to chain the promise calls so that you don't accidentally call MathJax a second time while an earlier call is waiting for an asynchronous load.

A possible promise-based version is

``` javascript
      MathJax.typesetShadowPromise = function (root) {
        const InputJax = startup.getInputJax();
        const OutputJax = startup.getOutputJax();
        const html = mathjax.document(root, {InputJax, OutputJax});
        return MathJax.handleRetriesFor(() => html.render());
      }
```

It would get called via

``` javascript

let promise = Promise.resolve();

class MathJaxText extends HTMLElement {

  connectedCallback() {
      const content_ =  this.display ? '$$' + this.content + '$$' : '$' + this.content + '$' ;
      this.attachShadow({mode: "open"});
      this.shadowRoot.innerHTML =  '<mjx-doc><mjx-head></mjx-head><mjx-body>' + content_ + '</mjx-body></mjx-doc>';
      promise = promise.then(() => MathJax.typesetShadowPromise(this.shadowRoot));
  }

}
```

**Warning:**  untested code, but this is the general idea.

-----

> arrows too short in Chrome, OK in Firefox. This suggests a font loading problem.

I'm not able to reproduce this in Chrome, but I do see it in Safari, so perhaps it is the same issue.  That is not due to a font loading problem, but rather to a positioning issue for the extender for the stretchy arrow.  I believe it is a bug in WebKit (which is why it may also affect Chrome), but I have a work-around in Safari.  Try adding the CSS

``` css
mjx-stretchy-h > mjx-ext > mjx-c::before {
  padding-top: 1px;
}
```

See if that helps you out.

**Comment by jxxcarlson** [comment]
Hello Davide,

Thanks very much for your reply … the tex-chtml-full.js solution works really well (like a charm!), so I have adopted that.  Still working on the Chrome “arrows” problem … the CSS fix did’nt work, but I’ll have some other folks try the app in Chrome.  Maybe there is something weird in my setup. 


— Jim

**Comment by dpvc** [comment]
I forgot that your math is in shadow DOMs, so the CSS would have to be included in them.  One way would be to modify `<mjx-head></mjx-head>` to be

```
<mjx-head><style>mjx-stretchy-h > mjx-ext > mix-c::before {padding-top: 1px}</script></mjx-head>
```

in `mathjax-text.js`, at least for testing purposes.  It would also be possible to add this in to the mathjax configuration, but this is probably easier for testing.
