### ISSUE TITLE
Formulas not displayed in any browser on any system

### ISSUE THREAD

**Issue by mhechthz** [mathjax/MathJax#2604]
Hi,

I'm not sure if this is the right place, so I try and ask for forgiveness if it wasn't ok. I try to see the formulas on the FiPy web page from NIST, e.g. https://www.ctcms.nist.gov/fipy/documentation/FAQ.html which are obviously configured using MathJax.

I failed with any browsr on several systems and browsers. I asked the webmaster of NIST (which is in my opinion a quite honorable site) but got now answer. If there would be a bug on the page I'm sure, that other users would have found it long ago. So what do I need to configure to see the formulas?.

**Comment by dpvc** [comment]
It looks like the page you cite isn't configured properly (they are using jsMath math delimiters rather than TeX delimiters, and don't have the proper extension loaded to process that).  It has already been reported on their [issue tracker](https://github.com/usnistgov/fipy/issues/762) back in October, so it looks like they aren't planning to fix it, but you might try pinging them there to see if you can prod them to do it.

In the meantime, you could open the browser's web console and type

```
MathJax.Ajax.Require('[MathJax]/extensions/jsMath2jax.js');
MathJax.Hub.Typeset();
```

and that should cause the math to be processed.  You should be able to make a bookmarklet out of it, or a Tampermonkey script, if you needed to do that a lot.

**Comment by mhechthz** [comment]
Thank you, at least in Firefox is works. For Chrome I get a new strange error with "blinking" span tags. Nevertheless, this solves my problem.

Thank You.

**Comment by dpvc** [comment]
Glad you get something that works for you.

**Comment by mhechthz** [comment]
Update: Meanwhile (after a Windows update) also Edge works with the workaround. This is better, because pasting code in the console is slightly difficult in Firefox but easy in Edge.
