### ISSUE TITLE
v3, SVG: \smash leads to 0 height

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#2605]
E.g., `\smash {\mathbb{R}^2}` renders to an SVG with height 0 (and similar viewport).

**Comment by dpvc** [comment]
It looks like 0-height SVGs are not displayed, as you probably noted.  We should probably make a small minimum height (and width) to prevent that.

**Comment by pkra** [comment]
> It looks like 0-height SVGs are not displayed, as you probably noted. We should probably make a small minimum height (and width) to prevent that.

I don't quite understand. Why would the SVG have height 0? I'd expect the output to appear identical to just \mathbb{R}^2 (as in CHTML).

**Comment by dpvc** [comment]
The height is 0 because you *asked* for the height to be 0 (that is what `\smash` does).  The output will be just `\mathbb{R}^2`, but it has no height.  That is also the case in CHTML.  (At least the `<mjx-math>` element is height 0.  The `<mjx-container>` ends up with a few pixels of height for reasons that I don't fully understand, but it is at least in part  because it is an in-line element, and there is a minimum height for those that has something to do with the line-height and font metrics of the surrounding font.)

The CSS for the `<svg>` elements produced by MathJax v3 have `overflow:visible`, so even though the height is 0, it should still display the content (unless you have not included the MathJax CSS in your page).  The problem is that a 0-height `<svg>` seems not to be rendered at all, so it needs a small amount of height for that to happen.  That is why I said to use a minimum height.

**Comment by pkra** [comment]
> The height is 0 because you asked for the height to be 0 (that is what \smash does).

Right, but I was thinking of this as "internally"

> The CSS for the <svg> elements produced by MathJax v3 have overflow:visible, so even though the height is 0, it should still display the content (unless you have not included the MathJax CSS in your page). 

Ah! I had not thought overflow works this way with SVG, especially not with the viewbox height. Thanks for explaining!

**Comment by dpvc** [comment]
I have made a PR to correct the problem of having a 0 height.

**Comment by pkra** [comment]
As a temporary workaround: `svg {min-height: 1px!important;}` seems sufficient.

**Comment by dpvc** [comment]
Thanks for the work-around.  I think that may be the easiest way to handle it (using a selector that is specific to the MathJax output).
