### ISSUE TITLE
\not a (etc) not italic 

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#2617]
E.g., $\not a$ comes out normal (u0061) whereas $\not{a}$ comes out math italic (u1D44E).

Screencap from https://www.mathjax.org/#demo

![image](https://user-images.githubusercontent.com/426686/105867920-e47dad80-5ff5-11eb-9742-e2d384e6ff31.png)

**Comment by dpvc** [comment]
OK, here's what's happening.  The `\not a` is creating `<mi>a&#x338;</mi>`, which ends up being a two-character `<mi>`, so its content is typeset with `mathvariant="normal"`.  I could make it be `<mi mathvariant="italic">a&#x338;</mi>`, but then the slash will also be in italics (that doesn't matter for the MathJax TeX fonts, but the STIX2 fonts do contain an italic U+0338, so that will be used, here).  Is that OK?  For something like `<mi mathvariant="bold">a&#x338;</mi>` I would think one would want the slash to be bold, so should the italic mathvariant use the italic one?  

The only alternative would be to do two elements, like `<mrow><mi>a</mi><mi mathvariant="normal">&#x338;</mi></mrow>`, but that has the wrong semantics.  Perhaps `<mrow data-mjx-texclass="ORD"><mi>a</mi><mo lspace="0" rspace="0">&#x338;</mo></mrow>` is better?

**Comment by pkra** [comment]
Ah, I shou'dve thought of that (I had actually looked at the MML). I'll check regarding STIX2 (but this was just a tangential find while working on the unicode-math extension).

**Comment by dpvc** [comment]
I suppose another alternative is to not count combining characters when determining whether the content is one character or not.  I'm not sure if that would be against the spec or not.  I think it doe make sense to consider them as a single glyph, so this might be the best approach.  This will become more important when we handle combining characters better during TeX input, for example.

It turns out that v2 accidentally doesn't count the U+0338 because of how it was added on, and so renders using italics.

**Comment by pkra** [comment]
Sorry for dropping the ball on this one. @davidmjones had looked at unicode-math / xelatex behavior and IIRC that was a bit dodgy  but MathJax v2's behavior was good with him. 

@davidmjones can you comment regarding the italic vs nonitalic slash issue in https://github.com/mathjax/MathJax/issues/2617#issuecomment-767684246?

**Comment by dpvc** [comment]
OK, I have tested out the following idea:  don't count combining characters as part of the length of an `<mi>`, and drop the italic U+0338 from the STIX2 font data so that `<mi>a&#x338;</mi>` will get `mathvariant="italic"` automatically, but the slash will fall back on the normal version, since the italic one is  not present.  What do you think of that idea?

**Comment by dpvc** [comment]
@pkra, any thoughts on my solution of dropping the italic U+0338 and not counting combining characters when determining the length of the `<mi>`?  I have a branch ready to go if you like the idea.

**Comment by pkra** [comment]
> @pkra, any thoughts on my solution of dropping the italic U+0338 and not counting combining characters when determining the length of the `<mi>`? I have a branch ready to go if you like the idea.

@dpvc I checked with @davidmjones and this sounds good.

**Comment by dpvc** [comment]
OK, I've pushed the `issue2617` branch that handles the (non) counting of combining characters, and made an update to the `stix2-svg` branch to remove the U+0338 character from the italic mathvariant.  That should produce better results for `\not a`.
