### ISSUE TITLE
inline MathJax is over left text ( width of stack span to small )

### ISSUE THREAD

**Issue by ev45ive** [mathjax/MathJax#262]
Setting Scale of HTML-CSS output Jax in config/default.js to 85 to match font size of surrounding text my inline math block is shorther than the contents, so it overlaps with the text on its right. The em value is bit too small.

Problem exists only in Google Chrome (19.0.1084.56 m)

**Comment by schinalex** [comment]
Hey! I have a problem with overlapping elements, although it's a bit different.
How can I target the rendered MathJax formulas with CSS, because they overlap on one another if they div containing them is smaller than the text that will be rendered.
What I do is write a few divs with some dimensions (say width:50px; height:50;), in each div I write a math formula (of different sizes). If the formula rendered is bigger than the div then it overlaps on the next div's formula. I could set the div a larger width, but then when the formula is short the text will be too far from one another.
I want to set something like "position: relative" so they would not overlap (as they would be relative to one another wouldn't they?). Will that work? or is there another solution.
Anyway... I need to target them directly. But there are so many classes and spans and div, I can't figure out which one represents the rendered text. I have this problem for several weeks now, and still couldn't fix that.
Please help!

**Comment by pkra** [comment]
Please don't double post. Thanks.
