### ISSUE TITLE
[v3] custom attributes on <a> in the output

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#2620]
In v2, I used something like 

```
 function(name) {
      var attributeValue = this.GetBrackets(name),
        url = this.GetArgument(name),
        arg = this.GetArgumentMML(name);
      arg = MML
        .mrow(arg)
        .With({
          href: url,
          attr: { 'data-xxx':  attributeValue },
          attrNames: [
            'data-xxx',
            'href',
          ],
        });
      this.Push(arg);
}
```

which would push the custom attribute to the anchor tag.

In v3, the similar 

```
function (parser: TexParser, name: string) {
    const attributeValue = parser.GetBrackets(name);
    const url = parser.GetArgument(name);
    const arg = GetArgumentMML(parser, name);
    let mrow = parser.create('node', 'mrow', [arg], {
        'data-xxx': attributeValue,
        href: url
    });
    parser.Push(mrow);
}; 
```

pushes the custom attribute to the mrow's output instead (inside the anchor tag).

This change of behavior makes sense of course. But is there (or could there be) a way to add custom attributes to the anchor?

**Comment by pkra** [comment]
I guess my real question is: could anchors just be a first class citizen in the internal format?

**Comment by dpvc** [comment]
Making an internal node for the `<a>` elements would be somewhat problematic, but I don't think it is necessary.  For example, here is a post-filter that you can add to the SVG output that will transfer attributes with names `data-href-*` from the MathML node's `<g>` element to its associated `<a>` element (removing the '-href' from the name).  So, for example, `<mi href="test.html" data-href-test="true">x</mi>` would end up with an `<a href="test.tml" data-test="true">`.

``` javascript
MathJax = {
  startup: {
    ready() {
      MathJax.startup.defaultReady();
      //
      //  Add a postfilter to the SVG output jax
      //
      MathJax.startup.output.postFilters.add(function ({data, document, math}) {
        const adaptor = document.adaptor;
        //
        //  Look for all the <a> elements in the output
        //
        for (const a of adaptor.tags(data, 'a')) {
          //
          //  Get the MathML node's <g> element and an array of attributes starting with 'data-href-'
          //
          const node = adaptor.lastChild(a);
          const hrefData = adaptor.allAttributes(node).filter((attr) => attr.name.substr(0,10) === 'data-href-');
          //
          //  Remove the attribute from the <g> and add it to the <a> (without the '-href').
          //
          for (const {name, value} of hrefData) {
            node.removeAttribute(name);
            a.setAttribute(name.replace(/-href/, ''), value);
          }
        }
      });
    }
  }
}
```

Perhaps that is good enough?

**Comment by pkra** [comment]
Ok. I thought it would be fairly simple and a step in the right direction (recalling an old TeX question about \href{\class{}}) but fair enough.

I already work around the problem via post-processing but I don't think it's a good solution solution. For example, your example could move attributes to the anchor that are not coming from the node that has the href (and possibly overwrite previously added attribute values) . Granted, likely not with as specific an attribute name as data-href but I don't have that luxury (e.g., with the role attribute).

In any case, thanks for considering.

**Comment by dpvc** [comment]
> For example, your example could move attributes to the anchor that are not coming from the node that has the href

I'm not sure I see how that would happen.  The last child of the `<a>` element should be the `<g>` node that is the one that cause the `<a>` to be inserted.  (The only `<a>` elements that are in there should be the ones that come from `href` attributes on MathML elements, unless you are considering annotation-xml from semantics elements).

If you have an example in mind, we can probably make the code handle that.

> and possibly overwrite previously added attribute values

Again, I'm not sure how that would work.  The `<a>` only has an `href` attribute by default, and since the code only moved `data-href-`attributes (to `data-` attributes) and since there can't be two different `data-href-` attributes with the same name, I don't see how there can be conflicts.  If you want to be able to attach non-data attributes to the `<a>`, that could be done by removing the full `data-href-` prefix, (so you could do `data-href-role` to set `role` on the `<a>`), but your original message only talked about setting `data-xxx`, not other attributes.  But it could certainly be done.  In that case, you would want to avoid `data-href-href`, but since `href` is the only original attribute on the `<a>`, I don't see that there would be any other conflict worries.

As above, if you have an example in mind, I'd be happy to see it.

> likely not with as specific an attribute name as `data-href` but I don't have that luxury (e.g., with the role attribute)

My example was set up to allow you to put attributes on both the `<a>` and the original MathML node's `<g>` element.  The `data-href-` prefix was used to indicate which ones to move and which ones to keep in place.  If you wanted to move *all* the attributes, you could do that, but probably wouldn't want to move the 'data-mjx-' ones, or perhaps the SRE-generated ones.  Or you could have a white-list ones to move.

Perhaps I've missed something important?
