### ISSUE TITLE
[v3] could TextMacrosConfiguration.ts export Configuration.create() ?

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#2623]
Without thorough checking, it seems TeX extensions usually export their Configuration.create calls, e.g.

https://github.com/mathjax/MathJax-src/blob/6ba6cca458080ec2a73c60f8b19db6491985f92b/ts/input/tex/ams/AmsConfiguration.ts#L51

However, the text macros extensions  

https://github.com/mathjax/MathJax-src/blob/6ba6cca458080ec2a73c60f8b19db6491985f92b/ts/input/tex/textmacros/TextMacrosConfiguration.ts#L96

does not - it only exports Configuration.local().

For background, this tripped me up since I prefer using the configuration's name property when configuring a TeX input, e.g.,

```js
const {textBase} = require('mathjax-full/js/input/tex/textmacros/TextMacrosConfiguration.js');

const tex = new TeX({
  packages: [textBase.name],
});
```

which fails because Configuraton.local() doesn't have a name prop.

**Comment by dpvc** [comment]
OK, I will add it.  Note, however, that you should **not** use `textBase` as a package for the TeX input jax (I assume you were trying for the `textmacros` configuration object instead).  The `textBase` configuration won't work with the `TexParser` object, because it is designed for a subclass of `TexParser` that has extra methods and data (for text parsing).  That's one reason it is a local configuration, not a global one.
