### ISSUE TITLE
Svg render error, when input  '·' repeatly

### ISSUE THREAD

**Issue by qq240814476** [mathjax/MathJax#2627]
This error can recurrent by https://www.mathjax.org/#demo

```
$····$ // wrong
$···$ // right
```

When the time of input '·'  is odd, the `transform` attr of  last '·'  can be calculated correctly
In case it's even, `transform`  attr will be calculated less than normal

I use MathJax 3.x

**Comment by dpvc** [comment]
The output is correct, and in accordance with LaTeX output.  It has to do with how binary operators with no preceding or following operand are treated.  For example, `x-` should not render with space between the `x` and the `-`, but `x-y` should have space there.  This is handled in TeX by changing the class of some items in the math list depending on what precedes or follows it.

Initially, all four bullets are assigned class Bin (binary operator), but the processing of the list includes the rule (see Appendix G of the TeXBook):

> (Rule 5) If the current item is a Bin atom, and if this was the first atom in the list, or if the most recent previous atom was Bin, Op, Rel, Open, or Punct, change the current Bin to Ord.

This means that the initial bullet will change to type Ord (ordinary) since it is the first node in the list, then the second bullet will remain Bin, and the third will be converted to Ord by rule 5 (since it is preceded by a Bin).  The fourth is kept as Bin for the moment, but there is a later rule (listed just before rule 19):

> After the entire math list has been processed by Rules 1–18, TeX looks at the last atom (if there was one), and changes its type from Bin to Ord (if it was of type Bin).

That means that the final bulls become type Ord as well.  So the type of the four bullets are now Ord, Bin, Ord, Ord.

The spacing between two items it determined by the table given in Chapter 18 of the TeXbook (p. 170) which indicates the space based on the types of the two items.  Between an Ord and a Bin (or a Bin and an Ord) there is to be a medium space (size "2" in the table), but between two Ord items there is no space.  

So this means there is between space between the first and second bullets, and the second and third, but no space between the last two.  That is exactly as MathJax handles it.  (And if there were three bullets, you would have Ord Bin Ord, and there would be medium space between them).

So this output is entirely in accordance with TeX's output, and as that is what MathJax is supposed to produce, this is the correct result.  For example, here is actual TeX output for `$$++++$$` (four binary operations in a row):

<center>
<img width="238" alt="pluses" src="https://user-images.githubusercontent.com/432782/106632012-4df84180-654b-11eb-8d7e-a2ca303d53b8.png">
</center>

If you want spacing between the final ones, you need to use `$$++++{}$$` to make it have an empty operand following the last plus.
