### ISSUE TITLE
No space around operators under high roots

### ISSUE THREAD

**Issue by Lutalli** [mathjax/MathJax#2630]
MathJax doesn't add space around the operators under a root with an order, like a cube root, fourth root, *n*th root, etc.

Example: If I write
```
\[ \sqrt{x+y} \qquad \sqrt[3]{x+y} \]
```
I get the following result:
<img width="314" alt="image" src="https://user-images.githubusercontent.com/47910890/107042432-ba4d9c00-67fc-11eb-9fe6-36cd21cd0044.png">
Notice the difference between the normal square root on the left, where there is space around the + symbol, and the cube root on the right, where there is no space.

I'm working on Safari with the latest version (3.1.2) of MathJax.

Thanks!

**Comment by dpvc** [comment]
Thanks for the report.  I will look into it.

**Comment by dpvc** [comment]
Good grief, it turns out that the `mroot` element (that underlies higher-order roots) doesn't perform the tex-class computations that are needed for the spacing.  I don't know how that could have slipped by for so long!

I have made a pull request for it.  If you want a configuration that resolves the issue, I can put one together for you.

Again, thanks for the report!

**Comment by Lutalli** [comment]
Really thanks for the check! I'm not in a hurry to resolve it. Waiting for the new version!
