### ISSUE TITLE
TeX parse error: Undefined control sequence \minus

### ISSUE THREAD

**Issue by xxuyang** [mathjax/MathJax#2635]
### Issue Summary

input`k \\geq 2 \\minus k`，error：**TeX parse error: Undefined control sequence \minus**。

### Steps to Reproduce:

1. `npm install mathjax-node`
2. copy node example,change tex to `k \\geq 2 \\minus k`
3. node app.js，return data.errors:**TeX parse error: Undefined control sequence \minus**

### Technical details:

* "mathjax-node": "^2.1.1",
* Client OS: win 10

**Comment by xxuyang** [comment]
input `k \\geq 2 \\minus k` to web example(https://mathjax.github.io/MathJax-demos-web/input-tex2svg.html),
renders visually wrong.

**Comment by dpvc** [comment]
The macros defined in MathJax are based primarily on the `amsart` article style, without additional packages loaded, and `\minus` is not defined in that setting, so MathJax dos not have `\minus` defined.  Of course, you can do `\newcommand{\minus}{-}` (inside math mode) in your page, or add

``` html
<script>
MathJax = {
  tex: {
    macros: {
      minus: '-'
    }
  }
}
</script>
```

to your page just before the script that loads MathJax.

As for `k \\geq 2 \\minus k`, you would want to use `k \geq 2 \minus k` in the page you link, since the commands are `\geq` and `\minus`, whereas `\\geq` is the command `\\` followed by the letters `g`, `e`, and `q` (and similarly for `\\minus`).  If you are entering the TeX into a string in javascript, you would need to double the backslashes because a backslash is a special character in javascript string literals, so to get a single backslash in a javascript string, you need to double it.  E.g.,

``` javascript
const tex = "k \\geq 2 \\minus k";
```

but directly in a web page (or in a text-area where you enter TeX code) you would use

``` html
... \(k \geq 2 \minus k\) ...
```

So all of this is correct as it is.

**Comment by dpvc** [comment]
Sorry, I see you are using mathjax-node, but you link to the v3 node demos.  To predefine the macro in mathjax-node, you would need to add

``` javascript
const mjx = require('mathjax-node');

mjx.config({
  MathJax: {
    TeX: {
      macros: {
        minus: '-'
      }
    }
  }
});
```

before calling `mjx.typeset()`.
