### ISSUE TITLE
MathJax 3, class{ } and asciimath. Scheduled release date, question

### ISSUE THREAD

**Issue by sqlpac** [mathjax/MathJax#2640]
Bonjour,

We are excited to migrate to MathJax 3 (great improvements : performance, extensions physics and brackets in Tex context). Congratulations.

But we face one blocking point to migrate : some chapters pages use AsciiMath and the syntax class { }. MathJax still relies on AsciiMath 1.x, do you have any planned release date about AsciiMath 2 support that includes class { } tex syntax in MathJax 3.

Sorry for my english. Thank you, best regards.

**Comment by dpvc** [comment]
Both MathJax version 2 and version 3 use AsciiMathML v2, but the copy in v3 is from 2017 (when the the preliminary AsciiMath support was added to v3), while the one in v2 has been updated since then.  A number of new commands have been added since then, including `class`, so they are missing from the AsciiMath support in MathJax v3.

I will update AsciiMath in the next release.  Unfortunately, I can't give you a patch to enable this in the meantime, so you will have to wait for the next release.  We are working on 3.1.3 right now, but it is still some weeks away.

**Comment by sqlpac** [comment]
Thank you very much for answering the question.  Very good news, looking forward to upgrading to version 3.1.3.
