### ISSUE TITLE
Italic fonts not applied using AsciiMath and text { } syntax, MathJax 2 and 3.

### ISSUE THREAD

**Issue by sqlpac** [mathjax/MathJax#2641]
Bonjour,

Using text { } syntax in AsciiMath, italic math fonts are not applied, code sample :
    `R=D/L=frac (text{del_lf_rows})(text{lf_rows}) >= 0,1`

We have to force the fonts using CSS :
MathJax 2 : 
```css
.mjx-mtext > * { font-family: MJXc-TeX-math-I,MJXc-TeX-math-Ix,MJXc-TeX-math-Iw !important; }
```
MathJax 3 : 
```css
mjx-mtext > * { font-family: MJXZERO, MJXTEX-I !important; }
```

The solution should be to write : `R=D/L=frac ("del_lf_rows")("lf_rows") >= 0,1`, the fonts are then the right ones, but we want to keep the Tex like syntax in some specific wrinting contexts.

Regards

**Comment by dpvc** [comment]
Note that the `text{}` command puts the contents into a `mtext` element, and that has `mathvariant="normal"` by default, so it should not be italic, and the MathJax output is correct as it stands.  Using italics for these identifiers is usually not considered correct, but if that is what you want to do, you should not use CSS to accomplish it, as MathJax will not get the sizes of the parts correct if you do.  Instead, you can use the `mtextFont` configuration option in v3 to force the output to be in another font.  

For example, you could include

``` javascript
MathJax = {
  loader: {load: ['input/asciimath', 'output/chtml', 'ui/menu']},
  chtml: {
    mtextFont: "MJXTEX-MI"
  }
}
```

as part of your configuration.  (It is better to use `MJXTEX-MI` than `MJXTEX-I` since the former is the italic font for text, while the latter is the italic font for math).

An alternative would be to use

``` javascript
MathJax = {
  loader: {load: ['input/asciimath', 'output/chtml', 'ui/menu']},
  startup: {
    ready() {
      const AM = MathJax.InputJax.AsciiMath.AM;
      AM.newsymbol({
        input:"it", tag:"mstyle", atname:"mathvariant", atval:"-tex-mathit", output:"mathit",
        tex:null, ttype:AM.TOKEN.UNARY
      });
      MathJax.startup.defaultReady();
    }
  }
}
```

to add a new command `it` that you can use around text to make it italic. Then your expression would be

```
`R=D/L=frac (it{"del_lf_rows"})(it{"lf_rows"}) >= 0,1`
```

or

```
`R=D/L=frac (it{text{del_lf_rows}})(it{text{lf_rows}}) >= 0,1`
```

Perhaps one of those will do what you want.

**Comment by sqlpac** [comment]
Thank you very much ! We have learnt a lot with your answer, even how to create new commands for AsciiMath.

Everything is perfect when setting `MJXTEX-I` (we need the math font)

```javascript
MathJax = {
  loader: {load: ['input/asciimath', 'output/chtml', 'ui/menu']},
  chtml: {
    mtextFont: "MJXTEX-I"
  }
```
}

**Comment by dpvc** [comment]
> we need the math font

OK, but the spacing will be wrong for textual material (which is what you are using).  For example, consider the output for `text{office}` using `MJTEX-I` versus `MJXTEX-MI`.

**Comment by sqlpac** [comment]
Right, you're the best : `MJXTEX-MI` is better for spacing. Office is a good example.

What we try to solve is the following context, and in this context no CSS is loaded

It's nearly perfect with AsciiMath/Tex and no CSS : font-size is 98.9% which is acceptable

```css
<mjx-utext variant="-explicitFont" style="font-size: 98.9%; padding: 0.758em 0px 0.202em;">Office</mjx-utext>
```
![mathjax-office-1](https://user-images.githubusercontent.com/50557334/112230494-34af6f80-8c35-11eb-9d5c-28cfdc486f61.png)

As soon as we introduce a font family, just this property, percentage becomes 81%. The O in upper case is too small

```html
  <head>
   <style>body { font-family: Verdana, Arial, sans serif; }</style>
 </head>
```
```css
<mjx-utext variant="-explicitFont" style="font-size: 81.1%; padding: 0.924em 0px 0.247em;">Office</mjx-utext>
```

![mathjax-office-2](https://user-images.githubusercontent.com/50557334/112230817-d20aa380-8c35-11eb-85dd-7923a542ff1a.png)

It's a detail, but in some pages we see evidence of this in the rendering.

**Comment by dpvc** [comment]
MathJax sets the font size of its typeset math to match the surrounding font so that the ex-height of the math matches the ex-height of the surrounding font.  Since the ex-height varies from font to font, the MathJax scaling factor varies as well.  Generally, MathJax has to scale up its font size to match the surrounding font, so you may see `font-size:123%` on the `<mjx-container>`, or something similar.  When an mtext font is specified, MathJax applies the reverse scaling to get back to the "normal" scaling of the surrounding font.  In this case, since you are using the MathJax font for the mtext, that "un-scaling" is in appropriate, and causes the size mismatch.

One option is to disable the automatic font matching using the `matchFontHeight: false` option in the `chtml` block of your configuration.  That may mean that the math doesn't match the surrounding quite so well, but the internal test will be more consistent.  You could add `scale: 1.23` as well in order to match the surrounding font by hand (on a global basis, not equation-by-equation).

Alternatively, you could set

``` css
mjx-utext {
    font-size: 100% ! important;
}
```

in your CSS which would force the scaling to 100%.

**Comment by sqlpac** [comment]
It's perfect, thank you very much. We were considering this CSS fix on `mjx-utext` and you confirm it.
