### ISSUE TITLE
Strange bug with using  \tag after \color

### ISSUE THREAD

**Issue by kwankyu** [mathjax/MathJax#2643]
This is with MathJax version 3.

In the source webpage, after this math display

``` 
\[
	\begin{aligned}
	\color{red}{1}
	\end{aligned}
\]
```

I have this math display

```
\[\tag{S}
\]
```

On the rendered webpage, the second display shows a strange error 

         \tag is not allowed in aligned environment

This seems a bug in MathJax.

**Comment by dpvc** [comment]
I can reproduce the result, and yes, it does seem to be a bug.  Thanks for the report.  I will investigate further.

**Comment by dpvc** [comment]
OK, I figured it out.  The tagging module keeps a stack of tagging information (as different environments are started and stopped), and it turns out that during the autoload of the `color` extension, the tag information was not being reset when the equation was being re-rendered.  That left an extra tagging information object on the stack, and that ended up being the initial state for the next equation (instead of a blank one).

Here is a configuration that I think will fix the issue for you.

``` javascript
MathJax = {
  startup: {
    ready() {
      const {AbstractTags, TagInfo} = MathJax._.input.tex.Tags;
      const clearTag = AbstractTags.prototype.clearTag;
      const startEquation = AbstractTags.prototype.startEquation;
      AbstractTags.prototype.clearTag = function () {
        clearTag.call(this);
        this.currentTag = new TagInfo('', undefined, undefined);
      }
      AbstractTags.prototype.startEquation = function (math) {
        this.history = [];
        this.stack = [];
        this.clearTag();
        startEquation.call(this, math);
      }
      MathJax.startup.defaultReady();
    }
  }
}
``` 

I will make a pull request that makes these changes for the next release.

**Comment by kwankyu** [comment]
Thank you for the fix!
