### ISSUE TITLE
Assistive Technology can't be disabled

### ISSUE THREAD

**Issue by plouffed** [mathjax/MathJax#2651]
### Issue Summary

I installed my own copy of the project from npm and I am not able to turn off assistive technology.
Everything works just fine, but it breaks when I try to disable.

Also, I am confuse about the line 
<code>sre.Variables.url="https://cdn.jsdelivr.net/npm/speech-rule-engine@"+sre.Variables.VERSION+"/lib/mathmaps</code> in the file <code>es5/sre/sre_browser.js</code>.

Why it doesn't load from my local copy?

### Steps to Reproduce:

When I add this configuration:

<code>
  MathJax = {
  options: {
    enableEnrichment: false,  // false to disable enrichment
  }
 };
</code><br/>
(as the documentation said <code>http://docs.mathjax.org/en/latest/options/accessibility.html</code>)
<br/><br/>
I get this error:
<br/>
<code>MathJax(?): Invalid option "enableEnrichment" (no default value).</code>
<br><br>
The same thing happen with this configuration:
<code>
  MathJax = {
  options: {
    enableComplexity: false, 
  }
 };
</code><br/>
which give this error:
<code>MathJax(?): Invalid option "enableComplexity" (no default value).</code>

**Comment by dpvc** [comment]
Can you be a little clearer about your setup?  Can you provide the code that sets up and runs MathJax?  Are you running this in node, or in a browser?

Also, there are a number of assistive components, so when you say "turn off assistive technology" is not clear which one you really mean.  Do you mean the assistive MathML that is produced automatically?  To disable that, use

``` javascript
MathJax = {
  options: {
    enableAssistiveMml: false
  }
};
```

It turns out that the `enableEnrichment` option is only available after the semantic-enrich extension is loaded (and similarly for `enableComplexity`), and these aren't loaded until they are requested using the MathJax contextual menu.  That is why you are getting those messages, most likely.  That should be fixed.

As for the location that SRE uses for the maps, that can be configured in the HTML file using an [SRE configuration script](https://github.com/zorkow/speech-rule-engine#configuration), or in a node application using `SRE.setupEngine()`.  But if you are running this in node on a server, you should be using `sre-node.js` rather than `sre_browser.js`, which will use your local `node_modules` copy of SRE and its maps.  That should be selected automatically when you are in a node setting, but I can't tell without more details about your code.

**Comment by plouffed** [comment]
I run MathJax in my browser, and I mostly use google chrome. 

My setup is pretty basic. I installed MathJax using npm command <code>npm install mathjax@3</code>.
Then I included this script
<pre><code>
<script>
  MathJax = {
    options: {
      enableMenu: false,
      //enableComplexity: false,
      //enableEnrichment: false,
    }
  };
</script>
<script type="text/javascript" id="MathJax-script" async src="/node_modules/mathjax/es5/tex-svg-full.js"></script>
</code></pre>

My point on doing all that is to keep just the bare minimum to make it run fast.

When I found that <code>sre_browser.js</code> was loading a file called <code>en.js</code>, I thought that maybe it was the bottleneck. 
So I start searching on the documentation to prevent it from loading and here I am now.

Since I didn't know how to configure sre_browser, I just erase the <code>sre.Variables.url</code>. It doesn't load the <code>en.js</code> file anymore, but it still search for and it didn't make much difference on the speed. I also have to change the ajax call in <code>sre_browser</code> to make it asynchronous. 

I don't know how <code>enableEnrichment</code> and <code>enableComplexity</code> works, but every time I refresh my web page, I see that <code>mml.js</code>, <code>sre_browser.js</code>, <code>en.js</code>, <code>semantic-enrich.js</code> and <code>explorer.js</code> loading.

Do we really need all those to parse mathematical formulas in the browser?

I try the option you proposed (<code>enableAssistiveMml: false</code>) and <code>mml.js</code> is still loading.

**Comment by dpvc** [comment]
Have you activated those assistive tools in the MathJax contextual menu?  If so, that will cause Mathjax to load the assistive tools (the changes in the menu are sticky so will stay in effect).  You can select the "Reset to defaults" in the "Math Settings" submenu to reset all the menu settings (which should turn off those features).  Then reload the page and see if you still see them.  The menu settings override the page settings, so that is probably what is causing them to load.

**Comment by plouffed** [comment]
You got it Mr. Davide P. Cervone!! It works like a charm now.. But I must admit that I couldn't have the contextual menu back by switching <code>enableMenu</code>. I just went in my browser localstorage and deleted the MathJax setting.

So maybe there is a problem there, it doesn't seem to change according to the updated MathJax setup.

**Comment by dpvc** [comment]
> it doesn't seem to change according to the updated MathJax setup.

Depending on how the javascript is packaged, some browsers may not clear it from cache, so you may not have gotten the updated version when you changed the `enableMenu`.  In any case, you seem to have it working now, so I will close the issue.
