### ISSUE TITLE
tex2svg  when meet 𝝅 is transform fail  see the details on the IMG

### ISSUE THREAD

**Issue by OnePsycho** [mathjax/MathJax#2657]
![59941abb9433849b7ef4f8f4258b6ce](https://user-images.githubusercontent.com/43296632/111755398-05ff6500-88d4-11eb-836c-f166f682b89c.png)

**Comment by dpvc** [comment]
The output in your image is correct for the TeX commands that you have entered.  In TeX, a macro name is initiated by a `\` and consists of the longest string of letter (a-z, A-Z) that follows, or by a single non-letter character that follow.  So when you type `\pix` that is the command that TeX receives.  Since that is not defined, MathJax displays it in red to inform you that it is not recognized.  What you should type is `\pi x` if you want *π x*.  The space is no optional, as it is necessary in order to end the `\pi` command.
