### ISSUE TITLE
Can't disable assistive MML

### ISSUE THREAD

**Issue by Rotario** [mathjax/MathJax#2659]
### Issue Summary
Hi,
I'm using Firefox and tex-svg.js to convert tex to base-64 encoded SVGs. Unfortunately the `<mjx-assistive-mml>` tags contain unicode characters, which breaks the base-64 encoding.

I can't seem to disable this assistiveMml? As per [this](http://docs.mathjax.org/en/latest/options/accessibility.html?highlight=assist#assistive-mml-options)
I've tried doing this

window.MathJax.options.assistiveMml = false;
window.MathJax.options.renderActions = {'assistiveMML': []}

but nothing seems to get rid of those `mjx-assistive-mml` tags? I've noticed it works [here](https://mathjax.github.io/MathJax-demos-web/tex-mml.html.html) but can't reproduce?
Any ideas please?

### Steps to Reproduce:
1. Include https://cdn.jsdelivr.net/npm/mathjax@3.1.2/es5/tex-svg.js
2. run `btoa( window.MathJax.tex2svg( "\\phi" ).innerHTML )`
3. See the DOMException
4. run `window.MathJax.options.assistiveMml = false;`
5. run `window.MathJax.options.renderActions = {'assistiveMML': []};`
6. run `btoa( window.MathJax.tex2svg( "\\phi" ).innerHTML )`
7. Still get a DOM exception because the HTML contains the following:

`<mjx-assistive-mml role="presentation" unselectable="on" display="block"><math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mi>ϕ</mi></math></mjx-assistive-mml>`
Where the Phi symbol is unicode so can't be base-64 encoded

### Technical details:

* MathJax Version: 3
*  OS: Ubuntu 20
* Browser:  Firefox

### Supporting information:
Fiddle [here](https://jsfiddle.net/s9Lu473r/)

**Comment by dpvc** [comment]
The `MathJax.options` are used when MathJax sets up its internal objects used for processing the page, and are not used after that.  So setting them when you do will have no affect (as you have seen). They need to be set BEFORE loading the `tex-svg` file.  E.g.

``` html
<script>
MathJax = {
  options: {
    assistiveMml: false,
    renderActions: {
      assistiveMml: []
    }
  }
}
</script>
<script id="MathJax-script" defer src="https://cdn.jsdelivr.net/npm/mathjax@3.1.2/es5/tex-svg.js"></script>
```

This requirement is described in the [documentation](https://docs.mathjax.org/en/latest/web/configuration.html#configuration-using-an-in-line-script).

Of course, you could use an approach other than `innerHTML`, for example, 

``` javascript
btoa( window.MathJax.tex2svg( "\\phi" ).querySelector('svg').outerHTML )
```

to get only the SVG element, and ignoring the other content of the `<mjx-container>`.

Finally, if you are just trying to produce SVGs from TeX expressions, you may find it easier to do this using a command-line script rather than in the browser itself.  See, for example, the various `tex2svg` programs in [MathJax node demos](https://github.com/mathjax/MathJax-demos-node) repository.  You can use these as starting points for your own versions that do the `btoa` conversion and save the results to files for you.

**Comment by Rotario** [comment]
Ah brill - thanks!
Apologies for not spotting that! I was obviously skim reading a little too quickly.
I'll try this now.
Appreciate your help.
R
