### ISSUE TITLE
Middle delimiter do not recognize in some cases

### ISSUE THREAD

**Issue by den-low** [mathjax/MathJax#2663]
### Issue Summary

The middle delimiter do not recognize inside \left \right tex expression in some cases.

### Steps to Reproduce:

Enter tex expression in MathJax demo: `\left( \color{red}  a \middle| \color{yellow} b  \right)`
and get an error message: \middle must be within \left and \right
a correct math expression is expected

### Technical details:

* MathJax Version: 3.1.2
* Client OS: Windows 7
* Browser: Version 89.0.4389.90 (64-bit)

**Comment by dpvc** [comment]
Thanks for the report.  The implementation is not sophisticated enough, it seems.  I will look into it further.

A workaround for now would be to do use

``` latex
\left( {\color{red} a} \middle| {\color{yellow} b} \right)
```

where the color is in braces so that the color command ends before the `\middle` is processed.  (It is the presence of the color-change item in the internal parser stack that is confusing the current implementation of `\middle`.  Ending the color before `\middle` eliminates that.)
