### ISSUE TITLE
Question : local installation

### ISSUE THREAD

**Issue by deb75** [mathjax/MathJax#2680]
Hello,

I am interested in using `mathjax` in combination with `reveal.js`.

Can I run `mathjax` locally ? that is to say without any web server, just a browser ?

I ask this because on reading the doc, it seemed like a web server was required and,
I have neither admin rights to install a web server (though could be possible if the port is > 1024)
and no access to internet (except from a dedicated browser)

Regards

**Comment by dpvc** [comment]
> Can I run mathjax locally ?

Sure.  Get a copy of MathJax (see the [instructions](https://docs.mathjax.org/en/latest/web/hosting.html)) and use a `file://` URL for it.  Note that some browsers are pretty strict about their interpretation of the same-origin security policy for `file://` URLs, so you may need to have MathJax be in the same directory as (or a subdirectory of) the one containing the HTML file.  For example, this could prevent loading extensions or the MathJax fonts, so if you see errors in the browser console window, that may be the issue.  

If that is the case, try using one of the components whose name ends in `-full` so that you don't need to load extra files, and use SVG output rather than CHTML, as that doesn't require fonts to be loaded.  The alternative is to run a local web server just for yourself.  It doesn't have to be fancy; for example Python's web server (`python -m http.server 8080`) would do it.

**Comment by deb75** [comment]
Hi

Thanks for your answer.

In short, whether I use the files locally with another browser than firefox (e.g. chrome) or I settle a 
simple web server as you mentioned. In that later case, where should I locate the files ? so that they be available
to the server.

Regards

**Comment by dpvc** [comment]
> In short, whether I use the files locally with another browser than firefox (e.g. chrome) or I settle a
> simple web server as you mentioned. In that later case, where should I locate the files ? so that they be available
> to the server.
> 

That depends on what server you are using, and how it is configured.  If you use the Python server, it will serve whatever is in the directory were you start it.  So you could put the MathJax directory there, and a directory of your HTML files next to it, and use <script src="/mathjax/es5/tex-chtml.js"> to load MathJax from your HTML files.  For other servers, you will have to read the documentation to tell where they will expect the files to live.

Davide
