### ISSUE TITLE
How to optimize server-side conversion?

### ISSUE THREAD

**Issue by coryschires** [mathjax/MathJax#2692]
## Background
I am using MathJax 3.6.4 to convert LaTex to various outputs on my server (via Node).

My current setup goes:

1. Given a document that includes equations as LaTex (mixture of both inline and block)
2. Gather all LaTeX equations from the document
3. Use Mathjax to convert each equation to MML (or whatever format)
4. Sweep back through the document replacing each LaTex equation with the converted MML

## Problem
This works well except that it becomes very slow if the document includes lots of equations (e.g. 50+). Specifically, step 3 – Use Mathjax to convert each equation – is slow.

## Question
How do you recommend I optimize this process? 

## Some ideas I've considered

* Is there a way to have Mathjax typeset the entire document in a single call rather than doing each equation serially? For example, I know it's possible to typeset an entire HTML doc very quickly. Is there a node / server-side equivalent of this?
* Is there a way to send MathJax all the equations in a single batch? This way, I could make one call to Mathjax for the entire doc rather than making a separate call for each equation.

Seems like others would have encountered this problem, and that I am probably missing something obvious.

By the way, version 3 such a huge improvement. Thanks for all the hard work!

**Comment by dpvc** [comment]
There are many ways you could have implemented step three, so without knowing more about the details of what you have done, it is difficult to offer optimizations.  For example, it you are forking a subprocess to run one fo the command-line tools for converting a single expression, then yes, that would be incredibly slow.

> I know it's possible to typeset an entire HTML doc very quickly. Is there a node / server-side equivalent of this?

Certainly.  See the examples ending in `-page` in the [MathJax node examples repository](https://github.com/mathjax/MathJax-demos-node).  There are several approaches to calling MathJax from node, and each has its own directory in the repository.  Most of those include `-page` examples.

> Is there a way to send MathJax all the equations in a single batch? 

Yes, you could do it via one the `-page` tools by putting the expressions into an HTML page that consisted only of the LaTeX commands and process them all as one document.  Or you could modify the single-expression tools to read expressions from stdin and pass them to MathJax one by one, printing the output to stdout.  You could make a "service" that does this, and communicate via pipes or unix sockets so that you only have to start up MathJax once.

If you look at the examples in the [direct](https://github.com/mathjax/MathJax-demos-node/tree/master/direct) subdirectory, they show how to import the MathJax modules directly into a node application, so that you could call MathJax functions however you want.

**Comment by coryschires** [comment]
Thanks @dpvc! This is very helpful.

I'll take another look at my code with this advice in mind. Depending on what I find, I will be sure to follow up on this thread with any info that may be helpful for other users.

Thanks again!
