### ISSUE TITLE
Issues with mathvariant=script, bold-script, and double-struck for some users

### ISSUE THREAD

**Issue by jmitsdarfer** [mathjax/MathJax#2713]
### Issue Summary
We are seeing inconsistent output between users for mathvariant="script", "bold-script", and "double-struck". For some (including me), they all look good and as expected. For others, they have various problems for script lowercase, bold-script lowercase and uppercase, and double-struck lowercase. Please see attached for more details. Is this all just related to each individual's installed fonts on their own computer? One user was able to fix the issue by installing a bunch of STIX fonts to their computer. Is this all that can be done (installing fonts on a per person basis)? This seems like it could be a cumbersome solution for our entire readership depending on how widespread this issue may be, but maybe that's all that can be done. Should we consider defining different fonts to be used for script, bold-script, and double-struck? Is there anything else we are missing here?
[Script, bold-script, double-struck.docx](https://github.com/mathjax/MathJax/files/6677519/Script.bold-script.double-struck.docx)

### Technical details:

The users seeing the issues were using the following:
User 1: We are using Windows 10. This was reproducible across Chrome 89, FireFox 87.0, Edge 42.17.
User 2: My FF version is 86.0.1 and Chrome is 89.0.4.

The users seeing the correct output were using the following:
User 3 (me):
MathJax Version: master - latest commit: MathJax.js v2.7.5
Client OS: Windows
Browser: Chrome Version 91.0.4472.114 (Official Build) (64-bit) and Firefox 78.11.0esr (64-bit)

User 4:
Chrome 90.0.4430.212 and Firefox 78.10.1esr

### Supporting information:

Note the users seeing incorrect output through our website were able to see the correct output for these examples:

https://www.sciencedirect.com/science/article/pii/S0001870821002127

https://iopscience.iop.org/article/10.1088/2515-7639/ab4092/meta

**Comment by dpvc** [comment]
>  Is this all just related to each individual's installed fonts on their own computer?

Yes.  You don't say which renderer you are using, but I suspect it is the HTML-CSS renderer, and that renderer tries to determine if you have either the MathJax fonts or the STIX fonts installed on your system, and selects which font to use based on that.  Mac's have the STIX fonts installed by default, and so Mac users would see the STIX fonts, while most other users (unless they installed the STIX fonts themselves) would get the default MathJax went fonts.  The STIX fonts have much greater coverage of math symbols, and so there will be differences in the results for people with and without the STIX fonts.  The variant forms that you are seeing are typical of the difference.  The STIX fonts include lower-case double struck characters, for example, while the MathJax fonts don't (except for the "k").  Similarly, STIX has lower-case script character while the MathJax fonts don't.  And because these are two different fonts, the upper-case script and double-struck characters are identical between the two.  That is likely the source of the differences you are seeing.

In version 2, which you are using, MathJax will substitute other variants if it doesn't have glyphs in the given one (MathJax version 3 works differently, and simply makes a unicode reference for the proper Math Alphanumerics character in hopes that a system font will contain a suitable glyph).  So for lower-case double-struck characters, it substitutes bold characters (since the double-struck form is "blackboard bold", which is what professors wrote on the blackboard to indicate letters that would have been bold in print).

You can configure MathJax *not* to look for local MathJax and STIX fonts, and instead always use web-based fonts.  That would mean that you always had the same results for all users, and could choose if it is the MathJax or the STIX version that they see.  You could force the STIX fonts if you need the lower-case script characters, for example, by using

``` html
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  "HTML-CSS": {
    fonts: ["STIX"]
  }
});
</script>
```

just *before*  the script tag that loads MathJax itself.

**Comment by jmitsdarfer** [comment]
Yes, the renderer is HTML-CSS. Thank you so much for the very helpful explanation!
