### ISSUE TITLE
3.2.0 Invalid WOFF fonts

### ISSUE THREAD

**Issue by sanmai-NL** [mathjax/MathJax#2714]
### Issue summary

My page with MathJax doesn’t render the fonts anymore.

Uploading e.g. `MathJax_Zero.v3.2.0.woff` to http://validator.fontbureau.com/ highlights a lot of errors:

![Preview of WOFF Validator errors](https://user-images.githubusercontent.com/3374183/122578942-a9d3ea80-d054-11eb-8f8d-e20add9d8048.png)

### Steps to reproduce

1. Upload`MathJax_Zero.v3.2.0.woff` to http://validator.fontbureau.com/.

I didn’t have the font issue with the previous major version.

### Technical details

* MathJax Version: 3.2.0
* Client OS: macOS 11.4
* Browser: Brave Version 1.25.73 Chromium: 91.0.4472.106 (Official Build) (x86_64)
* Used with Snowpack 3.5.9

### Supporting information:

![image](https://user-images.githubusercontent.com/3374183/122580015-cf152880-d055-11eb-81b2-98aa44617ae1.png)

**Comment by dpvc** [comment]
I am not able to reproduce the issue.  Here is the output for MathJax_Zero.woff for me:

<img width="1192" alt="mj-zero" src="https://user-images.githubusercontent.com/432782/122589946-dffe7380-d02e-11eb-8961-35e90299566c.png">

I checked this with both the original files, and with the version obtained from `npm install mathjax-full`.

The font files have not been changed since the previous version.  Can you checkout v3.1.4 and do a local diff on the 3.1.4 version and the 3.2.0 version and see if they differ for you?  When I do this, there is no reported difference.

I'm wondering if you have gotten a corrupted installation somehow.

**Comment by sanmai-NL** [comment]
I only see this corruption with the Snowpack dev server, not with a Snowpack production build.
