### ISSUE TITLE
Latex stacking issues

### ISSUE THREAD

**Issue by ess3sq** [mathjax/MathJax#2733]
### Issue Summary

Hello,

I have been sent here by the maintainers of the Pluto project ([original issue](https://github.com/fonsp/Pluto.jl/issues/1273)).
Basically, I wanted to ask if the fact that "stacking" commands without braces `{}` is disallowed by design.

Example:
- `\dot{\vec{a}}` this works exactly as intended
- `\dot \vec a` this does not.

Someone claimed this is because omitting the braces is not valid LaTeX, but my pdflatex installation works just fine when fed the shortened version. As such, I would liket o ask if this is a bug or whether such abbreviations are considered illegal syntax.

PS. What I find baffling is the MathJax error message; `Missing argument for \vec`, as if `\vec` is somehow cosidered the argument of `\dot` and `a` is eaten up for some reason...

### Steps to Reproduce:

1. Type `\(\dot \vec a\)` in the MathJax [demo](https://www.mathjax.org/#demo) 

I initially tried this in a [Pluto](https://juliapackages.com/p/pluto) notebook and the same issue appeared.

### Technical details:

I am not sure how to find these details. Consider them to be whatever the MathJax demo is running on (latest version I guess?)

**Comment by dpvc** [comment]
While MathJax does try to mimic LaTeX as closely as possible, not every feature of LaTeX is practical to copy, and we have not always implemented the edge case behavior, especially when that behavior differs depending on the packages and document class that is used.  The issue you describe is one of those situations.  The Pluto issue you link to indicates that when the document class is `article`, the `\dot \vec a` construction produces an error; with the `amsart` class (on which MathJax is based), the construction is allowed, but doesn't produce the expected result.  So the "correct" handling of this expression is not entirely clear.  How an expression of the form `\a \b c` is processed depends significantly on how `\a` and `\b` are defined, and has to do with low-level details of how TeX processes macros and native control sequences interact, and there is little consistency about it from a high-level standpoint (that is, the same construction may work in very different ways depending on how `\a` and `\b` are defined).  There is no way to tell from `\a \b c` whether it will be processed as `\a{\b c}` or `{\a{\b}} c` and some macros work one way and others another (and it is possible that is is actually neither one of these).

MathJax does not implement TeX's low-level processing, but instead has its own processing model that is a little more consistent than TeX.  In MathJax, if `\a` expects one argument, then that argument is whatever item immediately follows it, so `\a \b \c` is `\a{\b} c`, not `\a{\b c}` as it can be in actual TeX, if `\a` and `\b` have the right definitions.  So in your case, `\dot \vec a` is `\dot{\vec} a`, and since in this setting, the `\vec` does not have a following argument, that is the source of the message that you receive.

Similarly, `\mathbf \vec a` will give such a message, as will many other similar constructs, even if (in some document classes) they work in actual LaTeX.  The ambiguity in `\a \b c` makes it bad practice to use this format to mean `\a{\b c}`, and `\a{\b c}` is to be preferred.  In MathJax is is actually required.

So while this is a situation where MathJax differs from LaTeX, it is not something that we are planning to change in MathJax.

**Comment by ess3sq** [comment]
@dpvc I see, thanks a lot for the in-depth insights and reasoning, that certainly makes sense. I suppose it's not too hard to  avoid the short-hands when involving MathJax. While they are pleasant to use, I suppose they are hardly worth the effort of changing the parsing mechanism.
