### ISSUE TITLE
linebreak=”goodbreak” not honored as expected

### ISSUE THREAD

**Issue by jmitsdarfer** [mathjax/MathJax#2742]
### Issue Summary

I have noticed that linebreak=”goodbreak” doesn’t seem to act the same in MathJax as it does for us in our PDFs. I’ll just include one example, though I’ve seen this a lot. A break was needed for this equation, but it didn’t break on the more preferred “goodbreak space”. It broke a little after at an <m:mspace width=".25em"/>. We use any of these for what we call "goodbreak spaces":

`<mo linebreak="goodbreak" lspace="0em" rspace="1em">&#x2063;</mo>, <mo linebreak="goodbreak" lspace="0em" rspace="2em">&#x2063;</mo>, <mo linebreak="goodbreak" lspace="0em" rspace="3em">&#x2063;</mo>`

Our PDF composition engine sees these goodbreak spaces as very desirable breaking points if a break is needed in an equation. Is there a way for us to make MathJax honor this attribute in that same way as well? I searched around a little and saw https://github.com/mathjax/MathJax/issues/104. I believe we do already have the mentioned configuration option in place in our setup, i.e.,

`"HTML-CSS": {  
     preferredFont: "STIX", 
     linebreaks: { automatic: true }, 
},
`
XML for the example:

`<math xmlns="http://www.w3.org/1998/Math/MathML" display="block" indentalign="left" indentshift="1.0em" indentshiftfirst="0em" linebreak="auto">
  <msup>
    <mrow>
      <mi>d</mi>
    </mrow>
    <mrow>
      <mi>f</mi>
    </mrow>
  </msup>
  <mi mathvariant="bold">X</mi>
  <mo>=</mo>
  <munderover>
    <mrow>
      <mo linebreak="nobreak">&#x220F;</mo>
    </mrow>
    <mrow>
      <mi>&#x3BC;</mi>
      <mo>=</mo>
      <mn>1</mn>
    </mrow>
    <mrow>
      <msub>
        <mrow>
          <mi>N</mi>
        </mrow>
        <mrow>
          <mi>f</mi>
        </mrow>
      </msub>
    </mrow>
  </munderover>
  <msup>
    <mrow>
      <mi>d</mi>
    </mrow>
    <mrow>
      <msub>
        <mrow>
          <mi>f</mi>
        </mrow>
        <mrow>
          <mi>&#x3BC;</mi>
        </mrow>
      </msub>
    </mrow>
  </msup>
  <msub>
    <mrow>
      <mi mathvariant="bold">X</mi>
    </mrow>
    <mrow>
      <mi>&#x3BC;</mi>
    </mrow>
  </msub>
  <mo>&#x2234;</mo>
  <mi mathvariant="bold">X</mi>
  <mo>=</mo>
  <mi mathvariant="bold-script">R</mi>
  <mo>,</mo>
  <mi mathvariant="script">P</mi>
  <mo>,</mo>
  <mi mathvariant="bold">J</mi>
  <mo>,</mo>
  <mi mathvariant="bold">Q</mi>
  <mo>,</mo>
  <mi mathvariant="bold">P</mi>
  <mo>,</mo>
  <mo linebreak="goodbreak" lspace="0em" rspace="3em">&#x2063;</mo>
  <msup>
    <mrow>
      <mi>d</mi>
    </mrow>
    <mrow>
      <msub>
        <mrow>
          <mi>f</mi>
        </mrow>
        <mrow>
          <mi>r</mi>
        </mrow>
      </msub>
    </mrow>
  </msup>
  <mi mathvariant="bold-italic">&#x3B8;</mi>
  <mo>=</mo>
  <munderover>
    <mrow>
      <mo linebreak="nobreak">&#x220F;</mo>
    </mrow>
    <mrow>
      <mi>&#x3BC;</mi>
      <mo>=</mo>
      <mn>1</mn>
    </mrow>
    <mrow>
      <msub>
        <mrow>
          <mi>N</mi>
        </mrow>
        <mrow>
          <mi>f</mi>
        </mrow>
      </msub>
    </mrow>
  </munderover>
  <mfrac>
    <mrow>
      <mn>1</mn>
    </mrow>
    <mrow>
      <msub>
        <mrow>
          <mi>&#x3C3;</mi>
        </mrow>
        <mrow>
          <mi>&#x3BC;</mi>
        </mrow>
      </msub>
    </mrow>
  </mfrac>
  <mspace width=".25em" />
  <mi>sin</mi>
  <mo linebreak="nobreak" lspace="0em" rspace=".25em">&#x2061;</mo>
  <msub>
    <mrow>
      <mi>&#x3B2;</mi>
    </mrow>
    <mrow>
      <mi>&#x3BC;</mi>
    </mrow>
  </msub>
  <msup>
    <mrow>
      <mi>d</mi>
    </mrow>
    <mrow>
      <msub>
        <mrow>
          <mi>f</mi>
        </mrow>
        <mrow>
          <mi>r</mi>
          <mi>&#x3BC;</mi>
        </mrow>
      </msub>
    </mrow>
  </msup>
  <msub>
    <mrow>
      <mi mathvariant="bold-italic">&#x3B8;</mi>
    </mrow>
    <mrow>
      <mi>&#x3BC;</mi>
    </mrow>
  </msub>
</math>`

MathJax output:
![image](https://user-images.githubusercontent.com/82107944/126582120-3a96f12b-3a03-4028-9216-342ce9d639a7.png)

Expected output:
![image](https://user-images.githubusercontent.com/82107944/126582144-17e03c8c-08d5-43d6-88e1-ae203efea196.png)

### Technical details:

MathJax Version: master - latest commit: MathJax.js v2.7.5
Client OS: Windows
Browser: Chrome Version 91.0.4472.114 (Official Build) (64-bit)
Renderer: HTML-CSS

**Comment by dpvc** [comment]
The MathML specification does not prescribe a specific line breaking algorithm, and so MathML renderers each provide their own approach to that.  In particular, that means that different renderers will produce different results, as there is no standard for how that should work.

In MathJax, when an expression exceeds the width of its container, MathJax assigns to potential breakpoints a "penalty" based on a number of factors.  These include things like the distance of the breakpoint from the edge of the container and the nesting level of the element within the MathML expression.  The breakpoint with the lowest penalty is used.  If the remaining expression is still wider than the container, the process is repeated until the last line is small enough, or no further breakpoints are found.

In your case, because the space with he `linebreak="goodbreak"` is so far from the right-hand edge of the container, the penalty for that counteracts the lowering of the penalty due to the goodbreak, and a breakpoint nearer the right-hand side is chosen.

Since nesting level increases the penalty, one way of discouraging line breaks is to put one or more `mrow` elements around the content where you want to discourage breaks.  In your example, an `mrow` around the summation symbol and its summand would do the trick.

Alternatively, it is possible to adjust the penalty values for the various factors controlling the breakpoints.  These penalties are  stored in an array that can be modified, so you can "tune" the parameters to fit your needs better.  For example, you could increase the size of the (negative) penalty that is used by `linebreak="goodbreak"` so that it decreases the penalty at that point by a larger amount, making it more attractive to MathJax.  Here is a configuration that sets that to -400 (double the usual -200) for HTML-CSS output.  That also produces the result you are looking for in this case.

``` html
<script type="text/x-mathjax-config">
  MathJax.Hub.Register.StartupHook("HTML-CSS multiline Ready", function () {
    var PENALTY = MathJax.ElementJax.mml.mbase.prototype.HTMLlinebreakPenalty;
    PENALTY.goodbreak = [-400];
  });
</script>
```

You can do something similar for all three output formats (here I use a loop to handle all three):

``` html
<script type="text/x-mathjax-config">
(function () {
  var NAMES = [['HTML-CSS', 'HTML'], ['SVG', 'SVG'], ['CommonHTML', 'CHTML']];
  for (var i in NAMES) {
    let names = NAMES[i];
    MathJax.Hub.Register.StartupHook(names[0] + " multiline Ready", function () {
      var PENALTY = MathJax.ElementJax.mml.mbase.prototype[names[1] + 'linebreakPenalty'];
      PENALTY.goodbreak = [-400];
    });
  }
})();
</script>
```

You can also combine the two approaches, so that if your new penalty value doesn't work for some specific situation, you can still use `mrow` nesting to tweak the results.

**Comment by jmitsdarfer** [comment]
Thank you again very much. This was so helpful!
