### ISSUE TITLE
Possible code conflict?

### ISSUE THREAD

**Issue by JGFrog99** [mathjax/MathJax#2759]
Using tex-svg.js and tex-mml-chtml.js on the same page it seems to cause a conflict and this error appears

"Uncaught TypeError: MathJax.tex2svgPromise is not a function"

**Comment by dpvc** [comment]
The combined components, like `tex-mml-chtml.js` and `tex-svg.js` are not designed to be used in combination, since they both include copies of the startup code that does things like setup the `tex2svgPromise()` routines, and one will wipe out the work of the other.

You can, however load one of them and configure it to load the pieces you need from the other.  For example

``` html
<script>
MathJax = {
  loader: {load: ['output/svg']}
};
</script>
<script id="MathJax-script" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
```

would let you have both SVG- and CHTML-based typeset functions.
