### ISSUE TITLE
Display of fraction for root index is poor

### ISSUE THREAD

**Issue by NSoiffer** [mathjax/MathJax#2764]
### Issue Summary

The positioning of a fraction when used as the index to `\sqrt` is pretty bad

### Steps to Reproduce:

TeX Input: \sqrt[\frac{1}{2}]{1}

Display:
Normal zoom: 
![image](https://user-images.githubusercontent.com/1545836/132082027-0a9c4a63-c4ea-4661-b9d9-b85b1e95d682.png)

200%: 
![image](https://user-images.githubusercontent.com/1545836/132082050-35747cf0-79af-4d7e-b693-0d47543a9f5e.png)

Other zoom levels also result in poor rendering.

This is likely a result of TeX's rules for positioning the index being suboptimal. I suspect some additions to those rules are needed to avoid having the index crash into the radical.

### Technical details:

I viewed this on https://mathjax.github.io/MathJax-demos-web/speech-generator/convert-with-speech.html
Windows machine
The images are from Chrome; theylook similar on Firefox.

**Comment by dpvc** [comment]
It turns out that this is actually due to incorrectly positioning the surd and bar rather than the position of the 1/2 itself.  (Notice that the bottom of the surd isn't low enough.)  The CHTML output was correct:

<img width="69" alt="root" src="https://user-images.githubusercontent.com/432782/133513792-b1a61a7f-4f23-4dfe-ace9-5aec67ec423f.png">

though the position of the fraction isn't great due to the spacing around the fraction from it having TeX class INNER.

I have created a pull request to resolve the issue for the next release.
