### ISSUE TITLE
Sub- and superscript positioning

### ISSUE THREAD

**Issue by jmitsdarfer** [mathjax/MathJax#2777]
### Issue Summary
Is there a reason that a subscript appears lower when it's part of an msubsup than if it's in a plain msub or staggered msub and msup? (Also, a superscript appears slightly lower when it's part of an msubsup that if it's in a plain msup or staggerered msub and msup, though this is less obvious.) Is it something related to in case there happens to be further sub-sups or sup-subs?

XML:
`<msub>
    <mi>H</mi>
    <mn>1</mn>
  </msub>
  <msup>
    <msub>
      <mi>H</mi>
      <mn>1</mn>
    </msub>
    <mi mathvariant="normal">H</mi>
  </msup>
  <msubsup>
    <mi>H</mi>
    <mn>1</mn>
    <mi mathvariant="normal">H</mi>
  </msubsup>
  <msup>
    <mi>H</mi>
    <mi mathvariant="normal">H</mi>
  </msup>`

and

`<msub>
    <mi>H</mi>
    <mn>1</mn>
  </msub>
  <msup>
    <msub>
      <mi>H</mi>
      <mn>1</mn>
    </msub>
    <mn>2</mn>
  </msup>
  <msubsup>
    <mi>H</mi>
    <mn>1</mn>
    <mn>2</mn>
  </msubsup>
  <msup>
    <mi>H</mi>
    <mn>2</mn>
  </msup>`

and

`<msup>
    <msub>
      <mi>H</mi>
      <mn>1</mn>
    </msub>
    <mi mathvariant="normal">H</mi>
  </msup>
  <msubsup>
    <mi>H</mi>
    <mn>1</mn>
    <mi mathvariant="normal">H</mi>
  </msubsup>
  <msup>
    <msub>
      <mi>H</mi>
      <mn>1</mn>
    </msub>
    <msub>
      <mi mathvariant="normal">H</mi>
      <mi mathvariant="normal">j</mi>
    </msub>
  </msup>
  <msubsup>
    <mi>H</mi>
    <mn>1</mn>
    <msub>
      <mi mathvariant="normal">H</mi>
      <mi mathvariant="normal">j</mi>
    </msub>
  </msubsup>
  <msup>
    <msub>
      <mi>H</mi>
      <msup>
        <mn>1</mn>
        <mi mathvariant="normal">H</mi>
      </msup>
    </msub>
    <msub>
      <mi mathvariant="normal">H</mi>
      <mi mathvariant="normal">j</mi>
    </msub>
  </msup>
  <msubsup>
    <mi>H</mi>
    <msup>
      <mn>1</mn>
      <mi mathvariant="normal">H</mi>
    </msup>
    <msub>
      <mi mathvariant="normal">H</mi>
      <mi mathvariant="normal">j</mi>
    </msub>
  </msubsup>`

MathJax output w/ notes:

<img width="394" alt="MathJax sub and sup positioning" src=https://user-images.githubusercontent.com/82107944/135455906-5bb3a93c-0696-4027-8196-3e059bc9b52f.png>

MathJax output:

![image](https://user-images.githubusercontent.com/82107944/135473748-af5d7807-65eb-4c06-9ed6-dd9a53bd7c89.png)

Our PDF output:

![PDF output](https://user-images.githubusercontent.com/82107944/135456250-9e32e50f-6824-4b06-abd2-328c5a4e7661.jpg)

![image](https://user-images.githubusercontent.com/82107944/135473641-b36c1601-09f0-4f04-8df6-0937f08ec451.png)

### Technical details:
MathJax Version: master - latest commit: MathJax.js v2.7.9
Client OS: Windows
Browser: Version 94.0.4606.61 (Official Build) (64-bit)
Renderer: HTML-CSS

**Comment by dpvc** [comment]
MathJax's output rendering is based on the TeX layout engine as described in Appendix G of the TeXbook.  The TeX rules governing superscripts and subscripts are designed to disrupt the interline spacing as little as possible, so when there is only a subscript, for example, the subscript is placed so the standard baseline spacing doesn't change, and the look of a paragraph containing subscripted variables is consistent.  When there is both a superscript and a subscript, however, the vertical position of the subscript may be lowered to avoid the super- and subscript from bumping into each other.  While that would not be the case for your superscript H, it would be if the superscript had a descender, like a j or g.  That is why you are seeing a lowered subscript in your third example compared to the first two.

For the superscripts in the second through fourth, TeX uses different rules depending on whether the base is a single character, or a more complicated expression.  I'm working from memory, here, but when the base is a single character, TeX bases the height on the ex-height of the font in use; that means that the height of a superscript will be the same for a base that is an <i>x</i>, or a <i>k</i>, or an <i>X</i>, regardless of the height of the character.   But when the base is a more complicated expression, the position is based on the height of the expression above the baseline.  This is so that if the expression is very tall for example (say a matrix that extends several rows above the baseline), superscripts will be placed near the top of the expression, not where they would have been placed for a single letter.

In your situation, when you use `msup` around an `msub`, that means the base of the `msup` is not a single character, but a more complicated expression (an `msub` in this case), and so the height of the superscript is based on the height of the base, and that turns out to put it a bit higher than usual position.  Here is actual TeX output for your first four expressions:

<img width="488" alt="TeX" src="https://user-images.githubusercontent.com/432782/136630247-a8ad6b55-6d38-4f71-a197-d161518b45ca.png">
Note that the second superscript is a but higher than the others.  But here the third and fourth are the same, and that is what is supposed to happen, but the positioning on screen is very delicate, and the layout needed for the superscript-subscript stack is different from just the superscript, and rounding errors in placing the characters onto actual pixels does mean the two aren't exactly the same.  Also, the font metrics for the characters in the STIX font aren't identical to the ones for TeX's Computer Modern font, and so that affects things as well.

In any case, the output is largely as it is meant to be in MathJax, and the short answer is that it's that way because that's how it is in TeX.

If you want offset superscripts and subscripts, like in your second example, but want them to match the vertical positioning of the third one, then you might consider using `mmultiscripts` rather than nested `msup` and `msub`.  E.g., 

``` xml
  <math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
    <msub>
      <mi>H</mi>
      <mn>1</mn>
    </msub>
    <mmultiscripts>
      <mi>H</mi>
      <mn>1</mn><none></none>
      <none></none><mi mathvariant="normal">H</mi>
    </mmultiscripts>
    <msubsup>
      <mi>H</mi>
      <mn>1</mn>
      <mi mathvariant="normal">H</mi>
    </msubsup>
    <msup>
      <mi>H</mi>
      <mi mathvariant="normal">H</mi>
    </msup>
  </math>
```

which gives

<img width="460" alt="mmultiscripts" src="https://user-images.githubusercontent.com/432782/136631207-76abd909-6901-4a05-a04e-94b58a1da195.png">
