### ISSUE TITLE
Prime symbol is no longer in subscript after upgrading to 3.1.4+

### ISSUE THREAD

**Issue by lp-contentplus** [mathjax/MathJax#2781]
Prime symbol is no longer in subscript after upgrading to 3.1.4+

Symbol is located properly when using MathJax 3.1.2

    <math display="block"><mi>P</mi><mfenced separators="|"><mrow><mi>A</mi><mo>'</mo></mrow></mfenced><mo>=</mo><mn>1</mn><mo>-</mo><mi>P</mi><mfenced><mi>A</mi></mfenced></math>

MathJax 3.1.2:
![3 1 2](https://user-images.githubusercontent.com/40391318/136177632-d7779c96-18d8-4b95-bbc3-3f44170d5844.png)

MathJax 3.1.4 (also 3.2):
![3 1 4](https://user-images.githubusercontent.com/40391318/136177664-8a17a261-ec51-4260-a972-0506e3ac8524.png)

**Comment by dpvc** [comment]
The [MathML specification](https://www.w3.org/TR/MathML3/chapter7.html#chars.pseudo-scripts) indicates that

> the preferred encoding of "x prime" is
> 
>     <msup><mi>x</mi><mo>&#x2032;</mo></msup>
> 
> and not
> 
>     <mi>x'</mi>
> 
> or any other variants not using an explicit script construct.
> 
> ...
> 
> However, the data model for all MathML token elements is Unicode text, so one cannot rule out the possibility of valid MathML markup containing constructions such as
> 
>     <mrow><mi>x'</mi></mrow>
> 
> and
> 
>     <mrow><mi>x</mi><mo>'</mo></mrow>
> 
> While the first form may, in some rare situations, legitimately be used to distinguish a multi-character identifer named `x'` from the derivative of a function <i>x</i>, such forms should generally be avoided.

It goes on to list a number of pseudo-scripts, and includes U+0027 (apostrophe) as one of them.

In v3.1.3, MathJax expanded its handling of pseudo-scripts to make it possible to render them properly when proper characters are available in the fonts being used, in anticipation of the upcoming release of MathJax that will include a wider range of fonts with more character coverage.  As part of this new handling of pseudo-scripts, some pseudo-script characters are translated to the mathematical characters that they are usually meant to represent.  Since the apostrophe usually is intended to be a mathematical prime, it is translated to U+2032.

Because the recommended encoding for "A-prime" is

``` xml
<msup><mi>A</mi><mo>'</mo></msup>
```

and since superscript characters are rendered in a smaller font and raised, the prime character in the MathJax fonts is larger and upraised so that when it is put into a superscript, it will be shown properly.  That means that when used <i>not</i> in a superscript, it is too large and too low, as you are seeing.  That is the main problem with pseudo-scripts, as they need to be rendered differently in different situations, and so fonts need to include two versions of them.  The default MathJax font only has one.  (This issue will be resolved in the upcoming font release.)

What you were getting in v3.1.2 is not actually a prime, but an apostrophe, which probably isn't really what is intended.  But if you want that behavior back, you can use

``` javascript
MathJax = {
  startup: {
    pageReady() {
      const MmlMo = MathJax._.core.MmlTree.MmlNodes.mo.MmlMo;
      MmlMo.remapPrimes[0x27] = 0x27;
      return MathJax.startup.defaultPageReady();
    }
  }
};
```

which disables the translation of U+0027 to U+2032.  Note that this means that if you do what the MathML spec recommends,

``` xml
<msup><mi>A</mi><mo>'</mo></msup>
```

then the apostrophe will be too small and too high.  If you use both forms, you would use

``` xml
MathJax = {
  startup: {
    pageReady() {
      const FONT = MathJax.startup.document.outputJax.font;
      const [ph, pd, pw, pdata] = FONT.getChar('normal', 0x2032);
      const [qh, qd, qw, qdata] = FONT.getChar('normal', 0x27);
      FONT.defineChars('-tex-variant', {0x2032: [ph, pd, pw, {f:''}]});
      FONT.defineChars('normal', {0x2032: [qh, qd, qw, Object.assign({}, qdata, {c: "'"})]});
      const TextNode = MathJax._.output.chtml.Wrappers.TextNode.CHTMLTextNode
      TextNode.styles['mjx-mo.mjx-var mjx-c.mjx-c2032::before'] = {content: "'\u2032'"};
      return MathJax.startup.defaultPageReady();
    }
  }
};
```

instead, assuming that you are using CommonHTML output (if you are using SVG these needs some adjustment).  In this case, 

``` xml
<math display="block">
  <msup><mi>A</mi><mo>'</mo></msup>
  <mi>A</mi><mo>'</mo>
</math>
```

renders as

<img width="150" alt="prime" src="https://user-images.githubusercontent.com/432782/136672936-761c2594-d8d2-43aa-8d9f-78dd49e52a46.png">

It is also possible to add a little CSS to scale and adjust the large prime instead,

``` javascript
MathJax = {
  startup: {
    pageReady() {
      const FONT = MathJax.startup.document.outputJax.font;
      const [h, d, w, data] = FONT.getChar('normal', 0x2032);
      FONT.defineChars('-tex-variant', {0x2032: [h, d, w, {f:''}]});
      const TextNode = MathJax._.output.chtml.Wrappers.TextNode.CHTMLTextNode
      TextNode.styles['mjx-mo.mjx-var mjx-c.mjx-c2032::before'] = {content: "'\u2032'"};
      TextNode.styles['mjx-mo.mjx-n mjx-c.mjx-c2032::before'] = {'font-size': '70.7%'};
      TextNode.styles['mjx-mo.mjx-n mjx-c.mjx-c2032'] = {'vertical-align':'.4em'};
      return MathJax.startup.defaultPageReady();
    }
  }
};
```

but MathJax with think this character is its original size and position when computing bounding boxes for expressions, so it is not ideal.

**Comment by lp-contentplus** [comment]
Thank you for such an exhaustive response :)

Your right. It's the wrong character. That equation should be done differently.

Anyway, I believe that you should keep backwards compatibility, and stick this character in a superscript. Even if It's not inside <msup>
