### ISSUE TITLE
SVG Scaling

### ISSUE THREAD

**Issue by phantomlsh** [mathjax/MathJax#2799]
### Issue Summary

There seem to be some problems in `tex2svg()` with the scaling option.

### Steps to Reproduce:

```js
MathJax.tex2svg('x = p', { scale: 1 })
MathJax.tex2svg('x = p', { scale: 2 })
```

These two lines produce SVG with exactly the same width/height and viewBox. Where is the scaling going?

### Technical details:

* MathJax Version: 3
* Client OS: Windows 10
* Browser: Chrome

**Comment by dpvc** [comment]
Normally, MathJax's SVG output is places inside a `<mjx-container>` element, and that element has a scaling factor that is designed to match the font size in the math to the surrounding font.  The SVG (or CHTML) renderer needs to know that scaling factor in order to compensate for it when dimensions are given in absolute units (e.g., `\hskip 1cm`) or when switching back to native fonts for characters that aren't in the MathJax fonts (e.g., for `\unicode{x0416}`, or when `mtextInheritFont` is true, or for things like `\style{font-family: Arial}{x}`).  The `scale` parameter tells the renderer what factor was used to scale the math to match the outside fonts so that that can be compensated for in those situations.  It is not a scaling factor for the final result.

Note that SVG images are, by nature, scalable (SVG is Scalable Vector Graphics), so you can scale the SVG element after the fact.  For example, if you want it to be twice as big, add `font-size: 200%` to the `style` attribute of the surrounding `<mjx-container>` element.

If you are discarding the container, then you would have to scale the width, height and vertical-align values yourself by hand.  You could, of course, make your own wrapper for `MathJax.tex2svg()` that accepts a scaling factor and scales the width, height, and vertical-align of the result fo you.
