### ISSUE TITLE
[Question] Is a way to reverse a node back to TeX string?

### ISSUE THREAD

**Issue by t-k-** [mathjax/MathJax#2803]
Hi, I am doing the following to convert TeX to your internal representation:
```js
const {TeX} = require('mathjax-full/js/input/tex.js');
const {HTMLDocument} = require('mathjax-full/js/handlers/html/HTMLDocument.js');
const {liteAdaptor} = require('mathjax-full/js/adaptors/liteAdaptor.js');
const {AllPackages} = require('mathjax-full/js/input/tex/AllPackages.js');

const tex = new TeX({packages: [ 'base', 'autoload', 'ams', 'newcommand', 'require' ]});
const html = new HTMLDocument('', liteAdaptor(), {InputJax: tex});

fs = require('fs');
latex = fs.readFileSync('input.tex', 'utf8').trim();
console.log(latex)
node = html.convert(latex, {display: false})
console.log(node.childNodes[0].toString())
```
However, sometimes I need to change the symbol of a node or permute the order of some nodes. In these cases, I want to get the changed TeX string. Is there an existing facility for doing this? 

Thank you!

**Comment by dpvc** [comment]
It is not quite clear to me what you are asking.  Are you saying that you will be modifying the HTML that MathJax produces, and then want to convert that back into LaTeX?  There is no mechanism for that in MathJax.  Also, modifying the HTML after it is typeset may lead to incorrect typesetting (if your changes would change the spacing used in the output).  If you want to modify the expression, it is better to modify the original LaTeX and re-typeset it rather than modify the HTML directly.

Davide

**Comment by t-k-** [comment]
I see. Thanks!

Actually what i want to modify is the internal representation (if any) instead of HTML, then i want to convert a modified internal representation back to TeX.

So I guess this is not MathJaX is designed for... but just checking here. Thank you!
