### ISSUE TITLE
Missing spacing for \bmod in subscripts

### ISSUE THREAD

**Issue by int-y1** [mathjax/MathJax#2806]
### Issue Summary

I discovered this issue while working with MathJax 3.2.0. This issue is the same as #794, but the solution was specific to MathJax 2.

### Steps to Reproduce:

1. Go to https://www.mathjax.org/#demo
2. Type in `AA $i \bmod N$ AA $c_i = c_{i \bmod N}$ AA`.
3. ![Capture](https://user-images.githubusercontent.com/14223529/142751670-5f8f9192-1978-4e85-a2ed-ac46c0efec2b.png)

In the subscript, there should be spaces around the bmod.

### Technical details:

* MathJax Version: 3.2.0
* Client OS: Windows 10 21H1
* Browser: Chrome 96.0.4664.45

**Comment by dpvc** [comment]
Thanks for the report.  This is due to the fact that MathJax makes `\bmod` into a "math operator"  as `<mo>mod</mo>` in MathML, and that will normally get spacing around it, but spacing around operators is removed in script and script-script modes, so that space is lost in the subscript in your example.  I will look into resolving the issue.

**Comment by dpvc** [comment]
OK, it turns out that the `lspace` and `rspace` attributes were being given explicitly, as in the v2 solution, but that these spaces were being removed at a later stage by a filter that removes attributes when they equal the defaults.  That means the space was not added in the scripts, since the explicit `lspace` and `rspace` were no longer there to force the spacing (only the default space, which is removed in scripts).

I've made a pull request (listed above) to resolve the issue.
