### ISSUE TITLE
Problems MathJax3.2 and Prototype 1.7.3

### ISSUE THREAD

**Issue by jenswitzel** [mathjax/MathJax#2810]
### Issue Summary

We're trying to upgrade from an old MathJax V2.0 to V3.2 but got heavy problems: MathJax2.0 all worked fine for us. Now V3  prototype.js prevents showing the correct Math Symbols :-/ 

We have prototype.js 1.7.3, jQuery and lot more fund before adding MathJax CDN. See below. Is there any hint regarding the depencies of JS-libs and/or the formular "$" notation?

### Steps to Reproduce:
1) config and scripts in Template/HTML
```
 [...]
 <script src="/javascript/prototype.js"></script>
 [...]
 <!-- MathJax3.2 test -->
 <script>
 window.MathJax = {
  tex: {
    inlineMath: [ ['$','$'], ["\\(","\\)"] ],
    displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
    processEscapes: true,
    autoload: {
      color: [],
      colorv2: ['color']
    },
    packages: {'[+]': ['noerrors']}
  },
  options: {
    ignoreHtmlClass: 'tex2jax_ignore',
    processHtmlClass: 'tex2jax_process'
  },
  loader: {
    load: ['[tex]/noerrors']
  }
 };
 </script>
 <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script id="MathJax-script" async
          src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js">
  </script>
 <!-- MathJax3.2 test end -->
```
2) Math-Code
```
 <h1>Search for a new bottomonium state decaying to $\Upsilon(1S)\pi^+\pi^-$ in pp collisions at $\sqrt{s}$ = 8 TeV</h1>
```

But no Math seen. 

### Technical details:

* MathJax Version: 3.2
* all browsers, all systems

**Comment by jenswitzel** [comment]
![Screenshot 2021-12-08 at 10-16-34 Search for a new bottomonium state decaying to $ Upsilon(1S) pi^+ pi^-$ in pp collisions ](https://user-images.githubusercontent.com/13750822/145182379-b64e1ca3-284e-46c4-a94e-d7eef92b8e22.png)

**Comment by pkra** [comment]
You should try to post a full example exhibiting the problem.

But given the screenshot, you're probably injecting HTML after MathJax's initial rendering pass. In that case you're looking for http://docs.mathjax.org/en/latest/advanced/typeset.html.

**Comment by dpvc** [comment]
Are there any error messages in the browser developer console?

If you enter

```
MathJax.typeset()
```
into the browser console by hand after the page loads, does the math get processed?

**Comment by jenswitzel** [comment]
Thanks @dpvc , it's like this:

MathJax.typeset()
Uncaught TypeError: t.attributes is null
    getDataAttributes https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    getAttributes https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    getAttributes https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    visitDefault https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    visitNode https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    childNodeMml https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    visitDefault https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    visitNode https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    childNodeMml https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    visitDefault https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    visitNode https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    childNodeMml https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    visitDefault https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    visitNode https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    childNodeMml https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    visitDefault https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    visitNode https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    childNodeMml https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    visitDefault https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    visitNode https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    visitTree https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    toMML https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    assistiveMml https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    assistiveMml https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    y https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    renderDoc https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    render https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    typeset https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    <anonymous> debugger eval code:1

**Comment by jenswitzel** [comment]
Thanks @pkra 

i can not figure out, where or when to fill in that typeset. Nothing changes.

**Comment by jenswitzel** [comment]
> You should try to post a full example exhibiting the problem.
> 
> But given the screenshot, you're probably injecting HTML after MathJax's initial rendering pass. In that case you're looking for http://docs.mathjax.org/en/latest/advanced/typeset.html.

Try out https://www.zora.uzh.ch/MathJaxV3-test-1.html - it's a "reduced to the problem" HTML. Without <script src="/javascript/auto-3.3.16.js"></script> it works, i really need it due to other parts in that page, but i do not know who what part is fighting against the mathjax and how to config it to work... in MathJax Version 2.0 there where noch problems like this.

Thanks @pkra

**Comment by dpvc** [comment]
@jenswitzel, thanks for the example file and console output; that allowed me to track down the issue.

Libraries like Prototype.js historically have been problematic, especially in conjunction with other libraries, because modifying the standard javascript objects, like Prototype.js does, can cause incompatibilities.  See [here](https://labs.ft.com/2009/09/json2-js-vs-prototype/) and [here](https://humanwhocodes.com/blog/2010/03/02/maintainable-javascript-dont-modify-objects-you-down-own/) for examples.

That is what is happening in your case.  Your `auto-3.3.16.js` file replaces `Array.from()` with a version that is not compatible with modern ES6 object, which MathJax uses internally.  So when MathJax uses `Array.from(map.keys())`, where `map` is an instance of an ES6 `Map` object, it ends up being and empty array rather than the expected array of the keys of the map.  This causes MathJax to malfunction because `Array.from()` no longer does what it is supposed to.

I don't know if this is part of `Prototype.js` or some other package that you have combined into `auto-3.3.16.js`, but the offending line is line 1119, which is

``` javascript
Array.from = $A;
```

You might be able to fix that by replacing it with

``` javascript
if (!Array.from) Array.from = $A;
```

Note that the functions `$A` and `$w` are being defined globally, rather than within a closure, so they are polluting the global namespace.  You might want to enclose them in `(function () {` and `})();` in order to localize them.

Anyway, that is why it isn't working for you.

**Comment by jenswitzel** [comment]
@dpvc - you're my hero! It's the way it works :-D

Thanks for your quick and kind support!!!!
Cheers
 Jens
