### ISSUE TITLE
Redundant linebreaks inside table td

### ISSUE THREAD

**Issue by proy87** [mathjax/MathJax#2823]
There are redundant line breaks inside the table (\frac{5 M + 1}{3}): https://jsfiddle.net/L9z0qerf/
How to make table expand instead of shrinking formulas?

**Comment by dpvc** [comment]
First, you are using a 4 year old version of MathJax (2.7.4) and switching to the latest v2 version (2.7.9) will fix the issue with the fractions right off the bat.  I assume you need automatic line breaking in other parts of the document, so can't turn that off.

The reason that the cells break is that MathJax's line breaking needs to determine the width of the container in order to figure out where it needs to break, but in a "shrink-wrap" element, like a table cell, that with is the width of the longest item in the column (before MathJax runs on that cell).  That means your column is potentially zero width, or only as wide as the text in the title cells.

Changing the version should fix the fraction breaks, but the last column may need to have `min-width: 4.5em` set for it.

**Comment by proy87** [comment]
@dpvc , thank you!

**Comment by proy87** [comment]
@dvpc, after upgrading to 2.7.9 from 2.7.4, there appeared a bug in form: https://www.emathhelp.net/en/calculators/calculus-1/implicit-differentiation-calculator/ (f(x,y)=g(x,y) should be on one line, but now it is breaked). Everything was OK with 2.7.4.

**Comment by dpvc** [comment]
You are using flex-box alignments, and MathJax can't determine the width of those very easily.  If you add `width:100%;` to the CSS for the `label` tag that contains the formula, that should take care of it.

**Comment by proy87** [comment]
@dpvc , thank you. Is it possible to config MathJax, render the form and then re-config MathJax, so the formulas are rendered differently from those that are in the form? For example, I want to disable zoom and menu in the form.

**Comment by dpvc** [comment]
It depends on what configuration options you want to change.  Some are used only at startup, so changing them later won't affect anything, for example.  Some options, like the ones controlling menus, zoom, and other events, are "live", meaning that changing them will affect all the math on the page.  So if you disable the menu, it disables it for all math.  This setting is not saved with each math expression, but is global.

In order to prevent some math from having the menu and others having it, you would need to mark the math for which you want to disable the menu, and override the math event handler to make it check for that marker and not process the event for the marked items.

Here's one configuration that would do that:

``` html
<script type="text/x-mathjax-config">
MathJax.Hub.Register.LoadHook('[MathJax]/extensions/MathEvents.js', function () {
  var ME = MathJax.Extension.MathEvents.Event;
  var Handler = ME.Handler;
  ME.Handler = function (event, type, math) {
    //
    //  Only call the original handler for those that aren't marked
    //    as having no menu.
    //
    if (!math.getAttribute('data-mjx-nomenu')) {
      Handler.call(this, event, type, math);
    }
  }
});
MathJax.Hub.Queue(function () {
  //
  //  Find the math contained inside <math-momenu> elements and mark them as not to have the menu
  //     (you could use other criteria, such as having a particular class, or whatever)
  //
  var math = MathJax.Hub.getAllJax(Array.from(document.querySelectorAll('math-nomenu')));
  for (var i = 0, m = math.length; i < m; i++) {
    document.getElementById(math[i].inputID + '-Frame').setAttribute('data-mjx-nomenu', 'true');
  }
});
</script>
```

Place this just *before* the script that loads `MathJax.js` itself.  Then you enclose the math that doesn't need the menu in 

``` html
<math-nomenu>...</math-nomenu>
```

and any equations that are within those tags will not have any menu, key, or click interactivity, while the rest of the math will.  You can have multiple occurrences of `<math-nomenu>` if you need several different sets of expressions with no menu.

See if that does the trick for you.

**Comment by proy87** [comment]
@dvpc , thank you very much!
