### ISSUE TITLE
BrowserAdaptor's viewbox is too small when rendering invalid TeX with SVG output

### ISSUE THREAD

**Issue by wb-joona** [mathjax/MathJax#2824]
### Issue Summary

I'm trying to render TeX to SVG by using MathJax 3 modules directly for more control over a more advanced integration.

When typesetting an equation into SVG which produces an error, the produced SVG's viewbox seems to default to some nearly zero-width default width when using BrowserAdaptor instead of LiteAdaptor. The execution context is of course the browser, not Node.js. 

However, when using LiteAdaptor, the viewbox is large enough for the error message.

### Steps to Reproduce:

Please see example code sandbox here: https://codesandbox.io/s/mathjax-3-browseradaptor-svg-issue-fzv69?file=/src/index.js

1. Run the example sandbox
2. Notice that in the example, the SVG produced is of somewhat correct width, and it shows the error message (albeit with black text on a black background).
   - Open the console in CodeSandbox to see that the generated SVG has a viewbox with enough width to reveal the text, and the `rect` element has a nonzero width.
        ```svg
        <svg
            style="vertical-align: -0.452ex"
            xmlns="http://www.w3.org/2000/svg"
            width="25.792ex"
            height="2.149ex"
            role="img"
            focusable="false"
            viewBox="0 -750 11400 950"
            xmlns:xlink="http://www.w3.org/1999/xlink"
        >
            <defs></defs>
            <g
                stroke="currentColor"
                fill="currentColor"
                stroke-width="0"
                transform="scale(1,-1)"
            >
                <g data-mml-node="math">
                    <g data-mml-node="merror" data-mjx-error="Missing close brace">
                        <rect
                            data-background="true"
                            width="11400"
                            height="950"
                            y="-200"
                        ></rect>
                        <g data-mml-node="mtext" style="font-family: serif">
                            <text
                                data-variant="-explicitFont"
                                transform="scale(1,-1)"
                                font-size="884px"
                            >
                                Missing close brace
                            </text>
                        </g>
                    </g>
                </g>
            </g>
        </svg>
        ```
3. In the code sandbox, perform the following code change, save, and refresh the preview window.
    ```diff
    @@ -5,7 +5,7 @@ import { browserAdaptor } from "mathjax-full/js/adaptors/browserAdaptor";
     import { liteAdaptor } from "mathjax-full/js/adaptors/liteAdaptor";
     import { RegisterHTMLHandler } from "mathjax-full/js/handlers/html";
     
    -const adaptor = liteAdaptor();
    +const adaptor = browserAdaptor();
     RegisterHTMLHandler(adaptor);
     
     const tex = new TeX({});
    ```
4. Notice that the SVG's viewbox is now too small for the text, and the `rect`'s with is 0.
    ```svg
    <svg
        xmlns="http://www.w3.org/2000/svg"
        width="0.113ex"
        height="2.149ex"
        role="img"
        focusable="false"
        viewBox="0 -750 50 950"
        xmlns:xlink="http://www.w3.org/1999/xlink"
        style="vertical-align: -0.452ex"
    >
        <defs></defs>
        <g
            stroke="currentColor"
            fill="currentColor"
            stroke-width="0"
            transform="scale(1,-1)"
        >
            <g data-mml-node="math">
                <g data-mml-node="merror" data-mjx-error="Missing close brace">
                    <rect
                        data-background="true"
                        width="0"
                        height="950"
                        y="-200"
                    ></rect>
                    <g data-mml-node="mtext" style="font-family: serif">
                        <text
                            data-variant="-explicitFont"
                            transform="scale(1,-1)"
                            font-size="884px"
                        >
                            Missing close brace
                        </text>
                    </g>
                </g>
            </g>
        </g>
    </svg>
    ```

Additionally, here's a `diff` of the two SVGs:

```diff
@@ -1,12 +1,12 @@
 <svg
-    style="vertical-align: -0.452ex"
     xmlns="http://www.w3.org/2000/svg"
-    width="25.792ex"
+    width="0.113ex"
     height="2.149ex"
     role="img"
     focusable="false"
-    viewBox="0 -750 11400 950"
+    viewBox="0 -750 50 950"
     xmlns:xlink="http://www.w3.org/1999/xlink"
+    style="vertical-align: -0.452ex"
 >
     <defs></defs>
     <g
@@ -19,7 +19,7 @@
             <g data-mml-node="merror" data-mjx-error="Missing close brace">
                 <rect
                     data-background="true"
-                    width="11400"
+                    width="0"
                     height="950"
                     y="-200"
                 ></rect>
```

### Technical details:

* MathJax Version: mathjax-full@3.2.0
* Client OS: Windows 10 version 10.0.19044
* Browser: Chrome 97.0.4692.71, Firefox 96.0.2

### Supporting information:

 * Please supply a link to a (live) minimal example page, when possible.
   - https://codesandbox.io/s/mathjax-3-browseradaptor-svg-issue-fzv69?file=/src/index.js
 * If your issue is with the display of the mathematics produced by MathJax, include a screen snapshot that illustrates the problem, when possible.
   - LiteAdaptor (with text selected in the browser to reveal the text):
      * ![image](https://user-images.githubusercontent.com/85222502/150777728-8c151867-862e-4e3e-9d63-1eb8a2bdd4f7.png)
   - BrowserAdaptor (with text selected):
      * ![image](https://user-images.githubusercontent.com/85222502/150777781-9f088519-bc50-491a-897a-ddeae7d77da1.png)
 * Check your browser console window for any error messages, and include them here.
   - None
 * Include the MathJax configuration you are using, and the script tag that loads MathJax itself.

```js
// npm i mathjax-full@3.2.0
import { mathjax } from "mathjax-full/js/mathjax";
import { TeX } from "mathjax-full/js/input/tex";
import { SVG } from "mathjax-full/js/output/svg";
import { browserAdaptor } from "mathjax-full/js/adaptors/browserAdaptor";
import { liteAdaptor } from "mathjax-full/js/adaptors/liteAdaptor";
import { RegisterHTMLHandler } from "mathjax-full/js/handlers/html";

const adaptor = browserAdaptor();
RegisterHTMLHandler(adaptor);

const tex = new TeX({});

const svgOutput = new SVG({
  fontCache: "local"
});

const doc = mathjax.document("", {
  InputJax: tex,
  OutputJax: svgOutput
});

const node = doc.convert("\\text{\\begin{align}\\end{align}", {
  display: true,
  em: 50,
  ex: 25,
  containerWidth: 1100
});

const svg = adaptor.innerHTML(node);

console.log(svg);
document.getElementById("app").innerHTML = svg;
```

**Comment by dpvc** [comment]
Thanks for the detailed report.

Here's what's going on.  First, note that by default MathJax will typeset error messages using the browsers `serif` font rather than the MathJax TeX fonts (as that is more efficient and generally looks better).  But when MathJax has to typeset text using a font other than the MathJax TeX fonts, it doesn't have the font data needed to tell the sizes of the characters itself, so it has to determine the size some other way.  

For the `liteAdaptor`, that is done by making the size proportional to the width of the string (which is woefully inadequate, but the best it can do for now).  That is why the box is too large in your case (it assumes all characters are .5em wide, and that just isn't the case).

For the `browserAdaptor`, MathJax inserts the text temporarily into the DOM and asks the browser to measure it, and then converts that size into its internal measurements.  But in your case, you have used `mathjax.document("",...)`, and when you pass a string to `mathjax.document()`, it parses your string as a new DOM, and that DOM is detached from any window, so is not displayed.  That means that the browser won't compute any measurements within that DOM, and everything comes back as having width 0.  So MathJax can't tell how big anything is, and you get the near zero width element that you are seeing (it is actually set to be 1px wide according to the `ex` value that you have given it because some browsers don't show 0 width elements at all).

To resolve that issue, you should use `mathjax.document(document,...)` so that you are using the actual displayed document for the size computations.

Alternatively, you can tell MathJax to use its MathJax TeX fonts for error messages, so that it can compute the width properly without needing the browser to perform measurements.  To do that, use

``` js
const svgOutput = new SVG({
  fontCache: "local",
  merrorFont: ''
});
```

to disable the `merrorFont`.  That will also work with the `liteAdpator` to get the width to match the text.

As for the black background, that is due to the fact that you haven't included the CSS that the SVG output generates, and so the styling that is supposed to be applied to the background rectangle (and the text itself) is not being done.  To resolve that, you can either get the CSS from the SVG by using

``` js
svgOutput.stylesheet(doc)
```

or you could fold the CSS into the SVG element itself using

``` js
//
//  Minimal CSS needed for stand-alone image
//
const CSS = [
  'svg a{fill:blue;stroke:blue}',
  '[data-mml-node="merror"]>g{fill:red;stroke:red}',
  '[data-mml-node="merror"]>rect[data-background]{fill:yellow;stroke:none}',
  '[data-frame],[data-line]{stroke-width:70px;fill:none}',
  '.mjx-dashed{stroke-dasharray:140}',
  '.mjx-dotted{stroke-linecap:round;stroke-dasharray:0,140}',
  'use[data-c]{stroke-width:3px}'
].join('');

const svg = adaptor.innerHTML(node).replace(/<defs>/, `<defs><style>${CSS}</style>`);
```

instead.

**Comment by wb-joona** [comment]
Thank you for the thorough response! I can confirm that passing in `document` does, in fact, fix the sizing issue together with `merrorFont: ''`. The CSS was also missing, and we opted to bake those styles in as `style`s due to some SVG renderer requirements.

Thank you very much for your help.

**Comment by dpvc** [comment]
Glad it worked out for you!
