### ISSUE TITLE
How to not show parsing error or show customized error message?

### ISSUE THREAD

**Issue by sathiyad** [mathjax/MathJax#2832]
I am using MathJax for showing equations on my webpage. Using the below config script. But in case of syntax error, I Don't wanna show the exception instead it should show the Jax as it is. Gone through about formatError in here https://docs.mathjax.org/en/latest/options/input/tex.html but How to use it? tried a couple of methods but it does not help.

```JS
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    showMathMenu: false,
    extensions: ["tex2jax.js"],
    messageStyle: "none",
    showProcessingMessages : false,
    jax: ["input/TeX", "output/SVG"],
    tex2jax: {
      inlineMath: [ ['$','$'], ["\\(","\\)"] ],
      displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
      processEscapes: true,
      preview: "none",
      
    },
    processEnvironments: true,
  });
</script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js"></script>
```

![Screenshot from 2022-01-28 15-18-45](https://user-images.githubusercontent.com/25609136/152752046-affb678b-403e-47f3-a582-f7065453e072.png)

also find it here : https://stackoverflow.com/questions/70891686/how-to-not-show-parsing-error-in-mathjax

**Comment by dpvc** [comment]
You probably want to use the `noUndefined` and `noErrors` extensions.  The first will cause undefined macros to show as a red version of the macro name, but will typeset the rest of the expression.  For example `x + \3` would appear as

<img width="124" alt="noundefined" src="https://user-images.githubusercontent.com/432782/152837899-c079380a-aef9-445b-a526-8ce2baefe934.png">

rather than the undefined control sequence message that you are seeing above.

The second causes any other type of error to just display the original TeX code rather than the error message.  So `\frac{a}{b` with a missing close brace would just display as `\frac{a}{b` rather than the error message.

To do this, you would add

``` js
TeX: {
  extensions: ['noErrors.js', 'noUndefined.js']
},
```

to your configuration.  See the documentation for [noUndefined](http://docs.mathjax.org/en/v2.7-latest/tex.html#noundefined) and [noErrors](http://docs.mathjax.org/en/v2.7-latest/tex.html#noerrors) for more details.

**Comment by sathiyad** [comment]
It works! Thank you!
@dpvc
