### ISSUE TITLE
Add an entry for "prescription," the ℞ symbol

### ISSUE THREAD

**Issue by d0ugparker** [mathjax/MathJax#2839]
I've looked for the 

`℞`

entry, which I would think would be 

`\Rx`

but haven't found it. It is available in Unicode, as U211E.

`\Rx `

would display 

`℞`

**Comment by dpvc** [comment]
Because MathJax concentrates on displaying mathematical notation, many non-mathematical symbols are not in its fonts.  But you can use `\unicode{x211E}` to obtain the symbol, if you need it.  You can also define your own macro such as `\newcommand{\Rx}{\unicode{x211E}}`.  You can even add that into your MathJax configuration (if you are using this on your own pages).  See the documentation [here](https://docs.mathjax.org/en/latest/input/tex/macros.html) and [here](https://docs.mathjax.org/en/latest/input/tex/extensions/configmacros.html#tex-configmacros-options) for details.

**Comment by dpvc** [comment]
Note that the documentation I pointed you to is for version 3.  If you are using version, look [here](http://docs.mathjax.org/en/v2.7-latest/tex.html#defining-tex-macros) and [here](http://docs.mathjax.org/en/v2.7-latest/options/input-processors/TeX.html).
