### ISSUE TITLE
Rendering of spaces in Hugo

### ISSUE THREAD

**Issue by mojomaayan** [mathjax/MathJax#2841]
### Issue Summary

Using MathJax in Hugo, double spaces are rendered which are not in code.

### Steps to Reproduce:

1. I used the [Educenter theme](https://github.com/themefisher/educenter-hugo).
2. To embed MathJax in Hugo, I followed the steps in [this link](https://geoffruddock.com/math-typesetting-in-hugo/). 
3. The css files for the theme are [here](https://github.com/themefisher/educenter-hugo/tree/master/assets/scss)

The equation I had was:

```
The general equation of a circle is $(x-h)^2 + (y-k)^2= r^2.$ As the circle touches the $x$-axis, the length of the radius is equal to $k$, so the circle is Substituting the points $(1, −2)$ and $(3, 0)$, we have two equations: \begin{align*}
(1-h)^2+(-2-k)^2 &= 4,\\\
(3-h)^2+k^2 &= k^2.
\end{align*}
```
<img width="1108" alt="hugo_output" src="https://user-images.githubusercontent.com/96335452/155405222-9d140049-7001-459f-86bd-c8356738ed61.png">

### Technical details:

* MathJax Version: 3.0
* Client OS: Mac OS X latest
* Browser: Chrome and Safari (latest)

**Comment by dpvc** [comment]
I suspect there is something in the CSS that is causing this, but it is hard to find it outside of working with an actual live page.  Can you provide a link to a page that exhibits the problem?

Also, the link in your step 2 has some details that could be improved.  A trivial one is that to remove the `code` tag from the skip list it is better to use

``` javascript
skipHtmlTags: {'[-]': ['code']}
```

rather than listing all the tags to keep.  That way, if the list changes, you will get the updated version automatically.  (In fact, the list given at that link is missing a couple already.)

The more serious issue is the `onload` handler, which is not properly synchronized with MathJax.  It would be better to add a render action that adds the needed class.  A modified configuration would be

``` javascript
  MathJax = {
    tex: {
      inlineMath: [['$', '$'], ['\\(', '\\)']],
      displayMath: [['$$', '$$'], ['\\[', '\\]']],   // this is the default, so not really needed
      processEscapes: true,                          // ditto
      processEnvironments: true                      // ditto
    },
    options: {
      skipHtmlTags: {'[-]': ['code']},
      renderActions: {
        mathContainer: [250,
          (doc) => {for (const math of doc.math) MathJax.config.addClass(math)},
          (doc, math) => {MathJax.config.addClass(math)}
        ]
      }
    },
    addClass(math) {
      math.typesetRoot.parentElement.classList.add('has-jax');
    }
  };
```

I'm not sure I understand the need for the `has-jax` class, as it is being placed on the container element for the math (e.g., the `<p>` or `<div>` or whatever that holds math), and I don't know why you need to turn off its border or set its font size, as the theme should regulate those.  If some themes styles are bleeding into the math itself (say a border being put on the `<mjx-container>` element, then it is probably best to use CSS that styles `.MathJax`, since all the `<mix-container>` element, or style `mjx-container` itself.  but do what you need to do.

**Comment by mojomaayan** [comment]
@dpvc Thanks, I have removed the hasjax script and edited the javascript as you had said. Yet this had no changes. I have uploaded the website [here](https://padips.netlify.app/courses/jee-main-math/), would love to know which css conflicts with the rendering.

**Comment by dpvc** [comment]
OK, the culprit is [this rule](https://github.com/themefisher/educenter-hugo/blob/6b4ccc7a0f02a81f1be57e047e132254a31796c2/assets/scss/_common.scss#L322-L324) that sets the margin-bottom for essentially **all** elements in the page.  That's a pretty aggressive rule, and it affects any block or inline-block element, including most of MathJax's elements.  Since these are deeply nested, the bottom-margins add up to ta lot.

What may work better is to use `.content > *` rather than `.content *`.  Alternatively, you might try

``` css
mjx-container.MathJax * {
  margin-bottom: 0px;
}
```

but it is always dangerous to make such broad rules, as they can have unintended consequences (like the one you are seeing).  I don't think this will override anything that MathJax is setting, but things like this don't always work as expected.

In any case, it is not a MathJax error, but an overly aggressive CSS rule.

**Comment by mojomaayan** [comment]
Thanks, that works!
