### ISSUE TITLE
How to render data with math ml

### ISSUE THREAD

**Issue by illiyyin** [mathjax/MathJax#2842]
I had a string from a database like this

`<math xmlns="http://www.w3.org/1998/Math/MathML"><mfenced><mtable><mtr><mtd><mn>3</mn></mtd><mtd><mn>5</mn></mtd></mtr><mtr><mtd><mo>-</mo><mn>1</mn></mtd><mtd><mn>2</mn></mtd></mtr></mtable></mfenced><mfenced><mtable><mtr><mtd><mn>2</mn></mtd><mtd><mo>-</mo><mn>2</mn></mtd></mtr><mtr><mtd><mn>5</mn></mtd><mtd><mn>1</mn></mtd></mtr></mtable></mfenced></math>`

I tried using cdn and
`window.Mathjax.Hub.Queue(['Typeset', window.Mathjax.Hub]);`

It's still not working rn

**Comment by dpvc** [comment]
There is not enough information here to diagnose your problem.  MathJax can process the MathML that you gave, so it is probably in your setup or workflow, but you don't indicate which.  For example, you don't say what your configuration is, so I can't tell if you actually have the MathML input jax loaded or not.  You don't say how you insert the MathML into the page, and where the `MathJax.Hub.Queue()` call is in relation to that.  You don't say what browser or OS you are using, or what web platform you are using (or if you have written your own).  So there is not much we can say to help you at this point.

A link to a minimal (non-)working example page would be most useful.  Otherwise, additional details would help.

**Comment by illiyyin** [comment]
I just found the solution using `react-mathjax-preview` library, thanks for the answer
