### ISSUE TITLE
can mathjax convert mathml to asciimath

### ISSUE THREAD

**Issue by weihaopeng** [mathjax/MathJax#2843]
**Describe the solution you'd like**
I only found how to convert asciimath to mml. Can I input mml and output asciimath using MathJax?

**Comment by weihaopeng** [comment]
Thanks, In my situation, I need to input some simple structure mathml. So I use asciimath to  input, and then convert it to mathml using MathJax. We store data using mathml.

However, in edit mode, I have to convert mathml into asciimath.

My solution is parsing simple structure and converting symbols, consulting [mathml-to-asciimath](https://github.com/learningobjectsinc/mathml-to-asciimath). As you say, it's hard to conver all cases, but some simple mathml can be converted.

I think mathml to asciimath is useful sometime. Hope we can think of some better solutions in the future.

**Comment by dpvc** [comment]
> So I use asciimath to input, and then convert it to mathml using MathJax. We store data using mathml.  However, in edit mode, I have to convert mathml into asciimath.

Why not keep the original AsciiMath as part of the MathML?  You could use a `<semantic>` tag to do that, or you could use a data attribute to keep it.  For example, if your original AsciiMath is `x/y`, then the generated MathML is

``` mathml
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mstyle displaystyle="true">
    <mfrac>
      <mi>x</mi>
      <mi>y</mi>
    </mfrac>
  </mstyle>
</math>
```

but you could modify this to be

``` mathml
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <semantics>
    <mstyle displaystyle="true">
      <mfrac>
        <mi>x</mi>
        <mi>y</mi>
      </mfrac>
    </mstyle>
    <annotation encoding="text/x-asciimath">x/y</annotation>
  </semantics>
</math>
```

Alternatively, you could use

``` mathml
<math xmlns="http://www.w3.org/1998/Math/MathML" data-asciimath="x/y">
  <mstyle displaystyle="true">
    <mfrac>
      <mi>x</mi>
      <mi>y</mi>
    </mfrac>
  </mstyle>
</math>
```

That way, you can recover the original AsciiMath rather than having to reconstruct it from the MathML, which might not reproduce the original exactly even if you had a method of doing that.
