### ISSUE TITLE
Prevent rendering twice, how? (v2.x)

### ISSUE THREAD

**Issue by koosvanderkolk** [mathjax/MathJax#2848]
### Issue Summary

We have an external lib which creates a clone of a DOM element with rendered MathJax. After this, the environment (a Drupal site) re-runs the MathJax rendering process. This results in the clone receiving twice the rendered output.

In the DOM there are more than one indications that MathJax already finished rendering this element (added classes, DOM elements, etc), but still MathJax takes the <script> tag and re-renders it.

How can this be prevented?

### Steps to Reproduce:

1. In the JavaScript console, edit the HTML of an element containing rendered MathJax code.
2. Rerun the MathJax rendering: the output is rendered twice.
3. Do 1+2, but first remove the script tag. The output is rendered once.

### Technical details:

* MathJax Version: 2.7.9
* Client OS: Windows
* Browser: Chrome 29.0.1547.57

**Comment by dpvc** [comment]
Using `cloneNode()` on MathJax output can cause problems, as you have found.  In particular, there are important things that aren't cloned, including event handlers for things like the contextual menu and the various actions for the `action` extension.  But the other important item that is not copied is a property that MathJax attaches to the `<script>` element for the math.  This is an object that contains the information MathJax needs in order to manage the math expression.  For one thing, it is this that MathJax uses to tell that the math has been typeset, but there is a lot of other data there as well; it is also used by the MathJax menu, and for other features of MathJax.

The options, as I see it, are 

1.  Don't clone the output, but use the original elements instead, so that all the data are properly attached.  In case you are, you shouldn't have two copies of the MathJax output in the DOM at once, as the ids need to be unique.  If not, and you are removing the original elements, then there is no reason to make a copy; just use the originals.
2. Remove the script tags before cloning and only leave the output.  Since you aren't copying the event handlers, you won't be getting the contextual menu or any of the other features that need the script tags, so there is no need to keep them.  That way the second pass of MathJax over the content won't find any math to typeset.  (I see this is your item 3 above.)
3. Since you are running MathJax again anyway, why render it originally?  Just pass the source TeX or MathML and let the second pass render it, or if you need to display it before cloning, then remove the rendered output before hand.

I hope one of those will work for you.  But cloning is not going to work as you hope it will, I'm afraid.

**Comment by koosvanderkolk** [comment]
Thanks @dpvc!

I think I have to go for option 2, as 1 and 3 our not under my control.
