### ISSUE TITLE
Undefined error when running latest MathJax from cdn, makes the entire application freeze

### ISSUE THREAD

**Issue by evenstensberg** [mathjax/MathJax#2852]
### Issue Summary

If we load mathjax using `window.MathJax.typesetPromise();` it sometimes crash 

`
semantic-enrich.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'components')
    at Object.723 (semantic-enrich.js:1:5941)
    at r (semantic-enrich.js:1:7858)
    at semantic-enrich.js:1:7916
    at semantic-enrich.js:1:8222
    at semantic-enrich.js:1:8225
`
### Steps to Reproduce:

1. set `window.MathJax.typesetPromise();` after loading a fraction in html multiple times

Any other information you want to share that is relevant to the issue
being reported. Especially, why do you consider this to be a bug? What
do you expect to happen instead?

### Technical details:

* MathJax Version: 2.3 (latest commit: f3aaf3a2a3e964df2770dc4aaaa9c87ce5f47e2c)
* Client OS: Mac OS X 10.8.4
* Browser: Chrome 29.0.1547.57

### Supporting information:

N/A

**Comment by evenstensberg** [comment]
This happens if we import the mathjax script multiple times and set `window.MathJax.typesetPromise();`

**Comment by dpvc** [comment]
PS, you have not even filled in the Technical Details section, but have left the original example values there.  It is hard to help without the true details for your situation.

**Comment by teleprint-me** [comment]
This issue has driven me up the wall for the past few days because I could not figure it out. I finally was able to intentionally reproduce it and discover why it happens!

Let's start with a really simple example snippet of what does work.

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Meta tags and other head content here -->
    <title>MathJax Test</title>
  </head>
  <body>
    <div id="math-container"></div>
    <script>
      MathJax = {
        tex: {
          inlineMath: [
            ['$', '$'],
            ['\\(', '\\)']
          ],
          processEscapes: true // enable processing of dollar signs to produce a literal dollar sign
        }
      };
    </script>
    <script
      src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
      id="MathJax-script"
    ></script>
    <script>
      window.onload = function () {
        const mathContainer = document.getElementById('math-container');

        MathJax.typesetPromise().then(() => {
          mathContainer.innerHTML += '$a^2+b^2=c^2$';
          MathJax.typesetPromise();
        });
      };
    </script>
  </body>
</html>
```

Things to highlight and take note of:

- The script has no `type` attribute set.
- The configuration is set before loading the MathJax library
- The `MathJax` object is set and initialized with the `tex` prop before anything else

Doing any of this _after_ loading the `MathJax` library will override the `MathJax` instance object and render everything else as `undefined`.

This is why `MathJax.typeset` and `MathJax.typesetPromise` are `undefined`, essentially breaking the implementation.

It took me forever to piece this together and figure it out. It did __NOT__ matter where the scripts were placed in the document, e.g. in the `head` tag or in the `body` tag. The rationale for placing script tags in the body and not the head is usually to enable the content to be loaded and rendered before applying any scripts that modify the document in any way shape or form. So using this in the head or body is simply a matter of preference, not practice. The web usually exercises placing scripts in the body to enable the document to load as soon as possible for the user. So, with this out of the way, we can finally get into the meat of it.

```html
    <!-- mathjax -->
    <!-- 
      !!!IMPORTANT!!!
      --
      DO NOT SET A TYPE ON THE SCRIPT TAG(S) FOR MATHJAX
      --
      Configuration must be set _before_ loading MathJax from the CDN
      --
      If it is set _after_ loading MathJax from the CDN, the MathJax object is overridden and the classes, methods, and props become undefined as a result
    -->
    <script>
      MathJax = {
        tex: {
          inlineMath: [
            ['$', '$'],
            ['\\(', '\\)']
          ],
          processEscapes: true
        },
        svg: {
          fontCache: 'global'
        }
      };
    </script>
    <!--
      See the following links for more information:
      - https://docs.mathjax.org/en/v3.0-latest/input/tex/delimiters.html#tex-delimiters
      - https://docs.mathjax.org/en/v3.0-latest/options/input/tex.html#tex-options
    -->

    <!-- Enable Older Browsers -->
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <!-- Enable Inline and Block Level Rendering-->
    <script
      src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
      id="MathJax-script"
    ></script>
    <!-- Enable ASCII Rendering -->
    <script
      src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/input/asciimath.js"
      charset="UTF-8"
    ></script>
```

This snippet not only resolved inline rendering, but also fixed the issue with the `typeset` and `typesetPromise` methods being `undefined`.

Why does this happen? It's in the comment in the snippet, but just in case you missed it, I'll reiterate here again: **If this is set _after_ loading `MathJax` from the source, the MathJax object is overridden and the classes, methods, and props become undefined as a result**. All you're left with afterwards is what you overrode the instance object with. This is a really terrible way of handling this because of this very reason!

A potential solution to this problem is to dynamically and asynchronously handle loading the configuration. Enforcing the user to set the attribute _after_ the instance object is created (no pesky `MathJax` object does exist errors). The user explicitly loads the configuration with a method after having set the prop, e.g. `loadTex()` or whatever works. The goal of this proposal is to create a **preventative** measure so that the user does **not** accidentally override the `MathJax` object, essentially erasing any references to the library.

This should really be documented in a clearer fashion. It is mentioned briefly once in the introductory material. It's such a small mention that has a isolated snippet with zero context that it's actually difficult to infer how this is set up; It was still difficult to infer even after having inspected the source code for the official site that uses it to showcase how it works in the example section.

**Comment by zhxy98** [comment]
@teleprint-me you so smart man
