### ISSUE TITLE
How to fix NET::ERR CERT WEAK SIGNATURE ALGORITHM error while using mathjax with cloudfare cdn?

### ISSUE THREAD

**Issue by chaitanya71998** [mathjax/MathJax#2854]
Why my I am getting this error in Chrome browser, unable to use mathjax

### Technical details:
* version 2.7.1, while using Cloudflare cdn
* Client OS: Windows 8
* Browser: Chrome 99.0.4844.74

### Supporting information:
![image](https://user-images.githubusercontent.com/46353549/159130610-a00c5efd-4815-4b24-bc2e-7dd036e4df26.png)

TIA

**Comment by pkra** [comment]
`https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML` works without any cert issues for me on Chrome 99.0.4844.51.

But this is a question for cdnjs, not MathJax.

**Comment by chaitanya71998** [comment]
ok, will ask there, @pkra

**Comment by dpvc** [comment]
Although the `NET::ERR CERT WEAK SIGNATURE ALGORITHM` error your are receiving usually means that the server is misconfigured, it can also be caused by problems on your own computer, and in this case, it is unlikely that Cloudflare is misconfigured.  As Peter points out, he doesn't have any problem getting through, and neither do I (and it is used by many others successfully as well).

I see that you are using Windows 8.  This has been in "[end of life](https://support.microsoft.com/en-us/office/windows-8-end-of-support-and-office-34e28be4-1e4f-4928-b210-3f45d8215595)" status for 6 years, now, and has not been receiving updates since 2016.  It may be that the needed stronger SHA algorithm isn't available in Windows 8 and so it is trying to use the older, insecure algorithm.  I don't know for sure.

There are any number of websites that give you advice on how to check whether this is a problem on your own computer.  See [here](https://www.ssl2buy.com/wiki/how-to-fix-net-err_cert_weak_signature_algorithm-error-in-chrome) and [here](https://www.auslogics.com/en/articles/fix-neterr-cert-weak-signature-algorithm-error/) for two I picked basically at random.  Just [Google the error message](https://www.google.com/search?q=NET%3A%3AERR+CERT+WEAK+SIGNATURE+ALGORITHM) for more.

**Comment by chaitanya71998** [comment]
Yeah, working on it. @dpvc Thank you
