### ISSUE TITLE
`menuOptions` in MathJax 3 seems to be ignored altogether

### ISSUE THREAD

**Issue by fast-reflexes** [mathjax/MathJax#2855]
### Issue Summary

Tried in Chrome 98

### Steps to Reproduce:

According to https://docs.mathjax.org/en/latest/options/menu.html, the `options.menuOptions.settings` configuration object should enable the user to, for example, turn off assistive MML(`assistiveMml`) and remove math from tabbing (`inTabOrder`). However, these options do not seem to work at all. 

With the following configuration:

```js
MathJax = {
  options: {
    enableMenu: true,
    /*renderActions: {
      assistiveMml: []
    },*/
    menuOptions: {
      settings: {
        semantics: true,
        assistiveMml: false,
        inTabOrder: false
      }
    }
  }
};
```

... I would expect all math to be out of tab indexing, assistive mml to be disabled and the math menu to show (and some semantics feature to show in the code). The menu is indeed available but so is assistive mml and all math are included in tabbing. If I disable the math menu and uncomment the block in `renderActions`, I accomplish what I want, but this is not what the documentation says. Also, I should be able to disable math menu but still have tabbed math, which I can't.

Sandbox: https://codesandbox.io/s/pure-mathjax-v3-menuoptions-xdk7fc

In MathJax 2, the options for including math in tabbing works great and interplay with the menu being enabled flawlessly, e.g., I can enable the menu and disable the tabbing and vice versa with
```js
MathJax = {
  menuSettings: { inTabOrder: false },
  showMathMenu: true
};
```

Sandbox: https://codesandbox.io/s/pure-mathjax-v2-menuoptions-f8c3n5

Any other information you want to share that is relevant to the issue
being reported. Especially, why do you consider this to be a bug? What
do you expect to happen instead?

I would expect these settings to control what the documentation says and that the control would be independent from other settings, such as `enableMenu`.

### Technical details:

* MathJax Version: 3.2.0
* Client OS: Mac OS Catalina 10.15.7
* Browser: Chrome 98.0.4758.80 (Official Build) (x86_64)

**Comment by pkra** [comment]
>  Also, I should be able to disable math menu but still have tabbed math, which I can't.

Not a response regarding whether this is expected MathJax behavior but in such a situation (menu present, output not in the tab order) the page would fail [WCAG 2.1.1](https://www.w3.org/WAI/WCAG21/quickref/#keyboard) (all functionality must be keyboard operable).

**Comment by fast-reflexes** [comment]
Aha..

* So this behaviour changed from version 2?
* If so it should be clearly documented that the menu cannot be visible with tabbing disabled
* What about the assistiveMml thing? I didn't manage to turn that off (using the property in `menuOptions` no matter if the menu was enabled or not.

**Comment by dpvc** [comment]
There is a bug where of some of the sticky value (the ones set in the `menuOptions.settings` variable) are not being initialized correctly.  This was reported in #2786, and is fixed in pull request mathjax/Mathjax-src#769, so it will be working in the next release.  

Both the Assistive MML and the tab order settings were subject to this problem, along with a few others.  The semantics setting is not one of them, so you can see in your example that that one is working (if you show the MathML for your equation).   Also, the menu items are properly checked/uncheck, so the settings are not *entirely* ignored.  They just don't initialize properly.

In the meanwhile, here is a configuration that applies the patch from the pull request:

``` javascript
MathJax = {
  options: {
    enableMenu: true,
    menuOptions: {
      settings: {
        semantics: true,
        assistiveMml: false,
        inTabOrder: false
      }
    }
  },
  startup: {
    ready() {
      const {Menu} = MathJax._.ui.menu.Menu;
      
      class myMenu extends Menu {
        constructor(document, options) {
          super(document, options);
          this.applySettings();
        }
        
        applySettings() {
          this.setTabOrder(this.settings.inTabOrder);
          this.document.options.enableAssistiveMml = this.settings.assistiveMml;
          this.document.outputJax.options.scale = parseFloat(this.settings.scale);
          if (this.settings.renderer !== this.defaultSettings.renderer) {
            this.setRenderer(this.settings.renderer);
          }
        }
      }
      
      if (MathJax.version === '3.2.0') {
        MathJax.config.options.MenuClass = myMenu;
      }
      MathJax.startup.defaultReady();
    }
  }
};
```

> So this behaviour changed from version 2?

Only accidentally due to this initialization bug.  But Peter is right, these settings are not in compliance with WCAG specifications, and should only be used if there is a very good reason for it.  While it is possible for a user to enable the tab order setting in the menu, an assistive user who is using the keyboard rather than the mouse will not be able to get to the MathJax menu if the math isn't in the tab order, and so you will have made your page inaccessible to such a user.  It is *much* easier for a non-assistive user to turn *off* the setting than for an assistive user to turn it back on, so it is best to leave the tabbing order as is, unless you either don't care about such users, or know for certain that you will not be having any of them visit your site (e.g., if your site is for a specific audience and you know there are no assistive users in it).

**Comment by fast-reflexes** [comment]
Thanks for a great answer. I admire the extra effort for assistive users, even though in a lot of cases it boils down to non-assistive users wanting to get rid of the extra resulting details in graphic and ux ... But I agree with you from a principal level... So the idea is that as long as you have regular text, there are very many assistive technologies and such to help out but once it is typeset by MathJax, then an assistive user can't use those tools anymore and that's why you're putting so much effort into these features? Just guessing here...

All in all, there should be a flag in browsers / `window` object which indicates to libraries whether we want to enable assistive features and based on that do different things (e.g. `useAssistiveDefaults` if in assistive mode or something). Because I think most people would want to please assistive users too but maybe not at the cost of, what they see, as a lower experience for a larger user group.... then ofc it's debatable whether the experience is really worse or if it's just a mental hangup but....yeah this is a different subject altogether :)

But very happy with the answer! Thanks!

**Comment by fast-reflexes** [comment]
But the documentation is hopefully improved by 3.2.1 then so that it's clear, both what is possible and not and also why this design was chosen :)
