### ISSUE TITLE
MathML mathjax fallback stumbles over links (`<a>` tags).

### ISSUE THREAD

**Issue by FelixBenning** [mathjax/MathJax#2860]
### Issue Summary

I am using [latexml](https://math.nist.gov/~BMiller/LaTeXML/) to convert exercise sheets to html.
In particular the result typsets mathematical formulas in mathml which means that a fallback to mathjax for browsers other than firefox is currently neccessary.

Now if you open the site "https://mannheim-probability.github.io/Probability-Theory/exercises/sheet_7.html"
in any browser other than firefox you will find a "Math input error" in Exercise 5(iv).

The reason is `"unknown node type "a""`. In firefox the end result looks like this:
<img width="923" alt="Screenshot 2022-04-05 at 10 17 34" src="https://user-images.githubusercontent.com/29106652/161710230-c48dc46c-e1a6-4e1e-a5d7-385e9cc71f44.png">

i.e. there are links to previous equations over some equalities. These use the tag `<a>` which seems to be what mathjax is having issues with.

### Steps to Reproduce:

Open up the linked page in any non-Gecko browser such as Chrome or Safari.

### Technical details:

* MathJax Version: The fallback script includes https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js?config=MML_HTMLorMML

**Comment by dpvc** [comment]
The MathML in your equation includes an HTML `<a>` element within an `<mtext>` element.  That is allowed in HTML5's MathML, but it is not required by the MathML specification, and MathJax doesn't currently implement it.  There is a [pull request](https://github.com/mathjax/MathJax-src/pull/781) pending that implements it, but that is not scheduled to be included until the next feature release later this summer.

The link would be better handled via an `href` attribute on the `<mtext>` element, and indeed that `<mtext>` does have one, so I'm not sure why the need for the HTML `<a>`.  Perhaps there is an option to write "pure" MathML without embedded HTML?  If not, then one could probably write a MathML input jax pre-filter to remove the anchors.

**Comment by dpvc** [comment]
PS, the `?config=MML_HTMLorMML` is not needed (and does nothing) in your call to MathJax, and should be removed for version 3.

**Comment by FelixBenning** [comment]
@dpvc thank you for the information. The MathML is autogenerated by latexml and I do not want to modify it at the moment. I created an issue in the latexml repo (see above).

**Comment by dpvc** [comment]
The MathJax pre-filter is one that would run in the browser as part of MathJax's processing of the page, so that may still be an option for you that doesn't require modifying the actual MathML that is generated and included in the HTML.

**Comment by dpvc** [comment]
The MathJax input processors each have lists of functions that get called before or after the input is processed, so that you can do pre- and post-filtering on the input (for just such situations like this).  In the MathML input processor, there is a filter list that is called on the intermediate MathML (before it is turned into internal MathJax MathML nodes).  Here is one that will remove the `<a>` tags and replace them with the text content (i.e., the equation numbers that are the text of the link).  Since the `<mtext>` elements already have `href` attributes, there is no need for these `<a>` elements, as MathJax will create anchors based on the `href` itself.

``` html
<script>
MathJax = {
  startup: {
    ready() {
      MathJax.startup.defaultReady();
      MathJax.startup.input[0].mmlFilters.add(({math, document, data}) => {
        const tags = Array.from(data.querySelectorAll('a'));
        tags.forEach(tag => {
          tag.parentNode.innerHTML = tag.innerText;
        });
      });
    }
  }
}
</script>
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/mml-chtml.js" defer></script>
```

Note that this uses version 3 of MathJax, as your original post indicates; but the page you link to uses version 2.7.0, a *very* old version.  You don't seem to need anything specific to version 2, so I'd recommend moving to version 3.  If you must stay at v2, then at least move up to the current version, which is 2.7.9, which has a number of improvements and bug fixes over version 2.7.0.  Something similar could be done for v2, but the API is a bit different, so if you must stay with v2, this will need to be adjusted a bit.

**Comment by FelixBenning** [comment]
@dpvc thank you for the example - I think the reason for the version mismatch might be that, that the github action environment uses an older version of latexml and the maybe mathjax script is automatically added by that. I can change that easily though.

**Comment by dpvc** [comment]
> > I will try to follow the mml postfilter approach
> This does not seem to work as the problem occurs even earlier

Right, the post filter runs on MathJax's internal MathML structure, which is produced from parsing the MathML tree, but the message about the unknown node type is produced during the parsing (the construction of the internal tree).   So the post-filter is too late. That is why my original comment suggested using the `mmlFilter` rather than `postFilter`.  That runs on the MathML tree *before* it is parsed into the internal tree.  It is also easy to find the `<a>` elements within the tree ising `quersySelectorAll()`.  I still think that is a reasonable approach.

Did I give you the `mml3.transform` approach above?  I'm not sure why that is being used.  The `mml3` extension does set up an `mmlFilter`, but you can set up additional ones, and can use the filter's priority to positioning it either before or after the `mml3` filter, so there should be no need to use an mml3 transformer for this.

As for using `<a>` in v4, MathJax v4 already supports nested HTML in MathML.  You just need to enable it by setting the `allowHtmlInTokenNodes: true` in the `mml` block of your MathJax configuration.  Then something like:

``` html
<math display="block">
  <mi><a href="E.html">E</a></mi>
  <mo>=</mo>
  <mi><a href="m.html">m</a></mi>
  <msup>
    <mi><a href="c.html">c</a></mi>
    <mn>2</mn>
  </msup>
</math>
```

will produce the output

<img width="314" height="118" alt="Image" src="https://github.com/user-attachments/assets/0cc399d3-9ecc-44a1-8a1f-ab42b4d3250a" />

Note, however, that the symbols inside the `<a>` tags will be rendered as HTML, not MathML (so no italics, and not in the MathJax fonts).  You also can't put `<a>` tags around mathematics, like a square root or a fraction (unless you use a nested `<math>` tag, which MathJax won't process, but the native MathML rendering would handle).

If you want the contents of the `<a>` to be rendered as math, then using a configuration like

``` js
MathJax = {
  mml: {
    allowHtmlInTokenNodes: true,
    postFilters: [
      ({data, document}) => {
        const jax = document.inputJax.mml;
        const adaptor = document.adaptor;
        data.walkTree((node) => {
          for (const child of node.childNodes) {
            if (child.kind === 'html') {
              const html = child.getXML();
              if (adaptor.kind(html) === 'a') {
                const href = adaptor.getAttribute(html, 'href');
                const text = jax.mmlFactory.create('text').setText(adaptor.textContent(html));
                if (node.isToken) {
                  node.attributes.set('href', href);
                  node.replaceChild(text, child);
                } else {
                  const mml = jax.mmlFactory.create('mtext', {href}, [text]);
                  node.replaceChild(mml, child);
                }
              }
            }
          }
        });
      }
    ]
  }
};
```

could do it.  That would move the text content of the `<a>` into the parent token node (or into a new `mtext` node if the parent is not a token node.

Note that this would allow *any* HTML to be used inside the MathML.  If you want to restrict the allowed nodes to only `<a>` tags, then you could use 

``` js
MathJax = {
  startup: {
    ready() {
      MathJax.startup.defaultReady();
      const {mathml} = MathJax.startup.document.inputJax.mml;
      mathml.unknownNode = function (type, node) {
        if (type === 'a' && node.hasAttribute('href')) {
          const href = node.getAttribute('href');
          const text = this.adaptor.text(this.adaptor.textContent(node));
          return (this.factory.create('html')).setHTML(
            this.adaptor.node('a', {href}, [text]),
            this.adaptor
          );
        }
        this.error('Unknown node type "' + type + '"');
        return null;
      };
    }
  },
  mml: {
    postFilters: [
      ({data, document}) => {
        const jax = document.inputJax.mml;
        const adaptor = document.adaptor;
        data.walkTree((node) => {
          for (const child of node.childNodes) {
            if (child.kind === 'html') {
              const html = child.getXML();
              if (adaptor.kind(html) === 'a') {
                const href = adaptor.getAttribute(html, 'href');
                const text = jax.mmlFactory.create('text').setText(adaptor.textContent(html));
                if (node.isToken) {
                  node.attributes.set('href', href);
                  node.replaceChild(text, child);
                } else {
                  const mml = jax.mmlFactory.create('mtext', {href}, [text]);
                  node.replaceChild(mml, child);
                }
              }
            }
          }
        });
      }
    ]
  }
};
```

to restrict the nodes allowed, and to report others as unknown tags.  Note that MathJax doesn't sanitize the HTML within the Math (since it will already be in the page when processed), so that is up to you, if you are including user-entered MathML.
