### ISSUE TITLE
\overline converting to mathml with attribute [accent="true"] causes j without dot

### ISSUE THREAD

**Issue by hbghlyj** [mathjax/MathJax#2869]
Hello,

MathJax converts `$\overline{A_i}$` to
```
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mover>
    <msub>
      <mi>A</mi>
      <mi>i</mi>
    </msub>
    <mo accent="true">―</mo>
  </mover>
</math>
```

The `[accent="true"]` attribute can cause `i`(or `j`) in subscript to have no dot, in native MathML output. How to fix this problem (let MathJax set `accent` attribute of \overline to be false)?

Thanks!

**Comment by dpvc** [comment]
What are you using to render the MathML?  I am not able to reproduce the issue you are describing.  The subscript "i" renders properly for me.  In any case, this sounds like a problem with the native MathML renderer, not MathJax itself.

You could use a TeX input jax post-filter to alter the `accent` attribute, but since you haven't given any indication of how you are actually calling MathJax, I can't really tell you what is the best way to do that in your situation.

**Comment by hbghlyj** [comment]
Hello,

I was using Firefox Release 100.0 .
![fig](https://user-images.githubusercontent.com/53823634/167447347-92523a3f-58b6-4494-a205-5b971d8f7278.png)
Yes. This is a problem with the native MathML renderer, not MathJax itself. The subscript "i" renders properly in CommonHTML output.

**Comment by hbghlyj** [comment]
Hello,

I don't have a custom stylesheet. I was using Windows 10. The font for MathML engine is _Latin Modern Math_. But it works great for _Cambria Math_.
![pic](https://user-images.githubusercontent.com/53823634/167472139-00c788c7-1e61-4774-a4ae-1c22f4861018.png)

**Comment by hbghlyj** [comment]
Yes. This is a problem with the native MathML renderer, not MathJax itself.
I have reported at [BugZilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1779891)
