### ISSUE TITLE
The produced SVG is empty after download

### ISSUE THREAD

**Issue by snake-py** [mathjax/MathJax#2897]
I am unsure if this is a bug or a feature request. I am currently working on a site and I want to provide the user with a way of downloading the produced SVG, however, the downloaded svg appears to be empty. Is this a bug or am I doing something wrong?

SO it is not empty perse but everything is collapsed to 0 height. and 0 widths. 

The SVG I am getting looks something like this: 

```
<svg xmlns="http://www.w3.org/2000/svg" width="7.781ex" height="1.441ex" role="img" focusable="false" viewBox="0 -626 3439 637" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" style="vertical-align: -0.025ex;">

<g stroke="#a71e34" fill="#a71e34" stroke-width="0" transform="scale(1,-1)"><g data-mml-node="math">

<g data-mml-node="mi"><use data-c="1D461" xlink:href="#MJX-TEX-I-1D461"></use></g>
<g data-mml-node="mi" transform="translate(361,0)"><use data-c="1D452" xlink:href="#MJX-TEX-I-1D452"></use></g>
<g data-mml-node="mi" transform="translate(827,0)"><use data-c="1D460" xlink:href="#MJX-TEX-I-1D460"></use></g>
<g data-mml-node="mi" transform="translate(1296,0)"><use data-c="1D461" xlink:href="#MJX-TEX-I-1D461"></use></g>
<g data-mml-node="mi" transform="translate(1657,0)"><use data-c="1D45B" xlink:href="#MJX-TEX-I-1D45B"></use></g>
<g data-mml-node="mi" transform="translate(2257,0)"><use data-c="1D452" xlink:href="#MJX-TEX-I-1D452"></use></g>
<g data-mml-node="mi" transform="translate(2723,0)"><use data-c="1D464" xlink:href="#MJX-TEX-I-1D464"></use></g>
</g>
</g>
</svg>
```

This is how I load mathjax:

```js
window.MathJax = {
      tex: {
        inlineMath: [
          ['$', '$'],
          ['\\(', '\\)'],
        ],
      },
      svg: {
        fontCache: 'global',
      },
    };
    (function () {
      var script = document.createElement('script');
      script.src = 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js';
      script.async = true;
      document.head.appendChild(script);
    })();
```

Calling Mathjax like this
```js
    const MathJax = window.MathJax;
    const res = MathJax.tex2svg(equation);
    const svg = res.querySelector('svg');
```

**Comment by dpvc** [comment]
Your configuration specifies that MathJax use a global cache for the character paths.  That means there will be a separate svg element in the page that includes a `<defs>` tag that contains all the paths for the characters used on the page, and the individual expressions will refer to those pages via `<use>` tags with `xlink:href` attributes to identify the paths.  So your SVG that is being saved does not include the paths itself, as they are all in the common svg at the bottom of the page.  So when you save the svg separately and try to view it in a different setting, the paths are not available, and the `<use>` elements will not be able to locate the needed paths.

The solution is to either use a local font cache (each equation has its own `<defs>` element for the characters in the expression), or no cache at all explicit paths are used rather than `<use>` tags).

Also not that some CSS my be needed in order for the SVG to render properly.  The examples in the [MathJax node demos](https://github.com/mathjax/MathJax-demos-node) repository that produce SVG output contain code that inserts the needed styles into the SVG itself, so you might want to look there at any of the `tex2svg` or `mml2svg` implementations to see how that is done.

**Comment by snake-py** [comment]
@dpvc thank you for your quick answer - to me it sounds like the easiest solution will be to disable the cache. I cannot find the cache disable the option in the documentation. am I looking at the wrong place?
https://docs.mathjax.org/en/latest/web/configuration.html#configuring-mathjax

**Comment by dpvc** [comment]
That is the generic page about how configuration works,  The individual configuration options for the SVG output are describes [here](https://docs.mathjax.org/en/latest/options/output/svg.html).  Setting `fontCache: 'none'` should do it.

**Comment by snake-py** [comment]
@dpvc thank you so much this worked
