### ISSUE TITLE
MathjaxV2: Can't render elements and get result synchronously

### ISSUE THREAD

**Issue by scruel** [mathjax/MathJax#2925]
### Issue Summary
With `MathJax.Hub.Queue`, Seems that after 'Typeset' job done, the elements still will not be rendered fully, but outer code block can get the result I want to get, but outer code block will not always act like this, consider it will be executed asynchronously.
![image](https://user-images.githubusercontent.com/16933298/190859002-6ab3e297-57d5-4dcd-9ecd-2b26a9ed4fee.png)

### Steps to Reproduce:
After script loaded, just execute the following code in browser console:
```
var mathbox = document.createElement('div'); 
mathbox.innerHTML='$$\sum_x^33$$'
MathJax.Hub.Queue(
  ['Typeset', MathJax.Hub, mathbox, () => {console.log('callback', mathbox.innerHTML);}],
  ["PreProcess",MathJax.Hub],
  ["Delay",MathJax.Callback,5000],
  ["Process",MathJax.Hub],

  [() => {console.log('queue-next', mathbox.innerHTML);}]
);
console.log('outer', mathbox.innerHTML)
```

Any other information you want to share that is relevant to the issue
being reported. Especially, why do you consider this to be a bug? What
do you expect to happen instead?
I want to have “callback”, “queue-next”, 'outer' all get the same result, rather than get an incomplete rendered DOM object with “processing” styles.
The documentation mentioned that typeset will call the callback function after its process completed, and for all jobs pushed into the Queue, should be executed synchronously, but I can't get the rendered result like outside code block can.

### Technical details:

* MathJax Version: 2.7.9
* Client OS: Windows
* Browser: Firefox 102

I am using the following MathJax configuration:
MathJax default

and loading MathJax via

``` html
    <script src="https://unpkg.com/mathjax@2.7.9/MathJax.js?config=TeX-AMS_CHTML"></script>

```

**Comment by scruel** [comment]
Solved by updating to v2.7.9...

**Comment by dpvc** [comment]
MathJax v2 relies on the element containing the mathematics to be part of a live DOM, meaning it must be part of a page being displayed in the browser.  Your example creates a `div` node that is not part of any DOM, and so MathJax can't process it properly, and as a result, you are not getting the fully typeset result.  If you do

``` js
var mathbox = document.createElement('div'); 
document.body.append(mathbox);
mathbox.innerHTML='$$\\sum_x^33$$'
MathJax.Hub.Queue(
  ['Typeset', MathJax.Hub, mathbox, () => {console.log('callback', mathbox.innerHTML);}],
  ["PreProcess",MathJax.Hub],
  ["Delay",MathJax.Callback,5000],
  ["Process",MathJax.Hub],

  [() => {console.log('queue-next', mathbox.innerHTML);}]
);
console.log('outer', mathbox.innerHTML)
```

you should get the proper result for both the `callback` and `queue-next` output.  Note, however, that the `outer` output may or may not produce the correct result, as the commands that follow the `MathJax.Hub.Queue` call may run *before* the code in the queue itself, and that depends on both what may already be in the queue, as well as what browser you are using and on what OS. 

For example, the `outer` result for me is the original un-typeset TeX, because in my web page, the initial typeset run hasn't been performed yet when I make the `MathJax.Hub.Queue()` call, and so the commands following the `MathJax.Hub.Queue()` command are performed before the ones that you are pushing onto the queue.  Note that the `output` result is shown *before* the output for the other callbacks, indicating that the `console.log()` function is running *before* the items that have been added to the queue.  The `Typeset` command includes some delays (as so the `PreProcess` and `Process` commands, as well as your own `Delay` command) and so the code following the `MathJax.Hub.Queue()` will definitely run before MathJax can completed the `Typeset` command.

In any case, adding the `div` to the page will allow MathJax to complete the processing properly, and your `queue-next` result should be correct, and you can not rely on the `outer` output, as it will run before the queued commands are completed.

Note that I also doubled the backslash in the TeX code when you set the `innerHTML` so that an actual backslash will be part of the string, as backslashes are escape characters in Javascript string literals.

**Comment by scruel** [comment]
Ok, All I want is to get the correct result for `callbak` and `queue-next`, for `outer` part, it's excepted and fine for me.
For the backslash, it's a little mistake while I wrote this case, hope you don't mind, and thanks for your kindly reminder~
Thanks!
