### ISSUE TITLE
Uncaught Error: MathJax retry

### ISSUE THREAD

**Issue by scruel** [mathjax/MathJax#2932]
### Issue Summary

Seems that first render will always get error for some special equations.

### Steps to Reproduce:

1. Open browser console
2. Type and execute:
```js
MathJax.tex2chtml('\\color{#FF0000}{x^2}')
```
4. You will get the following error message:

```
Uncaught Error: MathJax retry
    retryAfter http://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    g http://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    p http://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    parse http://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    parse http://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    parse http://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    controlSequence http://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    parse http://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    parse http://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    parse http://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    Parse http://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    t http://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    compile http://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    compile http://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    m http://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    renderConvert http://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    convert http://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    convert http://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    i http://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js:1
    <anonymous> debugger eval code:1
```
5. After error shows, repeat step 2 again, you will not get same error message anymore.

Refresh the page, then if you type `MathJax.tex2chtml('x^2')`, then you will not get any error even for your first call.

### Technical details:

* MathJax Version: 3.2.2
* Client OS: Windows 10
* Browser: Firefox 105, Edge 105

I am using the following MathJax configuration:

DEFAULT CONFIGURATION

and loading MathJax via

``` html
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
```

**Comment by RootofalleviI** [comment]
Hi all, just curious, do we have any updates on this issue? I'm also getting the 
```
tex-chtml.js:1 Uncaught Error: MathJax retry
``` 
issue.

**Comment by dpvc** [comment]
Sorry, it looks like I never answered the original post.

MathJax sometimes needs to load extensions dynamically when they are needed.  For example, the `\color` macro is in the `color` or `colorv2` extension, and that is loaded only when `\color` is used for the first time.  Because loading extensions is asynchronous (MathJax must wait for the code to be sent from the server), MathJax stops processing the expression and waits until the extension is loaded and then retries rendering the expression again.  The `MathJax retry` exception is part of the mechanism MathJax uses to do that.  The `MathJax.tex2chtml()` and similar functions are synchronous ones, which don't know how to wait for extensions to load, and so the retry mechanism is not being handled and you see this as an error.

There are two ways to avoid this.  First, you could preload all the extensions you expect may be used.  So including the `[tex]/color` or `[tex]/colorv2` extension in the `loader.load` array of your Mathjax configuration would resolve this particular problem, but there are other auto-loaded extensions as well.  Using `tex-mml-chtml-full.js` rather than `tex-mml-chtml.js` would load most of the TeX extensions up front, and would resolve this problem, at the expense of requiring a larger initial download that includes things that may not be used.

The second approach is to use the `MathJax.tex2chtmlPromise()` function instead, which is an asynchronous function that handles the details of waiting for extensions to load.  But since it is asynchronous, you may have to modify your code to handle that asynchronous promise properly.  That could be through `await MathJax.tex2chtmlPromise()`, making the function that includes this be asynchronous itself, or via `MathJax.tex2chtmlPromise(...).then((node) => {...})`.  In either case, the processing is no longer synchronous, so you have to take that into account.

**Comment by RootofalleviI** [comment]
Thank you very much for your reply. Replacing tex-chtml.js by tex-chtml.full.js solved the problem.
