### ISSUE TITLE
Single and Double quote doesn't render properly

### ISSUE THREAD

**Issue by DerivedSkill** [mathjax/MathJax#2941]
### Issue Summary
I've tried [this link](https://www.mathjax.org/#demo) to view a latex equation. Which does not render properly, it rendered like [this](https://drive.google.com/file/d/12bgc5AZV2UDke6lRFlLTKG2A0yGcV0TT/view?usp=sharing), but it should render like [this](https://drive.google.com/file/d/1_rqn-HI9Yv_XeTs5mTvYpxzXFuk-mM9Z/view?usp=sharing).
I've also tried using MathJax version 3 by using below cdn, same things also happen there.

``` html
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
```

The latex was: ‘P’ f"

### Steps to Reproduce:

1. Use above mentioned CDN.
2. Render $‘P’ f"$ this latex.

### Technical details:

* MathJax Version: 3
* Client OS: Windows 10
* Browser: Firefox, Chrome, Microsoft Edge

### MathJax Configuration:
MathJax = {
    chtml: {
        mtextInheritFont: true, 
    }
};

``` html
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
```

**Comment by dpvc** [comment]
Sorry for the long delay in getting back to you; my fall teaching schedule left little room for MathJax questions, I'm afraid.

Your image for the "correct" rendering is not what LaTeX actually produces for `‘P’ f"` in math mode, which is 

<img width="162" alt="primes" src="https://user-images.githubusercontent.com/432782/206792131-65c96c4d-ae46-433a-80c3-964081f84573.png">

Note that the `’` is rendered as a prime symbol, not a quotation mark, in particular, and that is also the case for MathJax.

Because quotation marks are not common in mathematical notation, and because a number of text editors convert `'` and `` ` `` into "smart quotes" `‘` and `’` automatically,  MathJax processes these smart quotation marks as primes and back-primes, and the double quotes as double-primes.  This makes more sense for mathematical notation in most cases. 

The back-prime and double-prime characters are meant to be used within superscripts, and so the characters available for them are larger and on the baseline, and when used as a superscript, they are reduced in size and raises, as any superscript is.  In version 3.2.2 and earlier, the fonts do not include smaller and raised versions of these characters that could be used outside of superscripts, as in your expressions.  (One would need to use `^‘P’ f^"` to get the desired superscript effect.)  In version 4.0 (currently in alpha release) the fonts do include the needed characters to handle both the non-script and superscript versions of these characters, so the `^` will not be needed in the future.

Note, however, that the `'` character is treated specially in both LaTeX and MathJax in that it produces a superscript automatically, so there is no need for `^` in that case.

It is possible to disable the automatic conversion of `‘` and `"` if you wish, using the configuration

``` js
MathJax = {
  startup: {
    ready() {
      //
      //  Don't remap some of the prime-like characters
      //
      const {MmlMo} = MathJax._.core.MmlTree.MmlNodes.mo;
      MmlMo.remapPrimes[0x0022] = 0x0022;  // don't remap double quote
      MmlMo.remapPrimes[0x2018] = 0x2018;  // don't remap smart open quote
      //
      // Do the rest of the usual startup
      //
      MathJax.startup.defaultReady();
    }
  }
}
```

It would be possible to disable the processing of `'` as well, but that is harder, since it is a special character in LaTeX.  I don't recommend doing that, as that would make the output not the same as what LaTeX produces.
