### ISSUE TITLE
async in script breaking the equation

### ISSUE THREAD

**Issue by DerivedSkill** [mathjax/MathJax#2946]
### Issue Summary

I've tried to render two equation in same page mentioned in below code. When I use async like `<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>` No 1 equation got broken, but no. 2 equation renders perfectly.

When I don't use async like `<script id="MathJax-script" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>` No 2 equation got broken, but no. 1 equation renders perfectly.

HTML Code:
``` HTML
<ul type = "1">
    <li><span class="math-tex">\({\underset{\begin{matrix}|\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \\CH-N{O}_{2}\ \ \ \ \ \ \ \ \\|\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \\{CH}_{2}-N{O}_{2}\ \ \ \ \ \ \ \ \ \\\end{matrix}\ }{{CH}_{2}-N{O}_{2}}}\ \)</span></li>
    <li><span class="math-tex" style="font-family: Cambria Math !important;">\(\text{ট্রান্সক্রিপশন}\) </span></li>
</ul>

<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
<script>
    MathJax = {
        chtml: {
            mtextInheritFont: true,
        }
    };
</script>
```

### Steps to Reproduce:

1.  Run above mentioned html with async and without async

### Technical details:

* MathJax Version: 3
* Client OS: Windows 10
* Browser: Firefox, Chrome, Microsoft Edge

**Comment by dpvc** [comment]
The configuration script should come **before** the script that loads `tex-mml-chtml.js` so that it is in place when MathJax starts up (see the [documentation](https://docs.mathjax.org/en/latest/web/configuration.html#configuration-using-an-in-line-script).  Without the `async` attribute, the configuration script will definitely be too late, and the `mtextInheritFont` configuration will not occur, so the second one will certainly not render properly.  With the `async` attribute, you might get away with the configuration following it, but there is no guarantee.  It works for me, but I'm not using Windows.

Try moving the configuration script to its correct location before the `tex-mml-chtml.js` script so you are sure it gets properly processed.

**Comment by DerivedSkill** [comment]
After moving configuration **before** the script that loads `tex-mml-chtml.js`, `mtextInheritFont` applies perfectly. But the first equation still have extra space in middle line. I think the problem is with `mtextInheritFont`, when it applies then the extra space appear in first equation. When I compared the html generated by MathJax, I found [https://drive.google.com/file/d/1CWLXURqsGHJB5uAW3hydXPyhz8SwLxdi/view?usp=sharing](this) difference, you may know better if it's for `mtextInheritFont` or other.

I've tried it with **ubuntu 20.04.1 LTS**, same things also happen on there.
[https://drive.google.com/file/d/1YPfdK-hdtnJKWI0YBeLFa4kZnGCVqxJa/](Space problem image)

**Comment by dpvc** [comment]
The differences are due to the font inheritance, yes, but they are correct and not something to worry about.

> But the first equation still have extra space in middle line

This is due to the fact that you are trying to use spaces on the right to force the expression to be justified on the left.  That is not a very practical way to get the result you want.  You could use `\hfill` in place of the spaces to left-justify the entries in the matrix, or you could use the `array` environment instead of `matrix` as `\begin{array}{l}` so that the entries are left justified.  Using spaces for this is just a really bad idea.

**Comment by DerivedSkill** [comment]
By using \begin{array}{l} I'm able to fix the problem, Thanks a million for your help.
