### ISSUE TITLE
Erroneous Subscript Rendering on a Github Repo Wiki

### ISSUE THREAD

**Issue by duwudi** [mathjax/MathJax#2953]
### Issue Summary

When using certain combinations of LaTex commands on a Github repo Wiki page, subscripts fail to render (the text is instead  rendered as normal full-size text). This issue seems to be only present when using MathJax through a Github Wiki page, if there is a better place I should be posting this report, please let me know.

### Steps to Reproduce:

These all work as expected:

A_1

A_1 = B_1

A_{1,2} = B_{1,2}

Image of above:

<img width="88" alt="2022-10-20 21_03_03-Editing Luenberger Observer · Proton-Motor_PFD-Motor-Core Wiki" src="https://user-images.githubusercontent.com/58126123/197091034-cbbafc07-d63f-48b7-a997-f2a83c4e2e14.png">

When `\hat{}` is added to the first variable, subscripts are ignored and simply rendered as normal text:

\hat{A}_{1,2} = B_{1,2}

\hat{A}_{1,2}B_{1,2}

Image of above:

<img width="95" alt="2022-10-20 21_08_15-Editing Luenberger Observer · Proton-Motor_PFD-Motor-Core Wiki" src="https://user-images.githubusercontent.com/58126123/196957325-157641a4-2d6b-4d5b-8c2d-b18d0daa879e.png">

These examples also render as expected:

A_{1,2} = \hat{B}_{1,2}

\hat{A}_{1,2}

\hat{A}_{1,2}B_1

Image of above:

<img width="93" alt="2022-10-20 21_08_19-Editing Luenberger Observer · Proton-Motor_PFD-Motor-Core Wiki" src="https://user-images.githubusercontent.com/58126123/196957357-a4385fc1-93d6-49f7-9e74-431c42bdec32.png">

### Technical details:

* MathJax Version: Can't find the version, just using on a Github repo's Wiki page
* Client OS: Windows 10
* Browser: Chrome Version 106.0.5249.119 (Official Build) (64-bit)

I don't know the MathJax configuration.

### Supporting information:

I rendered the two failed examples [here](https://saxarona.github.io/mathjax-viewer/), and they work as expected:

<img width="76" alt="2022-10-20 21_09_38-MathJax Viewer" src="https://user-images.githubusercontent.com/58126123/196957703-9e775cce-b019-48ba-afb5-1c648d5fef79.png">
<img width="65" alt="2022-10-20 21_09_55-MathJax Viewer" src="https://user-images.githubusercontent.com/58126123/196957716-21d1b03d-f0fe-44ba-9a3b-6c8bfddf966e.png">

**Comment by dead-claudia** [comment]
Opened a feedback discussion in the GitHub Community forum about this, as I ran into a similar issue with a different macro: https://github.com/orgs/community/discussions/36984

Can't reproduce this in isolation with the MathJax version GitHub is currently using, FWIW, so there's some sort of non-default config they're setting here that I'm not sure about.

**Comment by dpvc** [comment]
This is an issue with how GitHub has hooked Mathjax into its Markdown processing.  Since Markdown uses underscores to indicate italics, it removes them and inserts HTML tags that produce italics.  MathJax doesn't process math that contains HTML tags.  If you look carefully at the "normal text" that you pasted into your report, you will see that the underscores are missing, and that the text between them are in italics.  That is why the math isn't being processed.

GitHub's implementation of MathJax tries to prevent the LaTeX from being processed by Markdown, but unfortunately, they didn't cover all the needed cases, and there are a number of bugs like this.  A workaround is to use `\_` rather than `_` so that Markdown won't process the underscores, but if GitHub ever fixes the problem, you might end up with explicit underscores in your math.

See [my response](https://github.com/community/community/discussions/36984#discussioncomment-3981018) to one of the bug reports in the GitHub discussions area.

**Comment by duwudi** [comment]
@dead-claudia glad someone else is seeing similar issues, thanks for letting me know! 

@dpvc thanks a lot, that makes complete sense - can't believe I didn't notice the italics! I'll use your workaround for now 👍
