### ISSUE TITLE
Github Mathjax chokes on the expression $g^{\frac {p-1} {{p_i}^{n_i}}}$ 

### ISSUE THREAD

**Issue by RisenCrypto** [mathjax/MathJax#2971]
### Issue Summary

Github Mathjax chokes on the expression `$g^{\frac {p-1} {{p_i}^{n_i}}}$`  in the build phase.

### Steps to Reproduce:

Use the expression `$g^{\frac {p-1} {{p_i}^{n_i}}\$`  in a github page where you import Mathjax. The page errors out while building.
This is the build error I get.

```
github-pages 227 | Error:  Liquid syntax error (line 3): Variable '{{p_i}' was not properly terminated with regexp: /\}\}/
```

### Technical details:

* MathJax Version: Latest
Client & Browser version aren't relevant because this is a build issue.

I am using the following MathJax configuration:

``` js
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    tex2jax: {
      inlineMath: [ ['$','$'], ["\\(","\\)"] ],
      processEscapes: true
    }
  });
```

and loading MathJax via

``` html
</script>

<script type="text/javascript" charset="utf-8" src="[https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML](view-source:https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML)">
</script>

<script type="text/javascript" charset="utf-8" src="[https://vincenttam.github.io/javascripts/MathJaxLocal.js](view-source:https://vincenttam.github.io/javascripts/MathJaxLocal.js)">
</script>

```

### Supporting information:

1) When you save the page in github, the github preview renders it fine without errors. However when the page builds, it errors out.

2) There is a simple workaround to fix this - If you use `$g^{\frac {p-1} {p_i^{n_i}}}$` instead of `$g^{\frac {p-1} {{p_i}^{n_i}}}$`, it no longer chokes, but the other form also shouldn't choke.

**Comment by dpvc** [comment]
As you point out, this is a build issue; MathJax isn't involved until the page is viewed in a browser, so it is not a MathJax problem, and there is nothing MathJax can do about it.

It appears that the Liquid Template for GitHub pages uses `{{ variable }}` to insert the value of a variable into your output, so that is conflicting with the use of braces in LaTeX notation.  The `{{` at the beginning of `{{p_i}...` is being picked up by the Liquid template as an attempted variable reference that isn't closed properly by `}}` since the next brace is a single brace.  You will need to either protect the braces in the math (perhaps via `\{`) or do something like insert spaces so that you have `{ {` rather than `{{` (I haven't tested either of those suggestions).

In any case, it is something that must be dealt with at the template level, as it occurs long before MathJax itself is involved.
