### ISSUE TITLE
[TeX] grouping of space-separated digits

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#2978]
The following is perhaps intentional (or unavoidable) but I wanted to double check.

Something like `$196 884 q + 21 493 760 q^2$` leads to 1 element per block of digits. SRE treats the separate blocks of digits as implicit multiplication, leading to incorrect non-visual presentation.

**Comment by dpvc** [comment]
The TeX input jax has a configuration option that lets you specify how numbers are to be parsed.  The default does not provide for space-separated digits, only bracketed commas (so that `196{,}884` would be read as a single number).

You can set that option to allow for space separation.  For example

``` js
MathJax = {
   tex: {
     digits: /^(?:[0-9]+(?:(?: |\{,\})[0-9]{3})*(?:\.[0-9]*)?|\.[0-9]+)/
  }
}
```

would allow for `21 493 760` to be read as a single number.  That would produce `<mo>21 493 760<mo>` as a single element.  The spaces will still be in the SRE output, but I suppose one could use a MathML post-filter to remove spaces within mo elements if that was a problem.

**Comment by pkra** [comment]
Thanks for clarifying.

**Comment by pkra** [comment]
@dpvc I was coming back to this, wanting to adopt the change but when testing it, I realized the pattern you shared seems to do the opposite of what I want (and how I understood your message).

I.e., `$123 456$` now renders visually with space in between the "blocks" and non-visually as multiplication of the blocks. What I was after is the opposite - 123456 and as one number non-visually.

Looking at the source, I'm guessing digit() might be to blame

https://github.com/mathjax/MathJax-src/blob/8565f9da973238e4c9571a86a4bcb281b1d98d9b/ts/input/tex/ParseMethods.ts#L71

it strips `{}` but not the space. So I'm guessing I'd have to adjust that, too.

**Comment by pkra** [comment]
Also the `{3}` in the regexp is probably not ideal for what I'm after. I have things like `(n)_2 = 1 0^n x` which I'd like to fix.

Maybe I should just fix the TeX source instead (either as a pre-processor or just in the publications).

**Comment by pkra** [comment]
> Looking at the source, I'm guessing digit() might be to blame

A quick test (using `/[{} ]/g`) seems to confirm this.

**Comment by pkra** [comment]
Thanks, I went with some TeX pre-processing. 

FWIW, I still think it is a bug to have visually grouped digits come out as implicit multiplication of groups of digits. From the content we have, it's simply not how authors use space between blocks of numbers.

**Comment by dpvc** [comment]
> `$123 456$` now renders visually with space in between the "blocks" and non-visually as multiplication of the blocks. 

I'm not sure I understand what you mean by non-visually as multiplication of the blocks.  If you mean that SRE is adding an invisible times, I'm not able to reproduce that.  Can you be more explicit about what is happening for you?

If you mean that is what happens without the `digits` pattern being changed, then yes, that is what would happen.  But with the `digits` pattern in place (so that you end up with `<mo>123 456</mo>` I'm not seeing any multiplication either with or without SRE.
