### ISSUE TITLE
How can I add Safe Extension Options in vue?

### ISSUE THREAD

**Issue by jgao1025** [mathjax/MathJax#2982]
Hi,

I have been stuck this issue for a long time and I am really new to vue. I can't find any similar example online so I am asking here.

The code is like this.

```
<script>
...
import 'mathjax/es5/tex-svg';
...

export default {
...
  computed: {
    code() {
      const parsedCode = this.rawCode.replace(/\$\$/g, '');
      const svg = window.MathJax.tex2svg(parsedCode);
      return svg.outerHTML;
    },
  },
...
};
</script>

<template>
  <div class="output">
    <prompt type="Out" :count="count" :show-output="index === 0" />
    <div ref="maths" v-safe-html:[$options.safeHtmlConfig]="code"></div>
  </div>
</template>

```

I have tried to add ` window.MathJax = { loader: {load: ['ui/safe']}, }; ` in the following place.
1. add `window.MathJax = { loader: {load: ['ui/safe']}, };` in beforeCreate() lifecycle
2. add `window.MathJax = { loader: {load: ['ui/safe']}, };` in beforeMount() lifecycle.
3. search "[es5/tex-svg](https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js)" in the code base to find where it is loaded. The only location is this vue file on the top `import 'mathjax/es5/tex-svg';` Then I try to add `window.MathJax = { loader: {load: ['ui/safe']}, };`  before import mathjax
4. try to add it in the template. got an error.

So far I can't work out where I can put this option. I know it is probably not too much related to mathJax but just try my luck here.

Thanks for reading it.

\label quesiton

**Comment by dpvc** [comment]
You want to configure and load MathJax only once, so your `window.MathJax = { loader: {load: ['ui/safe']}, };` needs to go in a place where it is only performed once, and it should occur before MathJax itself (via `tex-svg.js`) is loaded.

Your suggestions for (1) and (2) will likely wipe out the `MathJax` variable that was set up when `tex-svg.js` is loaded, and will lead to error messages about `window.MathJax.tex2svg` no being defined or not being a function.

Your (3) is likely the approach that will work, but because `import` commands are performed before any of the other code in a module, regardless of the order in which they appear, you can't just insert the configuration before the `import` for `tex-svg.js`.  Instead, you need to put your configuration into a separate file, and `import` that file by placing the `import` command before the one for `tex-svg.js`.

**Comment by jgao1025** [comment]
Hi Davide,

Many thanks for the information. Unfornately, although your suggestion really seems correct but it doesn't work for vue after I tested it. I will ask the owner who raised this issue and see if they have any idea on that. I would update the solution here once I got the answer or the issue can be closed.

Thanks again for the help.

**Comment by dpvc** [comment]
Please let us know if you find anything out.

**Comment by jgao1025** [comment]
A small update: I put more logs to debug and find out that adding a separate file might work. MathJax is still loaded unsuccessfully but this is because it can't find `ui/safe.js`.  Somehow it searched path at `https://site.com/assets/webpack/ui/safe.js` .  I am still unsure how webpack works with vue.

**Comment by dpvc** [comment]
You didn't mention you were web packing your result.  In that case, `ui/safe.js` will ;not be included in the packed application, and will need to be loaded from the CDN (as it would be if you used the configuration directly in a web page.  But MathJax won't know where to look for the CDN, since it gets it root location from the URL from which it was loaded.  You would need to configure the MathJax root to be the CDN from which you want to load other components (like `ui/safe.js`).  So you could include

``` js
window.MathJax = {
  loader: {
    load: ['ui/safe'],
    paths: {
      mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5'
    }
  }
};
```
 
for example so that MathJax will look for `ui/safe.js` (and any other needed components) from the jsdelivr CDN.

Alternatively, you can include `ui/safe.js` into your app directly by making a custom MathJax component that includes everything you need so that it is all pre-loaded.  See the [custom component](https://github.com/mathjax/MathJax-demos-web/blob/master/custom-component/custom-component.html.md) example from the [MathJax web demos](https://github.com/mathjax/MathJax-demos-web) for how that works.

**Comment by jgao1025** [comment]
> 

@dpvc OHHH. YES! that was the issue(⊙⊙). I have been stuck for this question for so long time, but now I start to get some idea on this.  Thanks so so much for supporting this issue. Have a nice day.

**Comment by jgao1025** [comment]
@dpvc FYI the issue that I am working on is this. I was thinking to reference it after it is merged but it might take longer time than I expected.

[1]. https://gitlab.com/gitlab-org/gitlab/-/merge_requests/105503
