### ISSUE TITLE
TeX input: `{}` inside `\textrm`

### ISSUE THREAD

**Issue by hbghlyj** [mathjax/MathJax#2989]
`\textrm{{}d}` produces `{}d` which is not consistent with real TeX (link to [texlive.net](https://texlive.net/run?%5Cdocumentclass%7Barticle%7D%0A%5Cbegin%7Bdocument%7D%0A$%5Ctextrm%7B%7B%7Dd%7D$%0A%5Cend%7Bdocument%7D))

**Comment by dpvc** [comment]
Because MathJax is primarily concerned with typesetting mathematics, it does not implement TeX's text-mode processing.  So the contents of `\text{}` is presented verbatim, other than embedded mathematics (e.g., `\text{for $x > 1$}`).

MathJax v3 has a [`textmacros` extension](https://docs.mathjax.org/en/latest/input/tex/extensions/textmacros.html) that allows processing of some macros in text mode, so if you are using version 3, you can load that, and it will handle the example you provide.
