### ISSUE TITLE
Bug: spacing in math align environment is incorrect for equal sign and minus sign

### ISSUE THREAD

**Issue by haucheefa** [mathjax/MathJax#2997]
### Issue Summary

In LaTeX align math environment and some other similar environments, space after equal sign and spaces around minus sign are set incorrectly.

### Steps to Reproduce

1. In MathJax demo https://www.mathjax.org/#demo, enter this example:
```
We have incorrect spacing here when we use align:
\begin{align}
a = & b \\
c = & -d \\
\end{align}

Compare to correct spacing when we use eqalign in plain math
\[ \eqalign{
a = & b \\
c = & -d \\
} \]
```

This is a bug for `align` because (1) there is no proper space between `=` and `b` in the first line, and (2) there is too much space between `-` and `d` in the second line.  The correct behavior is demonstrated with `eqalign` in plain math mode.

### Technical details

* MathJax Version: 3.2.2 (latest commit:  600692ad9d3552cc25f85510d5797bc942ecc9f7)
* Client OS: Linux 5.15.0-58-generic
* Browser: Firefox 109.0.1 (64-bit)

**Comment by dpvc** [comment]
The rendering you are seeing for your first example is actually correct.  Here is the output from actual LaTeX for your `align environment:

<img width="164" alt="latex output for align environment" src="https://user-images.githubusercontent.com/432782/216788238-bc9a9b22-b2a9-4ef8-8146-b7fcf2e5fa7b.png">

which is what MathJax is rendering as well.  Here is MathJax's output for the same expression:

<img width="139" alt="MathJax version of the align expression" src="https://user-images.githubusercontent.com/432782/216788269-665de382-5e40-466e-bad8-085664c103a1.png">

The reason is that you are not putting the ampersands in the correct place.  The proper expression would be

``` latex
\begin{align}
a &=  b \\
c &= -d
\end{align}
```

which renders as

<img width="145" alt="proper use of align environment" src="https://user-images.githubusercontent.com/432782/216788361-a9cab01b-b210-4398-b526-f6e16d00f3e4.png">

On the other hand, MathJax's rendering of your second expression is actually incorrect, at is should render like the first one.  Again, this is because the ampersands should precede the equal signs.

**Comment by haucheefa** [comment]
Thanks very much for your reply.  I agree with your conclusion.  When the right-hand side of equation is very long and I want to split it into multiple lines, I do want to put the ampersand to the right of equal sign so that all lines of the right-hand side are displayed to the right of the equal sign.  After some searching online, I find that I can achieve the correct spacing with ampersand to the right of equal sign by adding dummy tokens:
``` latex
\begin{align}
a = {} & b \\
c = {} & {-d} \\
f = {} & 1 + 2 + 3 + 4 \\
& + 5 + 6 + 7 + 8 \\
& + 9 + 10
\end{align}
```
This achieves the spacing that I want.  Thanks for your help!

**Comment by dpvc** [comment]
I'm glad you found something that works for you.  The usual approach to this is to still use the `&` before the `=`, but to add an explicit space at the beginning of the continuation lines.  E.g., 

``` latex
\begin{align}
a &= b \\
c &= -d \\
f &= 1 + 2 + 3 + 4 \\
&\hspace{1em} + 5 + 6 + 7 + 8 \\
&\hspace{1em} + 9 + 10
\end{align}
```

or

``` latex
\begin{align}
a &= b \\
c &= -d \\
f &= 1 + 2 + 3 + 4 \\
&\phantom{={}} + 5 + 6 + 7 + 8 \\
&\phantom{={}} + 9 + 10
\end{align}
```
 if you want exactly the amount of space for the equal sign.  If course, you can define a macro that makes these easier:

``` latex
\newcommand{\=}{\hspace{1em}}
\begin{align}
a &= b \\
c &= -d \\
f &= 1 + 2 + 3 + 4 \\
&\= + 5 + 6 + 7 + 8 \\
&\= + 9 + 10
\end{align}
```

or use `\newcommand{\=}{\phantom{={}}}` or use whatever spacing works best for you.  This is less complicated that adding the extra braces on all the lines that aren't broken, and around leading minus signs.  Just use `&\=` for the beginning of any continuation line and that is it.

The macro only has to be defined once, and you can add it to the `macros` list in the `tex` block of your Mathjax configuration.  See the [configmacros](https://docs.mathjax.org/en/latest/input/tex/extensions/configmacros.html) documentation.

**Comment by haucheefa** [comment]
Thank you!  These are great suggestions.
