### ISSUE TITLE
Mathjax conversion doesn't work properly for some formulas.

### ISSUE THREAD

**Issue by JoonsuRyu** [mathjax/MathJax#3007]
### Issue Summary

Mathjax conversion doesn't work properly for some formulas.

### Steps to Reproduce:

1. I'm building a github page built using Jekyll. (and Minimal-mistakes theme)
2. I'm trying to enter formulas using Mathjax, but I'm having a problem with some formulas not being converted.
3. After checking them one by one, I found that formulas containing curly brackets were not converted properly.

For example, 
```
\mathbf{w} 
```

prints fine, but like 
```
\mathbf{w}_{N-1} 
```
don't.

I don't know what's causing the problem, could you tell me how to fix it?

### Technical details:

* MathJax Version: 2.7.5
* Client OS: Windows 10 21H2 (19044.2604)
* Browser: Chrome 110.0.5481.178 (64 bit)

I am using the following MathJax configuration:

``` 
<script type="text/javascript" async
	src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-MML-AM_CHTML">
</script>
```

and loading MathJax via

``` 
<script type="text/x-mathjax-config">
   MathJax.Hub.Config({
     extensions: ["tex2jax.js"],
     jax: ["input/TeX", "output/HTML-CSS"],
     tex2jax: {
       inlineMath: [ ['$','$'], ["\\(","\\)"] ],
       displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
       processEscapes: true
     },
     "HTML-CSS": { availableFonts: ["TeX"] }
   });
</script>
```

### Additional information (Screenshots and links)

https://joonsuryu.github.io/studies/theory-of-generalization/

![1](https://user-images.githubusercontent.com/35926730/220823019-ffa3fa5c-e18f-480a-94c8-de43a4375aab.PNG)

https://joonsuryu.github.io/studies/bias-variance-tradeoff/

![2](https://user-images.githubusercontent.com/35926730/220823026-997e3949-f308-4b45-83cf-633959e67bef.PNG)

**Comment by dpvc** [comment]
It's not the braces that are the problem it is the underscores.  Markdown uses underscores to indicate italics (notice how the `{1} ~ \mathbf{x}` in your screen shot is in italics — this is the math between two underscores), and that means that your page will have `<i>` tags or some other markup within the mathematics.  MathJax does not process math that contains HTML tags, so that math is not being typeset.

One solution is to use `\_` rather than `_` in your equations, as that will prevent Markdown from processing them, and they will be sent to MathJax as plain underscores.

Because the markdown is processed before MathJax sees the page, there is nothing MathJax can do about it. It has to be handled by the markdown engine. My understanding is that kramdown (one of the Markdown engines) is supposed to properly handle this, but I don't have any experience with it myself. There are several tutorials for MathJax in kramdown, so consider [this one](11011110.github.io/blog/2019/10/17/mathjax-3-jekyll.html) or [this one](talk.jekyllrb.com/t/jekyll-and-mathjax/5514) for more. There seem to be various settings to control the handling of math, so you may need to set one of those.

**Comment by JoonsuRyu** [comment]
Thank you!
I sincerely appreciate your help in resolving this problem.
