### ISSUE TITLE
MathJax exceeds container width without wrapping in Obsidian

### ISSUE THREAD

**Issue by carterchannui** [mathjax/MathJax#3020]
### Issue Summary

MathJax exceeds container width without wrapping in Obsidian.

### Steps to Reproduce:

1. Create MathJax embed in Obsidian
2. Write on a single line until it visually exceeds container width.

### Technical details:

* MathJax Version: 3.2
* Client OS: macOS Ventura 13.2.1
* Browser: Obsidian

### Supporting information:

![image](https://user-images.githubusercontent.com/26908609/225087705-143f1ad3-2575-4d58-9d4d-eadcdc89880e.png)

> I believe this is a MathJax thing: 
> https://docs.mathjax.org/en/latest/output/linebreaks.html
> > Automatic line breaking has not yet been implemented in MathJax version 3, but is high on our list for inclusion in a future release.
> 
> MathJax isn't great and lack features, which is why I made this plugin to begin with; but I certainly did not expect it to not even have any kind of automatic line breaking.
> 
> There might be some workaround by manipulating the CSS, but I have not looked into it yet. I will let you know if I do find one.

_Originally posted by @SamZhang02 in https://github.com/SamZhang02/obsidian-latex-algorithms/issues/1#issuecomment-1467852283_

To render math from LaTeX notation Obsidian uses [MathJax](http://docs.mathjax.org/en/latest/basic/mathjax.html).
[https://help.obsidian.md/How+to/Format+your+notes#Math](url)

**Comment by dpvc** [comment]
This is unrelated to Obsidian itself.  As pointed out in the comment you quote, MathJax v3 does not do automatic line breaking, and so this is not a bug, it is the way MathJax works.  So do you mean this as a feature request, not a bug report?

MathJax v4 (currently in alpha release) does include line breaking, so that will be available soon (or you could try the alpha version now).

Note that MathJax implements TeX's math-mode typesetting, not its text-mode.  MathJax does have limited support for `\text{}` and other tex-mode material when it is used within a mathematical expression.  MathJax is not intended for typesetting sentences and paragraphs of text.  Although you don't include the original TeX for the image you provide, I can only assume that it is something like

``` latex
\textbf{Input:}\text{An array of $n$ sorted numbers $A$, number $x$, integers $min$, and $max$. (Initially $min = 0$ and $max = n-1$)}
```

or perhaps the plugin has different syntax for what amounts to this.

Note, however, that this is misusing MathJax to typeset textual information rather than mathematics.  Note also that TeX itself would not break the contents of the `\text{}` macro, so MathJax's output is consistent with that of actual TeX.

You quote the plug-in maintainer as saying "I certainly did not expect it to not even have any kind of automatic line breaking", but MathJax is doing exactly what TeX would do in this case (as it is supposed to do).  MathJax expects you to use normal HTML to handle the textual material on your page (not use `\text{}` for that), and have the browser handle the line breaking of that text, with MathJax handling the mathematical layout.

You also quote him as saying "MathJax isn't great and lack features".  I'm not sure how insulting the product is supposed to encourage us to give you (free) advice and support.  No one is forcing you (or him) to use MathJax, and if he doesn't like it, he could either implement TeX typesetting himself to suit his needs, use one of the other TeX-to-HTML implementations that are available, make a feature request to MathJax to include the features that he is interested in, or offer to contribute to the project by implementing those features himself.  But insults really don't help.
