### ISSUE TITLE
Requesting guidance on minimizing asset size in JupyterLab

### ISSUE THREAD

**Issue by dlqqq** [mathjax/MathJax#3021]
cc @fcollonval @jtpio @krassowski

Hello! I'm a contributor to JupyterLab and the author of [this PR](https://github.com/jupyterlab/jupyterlab/pull/13877) to upgrade JupyterLab's math renderer to use MathJax 3. For context, I am not the original author of the MathJax 3 extension; development was tracked in the [`jupyter-renderers`](https://github.com/jupyterlab/jupyter-renderers) repository up until now. I am, however, owning the migration and integration of the MathJax 3 extension into the JupyterLab core repository.

The original authors left some fairly opaque lines of code that appear to be remnants of an old MathJax 3 release. This is how the `MathDocument` object is being initialized (dynamic imports were added by me to improve initial load time):

```ts
protected async _ensureInitialized() {
  if (this._initialized) {
    return;
  }

  await import('mathjax-full/js/input/tex/require/RequireConfiguration');
  const { mathjax } = await import('mathjax-full/js/mathjax');
  const { CHTML } = await import('mathjax-full/js/output/chtml');
  const { TeX } = await import('mathjax-full/js/input/tex');
  const { TeXFont } = await import('mathjax-full/js/output/chtml/fonts/tex');
  const { AllPackages } = await import(
    'mathjax-full/js/input/tex/AllPackages'
  );
  const { SafeHandler } = await import('mathjax-full/js/ui/safe/SafeHandler');
  const { HTMLHandler } = await import(
    'mathjax-full/js/handlers/html/HTMLHandler'
  );
  const { browserAdaptor } = await import(
    'mathjax-full/js/adaptors/browserAdaptor'
  );

  mathjax.handlers.register(SafeHandler(new HTMLHandler(browserAdaptor())));

  class EmptyFont extends TeXFont {
    defaultFonts = {};
  }

  const chtml = new CHTML({
    // Override dynamically generated fonts in favor of our font css
    font: new EmptyFont()
  });

  const tex = new TeX({
    packages: AllPackages.concat('require'),
    inlineMath: [
      ['$', '$'],
      ['\\(', '\\)']
    ],
    displayMath: [
      ['$$', '$$'],
      ['\\[', '\\]']
    ],
    processEscapes: true,
    processEnvironments: true
  });

  this._mathDocument = mathjax.document(window.document, {
    InputJax: tex,
    OutputJax: chtml
  });
  this._initialized = true;
}

```

(the full file is viewable at the path `packages/mathjax-extension/src/index.ts` in the linked PR)

I have two questions:

1. Can we receive guidance on what the `SafeHandler`, `CHTML`, and `TeX` objects actually are, and whether it's necessary to instantiate these objects and pass them to `mathjax.document()` and `mathjax.handlers.register`? The imports that they depend on have a significant impact on the asset size. I have searched the official documentation, and it seems much of the library interface this code is using is undocumented. If these are not necessary, could you recommend an alternative that minimizes the size of the assets being dynamically imported?

2. Is it possible to use the `mathjax` package instead of `mathjax-full` while preserving type safety? [It seems that the latest version of the `mathjax` NPM package doesn't provide any type declarations](https://www.runpkg.com/?mathjax@3.2.2/es5/node-main.js). Is this intentional?

**Comment by dpvc** [comment]
> Can we receive guidance on what the `SafeHandler`, `CHTML`, and `TeX` objects actually are, and whether it's necessary to instantiate these objects and pass them to `mathjax.document()` and `mathjax.handlers.register`? 

The `SafeHandler` implements the `Safe` extension (see the [safe typesetting](https://docs.mathjax.org/en/latest/web/typeset.html#safe-typesetting) section of the documentation, and the link it includes the to configuration options for the safe extension).

The `TeX` object is the TeX/LaTeX input jax, which converts TeX and LaTeX input strings to the internal format (essentially MathML).  You need this if you want to process TeX/LaTeX strings.

The `CHTML` object is the CommonHTML output jax, which is what generates HTML output from MathJax's internal format.  You need this if you want to be able to produce HTML output.

Yes, you need to pass these to `mathjax.document()` and `mathjax.handlers.register()` if you want those functions (and yes, you want those function), though the usual way would be to use

``` js
  const { SafeHandler } = await import('mathjax-full/js/ui/safe/SafeHandler');
  const { RegisterHTMLHandler } = await import('mathjax-full/js/handlers/html');
  const { browserAdaptor } = await import('mathjax-full/js/adaptors/browserAdaptor');
  SafeHandler(RegisterHTMLHandler(browserAdaptor()));
```

>  it seems much of the library interface this code is using is undocumented

Yes, the Component-based usage is pretty well documented, but the lower-level direct-access method that you are using here is not, as you have found out.  We do hope to improve that in the future.  There are some examples in the [MathJax node demos](https://github.com/mathjax/MathJax-demos-node) repository (especially the `direct` subdirectory) that may be useful references.

> Is it possible to use the `mathjax` package instead of `mathjax-full` while preserving type safety?

Not if you are using direct calls to the MathJax modules.  The `mathjax` package contains the files needs for a CDN (or for a locally hosted web site) that uses MathJax Components, which is the standard way of using MathJax in a web page.  It does not contain the .js files (or the .d.ts files) that you need to use MathJax in the way you are doing, so you will have to use the `mathjax-full` package for that.

It would be possible to use MathJax Components rather than directly accessing the modules, which could allow you to use the `mathjax` package, but that requires the use of a global variable `MathJax` that would initially contain the configuration for MathJax; after loading MathJax, it would contain `MathJax.startup.document` that you could use for `this._mathDocument`.  Because MathJax can load components dynamically, however, if you wanted them to be included in your bundling, you would want to use a component that includes everything that you expect to use.  MathJax comes with a number of pre-build combined components that implement the common configurations (like `tex-chtml` and `tex-svg`), but since you are using the safe component and are using a customized `TeXFont` class, you would probably want to build your own custom combined component, and then import that into your project.  There is an example of this in the [MathJax web demos](https://github.com/mathjax/MathJax-demos-web#mathjax-demos-web), in particular the [custom component](https://github.com/mathjax/MathJax-demos-web/blob/master/custom-component/custom-component.html.md) example.  This example allows the page to include a custom `MathJax = {...}` configuration script, but you could build that into the component itself, or have the component augment the page's configuration (there are function to help with that in the `components/global.js` file) if you want to allow the page to modify the base configuration that you have built in.

> It seems that the latest version of the mathjax NPM package doesn't provide any type declarations. Is this intentional?

Yes.  The mathjax package contains only the webpacked component files for the CDNs to make available for websites that load and use MathJax in the usual way, not for those who are importing the mathjax modules directly.

**Comment by dpvc** [comment]
PS, the `tex-chtml-full.js` combined component (the one closest to what you are loading) is about 1.3MB.  If you roll your own with what you need, it should be around that size.

**Comment by fcollonval** [comment]
@dpvc thanks a lot for all the explanations and pointers

**Comment by dlqqq** [comment]
@dpvc Yes, thank you! Your input on the size of the `tex-chtml-full.js` component being 1.3 MB is good for setting a floor/target asset size. I did some testing and unfortunately the asset size appeared to be roughly 4.7 MB:

![image](https://user-images.githubusercontent.com/44106031/225656004-316e66be-c706-46cd-bb54-01058b644e77.png)

However, this was in a dev build, so I'll have to test this on a production build and get back to you on the asset sizes in a prod build.

**Comment by fcollonval** [comment]
@dlqqq I support @dpvc suggestion of packaging our own build.
