### ISSUE TITLE
Weird equation compiling error

### ISSUE THREAD

**Issue by sciarraseb** [mathjax/MathJax#3037]
The following equation does not compile when I render my post: 
```tex 
\begin{align}
\log L(\mathbf{\theta}|\mathbf{x}) &= \mathbb{E}_{P(\mathbf{z}|\mathbf{x}, \boldsymbol{\theta})}\log \Big(L(\mathbf{\theta}|\mathbf{x},\mathbf{z})\Big)  - \mathbb{E}_{P(\mathbf{z}|\mathbf{x}, \boldsymbol{\theta})}\log \Big(P(\mathbf{z}|\mathbf{x}, \boldsymbol{\theta})\Big).
\end{align}
```
Interestingly, the latex code does render in my IDE. 

<img width="374" alt="Screenshot 2023-04-21 at 9 27 07 AM" src="https://user-images.githubusercontent.com/85191660/233647806-db27b2a6-a370-4d47-9b5d-72e279fed29a.png">

Also interesting, if I remove either of the `\mathbb{E}_{P(\mathbf{z}|\mathbf{x}, \boldsymbol{\theta})}` terms,  the equation compiles.

**Comment by dpvc** [comment]
It renders for me, so it is probably an interaction with your content management system (CMS).  Is any of the un-rendered equation showing in italics, for example?  Markdown renderers often use underscores (`_`) to delimit italics, do if `{P(\mathbf{z}|\mathbf{x}, \boldsymbol{\theta})}\log \Big(L(\mathbf{\theta}|\mathbf{x},\mathbf{z})\Big)  - \mathbb{E}` is in italics (the stuff between two underscores), that might be the problem.

Otherwise, you should look at the page source (the actual page source in the browser, not your editor version), and check that there are no HTML tags in the middle of the math that have been inserted by the CMS.  That would be the other reason for the expression not being processed.

**Comment by sciarraseb** [comment]
Yes, `P(\mathbf{z}|\mathbf{x}, \boldsymbol{\theta})}\log \Big(L(\mathbf{\theta}|\mathbf{x},\mathbf{z})\Big) - \mathbb{E}{P(\mathbf{z}` is in italics . Is this solvable?

**Comment by dpvc** [comment]
Try using `\_` rather than just `_` in the two places they occur.

I don't know what CMS you are using, but if you do

```
$$
\log L(\mathbf{\theta}|\mathbf{x}) = \mathbb{E}_{P(\mathbf{z}|\mathbf{x}, \boldsymbol{\theta})}\log \Big(L(\mathbf{\theta}|\mathbf{x},\mathbf{z})\Big)  - \mathbb{E}_{P(\mathbf{z}|\mathbf{x}, \boldsymbol{\theta})}\log \Big(P(\mathbf{z}|\mathbf{x}, \boldsymbol{\theta})\Big).
$$
```
does it work (note the removal of the `&` in addition to changing from `\beign{align}...\end{align}` to `$$...$$`).

If that works, then it looks like the CMS only protects math within dollar sign delimiters, not `\begin...\end` delimiters.  In that case, you might be able to use

```
$$
\begin{align}
\log L(\mathbf{\theta}|\mathbf{x}) &= \mathbb{E}_{P(\mathbf{z}|\mathbf{x}, \boldsymbol{\theta})}\log \Big(L(\mathbf{\theta}|\mathbf{x},\mathbf{z})\Big)  - \mathbb{E}_{P(\mathbf{z}|\mathbf{x}, \boldsymbol{\theta})}\log \Big(P(\mathbf{z}|\mathbf{x}, \boldsymbol{\theta})\Big).
\end{align}
$$
```

to do it.

The other alternative would be to modify the plugin that you are using to handle `\begin...\end` delimiters as well.  You might need to contact the plugin author about that.

**Comment by sciarraseb** [comment]
Ok perfect! Yup, adding the `\` works. So in the end, the following modified latex compiles perfectly: 
```tex 
$$
\begin{align}
\log L(\boldsymbol{\theta}|\mathbf{x}) &= \mathbb{E}\_{P(\mathbf{z}|\mathbf{x}, \boldsymbol{\theta})}\log \Big(L(\boldsymbol{\theta}|\mathbf{x},\mathbf{z})\Big)  - \mathbb{E}\_{P(\mathbf{z}|\mathbf{x}, \boldsymbol{\theta})}\log \Big(P(\mathbf{z}|\mathbf{x}, \boldsymbol{\theta})\Big).
\label{eq:post-variation-inequality-exp}
\end{align}
$$
``
