### ISSUE TITLE
TeX -> MathML bug: consecutive "~"s result in a single mo

### ISSUE THREAD

**Issue by NSoiffer** [mathjax/MathJax#3043]
### Issue Summary
If the Tex input contains "\sim  \sim", the MathML output puts them both of them into a single `mo`. As with "++" and other operators, they should be in separate `mo`s.

### Steps to Reproduce:

1. Using https://mathjax.github.io/MathJax-demos-web/input-tex2chtml.html, enter `\sim  \sim T `
2. Click "Render TeX"
3. In the resulting output window, right click "show math as".

The result is:
```
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mo>&#x223C;&#x223C;</mo>
  <mi>T</mi>
</math>
```

The `mo` should be `<mo>&#x223C;</mo> <mo>&#x223C;</mo>`

### Technical details:

* MathJax Version: 3.2.2 and 4.0.0-alpha.1
* Client OS: (Windows 10)
* Browser: (Chrome and Firefox at least)

I also see the problem in my MathCATDemo using
```
<script id="MathJax-script" async="" src="https://cdn.jsdelivr.net/npm/mathjax@4.0.0-alpha.1/es5/tex-mml-chtml.js"></script>
```

**Comment by dpvc** [comment]
This is by design.  In TeX, there are two kinds of operators, binary operators and relations (and under certain conditions, a binary operator is converted to an ordinary symbol, making it act like a unary operator).  Two consecutive relations are treated as a single relation.  That way, things like `x : y :: a : b` are processed as three relations (not four), and `x := y` or `x == y` or `x << y` are treated as single relations.  MathJax mimics that behavior by combining adjacent relations into a single `mo` element.  This doesn't occur for `++` since those are binary operators, not relations.

Note that the spacing in TeX for `x \sim\sim y` is (from actual TeX)

<img width="210" alt="double sims with no space between in TeX" src="https://user-images.githubusercontent.com/432782/235325528-bfcf2018-e861-43b9-bfc5-130df594c6a4.png">

Your suggestion of `<math><mi>x</mi><mo>&#x223C;</mo><mo>&#x223C;</mo><mi>y</mi></math>` would produce 

<img width="163" alt="sims-mml" src="https://user-images.githubusercontent.com/432782/235325609-184ae550-a28c-4010-9901-74a5d3a21c6c.png">

in a MathML renderer (Firefox for this image), which is not the correct result for that TeX expression.

One could do

 ``` mathml
<math>
  <mi>x</mi>
  <mo rspace="0">&#x223C;</mo>
  <mo lspace="0">&#x223C;</mo>
  <mi>y</mi>
</math>
```

but this seems like "fiddly space adjusting" that the MathML spec recommends against.  And for something like `x := y`, needing to be 

``` mathml
<math>
  <mi>x</mi>
  <mo rspace="0">:</mo>
  <mo lspace="0">=</mo>
  <mi>y</mi>
</math>
```

is certainly semantically incorrect.  (It will also render in MathJax with slightly different spacing, since the presence of `lspace` or `rspace` will force MathML spacing for those `mo` elements, which is not quite the same as TeX spacing.)

You may disagree with the decision rho combine the relations, but it is designed to more accurately represent how TeX handles consecutive relations, and I stand by it.  If you wish to disable this feature, however, you can use

``` js
  MathJax = {
    startup: {
      ready() {
        const FilterUtil = MathJax._.input.tex.FilterUtil.default;
        MathJax.startup.defaultReady();
        MathJax.startup.input[0].postFilters.remove(FilterUtil.combineRelations);
      }
    }
  };
```

to remove the filter that replaces pairs of relations with a single `mo`.

**Comment by NSoiffer** [comment]
Thanks for the explanation. It make sense to follow TeX spacing rules, but it complicates some speech and braille rules for AT because the MathML differs from what other systems produce for the same input. Of course, there are _many_ , _many_ other cases of different input source generating different MathML for the same input.

FYI: MathML's operator dictionary contains 10 -15 double character sequences that correspond to standard programming language constructs such as `:=` and `==`. For those I would not expect separate `mo`s, but sadly some of the WYSIWG editors make them separate.

Unfortunately, I can't make use of `FilterUtil.combineRelations` because I'm consuming the MathML, not generating it. I'll have to think how best to deal with these. At least I know that this will happen in lots of other cases.

I'll close the issue.
