### ISSUE TITLE
Cannot set property Package of #<Object> which has only a getter     at a (tex-chtml-full.js:1:13801)

### ISSUE THREAD

**Issue by ss-zf-520** [mathjax/MathJax#3046]
![image](https://github.com/mathjax/MathJax/assets/47528311/57cc522a-2817-46bc-a917-3c0fb520a407)

![image](https://github.com/mathjax/MathJax/assets/47528311/7e3daa89-4dc7-43a3-a77d-2d59777ffe4b)

How did you handle it?

**Comment by dpvc** [comment]
When you start a new issue, there is a template for you to fill out that asks for the details of your situation.  You need to fill that out in order to give us the information needed to help you.  What you provide here is not enough.  I am closing this issue; please fill out a new one with the proper information.
