### ISSUE TITLE
The "\mathcal" symbol does not display properly in chromium-based browsers on macOS Ventura.

### ISSUE THREAD

**Issue by jianghao-zhang** [mathjax/MathJax#3050]
### Issue Summary

The "\mathcal" symbol does not display properly in Chrome-based browsers on macOS Ventura. See the image below:
<img width="1341" alt="image" src="https://github.com/mathjax/MathJax/assets/81921082/2f9f11e6-2674-44da-a92b-9222bb82c895">

### Steps to Reproduce:

1. Update to macOS Ventura;
2. Use any chromium-based browsers, e.g., Chrome, Arc;
3. Input "$\mathcal{G}$" in text blocks of any online notebook like Google Colab.

However, the "\mathcal" symbol can be properly displayed in Safari.

### Technical details:

* Client OS: macOS Ventura 13.4 Beta
* Browser: Arc, Chrome

**Comment by dpvc** [comment]
The HTML-CSS renderer in MathJax v2 tries to detect whether there are local copies of the MathJax or STIX fonts and will use those in place of web-based fonts if they are available (to reduce the amount of information that a user must download over the network).  Apple has shipped the STIX1 fonts as part of Mac OS and iOS for a number years, but in Ventura, they have switched to the STIX2 fonts.  These are packaged differently (the STIX1 fonts came in 29 separate fonts, but STIX2 combines these into 5, one each for regular, bold, italic, and bold-italic, plus a math font).  In order to try to keep things backward compatible, Apple still allows access to the STIX1 fonts by (what appears to be) mapping the original 29 fonts into the new 5 fonts.  This is largely effective, but not completely.  In particular, the calligraphic characters are not part of the Unicode standard, and so STIX includes them in the Private Use Are (PUA) of their fonts.  Unfortunately, the location in the PUA Changed between STIX1 and STIX2, and Apple mapping from the old fonts to the new ones doesn't take that into account.

The upshot is, when MathJax asks the local system whether STIXGeneral-Regular (the old STIX1 font) is available, Ventura says "yes" and MathJax believes that the 29 original fonts are there, and tries to use them in the layout that the original fonts actually have.  But in Ventura, the calligraphic characters are not in the same location, so you get the missing character symbol instead.

This issue only affects the HTML-CSS output, since it is the only one that uses local STIX fonts.  So if you switch to the CommonHTML or SVG output (using the MathJax contextual menu if you are a user, or changing the configuration file if you manage the website), or configuring MathJax to not look for local STIX fonts, then that should show these characters as they should be.

**Comment by jianghao-zhang** [comment]
Thank you for explaining!
