### ISSUE TITLE
MJ4 mathjax-tex: Prime (&#x2032;) is low and long

### ISSUE THREAD

**Issue by AlexEdgcomb** [mathjax/MathJax#3054]
### Issue Summary

MJ4's mathjax-tex renders prime (&#x2032;) as lower and longer than MJ2.

### Steps to Reproduce:

1. Go to https://codepen.io/alexedgcomb/pen/rNqRJgy
Observed: Prime is low and long
<img width="25" alt="image" src="https://github.com/mathjax/MathJax/assets/3512898/2a6f379e-7153-4045-8639-3540b96a061a">

Expected: Prime a bit higher and notably shorter, like in MJ2:
https://codepen.io/alexedgcomb/pen/XWxwRbw
<img width="24" alt="image" src="https://github.com/mathjax/MathJax/assets/3512898/c8b1bcc5-9e99-423a-bdbb-39cb7916c075">

### Technical details:

* MathJax Version: 4.0.0-alpha.1
* Client OS: Mac OS 13.2.1
* Browser: Firefox v113, Chrome v113, and Safari 16.3

I am using the following MathJax configuration:

``` js
MathJax = {output: {font: 'mathjax-tex'}}
```

and loading MathJax via

``` html
<script src="https://cdn.jsdelivr.net/npm/mathjax-full@4.0.0-alpha.1/es5/tex-mml-svg.min.js"></script>
```

### Supporting information:

Perhaps MJ4's mathjax-tex is working as intended.

**Comment by dpvc** [comment]
The MathML specification considers U+2032 to be what it terms a "pseudo-script" (see [section 7.2.2](https://www.w3.org/TR/MathML3/chapter7.html#chars.pseudo-scripts) of the MathML3 specification).

The recommended encoding in that section for "f prime" is to use an `<msup>`>, as in

``` xml
<msup><mi>f</mi><mo>&#x2032;</mo></msup>
```

which will render as you are looking for in MathJax.

There have been several discussions about this (see #2791 and this [user forum post](https://groups.google.com/g/mathjax-users/c/d4awxTUW8-E/m/NNAHKThlUBUJ)).  The upshot is that, in order to handle both `<msup><mi>f</mi><mo>&#x2032;</mo></msup>` and `<mi>f</mi><mo>&#x2032;</mo>`, Mathjax needs two forms of the U+2032 character, one that is larger and not raised for use in the `<msup>` construct (where the shrinking and raising is done by the usual process of forming a superscript), and one that is shrunken and raised for use without `<msup>` (where the shrinking and raising must be part of the U+2032 glyph itself).

The TeX font on which the original MathJax TeX fonts (way back in v1, which have migrated to v2 and v3) has only one size and placement of this character: the larger, un-raised version (it is the character associated with the `\prime` macro in TeX).  When you enter `f'` in TeX, it is translated into the equivalent of `f^\prime`, so needs the larger un-raised version, as the shrinking and raising is done by the superscript construction.  The MathJax TeX font does not have a smaller, pre-raised prime character, because the TeX font didn't have one.

While v3 (and v4) does have the infrastructure to handle both `<msup><mi>f</mi><mo>&#x2032;</mo></msup>` and `<mi>f</mi><mo>&#x2032;</mo>` properly, it does need to have the necessary characters in the font in order to do that.  But unfortunately, the MathJax TeX font only has one of the two needed glyphs, so can't properly render the second form.  If I recall correctly, all the other v4 fonts do have the needed characters, and certainly the mathjax-modern one does, but mathjax-tex doesn't.  It is just a porting of the original MathJax TeX font into the v4 format, so has all the limitations of the v3 (and v2 and v1) font.

Note that your v2 example works for you because your test page uses the old HTML-CSS output jax, and that jax would try to detect the presence of locally installed STIX fonts.  If found, they would be used rather than the MathJax TeX fonts in order to avoid having download web fonts.  The STIX fonts do include the two forms, and so MathJax could handle both MathML constructs when the STIX fonts are used, even back in v2.  Since MacOS ships with STIX fonts installed, the HTML-CSS output will find and use them, and so you will get a different rendering than if you had forced the use of the MathJax TeX fonts.  Because the fonts in use are different in your v2 example from your v4 one, it is not really a comparable test.

In the end, this is expected behavior for the mathjax-tex font, which has far less glyph coverage than the other v4 fonts.

**Comment by AlexEdgcomb** [comment]
Thank you for explaining, @dpvc !
