### ISSUE TITLE
MathJax fails to render on github pages or cloudflare pages

### ISSUE THREAD

**Issue by Tom-the-Bomb** [mathjax/MathJax#3062]
I'm using MathJax, more specifically [better-react-mathjax](https://www.npmjs.com/package/better-react-mathjax) a react wrapper around mathjax since I initially failed to get using the plain raw mathjax library to work in react.js with dynamic content in react.js

Everything works great locally, when testing using `npm run start` (react.js)
However when I try hosting the site on both github pages using the `gh-pages` module or cloudflare-pages, it fails to render and only leaves the raw content:

![image](https://github.com/mathjax/MathJax/assets/77308095/be787685-1f7d-42f8-bbb4-d7ad7fb388b5)
![image](https://github.com/mathjax/MathJax/assets/77308095/6a6ebdb7-01ce-4579-af0a-0d9d01e4e0db)

I have tried quick googling for a solution and it does seem that others have experienced this problem, but I failed to find any definitive working solution for me.

Thanks in advance

**Comment by dpvc** [comment]
You have not provided enough information to make an assessment of your situation.  When you started your issue, there was a template that was intended to help you provide what is needed, and you should not simply erase that and make your own free-form statement.  Please go back and fill out the information requested.

Some things you might check and include in your report are:

1. Are there any error messages in the browser console when you view your gh-pages?
2. Can you verify that the script for loading MathJax is actually in the page when you view its source?
3. Can you provide a link to an example page that illustrates the problem so that we can see what is going on ourselves?

**Comment by Tom-the-Bomb** [comment]
My apologies:
- there are no error messages whatsoever
- I'm pretty sure the source is there
![image](https://github.com/mathjax/MathJax/assets/77308095/49373f0d-d8d5-456c-b63c-9db51254705c)
![image](https://github.com/mathjax/MathJax/assets/77308095/71372b17-0ddf-4cc9-8d02-f67b76861b6b)
Link to WIP page: https://math-solver-4gi.pages.dev/

Let me know if you need anything else.

**Comment by dpvc** [comment]
If you enter `MathJax.typeset()` in the browser console, the expression will be typeset, so it looks like you are updating the AsciiMath string, but not calling `MathJax.typeset()` or `MathJax.typesetPromise()` for the updated container element.  It may be that the mathjax react component isn't tied into the updating that you are doing.  I'm afraid I don't know much about react, so can't guide you there, and your code is minimized, so it is not easy to tell what is going on.

See the [documentation](https://docs.mathjax.org/en/latest/web/typeset.html) for more on how to typeset dynamically created content.

**Comment by Tom-the-Bomb** [comment]
Thank you for your help, I've managed to fix it with that.
