### ISSUE TITLE
Force Load box won't stay unchecked

### ISSUE THREAD

**Issue by AndrewGellerII** [mathjax/MathJax#3065]
**Replace the text below with the details of the issue you are facing.  
DO NOT simply erase the form and type a free-form response.**
-----

### Issue Summary

The "force load" box won't stay unchecked. I don't want MathJax to load on every page (just on the pages with math).

### Steps to Reproduce:

1. Uncheck "Force Load"
2. Save
3. "Force Load" is checked again 

Any other information you want to share that is relevant to the issue
being reported. Especially, why do you consider this to be a bug? What
do you expect to happen instead?

The "Force Load" should stay unchecked (making it so MathJax doesn't load unless called).

### Technical details:

* MathJax Version: 3.2
* Browser: Chrome Version 114.0.5735.198 (Official Build) (arm64)

I am using the following MathJax configuration: default

and loading MathJax via

``` html
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
```

**Comment by dpvc** [comment]
MathJax doesn't have a "force load" checkbox, so that must be part of some other part of the user interface on the site you are using.  You may need to contact the site maintainers, or the developers of the content management system that you are using.  It is not clear from the information what platform you are using for that.  In any case, this is not within the control of MathJax.

**Comment by AndrewGellerII** [comment]
Hi Davide,

Thanks for the follow up. I am using Wordpress and using the MathJax-LaTeX wordpress plugin. If I am understanding correctly, I should be contacting the plugin developers directly in that the plugin and Mathjax are two separate things? That makes sense. 

A.

**Comment by dpvc** [comment]
Yes, that is correct.
