### ISSUE TITLE
v4-beta.3: Automatic Line-Break with `\text` in Inline Math

### ISSUE THREAD

**Issue by TrebledJ** [mathjax/MathJax#3099]
### Issue Summary

A follow-up of #3098, but instead of using `\break`, I tried using `\goodbreak` or nothing.

### Steps to Reproduce:

1. Open [web page][demo].
2. See math sticking out of container and not breaking.
3. Cry.

I tried using `\goodbreak` or no break along with the `{}` workaround suggested in #3098. It works on block-level mathjax (i.e. surrounded by `$$`), but doesn't work with inline mathjax (`$`). (See demo.)

```latex
\texttt{Maybe (Either (a, a) (Bool, a))} {} \equiv \texttt{(Maybe a, Maybe a)}
\texttt{Maybe (Either (a, a) (Bool, a))} {} \goodbreak \equiv \texttt{(Maybe a, Maybe a)}
```

### Technical details:

* MathJax Version: 4.0.0-beta.3
* Client OS: MacOS 12.6.8
* Browser: Chrome Version 116.0.5845.179 (Official Build) (x86_64)

I am using the following MathJax configuration:

``` js
MathJax = {
    tex: {
        inlineMath: [
            [
                '$', '$'
            ],
            [
                '\\(', '\\)'
            ]
        ],
    },
    svg: {
        fontCache: 'global',
        displayOverflow: 'linebreak',
    },
};
```

and loading MathJax via

``` html
<script defer id="MathJax-script" src="https://cdn.jsdelivr.net/npm/mathjax@4.0.0-beta.3/tex-mml-svg.js" type="text/javascript"></script>
```

### Supporting information:

 * [Demo][demo]
 * Screencap below. Blue region is the container.
    
    <img width="912" alt="Screenshot 2023-09-15 at 6 28 06 PM" src="https://github.com/mathjax/MathJax/assets/39648915/22c1d45c-9227-42c3-94d5-378eec9ba3dc">

[demo]: https://trebledj.github.io/mathjax/#without-break

**Comment by TrebledJ** [comment]
Huh, odd. It works all of a sudden. Let me investigate this a bit more.

**Comment by TrebledJ** [comment]
Hmm... so it ended up working in localhost after I opened the MathJax context menu and clicked `Math Settings > Reset to defaults`. But it's weird, because before resetting, the `Wide Expressions > Linebreak` and `Allow In-Line Linebreak` settings were _ticked_ ✅. Not sure if it's a settings (load? render?) issue.

**Comment by dpvc** [comment]
I'm not entirely sure what the current situation for you is.  Your test page works properly for me, so I think all should be well for you.  As I mentioned in a [comment](https://github.com/mathjax/MathJax/issues/3098#issuecomment-1719428310) to #3098, switching the renderer via the contextual menu is what was causing your error messages in the console, and that might have been causing other problems with the rendering as well.  Reseting to the defaults would have cleared that menu setting, so that might have been what the issue was, not the wide expression settings.  

If everything is working for you now, I will close this issue.

**Comment by TrebledJ** [comment]
Sure, no problem. It seems to be working fine. Thanks~

**Comment by dpvc** [comment]
Thanks for the problem reports.  I have made several PRs to address issues that it raised.  These will be in the next beta release.
