### ISSUE TITLE
AsciiMath Augmented Matrix does not render to SVG

### ISSUE THREAD

**Issue by naiveai** [mathjax/MathJax#3105]
### Issue Summary

AsciiMath has a feature that uses MathML `mtable`s to render augmented matrices. When converting to CHTML, this works and renders correctly. However, when converting to an SVG, the column lines do not appear, though there is a near-imperceptible amount of extra whitespace where the column line is supposed to be.

### Steps to Reproduce:

1. Set up a Node ESModule environment with MathJax installed
2. Run the following:

```javascript
import fs from "fs";

const MathJax = await (await import("mathjax")).init({
    loader: {
        load: ['input/asciimath', 'output/svg']
    }
});

const mathExpression = "[[a, b, |, c], [d, e, |, f], [g, h, |, i]]";

const renderedSvg = MathJax.startup.adaptor.innerHTML(MathJax.asciimath2svg(mathExpression));

fs.writeFileSync("output.svg", renderedSvg);
```
3. Check output.svg

The expected output looks like this (ignoring background color), which you can verify on [the AsciiMath website](http://asciimath.org/):

![correctly rendered augmented matrix](https://github.com/mathjax/MathJax/assets/40498911/d1e3220e-2fc4-4091-a6ce-613add818596)

However, the actual SVG output looks like this, missing its column line:

![incorrectly rendered augmented matrix](https://github.com/mathjax/MathJax/assets/40498911/ca2eed77-ca1e-49f2-b7f6-37cd0f5bbab9)

### Technical details:

* MathJax Version: 3.2.2
* Client OS: macOS Ventura 13.5
* No rendering is occurring in a browser, node version 18.17.1

**Comment by naiveai** [comment]
Upon further experimentation, this doesn't seem to be limited to AsciiMath:

```javascript
import fs from "fs";

const MathJax = await (await import("mathjax")).init({
    loader: {
        load: ['input/tex', 'output/svg']
    },
});

const mathExpression = String.raw`\left(\begin{array}{cc|c}  
 2 & 0 & 1\\  
 0 & 1 & 1  
\end{array}\right)`;

const renderedSvg = MathJax.startup.adaptor.innerHTML(MathJax.tex2svg(mathExpression));

fs.writeFileSync("test.svg", renderedSvg);
```

This also produces an output without a column line:

![image](https://github.com/mathjax/MathJax/assets/40498911/fd47c1fa-36a9-4d4d-8919-8fa55ed98168)

**Comment by dpvc** [comment]
As you have found out, this is was due to the missing CSS styles that control the lines (and a few other things).

Your solution certainly works, but includes more CSS than is generally needed.  The examples in the [MathJax node demos](https://github.com/mathjax/MathJax-demos-node) repository include a more minimal set.  For example:

https://github.com/mathjax/MathJax-demos-node/blob/d9ba8c61e54683efc04d0e11d5812bc974da65db/component/tex2svg#L35-L43

with the code to add them into the output at

https://github.com/mathjax/MathJax-demos-node/blob/d9ba8c61e54683efc04d0e11d5812bc974da65db/component/tex2svg#L150-L151
