### ISSUE TITLE
MathJax.mathml2chtml gives error when inputting certain numbers, e.g. 1000000

### ISSUE THREAD

**Issue by Sjiep** [mathjax/MathJax#3136]
### Issue Summary

Using the method to convert mathml to other format produces an error in certain cases when using Safari on an iPad, v16.7.2 or v17.1.1.
For example the following will result in an error:

```js
MathJax.mathml2chtml('<math><mn>1000000</mn></math>')
// results in the following error:
// Error parsing MathML: Unknown node type "a"‘
```

Choosing `2000000` or `10000000` works as expected but, `1000000000` (and adding more zeros) results in the above error. 

Using a different input processor, e.g. `MathJax.tex2chtml('1000000')` works fine. Also the "normal" typesetting procedure, `MathJax.typeset();`, with xml as input works as expected 

All examples behaviours provided can be replicated on the MathJax demo page from the browser devtools console, connecting the iPad to a MacBook. 

Note that the Safari on the Macbook worked as expected, but this is an outdated version. 

### Technical details:

* MathJax Version: 3.2.2
* Client OS: iPadOS 16.2 or 17.1.1
* Browser: Safari

**Comment by dpvc** [comment]
On iOS, Apple tries to identify telephone numbers and adds links to them so you can click on them to dial the number.  Unfortunately, they do a very poor job of distinguishing telephone numbers from other numbers, and essentially any number with 7 or more digits gets treated as a telephone number, regardless of the context.  That is what is happening to you, here.  Even though the number is within MathML, it still gets wrapped in an `<a href="...">` tag.  When MathJax tries to process that, it complains because the "a" tag is not a MathML tag.

There are two possible work-arounds:

You could add

``` html
<meta name="format-detection" content="telephone=no" />
```

to the document `<head>` to prevent iOS from linking telephone numbers.

Alternatively, you could try setting the MathML input jax's `parseAs` option to `xml` (the default is `html`), which I think should prevent the browser from looking for telephone numbers.  E.g., incorporate

``` js
MathJax = {
  mml: {
    parseAs: 'xml'
  }
};
```

into your configuration.

**Comment by Sjiep** [comment]
Thanks for the quick reply. I will take a look at your suggestions.

**Comment by Sjiep** [comment]
I tried both suggestions, but neither seems to solve the issue.

**Comment by dpvc** [comment]
It turns out the parsing is done in a separate document, so doesn't get the `meta` tag (my fault for a bad suggestion).  You might be able to do it by using

``` js
MathJax.mathml2chtml('<html><head><meta name="format-detection" content="telephone=no" /></head><body><math><mn>1000000</mn></math></body></html>');
```

instead.  Of course, you would make a function that adds the HTML around the MathML to make it easier for you, but that would probably do the trick.

As for parsing as XML, that should not introduce problems, unless you have `annotation-xml` nodes that contain HTML content, or (when v4 is out), if you embed HTML within MathML token nodes.  Other than that, there should be no problem.
