### ISSUE TITLE
`$\sqrt\dfrac{x}{y}$` yields `Missing argument for \dfrac`

### ISSUE THREAD

**Issue by Tiphereth-A** [mathjax/MathJax#3198]
### Issue Summary

`$\sqrt\dfrac{x}{y}$` yields `Missing argument for \dfrac`

### Steps to Reproduce:

1. Open <https://www.mathjax.org/#demo>
2. Type `$\sqrt\dfrac{x}{y}$ $\sqrt\frac{x}{y}$` in the text area

Observed:

![](https://github.com/mathjax/MathJax/assets/62847935/fdb789b0-9343-4aa5-9ea3-74d14623bb55)

### Technical details:

* MathJax Version: 3.2
* Client OS: Windows 11
* Browser: Firefox 122.0

### Supporting information:

`$\sqrt{\dfrac{x}{y}}$` works properly. `$\sqrt{\dfrac{x}{y}}$ $\sqrt{\frac{x}{y}}$` is rendered like this:

![](https://github.com/mathjax/MathJax/assets/62847935/5d0ab71e-6af8-4c75-84aa-85c963e20e0c)

**Comment by dpvc** [comment]
This is correct behavior, and consistent with how LaTeX works.  In actual LaTeX, $$\sqrt\dfrac{x}{y}$$ produces

<img width="186" alt="sqrt-dfrac" src="https://github.com/mathjax/MathJax/assets/432782/163f5206-6d14-4e11-adb6-671f9dccdb19">

while $$\sqrt\frac{x}{y}$$ renders as in your image.  Why one works and the other doesn't has to do with the details of how the `\dfrac` and `\frac` macros are defined, and so these are "magic" differences that one should not rely on.  Using braces around the argument to `\sqrt` is the only reliable approach, both in LaTeX and MathJax.  Without them, `\sqrt\dfrac{x}{y}` essentially means `\sqrt{\dfrac}{x}{y}`, and the `\dfrac` inside the braces has missing arguments.

The fact that `\sqrt\frac{x}{y}` works is an accident in LaTeX, not by design.  Unfortunately, relying on accidents will lead you to misinterpret the expected results in other situations, as it has here.  The real incorrect one is `\sqrt\frac{x}{y}` because it **doesn't** produce the expected error about the missing arguments.  MathJax is sometimes more picky about the need for braces, but in this case, it aligns with LaTeX in both cases.
