### ISSUE TITLE
MathJax.tex2chtml is not a function

### ISSUE THREAD

**Issue by kungfooman** [mathjax/MathJax#3207]
Version: 3.2.2

When I use this config:

```js
    window.MathJax = {
      tex: {
        macros: {
          "*": "\\\\,"
        }
      },
      startup: {
        // Works without ready function...
        ready() {
          console.log("Hai!");
        }
      }
    };
```

I get this error: `MathJax.tex2chtml is not a function`

The entire loading process already feels strange, but this is the top of strangeness. I simply wish you had a proper ESM setup.

**Comment by dpvc** [comment]
Your `ready()` function needs to call `MathJax.starutp.defaultReady()` at some point in order to get the normal startup action to be performed.  Otherwise, you have override the usual startup process, which sets up the various conversion function based on the input and output jax you have loaded.

See the documentation on [performing actions during initialization](https://docs.mathjax.org/en/latest/web/configuration.html#performing-actions-during-initialization) for more details.
