### ISSUE TITLE
What are best practices for using MathJax in ReactJS/NextJS?

### ISSUE THREAD

**Issue by khesualdo** [mathjax/MathJax#3221]
```
function fetchOutput() {
   setShowOutput(false);
   setOutput("$...$");
}

useEffect(() => {
  (async () => {
    MathJax.typesetClear();
    await MathJax.typesetPromise();
    setShowOutput(true);
  })();
}, [output]);
```

On a click of a button `fetchOutput` is called to generate new maths. To not display the `$$` delimiters, I hide the output `div` while MathJax is typesetting. Once the asynchronous typesetting is complete, I show the output `div`.

The **problem** is that sometimes the **output stays hidden**. So the code after `await MathJax.typesetPromise()` does **not** run.

Is the problem with using an `async` function in `useEffect`?
Is the problem with MathJax and React trying to manipulate the DOM at the same time?

**Comment by dpvc** [comment]
I have never used React.js or Next.js, so I can't really tell you what best practices are, but I do wonder whether `useEffect()` is expecting to have an `async` function, and whether that isn't the problem.  Your suggestion that React and MathJax are competing for the DOM sounds like a reasonable hypothesis.  The fact that it only happens *sometimes* suggest a race condition of that kind, and the `async` function is a likely culprit.

If you comment out the two `setShowOutput()` commands, so that the output is always shown,  does the math get processed?

If you add a `console.log()` call after the `await` command, does its output show up in the browser console?

**Comment by khesualdo** [comment]
I can get it work, but I am not sure if my solution is "correct" or if any anomalies will arise at some point.

Does the MathJax team have any plans to provide official packages for different frameworks?

**Comment by dpvc** [comment]
> Does the MathJax team have any plans to provide official packages for different frameworks?

The MathJax team is just two people, and we do not have the resources to make and maintain official plugins for all the popular frameworks.  Developing the needed expertise in a range of diverse frameworks takes time, and keeping up with changes in those frameworks is a maintenance cost that is beyond our current means.  The community members of those frameworks are in a better position to support their framework-specific plugins.  We answer questions for them as best we can, but that is the best we can offer.
