### ISSUE TITLE
Display a highlight on part of the formula

### ISSUE THREAD

**Issue by saraOrkide** [mathjax/MathJax#3223]
Hello
I wanted to mark part of the formula, how do I do this?
For example, I want to mark x in the following piece of code, when I put the mark tag, it gets "Math input error"
mark tag
``` html
                  <math xmlns='http://www.w3.org/1998/Math/MathML'
                    display='inline' mathcolor='#050038'>
                    <mfenced open='|' close='|' separators='|'>
                        <mrow>
                            <mfrac>
                                <mrow>
                                    <msup>
                                        <mrow>
                                            <mtext><mark>x</mark></mtext>
                                        </mrow>
                                        <mrow>
                                            <mn>2</mn>
                                        </mrow>
                                    </msup>
                                    <mo>+</mo>
                                    <mtext><mark>x</mark></mtext>
                                </mrow>
                                <mrow>
                                    <mtext><mark>x</mark></mtext>
                                    <mo>+</mo>
                                    <mn>1</mn>
                                </mrow>
                            </mfrac>
                        </mrow>
                    </mfenced>
                </math>
```

mahjax version: mathjax-4.0.0-beta.4
using: mml-chtml.js

**Comment by dpvc** [comment]
MathJax v4 does support HTML inside token elements in MathML, but you do have to enable it with a configuration option.

``` js
MathJax = {
  mml: {
    allowHtmlInTokenNodes: true
  }
}
```

Note that if you do this, the "x" in `<mark>x</mark>` will be an HTML formatted "x", not a MathJax formatted one.  That will damage the speech text for those using MathJax's assistive tools, as the speech-rule-engine currently ignores HTML in MathML.

Some potentially better approaches are to use `mathbackground="yellow"`  (if you want yellow highlighting), as in

``` xml
<mtext mathbackground="yellow">x</mtext>
```

This will make a yellow background using a tight bounding box (only as big as the text itself with no padding).  If you want padding so that the color extends slightly beyond the character, you can use

``` xml
<mtext mathbackground="yellow" style="padding:3px">x</mtext>
```

Either of these will work with the assistive tools better than the `<marK>x</mark>` approach, but that is up to you.

**Comment by saraOrkide** [comment]
thank you very much
