### ISSUE TITLE
report error

### ISSUE THREAD

**Issue by sunnyawake5** [mathjax/MathJax#3236]
``` js
import mathjax from "mathjax";
let MathJax=await mathjax.init({ loader: { load: ["input/tex"] } });
//let latex0=`$x_{1,2} = {-b\pm\sqrt{b^2 - 4ac} \over 2a}.$$`
let latex=`$$|\vec{A}|=\sqrt{A_x^2 + A_y^2 + A_z^2}.$$(1)`
let mml=MathJax.tex2mml(latex);
console.log(mml)
```

TypeError: null is not an object (evaluating 'a[4]')
      at b (/Users/a/workspace.js16/md2docx/node_modules/mathjax/es5/input/tex.js:1:98404)
      at /Users/a/workspace.js16/md2docx/node_modules/mathjax/es5/input/tex.js:1:18719
      at /Users/a/workspace.js16/md2docx/node_modules/mathjax/es5/input/tex.js:1:64889

but it's ok when trying on[ mathjax website demo.](https://www.mathjax.org/#demo)

latex0 also ok.

**Comment by dpvc** [comment]
Because Javascript uses the backslash (`\`) as an escape character, you need to double all backslashes in your `latex` string.  Without this, the `\v` becomes a vertical tab, and that is what is confusing MathJax.

Also, you shouldn't include math delimiters in the string passed to `MathJax.tex2mml()`, so should not include the `$$`.  Instead, if you want display math, use the second argument to `tex2mml()` and pass it `{display: true}`.

So you should try

``` js
import mathjax from "mathjax";
let MathJax = await mathjax.init({ loader: { load: ["input/tex"] } });
let latex = `|\\vec{A}|=\\sqrt{A_x^2 + A_y^2 + A_z^2}.`
let mml = MathJax.tex2mml(latex, {display: true});
console.log(mml);
```

If you want an equation number, use `\\tag{1}` not just `(1)`.

You might consider using

``` js
let mml = await MathJax.tex2mmlPromise(latex);
```

in order to handle loading of TeX extensions or other dynamically loaded code.  See the example [node demos](https://github.com/mathjax/MathJax-demos-node), for example the [simple/tex2mml](https://github.com/mathjax/MathJax-demos-node/blob/master/simple/tex2mml) examples.

Finally, in future, please fill out the template issue report rather than just erasing it and using your own free-form report.  For example, you didn't indicate which version of MathJax you are using, which can be important (though wasn't in this case as I could deduce that you were using v3).

**Comment by sunnyawake5** [comment]
tried and worked as you suggest. thank you.

**Comment by dpvc** [comment]
Thanks for letting us know.
