### ISSUE TITLE
How to use MathJax in Vue3+vite4

### ISSUE THREAD

**Issue by dragonliuhu** [mathjax/MathJax#3258]
require is not defined

**Comment by dpvc** [comment]
There is not enough information here about your situation to give you a meaningful answer.  Please fill out the issue template that you were presented with when you opened the new issue; don't just delete it.

**Comment by dragonliuhu** [comment]
I need the version for ES6.
I wanna use MathJax with ES6 and Vue3 or Vue2

**Comment by dragonliuhu** [comment]
Is there an ES6 version

**Comment by dragonliuhu** [comment]
> There is not enough information here about your situation to give you a meaningful answer. Please fill out the issue template that you were presented with when you opened the new issue; don't just delete it.

When will ES6 be released?

**Comment by dpvc** [comment]
I'm not sure why asking this three times here and once more in a separate issue is necessary.

MathJax v4 comes in with both ES Modules (mjs) and CommonJS (cjs) formats.  it is currently available in beta release, so that is one possibility for you.

Again, however, you have not provided sufficient information to really help you.  Saying you are wanting to use MathJax with Vue3 or Vue2 is not enough information.  What have you tried, and what is the result?  MathJax can be included in a project in several different ways, and we can't tell which you are trying to use.

While the files in the MathJax v3 are CommonJS files, ES Modules can load CommonJS files.  You are right that they can't include `require()` calls, so I'm assuming you re loading files from the `mathjax-full/js`, which do use `require()`.  Note, however, that the combined components in `mathjax/es5` or `mathjax-full/es5` do not use `require()`, and so you should be able to import them into your Vue application.  Have you tried that?  (We don't know since you haven't given any real information about what you re doing.)  

That is the best we can do until you provide some actual details.

**Comment by dragonliuhu** [comment]
Sorry, I'm not very good at English.

Now, my project installed 'mathjax@beta', but I don't know how to import the MathJax.

I don't know which file to import so that I can use MathJax in es6 mode.

**Comment by dpvc** [comment]
Closing this in favor of #3263.
