### ISSUE TITLE
MathJax Rendering issue

### ISSUE THREAD

**Issue by songxingling1** [mathjax/MathJax#3271]
### Issue Summary

![image](https://github.com/user-attachments/assets/52212dfa-f51b-466e-bcd0-70907cb5253f)
- The numeral font is different from the letter font.
- There is a scrollbar below.
- No block formulas were rendered.

### Steps to Reproduce:

1. Integrate MathJax using a CDN and configure it.
2. Discover the problem.

I used cnblog to write my blog, utilizing cnblog's JavaScript features.

### Technical details:

* MathJax Version: 3.2.2
* Client OS: Windows 10 19045.4651
* Browser: Microsoft Edge 127.0.2651.98

I am using the following MathJax configuration:

``` js
MathJax = {
  tex: {
    inlineMath: [['$', '$'], ['\\(', '\\)']]
  }
};
```

and loading MathJax via

``` html
<script id="MathJax-script" async
  src="https://cdn.jsdelivr.net/gh/mathjax/mathjax@3.2.2/es5/tex-mml-chtml.min.js">
</script>
```

### Supporting information:
![image](https://github.com/user-attachments/assets/20f884f2-074e-4289-a29f-a4073661947d)

**Comment by amrit3874** [comment]
![INDEFINITE INTEGRATION TEST 1 - Google Chrome 13-08-2024 12_26_19](https://github.com/user-attachments/assets/c052d20e-b51e-4593-ad59-3e17e1c6584b)

i've been facing this kind of error in my pc and laptop after I reinstalled windows in both of them..

**Comment by dpvc** [comment]
@amrit3874, your issue seems unrelated to the one in the original post.  You should open a new issue for that, with complete details.  There is not enough information here to diagnose your issue.

**Comment by dpvc** [comment]
@songxingling1, I suspect that you are using the Unicode Full-Width characters for the numbers (the ones at U+FF10 to U+FF19) rather than the ASCII numerals.  That MathJax fonts don't include these characters, so you are seeing the ones taken from a font installed on your system, and they don't match the MathJax fonts very well.  Also, the characters are wider than usual (they are the "full width" characters after all).  Can you enter ASCII rather than full-width numbers?

If not, we could perhaps create a TeX input jax pre-filter that will convert the full-width versions to the ASCII equivalents.

**Comment by songxingling1** [comment]
Well, actually this issue is caused by CSS style sheets and Markdown escaping, and there is no problem with the Mathjax library.

**Comment by amrit3874** [comment]
I tried with other browsers and it only seems to be working with mozilla
firefox for some reason.. so I'm using that nowadays..pls let me know if u
find any solutions for my problem..
