### ISSUE TITLE
Mode display or block

### ISSUE THREAD

**Issue by xrjunque** [mathjax/MathJax#3276]
&lt;math mode='block'&gt; renders tag &lt;munderover&gt; like if it was a &lt;msubsup&gt; tag, while mode='display' renders as expected.

1. Image for mode='block' (same as if mode is omitted):

![Block Captura de pantalla 2024-08-27 160903](https://github.com/user-attachments/assets/ea6d222a-04a1-4b46-84f1-ebddd2bbcbe1)

2. Image for mode='display': 

![Display Captura de pantalla 2024-08-27 160949](https://github.com/user-attachments/assets/6d5a754a-a809-4b0d-b4f1-2f20bf47eae5)

* MathJax Version: 2, 3, last
* Client OS: (Windows 11)
* Browser: ( Chrome, Edge)

(If you consider so, you may hava a try at my site (sample #8): [https://xrjunque.nom.es/MathML_To_String](https://xrjunque.nom.es/MathML_To_String)

Thanks in advance.

**Comment by dpvc** [comment]
The `mode` attribute is a deprecated MathML2 attribute, and it is allowed only two values, [`display` and `inline`](https://www.w3.org/TR/MathML2/chapter7.html#:~:text=The%20mode%20attribute%20specifies%20whether,%22inline%22%20(default).).  So `mode="block"` is not a valid attribute value, and since the default is `inline`, MathJax uses that for invalid values.  Perhaps you mean `display="block"`, which is the recommended MathML attribute for this?

**Comment by xrjunque** [comment]
Yes, sorry, you are right. But if attribute display is omitted or is display='inline? ii is rendering as a 'msubsup' instead of 'munderover':

![Inline Captura de pantalla 2024-08-27 165601](https://github.com/user-attachments/assets/2a8b53d3-3f77-4bd0-8ad5-81884f0ffcc3)

**Comment by dpvc** [comment]
Yes, `inline` is the default as indicated in the [MathML 3 specification](https://www.w3.org/TR/MathML/mathml.html#chapter2_interf.toplevel.atts)

**Comment by xrjunque** [comment]
So? The behaviour is not the one expected.

**Comment by dpvc** [comment]
> But if attribute `display` is omitted or is `display='inline'` it is rendering as a `msubsup` instead of `munderover`

Yes, that is correct.  If the `munderover` has an `mo` as its base and the `mo` has movable limits according to the operator dictionary, then the `munderover` acts as `msubsup`.  So that is the expected behavior.  See the `movablelimts` attribute in the [MathML3 description of `mo`](https://www.w3.org/TR/MathML3/chapter3.html#presm.mo.dict.attrs).  Note that the summation sign has `movablelimits` set in the [operator dictionary](https://www.w3.org/TR/MathML3/appendixc.html#oper-dict.entries-table)

**Comment by dpvc** [comment]
You can either put the `munderover` inside an `mstyle` element that sets `displaystyle="true"`, or add `movablelimits="false"` to the `mo` containing the summation sign if you want to force the under-over display in inline mode.

**Comment by xrjunque** [comment]
Besides movable or not, the same code having attribute 'inline' or 'block' responds in a different manner: like 'msubsup' or like 'munderover'.

**Comment by xrjunque** [comment]
Yes, as I said now I see that depending on display='inline' or ='block' the default values of displayStyle are set to 'false' or 'true' and, unless otherwise stated, output for &sum, &prod, lim (and other 'movables') will be in compact form ("like msubsup") or not ("like munderover"), respectively.
Thank you very much for the clarification!

**Comment by dpvc** [comment]
Sorry, I didn't see your edits to your previous message (which were made slightly after I posted my comment above), so I didn't see that you had worked out the details.

**Comment by xrjunque** [comment]
Well, the comments have been worth it. Thanks.
