### ISSUE TITLE
mark search term

### ISSUE THREAD

**Issue by hbghlyj** [mathjax/MathJax#3284]
**Is your feature request related to a problem? Please describe.**
For example, in a search result, after processed by a CMS to mark search term `x_2`, the string `\(x_1+x_2+x_3\)` becomes `\(x_1+<mark>x_2</mark>+x_3\)`, then MathJax will not typeset that formula: $x_1+<mark>x_2</mark>+x_3$

**Describe the solution you'd like**
I'd like to config MathJax so that
+ The `<mark>` tags in formulas are replaced with its contents during MathJax typeset.
+ The `<mark>` tags not in formulas are unchanged.

For example, `<mark>x_2</mark> \(x_1+<mark>x_2</mark>+x_3\)` becomes <mark>x_2</mark> $x_1+x_2+x_3$.

**Describe alternatives you've considered**
I looked at `HTMLDomStrings.OPTIONS.includeHtmlTags` but it seems to only replace a tag with a constant string.

**Additional context**
MathJax version: v3 latest

**Comment by hbghlyj** [comment]
```
<script>
MathJax = {
  startup: {
    ready: function() {
      const {HTMLDomStrings} = MathJax._.handlers.html.HTMLDomStrings;
      HTMLDomStrings.OPTIONS.includeHtmlTags['mark'] = '';
      var handleTag = HTMLDomStrings.prototype.handleTag;
      HTMLDomStrings.prototype.handleTag = function (node, ignore) {
          var text = this.adaptor.textContent(node);
          console.log(text);
        if (this.adaptor.kind(node) === 'mark') {
          this.string += text;
        }
        return handleTag.call(this, node, ignore);
      }
      MathJax.startup.defaultReady();
    }
  }
};
</script>
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js">
</script>
\(x_1+<mark>x_2</mark>+x_3\)
```
This seems to work:
![image](https://github.com/user-attachments/assets/19e7ca4e-7f04-4bfc-b0b2-1dc6ecb99a85)

**Comment by hbghlyj** [comment]
It would be better if we can set yellow background to the part of MathJax expression that corresponds to the <mark> tag. I don't know how to do that.

**Comment by dpvc** [comment]
Good for you for working it out as far as you did!  I would recommend this instead, however, as you should be calling `this.extendString()` rather than adjusting `this.string` directly.

``` js
MathJax = {
  startup: {
    ready: function() {
      const {HTMLDomStrings} = MathJax._.handlers.html.HTMLDomStrings;
      HTMLDomStrings.OPTIONS.includeHtmlTags['mark'] = '';
      Object.assign(HTMLDomStrings.prototype, {
        _handleTag_: HTMLDomStrings.prototype.handleTag,
        handleTag(node, ignore) {
          if (this.adaptor.kind(node) !== 'mark') {
            return this._handlTag_(node, ignore);
          }
          this.extendString(node, this.adaptor.textContent(node));
          return this.adaptor.next(node);
        }
      });
      MathJax.startup.defaultReady();
    }
  }
};
```

If you want a yellow background, you could do

``` js
MathJax = {
  startup: {
    ready: function() {
      const {HTMLDomStrings} = MathJax._.handlers.html.HTMLDomStrings;
      HTMLDomStrings.OPTIONS.includeHtmlTags['mark'] = '';
      Object.assign(HTMLDomStrings.prototype, {
        _handleTag_: HTMLDomStrings.prototype.handleTag,
        handleTag(node, ignore) {
          if (this.adaptor.kind(node) !== 'mark') {
            return this._handlTag_(node, ignore);
          }
          var text = this.adaptor.textContent(node);
          this.extendString(node, `\\style{background-color:yellow}{${text}}`);
          return this.adaptor.next(node);
        }
      });
      MathJax.startup.defaultReady();
    }
  }
};
```

though this will be a tight bounding box around the characters inside the mark, and you are right to worry about the possibility of the bracing being intermixed with bracing of the original MathJax.  It will mess up the result for something like `\(x + <mark>\sqrt{</mark>1+x}\)`.

For your suggestion of looking through the nodes to find a common ancestor, that also has some issues.  If you insert something at those locations, that can still mess up the internal tree.  For example, in `\(a+<mark>x^</mark>2\)`, whatever replaced the `</mark>` would end up being the superscript rather than the 2.  

I don't see a good way to accomplish what you are asking without the possibility of it messing up the result in some situations.
