### ISSUE TITLE
\mathcal uses incorrect font in Client side MathJax modes

### ISSUE THREAD

**Issue by physikerwelt** [mathjax/MathJax#3292]
### Issue Summary

As described in https://phabricator.wikimedia.org/T375932 LaTeX input like `$\mathcal A$` uses different fonts than it used with MathJax-node

With a [preprocessing script](https://gerrit.wikimedia.org/r/c/mediawiki/extensions/Math/+/979217/3/src/WikiTexVC/MMLmappings/Util/MMLParsingUtil.php) the LaTeX input is converted into MathML of this form
```
<mi>&#x1D49C;</mi>
```
To support MathJax we also added the classes
```
<mi data-mjx-variant="-tex-calligraphic" mathvariant="script">𝒜</mi>
```
which might have been contra productive?

Which seems to be [recommended](https://www.w3.org/TR/mathml-core/#script-mappings). The MathJax rendering looks more like `$\mathscr A$`

### Steps to Reproduce:

2. Login to https://en.wikipedia.beta.wmflabs.org/
3. Select Client Side Math rendering in the preferences https://en.wikipedia.beta.wmflabs.org/wiki/Special:Preferences#mw-prefsection-rendering-math
4. Goto https://en.wikipedia.beta.wmflabs.org/wiki/T375932

See that it works with FF but fails with Chrome.

### Technical details:

* MathJax Version: 3.2.2
* Client OS: Mac OS X 10.8.4
* Browser: Firefox 130.0.1 

I am using the following MathJax configuration:

https://github.com/wikimedia/mediawiki-extensions-Math/blob/db81c960623d346ca8f43fb91ca3da92f868ea29/modules/ext.math.mathjax.js#L7
``` js
( function () {
	'use strict';
	const extensionAssetsPath = mw.config.get( 'wgExtensionAssetsPath' );
	window.MathJax = {
		loader: {
			// see https://docs.mathjax.org/en/latest/input/mathml.html
			load: [ '[mml]/mml3' ],
			// see https://docs.mathjax.org/en/latest/options/startup/loader.html
			paths: {
				mathjax: extensionAssetsPath + '/Math/modules/mathjax/es5'
			}
		}
	};
}() );
```

and loading MathJax via

``` html
<script src="/w/extensions/Math/modules/mathjax/es5/input/mml.js" charset="UTF-8"></script>
<script src="/w/extensions/Math/modules/mathjax/es5/input/mml/extensions/mml3.js" charset="UTF-8"></script>
```

### Supporting information:

 * Please supply a link to a (live) minimal example page, when possible:
 
https://en.wikipedia.beta.wmflabs.org/wiki/T375932

 * If your issue is with the display of the mathematics produced by MathJax, include a screen snapshot that illustrates the problem, when possible.
![image](https://github.com/user-attachments/assets/d6f55f59-b0d5-45c9-90d7-8b35af182454)

See also https://phabricator.wikimedia.org/T375932 for more screenshots

 * Check your browser console window for any error messages, and include them here.
None

 * Include the MathJax configuration you are using, and the script tag that loads MathJax itself.
```
			load: [ '[mml]/mml3' ],

**Comment by dpvc** [comment]
The underlying problem is that the Unicode Math Alphanumerics block includes only one script variant, and the choice of the variant to use is up to the fonts.  Most seem to use a Roundhand style (as in `\mathscr`), so the Chancery form (`\mathcal`) is absent.  (The STIX2 Math fonts have the Chancery version.)

Since the MathML `mathvariant` has only one `script` value, that makes it difficult to implement both `\mathscr` and `\mathcal`.  MathJax uses `data-mjx-variant="-tex-calligraphic"` to overcome this difficulty, but since MathML renderers don't know about this attribute, MathJax adds `mathvariant="script"` to at least get a script variant (whichever one the font implements).

Note, however, that MathJax uses `<mi data-mjx-variant="-tex-calligraphic" mathvariant="script">A</mi>` not `<mi data-mjx-variant="-tex-calligraphic" mathvariant="script">&#x1D49C;</mi>`.  This is because the MathML specification indicates that the Math Alphanumeric values are not to be influenced by CSS styles or `mathvariant` settings (see end of the third paragraph of the description of `mathvariant` in the [specification](https://www.w3.org/TR/MathML3/chapter3.html#presm.commatt)):

> Note that the appearance of a mathematical alphanumeric symbol character should not be altered by surrounding mathvariant or other style declarations.

That is, if you do

``` xml
<mi mathvariant="bold">&#x1D504;</mi>
```

you get the non-bold Fraktur capital A U+1D504, not the bold one at U+1D56C.  I suspect the main reason for that is when the `mathvariant` is on an `mstyle` element, lik

``` xml
<mstyle mathvariant="bold">
  <mi>x<mi>
  <mo>+</mo>
  <mi> &#x1D504;</mi>
</mstyle>
```

The U+1D504 will not bin inadvertently changed to bold, while the other characters will.

In any case, since you are specifying the character U+1D49C explicitly (not just `A`), the `mathvariant` and `data-mjx-variant` won't change the result.  So you get the font's U+1D49C character, which for the MathJax fonts is the Roundhand version, not the Chancery one.

Note that MathML-Core has removed the `mathvariant` attribute from its specification, except for the `mi` element, where only `mathvariant="normal"` is allowed (to avoid the automatic italicization that is done for single-character content).  See the [mi](https://w3c.github.io/mathml-core/#the-mi-element) section of the specification.  Unfortunately, that means you can't use `<mi data-mjx-variant="-tex-calligraphic" mathvariant="script">A</mi>` to get this to work in both MathML-Core and MathJax.

The MathML-Core documentation notes that the issue exists (in the second note of [this section](https://w3c.github.io/mathml-core/#new-text-transform-mappings) of the specification).  It suggests two different potential solutions, both being font dependent.  The first is to use variant selectors U+FE00 and U+FE01 to specify Chancery and Roundhand respectively.  I don't know whether browsers actually implement this or not; testing in Safari, Chrome, and Firefox on  MacOS suggests they do not.  Also, for `<mi>&#x1D49C.</mi>`, I get the Chancery version (from STIX2) in Firefox and Chrome, but the Roundhand version in Safari.  As I said, it is font dependent.  In any case, MathJax doesn't support the variant selectors, either.

The second suggestion is to use font features and the `font-variant-alternatives` CSS property, but again, that is font dependent, and MathJax doesn't support that, either.  I haven't checked what the browser support for that is.

So there seems to be no direct way to reliably get both `\mathscr` and `\mathcal` to work in MathML-Core.  A cross-browser solution that works with both MathML-Core and MathJax seems out of reach at the moment.

In any case, MathJax is producing the correct output for the MathML you are using.

**Comment by physikerwelt** [comment]
Thank you for enlightening me! In general, this makes a lot of sense. However, this brings one backdoor to my mind. 

> So there seems to be no direct way to reliably get both \mathscr and \mathcal to work in MathML-Core. A cross-browser solution that works with both MathML-Core and MathJax seems out of reach at the moment.

We don't have \mathscr as an option. It's not safelisted in the texvc grammar. Is there a way (maybe via an input filter) to make MathJax display \mathcal like \mathsrc?

**Comment by dpvc** [comment]
> Is there a way (maybe via an input filter) to make MathJax display `\mathcal` like `\mathsrc`?

Well, you could replace the Roundhand script characters by the Chancery ones in MathJax's font definitions. That can be done in the MathJax startup `ready()` function as follows:

``` js
window.MathJax = {
  remapChars(v1, v2, base, map, font) {
    const c1 = v1.chars;
    const c2 = v2.chars;
    for (let i = 0; i < 26; i++) {
      const data1 = c1[map[i] || base + i] || [];
      const data2 = c2[0x41 + i];
      if (data1.length === 0) c1[base + i] = data1;
      [0, 1, 2].forEach(j => data1[j] = data2[j]);
      data1[3] = {...data2[3], f: font, c: String.fromCharCode(0x41 + i)};
    }
  },
  startup: {
    ready() {
      MathJax.startup.defaultReady();
      const variant = MathJax.startup.document.outputJax.font.variant;
      const map = {1: 0x212C, 4: 0x2130, 5: 0x2131, 7: 0x210B, 8: 0x2110, 11: 0x2112, 12: 0x2133, 17: 0x211B};
      MathJax.config.remapChars(variant.normal, variant['-tex-calligraphic'], 0x1D49C, map, 'C');
      MathJax.config.remapChars(variant.normal, variant['-tex-bold-calligraphic'], 0x1D4D0, {}, 'CB');
    }
  }
};
```

This replaces the original `script` (Roundhand) data with the calligraphic (Chancery) character definitions, so that the Unicode Math Alphanumeric script characters will be displayed as Chancery characters.  That means the Roundhand variant is no longer available.  I think that is what you were asking for.

**Comment by physikerwelt** [comment]
This exactly matches what I understand was desired. Thank you so much.

**Comment by dpvc** [comment]
@physikerwelt, the major change is that, because the v4 fonts have much greater character coverage, they are broken down into smaller chunks so that you don't have to load all the data for all the characters even if you are only using a few of them, and so ranges of characters will be loaded dynamically when they are needed.  That is not something you might have tied to this, but that is where the problem is occurring.

Most of the math variants are now in separate dynamically loaded files, and in particular, the calligraphic and script characters are dynamically loaded.  So the configuration I gave you above doesn't actually have access to the data for the calligraphic or script characters when it runs in v4, and that code doesn't take the dynamic nature of those ranges into account.

One solution would be to force that data to load up front and then do the remapping.  Here is a configuration that does that:

``` js
MathJax = {
  remapChars(v1, v2, base, map, font) {
    const c1 = v1.chars;
    const c2 = v2.chars;
    for (let i = 0; i < 26; i++) {
      const data1 = c1[map[i] || base + i] = [0, 0, 0, {}];
      const data2 = c2[0x41 + i];
      [0, 1, 2].forEach(j => data1[j] = data2[j]);
      data1[3] = {...data2[3], f: font, c: String.fromCharCode(0x41 + i)};
    }
  },
  startup: {
    async pageReady() {
      const font = MathJax.startup.document.outputJax.font;
      const fontClass = font.constructor;
      await Promise.all([
        font.loadDynamicFile(fontClass.dynamicFiles.calligraphic),
        font.loadDynamicFile(fontClass.dynamicFiles.script)
      ]);
      const variant = font.variant;
      const map = {1: 0x212C, 4: 0x2130, 5: 0x2131, 7: 0x210B, 8: 0x2110, 11: 0x2112, 12: 0x2133, 17: 0x211B};
      MathJax.config.remapChars(variant.normal, variant['-tex-calligraphic'], 0x1D49C, map, 'C');
      MathJax.config.remapChars(variant.normal, variant['-tex-bold-calligraphic'], 0x1D4D0, {}, 'CB');
      await MathJax.startup.defaultPageReady();
    }
  }
};
```

We use the `pageReady()` function rather than the `ready()` function in this case because the loading of the dynamic files is asynchronous, and `pageReady()` is asynchronous while `ready()` is not.  Note that this will *always* load the script and calligraphic character data, whether they are needed or not.

An alternative is to hook into the function that loads the dynamic ranges and check when the script ranges are loaded, and when they are, load the calligraphic range and use them to replace the script values.  That would use something like

``` js
MathJax = {
  remapChars(v1, v2, base, map, font) {
    const c1 = v1.chars;
    const c2 = v2.chars;
    for (let i = 0; i < 26; i++) {
      const data1 = c1[map[i] || base + i] = [0, 0, 0, {}];
      const data2 = c2[0x41 + i];
      [0, 1, 2].forEach(j => data1[j] = data2[j]);
      data1[3] = {...data2[3], f: font, c: String.fromCharCode(0x41 + i)};
    }
  },
  startup: {
    pageReady() {
      const font = MathJax.startup.document.outputJax.font;
      Object.assign(font, {
        _loadDynamicFile_: font.loadDynamicFile,
        async loadDynamicFile(dynamic) {
          await this._loadDynamicFile_(dynamic);
          if (dynamic.file === 'script') {
            await this._loadDynamicFile_(this.constructor.dynamicFiles.calligraphic);
            const variant = font.variant;
            const map = {1: 0x212C, 4: 0x2130, 5: 0x2131, 7: 0x210B, 8: 0x2110, 11: 0x2112, 12: 0x2133, 17: 0x211B};
            MathJax.config.remapChars(variant.normal, variant['-tex-calligraphic'], 0x1D49C, map, 'C');
            MathJax.config.remapChars(variant.normal, variant['-tex-bold-calligraphic'], 0x1D4D0, {}, 'CB');
          }
        }
      });
      return MathJax.startup.defaultPageReady();
    }
  }
};
```

instead.
