### ISSUE TITLE
MathJax 4.0 rendering in iframe

### ISSUE THREAD

**Issue by bjones1** [mathjax/MathJax#3309]
### Issue Summary

In MathJax 3.x, math renders correctly in an iframe. In MathJax 4.0.0-beta 7, it does not.

MathJax 3.2.2:
![image](https://github.com/user-attachments/assets/ad3d5f79-f536-4a97-a63d-e9713b906feb)

MathJax 4.0.0 beta 7:
![image](https://github.com/user-attachments/assets/9b3114bb-ae09-41b5-b3c1-3c428452d871)

### Steps to Reproduce:

Load the HTML file shown at the bottom of this issue in a browser (download it [here](https://gist.githubusercontent.com/bjones1/64630a16473436307767109b0c04fd3d/raw/0310714313d3042ed39d46ed40d0a5b81c80742d/test.html)). The MathJax version to use can be easily changed by commenting/uncommenting the appropriate `<script>` tag.

### Technical details:

* MathJax Version: 3.2.2 (correct) / 4.0.0-beta 7 (incorrect)
* Client OS: Windows 11 Education Version 10.0.26100 Build 26100
* Chrome Version 131.0.6778.70 (Official Build) (64-bit)

I am using the following MathJax configuration:

``` js
MathJax = {
    tex: {
        inlineMath: [['$', '$'], ['\\(', '\\)']]
    },
    svg: {
        fontCache: 'global'
    }
};
```

and loading MathJax via

(working)
``` html
<script type="text/javascript" id="MathJax-script" async
src="https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-chtml.js"></script>
```

(failing)
``` html
<script type="text/javascript" id="MathJax-script" async
src="https://cdn.jsdelivr.net/npm/mathjax@4.0.0-beta.7/tex-chtml.js"></script>
```

### Supporting information:

 * See the attached `test.html` file for a demo.
 * Screenshots: see above.
 * Browser console window: no errors

### HTML used
``` html
<!DOCTYPE html>
<html>
    <head>
        <title>MathJax in iframe</title>
        <script>
            MathJax = {
                tex: {
                    inlineMath: [['$', '$'], ['\\(', '\\)']]
                },
                svg: {
                    fontCache: 'global'
                }
            };
        </script>
        <!-- <script type="text/javascript" id="MathJax-script" async
        src="https://cdn.jsdelivr.net/npm/mathjax@4.0.0-beta.7/tex-chtml.js"></script> -->
        <script type="text/javascript" id="MathJax-script" async
        src="https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-chtml.js"></script>
    </head>
    <body>
        <iframe
            srcdoc="<!DOCTYPE html>
            <html>
                <body>
                    <p>$\frac{a}{b}$</p>
                    <script>setTimeout(() => parent.window.MathJax.typesetPromise([document.body]), 1000)</script>
                </body>
            </html>"
        >
        </iframe>
    </body>
</html>
```

**Comment by dpvc** [comment]
The version 3 result is not actually MathJax output, it is the browser's native MathML rendering of what is supposed to be the hidden MathML for screen readers.  The actual typeset math produced by MathJax requires CSS that is not being set within the iframe, and so both doesn't hide the MathML and doesn't show the typeset results (the characters are inserted using `content` CSS rules).  Version 4 doesn't have the hidden MathML on by default, and uses actual character content rather than `content` CSS, which is why you are seeing the difference between the two.

Because MathJax is loaded in the parent frame, the CSS is being inserted into the parent document, not the iframe document.  This is true in both versions, but the differences discussed above are what account for the different (both incorrect) outcomes you are seeing.

MathJax is not intended to be used in the way you are trying to use it.  You need to load MathJax within each iframe where you are using it in order to have it manage the CSS in the iframes correctly.

You might be able to get away with it if you use SVG output with a local font cache, for most expressions (but not ones with arrays that have vertical or horizontal lines, for example, which use CSS to set their size).

**Comment by bjones1** [comment]
@dpvc, thank you for the rapid response and for your explanation. That certainly makes sense. I assume there's no easy way to load just the MathJax CSS on a per-frame basis? If not, I'll instead load MathJax in each iframe where it's needed. Thanks also for your tireless effort in making mathematics so accessible on the web; I really appreciate it.

**Comment by bjones1** [comment]
I'm closing this; supporting CSS on a per-frame basis is (I'm guessing) very low on the priority list. Thanks again for your help, @dpvc!

**Comment by dpvc** [comment]
> I assume there's no easy way to load just the MathJax CSS on a per-frame basis?

Well, you can get the CSS.  Here is an example that does that:

``` html
<!DOCTYPE html>
<html>
    <head>
        <title>MathJax in iframe</title>
        <script>
            MathJax = {
                tex: {
                    inlineMath: [['$', '$'], ['\\(', '\\)']]
                },
                svg: {
                    fontCache: 'local'
                },
                startup: {
                  typeset: false,
                  ready() {
                    MathJax.startup.defaultReady();
                    for (const iframe of document.getElementsByClassName('mathjax-iframe')) {
                      MathJax.config.initFrame(iframe);
                    }
                  }
                },
                initFrame(iframe) {
                  const document = iframe.contentDocument;
                  if (document.readyState === 'complete') {
                    MathJax.config.typesetFrame(iframe);
                  } else {
                    document.addEventListener('load', () => {
                      MathJax.config.typesetFrame(iframe);
                    }, true);
                  }
                },
                typesetFrame(iframe) {
                  const document = iframe.contentDocument;
                  const jax = MathJax.startup.document.outputJax;
                  MathJax.startup.promise = MathJax.startup.promise.then(() => {
                    jax.clearCache();
                  });
                  MathJax.typesetPromise([document.body]).then(() => {
                    const sheet = MathJax.chtmlStylesheet().cloneNode(true);
                    const style = document.getElementById(sheet.id);
                    if (style) document.head.removeChild(style);
                    document.head.append(sheet);
                  });
                }
            };
        </script>
        <script type="text/javascript" id="MathJax-script" async
                src="https://cdn.jsdelivr.net/npm/mathjax@4.0.0-beta.7/tex-chtml.js"></script>
    </head>
    <body>
	<iframe class="mathjax-iframe"
	    srcdoc="<!DOCTYPE html>
	    <html>
	        <body>
	            <p>$\frac{a}{b}$</p>
	        </body>
	    </html>"
	>
        </iframe>
                <iframe class="mathjax-iframe"
            srcdoc="<!DOCTYPE html>
            <html>
                <body>
                    <p>$\sqrt{1-x^2}$</p>
                </body>
            </html>"
        >
        </iframe>

    </body>
</html>
```

It shows how to make it work in two separate iframes as well.  But the CSS is not the only problem, as there are other references to the window and document objects where MathJax will use the outer ones rather than the ones for the iframe.  The contextual menu is one of them, and if you try to use the menu on the equations in the iframe, it will not work (and will throw an error in the console window).  But perhaps you don't need the menu for your situation and can disable it.

Separating out those references would be possible, but as you say, it is not a high priority at the moment.  Something to keep in mind, however, for a future update.

**Comment by bjones1** [comment]
Thank you for your help! I'd like my users to have access to the context menu, so I'll forgo this approach for now.
