### ISSUE TITLE
Expose the content of <annotation-xml>/<annotation> to the "Show Math As" menu

### ISSUE THREAD

**Issue by fred-wang** [mathjax/MathJax#357]
The <semantics> element is often used by generators to provide the source code of a formula in an alternative syntax (StarOffice Math, content MathML, LaTeX, etc). It could be useful to make the source code available via the "Show Math As" menu so that it can be transfered to other applications.

**Comment by limeb** [comment]
@fred-wang could you post or link a simple example demonstrating this.

I am trying to display Mathematiac's InputForm in the right click menu, but its unclear from reading the Wiki if this was done/made.

**Comment by dpvc** [comment]
@limeb, Fred is no longer working on the MathJax project, so I don't think you will get an answer from him.

The feature was added to MathJax, so if you are producing math in the MathML format, you should be able to include annotations in any number of other formats.  For example, you could use

```
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <semantics>
    <mrow>
      <mi>sin</mi><mo>(</mo><mi>x</mi><mo>)</mo>
    </mrow>
    <annotation encoding="application/x-tex">\sin(x)</annotation>
    <annotation encoding="Maple">sin(x)</annotation>
  </semantics>
</math>
```

to allow the math to be displayed in TeX and Maple formats (these appear in the Show Math As -> Annotations -> TeX and Show Math As -> Annotations -> Maple menus).  These formats work out of the box because they are listed in the default annotation types (see [above](https://github.com/mathjax/MathJax/issues/357#issuecomment-18848447)).  If you wanted to add Mathematica InputForm annotations, you would need to configure the MathMenu to look for those.

For example, you can add

```
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  MathMenu: {
    semanticsAnnotations: {
      Mathematica: ["InputForm"]
    }
  }
});
</script>
```

to your page just *before* the script that loads MathJax.js itself, and then use

<math xmlns="http://www.w3.org/1998/Math/MathML">
  <semantics>
    <mrow>
      <mi>sin</mi><mo>(</mo><mi>x</mi><mo>)</mo>
    </mrow>
    <annotation encoding="application/x-tex">\sin(x)</annotation>
    <annotation encoding="Maple">sin(x)</annotation>
    <annotation encoding="InputForm">Sin[x]</annotation>
  </semantics>
</math>

within your document to add the InputForm annotation to the math.  This will then be available in the annotations submenu, along with the other two formats.

Hope that does what you need.

**Comment by limeb** [comment]
Thank you this is way easier then I would have guessed!  Here is a complete example for anyone looking to do the same thing.  Took me a second to realize the cdn I was using was down.

```
<!doctype html><script type="text/x-mathjax-config">
MathJax.Hub.Config({
  MathMenu: {
    semanticsAnnotations: {
      Mathematica:["Mathematica"]
    }
  }
});
</script><script type="text/javascript" async
  src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML">
</script>
<math xmlns='http://www.w3.org/1998/Math/MathML'>
 <semantics>
 <mrow>
  <mi>sin</mi>
  <mo>&#8289;</mo>
  <mo>(</mo>
  <mi>x</mi>
  <mo>)</mo>
 </mrow>
 <annotation encoding="Mathematica">Sin[x]</annotation>
 </semantics>
</math>
```
