### ISSUE TITLE
whitespace at the start/end of mtext elements is lost on rendering

### ISSUE THREAD

**Issue by hubgit** [mathjax/MathJax#417]
White space at the start or end of `mtext` elements (at least) is being lost when rendered.

For example, `<mtext> and </mtext>` is rendered as "and" rather than " and ".

Here's a live example: http://fiddle.jshell.net/hubfiddle/Evwhj/show/light/

**Comment by abinash18** [comment]
Is there an option to disable this?
If not what part of the JS can I alter to stop this behavior. I am using wolfram's MathML output and wolfram dose not respect the MathML specification (see Section 2.1.7)

**Comment by dpvc** [comment]
@abinash18, no there is no option to disable this, as that is what the specification requires.

If you are getting the MathML from Wolfram as a serialized MathML string, then you could use

``` javascript
mathml.replace(/<mtext>( +)/, (match, spaces) => '<mtext>' + spaces.replace(/ /g, '\u00A0'))
      .replace(/( +)<\/mtext>/, (match, spaces) => spaces.replace(/ /g, '\u00A0') + '</mtext>')
```

If you want to retain multiple internal spaces as well, you could just do 

``` javascript
mathml.replace(/<mtext>(.+)<\/mtext>/, (match, text) => '<mtext>' + text.replace(/ /g, '\u00A0') + '</mtext>')
```

Otherwise, the code that does it is this line:

https://github.com/mathjax/MathJax-src/blob/41565a97529c8de57cb170e6a67baf311e61de13/ts/input/mathml/MathMLCompile.ts#L247

You could use a `startup.ready()` function in your configuration to override this method of the `MathMLCompile` object.
