### ISSUE TITLE
Mathjax and GWT

### ISSUE THREAD

**Issue by tarobins** [mathjax/MathJax#508]
I have been investigating an issue with using the MathJax Queue from GWT-based java code.  In particular the line 

$wnd.MathJax.Hub.Queue(["Typeset",$wnd.MathJax.Hub,element]);

would not work from within GWT code.  Using such a line results in the error 

com.google.gwt.core.client.JavaScriptException: (Error) @com.....mathtest.client.MathTest::layoutMath(Lcom/google/gwt/dom/client/Element;)([JavaScript object(4)]): Can't make callback from given data

This issue has been previously reported here: http://t2774.codeinpro.us/q/50812a4d4f1eba38a41e20b7 , among other places.  However, the solution proposed there is not optimal, because the MathJax queue is not used, resulting in unpredictable behaviour. 

After some investigation of the problem, I determined the problem lie in the USING function at the line 

} else if (args instanceof Array) {

Even though args is an array, instanceof is returning false.

This problem with instanceof is probably the one reported here http://perfectionkills.com/instanceof-considered-harmful-or-how-to-write-a-robust-isarray/ due to the way GWT uses frames.  

I have found that replacing the instanceof call above with the code 

Array.isArray(args) 

solves the problem.  

I'm not that familiar with web development, mathjax, open source development, and I'm not sure if such a change will cause problems in some browsers.  If I can be of some help in fixing this bug, please let me know.

**Comment by Sjiep** [comment]
I have ran into the same issue as the OP. The final solution that @tarobins came up with is not sufficient enought for me, because I also need to call specific Java functions from the MathJax queue. This is however only possible directly from Java native methods and not from plain Javascript.

On the other side, the fix that @tarobins provides in his initial post actually works for me, and still allows me to call Java functions from Java native methods containing Javascript.

Would it be possible to have this change in code, i.e. replacing
    
    } else if (args instanceof Array) {

with

    Array.isArray(args)

in the `MathJax.js` file. This small change in code that I require prevents me from being able to use the MathJax CDN and requires met to apply the fix on every MathJax release.

Robert

**Comment by pkra** [comment]
@Sjiep please file a separate issue with more details.
