### ISSUE TITLE
clearing listeners

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#693]
This feature request came up on the user group, cf. https://github.com/mathjax/MathJax-docs/wiki/How-to-stop-listening-or-un-register-from-a-messagehook

As per Davide: "there probably should be an API".

**Comment by pkra** [comment]
I'm not sure where and how this should be documented. @dpvc can you make a suggestion?

**Comment by dpvc** [comment]
It probably belongs in `hub/api.rst` where the `Register` commands are documented.  There are now `UnRegister` commands that correspond to each.  Note that the `Register` commands now return an object to be passed to the `UnRegister` commands.

There is also a new `RemoveHook()` method in `api/signal.rst`, and there is a new `removeHook()` in `api/ajax.rst`, through that one is intended for internal use (like `addHook()`), but I could see including it since `LoadHook()` is already there, and `removeHook()` undoes that.

**Comment by dpvc** [comment]
==> In Testsuite

API/Hub/remove-hooks.html
