### ISSUE TITLE
Fraction line thickness - printing

### ISSUE THREAD

**Issue by ErnWong** [mathjax/MathJax#722]
Hello,
This isn't important actually, and I'm not sure if this is an expected behaviour, but the fraction lines are sometimes a bit thicker than the other (especially for fractions inside fractions) on the screen (Google Chrome):
![frac chrome screen](https://f.cloud.github.com/assets/2609018/1981205/ab52a102-83d2-11e3-8f9a-32eb65a93a8f.png)
http://www.mathjax.org/demos/tex-samples/

Then, when printing it, the thicker lines are more obvious:
![frac chrome print](https://f.cloud.github.com/assets/2609018/1981214/ec3ec678-83d2-11e3-9a16-00264318b6db.png)

It doesn't just show up in fractions-inside-fractions though:
![frac chrome print 2](https://f.cloud.github.com/assets/2609018/1981220/3c34bfa2-83d3-11e3-9527-96039e247acb.png)

I've printed that page out and it's the same as previewed.

It gets a bit weird with small font sizes:
![frac chrome print 3](https://f.cloud.github.com/assets/2609018/1981271/7d9e9ef8-83d4-11e3-9922-019cc52cf6f1.png)

(Size is about 9pt)

I've also checked the preview with the actual printed page.

**Comment by LukasDrude** [comment]
For everybody who encounters this issue. Say you have a presentation tomorrow and really want all fractions to appear at all costs, you can use your own definition of fractions (with thicker lines):
```
\begin{align}
    \genfrac{}{}{1pt}{0}{a+b}{c+d}
\frac{a+b}{c+d}
```

**Comment by kevinc1984** [comment]
I'm my case, I'm actually getting zero width fraction lines. This only happens in IE (I'm using 11 in this case). This is at zero zoom level:

![image](https://cloud.githubusercontent.com/assets/4650870/13508735/36cfb430-e156-11e5-8fd9-9b2cf9994d72.png)

![image](https://cloud.githubusercontent.com/assets/4650870/13508803/8c40c86e-e156-11e5-92ac-d58dcfb6cf92.png)

**Comment by pkra** [comment]
@kevinc1984 without a live sample exhibiting the problem, there's not much to say, I'm afraid.

**Comment by kevinc1984** [comment]
@pkra Thanks for the reply. Here's a link that exhibits the issue consistently (in IE 11 at least). I am desperate for some sort of reliable fix!

**Comment by dpvc** [comment]
@kevinc1984, you seem to be using MathJax v2.2, which is quite old.  The current version is 2.6.  The results have been improved in later versions.  In particular, the HTML-CSS and CommonHTML output now use units of px rather than em for the rulings, and that should provide better results.  I would recommend CommonHTML, which is faster than SVG, and should produce results whose quality is more in line with the rest of the text.

**Comment by kevinc1984** [comment]
That's definitely a great idea to move away from SVG.

Just for the record, I did do an upgrade to the latest version of 
mathjax to see if this was fixed for SVG, but it was not. So to fix this 
I will likely move away from SVG, but I'd love to know why it wasn't 
working right for this format, or there is a fix for it! :) Thanks!

**Comment by dpvc** [comment]
The v2.2 HTML-CSS output will not be any better, so you will need to update to v2.6 to get the improvements.

As for why it happens, it is the issue I discussed above.  How the horizontal line is rendered depends on how its position relates to the pixel grid.  Some positions will render as a one pixel line, and some will drop the line (at least in IE11, apparently).  Being 1 px wide does not fix that, because if the line where requested at a position of 1/2 pixel, then 1px thick would mean the line is 1/2 pixel in one row of pixels and 1/2 in the next.  It may be that the renderer decides that 1/2 pixel is not to be filled, so drops both halves.  Anti-aliasing may affect that as well, as each half is not a full-black pixel, but some grey level, which might make it less likely to be retained.  I have not been impressed with the IE implementation of SVG, so it would not surprise me.

**Comment by kevinc1984** [comment]
David,

Thank you for this thoughtful response. I agree with your assessment, 
particularly with IE. Can they ever just get everything right? The other 
primary browsers out there never have these kind of troubles, and "Edge" 
was supposed to reset the game for IE.

I would assume that changing any sort of code in MathJax might actually 
make things worse in the browsers that do "get it right" because you may 
begin adding thickness to these lines that should not exist, just to 
cause one browser to show a 1px line.

**Comment by ifyousayso** [comment]
Hi!

I have this issue as well and I think I have a solution that (probably) worked for me.. can't test it since I have no printer, but it should work. The worrying part for me is that some fraction lines are not drawn in print preview and I want to make sure the line is visible.

.tex .mfrac > span > span:last-child > span:first-child {
	border-top-width: .4mm !important;
}

The above code, in a print.css file, should force a certain fraction line width for printing. So far, I've only noticed the class mfrac in my code, so it may not work for other fractions or fractions within fractions, but it's better than nothing. (0.4 / 25.4) * 96 = 1.5118px on screen (preview) and 4 to 5 dots on paper at 300DPI.
