### ISSUE TITLE
Allow bundling with browserify / provide an npm module

### ISSUE THREAD

**Issue by andrenarchy** [mathjax/MathJax#951]
It would be great if MathJax could be used with npm and especially with browserify (which consumes npm modules). On production systems it is common to bundle all javascript code into one file in order to reduce the number of HTTP requests (e.g., with browserify). However, MathJax tries to download at least another javascript file (a config).

So: is there a way to bundle all required MathJax js code for a specific config in one file? A proper npm module would already be a huge improvement in this direction.

**Comment by adius** [comment]
Just wanted to let you know that I published mathjax as a npm module (name: mathjax)
I'll gladly hand over the module name when you (finally) maintain a real node module. ;-)

**Comment by andrenarchy** [comment]
@adius: thx! However, adding a package.json is not enough for actual bundling with browserify. In order to support this, MathJax would have to stop downloading files on demand. Instead, the wanted functionality should be pulled in with `require` calls. Until now, MathJax is the only package where I failed with my browserify skills. ;) @pkra: are there any advances in this direction?

**Comment by adius** [comment]
Yeah, i know. …at least now I can load it like `/node_modules/mathjax/MathJax.js?config=AM_HTMLorMML` in my html files, I don't need to check it into my repo and I don't have to use bower anymore! So already a huge improvement =P

**Comment by pkra** [comment]
@adius this does not make sense to me. MathJax does not work in a nodejs setting. What problem are you trying to to solve? 

I also find it extremely odd that you did not bring it up for discussion with us before making your decision.

@andrenarchy no news. As I wrote before, the reasonable approach at this point is to pre-build a single-file build that you feed into your workflow. If you want to learn more about that, follow the links I posted earlier. PR's to make those tools better are obviously welcome.

If we end up working on something along those lines, then it will be v3.0 at the earliest since it will require as significant re-write. However, I have doubts that full "browserificiation" will gain much. I doubt any developer wants to ship all of MathJax in a single file (18MB right now). Most likely, they'll want to cut down MathJax functionality and could easily build a single-file version while they're at it.  (Of course, even with 1 input, 1 output, 1 font they still have 0.5MB to ship, even on pages where MathJax would need a fraction of that.)

**Comment by nschloe** [comment]
> Most likely, they'll want to cut down MathJax functionality and could easily build a single-file version 
> while they're at it.

One functionality we'd more more than glad to drop is support for IE6 & its friends from the browser netherworld; I wonder how much that would save.

> they still have 0.5MB to ship, even on pages where MathJax would need a fraction of that.

I suppose we have to dig through the MathJax code to find out why we can't a priori determine which parts of MathJax are actually needed.

**Comment by pkra** [comment]
>  I wonder how much that would save.

That's not how MathJax works.

> I suppose we have to dig through the MathJax code to find out why we can't a priori determine which parts of MathJax are actually needed.

The documentation or the grunt cleaner is probably an better starting point.

**Comment by adius** [comment]
Sorry for taking action so fast. I was just really astonished that nobody had reserved the mathjax slug on npm yet and so I just quickly published to it so nobody with evil intentions would take it.

The problem this is solving now is:
1. You don't want to commit MathJax into a repo because it's much too large, you might not want to use a CDN either because it's not accessible offline and you might want to host everything yourself for privacy reasons
2. This means you need a package manager. For compiled frontend packages you'd normally go with bower but because almost every frontend library is now also available as commonjs version you prefer browserify and using bower for just one package is kind of ugly.

Solution: Use npm to deliver a compiled version of mathjax which can get loaded in a script tag in your website.

…and voila, works like a charme =)

**Comment by pkra** [comment]
This is mixing up a number of things (again); it's not helpful. 

If all you wanted was some way of adding MathJax as a dependency, you could have just used a tarball, e.g., as we do in https://github.com/mathjax/MathJax-node/blob/master/package.json.

Again, the very least would have been to bring it up for discussion. This way, it just causes unncessary conflict.

**Comment by brettz9** [comment]
ES6 modules (with say Rollup) nowadays would I think be a great way to go now...

**Comment by dpvc** [comment]
MathJax v3 is now distributed via npm, and can be webpacked.
