### ISSUE TITLE
HTML-CSS output: line-breaking with label

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#957]
The HTML-CSS output has trouble with labeled rows. Here's an example http://codepen.io/pkra/pen/dPyrKV

**Comment by pkra** [comment]
Two notes on this bug:

* stupid me for not describing the problem. @dpvc 's reply indicates that the label was pushed out of the container. That does not seem to be the case; instead, both HTML-CSS and SVG output make the label overlap with the content when linebreaking is off (see the codepen example). With line-breaking, the labeled example looks good now (so the table problem @dpvc described seems resolved here)
* However: linebreaking leads to funky behavior in the second equation in that codepen. For HTML-CSS I get a Math Processing error `Error: g.bbox is undefined`. With SVG the equation disappears -- not even an error :-(

Not sure if we should rename this or close and open something new. I'm opening a meta-issue for label-related bugs.

**Comment by dpvc** [comment]
MathJax v2.5 tried to fix the inconsistency between HTML-CSS and SVG output in handing how the situation where the equation+label width exceeded that of the container.  (It used to be that SVG had the label overlap the equation, while HTML-CSS cause the width of the equation to exceed that of the container.)  You requested that both extend the container, which is what was supposed to have been implemented. The fix has a bug, however, where an incorrect scaling factor was used, so now both overlap rather than both extend the container.

The table problem is not resolved.  Cells still break only to the full width of the container, not the space allocated of that column.

The processing error in the second example is due to the duplicate ID of `diff.operator` in the final `<mrow>` of the two equations.

**Comment by pkra** [comment]
Thanks for clarifying! To organize, let's make this bug about the table line-breaking issue and use #1189 for the overlapping labels problem; does that sound ok?

**Comment by dpvc** [comment]
The table issue is independent of labels, so I'd like to see it have an issue that is titled with something involving tables line breaking, and it is not restricted to HTML-CSS but affects all the output formats (except NativeMML).  So I'm thinking it might be good to start a fresh issue for it that refers back to this one if needed.

**Comment by pkra** [comment]
Just adding this to the milestone so that it is one some milestone. Feel free to move to an appropriate milestone.

**Comment by dpvc** [comment]
In my last comment above, I suggested making a new issue for the table-cell-breaking issue (which affects HTML-CSS, CHTML, and SVG).  The label portion of this issue has been fixed, and I would prefer the fresh issue so that it is easier to identify the portion of the problem that is actually still in effect.  I'm removing from 2.7, since I don't plan to fix it in that release (it will take some substantial rewriting of the table code).

**Comment by pkra** [comment]
Thanks! I've opened #1557. Does this mean we can close this issue? Also, which milestone does this issue belong to?

**Comment by dpvc** [comment]
This was fixed with the rewriting of the label code in 2.6 (commit d127b1b on 16 July 2015), so I think it can be closed, along with several other label issues listed in the meta issue #1191.

**Comment by pkra** [comment]
>  I think it can be closed, along with several other label issues listed in the meta issue #1191.

That's referring to #1031, #596, #1189, right?

**Comment by dpvc** [comment]
Actually, I think it also includes #1190 and #961 as well.  The `minlabelspacing` is now only on one side of the label (instead of both), so I think that takes care of #1190 (though the tracker discusses other issues as well, so I don't know if you want to keep it open, but personally, I think they deserve new issues if you do), and the overlapping no longer occurs, so I think #961 is also taken care of.  I still think one should use `displayIndent` there, but I've made it work the way you asked (while still working properly if you *do* use `displayIndent`).  I have a lab page that lets you test out different indent and alignment configurations to see how they work.  I could make that available to you if you want.  Perhaps we need a repo for such things?

**Comment by pkra** [comment]
Thanks, Davide! I've closed/moved the other issues.

> Perhaps we need a repo for such things?

That sounds good. `MathJax-Labs`?

**Comment by dpvc** [comment]
MathJax-Labs is fine.  I have a few that could go there when it is created.
