### ISSUE TITLE
display-align with mtable side-attribute

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#961]
When aligning labels and display-style to the same side, there is overlappping (both HTML-CSS and SVG output); example http://jsbin.com/gilece/3/edit

I'm not sure if this is expected behavior, a shortcoming of the spec or just a bug but it seems to me that there should be padding (when there's enough space).

**Comment by dpvc** [comment]
> I'm not sure what later equations have to do with this.

What I meant by this is that when equations are aligned left or right, they are all supposed to be aligned at the same location.  The presence of absence of equation numbers isn't supposed to affect that, so that equations with alignment to the left and equations numbers should look like

```
       x1 = 1 + 2x

some text

       x2 = x1 - 3

some text

(1)    x3 = x2 + x1

some text

        x1 + x2 + x3 = 5

more text
```

Not

```
x1 = 1 + 2x

some text

x2 = x1 - 3

some text

(1)    x3 = x2 + x1

some text

x1 + x2 + x3 = 5

more text
```

The labels are not part of the equation, and alignment and indenting are not supposed to apply to them.  Because MathJax doesn't know the size of labels later in the page when it typesets the ones earlier in the page, it can't reserve the proper space itself for the earlier equations, so the page author needs to set the `displayIndent` to accommodate the largest label the is to be used.

Prior to version 2.6, if you didn't do that, you would get overlapping, as described here.  Since 2.6, you get the second example above (which I think is bad layout, but I suppose it is better than overlapping, even though overlapping would have encourage you to set `displayIndent` to get better typesetting).

**Comment by dpvc** [comment]
> If indentation is set in the core configuration, I expect the entire expression to be indented (not just "past the label").

The label is not part of the expression, that's the point.  The expression *is* only the part past the label.  That MathML spec alludes to this in the [`mlabeledtr`](http://www.w3.org/Math/draft-spec/chapter3.html#id.3.5.3.1) section, where it says "the label element is not taken into consideration in the table layout for purposes of width and alignment calculations".  Here, I believe that "alignment" refers to horizontal alignment, which (to my mind) includes left alignment with and indenting.  The spec is not clear on how to treat alignment that would cause labels to overlap.  It does talk about `side="leftoverlap"` and `side="rightoverlap"`, but these are vertical overlaps, not horizontal ones, and there is no mention of what `side="left"` and `side="right"` do when there is no enough space.  So it seems to be up to the implementation.

In any case, I think this issue is resolved by the current label implementation.

**Comment by pkra** [comment]
Thanks for the detailed clarification, Davide!

I'll close it as fixed.
