### ISSUE TITLE
v2.5 final bug

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#963]
* [x] finish release checklist
* [x] update documentation
* [x] create `2.5-latest` copy on CDN
* [x] update `latest` branch CDN.
* [x] merge final pull request from `develop` into `master`

**Comment by pkra** [comment]
@dpvc I've created https://github.com/mathjax/MathJax/wiki/Draft-for-what%27s-new-page in case you want to look it over.

**Comment by dpvc** [comment]
A couple of comments:

* I would not include issue 970 or 975 as they are not bugs in 2.4, but bugs that were found in the alpha of 2.5

* For 900, I'd say "Fix `\buildrel` to get TeX class REL instead of ORD" to make it clearer (it sounds like it might be the reverse).

* In 375, there is an error in escaping ``\}``.

* In 982, there is an escaping problem in the Markdown.

* In the AsciiMath section, do you want to mention the update to v2.2 of AsciiMathML?  I know there are other improvements not listed in our tracker (but in the AsciiMath one).

Other than that, looks good.

**Comment by pkra** [comment]
Thanks, Davide. I've updated the doc.

**Comment by pkra** [comment]
Completed.
