### ISSUE TITLE
Problems with the CLA

### ISSUE THREAD

**Issue by alawatthe** [mathjax/MathJax#987]
Today I read the blog post ["A quick stroll around our code repositories"](http://www.mathjax.org/a-quick-stroll-around-our-code-repositories/) on the MathJax blog and got interested in contributing to MathJax. For example with the Grunt/Gulp stuff you mentioned in the blog post. (In fact, I already contributed to MathJax by translating some stuff over at the translatewiki.)

Then I saw that MathJax requires contributors to sign a CLA. So it read what you want me to sign. But from reading the CLA the following questions remained unanswered:

* Why do you need my **phone number/mailing address/real name**?
* Under what circumstances would you contact me on my phone? (The answer is probably "never". So why do you need it?)
* Under what circumstances would you write me a letter/pay me a visit/do something else with my mailing address?
* What is with people who don't have a phone? What is with people like [Vitaly Friedman](https://the-pastry-box-project.net/vitaly-friedman/2014-december-23) (a famous (homeless) web developer and editor-in-chief of Smashing Magazine), who don't have a mailing address? Are they not allowed to contribute?
* Who has access to these information? I mean, I'm getting enough spam these days. I don't need more. (I'm not implying that any one of you is sending spam.)
* How are these information stored (e.g. encrypted or not)?
* What happens if my phone number/mailing address changes? Do I have to provide the new information to you?
* How you verify if the information I gave you are correct? (Or, still correct after some time? See previous problem.)

  * I haven't seen a requirement in the CLA that my information have to be correct. (Ok, ok you could say this is ridiculous, but you started with this legal stuff.)
  * So, do you write me a letter, and call me, to check if they are correct?
  * Or, well if you don't actually care what I write into that form, here you go:
  
  	```
  	I agree to the CLA.
  	
  	Name: John Doe 
    Phone: 0123456789
  	Address:
	1600 Pennsylvania Avenue Northwest
	Washington
	DC 20500
  	```
* Furthermore: while my employer encourages open source work, we have no written "Open Source Contribution Policy". And I don't think I should bother my boss creating one, because some random CLA requires one.

I hope that you don't think of this issue as a random person trolling around, but see how ridiculous at least some parts of your CLA are. Good open source should encourage people to contribute and not scare them away with weird CLAs.

But I'm not here to only complain. I have a few improvement suggestions.

Dropping the CLA
----------------
I have absolutely no problem with the content of the CLA (if I understood the officialese correctly). I am also not against having a CLA. My problem is the meta stuff around the CLA.

But let me suggest to drop the CLA. What was the reason to require it in the first place? Does this reason outweigh the fact, that many possible contributors will not contribute to MathJax because of the CLA?

MathJax wouldn't be the first project to do so. For example, in June 2014 Joyent [removed the node.js CLA](https://www.joyent.com/blog/broadening-node-js-contributions) with the goal of broadening contributions.

They are even calling CLAs an **open source anti-pattern** in that blog post.

Furthermore, the fact, that the Site for the MathJax CLA is copied verbatim from the mentioned [former node.js CLA](http://nodejs.org/cla.html) in many places, together with the many problems I mentioned above, raises the feeling, that the MathJax CLA is not completely thought through in many places...
(I am assuming here, MathJax copied from node.js not the other way round.)

Improving the CLA
-----------------
I understand, if dropping the CLA might not be an option for you. But in this case let me give some improvement suggestions.
Take a look at [Yahoo's CLA](https://yahoocla.herokuapp.com/), which is (at least in my opinion) a more or less ideal CLA.

1. It starts with Human-readable summary of the license
2. The only thing it requires is the Github user name. No phone number, mailing address or real name. They don't even want my email address!
3. They do not ask for my Employer, Employer Contact, Employer Open Source Contribution Policy.
4. It requires you to log in through Github. So they can be sure that the person signing the CLA and the person making the contributions are the same. (This is also something your CLA is missing.)

Adapting the points 2 and 3 would remove all of the problems I mentioned above.

If the MathJax CLA is like the Yahoo CLA I will happily sign it immediately. So yes, I want to give back and contribute to MathJax, but I will not sign the CLA in the current form. And I am pretty sure, that I am not the only person having this opinion.

A happy new year to everyone from a (hopefully) future contributor

P.S.:
Yes, I know this issue is not a software bug in MathJax. But I want to make this discussion public, so mailing you at manager@mathjax.org wasn't an option for me. So please do not close this issue as "invalid".

**Comment by pkra** [comment]
Thanks for sharing your thoughts on the CLA. This discussion would probably fit better on the mathjax-dev mailing list but let me try to respond here. (It's actually the first time somebody has been concerned with the CLA so this might not be a concise as it could be.)

First off, please keep in mind that MathJax team members do not make decisions about legal matters like CLAs or licensing. Also, we are not lawyers and cannot provide legal advice or identify all relevant scenarios that might have affected the decisions.

Second, because of this, the only answer we can give to some questions raised is "because this was the legal advice MathJax received". Revisiting the decisions regarding licensing is currently not planned but is obviously not impossible (it would, however, incur significant cost).

Third, please note that only contributions to the core of MathJax require a CLA (primarily, the jax'es and the core extensions). So, for example, contributions to the dev tools, the docs, and MathJax-node or in the form of non-essential files (like bower.json) do not require a CLA. This decision was made to simplify contributions; it's where almost all contributions come in and where Apache-compatible licensing was considered sufficient protection.

To answer some of your specific questions.

* Re: necessary personal details. I don't think it's set in stone what's necessary but, theoretically, if a contributor cannot provide sufficient information then, yes, we (the team members) are not permitted to merge the code.
* Re: storage of personal information. As is probably obvious, the form feeds into a Google spreadsheet that can be accessed by the project management (myself and some people at the AMS, MathJax managing partner). After confirming the contributor's information, a copy of the finalized CLA is stored with the AMS. The initial confirmation is done by email but alternatives are possible. I'm not sure how frequently it is checked but I think it's quite rarely. As I'm not a lawyer, I cannot tell you what might be legally required here.
* Re: contacting contributors. The main reason to contact a contributor would be to inquire about the contributed code or to check if the information on file is up to date. 
* Re: corporate contributions. Again I'm not a lawyer but I think this is only relevant if the contributor acts as an employee (e.g., they contribute company code not owned by themselves, or contribute as part of their work for that company), that is, it serves to protect the employee from personal liability.
* Re: wording. Save for the non-binding opening (mostly taken, as you point out, from Nodejs's page), the CLA is the [standard Apache CLA](https://www.apache.org/licenses/#clas). MathJax itself is licensed under Apache license and this is the natural CLA to go along with that.

I hope this clarifies things a little and I hope you'll consider contributing. I think, ultimately, this comes down to a question of trust towards the MathJax Consortium, i.e., AMS and SIAM. Naturally, we (the MathJax team) are very biased here :-)

**Comment by alawatthe** [comment]
> Thanks for sharing your thoughts on the CLA. This discussion would probably fit better on the mathjax-dev mailing list but let me try to respond here.

I though about the mailing list, too. But I decided for Github, since I think it is more likely that programmers which are not closely connected to MathJax will see it, too.

>(It's actually the first time somebody has been concerned with the CLA so this might not be a concise as it could be.)

My text wasn't concise either :-)

>[...] Revisiting the decisions regarding licensing is currently not planned but is obviously not impossible (it would, however, incur significant cost).

Not changing the CLA, does not make me too happy apparently. But since there is the next point, this shouldn't matter to much. Therefore I am closing the issue. (I'm just surprised, that dropping some fields in the CLA incurs significant cost. But probably you need to contact a lawyer and that makes it expensive.)

>Third, please note that only contributions to the core of MathJax require a CLA (primarily, the jax'es and the core extensions). So, for example, contributions to the dev tools, the docs, and MathJax-node or in the form of non-essential files (like bower.json) do not require a CLA. This decision was made to simplify contributions; it's where almost all contributions come in and where Apache-compatible licensing was considered sufficient protection.

This is interesting and basically solves my problem. You should also add these information to the CLA page, too.

(I am surprised, that not having to sign the CLA for specific files does not make things overly complicated.)

>To answer some of your specific questions. [...]

So everything is basically as I thought it would be. I just want to pick out a specific point:

> Re: contacting contributors. The main reason to contact a contributor would be to inquire about the contributed code or to check if the information on file is up to date.

Hmm, since there is paragraph 6 in the CLA: *"You are not expected to provide support for Your Contributions, except to the extent You desire to provide support. [...]"* you shouldn't be calling former contributors and ask them about their code. And I would be surprised, if this has ever happened. The only place to discuss code related things should be Github (and perhaps the mailing list). Just create a new issue, @mention the former contributor and perhaps he will contribute again. If he is not contributing again, there is nothing you can do about it.

And storing personal information to check if the personal information is up to date is just weird.



>I hope this clarifies things a little and I hope you'll consider contributing. I think, ultimately, this comes down to a question of trust towards the MathJax Consortium, i.e., AMS and SIAM. Naturally, we (the MathJax team) are very biased here :-)

Yes, it clarifies things. It is not, that I don't trust the MathJax consortium. I am just not too fond of spreading my personal information around the internet. And sometimes I question why I should give them away.

So the grunt/gulp stuff should go on the [https://github.com/mathjax/MathJax-dev/issues](https://github.com/mathjax/MathJax-dev/issues) list, right?

**Comment by pkra** [comment]
> You should also add these information to the CLA page, too.

This is documented at https://github.com/mathjax/MathJax/wiki/Contributor-license-agreement-etc

> (I am surprised, that not having to sign the CLA for specific files does not make things overly complicated.)

It does but we think it's worth it.

> But probably you need to contact a lawyer and that makes it expensive.

Correct.

> you shouldn't be calling former contributors and ask them about their code. 

The scenario I had in mind was somebody questioning the legality of the contribution; in that case, I would expect to reach out to the contributor (if only to hear both sides). 

If somebody really does not want to be in contact with MathJax, then perhaps they should not contribute (and perhaps MathJax should not be accepting such contributions to save both sides the trouble; trust has to go both ways after all). Fortunately, being interested in core development and objecting to the CLA has not coincided so far.

> So the grunt/gulp stuff should go on the https://github.com/mathjax/MathJax-dev/issues list, right?

Yes but you could also post this on this tracker (for greater visibility). [This](https://github.com/pkra/MathJax-single-file) might be interesting.
