### ISSUE TITLE
SVG output baseline alignment problems

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#995]
Similar to #931, SVG output has some baseline alignment issues on Safari 8.

**Comment by pkra** [comment]
This seems to be more widespread. (Changing the title.)

I ran [this gist](https://gist.github.com/pkra/adb4659db446f0c6e30b) through browserstack.com to generate some screenshots.

I see a baseline too high on: IE9/Win7, IE 10/Win8,  IE11/Win8.1, FF30/Win7+8.1+XP, Opera 12.15/OSX, Chrome 36/Win8.1+XP

I see a baseline too low on: Chrome 36/OSX, Nexus 5/Android5, Safari 8.

![android_google-nexus-5_5 0_portrait](https://cloud.githubusercontent.com/assets/426686/5644414/7c3617f6-9663-11e4-97e5-6cca02be173a.png)
![macmav_chrome_36 0](https://cloud.githubusercontent.com/assets/426686/5644418/7c44c044-9663-11e4-8b34-0ba099c5f81a.png)
![macyos_opera_12 15](https://cloud.githubusercontent.com/assets/426686/5644415/7c384f9e-9663-11e4-856a-16b5159d30cc.png)
![win7_firefox_30 0](https://cloud.githubusercontent.com/assets/426686/5644417/7c3f2c1a-9663-11e4-960e-e536f020c877.png)
![win7_ie_9 0](https://cloud.githubusercontent.com/assets/426686/5644413/7c3008ac-9663-11e4-9a22-0c0ed91f696a.png)
![win8_ie_10 0](https://cloud.githubusercontent.com/assets/426686/5644416/7c392b58-9663-11e4-8bd3-7f3582d1889c.png)
![win8 1_chrome_36 0](https://cloud.githubusercontent.com/assets/426686/5644419/7c45c12e-9663-11e4-8fda-247ea76c2e30.png)
![win8 1_firefox_30 0](https://cloud.githubusercontent.com/assets/426686/5644420/7c4a596e-9663-11e4-843b-260aef186ffb.png)
![win8 1_ie_11 0](https://cloud.githubusercontent.com/assets/426686/5644421/7c513518-9663-11e4-9e06-7cee5e6853fe.png)
![winxp_chrome_36 0](https://cloud.githubusercontent.com/assets/426686/5644422/7c51ee04-9663-11e4-8e22-8f231222c2b9.png)
![winxp_firefox_30 0](https://cloud.githubusercontent.com/assets/426686/5644423/7c59d556-9663-11e4-982a-0c38dfef7deb.png)

**Comment by pkra** [comment]
@dpvc is it ok that I've added this to the v2.6 milestone?

**Comment by dpvc** [comment]
Yes.  I want to go through the open issues myself and suggest some other candidates as well, but haven't taken time for that yet.

**Comment by dpvc** [comment]
I have made what I hope to be a fix for this in the `issue995` branch of my fork of MathJax.  What it does is to round up the height and depth of the final expression to the nearest pixel size so that the `vertical-align` that is used to position the formula will be a size that matches the pixels better.  That seems to resolve the situation in the tests that I have looked at.  Of course, this relies on the fact that the initial measurement of pixels-per-ex is accurate, and so it may still be problematic at some magnifications.  But it seems to be better than it was.

For MathJax-node, this may mean you have to be more careful about specifying the ex-height so that it actually matches your use case, otherwise the rounding will not be to the correct pixel size.  I have not really tested it out in that situation yet, but it does better in the browser, where we get reasonably accurate pixel sizes.

**Comment by dpvc** [comment]
==> Merged
