### ISSUE TITLE
2.5: HTML-CSS output and outline styling

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#997]
Due to (I think) #893, the output now gets outlines when tabbing through content (or clicking on it).

The HTML-CSS output on Chrome gets some pretty odd looking outlines. I don't like disabling them but perhaps we can improve them.

**Comment by dpvc** [comment]
You are right, this is due to the `tabindex` added in #893.  The browsers don't seem to be taking the clipping regions into effect when the determine the bounding boxes for the math, which is why the outlines are so strange.  (The HTML-CSS output uses very tall boxes to make it possible to do absolute positioning without having an accurate measurement of the position of the baseline, and that is what is causing the strange outlines on top.)

I suggest we remove the `tabindex` for now and do an accessibility update later (when we do the menus, for example).  We really need to get some input from the accessibility community about what is really needed.

**Comment by pkra** [comment]
FWIW, I think it's only Chrome that's not taking the clipping into account (I tried a recent WebKit build, current FF, IE9-11).

But I'll ask around for alternatives for input.

**Comment by dpvc** [comment]
No, it is in all the browsers I tested.  Here are images from Safari, Firefox, and Chrome.

![safari selection](https://cloud.githubusercontent.com/assets/432782/5651218/8e3acc0c-9673-11e4-8c48-d41a93d7bf82.png)

![firefox selection](https://cloud.githubusercontent.com/assets/432782/5651224/968010a2-9673-11e4-9782-9b8cc00b2121.png)

![chrome selection](https://cloud.githubusercontent.com/assets/432782/5651231/9baf9b60-9673-11e4-9fc6-cf3d75010e7a.png)

Chrome is certainly the worst.  The others seem to take the smallest rectangle containing all the bounding boxes in the selection.  None seem to honor the clipping regions that MathJax has in place.

**Comment by pkra** [comment]
Ah, I missed the overall problem due to the jagged edges in Chrome.

BTW, the outline can be disabled via CSS.  But I'm fine with throwing the tabindex out. I suspect the future menu will be very different anyway.

**Comment by dpvc** [comment]
I'm removing the `tabindex` setting for now.  This is in the `issue997` branch of my fork of MathJax.

**Comment by dpvc** [comment]
=> Merged
